### ISSUE TITLE
"correcting tags" diff view: display #track before title

### ISSUE THREAD

**Issue by azrdev** [beetbox/beets#1057]
feature request:
current view:

    (Similarity: 89.9%) (tracks, album) (2001, US)
     * Prison Song (#0)      -> Prison Song (#1)
     * Drugs (#0)            -> Drugs (#2)

If track numbers would be placed before the title names instead of after them, they would print as one column instead of "jumping around":

     * (#0) Prison Song      -> (#1) Prison Song
     * (#0) Drugs            -> (#2) Drugs

Probably it would be a good idea to fill track numbers to two chars with spaces, so they align cleanly with numbers >=10, too

**Comment by sampsyo** [comment]
Closing in favor of the ongoing UI overhaul in #1685.
