### ISSUE TITLE
fetchart: Minimum width option

### ISSUE THREAD

**Issue by sp00kie** [beetbox/beets#1058]
Hi, 

The fetchart plugin is finding tiny images that are useless for my albums.  Would it be possible to set a minimum image size eith in width/height or in KB.

**Comment by dprus** [comment]
Is this still being worked on? I'd like this feature too. Right now the plug-in is pulling some ugly low-res coverart for my music.

**Comment by tomjaspers** [comment]
Oh right! I was/am waiting on PR #1277 to be merged, considering some work was done there on `ArtResizer`, but I have to admit I totally forgot about this issue (woops).
