### ISSUE TITLE
Restrict bucket definition to a specific field

### ISSUE THREAD

**Issue by Kraymer** [beetbox/beets#1062]
Current distinction year vs alpha bucket is not sound :  
- we're stucked with only one alpha range even if we'd like to have many. For example one for artists, one for albums like :  
  
  ```
  paths:
      singleton: Others genres/%bucket{$artist}/$artist/$artist-%asciify/$title
      comp: Others genres/Compilations/%bucket{$album)/VA-$album-$year/$title
  ```
- we cannot choose to extrapolate only one of the buckets ranges (`extrapolate` option apply to both).

I think it should be quite easy to scale the plugin to handle these use cases :  
- we already have the optional _field_ argument `_tmpl_bucket(self, text, field=None)` that we could use to select the appropriate bucket
- additional buckets could be defined by using the _bucket_$field_ name, like _bucket_year_ does :  
  
  ```
  bucket:
     bucket_artist: ...
     bucket_genre : ...
     bucket_year: ...
  ```
- the `extrapolate` option could be suppressed and merged in the bucket definition by using the `...` chars, ie :  
  
  ```
  bucket:
     bucket_artist: ['A-C','D-F', ...]  # extrapolate: two letters buckets dirs
     bucket_genre : ['A-C','D-F']  # just two buckets dirs, initials otherwise
  ```
  
  and '...' is not a valid folder name anyway so it makes a perfect keyword to use in a bucket definition list

Wat y'all tink ? :japanese_goblin:

**Comment by Kraymer** [comment]
@sampsyo I'd like your feedbacks on [proposed interface](https://gist.github.com/Kraymer/83b9e27881c136820fe3#file-gistfile1-rst)

**Comment by sampsyo** [comment]
This looks great! I like the ... idea for filling in extrapolations. Very elegant. :+1:
