### ISSUE TITLE
In %asciify, asciify_paths, scrub path separators

### ISSUE THREAD

**Issue by igno2k** [beetbox/beets#1087]
Songs starting with "½" should be renamed like the following:

$artist/$album/01 - 1_2 song title.mp3

Actually they will be renamed like this:

$artist/$album/01 -1/2 sing title.mp3

So a new folder starting with "01" is created.

Suggestion:
We will probably need to special-case this to re-scrub path separators after asciification.

Also see:
https://groups.google.com/forum/#!topic/beets-users/cpY7zKRUGbA

Regards,
Matthias

**Comment by aaronk6** [comment]
I just ran into this issue and I find it pretty annoying. Is there any workaround?

Thanks for the great work though. Beets is awesome 👏

**Comment by sampsyo** [comment]
No currently, although @tweitzel appears to be working on a fix: https://github.com/tweitzel/beets/commit/c3e63084d2299920396d976604f7ae896e22be37

And thanks! :sparkles:

**Comment by aaronk6** [comment]
A fix is even better 😊 Thanks for the super-fast reply!

**Comment by exislow** [comment]
Voting for a fix! This is really annoying.

**Comment by sampsyo** [comment]
See #2303 for the latest progress.
