### ISSUE TITLE
echonest: IO error: timed out

### ISSUE THREAD

**Issue by euri10** [beetbox/beets#1096]
I discovered this plugin yesterday, so I'm trying to fill my library doing a beet echonest
I got this "error" echonest: IO error: timed out after a few songs that work
echonest: truncating /media/raid5/BEETS/Gil Scott-Heron & Brian Jackson/Home Is Where The Hatred Is (Live) _ The Bottle (Live)/02 The Bottle (Live).flac to /tmp/tmpcOPouX.ogg
echonest: truncate encoding /media/raid5/BEETS/Gil Scott-Heron & Brian Jackson/Home Is Where The Hatred Is (Live) _ The Bottle (Live)/02 The Bottle (Live).flac
echonest: uploading file, please be patient
echonest: IO error: timed out
echonest: IO error: timed out
echonest: IO error: timed out
echonest: IO error: timed out
echonest: IO error: timed out
echonest: IO error: timed out
echonest: IO error: timed out
echonest: IO error: timed out
echonest: IO error: timed out
echonest: IO error: timed out
error: echonest request failed repeatedly

and if I relaunch the same command, 1st thing it converts / uploads the same songs he already did which is kind of annoying but well not so important compared to the fact it fails at the very same song. I even removed the songs in question but I end up at some point with the same issue on another song.

**Comment by sdfg2** [comment]
I just discovered this today - is the whole file uploaded the EN servers?
