### ISSUE TITLE
Ignore OS-specific hidden files

### ISSUE THREAD

**Issue by ghost** [beetbox/beets#110]
This issue was automatically migrated from Google Code.
_Original author: Joris.Dobbelaer@gmail.com (January 13, 2012 19:58:52)_
_Original issue: https://github.com/google-code-export/beets/issues/293_

**Comment by jrobeson** [comment]
i coulda swore i saw some mentions of ignoring .DS_Store in the codebase, but maybe that doesn't cover all the places.

**Comment by sampsyo** [comment]
Here's some more detail on the GitHub issue mirror of Google Code: https://github.com/google-code-export/beets/issues/293

It's about the "hidden" metadata flag some OSes have.
