### ISSUE TITLE
Updating Mopidy's library with beets

### ISSUE THREAD

**Issue by sondr3** [beetbox/beets#1191]
I'm currently using Mopidy as my MPD player and use ncmpcpp to play my music, however I'd like to have the database for Mopidy to be updated when I add music with beets. Right now I have to quit mopidy, run `mopidy local scan` and then start mopidy again. I'm using the `mpdupdate` plugin as well but it doesn't seem like it's working. Any idea what I could do?

**Comment by m-urban** [comment]
Just created PR #1573 to run scripts after import. Configuring the new `runafter` plugin with a script like this will automate the mopidy update.

```
#!/bin/sh

mopidy local scan

```

**Comment by m-urban** [comment]
Referencing #1603
