### ISSUE TITLE
Ignore missing video tracks identified by MusicBrainz during import and in missing plugin

### ISSUE THREAD

**Issue by fortes** [beetbox/beets#1210]
Musicbrainz albums sometimes have video tracks in them (example: http://musicbrainz.org/release/49da37ee-065a-4d7f-a204-9dda8047aad4 ) -- is it possible to ignore video tracks we importing or using `beet missing`?

**Comment by sampsyo** [comment]
Not currently, but (if there's a reliable way of identifying them) then this seems like a worthy goal.

**Comment by fortes** [comment]
Here's the XML: http://musicbrainz.org/ws/2/release/49da37ee-065a-4d7f-a204-9dda8047aad4?inc=artists+artist-credits+recordings+aliases

Looks like the track has `<video>true</video>` in the response.

**Comment by sampsyo** [comment]
Cool. If anyone's interested in taking this on, the first step will be propagating that information from MB to the beets database.

**Comment by Freso** [comment]
Related Picard issue: musicbrainz/picard#383 - note that this is not just videos, there are plenty of "enhanced" cds with e.g. bonus MP3s on the data section.
