### ISSUE TITLE
Smartplaylist plugin generates a directory path for album_query

### ISSUE THREAD

**Issue by pjones** [beetbox/beets#1225]
When using `album_query`, the documentation states that the smartplaylist plugin will include all tracks from matching albums.  Instead, the smartplaylist plugin writes the directory name into the playlist file.  To be a proper playlist, the smartplaylist plugin should export all tracks from a matching album.

**Comment by sampsyo** [comment]
Thanks for pointing this out. It looks like this regressed in 11c60ce101c7642eee1fb7fa589b74f69371a21e. This should be fixed now—can you pull the latest source and check that it's working for you?

**Comment by pjones** [comment]
Works for me.  Thanks!
