### ISSUE TITLE
lyrics: Some self.config references broken

### ISSUE THREAD

**Issue by sampsyo** [beetbox/beets#1226]
@brunal, it looks like the source-class refactoring in `lyrics` broke some `self.config` references in the `Google` backend. Specifically, that code still refers to `self.config['google_API_key']`, even though the `Google` object does not have a `config`.

I'm not sure what the best resolution is—pass the `config` along? Initialize the objects up front and pass the Google-specific parameters to `__init__`?

**Comment by sampsyo** [comment]
Oops, forgot to include a relevant traceback from a user: http://pastebin.com/YP1RrEQn

**Comment by brunal** [comment]
That's right, sorry for the bug!

I now pass `config` as the first init parameter (like in `beets.replaygain`), ignored by every backend but Google.
