### ISSUE TITLE
Re-importing with fetchart creates two album art files

### ISSUE THREAD

**Issue by k-f-** [beetbox/beets#1264]
Heya guys,

Not a bug or anything but I'm occasionally getting multiple cover art files.
I'm thinking it's when I previously had the incorrect musicbrainz ID for the album, thus the existing `cover.jpg` isn't valid.

an example: http://pastebin.com/mz13gBZ9

I'm `cover.2.jpg` is the correct art for the release of that album I have. 
I'm kind of anal here and would much rather have any existing `cover*.jpg` files deleted if it's going to get new art.

I already have `*.jpg` configured under `clutter:`, perhaps incorrectly thinking it would remove any jpgs when it checked for new artwork.

_I suspect I'm just not groking something in the beets decision tree_

fyi: fetchart is enabled and runs with these settings:

```
fetchart:                                   # get album art
    auto:               yes                 # default: yes
    cautious:           yes                 # require cover_names
    cover_names:        cover folder front picard  # be paranoid
    sources:            coverart itunes *   # prefer coverart itunes
    maxwidth:           2500                # max of 2500px wide please
    remote_priority:    no                  # prefer local
```

**Comment by sampsyo** [comment]
Hello, and thanks for reporting! Can you please try to reproduce this from the beginning so we can see exactly what might be going on? For example, steps to reproduce might look like:

1. Import this album (attached as zip file) with this config (also attached)
2. Run `fetchart`
3. Type `ls /path/to/album` to see the two files

Without knowing what you did to lead up to this situation, it's difficult to tell how things got into a bad state.

---

> I already have *.jpg configured under clutter:, perhaps incorrectly thinking it would remove any jpgs when it checked for new artwork.

Yes, clutter is unrelated.

**Comment by djl** [comment]
This happens to me when I import an album multiple times.

Steps to reproduce:

1. Import an album
2. Make sure it has a cover file
3. Import the album again
4. There should now be a `cover.N.jpg` file (`N` increments each time you re-import the album)


Here's my fetchart config:

    fetchart:
      cautious: true
      remote_priority: true

**Comment by k-f-** [comment]
That's exactly what I've experienced.  Thanks @djl

**Comment by djl** [comment]
I think I've tracked this down to a bug in [`Album.set_art()`](https://github.com/sampsyo/beets/blob/master/beets/library.py#L932). Rather than deleting the old file (as the docstring implies) a new file with a unique suffix is created instead.

Looking at this, it seems like a simple fix but now I'm not sure if this was done intentionally (possibly to prevent accidental data loss?) and the docstring is just incorrect.

In any case, pull request coming shortly. We can discuss it there :)

**Comment by sampsyo** [comment]
Hi there, @djl—thanks for doing some investigation. The story is much clearer now: re-importing albums with `fetchart` enabled creates double album art files. It's related to #314.

That does seem like a problem in `set_art`, but I actually don't think that's the only cause here. When re-importing, we currently don't do anything smart at all about album art. The normal workflow would pick up the file that already exists, but you have `remote_priority` enabled so it downloads another image. Re-importing creates a new Album in the database and replaces the old one.

A full solution here, and probably to #314, would need to bring over the old Album's art to the new one, and then make sure it gets deleted if it's replaced. Does that make sense?

Also, if you do tackle this, can I ask you the favor of creating a separate `delete_art` helper method? That will be helpful for, e.g., #733.

**Comment by djl** [comment]
>  but you have `remote_priority` enabled so it downloads another image

I'm a little confused now.

If `remote_priority` is the trigger for this bug, how did @k-f- end up with multiple cover files? I tested fetchart without `remote_priority` and it didn't create any duplicate files.

What am I misunderstanding?

**Comment by sampsyo** [comment]
Good question—I don't exactly know how @k-f- ended up with this behavior. If you can cook up reproduction steps with your config, @k-f-, do let us know.

**Comment by k-f-** [comment]
Hey guys,

Sorry been fighting a failing raid array all day, and haven't had a chance to get back to you.  :neckbeard: 
I do indeed have `remote_prority:   no' set.

I've been meaning to make a config I can use for dev/testing without nuking my personal stuff, so I'll do that and see if I can't replicate this for you.
