### ISSUE TITLE
Permissions plugin: change permissions of folders

### ISSUE THREAD

**Issue by l-t-k** [beetbox/beets#1308]
Would be great if the permissions plugin can be used to change the permissions of the created folders as well.

**Comment by xsteadfastx** [comment]
yeah cool idea. i dont have time today but will look into that in the next days :)

**Comment by xsteadfastx** [comment]
im kind of stuck in some design descisions. i cant find a fitting listener for that case. i could just chmod the album directory after they get imported. but that would miss the artist directory. mh. i will see

**Comment by xsteadfastx** [comment]
i could do some stuff with os.path.split... but i would just always get the directory the tracks are in... not the artist folder for example.

**Comment by sampsyo** [comment]
Perhaps just chmod all of the ancestors of the file, recursively, stopping when the change is disallowed? There's a utility in `beets.util` that can give you the ancestors.

The pruning logic there is another example of "bubbling up" until we hit the top library directory.

**Comment by xsteadfastx** [comment]
thats what i was thinking. i wrote my own "walker" for the directories. i just want to change permissions on directories in the library. what do you think?
