### ISSUE TITLE
Non-determinism of MediaFile.art and embedart plugin

### ISSUE THREAD

**Issue by brunal** [beetbox/beets#1332]
@mried work on #1328 brought to light the fact that the `extractart` plugin relies on `MediaFile.art` which is as "legacy album art field", the "first image on a file". However this seems non-deterministic (sometime returns a 2nd+ image) especially on python 2.6 (sigh).

Moreover `extractart` works with this field, while it could work with `images`, extracting all arts from a file (`MediaFile.images`).

The questions raised are:
- how does MediaFile determines the `art` property?
- should the `art` property be kept? It seems used by the plugins `scrub` and `embedart`
- shouldn't `embedart` manage all art files?

**Comment by mried** [comment]
I believe the images embedded into mp3 can be tagged with image types like 'Front cover' or 'Back cover' or ... Maybe `embedart` should take care of this type? (I don't know if `MediaFile` is able to read the types.)

**Comment by brunal** [comment]
The images do have a description, which can be used to determine the main art file (= front cover). `MediaFile` knows about it, as well as the mime type. 

Given that the `art` property is used in some `beets` core, I think determining the main art should be the responsibility of `beets.mediafile`.

**Comment by brunal** [comment]
`MP3ImageStorageStyle.fetch()` is not deterministic in the order of the images returned: it works on a dict (`mutagen_file.tags`) and returns a list, we cannot predict what will be the first image (which is to be the art).

**Comment by sampsyo** [comment]
Thanks for uncovering this. Yes, the `art` field should be deterministic; and I agree with the approach of using the front cover.

I don't mind keeping the `art` property currently. Barring a sweeping change for supporting multiple art files everywhere, the status quo seems fine (and "legacy" is perhaps too strong a label, which we applied prematurely).

**Comment by brunal** [comment]
Here comes a fix: images are filtered on their type, looking for `Imagetype.front`.

Remains the subject of the `extractart` command of the embedart plugin: shouldn't it extract all images? In that case should it be the default, or a `--all` flag?

* if it is the default: with `-o` only extract the cover, with `-n` extract all but rename the front cover with the argument of the `-n` option
* if it is another flag, shan't it be incompatible with `-o`?
