### ISSUE TITLE
list command needs option to display all metadata

### ISSUE THREAD

**Issue by alphapapa** [beetbox/beets#1374]
I often want to look at all of a file's metadata.  I can do this easily with `mediainfo`, and I expected an easy way to do this in Beets, but apparently there isn't such a way.  `beet ls` doesn't print anything but the artist/album/track or path.  

I'm thinking that it should work something like this:

```
$ beet ls -a bob
Artist - Album - Title1
    artist: Artist
     album: Album
     title: Title 1
     genre: genre
      year: 0000
    ...
Artist - Album - Title 2
    artist: Artist
     album: Album
     title: Title 2
     genre: genre
      year: 0000
    ...
```

**Comment by guibog** [comment]
Hi, I have the same need. In fact you can enable info plugin and call `beet info foo`. But it is not enough detailed for my needs: I would like to know which metadata is stored in the file itself, which one is only in the library database, which one in both, and some highlighting when it is not the same value.

**Comment by tomjaspers** [comment]
@guibog Until someone implements the feature, I think the following command could help you maybe?

`$ diff <(./beet info bohemian) <(./beet info -l bohemian)`

There's been more discussion about this topic (`info` vs `ls`) elsewhere; can't seem to find it straight away though.

**Comment by alphapapa** [comment]
Thanks guibog, I didn't know about that plugin.  Maybe it should be enabled by default.  :)

But I agree with you, I'd also like to be able to see actual file metadata rather than only database metadata.

**Comment by brunal** [comment]
@alphapapa no plugin is enabled by default, even though many of them are must-have. Be sure to read the [plugin list page](http://beets.readthedocs.org/en/v1.3.10/plugins/index.html), you'll probably find many useful ones.

**Comment by alphapapa** [comment]
I see.  So how do you decide what is a plugin and what isn't?  If "must-have" is really must-have, why is it not default functionality?  :)  From the perspective of a new user, this seems like an unnecessary, extra hoop to jump through.  I mean, does having these must-have plugins merely enabled have any ill effects?  If not, why are they merely plugins?  :)

**Comment by sampsyo** [comment]
There are a few reasons:

* Avoiding overwhelming "help" output and documentation (which is already quite large).
* Isolate dependencies, when they exist (doesn't apply to `info`).
* Design modularity: plugins using the same interfaces makes us more disciplined about keeping concerns separate.

A good case could be made for enabling `info` by default, but I don't think the outcry is currently universal by any means.
