### ISSUE TITLE
'beet fields' output should be sorted

### ISSUE THREAD

**Issue by flight16** [beetbox/beets#1401]
Output would be easier to read if it were sorted.  Currently it appears as

<pre>
$ beet fields
Item fields:
  lyrics
  disctitle
  month
  channels
  disc
  mb_trackid
  composer
  albumartist_sort
  bitdepth
  title
  mb_albumid
  acoustid_fingerprint
  rg_album_gain
  mb_releasegroupid
  rg_album_peak
  albumartist_credit
  acoustid_id
  format
  encoder
  rg_track_gain
  day
  original_year
  artist
  mb_albumartistid
  bpm
  artist_credit
  grouping
  disctotal
  album_id
  albumstatus
  mtime
  original_day
  albumartist
  year
  albumdisambig
  samplerate
  id
  album
  mb_artistid
  media
  artist_sort
  comments
  tracktotal
  rg_track_peak
  catalognum
  added
  original_month
  asin
  track
  comp
  initial_key
  genre
  path
  bitrate
  language
  country
  script
  label
  length
  albumtype
  singleton
  filesize
  data_source

Album fields:
  disctotal
  albumstatus
  month
  original_day
  albumartist
  year
  albumdisambig
  albumartist_sort
  id
  album
  asin
  script
  mb_albumid
  label
  rg_album_gain
  mb_releasegroupid
  artpath
  rg_album_peak
  albumartist_credit
  catalognum
  added
  original_month
  comp
  genre
  day
  original_year
  language
  mb_albumartistid
  country
  albumtype
  path
  albumtotal
  path
  data_source
</pre>

**Comment by flight16** [comment]
I was planning on working on this one when I got home tonight but you beat me to it.  Was that ever fast. : )

**Comment by sampsyo** [comment]
Fixed in #1402.
