### ISSUE TITLE
Release planning

### ISSUE THREAD

**Issue by sampsyo** [beetbox/beets#1425]
As suggested by @brunal in #1415, let's plan some upcoming milestones.

I'd like to push out 1.3.12 quickly, as mostly a bugfix release. After that, we have our pick of big refactoring tasks to work on:

* pathlib #1409 
* some kind of refactoring to encapsulate global state, as discussed in #1415 
* new plugin manager infrastructure and API, avoiding class-level state, as in #607 
* replace optparse with Click

Any one of these would be enough to make a 1.4.0 or some 1.x.0 beyond that. The only question is where to spend our time first!

**Comment by LordSputnik** [comment]
I'd like to see pathlib and unicode/bytes path clean-up happening first, as a precursor to supporting Python 3, now that both mutagen and Flask are Python 3 compatible. If I get time I'll start getting used to the overall structure of beets and then see what I can do about #1409.

**Comment by svenstaro** [comment]
Seems like this should be closed in favor of a new issue?

**Comment by sampsyo** [comment]
Yep; thanks!
