### ISSUE TITLE
duplicates: Crash when "move" or "copy" option is "yes"

### ISSUE THREAD

**Issue by TylerRudie** [beetbox/beets#1457]
Issue with the Duplicates Plugin. When i have the 'Path' setting populated the plugin dumps a trackback. remove the path and set move to no and the plugin works just fine.

```
duplicates:
    album: no
    full: no
    format: ''
    keys: [mb_trackid, mb_albumid]
    path: /mnt/download/dest/beat/.dup/
    move: yes
    tag: no
    copy: no
    count: no
    checksum:
    delete: no
```

```
$ beet dup
Warning: top-level configuration of `color` is deprecated. Configure color use under `ui`. See documentation for more info.
Traceback (most recent call last):
  File "/usr/local/bin/beet", line 9, in <module>
    load_entry_point('beets==1.3.14', 'console_scripts', 'beet')()
  File "/usr/local/lib/python2.7/site-packages/beets/ui/__init__.py", line 1104, in main
    _raw_main(args)
  File "/usr/local/lib/python2.7/site-packages/beets/ui/__init__.py", line 1094, in _raw_main
    subcommand.func(lib, suboptions, subargs)
  File "/usr/local/lib/python2.7/site-packages/beetsplug/duplicates.py", line 148, in _dup
    fmt=fmt.format(obj_count))
  File "/usr/local/lib/python2.7/site-packages/beetsplug/duplicates.py", line 161, in _process_item
    item.move(basedir=move, copy=False)
  File "/usr/local/lib/python2.7/site-packages/beets/library.py", line 713, in move
    dest = self.destination(basedir=basedir)
  File "/usr/local/lib/python2.7/site-packages/beets/library.py", line 808, in destination
    return normpath(os.path.join(basedir, subpath))
  File "/usr/local/lib/python2.7/posixpath.py", line 77, in join
    elif path == '' or path.endswith('/'):
AttributeError: 'bool' object has no attribute 'endswith'
```

**Comment by sampsyo** [comment]
Thanks for reporting. The plugin definitely shouldn't crash in this situation. But the reason this isn't working is that `path`, `move`, and `copy` don't quite work how you're using them. To quote from the docs:

> path: Output the path instead of metadata when listing duplicates. Default: no.
> move: A destination base directory into which it will move matched items. Default: none (disabled).

So if you want to move items, just put a path in for `move:`, not "yes".

**Comment by sampsyo** [comment]
Assigning @pedros in case he's interested in adding a handler for this kind of misconfiguration.

**Comment by pedros** [comment]
Sorry about the delay, been out of town lately. The above fix would result on the following error now:

    configuration error: duplicates.checksum: must be a string

This would happen for `checksum`, `move`, `tag` and `copy`. `path` would result in:

    configuration error: duplicates.path: must be a bool, not unicode

**Comment by sampsyo** [comment]
Looks perfect. Thanks as always, @pedros, and not to worry about timing—open source hacking usually isn't time-sensitive. :smiley: Would you mind adding a short note to the changelog?

**Comment by pedros** [comment]
Yup, done.

**Comment by sampsyo** [comment]
Awesome; thanks again.
