### ISSUE TITLE
beet update crashes out

### ISSUE THREAD

**Issue by darthanubis** [beetbox/beets#1458]
beet update crashes out

beet update -p
Traceback (most recent call last):
  File "/usr/local/bin/beet", line 9, in <module>
    load_entry_point('beets==1.3.13', 'console_scripts', 'beet')()
  File "/usr/local/lib/python2.7/dist-packages/beets/ui/**init**.py", line 1104, in main
    _raw_main(args)
  File "/usr/local/lib/python2.7/dist-packages/beets/ui/__init__.py", line 1094, in _raw_main
    subcommand.func(lib, suboptions, subargs)
  File "/usr/local/lib/python2.7/dist-packages/beets/ui/commands.py", line 1089, in update_func
    update_items(lib, decargs(args), opts.album, opts.move, opts.pretend)
  File "/usr/local/lib/python2.7/dist-packages/beets/ui/commands.py", line 1012, in update_items
    if not os.path.exists(syspath(item.path)):
  File "/usr/lib/python2.7/genericpath.py", line 18, in exists
    os.stat(path)
TypeError: coercing to Unicode: need string or buffer, NoneType found

**Comment by sampsyo** [comment]
Thanks for reproducing. Can you please provide the full context for this error so we can try to reproduce it?

**Comment by darthanubis** [comment]
I don't know what else to add. I thought the -v debug option would reveal more clues, but I get the same output as above. I'm simply trying to run the update. Nothing exotic. Update has never worked for me. I have no duplicates or missing files.
beet config
lyrics:
    sources: [lyricwiki, lyrics.com, musixmatch]
    google_API_key: REDACTED
    force: no
    auto: yes
    google_engine_ID: REDACTED
    fallback:
lastfm:
    user: darthanubis
    api_key: REDACTED
mpd:
    host: 192.168.123.112
    music_directory:
    rating: yes
    rating_mix: 0.75
    password: REDACTED
    port: 6600
scrub:
    auto: yes
embedart:
    ifempty: yes
    compare_threshold: 0
    auto: yes
    maxwidth: 0
zero:
    fields: comments
    comments: []
library: ~/Music/data/musiclibrary.blb

plugins: fetchart lyrics duplicates embedart mbsync missing scrub discogs zero info mpdstats lastimport
directory: ~/freenas/data/Music/beets

import:
    move: yes
    log: ~/.config/beets/log
echonest:
    upload: no
    convert: no
    apikey: redacted
acoustid:
    apikey: redacted
duplicates:
    album: no
    full: no
    format: ''
    keys: [mb_trackid, mb_albumid]
    move: no
    tag: no
    path: no
    copy: no
    count: no
    checksum:
    strict: no
    delete: no
lastimport:
    per_page: 500
    retry_limit: 3
fetchart:
    minwidth: 0
    sources:
    - coverart
    - itunes
    - amazon
    - albumart
    - google
    - wikipedia
    cautious: no
    maxwidth: 0
    google_search: no
    auto: yes
    cover_names:
    - cover
    - front
    - art
    - album
    - folder
    remote_priority: no
    enforce_ratio: no
discogs:
    tokenfile: discogs_token.json
    apikey: REDACTED
    apisecret: REDACTED
    source_weight: 0.5
missing:
    count: no
    total: no
beet version
beets version 1.3.13
plugins: discogs, duplicates, embedart, fetchart, info, lastimport, lyrics, mbsync, missing, mpdstats, scrub, zero

Debian Jessie

**Comment by sampsyo** [comment]
Can you narrow it down to a specific file that's crashing and provide details on it (or even share the file)?

**Comment by sampsyo** [comment]
This issue is timing out. Please reopen it if you can dig a little deeper into the cause of the problem.
