### ISSUE TITLE
fetchart: enforce_ratio option silently fails (and causes tests to fail) if backend isn't available

### ISSUE THREAD

**Issue by sampsyo** [beetbox/beets#1460]
The new enforce_ratio option requires an imaging backend (PIL or ImageMagick) to get the size of an image. If it can't get the image, then `ArtResizer.get_size()` returns None and the plugin (rightly!) will not embed the image.

The trouble is that this failure mode isn't logged anywhere. I propose the following:
- [x] Log a warning (or at least a debug message) when the plugin gets None back from ArtResizer.
- [x] Add to the documentation for fetchart that you need ImageMagick or PIL.
- [x] Skip the tests for `enforce_ratio` if ArtResizer is using the fallback (proxy) backend.

Does that sound OK, @tomjaspers?

**Comment by tomjaspers** [comment]
Right! Seems like a pretty bad oversight on my part, woops. I'll be away until Monday, but I'll get right on it when I'm back (if it can wait that long).

**Comment by sampsyo** [comment]
Only a medium-sized oversight! And no hurry; please don't let it interfere with your travels.

**Comment by sampsyo** [comment]
This all looks awesome. Thank you!
