### ISSUE TITLE
On OS X, `beet config -e` doesn't work for initial setup by default

### ISSUE THREAD

**Issue by sampsyo** [beetbox/beets#1480]
By default (when `$EDITOR` is not set), the `beet config -e` command will try to use OS X's `open` command to edit the config file on that platform. Unfortunately, that command doesn't work when the file does not exist—when setting up beets for the first time, for example.

We may need to run `touch` first to create the file, and then use `open -t` to get the default text editor.

Background in a mailing-list thread:
https://groups.google.com/d/topic/beets-users/FDa_3fO3sBM/discussion

**Comment by tomjaspers** [comment]
I didn't mention it in the commit or in the code, but this also creates any directories needed (which was the case in the mailing-list thread).
