### ISSUE TITLE
Replace nosetests with py.test?

### ISSUE THREAD

**Issue by untitaker** [beetbox/beets#1483]
While working on #1442 I noticed that there are a lot of helper functions regarding tempfiles and stdio in `test/helpers.py`. Py.test has all of this baked in and, more generally, is a much nicer testrunner to use. What's your opinion?

**Comment by adolenir** [comment]
alguém me diz como-se ganha dinheiro com este programa ???

**Comment by untitaker** [comment]
@adolenir Please write in english, also I think you'll have to figure out for yourself how to make money off this. In any case this is off-topic, which is why I'll delete this comment.

**Comment by sampsyo** [comment]
With no specific preference for nose, I would love to continue not requiring a specific test runner—it's a nice property to have that we work with generic `unittest` in a pinch (or nose or py.test, which both work equally well now). So no objection to using more fixture dependencies and deleting our hand-rolled stuff, but perhaps we can avoid coupling too closely with py.test?

**Comment by untitaker** [comment]
Pytest's fixtures are very tightly coupled to the testrunner. I don't think we'll be able to use them without having a hard dependency on pytest as testrunner. Fwiw the tests work fine as-is in pytest.

**Comment by arcresu** [comment]
I think that this substantially overlaps with #2202 in terms of deciding which test runner to use. As for removing the test helpers I agree that keeping the unit tests framework-agnostic is preferable so would be hesitant to change that state of affairs.
