### ISSUE TITLE
Add support for generating nfo files

### ISSUE THREAD

**Issue by ghost** [beetbox/beets#150]
This issue was automatically migrated from Google Code.
_Original author: coolke...@gmail.com (April 27, 2011 23:31:08)_
_Original issue: https://github.com/google-code-export/beets/issues/178_

**Comment by sampsyo** [comment]
I don't think we need this.

**Comment by OmgImAlexis** [comment]
Can this be reopened? It'd be nice to have beets save a nfo file so the albums and artists will always match to the correct musicbrainz ID.

**Comment by sampsyo** [comment]
Hey! If you're interested, can you open a new issue with a full proposal and some reasons why it would be useful?
