### ISSUE TITLE
Bandcamp metadata source plugin

### ISSUE THREAD

**Issue by Schweinepriester** [beetbox/beets#1508]
Couldn't find an issue for this, therefore: Has Bandcamp been considered as a source in general? For the autotagger, for cover art, lyrics, genre, etc.?

I know that the API is deprecated, see https://bandcamp.com/developer, and no new version anywhere close, but what about scraping stuff?

Has this been considered?

**Comment by sampsyo** [comment]
Seems like a reasonable idea! That is, if we can confirm that scraping their site doesn't violate their ToS.

**Comment by Schweinepriester** [comment]
Sadly i think it would violate their ToS :/

Section "[Rules and Conduct](https://bandcamp.com/terms_of_use)":

> Additionally, you shall not: \[...\] (v) use manual or automated software, devices, or other processes to “crawl” or “spider” any page of the Site.

Or would that not apply in this case?

I'll see if i can find anything about a new API or something.

**Comment by Schweinepriester** [comment]
Doesn't look good for anything official. I [asked](https://twitter.com/schweinepriestr/status/611652328043753472) though, lets see if and what they respond...

There is stuff, like

- <https://www.npmjs.com/package/node-bandcamp>
- <https://www.npmjs.com/package/bc-search>

which would work, i guess. But unofficial and potential against their ToS (and in beets' case: not Python)? Not so cool.

Bandcamp would be a really great source, though, especially for data of/from new/small artists. I think Bandcamp encourages good tags, lyrics, album art and so on...

**Comment by sampsyo** [comment]
Sure, borrowing techniques from those Node modules might be a good way to go.

**Comment by workerparasite303** [comment]
a lot of my digital media is from BC, so id love for this to get solved...

BC, for the most part, has great tagging. it suggests several main ones (ie. Techno, House, Experimental) and then allows the users to add their own tags, sometimes including where theyre from, etc (which is not very useful most of the time)

what if the plugin added a feature that allowed you to pull from BC on auto import, but didnt include functionality to pull data in massive chunks all at once? (not a programmer, just a musician/dj that loves beets)

i think its insane BC hasnt looked at this...they ARE supposed to be SF superstar music hackers afterall...

**Comment by discopatrick** [comment]
👍  +1 for this feature :)

**Comment by Schweinepriester** [comment]
Dreaming about this feature again… :)

Just imported <http://fallofanempireband.bandcamp.com/album/croweater-an-echo-in-the-bone> and, while its thankfully [on musicbrainz](http://musicbrainz.org/release/e6a38ab2-ba35-421d-ac1d-d2c30064693f), all the lyrics only exist on bandcamp :o

They even utilize <http://schema.org/>, look at that beautiful markup/DOM.

Maybe one/we could write a plugin, whereby beets wouldn't be associated with any ToS violating…? 0:-)

**Comment by sampsyo** [comment]
Huh! Yeah, it does seem feasible… especially for the lyrics.

**Comment by mo65535** [comment]
I just tried this plugin. Nice job, @unrblt!
https://github.com/unrblt/beets-bandcamp

It worked fine for me (Windows 10 Pro, Python 2.7.12 32-bit). For installation step one I did need to create a folder and then specify it as my `pluginpath` in beets' config.yaml. The plugin can purportedly fetch lyrics and art, but I didn't try either.

**Note:**
When importing four albums that I just purchased from Bandcamp, two had entries at MusicBrainz and apparently beets defaulted to using that (which resulted in a few small title changes). Metadata for the other two albums, which had no MusicBrainz entries, were fetched from Bandcamp.

I just started using beets two days ago and I don't know of a way to force it to prefer one metadata source over another. I'm not too bothered that a couple of these albums now differ slightly from their Bandcamp metadata. However, if you want to fetch lyrics from Bandcamp, for an album that has a MusicBrainz entry, beets (and/or the plugin) might require some modification.

**Comment by unrblt** [comment]
I wrote that plugin, I'm glad you liked it @mo65535 ! The code now feels a little _hackish_ and I'm sure it can be improved but I have been using it for over an year now without problems.

> When importing four albums that I just purchased from Bandcamp, two had entries at MusicBrainz and apparently beets defaulted to using that

That is by design, but changing the `source_weight` for the bandcamp plugin in your config should work (though I didn't test it). Something like:

```yaml
bandcamp:
    source_weight: 0
```
