### ISSUE TITLE
zero: Add option to update database?

### ISSUE THREAD

**Issue by djl** [beetbox/beets#1516]
The [docs for the zero plugin](http://beets.readthedocs.org/en/v1.3.13/plugins/zero.html) state:

> This plugin only affects files’ tags ; the beets database is left unchanged.

This means users have to run an extra `beet up` command for the changes to take effect in the database. If one was to run `beet write` before doing this, our freshly zeroed tags would be overwritten again.

Should there be an option to update the database as well as the files' tags?

**Comment by sampsyo** [comment]
Yes, that option seems reasonable to me.
