### ISSUE TITLE
zsh completion: Breaks when smartplaylist is enabled

### ISSUE THREAD

**Issue by parnmatt** [beetbox/beets#1525]
If I have `smartplaylist` in my list of plugins, I get the following message, `<TAB>` shown where pressed for completion:

```
beet <TAB>...error: unknown command 'as'

_beet:zregexparse:4: invalid regex : #
_beet:zregexparse:4: invalid regex : #
```

However works fine without the plugin. The program and plugins work perfectly fine, its just the tab completion that's messed up.

![2015-06-28-234251_956x510_scrot](https://cloud.githubusercontent.com/assets/318829/8398653/6fae6d80-1def-11e5-9f10-b2f01c2e664f.png)

**Comment by sampsyo** [comment]
Any chance you can dig into the zsh completion script to find out what's going wrong, and possibly fix the incompatibility?

You can also always just disable the zsh completion script.

**Comment by GrzegorzZawadzki** [comment]
ok

**Comment by akermu** [comment]
The problem is that the splupdate command has 2 lines of description in the output of `beet help`.

**Comment by sampsyo** [comment]
Good catch! Perhaps there's a way we can adapt the completion script to be more robust to that kind of difference.

**Comment by akermu** [comment]
As a quick hack line 153 can be replaced by
```bash
for i in ${${(f)"$(beet help | awk 'f;/Commands:/{f=1}' | grep '^  \w.*')"[@]}[@]}
```
to fix the problem.

**Comment by sampsyo** [comment]
Nice, @akermu. That looks good. Would you mind opening a PR? Just editing in the GitHub web interface should do fine.

**Comment by akermu** [comment]
Done :)
