### ISSUE TITLE
Discogs: beets takes one number (i.e. 5A and 5B) as two different numbers

### ISSUE THREAD

**Issue by kooimens** [beetbox/beets#1543]
Some discogs releases contain track numbers A and B (for example 5A and 5B). In reality, this is most of the time 1 mp3 file. It usually occurs with dance music / house tracks. Beets is unable to recognize this. Therefore, tagging is impossible because beets concludes that the album is having a missing track (for example 5B).

**Comment by sampsyo** [comment]
Can you please provide several examples demonstrating this case?

**Comment by kooimens** [comment]
http://www.discogs.com/Various-Defqon1-Weekend-Festival/release/7168134

For example, 2-20A and 2-20B. Should be seen as one track number (20) but beet thinks it are two seperate tracks. Total tracks is 94. Beets counts 95 tracks and concludes with missing 1 track out of 95.

**Comment by sampsyo** [comment]
Thanks. Do you have more examples, too? Having multiple instances would help establish a pattern.

Do you know of any examples where this kind of numbering refers to two different tracks?

**Comment by kooimens** [comment]
http://www.discogs.com/Hardwell-Eclectic-Beatz-8-The-Miami-Edition/release/2885582
22a and 22b

and the musicbrainz equivalent:
http://musicbrainz.org/release/51763b85-fd2a-4c89-b13a-84f57ebab53c

**Comment by dagobert** [comment]
I stumbled upon the same problem. The help page of discog states clearly how the numbering of tracks is to be read.

http://www.discogs.com/help/doc/submission-guidelines-release-trk
at Heading "12.2.9. The standard Discogs positions are:" bulletin point:

> Sub tracks, for example DJ mixes that comprise one track on a CD: Separate songs or tunes that are rolled into one track on a CD, LP etc should be listed using a point and then a number: 1, 2, 3.1, 3.2, 3.3, 4… Letters can also be used, with or without a point; A3.a A3.b, or A3a, A3b…

Notice that 1.1 or 1.a or 1b all mean that these tracks are no real separate tracks on the CD but merged into one. Discog help page advises people to use an heading to give a meaningful title to the track.
I would guess that this heading should be the real name of the title.

Here is another example CD:
http://www.discogs.com/release/2994591

In this case the beets-discog plugin gives this output also missinterpreting it as a 3CD release:

```
Correcting tags from:
    Otto Waalkes - Hilfe Otto kommt!
To:
    Otto Waalkes - Hilfe Otto Kommt!
URL:
    https://www.discogs.com/Otto-Hilfe-Otto-Kommt/release/2994591
(Similarity: 75.8%) (missing tracks, tracks, source, year, country) (Discogs, 3xCD, 2001, Europe, Rüssl Räckords)
CD 0
 * Publikumsbefragung (#1)         -> Publikumsbefragung (#0-1)
 * Hosenkauf (#2)                  -> Hosenkauf (#0-2)
 * Otti's Rap (#3)                 -> Otti's Rap (#0-3)
 * Olaf und der Nachtvogel (#4)    -> Olaf Und Der Nachtvogel (#0-4)
 * Jodel-di-ho (#5)                -> Jodel-di-ho (#0-5)
 * Werbespots (#6)                 -> Werbespots (#0-6)
 * L'Amore di Nutella (#7)         -> L'Amore Die Nutella (#0-7) (title)
 * Otti's letzte Meldungen (#8)    -> Otti's Letzte Meldungen (#0-8)
 * Grand Schmou d'Eurovision (#9)  -> Grand Schmou D'Eurovision (#0-9)
 * O.T. Der Ausserfriesische (#10) -> O.T. Der Ausserfriesische (#0-10)
 * Wollemernreinlasse? (#11)       -> Wollenerbreinlasse?? (#0-11) (title)
 * Leben an der Autobahn (#12)     -> Leben An Der Autobahn (#0-12)
 * Ostfriesen-Reggae (#13)         -> Ostfriesen-Reggae (#0-13)
 * Wetten dass? (#14) (2:47)       -> Wetten Dass? (#0-14) (2:30) (length)
 * Jeden Abend (#15) (1:40)        -> Jeden Abend (#0-15) (1:30) (length)
 * Hänsel und Gretel (#16)         -> Hänsel Und Gretel (#0-16)
CD 1: Variationen
 * Variationen (#17) (9:13)        -> Variation Extrabreit (#1-1) (0:50) (length, title)
CD 2: Bonustitel
 * Manni (Bonustitel) (#18)        -> Manni (#2-1) (index, title)
Missing tracks (10/28 - 35.7%):
 ! Variation Falco (#1-2) (0:45)
 ! Variation Spliff (#1-3) (0:20)
 ! Variation Lindenberg (#1-4) (0:12)
 ! Variation Markus (#1-5) (0:23)
 ! Variation Trio (#1-6) (0:40)
 ! Variation Spider Murphy Gang (#1-7) (0:55)
 ! Variation Nena (#1-8) (0:40)
 ! Variation Peter Schilling (#1-9) (0:55)
 ! Variation D.Ö.F. (#1-10) (1:00)
 ! Variation Bap (#1-11) (0:48)
```

**Comment by sampsyo** [comment]
Thanks for the extra data! This *really* helps clarify things. :sparkles:

I'd gladly welcome a contribution that coalesces these sub-tracks from discogs.

**Comment by dagobert** [comment]
I would be happy to help, but I am really having trouble with python :( C, JAVA, PHP and so on, you name it, is no problem.

If you give me a hint where to look in your plugin, I will still try to help.

**Comment by sampsyo** [comment]
The plugin assigns indices to tracks around here: https://github.com/sampsyo/beets/blob/master/beetsplug/discogs.py#L280

I hope that helps!

**Comment by dagobert** [comment]
One more question: How to turn on debug or better how do you debug this when working on this plugin?

**Comment by sampsyo** [comment]
Try the verbose flag (see the docs), and there's no shame in putting in `print()`s while you're debugging. The Python debugger (pdb) should also work fine if you disable threading.

**Comment by diego-plan9** [comment]
Closing after adding support for sub-tracks (in two different "formats": one where the subtracks are listed as regular tracks with a specific format for the position field, and one where subtracks might appear as a nested field of a regular track) at #2222.
