### ISSUE TITLE
Support replaygain for flac files using metaflac

### ISSUE THREAD

**Issue by mathstuf** [beetbox/beets#1549]
`metaflac --add-replay-gain *.flac` may be used to add replay gain tags (both album and track level, assuming an album is given at a time). However, all files do need to be the same bitrate, frequency, and number of channels. For "album gain cannot be computed due to different $stuff", ask whether it should compute just the track-level or quit (I fix mine with `sox`, but the logic around it is a little crazy).

**Comment by sampsyo** [comment]
Thanks for the suggestion! Please see #1203.
