### ISSUE TITLE
Let beets execute a shell script after import/update

### ISSUE THREAD

**Issue by marlemion** [beetbox/beets#1561]
Hey, this is a feature request. I don't know how to label it accordingly.

I ran into the problem that I would like to automate my update process for my music system. This system is basically using beets in combination with KODI and kplaylist. At least kplaylist can be triggered from the command line to update its database. I guess KODI should be able to be triggered, too. So I searched for an option to execute a shell script every time beets imported or updated the database. In such a script I could call respective trigger commands for KODI and kplaylist.

AFAIK there is nothing around to solve this. If there is, I'd be happy to get a pointer to it. Otherwise, it might be a good idea to be implemented.

Thanks! :)

**Comment by Kraymer** [comment]
What about using ``importfeeds`` plugin, and using a tool like [maid](https://github.com/benjaminoakes/maid) to watch its output folder and acts accordingly?  
I have a similar setup on mac (hazel instead of maid) to import new tunes to itunes and it works like a charm.

**Comment by marlemion** [comment]
Thanks for the idea. I will have a look into this.

**Comment by sampsyo** [comment]
Thanks, @Kraymer! Seems like a worthy feature request in any case—probably a plugin that can run shell commands on any beets event.

**Comment by untitaker** [comment]
What's wrong with writing a shellscript that executes beets and those commands sequently?

On 8 August 2015 02:18:20 CEST, Adrian Sampson <notifications@github.com> wrote:
>Thanks, @Kraymer! Seems like a worthy feature request in any
>case—probably a plugin that can run shell commands on any beets event.
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/sampsyo/beets/issues/1561#issuecomment-128866488

-- 
Sent from my phone. Please excuse my brevity.

**Comment by sampsyo** [comment]
Good point. For the case where you just want to run after an import, a wrapper script/alias seems like the right solution.

**Comment by untitaker** [comment]
FWIW a plugin to replace beet's UI with machine readable output (printing raw filepaths etc, no colors) would be nice. But I'm not sure that's necessary for OP's usecase.

**Comment by marlemion** [comment]
A simple wrapper script would be e.g. /usr/local/bin/beet:

#!/bin/bash
SCRIPT=/usr/local/bin/beet_follow_import.sh
/usr/bin/beet "$@"
if [ "$?" = 0 ] && [ "$1" = "import" ]; then
        echo Executing script "$SCRIPT"
        "$SCRIPT"
fi
exit 0

**Comment by untitaker** [comment]
I don't think it's necessary to globally override the beet binary.

**Comment by marlemion** [comment]
To implement the desired use case, it is necessary imho.

**Comment by m-urban** [comment]
I have actually cobbled together a plugin to do this a while ago. I am fairly busy right now, but would offer to create a pull request one of these days.

**Comment by sampsyo** [comment]
Awesome! Good point about that Mopidy hook, @m-urban.

**Comment by m-urban** [comment]
Just created PR #1573 to run scripts after import. I don't think we have a hook for `beet update` yet, do we?

**Comment by untitaker** [comment]
I still don't see why this is necessary though?
-- 
Sent from my phone. Please excuse my brevity.

**Comment by jackwilsdon** [comment]
@untitaker I can imagine this being useful if you want to sync your beets configuration across machines. Currently I use beets with git-annex, and I have to run `git annex sync --content` every time I import music or change my library. It would be nice to have a plugin that allows hooking into beets events, so it could run `git annex sync --content` automatically for me.

**Comment by jackwilsdon** [comment]
For reference, you can now use the `hook` plugin merged in #1603 (as long as you're running >=1.3.18) to do this.
