### ISSUE TITLE
plexupdate: Doesn't work with libaries not named "Music"

### ISSUE THREAD

**Issue by l-t-k** [beetbox/beets#1572]
I've named my music libaries `Music (New)` and `Music (Untagged)`. The plex update plugin should update the `Music (New)` section, but instead of updating at least both music libaries it doesn't update anything. If I change the library name from `Music (New)` to `Music` it works like a charm. This is specified on line 33 of the beets plugin. A config option to add libraries other than `Music` would make sense imo.

**Comment by sampsyo** [comment]
Odd—did the body of this issue get deleted somehow?

**Comment by sampsyo** [comment]
Odd—did the body of this issue get deleted somehow?

**Comment by sampsyo** [comment]
Sounds quite reasonable!

**Comment by kooimens** [comment]
Yeah, I'm sorry. The initial body of this issue consist of just the problem with the plex update plugin (and my config file etc.), but after some research I've found the real issue which is far more useful I think.
