### ISSUE TITLE
wiki - coverage

### ISSUE THREAD

**Issue by pkess** [beetbox/beets#1606]
Hi,

on your page [Hacking](https://github.com/sampsyo/beets/wiki/Hacking) you report that the test coverage is low at the moment. At the moment this is a link to [coveralls.io](https://coveralls.io/github/sampsyo/beets). This has to link to [codecov.io](https://codecov.io/github/sampsyo/beets), am i right?

I would like to contribute by adding some test, but i don't know how to write tests correctly. Can you give help?

**Comment by sampsyo** [comment]
Thanks! Link's fixed.

And thanks for being willing to help add some tests! I think the best way to get an idea of how testing works would be to read some existing ones. Start simple: there are some really complex testing strategies in beets, but many of them are easy to understand.
* There are some very straightforward tests for how template evaluation works in isolation. They should give you an idea of how simple things can be: https://github.com/sampsyo/beets/blob/master/test/test_template.py#L224
* And here's a more complex example that tests fetchart using methods from a test help class called `TestHelper`, that can be really useful: https://github.com/sampsyo/beets/blob/master/test/test_fetchart.py#L36

**Comment by pkess** [comment]
Thank you for your quick response.

I just fixed a link and added some information on https://github.com/sampsyo/beets/wiki/Testing too.

**Comment by sampsyo** [comment]
Nice; thanks! These are great notes.

**Comment by arcresu** [comment]
I don't think there's anything specific left to do in this issue. More tests are certainly always welcome, and if there's some way that the documentation related to tests can be improved then that would also be useful, but now that there's the wiki page I think the basics are covered.

As an aside, I find the coverage reports a bit mystifying. Some files aren't included for no apparent reason and my PRs related to bpd resulted in coverage reports that made no sense. It was claiming that some lines were executed while neighbouring lines were not, even though they were all inside the same code block and there's no way some lines could have executed without the others. I wonder if the line number map was somehow buggy and the report wasn't displaying correctly.
