### ISSUE TITLE
export command/plugin

### ISSUE THREAD

**Issue by snicker** [beetbox/beets#1618]
I currently use beets to manage my library on my home server and process media. I have been using a windows based tool (mediamonkey) to sync my library to an external hard drive to use in my car. I'd like to be able to use beets to do that.

Ideally, this plugin would:
1. accept a target path (this could be an external drive, another directory, whatever)
2. keep a copy of the beets DB in the target (optional)
3. copy media to the target according to a configurable path using metadata (just like `import` does). Also allowing to truncate path or filenames as some hardware media players have this restriction.
4. remove media on the target that have been removed from the master library (optional)
5. synchronize changes to media or metadata to the target
6. accept query parameters for what media to export.

Current idea for a workaround that I haven't tried yet is using a custom .beetconfig and creating a new library on the target, importing from my current library.

**Comment by sampsyo** [comment]
Hi! Have you tried the `convert` plugin? As a checklist:

1. :white_check_mark: You give it a target path to copy files to.
2. :negative_squared_cross_mark: No DB copy.
3. :white_check_mark: Path is configurable.
4. :negative_squared_cross_mark: No synchronized removal.
5. :question: You can just re-run the command if you want to update metadata.
6. :white_check_mark: You give it a query to select music.

**Comment by snicker** [comment]
Is there a way to skip the conversion completely? I don't need to convert the files; a copy is fine. If so, that could just do the trick!

**Comment by sampsyo** [comment]
Not *exactly*, but if you have mostly the same kind of music (e.g., MP3s), you can set the format to that (i.e., `format: mp3`) and nothing will get transcoded.

Or, if you have, say, a mixture of and FLACs and some other formats, set the format to FLAC and turn on `never_convert_lossy_files` to leave the other ones intact.

**Comment by snicker** [comment]
Just ran some tests and did some `--pretend`ing and it looks like this will
work for my needs.

Replicating some of the other features that are available (modifying
metadata upon export, truncating filenames (can you do this with `paths`?))
and an option to never transcode would pretty much nail it down completely.

**Comment by sampsyo** [comment]
You should be able to truncate paths with the `%left` path function: http://docs.beets.io/en/v1.3.14/reference/pathformat.html#template-functions

Or, of course, globally: http://docs.beets.io/en/v1.3.14/reference/config.html#max-filename-length

For the turn-off-transcoding-completely option (and other new features we could tack onto `convert`), would you mind opening a new ticket?

**Comment by snicker** [comment]
definitely. Thanks for the help.
