### ISSUE TITLE
convert: Option to turn off transcoding completely

### ISSUE THREAD

**Issue by snicker** [beetbox/beets#1620]
in using the `convert` plugin to export files to new paths for external hard drives or media players, an option to never transcode would be useful. No conversion would take place, only copying/moving files to the destination.

**Comment by nathdwek** [comment]
Maybe it would be worth it to check out [beets-alternatives](https://github.com/geigerzaehler/beets-alternatives), which seems to be more in line with what you desire to eventually achieve, and it also ticks more boxes in your previous feature request.

I don't know the exact status of the plugin however, but if there's a need for it I can maybe help you maintain it again.

**Comment by snicker** [comment]
@nathdwek giving that a whirl today, but it looks like it may be just what i need.

**Comment by Kraymer** [comment]
@snicker did beets-alternatives fullfilled your needs?

**Comment by wisp3rwind** [comment]
Closing this for now, if beets-alternatives did not fulfill your needs, feel free to reopen this issue and explain what it misses.
