### ISSUE TITLE
Error handling in Importadded

### ISSUE THREAD

**Issue by pkess** [beetbox/beets#1628]
While developing some code to improve coverage, i found the following code:

```
    def write_item_mtime(self, item, mtime):
        """Write the given mtime to an item's `mtime` field and to the mtime
        of the item's file.
        """
        if mtime is None:
            self._log.warn(u"No mtime to be preserved for item '{0}'",
                           util.displayable_path(item.path))
            return

        # The file's mtime on disk must be in sync with the item's mtime
        self.write_file_mtime(util.syspath(item.path), mtime)
        item.mtime = mtime
```

in file  [beets/beetsplug/importadded.py](https://github.com/sampsyo/beets/blob/master/beetsplug/importadded.py)

I think when mtime is None this should be a error in the programm and raise an Exception instead of write to logfile.

**Comment by sampsyo** [comment]
Hmm... Do you know the circumstances where mtime can be None? If it's something non-critical, it would be a shame to abort the whole import process for this.

**Comment by pkess** [comment]
At the moment the only invocations of this function is in importadded.py itself. and there is a check before if mtime is not None.

So i think at the moment it might be safe to add a Exception

**Comment by sampsyo** [comment]
OK, it looks like the `mtime` comes from the plugin's internal `self.item_mtime` map, and is none if the item is missing from the map. So we should be careful to understand (regardless of whether or not we make this change) how items could be missing from the map.

It could be that this is an artifact from a previous version where it was possible for this to be missing. Looking at the code, it looks like there are several cases:
* the file is moved
* it's linked
* it's copied
* none of the above
I think that covers all the cases, but I'm not 100% sure. Worth investigating.

**Comment by pkess** [comment]
I think this is not an artifact, because it was introduced with 94aad7e and i think there is still no need for the message.
Maybe @silb can help us giving us his intention?

**Comment by silb** [comment]
I guess my main intention was that mtimes not being preserved isn't important enough to abort the import job. The log message also helped during debugging / development of the plugin.

From what I can see, it should be safe to remove the `None` check in `write_item_mtime` since all the invocations are wrapped in a `None` check.

**Comment by pkess** [comment]
Ok, thank you for your fast response. If there are no other contradictions i will open a PR with removed check in `write_item_time` tomorrow.

**Comment by sampsyo** [comment]
Sounds good! Thanks for weighing in, @silb.

**Comment by pkess** [comment]
I think this is finished then. Any further discussion in #1630
