### ISSUE TITLE
AcousticBrainz plugin

### ISSUE THREAD

**Issue by nagisa** [beetbox/beets#1629]
Add an [AcousticBrainz](http://acousticbrainz.org/) plugin. See the FAQ page on how it differs from AcoustID.

Since beets is already centered around *Brainz community heavily (MusicBrainz, AcoustID), this would be a no-brainer.

**Comment by sampsyo** [comment]
Yes, sounds great! I know some people have been looking into this, so it might be worth googling a little to see if any progress was made.

**Comment by Freso** [comment]
I was the one looking into this back when, but I never made any real progress, outside of the spec. drafts, which I'd be happy to share if I can find them. In the meantime, a (half-finished, IMHO, but at least it's something) plugin is about to be committed to MusicBrainz Picard's plugin repository: musicbrainz/picard-plugins#9 - that may or may not be helpful (it's GPLv2, so should be safe to copy/paste from too).

**Comment by Sophist-UK** [comment]
See also musicbrainz/picard-plugins#41 which is also an AcousticBrainz plugin.

musicbrainz/picard-plugins#9 looks up mood and genre.

musicbrainz/picard-plugins#41 looks up musical key and BPM.

**Comment by sampsyo** [comment]
We have an initial plugin as of #1784. Future work, in case anyone's interested:

* fetch more information (we currently get just 3 fields)
* an auto mode
* analysis/submission

**Comment by Freso** [comment]
> Future work, in case anyone's interested

You know how to make GCI tasks, right? :wink:

**Comment by sampsyo** [comment]
Ha, that's a very good call, @Freso. Entering them now.

**Comment by opatel99** [comment]
I have started working on the "auto" mode. I will submit PR with code update and partnered docs.

**Comment by opatel99** [comment]
I have completed the "auto" mode and performed a pull request at https://github.com/sampsyo/beets/pull/1787
