### ISSUE TITLE
badfiles: Check on import

### ISSUE THREAD

**Issue by Schweinepriester** [beetbox/beets#1633]
How about running the badfiles-plugin on import, exactly like https://github.com/geigerzaehler/beets-check#usage-with-import (sans the checksum)?
Including the option to prevent import of a corrupted file.

Furthermore with at least mp3val an (automatic) fix could be possible?

**Comment by sampsyo** [comment]
A standard `auto` option sounds fine. Some thought will need to be put into choosing when to run the check and log messages without interrupting the main UI.

**Comment by nomadturk** [comment]
I think this can be like:

During import, check for badfiles, if there's any warning, run mp3val -f -nb OR whatever command user wants to.

Or it can be achieved whilst running beet bad command and setting autofix: yes in config.yaml

**Comment by mfiano** [comment]
I suggest adding a bad_import_action configuration option. It can take one of: ask, always, or never.

always: In this circumstance, likely the default, bad-files is never queried, and is thus faster and without any extra log messages interrupting the main UI.

never: In this circumstance, bad-files is ran, and if there are errors in any file, all files for the entire release are never imported. A single warning message for the release is displayed.

ask: In this circumstance, bad-files is ran, and for each track with errors, asks the user whether to [i]mport or [s]kip, with the output of bad-files displayed to aid them in choosing.

**Comment by sdfg2** [comment]
Yes, I came here looking for exactly this.  Perhaps a more general solution would be to add import hooks in general, so a number of plugins/commands can be run after the import process has completed?  I know that's sort of covered by auto: in a lot of plugins, but having it this way round would negate the need to have every plugin implement such a feature.

**Comment by sampsyo** [comment]
Yeah, I've always though it would be nice to provide "templates" for plugins to easily offer the same functionality on import and via an explicit command. Any help with this refactoring would be greatly appreciated.
