### ISSUE TITLE
Should beet update be moving files to new folders?

### ISSUE THREAD

**Issue by addisonamiri** [beetbox/beets#1646]
It seems from the documentation that `beet update` should be moving files to new folders but this isn't happening in action. I've found a workaround that's re-importing the files and there doesn't seem to be any problems arising from this but it's a bit annoying. I noticed it when adding the release year to an album and the folder remained `(0000) ...`. Is there anything that could be causing this or is it a bug?

**Comment by sampsyo** [comment]
Yes, `update` should move files (and does for me). Is there something special about your setup?

For changing years manually (presumably with `modify`): you probably want to use the -a (album) flag.

**Comment by addisonamiri** [comment]
I wasn't using the `-a` flag so beets might not realize that I'm modifying the whole album but shouldn't it still move the files to a new folder with the new year? Either way I'm going to close this for now and wait until I get a little more familiar with beets before bugging you anymore ;) I'll either reopen it or make a new issue if I see it happening again.

Thanks

**Comment by sampsyo** [comment]
Yes, this is indeed confusing—see #561 for more background.
