### ISSUE TITLE
badfiles: silent mode

### ISSUE THREAD

**Issue by Kernald** [beetbox/beets#1654]
Running the `badfiles` plugin on an entire collection is pretty much unreadable for now. It would be great to have different levels of verbosity:
- display all
- display only bad files
- display nothing (just a return code).

**Comment by sampsyo** [comment]
Sounds good. In fact, I'd argue that "show bad files only" should be the default mode.

**Comment by Kolbasz12** [comment]
2 cents, if showing bad files only, does this mean files with "garbage at beginning/end of file"

This seems fairly common on some media so it could still be a lot of files.  I would argue to add option to fix files and then display only ones bad after a failed fix maybe.  I dont know, could be off topic for the OP

**Comment by BeetsStudentTeam** [comment]
Hey guys, we would like to tackle this issue, if anyone is going to work on this soon let me know so we can look at other issues! We're planning to start working on this on Monday February 1st. Thanks! -Jake

**Comment by fxthomas** [comment]
I was planning on doing this but I don't have much time to hack on beets at the moment. You're good to go!

**Comment by SpirosChadoulos** [comment]
Greetings..I was thinking about tackling this issue but then I noticed tha some changes were made to the badfiles plugin. Does this mean this issue should be closed or shall I tackle it?

**Comment by sampsyo** [comment]
Oh yeah, thanks! Looks like this was fixed in #2434.
