### ISSUE TITLE
Zero plugin: only zero field if not equal to regexp

### ISSUE THREAD

**Issue by l-t-k** [beetbox/beets#1667]
Is it possible to nullify a field if, for example, the comment is not equal to "test" or, even better, "test *". In that case comments will always be erased if the field does not contain "test". I don't want to make use of the whitelist option.

**Comment by sampsyo** [comment]
You can use regular expressions. The documentation has examples. http://docs.beets.io/en/v1.3.15/plugins/zero.html

To quote the docs:

> To conditionally filter a field, use `field: [regexp, regexp]` to specify regular expressions.

**Comment by kooimens** [comment]
I've read the docs. But if I use `field:` I can only specify comments I want to remove. I like the other way around. Specify only comments I want to keep and remove everything else.

**Comment by sampsyo** [comment]
A negative lookahead assertion in your regex should do the trick. https://docs.python.org/2/library/re.html

**Comment by kooimens** [comment]
That isn't working unfortunately. Tried several things:

`    comments: [?! 'test']` gives me error:
`configuration error: zero.comments: must be a list of strings`

`    comments: [?!'test']`
`configuration error: zero.comments: must be a list of strings`

`    comments: [?!test]`
`configuration error: file /root/.config/beets/config.yaml could not be read: while parsing a flow sequence
  in "/root/.config/beets/config.yaml", line 136, column 15
expected ',' or ']', but got ':'
  in "/root/.config/beets/config.yaml", line 139, column 9`

`    comments: ?! [test] `
http://pastebin.com/wY4SZ34a

`    comments: ?!test`
http://pastebin.com/ihEymzXX

**Comment by sampsyo** [comment]
Try:

    comments: ['?!test']

**Comment by sampsyo** [comment]
Oh wait, sorry, I think the whole thing needs to be in parentheses to be a negative lookahead. You might want to try on one of those web sites that lets you fiddle with regexes.

    comments: ['(?!test)']

**Comment by kooimens** [comment]
Tried with your last suggestion. It doesn't return an error. However, all comments are nullified. Even the ones that equal 'test'. Tried the websites you mentioned and some others. I can't think of anything else than you're last suggestion tbh.

**Comment by kooimens** [comment]
`['^(?!test *)']`

I'm now using it like this. The ^ forces a search at beginning of the string. everything not equal to "test ..." is now removed.
