### ISSUE TITLE
Apply `data_source` field to albums

### ISSUE THREAD

**Issue by l-t-k** [beetbox/beets#1693]
I like to check which albums in my library are from discogs. The use of `beet list data_source:discogs` returns all the tracks I like to see. However, when using `beet list -a data_source:discogs` the return is zero. It seems like the flexible attribute data_source is a item field and an album field.

**Comment by sampsyo** [comment]
That's odd; it definitely should be applied to albums. Can you please check with `beet list` whether *any* of your music has an album-level `data_source` set?

**Comment by kooimens** [comment]
I've tried several albums, including mb and discogs, none of them is having an album-level field.
If I configure this: 
`format_item: $album - $disc$track - $artist - $title - $data_source`. I get:
`The Year 2000 - 0101 - The O'Jays - The Year 2000 - Discogs`

`format_album: $albumartist - $album - $data_source` I get: 
The O'Jays - The Year 2000 - $data_source

**Comment by sampsyo** [comment]
Thanks. I looked into it a little more—I should have remembered that we don't apply *anything* directly to album structures. (It's all just inferred from item-level data, and that doesn't include flexible attributes.)

This would be a useful thing to add.

**Comment by BeetsStudentTeam** [comment]
Hey guys, we would like to tackle this issue, if anyone is going to work on this soon let me know so we can look at other issues! We're planning to start working on this on Monday February 1st. Thanks! -Jake

**Comment by bartkl** [comment]
@jacob-elliott Have you begun working on this issue?
@sampsyo Is the idea to enable the inferring of the `data_source` field from item to album level, or more general to enable this kind of inferrence for _any_ flexible attribute? The latter sounds better to me, but then the next question would be: how to configure which flexible attributes are to be passed to the album level and which are not (config file?).

Just thinking out loud and depending on the complexity I might pick this up myself :).

**Comment by Mary011196** [comment]
Hello, 
I would like to tackle this issue,is anyone that working on this?
Thank you

**Comment by sampsyo** [comment]
Go for it, @Mary011196! Please let us know if more context would be useful.

Looks like I forgot to respond to @bartkl—oops! I'm not 100% sure about promoting arbitrary track-level fields to album-level fields. The generality is definitely a good idea, but because our metadata backends are fairly controlled, we can get the same generality by asking them to assign attributes to the `AlbumInfo` objects. That would remove the need to "guess" whether track-level data needs to be promoted.

**Comment by Mary011196** [comment]
Hello,
My first thought was to add `'data_source': types.STRING,` in class Album to the `library.py` file. Is a good start? More context would be useful. Thank you very much!

**Comment by sampsyo** [comment]
Declaring a field like that wouldn't hurt, exactly, but it's not necessary: with beets's *flexible attributes* system, you can just write `album.data_source = 'foo'` without declaring anything and it will "just work."

The local solution to this particular problem should probably go in the `ImportTask.add` method found in `beets.importer`. That's where the `Album` object is created, and that's probably the right place to add album-level data.

**Comment by Mary011196** [comment]
Hello,
If i create a field that gets the value of `album_info.data_source` in the place that you told me? 
Thank you again!

**Comment by sampsyo** [comment]
Yep! I believe (although I haven't checked) that the `data_source` field on `album_info` should be populated. (But that might be worth checking by printing out the value there.)

**Comment by Mary011196** [comment]
Hello,
I try to create this field but as you said i gοt the message that `album_info` is not defined. Even if i import the `hooks.py` file found in `beets.autotag` i gοt the same message. Isn't the `album_info` the object of `AlbumInfo`? 
Thank you!

**Comment by sampsyo** [comment]
Hmm; I'm not quite sure I understand. Maybe an error message would help?

**Comment by narendravardi** [comment]
@Mary011196, Please let me know if you are still working on this issue. 

If not, I can take this up.

**Comment by apitofme** [comment]
Any progress with this?
...from a quick check in my DB the _album_attributes_ table is still absent of _data_source_ fields!

My understanding is that there's 2 sensible options for this:
1. Determine the value at run-time from the album's items (i.e. not explicitly stored in the DB)
2. Explicitly store the value in the DB (i.e. an album-level metadata flex-attribute)

...with the consensus/preference being to store it explicitly?

> sampsyo commented on 22 May 2017
> ...
> ...this particular problem should probably go in the `ImportTask.add` method found in `beets.importer` ...

Looking at the file I wondered if `ImportTask.align_album_level_fields` would be more appropriate, which is called from `ImportTask.add` ?

**Comment by sampsyo** [comment]
Yo! I think I prefer option 2, i.e., an explicit album-level field. This sort of aligns with IDs and other information—it seems most reflective of the actual truth that the entire album came from a certain data source. (Individual tracks can also be associated with data sources independently, of course.)

And indeed; I do think `align_album_level_fields` seems like the place to do it! FWIW, the reason this isn't happening automatically is this line:
https://github.com/beetbox/beets/blob/27e0e7600d05fd7d2e36124b803120ea5cb9e3d4/beets/library.py#L1353-L1354

That is, adding an album automatically promotes all built-in fields, but `data_source` is a flexible attribute.

**Comment by apitofme** [comment]
> Mary011196 commented on 22 May 2017
> Hello,
> My first thought was to add `'data_source': types.STRING,` in class Album to the `library.py` file. Is a good start? More context would be useful. Thank you very much!

This is actually already in the _Album_ library model (along with 'path') ...

So is the issue that these fields aren't getting populated with data from their corresponding _Item_ attributes?
-- or --
That these fields aren't being saved back to the DB because the library model only elevates built-in fields?

In the case of the latter I can't see how to fix this without changing `Album.add_album` in _`library.py`_
(the section you reference) to explicitly check for the presence of additional fields coming from _`item`_ and comparing them to `Album._types` as well ... or rather (more clearly) to include the `Album._types` fields in the evaluation against the item's keys.

Something along the lines of:

```
for key in Album._types:
    Album.item_keys.append(key)
```
before the lines you referenced.

_(Sorry, still very new at all this)_

**Comment by sampsyo** [comment]
No worries; all very good questions! It's the former, with a tiny shade of the latter. All fields get saved to the database (built-in or flexible), but only built-in fields get automatically propagated during the import process from items to albums.

I don't think we want to automatically promote _all_ fields from items to albums, because some fields aren't relevant there. So I think we should change the importer rather than the library—in particular, the `align_album_level_fields` function you found earlier seems like the perfect place to do this.

**Comment by apitofme** [comment]
Okay so after a bit of playing around I seem to have something that works
...whether or not this is appropriate/acceptable is another matter and really up to someone with a lot more knowledge and experience of Python and Beets than I

beets\importer.py

```
def add(self, lib):
        """Add the items as an album to the library and remove replaced items.
        """
        self.align_album_level_fields()
        with lib.transaction():
            self.record_replaced(lib)
            self.remove_replaced(lib)
            self.album = lib.add_album(self.imported_items())

            # Apply `data_source` field to albums [#1693]
            log.info(u'-- Attempting to store album field for data_source --')
            item = self.imported_items()[0]
            log.info(u'- Item data_source is {}', item.data_source)
            self.album.set_parse('data_source', item.data_source)
            log.info(u'- Album data_source: {}', self.album.get('data_source'))
            
            self.reimport_metadata(lib)
```

Running an import:
```
X:\Development\Python\venv
(venv) λ beet -vv imp -I "X:\Music\MP3\Artists\How to Destroy Angels"
...
plugin paths:
Sending event: pluginload
lastgenre: Loading canonicalization tree x:\development\python\venv\lib\site-packages\beetsplug\lastgenre\genres-tree.yaml
inline: adding item field disc_track
inline: adding item field top_genre
inline: adding album field atype
library database: X:\Music\MP3\beet-library.db
library directory: X:\Music\MP3
Sending event: library_opened
Sending event: import_begin
Sending event: import_task_created
Sending event: import_task_start
Looking up: X:\Music\MP3\Artists\How to Destroy Angels\[2010] How to Destroy Angels [EP]
Tagging How to Destroy Angels - How to Destroy Angels
Searching for discovered album ID: c52aecba-56ba-3d75-871b-87d4293b5420
Requesting MusicBrainz release c52aecba-56ba-3d75-871b-87d4293b5420
primary MB release type: ep
Sending event: albuminfo_received
Candidate: How to Destroy Angels - How to Destroy Angels (c52aecba-56ba-3d75-871b-87d4293b5420)
Computing track assignment...
...done.
Success. Distance: 0.01
Album ID match recommendation is Recommendation.strong
ID match.

X:\Music\MP3\Artists\How to Destroy Angels\[2010] How to Destroy Angels [EP] (6 items)
Sending event: before_choose_candidate
Tagging:
    How to Destroy Angels - How to Destroy Angels
URL:
    https://musicbrainz.org/release/c52aecba-56ba-3d75-871b-87d4293b5420
(Similarity: 99.3%) (country) (CD, 2010, US, The Null Corporation, sigil 2)
Sending event: import_task_choice
Sending event: import_task_apply
0 of 6 items replaced
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
-- Attempting to store album field for data_source --
- Item data_source is MusicBrainz
- Album data_source: MusicBrainz
lastgenre: added last.fm album genre (album): Electronic
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
fetchart: trying source filesystem for album How to Destroy Angels - How to Destroy Angels
fetchart: using well-named art file cover.jpg
ImageMagick version check failed: [WinError 2] The system cannot find the file specified
ImageMagick version check failed: Command 'convert --version' returned non-zero exit status 4.
artresizer: method is (3, 0)
fetchart: image size: None
fetchart: Could not get size of image (please see documentation for dependencies). The configuration options `minwidth` and `enforce_ratio` may be violated.
fetchart: using local image X:\Music\MP3\Artists\How to Destroy Angels\[2010] How to Destroy Angels [EP]\cover.jpg
Sending event: before_item_moved
Sending event: item_moved
Sending event: database_change
Sending event: database_change
Sending event: write
Sending event: after_write
Sending event: before_item_moved
Sending event: item_moved
Sending event: database_change
Sending event: database_change
Sending event: write
Sending event: after_write
Sending event: before_item_moved
Sending event: item_moved
Sending event: database_change
Sending event: database_change
Sending event: write
Sending event: after_write
Sending event: before_item_moved
Sending event: item_moved
Sending event: database_change
Sending event: database_change
Sending event: write
Sending event: after_write
Sending event: before_item_moved
Sending event: item_moved
Sending event: database_change
Sending event: database_change
Sending event: write
Sending event: after_write
Sending event: before_item_moved
Sending event: item_moved
Sending event: database_change
Sending event: database_change
Sending event: write
Sending event: after_write
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: import_task_files
Sending event: database_change
Sending event: album_imported
Sending event: import
Sending event: cli_exit
```

Listing the imported items:
```
X:\Development\Python\venv
(venv) λ beet ls -f "$album - Track $track - Source = $data_source" destroy angels
How to Destroy Angels - Track 01 - Source = MusicBrainz
How to Destroy Angels - Track 02 - Source = MusicBrainz
How to Destroy Angels - Track 03 - Source = MusicBrainz
How to Destroy Angels - Track 04 - Source = MusicBrainz
How to Destroy Angels - Track 05 - Source = MusicBrainz
How to Destroy Angels - Track 06 - Source = MusicBrainz
```

Listing the album:
```
X:\Development\Python\venv
(venv) λ beet ls -a -f "ID: $id - $albumartist - Source = $data_source" destroy angels
ID: 147 - How to Destroy Angels - Source = MusicBrainz
```

![screenshot 2](https://user-images.githubusercontent.com/1789853/63225118-fe8e4c00-c1c4-11e9-83ce-e08242d48dd5.jpg)

---
I'm asking myself now though how to implement this to work for albums already in the database, without having to re-import them?!

**Comment by sampsyo** [comment]
Awesome; seems like the right spirit! But just for the sake of modularity, what do you think about putting this in the aforementioned `align_album_level_fields` method that gets called from `add`? We already do a lot of fiddling with the "first item" there.

**Comment by apitofme** [comment]
I tried that first, by adding the `data_source` field (and value) to the `changes` dictionary
```
def align_album_level_fields(self):
    """Make some album fields equal across `self.items`. For the
    RETAG action, we assume that the responsible for returning it
    (ie. a plugin) always ensures that the first item contains
    valid data on the relevant fields.
    """
    changes = {}

    ... contents omitted for brevity ...

    # Apply `data_source` field to albums [#1693]
    if self.items[0].data_source:
        changes['data_source'] = self.items[0].data_source
    
    # Apply new metadata.
    for item in self.items:
        item.update(changes)
```
...but as far as I could tell this was caught out by the model filtering the keys that get applied!

Since _'lib'_ is not available in the `align_album_level_fields` method  I didn't know how to get the album as an object to then apply the metadata field.
-- it didn't feel appropriate for me to modify the method to take the extra parameter and pass _'lib'_ in for that single purpose.

Maybe there's a better way to access it? -- I don't know beets well enough yet  :/

**Comment by apitofme** [comment]
I know we kind of agreed that this should be implemented in the importer, but wouldn't that mean this will only work for albums when they're imported ... i.e. `update` wouldn't fix the missing _'data_source'_ attribute for albums already in the database.

What is the reason for _not_ implementing this in the Album class in `library.py` ?
I mean, an album-level metadata attribute (even a flexible one) seems like it should be considered a more general part of an 'Album' (object/record) and not tied specifically to just one user action (i.e. import).

I think that handling it in the album library-model would mean that any process (user, internal or plugin) can utilise the functionality to store flex-attributes and keep them updated.

I just like to ask the question, show my thinking and try to get a better understanding  :)

**Comment by sampsyo** [comment]
The reason is predictability: automatically modifying album-level metadata transparently is not something we normally do, so making that happen every time or special-casing it for one field would be disruptive to people using that API. The field comes from the import process, so that's an appropriate place to take care of it.

And good point; that "align" method would indeed need to take the album as an argument! Would you mind opening a PR with your change?

**Comment by apitofme** [comment]
Of course ... I'll need to read up on creating pull-requests and things first but I will sort it out in the next day or two.

...also ... so would it be necessary to implement other methods so that the _data_source_ album-level attribute can be created during an `update` or other operations?

Thanks for your guidance with all this @sampsyo

**Comment by sampsyo** [comment]
I'd say no to other operations. This information really comes from the import process, so let's just deal with it there. For `update` in particular, we can't possibly have an effect, because `update` only reads tags from files—and `data_source` is never written to files.

**Comment by apitofme** [comment]
Ahh yes I understand, and agree. Thank you ... glad that one of us is thinking logically!

I am however having a slight problem getting this to work inside _align_ method though...

Problem: `align_album_level_fields()` is called _before_ `lib.add_album()` during the import task
...so there isn't yet an _Album_ object available to work on
...and I don't know how to create one (from a list of Items that are not yet in the database) without using `lib.add_album()`
...which of course I don't want to do from within the _align_ method  :/

The only solution I came up with (which seems a bit 'hack-ish') is to use two calls the the _align_ method... i.e. call _align_ again after the album object has been created, as follows...

```
def add(self, lib):
        """Add the items as an album to the library and remove replaced items.
        """
        self.align_album_level_fields()
        with lib.transaction():
            self.record_replaced(lib)
            self.remove_replaced(lib)
            self.album = lib.add_album(self.imported_items())
            
            # call 'align' again now that the album has been created
            self.align_album_level_fields(True)
            
            self.reimport_metadata(lib)
```

```
def align_album_level_fields(self, album=False):
        """Make some album fields equal across `self.items`. For the
        RETAG action, we assume that the responsible for returning it
        (ie. a plugin) always ensures that the first item contains
        valid data on the relevant fields.
        """
        changes = {}
        
        # Apply `data_source` field to albums [#1693]
        if album:
            log.info(u'-- Self-Album = {}', self.album)
            log.info(u'-- Attempting to store album field for data_source --')
            self.album.set_parse('data_source', self.items[0].data_source)
            log.info(u'- Album data_source set to: {}', self.album.get('data_source'))

        else:
            ... { existing functionality } ...
```

Of course it is possible to test on the existence of `self.album` implicitly, but (for now) I thought it was clearer to do it as I have shown.

Do you think this is okay?

---
About creating a PR...
- I already have a local 'clone' of the main beets repo so do I still need to 'fork' the project first or can I just create a branch for the changes?
- If I have to create a fork then is it possible to force my local repo to point to that instead, or will I have to clone my fork separately?

**Comment by sampsyo** [comment]
Ya know, I think I would just not worry about it—just doing it right in the `add` function certainly seems easier, and it's not a bad trade-off. Multiple calls to that method, however, does seem like it could get pretty messy.

You do need to fork to create a PR. And yes, you can change your `.git/config` to point to your fork. The GitHub documentation has pretty good guides about how to create pull requests.

**Comment by apitofme** [comment]
Thanks @sampsyo 

I've created a PR for this now, implemented in the `ImportTask.add()` function.
( please see: https://github.com/beetbox/beets/pull/3350 )
