### ISSUE TITLE
Allow to specify the musicbrainz ID when importing without having to wait for beet to search first

### ISSUE THREAD

**Issue by ghost** [beetbox/beets#170]
This issue was automatically migrated from Google Code.
_Original author: ryana...@gmail.com (August 17, 2012 13:57:44)_
_Original issue: https://github.com/google-code-export/beets/issues/424_

**Comment by johtso** [comment]
This would be a nice feature.

Just imported a 300+ track boxed set, that already had musicbrainz ids in the tags, and it took about 10 minutes because it was trying to do lots of matching.

**Comment by sampsyo** [comment]
Implemented in #1808!
