### ISSUE TITLE
Other database servers?

### ISSUE THREAD

**Issue by laduke** [beetbox/beets#1710]
I was reading through the issues regarding new web UI, new REST api*, and I'm wondering, can a two different processes access the sqlite database at the same time? Would you not be able to "beet import" while the webserver was running? 

I'm mostly wondering if anyone has tried migrating  their db to postgres or mysql, and how it went. Is it even possible with whatever db driver beets is using? 
- for example, https://github.com/sampsyo/beets/issues/738

**Comment by sampsyo** [comment]
Yes, multiple processes should be able to access the database concurrently. We use SQLite's transactions to make sure things don't go wrong.

I know some people have endeavored to port beets to a client/server database like Postgres, but that was a long time ago—I'm not sure if anyone actually got it working.

**Comment by bearcatsandor** [comment]
I know that for me, even with only 10k tracks, it can take a few seconds to return a query. Seeing as by the time i'm done importing i'll have around 25k, would using mysql be faster for those of us with large collections?

**Comment by sampsyo** [comment]
I'm actually skeptical that SQLite is the bottleneck—we would of course need to measure, but I would be much more likely to blame inefficient queries than the engine itself.

**Comment by jackwilsdon** [comment]
Is there a reason you closed this @laduke? It still seems like a reasonable discussion.

**Comment by laduke** [comment]
I don't even remember what I was trying to do. Don't wanna create work for people. Sorry to create  another github alert for you!
