### ISSUE TITLE
Interactive mode for modify option

### ISSUE THREAD

**Issue by pkess** [beetbox/beets#1723]
Hi,

im using the alternatives plugin to for selective synchronisation with my mp3 player. I introduced a tag "onplayer" for tracks which i can set to true to sync them to my device.
As selecting every single track and running beet modify on it is very annoying i would like to implement an interactive mode for the modify option.
Workflow could be like this:

  1. Run beets modify like you would modify e.g. a whole album, but in interactive mode:
```
beet modify -i -w "onplayer=true" "AC/DC"
```
  2. Beets will then generate a temporary file containing an output like `beet ls "AC/DC"` would do and open it with the default editor
  3. You will interactive delete all lines with tracks you don't want to modify
  4. You save and close the file
  5. Beets will list all modifications as always and requires confirmation
  6. You confirm your changes and you're finished

Any comments on this workflow?
If you agree with this feature i will start to implement this and create a pull request

**Comment by sampsyo** [comment]
Interesting idea. Have you seen the work we've recently started on the `edit` branch in #1706? We have a similar edit-in-a-text-editor approach that is actually quite similar. We're even considering supporting some kind of batch mode for that editor (although it's not in the current revision). Maybe we can fold this functionality into that effort somehow?

**Comment by pkess** [comment]
Ok,

Sadly i was not able to guess the approach  of this plugin in this short time but i will have a closer look on that in the next days.

**Comment by pkess** [comment]
Since i had a look into the edit plugin now, i would suggest the following workflow to merge the ideas
- introduce a batch mode as suggested in #1706
  - batch mode first lists tracks to apply and those can be modified in an editor
  - all standard fields and explicit selected fields are listed in a yaml style and commented out if multiple values are applied
  - you can edit the fields exactly like in the edit plugin
  - finished

The workflow in practice:
- user types `beet edit -b -e onplayer "AC/DC"`
- beets opens a file like this:

> AC/DC - Back in Black - Hells Bells
> AC/DC - Back in Black - Shoot to Thrill
> AC/DC - Back in Black - Given the Dog a Bone
> AC/DC - Back in Black - Let Me Put My Love Into You
> AC/DC - Back in Black - Back in Black
> AC/DC - Back in Black - You Shook Me All Night Long
> AC/DC - High Voltage - T.N.T.
> AC/DC - High Voltage - High Voltage

- user edits it to this:

> AC/DC - Back in Black - Hells Bells
> AC/DC - Back in Black - Let Me Put My Love Into You
> AC/DC - High Voltage - T.N.T.
> AC/DC - High Voltage - High Voltage

- beets opens a file like this:

>#album: Back in Black
>#album: High Voltage
>artist: AC/DC
>#id: 25
>#id: 28
>#id: 31
>#id: 32
>#title: Hells Bells
>#title: Let Me Put My Love Into You
>#title: T.N.T.
>#title: High Voltage
>#track: 1
>#track: 5
>#track: 5
>#track: 9
>#onplayer: true
>#onplayer: false
>#onplayer: 

- user edits it to this:

>#album: Back in Black
>#album: High Voltage
>artist: AC/DC
>#id: 25
>#id: 28
>#id: 31
>#id: 32
>#title: Hells Bells
>#title: Let Me Put My Love Into You
>#title: T.N.T.
>#title: High Voltage
>#track: 1
>#track: 5
>#track: 5
>#track: 9
>___onplayer: true___
>#onplayer: false
>#onplayer: 

(or to make it simple you just leave this in the file:
>___onplayer: true___

)
- normal list of changes and ask for confirmation
- finished

**Comment by pkess** [comment]
Any thoughts?

**Comment by sampsyo** [comment]
It seems like there might be two components to this idea:

- A separate step where you choose which items to edit.
- A batch mode where you change data en masse.

Would it make sense to break these into two orthogonal options?

Or, would it make sense to let you change *inline* which items you're editing—for example, by deleting the ones you don't want to edit?

**Comment by pkess** [comment]
>- A separate step where you choose which items to edit.

>Or, would it make sense to let you change inline which items you're editing—for example, by deleting the ones you don't want to edit?

I think both of these approaches do not really simplify the problem or the interaction

>- A batch mode where you change data en masse

I can't imagine the workflow for this mode. Could you explain it with an example?

**Comment by sampsyo** [comment]
> > A batch mode where you change data en masse
> 
> I can't imagine the workflow for this mode. Could you explain it with an example?

I meant to indicate the same thing as step 2 in your workflow---if I understand correctly, the idea is that you want to change the tags on many objects at once, as the `modify` command currently does, right?

The idea was that the task of choosing *what* to operate on and *how* to change them are actually distinct steps. For example, you could imagine wanting to use your "edit a file to choose the items" step with other commands as well. So unless we want to merge them into a single step (which might be useful!), it could be useful to keep the ideas distinct.

**Comment by sampsyo** [comment]
@pkess, have you tried the new edit plugin? Does it get close at all to what you want

**Comment by pkess** [comment]
Hi,
I tried the edit plugin when it was in a separate branch. I will have a closer  look on that tomorrow.

**Comment by pkess** [comment]
So i had a closer look now and i am not able to modify as easy as i want.
I implemented a way to fulfil my requirement and opened PR #1838. We can switch the discussion to this issue now.
