### ISSUE TITLE
consider moving beets to a github organization

### ISSUE THREAD

**Issue by jrobeson** [beetbox/beets#1730]
Once many projects get popular, they often migrate to a github organization , so it is easier to manage contributor access.

**Comment by sampsyo** [comment]
Yeah, I've considered this! It would be nice also to group together the related projects (pyacoustid, audioread, etc.). I'd love to hear people's opinions.

One silly roadblock is that the @beets username is taken on GitHub. If you're out there, @beets, can we talk about taking over your username for an excellent cause?

**Comment by beets** [comment]
Sorry but I'm quite attached to my username. I use it across many machines and have shared projects as well so please pick a different name.

**Comment by sampsyo** [comment]
:cry: OK, thanks for responding, @beets! We'll think of something else if we make the move.

**Comment by Freso** [comment]
The Twitter is @b33ts, which isn't taken on GH. I'm not exactly excited by that organisation name though. :)

**Comment by sampsyo** [comment]
Yeah, it's kind of a fun name for social media, but not exactly thrilling as our permanent home.

Other ideas: `beetsmusic` (and risk getting sued by Apple :smiley:), `beetsio` (and actually start using our corresponding domain name, beets.io). A better tactic would be to come up with a creative name for the amorphous "organization" that produces beets: MusicBrainz : MetaBrainz :: beets : ?.

**Comment by Freso** [comment]
@Beetroot? It's the "root" of the "beets". (Taken but doesn't seem to be actively used, so @Beetroot might be convinced to change their username.)
@BetaVulgaris? Perpetual beta and… vulgarity? Uhm… (Also taken, also doesn't seem to be actively used.) Maybe something similar-to-but-not-quite "vulgaris"?
@Betoideae? This is the subfamily of the beetroot plant, and is not taken.

Perhaps something with earth/soil/fertiliser?

I don't like @beetsmusic, as you have said yourself you would like to look into also handling videos possibly, and I guess beets could be used to manage just about anything with the proper plugins.
@beetsio could work with accompanying website domain.

**Comment by sampsyo** [comment]
I also went to the same place as you with @beetroot (or @beetroots or @beetsroot) and Latin names on Wikipedia. :smiley: Sadly, the genus/phylum/species names are a little complex and uninspiring.

What do you think of @taproots? It's vegetable-relevant, has a nice onomatopoeic feel, and "tap" is a near-synonym for "beat." @taproot is taken, but this project is no stranger to plurals.

Other, sillier discarded ideas: vegetables, veggies, produce, veg.

**Comment by oldtopman** [comment]
What about @beetbox ?

**Comment by jrobeson** [comment]
i was going to suggest beetsmusic.. glad you pointed out that bit about apple. I totally forgot that beats headphones and whatever were a thing :(

**Comment by sampsyo** [comment]
I love @beetbox! Fits with the whole pun thing. Here's a picture I took of a beet box.
![beets](https://cloud.githubusercontent.com/assets/188033/11262009/b9028b7e-8e2e-11e5-82b0-6e64f39de806.jpg)

**Comment by eliasp** [comment]
+1 for @beetbox - quick, register it, before someone else grabs it! :)

**Comment by pkess** [comment]
+1 @beetbox ... Sounds great

On November 19, 2015 5:26:54 AM GMT+01:00, Elias Probst <notifications@github.com> wrote:
>+1 for @beetbox - quick, register it, before someone else grabs it! :)
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/sampsyo/beets/issues/1730#issuecomment-157947570

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by Kraymer** [comment]
Calling it beetsio would consolidate the *brand* and would help switch to the new domain
beetbox is a great name to use related with beet, not so sure about using as org name

**Comment by Schweinepriester** [comment]
+1 for beetbox :D

**Comment by xsteadfastx** [comment]
+1 beetbox... sounds nice :)

**Comment by Freso** [comment]
+1 to @beetbox for me.

**Comment by m-urban** [comment]
+1 for beetbox

**Comment by claman** [comment]
I like either taproots or beetbox

**Comment by devster31** [comment]
+1 for beetbox,

**Comment by khaeru** [comment]
https://twitter.com/jonnysun/status/655932934801723396

**Comment by sampsyo** [comment]
I love that tweet.

**Comment by khaeru** [comment]
A less-frivolous contribution: some projects, like Pelican, have repositories under their organization that are a long list of Git submodules, one for each third-party [theme](https://github.com/getpelican/pelican-themes), [plugin](https://github.com/getpelican/pelican-plugins), etc.

The idea is to make it easier for users to clone them all at once. A similar repo would make sense for beets' [non-core plugins](http://beets.readthedocs.org/en/latest/plugins/index.html#other-plugins), once it moves to an org.

**Comment by sampsyo** [comment]
Oh, cool! I really like this idea.

**Comment by oldtopman** [comment]
I see that @beetbox has been registered - will this discussion/issue be closed?

**Comment by jrobeson** [comment]
beets has not yet been moved, thus the issue should stay open

**Comment by sampsyo** [comment]
Yep, I reserved the name. I plan to get around to making the move soon.

**Comment by jrobeson** [comment]
and now this issue should be closed :)

**Comment by sampsyo** [comment]
Woohoo!

I'm still getting a handle on this organization thing, so let me know if you need an invitation.
