### ISSUE TITLE
Convert MP3 default isn't gapless

### ISSUE THREAD

**Issue by smlx** [beetbox/beets#1741]
When importing losless files, the `convert` plugin's default mp3 command-line discards length information:

```
ffmpeg -i $source -y -vn -aq 2 $dest
```

Instead, I believe that the following command-line should be default:

```
ffmpeg -i $source -f wav - | lame -V 2 --noreplaygain - $dest
```

This ensures that delay/padding information is preserved in the [LAME MP3 Info Tag](http://wiki.hydrogenaud.io/index.php?title=MP3#LAME_tag), enabling gapless playback on [many devices / applications](https://en.wikipedia.org/wiki/Gapless_playback#Player_support). The downside, of course, is that the `lame` executable is required in addition to `ffmpeg`.

Would you accept a pull-request to change the default command-line, or at least document this shortcoming of the default and the alternative gapless solution?

**Comment by sampsyo** [comment]
Thanks for pointing that out; good point. Let's document it. It's nice that, for now, it's easy to describe the dependencies for the default convert configurations (you just need ffmpeg). I'm also not sure we currently support shell pipelines in the configuration, so you might need to wrap this in a shell script to get it to work.

**Comment by smlx** [comment]
I'm actually using that exact configuration line with the pipe, so it does work. :smile: 
Okay, I'll look at documenting this.

**Comment by sampsyo** [comment]
Well, that's great, at least!

**Comment by smlx** [comment]
There's a small wrinkle with this: I'm using beet 1.3.8 from Debian, which allows the pipe in the command.

As part of #1157 (in 8579412), you removed this capability. As there is no safe way of handling a malicious `$source` or `$dest`, I guess we'll need a standalone shell script to handle this case...

**Comment by sampsyo** [comment]
Got it; good point. Yes, we'll need to recommend a shell script wrapper (or some crazy special handling for shell syntax).
