### ISSUE TITLE
info needed for query with e and é 

### ISSUE THREAD

**Issue by jmwatte** [beetbox/beets#1755]
```
jmw at huba in ~/Desktop/playlists 
$ /usr/bin/beet ls boulez Répons -a
Pierre Boulez - Répons / Dialogue de l'ombre double (Ensemble Intercontemporain feat. conductor: Pierre Boulez)

jmw at huba in ~/Desktop/playlists 
$ /usr/bin/beet ls boulez Repons -a

jmw at huba in ~/Desktop/playlists 
$ /usr/bin/beet ls boulez '~Repons' -a
```

If I want to search for an album but I forgot that it should be with ``é`` I get nothing(also not with fuzzy search) Is there another way to get to that searchresult ? Because now I would have to ascify my album names to get to it(not to mention my titles :-) ).  Is this something for a plugin? Or a global option for the list command? Or something else?  Any kick in the right direction is welcome.
thx
jm

**Comment by diego-plan9** [comment]
Coincidentally, I have also run across some similar case while doing some searches on my library (which contains a bunch of Spanish songs, some of them not properly having the diacritic characters), but did not investigate further.

Perhaps adding some code that uses [NFKD unicode normalization](https://docs.python.org/2/library/unicodedata.html#unicodedata.normalize) to the `fuzzy` plugin should be enough? I'm not sure if sqlite provides some mechanism for making 'accent-insensitive' queries so this could be handled at the DB level (the closest I could find is using a [collation](http://www.sqlite.org/datatype3.html#collation)); in any case, I would personally welcome some mechanism for solving this issue.

**Comment by sampsyo** [comment]
Hmm... the fuzzy plugin definitely *should* work for this case. Does it ever work for strings with accents, or does it seem totally broken? How about when usi a field qualifier like `album:~repons`?

**Comment by jmwatte** [comment]
strange... sometimes ``fuzzy`` does sometimes ``fuzzy`` don't
```
$ beet ls Järvi -a
Neeme Järvi - Symphony No. 1 in F minor, Op. 10
Neeme Järvi - Symphony No. 12 in D minor, Op. 112
Neeme Järvi - Symphony No. 13 in B flat minor, Op. 113
Neeme Järvi - Symphony No. 14, Op. 135
Neeme Järvi - Symphony No. 15
Neeme Järvi - Symphony No. 2 in B major, Op.14
Neeme Järvi - Symphony No. 3 in E flat major, Op. 20
Neeme Järvi - Symphony No. 6 in B minor, Op. 54
Neeme Järvi - Symphony No. 9 in E flat major, Op. 70


$ beet ls '~Jarvi' -a
Travis - The Man Who


$ beet ls albumartist:'~Jarvi' -a
Travis - The Man Who

```
But if I do
```

$ beet ls albumartist:'~Neeme Jarvi' -a
Neeme Järvi - Symphony No. 1 in F minor, Op. 10
Neeme Järvi - Symphony No. 12 in D minor, Op. 112
Neeme Järvi - Symphony No. 13 in B flat minor, Op. 113
Neeme Järvi - Symphony No. 14, Op. 135
Neeme Järvi - Symphony No. 15
Neeme Järvi - Symphony No. 2 in B major, Op.14
Neeme Järvi - Symphony No. 3 in E flat major, Op. 20
Neeme Järvi - Symphony No. 6 in B minor, Op. 54
Neeme Järvi - Symphony No. 9 in E flat major, Op. 70
Jessie Ware - Tough Love
Jane Weaver - The Silver Globe

```

and with the Boulez case I got to give all of this to get a hit

```

$ beet ls boulez album:'~repons /  Dialogue de l ombre double (Ensemble Intercontemporain' -a
Pierre Boulez - Répons / Dialogue de l'ombre double (Ensemble Intercontemporain feat. conductor: Pierre Boulez)

```

So ``fuzzy`` takes into account the length of the string but like in the Boulez case shows, that is not the most practical thing

Another example
```
$ beet ls artist:spektor title:'~bon idee'
Regina Spektor - Begin to Hope - Field Below
Regina Spektor - Songs - Bon idée

$ beet ls artist:spektor title:'~idee'
Regina Spektor - Begin to Hope - Edit
```
You get the idee :)
So it would really be nice if we could make the search for les accents aigu/grave more idiot-proof.

**Comment by sampsyo** [comment]
:)

Yes, that is certainly a weird thing for the fuzzy plugin to do---it would be nicer if it worked like a fuzzy *substring* match rather than a fuzzy *exact* match. I'm all for fixing this.

And, as a separate issue, there's definitely an argument to be made that queries should let you ignore Unicode details like accents by default. The only problem is that this could make ordinary queries much slower. Since SQLite itself can't do ASCIIfication, we'd be stuck doing a full scan in Python. (This technique is called a "slow query" in beets, for good reason.)

So perhaps the best solution here is just to fix the fuzzy plugin?

**Comment by thevorpalblade** [comment]
Couldn't one use the icu extension for something like this? Or overload the sqlite ````LIKE```` operator?
references:
https://www.sqlite.org/src/artifact?ci=trunk&filename=ext/icu/README.txt
https://www.sqlite.org/faq.html#q18

**Comment by sampsyo** [comment]
Yeah, Unicode data tables are what we need—but, unless I'm misunderstanding, the SQLite ICU stuff only applies to casing?

**Comment by thevorpalblade** [comment]
You may be totally right! I was taking the example of the "dotless i" mentioned in the section:
  1.2  Unicode Aware LIKE Operator
to imply that the ````LIKE```` operator also munged the Unicode to the closest ascii equivalent (which, of course, is a phenomenally difficult problem in general!)

**Comment by sampsyo** [comment]
Marking this question as resolved, even though the situation isn't awesome. :confused:
