### ISSUE TITLE
discogs: On vinyl releases, "sides" treated as "disks"

### ISSUE THREAD

**Issue by m0nkey-br4in** [beetbox/beets#1762]
I've retagged this release recently: http://www.discogs.com/Various-1989-Hustlers-Convention-Live/release/404846
And noticed afterwards, that iTunes shows me it's on two disks, which is clearly wrong. Then i've found more releases that show up with more disks than they really had.

**Comment by sampsyo** [comment]
Thanks for reporting. Yep, this is wrong (and inconsistent with MusicBrainz, of course).

**Comment by diego-plan9** [comment]
Closing after adding support for two-sided media at #2222. Please note that the detection of two sided media is based on whether all the `track.mediums` are single consecutive letters (ie. A1 B1 C1 -> disc one: AB, disc two: C) and *not* by checking the `formats` discogs API field.
