### ISSUE TITLE
[HowTo] Modify/Duplicate MusicBrainz tags to personal tags?

### ISSUE THREAD

**Issue by fohrums** [beetbox/beets#1764]
When importing tracks with `beets` and the fact that it has found *matching-sources* with `MusicBrainz`, then  how would I be able to duplicate the *fetched-tags* to a more personalized tag mapping in my complete control? I'll give you an example and my reasoning behind it.

For example:
=
Assuming I have successfully imported a release that fetched-tags via MusicBrainz `Capital STEEZ ‎– AmeriKKKan Korruption (2012)`

Now MusicBrainz has their own specialized *tag-mapping* and I want to take the following tags (written in `Foobar2000's` tagmapping format):
- %MUSICBRAINZ MEDIA TYPE%
- %MUSICBRAINZ RELEASE TYPE%

and have them be duplicated to (written in `beets` tagmapping format):
- $mediatype
- $releasetype

Reason
=
The reason being is that it's more personalized and entirely within my control to use custom tags that are considered to be more universal. This is because, **I have found a flaw in MusicBrainz's monolithic tag-mapping criteria relating to consistency**. This is all due to how we identify albums/compilations/tracks/bootlegs, as they should all simply be labeled as *releasetype* whether it's a free body of work or not and it's a universal identifier for all considered.

Now MusicBrainz does have tags that don't begin with their brand name, e.g.:
- %releasestatus%
- %releasecountry%

So, why not make the same stylized tag-mapping format for all tags found from MusicBrainz and instead use the universal tag-mapping format that compliments the entirety of having a music-library?

So, in the end I want to use the universal identifier route and essentially remove the MusicBrainz prepended title that serves as a tag-mapping criteria.

**Comment by sampsyo** [comment]
To clarify: Are you saying that you want to take the field that beets calls `$albumtype` and choose exactly how it is written into your tags?

If I understand correctly, this only makes sense as long as you're not talking about ID3 or MPEG-4 tags, but rather some more extensible tag format like Vorbis comments, right? Or perhaps you mean the description field of an ID3 TXXX frame?

There is currently no way to customize the specific tag storage details for various formats in beets. This is mostly because it's not clear how to do so in general. The Vorbis comments name or TXXX description for a given field makes sense to change, but there is a very large number of these strings—and some fields and formats don't even match this pattern of customization. It would be interesting to hear specific proposals about how the configuration interface would work. Do you have any ideas?

**Comment by fohrums** [comment]
> sampsyo - "this only makes sense as long as you're (using these formats): ID3, MPEG-4, etc."

It's strange, but I never considered this is important, primarily due to me using Foobar2000 as my main media player, it can do all sorts of things. Most particularly, i'm able to add any *field/tag* I plan to use.

Is this all for context-purposes like media players being able to properly read a tag (if they're not able to do so then it's out of the question)?

I've customized my foobar2000 to be able to display my custom tag mappings for easy access to view/edit:
![my foobar2000 setup](http://s18.postimg.org/ck2a5riyh/Untitled_2.jpg)

**Comment by sampsyo** [comment]
Yes, Foobar is showing you a simplified version of what's going on. Here's the difference that makes this easy for Foobar and hard for beets:

- Foobar works directly on individual files, with no abstraction layer. When you're hand-modifying a specific file's tags, it's OK to give you direct control over how those tags work for that specific file format.
- Beets works with an indirection layer, so `albumtype` is `albumtype` regardless of the underlying file format. On ID3, it's a TXXX frame with the description "MusicBrainz Album Type". On MP4, it's a "----:com.apple.iTunes:MusicBrainz Album Type" frame. On most others, it's called "MUSICBRAINZ_ALBUMTYPE". And things can get much more complex than that. There's no way for `beet modify` to refer to the underlying storage mechanism—it's not even aware of which format the file is, much less the particular strategy for storing data in it.

So yes, in summary, the world is more complicated than Foobar2k is making it appear. It's not clear how we can preserve the simplicity of beets while offering this flexibility.
