### ISSUE TITLE
ftintitle Plugin Question

### ISSUE THREAD

**Issue by jswanson04** [beetbox/beets#1766]
First off, I want to say this is more of a question of functionality than a full-blown issue.  I could not find a good place to ask the question.  Please feel free to point me in the right direction if this is not the location for my question/issue.

Background:  I am a first time Beets user, and I am trying to import my music and tag everything.  I am running Beets as a Docker on an Unraid Box (not sure if that really matters) version 1.3.15.

Issue: I am trying to get the "ftintitle" plugin to work.  I too would like to have 1 folder for the main artist and many folders etc (Ex. "Artist 1", "Artist 1 feat. Artist 2", "Artist 1 feat. Artist 3".  I want only a "Artist 1" folder).

I have the following in my config file:
'ftintitle:
    auto: yes
    drop: no
    format: feat. {0}'

When I run 'beet ftintitle' it just comes back, not changes to my library.  (There are songs which have "Artist 1 feat. Artist 2" in my test library.

Also another weird thing was when I imported a soundtrack and ran the `beet ftintitle` it told me there was "No featured artists found" for those songs, but ignored the rest.

Also note, it is not being run on import when it should be.

Am I missing something in the setup? Is there some more logging I can turn on to see what is going on?

Please let me know if you need anymore information.

Thank you in advance.

**Comment by sampsyo** [comment]
Discussion tickets on GitHub are fine! We also have a mailing list on Google Groups, FWIW.

Can you please give specific examples of the songs that this is failing on? Show the current metadata using `beet list` or `beet info`. Then show what happens when you run `beet -v ftintitle` on the same music.

Can you also try turning off those extra config options, like `drop`, to see whether they're to blame?

**Comment by jswanson04** [comment]
Thanks for the info and direction, here is what I did:

Remove all the config options for `ftintitle` in my config file

I have 2 test files 1 with no feat. artists and 1 with.

Here are my outputs after a clean import.
```
beet list
Avicii - Wake Me Up - Wake Me Up
Avicii feat. Salem Al Fakir - Silhouettes - Silhouettes (original radio edit)
```

```
beet info /music3
/music3/Avicii/Wake Me Up/01 - Wake Me Up.mp3
album: Wake Me Up
albumartist: Avicii
albumartist_credit: Avicii
albumartist_sort: Avicii
albumstatus: Official
albumtype: single
art: False
artist: Avicii
artist_credit: Avicii
artist_sort: Avicii
bitdepth: 0
bitrate: 250169
bpm: 0
channels: 2
comp: False
country: US
date: 2013-06-25
day: 25
disc: 1
disctotal: 1
encoder: FRAY
format: MP3
genre: Pop
genres: Pop
language: eng
length: 249.730612245
lyrics:
mb_albumartistid: c85cfd6b-b1e9-4a50-bd55-eb725f04f7d5
mb_albumid: 250a6ba9-c347-421e-a60b-e8c727dfd92e
mb_artistid: c85cfd6b-b1e9-4a50-bd55-eb725f04f7d5
mb_releasegroupid: 8243edf0-1c84-4c5e-b693-811b1a2ef070
mb_trackid: b437fbda-9c32-4078-afa2-1afb98ff0d74
media: Digital Media
month: 6
original_date: 2013-06-25
original_day: 25
original_month: 6
original_year: 2013
rg_track_gain: -8.8
samplerate: 44100
script: Latn
title: Wake Me Up
track: 1
tracktotal: 1
year: 2013

/music3/Avicii feat. Salem Al Fakir/Silhouettes/01 - Silhouettes (original radio edit).mp3
album: Silhouettes
albumartist: Avicii feat. Salem Al Fakir
albumartist_credit: Avicii feat. Salem Al Fakir
albumartist_sort: Avicii feat. Al Fakir, Salem
albumstatus: Official
albumtype: single
art: False
artist: Avicii feat. Salem Al Fakir
artist_credit: Avicii feat. Salem Al Fakir
artist_sort: Avicii feat. Al Fakir, Salem
bitdepth: 0
bitrate: 320117
bpm: 0
channels: 2
comments: Sound Of Bass
comp: False
country: XW
date: 2012-04-27
day: 27
disc: 1
disctotal: 1
encoder: Lame 3.98.4 (VBR -V0)
format: MP3
genre: House
genres: House
label: Universal Music AB
language: eng
length: 211.88
lyrics:
mb_albumartistid: c85cfd6b-b1e9-4a50-bd55-eb725f04f7d5
mb_albumid: 45239ebf-6ad9-4750-a120-30e1ca5a5276
mb_artistid: c85cfd6b-b1e9-4a50-bd55-eb725f04f7d5
mb_releasegroupid: 616e4b0e-d523-487b-b418-4a0d6c948da8
mb_trackid: 47130ac0-a5d4-42f7-bdbf-ea71810f5fa3
media: Digital Media
month: 4
original_date: 2012-04-27
original_day: 27
original_month: 4
original_year: 2012
rg_track_gain: -8.5
samplerate: 44100
script: Latn
title: Silhouettes (original radio edit)
track: 1
tracktotal: 2
year: 2012
```

I then ran:
```
beet -v ftintitle
user configuration: /config/config.yaml
data directory: /config
plugin paths:
Sending event: pluginload
library database: /config/musiclibrary3.blb
library directory: /music3
Sending event: library_opened
Sending event: database_change
Sending event: write
Sending event: after_write
Sending event: database_change
Sending event: write
Sending event: after_write
Sending event: cli_exit
```

At this point I was expecting the file '/music3/Avicii feat. Salem Al Fakir/Silhouettes/01 - Silhouettes (original radio edit).mp3' to be move/renamed to '/music3/Avicii/Silhouettes/01 - Silhouettes (original radio edit) ft. Salem Al Fakir.mp3'.  That is the indented functionality correct?  Want to make sure I'm not too crazy.

The file was not renamed on the system, so I ran the `list` and `info` again to see if the library was updated 

```
beet list
Avicii - Wake Me Up - Wake Me Up
Avicii feat. Salem Al Fakir - Silhouettes - Silhouettes (original radio edit)
```

```
beet info /music3
/music3/Avicii/Wake Me Up/01 - Wake Me Up.mp3
album: Wake Me Up
albumartist: Avicii
albumartist_credit: Avicii
albumartist_sort: Avicii
albumstatus: Official
albumtype: single
art: False
artist: Avicii
artist_credit: Avicii
artist_sort: Avicii
bitdepth: 0
bitrate: 250169
bpm: 0
channels: 2
comp: False
country: US
date: 2013-06-25
day: 25
disc: 1
disctotal: 1
encoder: FRAY
format: MP3
genre: Pop
genres: Pop
language: eng
length: 249.730612245
lyrics:
mb_albumartistid: c85cfd6b-b1e9-4a50-bd55-eb725f04f7d5
mb_albumid: 250a6ba9-c347-421e-a60b-e8c727dfd92e
mb_artistid: c85cfd6b-b1e9-4a50-bd55-eb725f04f7d5
mb_releasegroupid: 8243edf0-1c84-4c5e-b693-811b1a2ef070
mb_trackid: b437fbda-9c32-4078-afa2-1afb98ff0d74
media: Digital Media
month: 6
original_date: 2013-06-25
original_day: 25
original_month: 6
original_year: 2013
rg_track_gain: -8.8
samplerate: 44100
script: Latn
title: Wake Me Up
track: 1
tracktotal: 1
year: 2013

/music3/Avicii feat. Salem Al Fakir/Silhouettes/01 - Silhouettes (original radio edit).mp3
album: Silhouettes
albumartist: Avicii feat. Salem Al Fakir
albumartist_credit: Avicii feat. Salem Al Fakir
albumartist_sort: Avicii feat. Al Fakir, Salem
albumstatus: Official
albumtype: single
art: False
artist: Avicii feat. Salem Al Fakir
artist_credit: Avicii feat. Salem Al Fakir
artist_sort: Avicii feat. Al Fakir, Salem
bitdepth: 0
bitrate: 320117
bpm: 0
channels: 2
comments: Sound Of Bass
comp: False
country: XW
date: 2012-04-27
day: 27
disc: 1
disctotal: 1
encoder: Lame 3.98.4 (VBR -V0)
format: MP3
genre: House
genres: House
label: Universal Music AB
language: eng
length: 211.88
lyrics:
mb_albumartistid: c85cfd6b-b1e9-4a50-bd55-eb725f04f7d5
mb_albumid: 45239ebf-6ad9-4750-a120-30e1ca5a5276
mb_artistid: c85cfd6b-b1e9-4a50-bd55-eb725f04f7d5
mb_releasegroupid: 616e4b0e-d523-487b-b418-4a0d6c948da8
mb_trackid: 47130ac0-a5d4-42f7-bdbf-ea71810f5fa3
media: Digital Media
month: 4
original_date: 2012-04-27
original_day: 27
original_month: 4
original_year: 2012
rg_track_gain: -8.5
samplerate: 44100
script: Latn
title: Silhouettes (original radio edit)
track: 1
tracktotal: 2
year: 2012
```

Please let me know if there is anything else I can do or try

**Comment by sampsyo** [comment]
Yep, you're expecting the right thing! I think the problem is this:

    albumartist: Avicii feat. Salem Al Fakir

The plugin wants to work on songs where the `albumartist` is the single "real" artist and the plain `artist` field has the "feat." in it. Here, the "feat." shows up in *both* artist names. I think it would work if the `albumartist` were just `Avicii`. Perhaps you can confirm this using something like `beet modify albumartist=Avicii ...` as a test.

**Comment by jswanson04** [comment]
Ahh that makes so much sense!  I missed it.  Modified the tags and then ran
```
beet -v ftintitle
user configuration: /config/config.yaml
data directory: /config
plugin paths:
Sending event: pluginload
library database: /config/musiclibrary3.blb
library directory: /music3
Sending event: library_opened
Sending event: database_change
Sending event: write
Sending event: after_write
ftintitle: /music3/Avicii feat. Salem Al Fakir/Silhouettes/01 - Silhouettes (original radio edit).mp3
ftintitle: artist: Avicii feat. Salem Al Fakir -> Avicii
ftintitle: title: Silhouettes (original radio edit) -> Silhouettes (original radio edit) feat. Salem Al Fakir
Sending event: database_change
Sending event: write
Sending event: after_write
Sending event: cli_exit
```

Confirmed with
```
beet list
Avicii - Silhouettes - Silhouettes (original radio edit) feat. Salem Al Fakir
Avicii - Wake Me Up - Wake Me Up
```

That makes sense, but the physical file was still not updated.  Is there a separate config for that?  Also thank you for your help and quick responses.

**Comment by sampsyo** [comment]
Great!

It should write to the tags if you have import.write enabled (I think?). Otherwise you can use `beet write` explicitly.

**Comment by Kxze** [comment]
I patched the FtInTitle plugin to always assume the first artist in the artist string is the main artist in case both fields are equal. I can submit it as a pull request if the maintainers find it would be useful.

**Comment by sampsyo** [comment]
Sounds interesting! A pull request would certainly help clarify the behavior. Would it make sense for that to be an option (i.e., configurable)?

**Comment by Kxze** [comment]
Yup, that's what I was thinking. My Python's a little rusty, so I'll clean up the code where I can and submit a PR.

**Comment by trapd00r** [comment]
What's the status of this? I, too, would want a single directory per main artist. I've tried all the snippets in this thread but nothing seems to be working properly.
