### ISSUE TITLE
reimport files: old folder won't get deleted always

### ISSUE THREAD

**Issue by mankoell** [beetbox/beets#1772]
I've some files in my lib accidentally imported as Albums, I'm going to reimport now as single tracks. I'm using `beet import -As foo/` as I dont need to autotag again and want to reimport them as singletons. Also I've set up beets to move files. Now when I'm reimporting tracks this way, the old folder won't get deleted. This happens only to folders with a cover art image in there. I would prefer to keep the cover and go with the moved files within the non-albums folder.

I think I imported the files first as (fake) albums as I wanted to have at least a cover art fetched and embedded with, even if it isnt the right one. I dont know if this makes sense on singleton tracks.

**Comment by sampsyo** [comment]
The trouble, I think, is that singletons (non-album tracks) can't have associated album art files. You might consider embedding the image into the tracks and then deleting the original image file if that's what you need. Does that make sense?

**Comment by mnlgn** [comment]
Yes, I thought about the same. But still isn't solving the issue with the empty folders left behind. The same happens if I import single tracks from a folder, after all files moved to my lib, the folder is still there (empty).

**Comment by sampsyo** [comment]
Well, in that case, I think this is an instance of #130. Namely, we don't prune the top-level directory given on the command line (or anything above it), because this can be surprising for users when they import a "Music" container and don't want it to disappear. Does this sound like what's going on?

**Comment by mnlgn** [comment]
Yes, but what about the folder with `cover.jpg` left behind on moving? :crying_cat_face: 
This wouldn't be the expected behaviour with `fetchart` plugin.

**Comment by sampsyo** [comment]
The fetchart plugin doesn't run on singleton imports, so the image doesn't go anywhere. Does that explain it?

**Comment by sampsyo** [comment]
Timing out. Please reopen if things aren't clear.
