### ISSUE TITLE
comp field not recognized for compilation path

### ISSUE THREAD

**Issue by smittie** [beetbox/beets#1773]
Kubuntu 14.04 LTS
beets 1.3.15 installed unmolested using pip
no plugins enabled
Kid3 v3.0.2 used to view and edit ID3 tags.

I set up beets mostly as it is in the QuickStart/HowTo.
I have compilation albums that are recognized by MusicBrainz, appear to have all of the compilation related fields set appropriately yet nothing ends up on the comp: <pathToComps> path.
I am using beets import <path> and beets import -A <path> to manipulate my library.

-=-=-=-=-=-=-=-=-=-=-=-=-=-=-
config.yaml
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-
directory: ~/new_music
library:   ~/.config/beets/musiclibrary.blb
import:
    write:        yes
    move:         yes
    resume:       yes
    group_albums: no
paths:
    default:               $albumartist/$album/$track $title
    singleton:             $albumartist/Singles/$title
    comp:                  $album/$track $title
    albumtype:soundtrack:  Soundtrack/$album/$track $title

**Comment by smittie** [comment]
Adding "albumtype:compilation: Compilations/$album/$track $title" to config.yaml does cause compilations to get filed as expected.

**Comment by sampsyo** [comment]
Can you verify that the comp flag is set with this command?

	$ beet ls -af '$comp' ...

(Use a query to select one of the problematic albums.)

**Comment by Kernald** [comment]
When you add `albumtype:compilation: Compilations/$album/$track $title` as a check, are you replacing the `comp:` line, or adding it at the end? I had a similar issue where I had to move the `comp:` line *after* the `albumtype:soundtrack` one (all my compilations are also tagged as soundtracks on MusicBrainz, so it was kind of logical).

**Comment by sampsyo** [comment]
Yes, they're checked in order (as described in the docs).

**Comment by sampsyo** [comment]
Timing out. Please reopen, @smittie, if there's still a problem here.
