### ISSUE TITLE
"beet move -p" lists non-moves for all tracks in library?

### ISSUE THREAD

**Issue by BrianZbr** [beetbox/beets#1777]
If I run `beet move -p`, the head of the output looks like this

```
Moving 2442 items.
/home/dowcet/my/music/all/+One/Bare Necessities/01 Sticker.mp3 
  -> /home/dowcet/my/music/all/+One/Bare Necessities/01 Sticker.mp3
/home/dowcet/my/music/all/+One/Bare Necessities/02 Nibble.mp3 
  -> /home/dowcet/my/music/all/+One/Bare Necessities/02 Nibble.mp3
```

As far as I can tell, these are non-changes, while some actual changes are buried in a long list of these not-very-helpful lines. What I would expect instead is that only actual file moves should be listed. 

Am I missing something? Can I do something differently to get what I want (i.e. a list of actual file moves that would occur without `-p`)?

**Comment by sampsyo** [comment]
Please see #1583.
