### ISSUE TITLE
write tags after manual replaygain

### ISSUE THREAD

**Issue by medyagh** [beetbox/beets#1782]
I did a manual replay gain on part of my album using a query, and now when I check the tags they are not written on the file, do I need to do something to make that happen?

**Comment by jackwilsdon** [comment]
Have you tried running `beet write`?

**Comment by medyagh** [comment]
yes I have tried beet write, and still I can't see the tag. do I need to enable some sort of sepecial tag format ? ( I use default options)

**Comment by sampsyo** [comment]
No, it should work out of the box.

What software are you using to look for the data? Does `beet info` show it? (That's from the `info` plugin, which you might need to enable.) There's a chance that whatever you're using just expects a different format from beets.

**Comment by medyagh** [comment]
ok I confirm beet info does show it, however all the tools I tried in linux didn't show it. for example
EasyTag,
Quod Libet,
GmusicBrowser.

**Comment by sampsyo** [comment]
OK—can you describe exactly what happens in those tools so we can see what's going on? For example, you could find another file that EasyTag *can* see the RG tags on. What does it say differently for that file vs. the beets-tagged file? And, can you provide sample files so we can compare locally?

**Comment by sampsyo** [comment]
Timing out. Feel free to reopen if you have more information, @medyagh.
