### ISSUE TITLE
edit plugin doesn't rename folders

### ISSUE THREAD

**Issue by stp242** [beetbox/beets#1804]
when I do:
`beet edit album:"somealbum"`

and change the album artist, the folder doesn't get renamed.

using beets 1.3.16 on OS X 10.9

**Comment by sampsyo** [comment]
Thanks! This is indeed a bug. Addressing it now.

**Comment by sampsyo** [comment]
Fix pushed. Would you mind taking a look to see if this fixes it for you?

**Comment by stp242** [comment]
thank you for the quick update

the path still remains the same :confused:

**Comment by sampsyo** [comment]
Can you give a few more details about what's going on? Your configuration and an example showing your modification would help.

**Comment by stp242** [comment]
here's my config: https://gist.github.com/stp242/fb1f07e9a100603aa271

so I do:
`beet -v edit album:"fulfilled wish"`
output: https://gist.github.com/stp242/83ff078640419660deea

but if I do:
`beet -v mod -aw album:"fulfilled wish" year=2007`
it gets renamed correctly, output: https://gist.github.com/stp242/f6efced9fa93fa8c13cf

**Comment by sampsyo** [comment]
As with the `modify` command, you'll need to use the `-a` flag when editing album-level fields. Does that help?

**Comment by stp242** [comment]
for some reason I haven't been able to use that option:

`beet edit: error: no such option: -a`

**Comment by sampsyo** [comment]
Very strange! This works fine here:

    $ beet edit -a
    <editor opens>

Any chance you have an older git checkout?

**Comment by stp242** [comment]
I tested it in a virtual machine with linux and now it works :smiley:
I will try to reinstall pip/python on OS X.

also it looks a lot different inside the editor this time, some fields like label and year are missing. do you know if that's on purpose? it would be great to have them again

thanks a lot for the help :smiley:

**Comment by sampsyo** [comment]
Huh! Sounds like you probably had a pre-release version checked out.

It's now possible to configure the set of fields that gets displayed. The docs for the plugin can help you out with that.
