### ISSUE TITLE
Paths for multidisc files

### ISSUE THREAD

**Issue by Psirus** [beetbox/beets#1811]
I'm trying to have multiple discs of the same release under different directories, such as "Disc 1" for example. This is also explained in the [FAQ](https://beets.readthedocs.org/en/latest/faq.html#create-disc-n-directories-for-multi-disc-albums). Unfortunately, it does not work for me. The item field multidisc is set correctly, as seen when I do `beet list multidisc:1`. However, the tracks are all collected in one folder.

My config

    directory: ~/Musik
    library: ~/.config/beets/library.blb
    import:
        move: yes
    plugins: fetchart lastgenre inline
    fetchart:
        minwidth: 300
    path:
        default: $albumartist/$album%aunique{}/%if{$multidisc,Disc $disc/}$track $title
        comp: Various Artists/$album%aunique{}/%if{$multidisc,Disc $disc/}$track $title
    item_fields:
        multidisc: 1 if disctotal > 1 else 0

**Comment by sampsyo** [comment]
Huh, that's strange—the configuration looks fine, and things work correctly on my machine. Any chance you still need to run `beet move` since you updated your configuration?

You can also try something like `beet ls -f '%if{$multidisc,Disc $disc/}'` to test that specific part of the format.

**Comment by Psirus** [comment]
I noticed this on a new import after changing the configuration. The format test `beet ls -f ....` went fine, giving the expected output. When doing `beet move multidics:1 -p`, beets selects the right items, but the paths are as they were:

    /home/psirus/Musik/Red Hot Chili Peppers/Stadium Arcadium/01 Dani California.flac 
      -> /home/psirus/Musik/Red Hot Chili Peppers/Stadium Arcadium/01 Dani California.flac

Looking at this album, beets also apparently numbered the tracks continuously, i.e. track 1 on disc 2 is track 15. Which is fine by me, as long as they are in seperate folders.

**Comment by sampsyo** [comment]
Oh! I just noticed the typo in your configuration: it should be `paths:`, not `path:`.
