### ISSUE TITLE
Option to control metadata block padding to keep data aligned on deduplicating filesystems

### ISSUE THREAD

**Issue by snorrej** [beetbox/beets#1813]
I need to keep two sets of my collection, one set for tagging to my liking, an one untouched set.

To save some space, I enabled deduplication on my zfs file system, and made a copy of my untouched files. 

While beets was doing its job, I noticed the dedup ratio was decreasing way faster than expected.

Investigating the files in an hex editor before and after tagging, shows that the actual music data is starting at a different place and is making all the files not deduplicate at all.

**Comment by sampsyo** [comment]
I think that's a necessary consequence of updating tags on most formats. Is the idea that we should waste space in files' headers so the audio data stays at a constant offset when the tags get shorter? What if the tags get longer (the common case)---wouldn't that make this impossible?

**Comment by snorrej** [comment]
Every file I cheeked (flac) had plenty of space for tags before the audio data. Around 10% of 1kB was used for tags. Beets seems to increase the header space to around 12kB even if it's not needed and the new tags would fit in that 1kB space.

The default record size on ZFS is 128K(Byte?), so in case there is not enough space for the new tags, maybe the audio data could be shifted by increments of 128KB. 

I would happily waste 128KB in order to save 40MB.

**Comment by sampsyo** [comment]
Well, it actually wouldn't be crazy if new tags, especially if including embedded images or lyrics, would take up 12k. Can you provide sample files that show exactly what's going on—or, even better, data from hex dumps (or whatever) showing the phenomenon and theorizing about why Mutagen is adding the empty space?

**Comment by snorrej** [comment]
Tags/header before beets import
![tags-before](https://cloud.githubusercontent.com/assets/10185318/12483948/00466676-c058-11e5-8223-c0e7ff2cb8d1.png)

Tags/header after beets import
![tags-after](https://cloud.githubusercontent.com/assets/10185318/12483954/06a90668-c058-11e5-8e0a-52c9b1d8947b.png)

Data start location before import
![data-start-location-before](https://cloud.githubusercontent.com/assets/10185318/12483962/124f50bc-c058-11e5-9f95-84b6a735ecea.png)

Data start location after import
![data-start-location-after](https://cloud.githubusercontent.com/assets/10185318/12483964/14a7db2c-c058-11e5-9356-57414bbe1433.png)

New in Mutagen 1.31 is a padding control API 
https://mutagen.readthedocs.org/en/latest/changelog.html
https://mutagen.readthedocs.org/en/latest/tutorial.html#padding

**Comment by sampsyo** [comment]
Great! Thanks for the extra details.

This sounds like a fine direction if we can sort out exactly how the option would work.

**Comment by lazka** [comment]
mutagen >= 1.31 should not add unnecessary padding, only in case there is not enough space. I think this can be closed.

**Comment by lazka** [comment]
To expand on the aligning. To use the padding API you can do something like:

```
def padding_align(info):
    default = info.get_default_padding()
    align = 1024 * 128
    if info.padding < 0:
        return ((default + align - 1) // align) * align - (-info.padding % align)
    else:
        return default

tags.save(padding=padding_align)
```

but there is no 100% guarantee that the audio offset will change by that amount. There are multiple ways to add padding to a file and some overhead might depend on the size etc.

**Comment by sampsyo** [comment]
Great; thank you. I think we will avoid using the explicit padding API for now, but it's good to know that it exists.
