### ISSUE TITLE
Importer hangs on lost internet connection

### ISSUE THREAD

**Issue by klingtnet** [beetbox/beets#1816]
I've a fairly large music collection that I want to tag using beets importer, and this process takes more than 24h to complete because of the 1s per request rate limiting of discogs and musicbrainz.
My ISP resets my internet connection every 24 hours to give me a new IP.
Beets will hang after the reconnect without showing any error message.
The preferred behaviour should look like this:

- beets sends a request to musicbrainz/...
- no response until timeout, request again
- do this `n` times
- if there wasn't any successful response after `n` tries, fail with an error

**Comment by sampsyo** [comment]
Can you provide a little more detail about your setup and exactly what's going on? What you describe is more or less what's implemented, and I can make it happen on my machine by turning off my wifi ("MusicBrainz is unreachable").

Maybe a specific plugin can be blamed?

**Comment by klingtnet** [comment]
I'm starting beets like this: `nohup beet import --quiet /path/to/music 2> ~/beet.err > ~/beet.log &`
The only plugin I use is the discogs plugin.

Here is my `~/.config/beets/config.yaml`:

```ini
directory:  /path/to/music
library:    ~/.local/beets/library.blb

plugins:    discogs

asciify_paths: yes

replace:
    '[\\/]': _
    '^\.': _
    '\.$': _
    '\s+$': ''
    '^\s+': ''
    '\s': '_'
    '[\x00-\x1f]': _
    '[<>:"\?\*\|]': _

paths:
    default: $albumartist/$album%aunique{}/$track-$title
    singleton: $artist/singles/$title
    comp: compilations/$album%aunique{}/$track-$title

match:
    strong_rec_tresh: 0.18
    ignored: missing_tracks unmatched_tracks

import:
    copy: yes
    quiet_fallback: asis

musicbrainz:
    source_weight: 0.7

discogs:
    source_weight: 0.3
```

**Comment by klingtnet** [comment]
I could also find the `not reachable` error in my `beet.err` log:
`Error: MusicBrainz not reachable in release search with query ...`

**Comment by klingtnet** [comment]
Nevertheless, the problem still exists. My current workaround looks like this:

`nohup beet import --quiet /path/to/music/[M-Z]* 2> ~/beet.err > ~/beet.log &`

Where `M` is the last first character of the folder name where beets has stopped working.

**Comment by sampsyo** [comment]
Aha! Thanks for the extra details.

To help narrow down what's going on, let's see if we can blame some of the specific factors:
* Could the discogs plugin be to blame? If you turn it off, does this still happen?
* Can you reproduce the problem in verbose mode? This might help us see where the hang is occurring.
* Maybe it only happens under `nohup`?

**Comment by klingtnet** [comment]
I will close this issue for now because I haven't had much time lately to investigate the problems cause.
