### ISSUE TITLE
Pip release missing tests/test_completion.sh

### ISSUE THREAD

**Issue by diego-plan9** [beetbox/beets#1826]
A very minor issue slightly related to #1825 - it seems that the releases are missing `tests/test_completion.sh`, and as a result `test_ui.CompletionTest` results in an IOError if trying to run the test suite directly from a tar.gz release. Perhaps it would be a good idea to include the file on future releases?

**Comment by sampsyo** [comment]
Good catch! This really needed to be located in `test/rsrc/`, not just in `test/`. Only Python files belong there. I've moved it, and I tested that it's now included in the sdist tarball.
