### ISSUE TITLE
TypeError: data must be bytes, buffer, or memoryview in chromaprint.py

### ISSUE THREAD

**Issue by rotzbouw** [beetbox/beets#1829]
Using beets 1.3.16 installed via pip (all deps up to date) on Debian Sid and importing some dirs will cause this error in Chromaprint:
```
$ beet -vvv import Scared\ of\ Chaka/
user configuration: /home/thierry/.config/beets/config.yaml
data directory: /home/thierry/.config/beets
plugin paths: 
Sending event: pluginload
inline: adding item field initial
inline: adding item field multidisc
inline: adding item field release_year
library database: /home/thierry/.config/beets/library.db
library directory: /mnt/music
Sending event: library_opened
Sending event: import_begin
Sending event: import_task_created
Sending event: import_task_start
Traceback (most recent call last):
  File "/usr/local/bin/beet", line 9, in <module>
    load_entry_point('beets==1.3.16', 'console_scripts', 'beet')()
  File "/usr/local/lib/python2.7/dist-packages/beets/ui/__init__.py", line 1207, in main
    _raw_main(args)
  File "/usr/local/lib/python2.7/dist-packages/beets/ui/__init__.py", line 1197, in _raw_main
    subcommand.func(lib, suboptions, subargs)
  File "/usr/local/lib/python2.7/dist-packages/beets/ui/commands.py", line 947, in import_func
    import_files(lib, paths, query)
  File "/usr/local/lib/python2.7/dist-packages/beets/ui/commands.py", line 924, in import_files
    session.run()
  File "/usr/local/lib/python2.7/dist-packages/beets/importer.py", line 318, in run
    pl.run_parallel(QUEUE_SIZE)
  File "/usr/local/lib/python2.7/dist-packages/beets/util/pipeline.py", line 302, in run
    out = self.coro.send(msg)
  File "/usr/local/lib/python2.7/dist-packages/beets/util/pipeline.py", line 184, in coro
    func(*(args + (task,)))
  File "/usr/local/lib/python2.7/dist-packages/beets/importer.py", line 1247, in lookup_candidates
    plugins.send('import_task_start', session=session, task=task)
  File "/usr/local/lib/python2.7/dist-packages/beets/plugins.py", line 459, in send
    result = handler(**arguments)
  File "/usr/local/lib/python2.7/dist-packages/beets/plugins.py", line 124, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/beetsplug/chroma.py", line 144, in fingerprint_task
    return fingerprint_task(self._log, task, session)
  File "/usr/local/lib/python2.7/dist-packages/beetsplug/chroma.py", line 213, in fingerprint_task
    acoustid_match(log, item.path)
  File "/usr/local/lib/python2.7/dist-packages/beetsplug/chroma.py", line 66, in acoustid_match
    duration, fp = acoustid.fingerprint_file(util.syspath(path))
  File "/usr/local/lib/python2.7/dist-packages/acoustid.py", line 321, in fingerprint_file
    return _fingerprint_file_audioread(path, maxlength)
  File "/usr/local/lib/python2.7/dist-packages/acoustid.py", line 264, in _fingerprint_file_audioread
    fp = fingerprint(f.samplerate, f.channels, iter(f), maxlength)
  File "/usr/local/lib/python2.7/dist-packages/acoustid.py", line 206, in fingerprint
    fper.feed(block)
  File "/usr/local/lib/python2.7/dist-packages/chromaprint.py", line 119, in feed
    raise TypeError('data must be bytes, buffer, or memoryview')
TypeError: data must be bytes, buffer, or memoryview
```

Here's my beets config:
```
directory: /mnt/music
import:
    copy: yes
    write: yes
    log: beets.log
paths:
    default: $initial/$albumartist/%if{$release_year,$release_year/}$album/%if{$multidisc, Disc $disc/}$track - $title
    comp: Compilations/%if{$release_year,$release_year/}$album/%if{$disc,Disc $disc/}$track - $title ($artist)
per_disc_numbering: yes
plugins: duplicates inline missing chroma discogs
chroma:
    auto: yes
item_fields:
    initial: |
        if albumartist_sort:
            return albumartist_sort[0].upper()
        elif albumartist:
            return albumartist[0].upper()
        elif artist:
            return artist[0].upper()
        else:
            return "#"
    multidisc: |
        if disctotal > 1:
            return 1
        elif disc > 0:
            return 0
        else:
            return 0
    release_year: |
        if original_year:
            return original_year
        elif year:
            return year
        else:
            return 0
#musicbrainz:
#    host: localhost:8080
#    ratelimit: 100
```

Let me know if you need more info, thanks!

**Comment by sampsyo** [comment]
Thanks for the details!

I realize this is a fuzzy question, but do you know what backend `audioread` is using to decode tour files? That is, do you have gstreamer, ffmpeg, or both installed?

Also, is there anything in common about the files that trigger the problem? Which file format are they?

**Comment by rotzbouw** [comment]
Okay, I think I solved this issue by uninstalling the distribution's audioread packages (python-audioread and python3-audioread) which were kind of old (v1.0.3). I don't know what backend is used by audioread, is there a way to find out? I have both, gstreamer and ffmpeg, installed. The files causing the issue were .m4a files.
Anyway, thanks for pointing me in the right direction (audioread) and helping me solve this issue by simply using a newer version of audioread using pip!

**Comment by sampsyo** [comment]
Aha! That would explain it.

Unfortunately, there's not an easy way to figure out the backend—it's mostly guesswork. We should fix that.

**Comment by neilbags** [comment]
i'm hitting this bug on debian sid with beets 3.18.
removing python-audioread and installing the version from pip didn't help

**Comment by sampsyo** [comment]
This was recently fixed in https://github.com/beetbox/pyacoustid/commit/4a6253e690a6db76259397f6330b8c0e3bc68d14. We'll release the version with the fix soon.

**Comment by neilbags** [comment]
thanks. i just saw https://github.com/beetbox/beets/issues/2216
removing pymad works around the issue for now

**Comment by estelondono** [comment]
I had the same problem but with the changes proposed by rwthompsonii. Now beet is running and working as it should. I installed beets via pip and all the other requirements for chroma suggested in the page of beets.

```
rwthompsonii commented on 27 Oct 2016 • edited

FWIW, I just ran into this issue myself.

When I modify this function:

def feed(self, data):
        """Send raw PCM audio data to the fingerprinter. Data may be
        either a bytestring or a buffer object.
        """
        if isinstance(data, BUFFER_TYPES):
            data = str(data)
        elif not isinstance(data, bytes):
            raise TypeError('data must be bytes, buffer, or memoryview')
        _check(_libchromaprint.chromaprint_feed(
            self._ctx, data, len(data) // 2
        ))

to this:

def feed(self, data):
        """Send raw PCM audio data to the fingerprinter. Data may be
        either a bytestring or a buffer object.
        """
        if isinstance(data, BUFFER_TYPES):
            data = str(data)
        elif isinstance(data, bytearray):
            data = bytes(data)
        elif not isinstance(data, bytes):
            raise TypeError('data must be bytes, buffer, or memoryview')
        _check(_libchromaprint.chromaprint_feed(
            self._ctx, data, len(data) // 2
        )

It runs without issue. That function is located in this location https://github.com/beetbox/pyacoustid/blob/master/chromaprint.py and on my box is located at path:
/usr/local/lib/python2.7/dist-packages/chromaprint.py

This is just a heads up to anyone else that googles the error code and finds a github issue, which I find is always a bad sign. It's a hack and a workaround but I'm not the project maintainer, I just want it to work, I don't mind if it takes longer (because I just copied a crap ton of bytes unnecessarily, I'm assuming.)
```

**Comment by sampsyo** [comment]
@estelondono I don't quite understand—are you still hitting the same bug with up-to-date installations of beets and pyacoustid?

**Comment by estelondono** [comment]
Yes @sampsyo! I'm using Linux Lite 3.4 (based on Ubuntu 16.04) and the process installing beets was this:
First installing pip.
`sudo apt install python-pip`
it installed also 
`libexpat1-dev libpython-all-dev libpython-dev libpython2.7-dev python-all
  python-all-dev python-dev python-pip python-pip-whl python-setuptools
  python-wheel python2.7-dev`

I updated pip with 
`pip install --upgrade pip`

Then I installed chroma with
`sudo apt install libchromaprint-dev libchromaprint-tools`
I wasn't sure which one was the one needed, so I installed both.

Then I installed gstreamer1.0 and python-gi
`apt-get install gstreamer1.0 python-gi`

Then I installed
`sudo -H pip install discogs-client`
`sudo -H pip install requests`

And I downloaded [abzsubmit-0.1-linux-x86_64.tar.gz](http://acousticbrainz.org/static/download/abzsubmit-0.1-linux-x86_64.tar.gz), [chromaprint-fpcalc-1.4.2-linux-x86_64.tar.gz](https://github.com/acoustid/chromaprint/releases/download/v1.4.2/chromaprint-fpcalc-1.4.2-linux-x86_64.tar.gz) and [linux x86_64 extractor static binary](http://acousticbrainz.org/static/download/essentia-extractor-v2.1_beta2-linux-x86_64.tar.gz). The last two ones where copied to /usr/bin

**my config file is**
_directory: ~/Música
import:
   move: yes
acoustid:
    apikey: XXXXXXXX
plugins: chroma discogs absubmit acousticbrainz fetchart_

I hope I'm not forgetting nothing.

**Comment by sampsyo** [comment]
OK! If that's the case, please file a new bug with full details—including verbose output and a traceback—and we can look into it.

**Comment by shangshao** [comment]
Loaded your LOCAL configuration
Traceback (most recent call last):
  File "/usr/hdp/2.6.3.0-235/superset/lib/python3.4/site-packages/sqlalchemy/engine/base.py", line 1116, in _execute_context
    context = constructor(dialect, self, conn, *args)
  File "/usr/hdp/2.6.3.0-235/superset/lib/python3.4/site-packages/sqlalchemy/engine/default.py", line 649, in _init_compiled
    for key in compiled_params
  File "/usr/hdp/2.6.3.0-235/superset/lib/python3.4/site-packages/sqlalchemy/engine/default.py", line 649, in <genexpr>
