### ISSUE TITLE
Decreasing file size after removing album art?

### ISSUE THREAD

**Issue by mried** [beetbox/beets#1832]
I've accidentally embedded a cover image of about 20MB into my 3MB mp3 files - now they have a size of 23MB :flushed: So I decided to replaced the image by a smaller one but the file size does not change. The next thing I tried was to clear the embedded art using `clearart`. The image is removed, but the file size is still far to big.

Is it possible to reduce the file size somehow?

**Comment by sampsyo** [comment]
That's quite a lot of wasted space!

We don't currently have a built-in way to address padding, but #373 has a proposal for how that would work.

In the mean time, there's *some* chance that `beet scrub`ing the file in question will do the trick. Worth a try.

**Comment by mried** [comment]
Thanks for pointing me to the `scrub` plugin which did the job perfectly! :+1:

**Comment by sampsyo** [comment]
That's awesome! :tada: I gave it about 50/50 odds that would work.

**Comment by lazka** [comment]
@mried What is your mutagen version? (``python2 -c "import mutagen; print(mutagen.version)"`` in a terminal should show it)

**Comment by lazka** [comment]
Oh, just saw that this issue quite old, never mind then.
