### ISSUE TITLE
Bad mapping on track renaming at import

### ISSUE THREAD

**Issue by yohanboniface** [beetbox/beets#1834]
It fails to map tracks 2 and 14:

<pre>
Tagging:
    Renaud - Marchand de cailloux
URL:
    http://musicbrainz.org/release/245f40ae-1170-3dd2-ab69-2761153473b1
(Similarity: 52.0%) (tracks) (CD, 1991, FR, Virgin France S.A.)
 * 01 - Marchand de cailloux.mp3 (#0)                -> Marchand de cailloux (#1) (title)
<b> * 14 - Tant qu'il y aura des ombres.mp3 (#0) (4:21) -> L'Aquarium (#2) (4:10) (title, length)</b>
 * 03 - P'tit voleur.mp3 (#0)                        -> P'tit voleur (#3) (title)
 * 04 - Olé.mp3 (#0)                                 -> Olé ! (#4) (title)
 * 05 - Les dimanches à la con.mp3 (#0)              -> Les Dimanches à la con (#5) (title)
 * 06 - Dans ton sac.mp3 (#0)                        -> Dans ton sac (#6) (title)
 * 07 - Le tango des élus.mp3 (#0)                   -> Le Tango des élus (#7) (title)
 * 08 - La ballade nord - irlandaise.mp3 (#0)        -> La Ballade nord-irlandaise (#8) (title)
 * 09 - 500 connards sur la ligne de départ.mp3 (#0) -> 500 connards sur la ligne de départ (#9) (title)
 * 10 - Tonton.mp3 (#0)                              -> Tonton (#10) (title)
 * 11 - Je cruel.mp3 (#0)                            -> Je cruel (#11) (title)
 * 12 - C'est pas du pipeau.mp3 (#0)                 -> C'est pas du pipeau (#12) (title)
 * 13 - Ma chanson leur a pas plu.mp3 (#0)           -> Ma chanson leur a pas plu (suite) (#13) (title)
<b> * 02 - L'aquarium.mp3 (#0)                          -> Tant qu'il y aura des ombres (#14) (title)</b>
</pre>

Not sure what more info I can give to help debugging.

Thanks :)

**Comment by sampsyo** [comment]
Do these files have MusicBrainz IDs? Or, do you have fingerprinting enabled? In either case, those signals can override title-based matches. (And they may be correct!)

**Comment by yohanboniface** [comment]
> Do these files have MusicBrainz IDs?

Don't see any from RhythmBox or EasyTAG. How can I check that for sure?

> Or, do you have fingerprinting enabled?

I'd say no. AFAIK this needs to be enabled through a plugin which I haven't done.

> (And they may be correct!)

In this case I'm sure those tracks names are good and should not be mapped one to the other :)

Thanks :)

**Comment by sampsyo** [comment]
> Don't see any from RhythmBox or EasyTAG. How can I check that for sure?

The `info` plugin can help.

I also just noticed from your listing that these files don't have any tags at all. That's why filenames are appearing instead of titles. Beets did its best to guess based on track lengths, but got confused when two tracks had a similar length. You can enable the `fromfilename` plugin to use unstaffed files based on their names.

**Comment by yohanboniface** [comment]
> You can enable the fromfilename plugin to use unstaffed files based on their names

Oh, makes sense, thanks! I'll try it :)

**Comment by sampsyo** [comment]
unstaffed -> untagged. Thanks, autocorrect!
