### ISSUE TITLE
Error handling multi-cd track numbers

### ISSUE THREAD

**Issue by bspeice** [beetbox/beets#1835]
I haven't confirmed whether this is a beets-wide issue, or just the album, but wanted to report it:
When importing the [WOW Hits 2005](http://musicbrainz.org/release/b973d23c-2368-480e-b33d-8bb72c37aeaf) album it is listed online as a 2-cd collection, which is correct. And Beets tags it as Disc 1 and Disc 2. However, it tags tracks 1-34, rather than 1-17 of disc 1, and 1-17 of disc 2. Is it possible to fix this so that the track numbers are correctly tagged according to MusicBrainz?

**Comment by sampsyo** [comment]
Please see the `per_disc_numbering` configuration option.
