### ISSUE TITLE
On replaygain: gstreamer crashes

### ISSUE THREAD

**Issue by petwri** [beetbox/beets#1841]
When doing a replaygain -a, this happens:

`ReplayGain error: Error GLib.Error('GStreamer encountered a general stream error.', 'gst-stream-error-quark', 1) - 'gstbaseparse.c(3457): gst_base_parse_loop (): /GstPipeline:pipeline0/GstDecodeBin:decbin/GstMpegAudioParse:mpegaudioparse1:\nstreaming stopped, reason error' on file '/media/Music/Audioslave/Out of Exile/01-02 Out of Exile.mp3'`

Is this an issues with beets or Gstreamer-related?

**Comment by sampsyo** [comment]
That would be a GStreamer error.
