### ISSUE TITLE
tag contentgroup is not scrubbed

### ISSUE THREAD

**Issue by Rouzax** [beetbox/beets#1844]
I have a tag that is leftover from MusicBrainz Picard that is not scrubbed when scrubbing my files.
![image](https://cloud.githubusercontent.com/assets/4103090/12674950/31faa65c-c687-11e5-968e-9b24b2812613.png)
```
PS C:\> beet -v scrub moments
user configuration: C:\Users\Admin\AppData\Roaming\beets\config.yaml
data directory: C:\Users\Admin\AppData\Roaming\beets
plugin paths:
Sending event: pluginload
artresizer: method is (1, (0,))
library database: C:\Beets\musiclibrary.blb
library directory: C:\_Data\Music
Sending event: library_opened
scrub: scrubbing: C:\_Data\Music\Above & Beyond\2013-03-04 - Anjunabeats, Volume 10\01.01 - Above & Beyond - Small Moments.mp3
scrub: writing new tags after scrub
Sending event: write
Sending event: after_write
scrub: restoring art
Sending event: cli_exit
```
After the scrub the tag is still present and as far as I can see the tag is not part of Beets.

**Comment by sampsyo** [comment]
It looks like the field that some tools call "contentgroup" is the one that beets calls "grouping" (i.e., the `TIT1` frame in ID3, etc.).

**Comment by Rouzax** [comment]
How is that tag populated by Beets?

**Comment by sampsyo** [comment]
It's not (by any backend I know of). Maybe it was on your files already?

**Comment by Rouzax** [comment]
It was added by the ng lastfm plugin for Picard, how could I clear those then in beets?

**Comment by sampsyo** [comment]
Check out the `zero` plugin.

**Comment by Rouzax** [comment]
Thanks for this, looks promising.
