### ISSUE TITLE
Copyright date on documentation

### ISSUE THREAD

**Issue by diego-plan9** [beetbox/beets#1847]
A candidate for the smallest-issue contest: perhaps the [copyright year](https://github.com/beetbox/beets/blob/master/docs/conf.py#L14) on the documentation should be updated, so the docs footer looks up to date (currently shows 2012)?

**Comment by sampsyo** [comment]
Wow! That's pretty old. Yeah, please do go for it.

**Comment by diego-plan9** [comment]
Cool! Fixed on #1848
