### ISSUE TITLE
Lost Music

### ISSUE THREAD

**Issue by tmoreau24** [beetbox/beets#1849]
I originally had beets import music to the default  ~/music directory.

Once I got a feel for the config set up I wanted, I decided to use [beet move] to move the imported music to a more desirable directory on an external drive.  

I set up my config file to move the ~/music files to the ~/HD/Project Complete directory. 

Problem is that it seems to have removed all the music that was already in /Project Complete and started a brand new directory. 

Is this music gone? Hidden? Recoverable?

**Comment by sampsyo** [comment]
Wow, weird. Nothing in beets should remove files like that—in fact, when beets encounters a conflicting filename during a move or copy, it appends a number to make sure no data is lost. Is there any chance something more subtle is going on with the filesystem that's hiding your old files?

**Comment by tmoreau24** [comment]
My original config file was: 
directory: ~/users/username/music
library: ~/.config/beets/library.db
import:
    move: yes
plugins: fetchart copyartifacts

paths:
    ext:log: $albumpath/$artist - $album
    ext:cue: $albumpath/$artist - $album
    ext:jpg: $albumpath/cover

copyartifacts:
    extensions: .cue .log .jpg
    print_ignored: yes

fetchart:
    cautious: true
    cover_names: front back
    sources: itunes *

I then switched the directory to 
      directory: /Volumes/The Wardrobe/Project Complete

Project Complete was a folder where I had manually moved files into a path I desired before discovering beets. 

When I issued the "beet move" command it started "Project Complete" over only moving files from the original directory while all of the files I had moved manually are gone.  

I've attempted to recreate the problem by moving music into another directory containing files and it seems to work perfectly.

**Comment by sampsyo** [comment]
Yeah, I think I understand what you're seeing—I just can't explain it. There's nothing in beets that should remove existing files when you do something like that. This seems frustrating!

**Comment by tmoreau24** [comment]
Yea and not being able to recreate the problem has me pessimistic. It was a ton of music and happened over the course of seconds so I'm not sure where it could have moved to or deleted that much data so quickly. I'll see if I can figure anything out.

**Comment by tmoreau24** [comment]
I honestly don't know how it happened, but I've been able to find the "missing" folders.  For some reason it created a duplicate folder of the same name in the directory I specified and moved the original into the folder queued for import. Thanks for the support, and long live BEETS!

**Comment by sampsyo** [comment]
Wow; weird! Glad your data is safe.
