### ISSUE TITLE
Album matches regex but not -a, not appearing in correct directory structure

### ISSUE THREAD

**Issue by WheresWardy** [beetbox/beets#1852]
I have some music files which when imported (without autotagging as I copied my existing iTunes library into a new location) didn't have an album or artist set. I used the `modify` command to add them, but now the files appear under the artist's directory (instead of artist and them the album name) even though they have an album set. Also, if I list the album using regex it appears, but if I use the `-a` flag it doesn't. I have some example command output that hopefully explains what I mean, I've used `...` in places where there are several files for brevity.

```
$ beet ls 'album::Live Trax 16'
Dave Matthews Band Live - Live Trax 16: Riverbend Music Center (2000) - #41
...
```
```
$ beet ls -a 'album::Live Trax 16'
(no output)
```
```
beet ls -p 'album::Live Trax 16'
/storage/Matt/Music/Dave Matthews Band Live/01 #41.mp3
...
```
The above file is under the artist directory (Dave Matthews Band Live) instead of an album directory, like the following working album is:
```
$ beet ls -a 'album::Live Trax 33'
Dave Matthews Band Live - Live Trax 33: Lupo's Heartbreak Hotel (1995)
```
```
$ beet ls -p 'album::Live Trax 33'
/storage/Matt/Music/Dave Matthews Band Live/Live Trax 33_ Lupo's Heartbreak Hotel (1995)/01 Seek Up.mp3
```
Here's one of the non-working files' info output:
```
$ beet info 'Live Trax 16'
/storage/Matt/Music/Dave Matthews Band Live/01 #41.mp3
        album: Live Trax 16: Riverbend Music Center (2000)
  albumartist: Dave Matthews Band Live
          art: True
       artist: Dave Matthews Band Live
     bitdepth: 0
      bitrate: 320000
          bpm: 0
     channels: 2
         comp: False
         date: 2000-01-01
         disc: 1
    disctotal: 0
       format: MP3
       genres:
       length: 620.88155
       lyrics:
original_year: 0
   samplerate: 44100
        title: #41
        track: 1
   tracktotal: 0
         year: 2000
```

**Comment by sampsyo** [comment]
It looks like you need to use `beet modify -a` (note the -a flag) to affect the album-level metadata. Can you give that a try?

**Comment by WheresWardy** [comment]
Looks like that could be the case, but now not sure how to query for the files, because adding the `-a` flag to the modify command means I can't find any matching files anymore?

**Comment by sampsyo** [comment]
You can try using a directory, or, if all else fails, use `beet ls -af '$id ...'` to find the album's id and query by that.

**Comment by WheresWardy** [comment]
I used a combination of a path of the artist directory and a regex for no album (`album::^$`) and that seemed to catch them. Perfect, and thanks for your help, loving beets!

**Comment by sampsyo** [comment]
Fantastic!
