### ISSUE TITLE
lastimport: Use project's API key

### ISSUE THREAD

**Issue by intelfx** [beetbox/beets#1859]
Looks like the lastimport plugin requires a user to get their own last.fm API key. This is not mentioned in the docs.

Moreover, why can't a global (per-app) API key be used?

I'm sorry if this is explained somewhere. A cursory sweep over the docs told me nothing.

**Comment by sampsyo** [comment]
Huh, thanks for pointing that out. We used to use beets' own API key, but it looks like that was accidentally changed here: https://github.com/beetbox/beets/commit/0a6983b7595497ecea375890d7acb021f0ce0994

We should go back to not requiring a configured key, and we should probably document that it's possible to provide your own if you want.

**Comment by petwri** [comment]
Is the error

`pylast.WSError: Invalid API key - You must be granted a valid key by last.fm`

I get when running `beet lastimport` related to this?

**Comment by intelfx** [comment]
@pewtri: yes, it's precisely this issue.

**Comment by petwri** [comment]
@intelfx Ok, thanks for the info. So, the idea is to use the API key stored in the beets config file or what?

**Comment by sampsyo** [comment]
The key's available here: https://github.com/beetbox/beets/blob/master/beets/plugins.py#L35

The idea is to do the same thing as the lastgenre plugin, i.e., use that key unless the user overrides it in the per-plugin config.

**Comment by petwri** [comment]
So is there any workaround for now to get lastimport working?

**Comment by SJoshBrown** [comment]
@petwri I've submitted a pull request that will sort this out.

In the meantime you can put the beets project api key in your config file under lastfm.

lastfm:
    user: username
    api_key: 2dc3914abf35f0d9c92d97d8f8e42b43

**Comment by petwri** [comment]
And this will import from the user defined with 'username'?

**Comment by SJoshBrown** [comment]
@petwri Yes it will. That API key is not specific to any user account so you'll be able to use it for yours.

**Comment by jackwilsdon** [comment]
So it looks like this was fixed by #1868.

**Comment by sampsyo** [comment]
Yep, thanks!
