### ISSUE TITLE
piecewise import vs. %aunique

### ISSUE THREAD

**Issue by intelfx** [beetbox/beets#1861]
Another minor usability thing I've spotted.

Usecase
=======
Sometimes, if one tries to reconstruct a badly sorted music library, it happens that albums/releases are imported in parts (due to user error). Something like:

    $ beet import /path/to/music/subdir/*album*
    <tag the album, confirm missing tracks, suddenly remember another subdirectory>
    $ beet import /path/to/music/another/*album*
    <tag the album's remaining tracks>
    This album is already in the library!
    Old: N items, ...
    New: M items, ...
    [S]kip new, Keep both, Remove old? 

If album name disambiguation (`%aunique{...}`) is enabled in the config, then the newly-added tracks are placed into a suffixed directory, even if there are no real name clashes. What I expect is to merge the two pieces into a single album, both in database and in the filesystem.

I don't really know which component is responsible for this behavior. Either the importer could be tuned to avoid creating second database entry for the same album (if all fields match perfectly), or the `%aunique{}` function implementation could be made to return empty suffixes for all albums with the same musicbrainz id.

**Comment by sampsyo** [comment]
The essential problem isn't actually %aunique; it's that beets now has two separate albums in its database. There's more on this at #112.
