### ISSUE TITLE
Convert plugin - transcode during import

### ISSUE THREAD

**Issue by exptom** [beetbox/beets#1862]
Is there a way (or is it planned) to automatically transcode music at the time of import?
I have a "master" directory of my CD rips that is almost completely FLAC, I would like to able to automatically maintain a "transcode" mirror directory of lower bitrate MP3s for use on a portable device.

I thought the "auto" flag (I misread the docs first time) for the convert plugin would do what I wanted but realised it was converting my FLAC and storing mp3 into my library!

If I run "beet convert" for the whole library it redoes the transcoding of all files rather than just those that are missing from the transcode directory so it means that every time I import something new I have to remember to run "beet convert QUERY" to convert the new stuff that I have added.

**Comment by intelfx** [comment]
This sounds like #1840.

**Comment by exptom** [comment]
Yes sorry, should have checked the other tickets more closely!
