### ISSUE TITLE
importing files (using wildcards) doesn't work as expected

### ISSUE THREAD

**Issue by m8ram** [beetbox/beets#1870]
Hi,

When ripping a disk to multiple output formats with abcde the different formats are placed in the same directory.
I wanted to import only the ogg vorbis files so I ran `beet import /path/*ogg`.
The result is that each file is imported individually and reports missing tracks before reporting the album is already in the DB.
It is not clear to me whether there is an option to add the new track to an existing album:

```
Apply, More candidates, Skip, Use as-is, as Tracks, Group albums,
Enter search, enter Id, aBort? A
This album is already in the library!
Old: 1 items, OGG, 112kbps, 3:10, 2.3 MB
New: 1 items, OGG, 112kbps, 3:04, 2.3 MB
```
If the new tracks are skipped they are not moved at all, and when Remove is selected not only the album but the track it contains is removed as well which caused data loss.

How can I import only the ogg vorbis files and leave the MP3 untouched?
Or better yet how can I move th ogg vorbis into my library and then use beets to rename the MP3 files but move them to a separate directory altogether?

Regards

Bram

**Comment by sampsyo** [comment]
As the importer docs describe, the album importer works in a "directory-based" way, meaning that directories are used to indicate which tracks are part of the same album. So if you pass individual files on the command line (your shell expands globs into individual filenames), beets assumes you have lots of 1-track albums.

If I were you, I would either:
- Use `mv` to separate the files and then import them.
- Temporarily adjust the `ignore` configuration to exclude one type or the other before importing.
