### ISSUE TITLE
Use multi-processing for import

### ISSUE THREAD

**Issue by svenstaro** [beetbox/beets#1872]
I noticed that even though beets is threaded, it only uses a single process for preparing importing tasks. I think apart from being threaded to allow for asynchronous scanning and user input as it does now, it should optionally make use of all available CPUs for parallel scanning while importing.

Currently, 7 out of my 8 cores sit by idly while it's busy fingerprinting my collection, for instance.

**Comment by sampsyo** [comment]
Yep, more parallelism is always worth exploring.

But we should definitely do some profiling before taking any drastic action. For the majority of beets' tasks, I'm fairly confident we're I/O bound—I'd be surprised if multiple cores would have any effect on the initial file reading, for example.

Fingerprinting is a clear exception, for which we have this very old issue: #126. It would be great to parallelize that in particular.

**Comment by sampsyo** [comment]
Timing this out unless you'd like to discuss more.
