### ISSUE TITLE
Installation Fails on MacOS 10.11.3

### ISSUE THREAD

**Issue by ahaghgoo** [beetbox/beets#1877]
Just tried to install Beets on my Mac with the command: 

`sudo pip install beets`

But it resulted with this error: 

```
Command /usr/bin/python -c "import setuptools, tokenize;__file__='/private/tmp/pip_build_root/mutagen/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-Tvjq7f-record/install-record.txt --single-version-externally-managed --compile failed with error code 1 in /private/tmp/pip_build_root/mutagen
```

I've got no background with python so I don't know what's going on.  The log is attached. 
[pip.txt](https://github.com/beetbox/beets/files/123673/pip.txt)

**Comment by sampsyo** [comment]
Weird; I've never seen this before. Can you please paste the full output of the pip command (assuming that this is just the last line)?

**Comment by ahaghgoo** [comment]
Yes, the entire output is below: 

sudo pip install beets
Requirement already satisfied (use --upgrade to upgrade): beets in /Library/Python/2.7/site-packages
Requirement already satisfied (use --upgrade to upgrade): enum34>=1.0.4 in /Library/Python/2.7/site-packages (from beets)
Downloading/unpacking mutagen>=1.27 (from beets)
  Downloading mutagen-1.31.tar.gz (897kB): 897kB downloaded
  Running setup.py (path:/private/tmp/pip_build_root/mutagen/setup.py) egg_info for package mutagen
    
Downloading/unpacking munkres (from beets)
  Downloading munkres-1.0.7.tar.gz
  Running setup.py (path:/private/tmp/pip_build_root/munkres/setup.py) egg_info for package munkres
    
Downloading/unpacking unidecode (from beets)
  Downloading Unidecode-0.04.19.tar.gz (204kB): 204kB downloaded
  Running setup.py (path:/private/tmp/pip_build_root/unidecode/setup.py) egg_info for package unidecode
    
Downloading/unpacking musicbrainzngs>=0.4 (from beets)
  Downloading musicbrainzngs-0.5.tar.gz (61kB): 61kB downloaded
  Running setup.py (path:/private/tmp/pip_build_root/musicbrainzngs/setup.py) egg_info for package musicbrainzngs
    
Downloading/unpacking pyyaml (from beets)
  Downloading PyYAML-3.11.tar.gz (248kB): 248kB downloaded
  Running setup.py (path:/private/tmp/pip_build_root/pyyaml/setup.py) egg_info for package pyyaml
    
Downloading/unpacking jellyfish (from beets)
  Downloading jellyfish-0.5.2.tar.gz
  Running setup.py (path:/private/tmp/pip_build_root/jellyfish/setup.py) egg_info for package jellyfish
    
Installing collected packages: mutagen, munkres, unidecode, musicbrainzngs, pyyaml, jellyfish
  Running setup.py install for mutagen
    changing mode of build/scripts-2.7/mid3cp from 644 to 755
    changing mode of build/scripts-2.7/mid3iconv from 644 to 755
    changing mode of build/scripts-2.7/mid3v2 from 644 to 755
    changing mode of build/scripts-2.7/moggsplit from 644 to 755
    changing mode of build/scripts-2.7/mutagen-inspect from 644 to 755
    changing mode of build/scripts-2.7/mutagen-pony from 644 to 755
    error: could not create '/System/Library/Frameworks/Python.framework/Versions/2.7/share': Operation not permitted
    Complete output from command /usr/bin/python -c "import setuptools, tokenize;__file__='/private/tmp/pip_build_root/mutagen/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-PZtPKL-record/install-record.txt --single-version-externally-managed --compile:
    running install

running build

running build_py

creating build

creating build/lib

creating build/lib/mutagen

copying mutagen/__init__.py -> build/lib/mutagen

copying mutagen/_compat.py -> build/lib/mutagen

copying mutagen/_constants.py -> build/lib/mutagen

copying mutagen/_file.py -> build/lib/mutagen

copying mutagen/_mp3util.py -> build/lib/mutagen

copying mutagen/_tags.py -> build/lib/mutagen

copying mutagen/_toolsutil.py -> build/lib/mutagen

copying mutagen/_util.py -> build/lib/mutagen

copying mutagen/_vorbis.py -> build/lib/mutagen

copying mutagen/aac.py -> build/lib/mutagen

copying mutagen/aiff.py -> build/lib/mutagen

copying mutagen/apev2.py -> build/lib/mutagen

copying mutagen/easyid3.py -> build/lib/mutagen

copying mutagen/easymp4.py -> build/lib/mutagen

copying mutagen/flac.py -> build/lib/mutagen

copying mutagen/m4a.py -> build/lib/mutagen

copying mutagen/monkeysaudio.py -> build/lib/mutagen

copying mutagen/mp3.py -> build/lib/mutagen

copying mutagen/musepack.py -> build/lib/mutagen

copying mutagen/ogg.py -> build/lib/mutagen

copying mutagen/oggflac.py -> build/lib/mutagen

copying mutagen/oggopus.py -> build/lib/mutagen

copying mutagen/oggspeex.py -> build/lib/mutagen

copying mutagen/oggtheora.py -> build/lib/mutagen

copying mutagen/oggvorbis.py -> build/lib/mutagen

copying mutagen/optimfrog.py -> build/lib/mutagen

copying mutagen/trueaudio.py -> build/lib/mutagen

copying mutagen/wavpack.py -> build/lib/mutagen

creating build/lib/mutagen/id3

copying mutagen/id3/__init__.py -> build/lib/mutagen/id3

copying mutagen/id3/_frames.py -> build/lib/mutagen/id3

copying mutagen/id3/_specs.py -> build/lib/mutagen/id3

copying mutagen/id3/_util.py -> build/lib/mutagen/id3

creating build/lib/mutagen/mp4

copying mutagen/mp4/__init__.py -> build/lib/mutagen/mp4

copying mutagen/mp4/_as_entry.py -> build/lib/mutagen/mp4

copying mutagen/mp4/_atom.py -> build/lib/mutagen/mp4

copying mutagen/mp4/_util.py -> build/lib/mutagen/mp4

creating build/lib/mutagen/asf

copying mutagen/asf/__init__.py -> build/lib/mutagen/asf

copying mutagen/asf/_attrs.py -> build/lib/mutagen/asf

copying mutagen/asf/_objects.py -> build/lib/mutagen/asf

copying mutagen/asf/_util.py -> build/lib/mutagen/asf

running build_scripts

creating build/scripts-2.7

copying and adjusting tools/mid3cp -> build/scripts-2.7

copying and adjusting tools/mid3iconv -> build/scripts-2.7

copying and adjusting tools/mid3v2 -> build/scripts-2.7

copying and adjusting tools/moggsplit -> build/scripts-2.7

copying and adjusting tools/mutagen-inspect -> build/scripts-2.7

copying and adjusting tools/mutagen-pony -> build/scripts-2.7

changing mode of build/scripts-2.7/mid3cp from 644 to 755

changing mode of build/scripts-2.7/mid3iconv from 644 to 755

changing mode of build/scripts-2.7/mid3v2 from 644 to 755

changing mode of build/scripts-2.7/moggsplit from 644 to 755

changing mode of build/scripts-2.7/mutagen-inspect from 644 to 755

changing mode of build/scripts-2.7/mutagen-pony from 644 to 755

running install_lib

copying build/lib/mutagen/__init__.py -> /Library/Python/2.7/site-packages/mutagen

copying build/lib/mutagen/_compat.py -> /Library/Python/2.7/site-packages/mutagen

copying build/lib/mutagen/_constants.py -> /Library/Python/2.7/site-packages/mutagen

copying build/lib/mutagen/_file.py -> /Library/Python/2.7/site-packages/mutagen

copying build/lib/mutagen/_mp3util.py -> /Library/Python/2.7/site-packages/mutagen

copying build/lib/mutagen/_tags.py -> /Library/Python/2.7/site-packages/mutagen

copying build/lib/mutagen/_toolsutil.py -> /Library/Python/2.7/site-packages/mutagen

copying build/lib/mutagen/_util.py -> /Library/Python/2.7/site-packages/mutagen

copying build/lib/mutagen/_vorbis.py -> /Library/Python/2.7/site-packages/mutagen

copying build/lib/mutagen/aac.py -> /Library/Python/2.7/site-packages/mutagen

copying build/lib/mutagen/aiff.py -> /Library/Python/2.7/site-packages/mutagen

copying build/lib/mutagen/apev2.py -> /Library/Python/2.7/site-packages/mutagen

copying build/lib/mutagen/asf/__init__.py -> /Library/Python/2.7/site-packages/mutagen/asf

copying build/lib/mutagen/asf/_attrs.py -> /Library/Python/2.7/site-packages/mutagen/asf

copying build/lib/mutagen/asf/_objects.py -> /Library/Python/2.7/site-packages/mutagen/asf

copying build/lib/mutagen/asf/_util.py -> /Library/Python/2.7/site-packages/mutagen/asf

copying build/lib/mutagen/easyid3.py -> /Library/Python/2.7/site-packages/mutagen

copying build/lib/mutagen/easymp4.py -> /Library/Python/2.7/site-packages/mutagen

copying build/lib/mutagen/flac.py -> /Library/Python/2.7/site-packages/mutagen

copying build/lib/mutagen/id3/__init__.py -> /Library/Python/2.7/site-packages/mutagen/id3

copying build/lib/mutagen/id3/_frames.py -> /Library/Python/2.7/site-packages/mutagen/id3

copying build/lib/mutagen/id3/_specs.py -> /Library/Python/2.7/site-packages/mutagen/id3

copying build/lib/mutagen/id3/_util.py -> /Library/Python/2.7/site-packages/mutagen/id3

copying build/lib/mutagen/m4a.py -> /Library/Python/2.7/site-packages/mutagen

copying build/lib/mutagen/monkeysaudio.py -> /Library/Python/2.7/site-packages/mutagen

copying build/lib/mutagen/mp3.py -> /Library/Python/2.7/site-packages/mutagen

copying build/lib/mutagen/mp4/__init__.py -> /Library/Python/2.7/site-packages/mutagen/mp4

copying build/lib/mutagen/mp4/_as_entry.py -> /Library/Python/2.7/site-packages/mutagen/mp4

copying build/lib/mutagen/mp4/_atom.py -> /Library/Python/2.7/site-packages/mutagen/mp4

copying build/lib/mutagen/mp4/_util.py -> /Library/Python/2.7/site-packages/mutagen/mp4

copying build/lib/mutagen/musepack.py -> /Library/Python/2.7/site-packages/mutagen

copying build/lib/mutagen/ogg.py -> /Library/Python/2.7/site-packages/mutagen

copying build/lib/mutagen/oggflac.py -> /Library/Python/2.7/site-packages/mutagen

copying build/lib/mutagen/oggopus.py -> /Library/Python/2.7/site-packages/mutagen

copying build/lib/mutagen/oggspeex.py -> /Library/Python/2.7/site-packages/mutagen

copying build/lib/mutagen/oggtheora.py -> /Library/Python/2.7/site-packages/mutagen

copying build/lib/mutagen/oggvorbis.py -> /Library/Python/2.7/site-packages/mutagen

copying build/lib/mutagen/optimfrog.py -> /Library/Python/2.7/site-packages/mutagen

copying build/lib/mutagen/trueaudio.py -> /Library/Python/2.7/site-packages/mutagen

copying build/lib/mutagen/wavpack.py -> /Library/Python/2.7/site-packages/mutagen

byte-compiling /Library/Python/2.7/site-packages/mutagen/__init__.py to __init__.pyc

byte-compiling /Library/Python/2.7/site-packages/mutagen/_compat.py to _compat.pyc

byte-compiling /Library/Python/2.7/site-packages/mutagen/_constants.py to _constants.pyc

byte-compiling /Library/Python/2.7/site-packages/mutagen/_file.py to _file.pyc

byte-compiling /Library/Python/2.7/site-packages/mutagen/_mp3util.py to _mp3util.pyc

byte-compiling /Library/Python/2.7/site-packages/mutagen/_tags.py to _tags.pyc

byte-compiling /Library/Python/2.7/site-packages/mutagen/_toolsutil.py to _toolsutil.pyc

byte-compiling /Library/Python/2.7/site-packages/mutagen/_util.py to _util.pyc

byte-compiling /Library/Python/2.7/site-packages/mutagen/_vorbis.py to _vorbis.pyc

byte-compiling /Library/Python/2.7/site-packages/mutagen/aac.py to aac.pyc

byte-compiling /Library/Python/2.7/site-packages/mutagen/aiff.py to aiff.pyc

byte-compiling /Library/Python/2.7/site-packages/mutagen/apev2.py to apev2.pyc

byte-compiling /Library/Python/2.7/site-packages/mutagen/asf/__init__.py to __init__.pyc

byte-compiling /Library/Python/2.7/site-packages/mutagen/asf/_attrs.py to _attrs.pyc

byte-compiling /Library/Python/2.7/site-packages/mutagen/asf/_objects.py to _objects.pyc

byte-compiling /Library/Python/2.7/site-packages/mutagen/asf/_util.py to _util.pyc

byte-compiling /Library/Python/2.7/site-packages/mutagen/easyid3.py to easyid3.pyc

byte-compiling /Library/Python/2.7/site-packages/mutagen/easymp4.py to easymp4.pyc

byte-compiling /Library/Python/2.7/site-packages/mutagen/flac.py to flac.pyc

byte-compiling /Library/Python/2.7/site-packages/mutagen/id3/__init__.py to __init__.pyc

byte-compiling /Library/Python/2.7/site-packages/mutagen/id3/_frames.py to _frames.pyc

byte-compiling /Library/Python/2.7/site-packages/mutagen/id3/_specs.py to _specs.pyc

byte-compiling /Library/Python/2.7/site-packages/mutagen/id3/_util.py to _util.pyc

byte-compiling /Library/Python/2.7/site-packages/mutagen/m4a.py to m4a.pyc

byte-compiling /Library/Python/2.7/site-packages/mutagen/monkeysaudio.py to monkeysaudio.pyc

byte-compiling /Library/Python/2.7/site-packages/mutagen/mp3.py to mp3.pyc

byte-compiling /Library/Python/2.7/site-packages/mutagen/mp4/__init__.py to __init__.pyc

byte-compiling /Library/Python/2.7/site-packages/mutagen/mp4/_as_entry.py to _as_entry.pyc

byte-compiling /Library/Python/2.7/site-packages/mutagen/mp4/_atom.py to _atom.pyc

byte-compiling /Library/Python/2.7/site-packages/mutagen/mp4/_util.py to _util.pyc

byte-compiling /Library/Python/2.7/site-packages/mutagen/musepack.py to musepack.pyc

byte-compiling /Library/Python/2.7/site-packages/mutagen/ogg.py to ogg.pyc

byte-compiling /Library/Python/2.7/site-packages/mutagen/oggflac.py to oggflac.pyc

byte-compiling /Library/Python/2.7/site-packages/mutagen/oggopus.py to oggopus.pyc

byte-compiling /Library/Python/2.7/site-packages/mutagen/oggspeex.py to oggspeex.pyc

byte-compiling /Library/Python/2.7/site-packages/mutagen/oggtheora.py to oggtheora.pyc

byte-compiling /Library/Python/2.7/site-packages/mutagen/oggvorbis.py to oggvorbis.pyc

byte-compiling /Library/Python/2.7/site-packages/mutagen/optimfrog.py to optimfrog.pyc

byte-compiling /Library/Python/2.7/site-packages/mutagen/trueaudio.py to trueaudio.pyc

byte-compiling /Library/Python/2.7/site-packages/mutagen/wavpack.py to wavpack.pyc

running install_data

creating /System/Library/Frameworks/Python.framework/Versions/2.7/share

error: could not create '/System/Library/Frameworks/Python.framework/Versions/2.7/share': Operation not permitted

----------------------------------------
Cleaning up...
Command /usr/bin/python -c "import setuptools, tokenize;__file__='/private/tmp/pip_build_root/mutagen/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-PZtPKL-record/install-record.txt --single-version-externally-managed --compile failed with error code 1 in /private/tmp/pip_build_root/mutagen

**Comment by sampsyo** [comment]
Aha; it looks like you're getting burned by [SIP](https://en.wikipedia.org/wiki/System_Integrity_Protection), a new security feature in El Cap. A good workaround is to use `pip install --user` to install in your home directory (but you'll need to adjust your $PATH in that case).

**Comment by ctam** [comment]
Try `sudo easy_install mutagen`.  It worked for me.
