### ISSUE TITLE
beets ignoring musicbrainz

### ISSUE THREAD

**Issue by grawlinson** [beetbox/beets#1879]
For some reason, this idiot called Lukas Graham has decided to name two albums _almost_ identically.

Albums:
* [Lukas Graham (2012)](http://musicbrainz.org/release/e90745f7-6e2b-45b0-aa42-5f146cfaa54f)
* [Lukas Graham (Blue Album) (2015)](http://musicbrainz.org/release/b2e39c83-feb3-4ef5-bf7e-e003761a51c5)

```
Correcting tags from:
    Lukas Graham - Lukas Graham (Blue Album)
To:
    Lukas Graham - Lukas Graham
URL:
    http://musicbrainz.org/release/b2e39c83-feb3-4ef5-bf7e-e003761a51c5
This album is already in the library!
[S]kip new, Keep both, Remove old? s
```

I've read the docs and I can't find an option that allows me to directly paste the ID/URL when importing.

**Comment by sampsyo** [comment]
Interesting. It looks like beets has chosen that release and is *so confident* in its choice that it gave it a high enough score that it didn't want to confirm with you. If you want a shot at pasting a custom ID, you can run in "timid" mode or use the new `--search-id` option to specify an ID a priori.

And to be clear, if you follow that link, you'll see that it *did* (correctly?) choose the Blue Album release. In MB land, however, that's not part of the release's title -- that's its "disambiguation string," so beets isn't displaying it here. Confusing, I know!

**Comment by grawlinson** [comment]
Is that option `--search-id` in the docs? I was looking for something like that.

I ended up just importing as-is, which did what I want for now.

Thanks for your help, much appreciated! :+1:

**Comment by sampsyo** [comment]
Looks like it's at the bottom of this section: http://docs.beets.io/en/v1.3.17/reference/cli.html#import
