### ISSUE TITLE
Not able to import different release/version of the same album as it "already exists"

### ISSUE THREAD

**Issue by jonathanthomas83** [beetbox/beets#1882]
Beets currently chooses to prompt for duplicate album when the titles match. This is expected behaviour, but becomes problematic when I explicitly want to import a US release with a different track order or different tracks unavailable on the currently imported release.

Another good example of this would be when a single takes its name from the title track of the album, so both the album and the single share the same name.

But the most common scenario is when I get a UK and a US release with different tracks on each. I'd like them both in my library, for completion sake.

Is there any way to tell Beets that this is a different release based on its MBID and append a country code to the album title (or better alternative) if required, to get around the filing issues that this could cause.

Many thanks

**Comment by sampsyo** [comment]
Hi! These situations , where you have two different releases with the same name, is what the "keep both" option at that prompt is meant for. Try choosing that.

Have you read about %aunique in the docs? It avoids collisions among such albums on the file system.

**Comment by jonathanthomas83** [comment]
Sorry @sampsyo, I didn't know this function existed. My bad. Thank you.

**Comment by jonathanthomas83** [comment]
@sampsyo Do you have an example of how I should make my path so that includes the function? Sorry, I know that's probably basic stuff...here's my path..

`default: artists/$albumartist_sort/$original_year $album/$track $title`

Many thanks

**Comment by sampsyo** [comment]
The defaults are a good example: http://docs.beets.io/en/v1.3.17/reference/config.html#path-format-configuration

**Comment by jonathanthomas83** [comment]
Ah man, I'm sorry, I did look...I promise! Didn't look hard enough. Apologies and thanks.

**Comment by sampsyo** [comment]
No worries whatsoever! :sparkles:
