### ISSUE TITLE
configure beets to use relative paths

### ISSUE THREAD

**Issue by fx3O2** [beetbox/beets#1883]
I moved my music folder and the beets library file to a new machine. The old path looks like `/media/data1/manu/musik` (external hdd) while the new one is just `/home/manu/Musik`. Now I asked on #beets how to move the library to a new place, as all queries still include the old path. Freso on IRC told me about how to [point beets to a new music directory](http://beets.readthedocs.org/en/latest/faq.html#point-beets-at-a-new-music-directory). I also use syncthing to keep all my music in sync with my computer, laptop and other users. So there could be always different locations included.

I dont know why beets is saving the absolute path in its library. In my opinion it just feels wrong. If there is an option to use relative paths, I would never have to mess around with wrong paths in my library. Beets should consider relative paths and provide a **path** option to do so:

```
directory: ~/Musik
library: ~/Musik/lib.db
path: relative

import:
    move: yes
plugins:
    edit
    info
    random
    missing
    fetchart
    embedart
    badfiles
    thumbnails
    duplicates
    fromfilename
```

Thanks in advance!

PS: There is no `-M` option with `beet import`? Regarding to the docs:

> Delete your database and re-create it from the new paths using beet import -AWMC.

**Comment by sampsyo** [comment]
Hi! Please see #133.

> PS: There is no -M option with beet import? Regarding to the docs:

Oops! That looks like a docs bug. Any chance you could open a PR to correct it?
