### ISSUE TITLE
RFE: `beet foreach`, shell integration

### ISSUE THREAD

**Issue by intelfx** [beetbox/beets#1890]
This is yet another feature request. It would be very nice to have a `beet foreach` or (`beet do`) verb with syntax of `beet foreach <QUERY...> -- <COMMAND...>`, which would execute the specified command (with field substitutions as in `beet list`) using system() or equivalent for each track matching the query.

In fact, this would allow doing various things with the tracks without implementing them as beets plugins (which requires significantly more boilerplate than writing a shell one-liner, at least on Linux).

~~An obvious addition to this would be to allow to give aliases to the commands via the config file, and (even better) to register such commands for various beets' pipeline stages (like plugins do).~~ (solved by in-flight `hook` plugin, see below)

Well, I'm just obsessed with extensibility and the shell language.

**Comment by sampsyo** [comment]
Nifty! Unixy extensibility is awesome, of course.

For the first case, the usual way people do this is with `xargs`—namely, `xargs -d'\n'`. And for the "in-pipeline" idea, that more or less matches this in-progress "hook" plugin: https://github.com/beetbox/beets/pull/1603

Do those cover what you were looking for, more or less?

**Comment by intelfx** [comment]
Yes — right now I do `beet list -f | xargs -n1 bash`, or `beet list | while read`, but i was looking for something... well, more integrated. And the hook plugin is exactly what I've meant (in the second part of the RFE), thanks.

**Comment by sampsyo** [comment]
Cool. To my sensibilities, `xargs` seems like the Unixy "one thing well" way to do it, but maybe the new hook plugin should consider adding an `exec` or similar command for people who would like to type even less (or who are not on Unix). Could you perhaps comment on that thread if you're interested?
