### ISSUE TITLE
stats -e fails on windows when path contains some characters

### ISSUE THREAD

**Issue by GuilhermeHideki** [beetbox/beets#1891]
Python can't get the size of some files because it can't find the correct folder or file, throwing OSError 2 and 3's.

### Problem
It's probably a difference on windows paths / linux or decoding?
https://github.com/beetbox/beets/blob/master/beets/ui/commands.py#L1260

Examples:

Chinese characters on `1.07 2Cellos feat. 郎朗 - Clocks.m4a`
```sh
could not get size of X:\lts\music\#\2Cellos\Albums\[2012] In2ition {256 kbps AAC}\1.07 2Cellos feat. éƒŽæœ— - Clocks.m4a: 
[Error 2] The system cannot find the file specified: 'X:\\lts\\music\\#\\2Cellos\\Albums\\[2012] In2ition {256 kbps AAC}\\1.07 2Cellos feat. \xe9\x83\x8e\xe6\x9c\x97 - Clocks.m4a'
```
Apostrophe on `X:\lts\music\Z\ZZ Top\Albums\[1971] ZZ Top’s First Album {320 kbps MP3}\1.01 ZZ Top - (Somebody Else Been) Shaking Your Tree.mp3`
```sh
could not get size of X:\lts\music\Z\ZZ Top\Albums\[1971] ZZ Top’s First Album {320 kbps MP3}\1.01 ZZ Top - (Somebody Else Been) Shaking Your Tree.mp3:
[Error 3] The system cannot find the path specified: 'X:\\lts\\music\\Z\\ZZ Top\\Albums\\[1971] ZZ Top\xe2\x80\x99s First Album {320 kbps MP3}\\1.01 ZZ Top - (Somebody Else Been) Shaking Your Tree.mp3'
```

### Setup

* OS: Win 10
* Python version: 2.7.11
* beets version: lastest

###### My configuration:
 - I don't "asciify" my paths
 - codepage is 1252 in `chcp`, `locale.getdefaultlocale() = ('en_US', 'cp1252')` and `terminal_encoding: cp1252`

**Comment by sampsyo** [comment]
Thanks for the report! I think the fix was relatively straightforward—can you please check whether the above commit fixes this?

**Comment by GuilhermeHideki** [comment]
This reduces the quantity of problems, but now I get Unicode problems with the apostrophe `’` `\u2019`
```sh
could not get size of X:\lts\music\B\Bruce Springsteen\Albums\[1984] Born in the U.S.A. {320 kbps MP3}\1.09 Bruce Springsteen - I’m Goin’ Down.mp3:
[Error 2] The system cannot find the file specified: u'\\\\?\\X:\\lts\\music\\B\\Bruce Springsteen\\Albums\\[1984] Born in the U.S.A. {320 kbps MP3}\\1.09 Bruce Springsteen - I\u2019m Goin\u2019 Down.mp3'
```

**Comment by sampsyo** [comment]
There's an apostrophe in one of the examples above too. Was that affected?

**Comment by GuilhermeHideki** [comment]
Oh, my bad. some files had inconsistent paths, so I renamed manually the file to the same as in beets and use `move`. This had the typewriter apostrophe instead of the curly one

**Comment by sampsyo** [comment]
Woohoo!
