### ISSUE TITLE
Music library shared between Windows and Linux - file paths

### ISSUE THREAD

**Issue by Ezodev** [beetbox/beets#1897]
Hi. I'm using both Linux and Windows(dual booting). Problem is, path to music library from the Windows point of view  is 'D:\nMusic', and from the Linux point of view it's '/mnt/data/nMusic'. That causes problems with, for example, 'beet write' command -> it reports 'missing file', because in DB it's using path to the file from the other OS.

Can't it somehow be fixed?

If not, then could anyone tell me how may I change file patches in DB so they're all in form '/mnt/data/nMusic/*actual path*'? I tried simply changing all the strings in DB from 'D:' to '/mnt/data', but then of course DB is damaged... any suggestions about which tool could help?

**Comment by sampsyo** [comment]
There's not currently a good way to maintain paths that will work from two different OSes. See #133.

Some of these tips in the FAQ might be relevant: http://docs.beets.io/en/v1.3.17/faq.html#point-beets-at-a-new-music-directory

Short of manually modifying the SQLite database with the `sqlite3` command-line tool, one option is to import again (in non-autotagged mode) to reconstruct the database.

**Comment by Ezodev** [comment]
"Short of manually modifying the SQLite database with the sqlite3 command-line tool, one option is to import again (in non-autotagged mode) to reconstruct the database."

This wouldn't result in any data loss, right? Like chroma plugin data? I have 'write' enabled on import.

**Comment by sampsyo** [comment]
Probably not (fingerprints, for example, are included in files' tags), but it would be worth making a backup and comparing to be sure.

**Comment by Ezodev** [comment]
Okay, I've done that and it seems everything's fine. Thanks for help!
