### ISSUE TITLE
Enable 'beet mod' style tag definition with 'beet import'

### ISSUE THREAD

**Issue by khimaros** [beetbox/beets#1899]
It would be useful to be able to tag all music while importing a new directory.

The behavior would be similar to the 'beet mod' command but applied during import.

For example:

% beet import /path/to/music special=mashups
% beet import /path/to/other special=remixes

With some workflow, you can accomplish this now:

% beet import /path/to/music
% beet mod -y '^special::\w+' special=mashups
% beet import /path/to/other
% beet mod -y '^special::\w+' special=remixes 

However, this becomes unruly unless you use the same field for all imports.

**Comment by sampsyo** [comment]
Please see #1881.
