### ISSUE TITLE
Fetch MusicBrainz track disambiguation field

### ISSUE THREAD

**Issue by SimonHova** [beetbox/beets#1904]
I download a lot of singletons, and I use the track disambiguation notes frequently. I saw that Beets has a way to note the **album** disambig, but not the **track** disambig. Can this be inserted into a future release? This way, my beets.yaml config could look something like this:

`paths:
    default: $albumartist_sort/[$year] $album/$track. $artist- $title
    comp: Various Artists/[$year] $album/$track. $artist- $title
    singleton: $artist_sort/$artist- $title [$trackdisambig]
`

**Comment by sampsyo** [comment]
Yes, sounds like a very reasonable addition.
