### ISSUE TITLE
import using pre-existing musicbrainz tags

### ISSUE THREAD

**Issue by zuzzurro** [beetbox/beets#1919]
My audio files are pre-tagged using Picard.
When importing these files, does beets take into consideration the pre-existing musicbrainz metadata?
Basically I find musicbrainz very useful for managing the initial matching in a gui oriented way, but once the relationship is established i prefer the batch oriented beets way.

**Comment by sampsyo** [comment]
Yes, beets uses the existing metadata, including IDs in the files' tags.

You can also use `-A` to use the existing metadata as-is every time, without looking it up again.

**Comment by zuzzurro** [comment]
Good. What made me wonder is that the process for importing already picard-tagged folders with multiple CD (cd1, cd2 or disc1, disc2) seem way more complicated than I would expect. Lots of questions gets asked, while since the ID are already there I would expect no questions..

**Comment by sampsyo** [comment]
Beets still needs a way to decide which songs are part of each album (described in the autotagging guide).

If something specific seems wrong, could you provide an example (along with what you expected to happen)?

**Comment by zuzzurro** [comment]
this is it. As each file is tagged with the musicbrainz release id/release group id, why does beets need to decide anything?

**Comment by sampsyo** [comment]
Did you mean to paste example output here?

Beets' importer balances the signal from the ID with other signals, like the track titles. If they don't line up perfectly, it asks you questions.

**Comment by zuzzurro** [comment]
OK, import log following..

**Comment by zuzzurro** [comment]
Before pasting the log, let me ask one more question.
In a multi cd case, Picard (Musicbrains?) names the tracks as 1-1, 1-2...1.10, 2-1,2-2 while beets seems to prefer 1,2,...,10,11,12...
while in the single cd case it just goes 1,2,...10
Is there a way to emulate the picard behavior in beets?

**Comment by sampsyo** [comment]
Please search the docs for `per_disc_numbering`.

**Comment by zuzzurro** [comment]
will do right away

**Comment by zuzzurro** [comment]
ok, seen that:
If you enable per_disc_numbering, you will likely want to change your Path Format Configuration also to include $disc before $track to make filenames sort correctly in album directories. For example, you might want to use a path format like this:
can i add the the disc number only in the multi-cd case?

**Comment by sampsyo** [comment]
The FAQ will help with that.

**Comment by zuzzurro** [comment]
And here is the log. With per_disc_numbering it's tidier, still my guess is that the questions do not come from a real difference but from different defaults from picard.

paolo@zot 2136> beet import /run/media/paolo/backups/lossless/Tracks/downloads/*Gaga*Monster*

/run/media/paolo/backups/lossless/Tracks/downloads/Lady Gaga - The Fame Monster
/run/media/paolo/backups/lossless/Tracks/downloads/Lady Gaga - The Fame Monster/Lady Gaga - The Fame Monster [Disc 1]
/run/media/paolo/backups/lossless/Tracks/downloads/Lady Gaga - The Fame Monster/Lady Gaga - The Fame Monster [Disc 2] (24 items)
Tagging:
    Lady Gaga - The Fame Monster
URL:
    http://musicbrainz.org/release/41ab0a5e-5378-33e6-941f-329047aa65f8
(Similarity: 98.5%) (tracks) (2xCD, 2009, IE, Interscope Records)
CD 1: The Fame Monster
 * Bad Romance (#1)                     -> Bad Romance (#1-1)
 * Alejandro (#2)                       -> Alejandro (#1-2)
 * Monster (#3)                         -> Monster (#1-3)
 * Speechless (#4)                      -> Speechless (#1-4)
 * Dance in the Dark (#5)               -> Dance in the Dark (#1-5)
 * Telephone (#6)                       -> Telephone (#1-6)
 * So Happy I Could Die (#7)            -> So Happy I Could Die (#1-7)
 * Teeth (#8)                           -> Teeth (#1-8)
CD 2: The Fame
 * Just Dance (#1)                      -> Just Dance (#2-1)
 * LoveGame (#2)                        -> LoveGame (#2-2)
 * Paparazzi (#3)                       -> Paparazzi (#2-3)
 * Poker Face (#4)                      -> Poker Face (#2-4) (id)
 * I Like It Rough (#5)                 -> I Like It Rough (#2-5)
 * Eh, Eh (Nothing Else I Can Say) (#6) -> Eh, Eh (Nothing Else I Can Say) (#2-6)
 * Starstruck (#7)                      -> Starstruck (#2-7)
 * Beautiful, Dirty, Rich (#8)          -> Beautiful, Dirty, Rich (#2-8)
 * The Fame (#9)                        -> The Fame (#2-9)
 * Money Honey (#10)                    -> Money Honey (#2-10)
 * Boys Boys Boys (#11)                 -> Boys Boys Boys (#2-11)
 * Paper Gangsta (#12)                  -> Paper Gangsta (#2-12)
 * Brown Eyes (#13)                     -> Brown Eyes (#2-13)
 * Summerboy (#14)                      -> Summerboy (#2-14)
 * Disco Heaven (#15)                   -> Disco Heaven (#2-15)
 * Again Again (#16)                    -> Again Again (#2-16)
This album is already in the library!
Old: 24 items, AAC, 224kbps, 91:48, 148.3 MiB
New: 24 items, AAC, 224kbps, 91:48, 148.2 MiB
[S]kip new, Keep both, Remove old? 

/run/media/paolo/backups/lossless/Tracks/downloads/Lady Gaga - The Fame Monster - 2009 [EAC - FLAC] (oan)
/run/media/paolo/backups/lossless/Tracks/downloads/Lady Gaga - The Fame Monster - 2009 [EAC - FLAC] (oan)/Lady Gaga - The Fame Monster [Disc 1]
/run/media/paolo/backups/lossless/Tracks/downloads/Lady Gaga - The Fame Monster - 2009 [EAC - FLAC] (oan)/Lady Gaga - The Fame Monster [Disc 2] (24 items)
Tagging:
    Lady Gaga - The Fame Monster
URL:
    http://musicbrainz.org/release/41ab0a5e-5378-33e6-941f-329047aa65f8
(Similarity: 100.0%) (2xCD, 2009, IE, Interscope Records)
CD 1: The Fame Monster
 * Bad Romance (#1)                     -> Bad Romance (#1-1)
 * Alejandro (#2)                       -> Alejandro (#1-2)
 * Monster (#3)                         -> Monster (#1-3)
 * Speechless (#4)                      -> Speechless (#1-4)
 * Dance in the Dark (#5)               -> Dance in the Dark (#1-5)
 * Telephone (#6)                       -> Telephone (#1-6)
 * So Happy I Could Die (#7)            -> So Happy I Could Die (#1-7)
 * Teeth (#8)                           -> Teeth (#1-8)
CD 2: The Fame
 * Just Dance (#1)                      -> Just Dance (#2-1)
 * LoveGame (#2)                        -> LoveGame (#2-2)
 * Paparazzi (#3)                       -> Paparazzi (#2-3)
 * Poker Face (#4)                      -> Poker Face (#2-4)
 * I Like It Rough (#5)                 -> I Like It Rough (#2-5)
 * Eh, Eh (Nothing Else I Can Say) (#6) -> Eh, Eh (Nothing Else I Can Say) (#2-6)
 * Starstruck (#7)                      -> Starstruck (#2-7)
 * Beautiful, Dirty, Rich (#8)          -> Beautiful, Dirty, Rich (#2-8)
 * The Fame (#9)                        -> The Fame (#2-9)
 * Money Honey (#10)                    -> Money Honey (#2-10)
 * Boys Boys Boys (#11)                 -> Boys Boys Boys (#2-11)
 * Paper Gangsta (#12)                  -> Paper Gangsta (#2-12)
 * Brown Eyes (#13)                     -> Brown Eyes (#2-13)
 * Summerboy (#14)                      -> Summerboy (#2-14)
 * Disco Heaven (#15)                   -> Disco Heaven (#2-15)
 * Again Again (#16)                    -> Again Again (#2-16)
This album is already in the library!
Old: 24 items, AAC, 224kbps, 91:48, 148.3 MiB
New: 24 items, AAC, 224kbps, 91:48, 148.2 MiB
[S]kip new, Keep both, Remove old?

**Comment by zuzzurro** [comment]
it seems beets is complaing about "(tracks)", because it manages the tracks in multiple cds in a different way. Is that correct?

**Comment by sampsyo** [comment]
Yep. Looks like beets is tagging this automatically, without user intervention, except for the duplicate detector (which is not related to metadata matches). Is there still a problem?

**Comment by sampsyo** [comment]
> it seems beets is complaing about "(tracks)", because it manages the tracks in multiple cds in a different way. Is that correct?

That's just indicating that the tracks' tags don't have a disc number, but beets wants to add one.

**Comment by zuzzurro** [comment]
I think we are mostly fine.
Apart from checking the FAQ for adapting the naming to making it more similar to the Picard way, there's one last small issue.
As you can see above there are two copies of the same disc that are tagged by picard in the exact same way (I retagged them 1 minute ago) still beets complains about the tag of

 Poker Face (#4)                      -> Poker Face (#2-4) (id)

How can that be?

**Comment by sampsyo** [comment]
That's indicating that there's an ID mismatch. Maybe you can dig in a little further and investigate why (which IDs didn't match).

**Comment by zuzzurro** [comment]
```
paolo@zot 2146> operon list -a /run/media/paolo/backups/lossless/Tracks/downloads/Lady\ Gaga\ -\ The\ Fame\ Monster\ -\ 2009\ \[EAC\ -\ FLAC\]\ \(oan\)/Lady\ Gaga\ -\ The\ Fame\ Monster\ \[Disc\ 2\]/04\ -\ Poker\ Face.m4a                                                                                                  
 Description                   | Value                                                                       | Tag                      
-----------------------------------------------------------------------------------------------------------------------------------------
 Title                         | Poker Face                                                                  | title
 Artist                        | Lady Gaga                                                                   | artist
 Album                         | The Fame Monster                                                            | album
 Date                          | 2009-11-20                                                                  | date
 Encodedby                     | qaac 2.58, CoreAudioToolbox 7.10.5.0, AAC-LC Encoder, TVBR q100, Quality 96 | encodedby
 Genre                         | Electronic, Hip Hop, Pop                                                    | genre
 Track                         | 4/16                                                                        | tracknumber
 MusicBrainz Release Artist ID | 650e7db6-b795-4eb5-a702-5ea2fc46c848                                        | musicbrainz_albumartistid
 MusicBrainz Release ID        | 41ab0a5e-5378-33e6-941f-329047aa65f8                                        | musicbrainz_albumid
 MusicBrainz Artist ID         | 650e7db6-b795-4eb5-a702-5ea2fc46c848                                        | musicbrainz_artistid
 MusicBrainz Recording ID      | ce3a5a96-e755-4742-9f20-2578600daa4c                                        | musicbrainz_trackid
paolo@zot 2147> operon list -a  /run/media/paolo/backups/lossless/Tracks/downloads/Lady\ Gaga\ -\ The\ Fame\ Monster/Lady\ Gaga\ -\ The\ Fame\ Monster\ \[Disc\ 2\]/04\ -\ Poker\ Face.m4a           
 Description                   | Value                                                                       | Tag                      
-----------------------------------------------------------------------------------------------------------------------------------------
 Title                         | Poker Face                                                                  | title
 Artist                        | Lady Gaga                                                                   | artist
 Album                         | The Fame Monster                                                            | album
 Date                          | 2009-11-20                                                                  | date
 Encodedby                     | qaac 2.58, CoreAudioToolbox 7.10.5.0, AAC-LC Encoder, TVBR q100, Quality 96 | encodedby
 Genre                         | Electronic, Hip Hop, Pop                                                    | genre
 Track                         | 4/16                                                                        | tracknumber
 MusicBrainz Release Artist ID | 650e7db6-b795-4eb5-a702-5ea2fc46c848                                        | musicbrainz_albumartistid
 MusicBrainz Release ID        | 41ab0a5e-5378-33e6-941f-329047aa65f8                                        | musicbrainz_albumid
 MusicBrainz Artist ID         | 650e7db6-b795-4eb5-a702-5ea2fc46c848                                        | musicbrainz_artistid
 MusicBrainz Recording ID      | 080975b0-39b1-493c-ae64-5cb3292409bb                                        | musicbrainz_trackid
paolo@zot 2148> 

```


What else can I do for investigating?

**Comment by zuzzurro** [comment]
Gees, there it is. A different recording ID..

**Comment by zuzzurro** [comment]
Amazing. In Picard the two files are exactly the same. Looks like it botches writing the tag in the file..

**Comment by sampsyo** [comment]
That'd do it, certainly!

**Comment by zuzzurro** [comment]
OK, got the multidisc configuration right. One last thing, is there a way for disc number to have the numbered from 1 to 9 instead of 01 to 09?

**Comment by sampsyo** [comment]
One hacky way is to use the `inline` plugin to define a `$mydisc` field that is just an alias for `disc`.

**Comment by zuzzurro** [comment]
Or adapt this example from the inline plugin page :
```
item_fields:
    initial: albumartist[0].upper() + u'.'
    disc_and_track: u'%01i.%02i' % (disc, track) if
                    disctotal > 1 else u'%01i' % (track)
```
Right?

I have been meaning for more than a year to adopt beets for managing my music library. Now that I started really doing it, it's performing the way I hoped. Thanks a real lot.

**Comment by sampsyo** [comment]
Yep! Glad things are working for you.
