### ISSUE TITLE
%media imported from Discogs is always CD

### ISSUE THREAD

**Issue by kroem** [beetbox/beets#1921]
All releases from Discogs show up as CD - when matching to a release on MB there a correct tag . 

Anyway to get beets to pickup if a release is CD/Vinyl/Digital when importing from Discogs? There's so many of my releases that aren't on MB so Discogs is pretty essential. 

Alternatively - and this is outside of beets I guess - is there any smooth import/export feature to get a Discogs release to MB?

**Comment by sampsyo** [comment]
Interesting. Are there ever multiple media choices when you choose to see more options?

I haven't used it, but I've heard the standard way to move stuff from Discogs to MB is to use a browser-side user script. This thing, perhaps? https://github.com/murdos/musicbrainz-userscripts

**Comment by kroem** [comment]
Apologies for my newbieness - but how do I see more options? :) 

I'll try to get the script going also!

**Comment by sampsyo** [comment]
I meant the "M" choice: http://docs.beets.io/en/v1.3.17/guides/tagger.html#choices

**Comment by kroem** [comment]
Ah ok! Yes, the media shows up there;

/media/vol2/Sorted/SortedMusik/---Highres/Ryan Adams - 2011 - Ashes & Fire (CD FLAC 96kHz-24 bits) (11 items)
Tagging:
    Ryan Adams - Ashes & Fire
URL:
    http://musicbrainz.org/release/513486c0-cbc3-4c88-a056-08ec7c5e41c0
(Similarity: 84.7%) (id, label, media) (CD, 2011, US, PAX•AM)
 * Chains Of Love                          -> Chains of Love
 * I Love You But I Don't Know What To Say -> I Love You but I Don’t Know What to Say
[A]pply, More candidates, Skip, Use as-is, as Tracks, Group albums,
Enter search, enter Id, aBort, eDit, edit Candidates? m
Finding tags for album "Ryan Adams - Ashes & Fire".
Candidates:
1. Ryan Adams - Ashes & Fire (84.7%) (id, label, media) (CD, 2011, US, PAX•AM)
2. Ryan Adams - Ashes & Fire (81.5%) (id, source, year, ...) (Discogs, CD, 2011, US, Pax Americana Record Company)
3. Ryan Adams - Ashes & Fire (80.9%) (id, source, year, ...) (Discogs, CD, 2011, UK & Europe, Pax Americana Record Company)
4. Ryan Adams - Ashes & Fire (80.1%) (id, mediums, missing tracks, ...) (2xCD, 2011, US, PAX•AM, Deluxe Edition)
5. Ryan Adams - Ashes & Fire (79.8%) (id, mediums, source, ...) (Discogs, 2xVinyl, 2011, US, Pax Americana Record Company)
6. Ryan Adams - Ashes & Fire (79.2%) (id, mediums, source, ...) (Discogs, 2xVinyl, 2011, UK & Europe, Pax Americana Record Company)
7. Ryan Adams - Ashes & Fire (76.2%) (id, mediums, source, ...) (Discogs, 3xVinyl, 2011, US, Pax Americana Record Company)
8. Ryan Adams - Swedish Sessions (38.0%) (tracks, id, album, ...) (CD, 2002, US, Lost Highway Records)
9. Ryan Adams - 2002-02-13: Century Ballroom, Seattle, WA, USA (disc 2) (33.2%) (tracks, id, album)
10. Ryan Adams - 2002-09-29: Austin City Limits Festival, Austin, TX, USA (32.3%) (tracks, id, album)
# selection (default 1), Skip, Use as-is, as Tracks, Group albums,
Enter search, enter Id, aBort, eDit, edit Candidates? 6
Tagging:
    Ryan Adams - Ashes & Fire
URL:
    https://www.discogs.com/Ryan-Adams-Ashes-Fire/release/3166333
(Similarity: 79.2%) (id, mediums, source, year, country) (Discogs, 2xVinyl, 2011, UK & Europe, Pax Americana Record Company)
Vinyl 1
Vinyl 2
Apply, More candidates, Skip, Use as-is, as Tracks, Group albums,
Enter search, enter Id, aBort, eDit, edit Candidates? a


But the %media tag is still written as CD

**Comment by sampsyo** [comment]
Hmm, interesting—and, to be clear, you're checking the media field by typing `beet ls -af '$media' …` or similar, right? Can you show the output of that to confirm what the tag contains?

**Comment by kroem** [comment]
I'm getting something wrong when trying that - 

freeleech@debian:~$ beet ls -af '$media' beach
$media
$media
$media
$media
$media
$media
freeleech@debian:~$ beet ls -a beach
Beach House - Bloom
Beach House - Depression Cherry
Beach House - Depression Cherry
Beach House - Teen Dream
Beach House - Thank Your Lucky Stars
Beach House - Thank Your Lucky Stars

But the media tag works, but not with -a flag: 

freeleech@debian:~$ beet ls -a beach media:Vinyl
freeleech@debian:~$ beet ls beach media:Vinyl
Beach House - Bloom - Myth
Beach House - Bloom - Wild
Beach House - Bloom - Lazuli
Beach House - Bloom - Other People
Beach House - Bloom - The Hours
Beach House - Bloom - Troublemaker
Beach House - Bloom - New Year
Beach House - Bloom - Wishes
Beach House - Bloom - On the Sea
Beach House - Bloom - Irene
Beach House - Teen Dream - Zebra
Beach House - Teen Dream - Silver Soul
Beach House - Teen Dream - Norway
Beach House - Teen Dream - Walk in the Park
Beach House - Teen Dream - Used to Be
Beach House - Teen Dream - Lover of Mine
Beach House - Teen Dream - Better Times
Beach House - Teen Dream - 10 Mile Stereo
Beach House - Teen Dream - Real Love
Beach House - Teen Dream - Take Care
Beach House - Thank Your Lucky Stars - Majorette
Beach House - Thank Your Lucky Stars - Majorette
Beach House - Thank Your Lucky Stars - She’s So Lovely
Beach House - Thank Your Lucky Stars - She’s So Lovely
Beach House - Thank Your Lucky Stars - All Your Yeahs
Beach House - Thank Your Lucky Stars - All Your Yeahs
Beach House - Thank Your Lucky Stars - One Thing
Beach House - Thank Your Lucky Stars - One Thing
Beach House - Thank Your Lucky Stars - Common Girl
Beach House - Thank Your Lucky Stars - Common Girl
Beach House - Thank Your Lucky Stars - The Traveller
Beach House - Thank Your Lucky Stars - The Traveller
Beach House - Thank Your Lucky Stars - Elegy to the Void
Beach House - Thank Your Lucky Stars - Elegy to the Void
Beach House - Thank Your Lucky Stars - Rough Song
Beach House - Thank Your Lucky Stars - Rough Song
Beach House - Thank Your Lucky Stars - Somewhere Tonight
Beach House - Thank Your Lucky Stars - Somewhere Tonight
Bon Iver - Blood Bank - Beach Baby

**Comment by kroem** [comment]
Just noticed another thing, the $albumtype is more descriptive for Discogs, MusicBrainz do not give the "lp" tag there either. Maybe it can pick up on there being a "LP" tag and write -> Vinyl in $media ... 
My path is like this: 
$albumartist - $year - $album%aunique{} ($albumtype $media $format $samplerate%if{$bitdepth,-$bitdepth bits})/$track - $title

From Discogs ( wrong $media tag )
Bright Eyes - 2002 - Lifted Or The Story Is In The Soil, Keep Your Ear To The Ground (LP, Album CD FLAC 96kHz-24 bits)

From MB, only a album flag in the $albumtype.
Bright Eyes - 2005 - I’m Wide Awake, It’s Morning (album 12_ Vinyl FLAC 96kHz-24 bits)

**Comment by sampsyo** [comment]
Oops! Sorry; $media is a track-level field, so you'll need to query it without -a.

I don't quite understand what you're saying about albumtype—that, as far as we know, only comes from MB.

**Comment by kroem** [comment]
Nvm the albumtype thing - if it's MB exclusive then that's my answer :) 

Anyways, the $media tag is populated: 

freeleech@debian:~$ beet list -f '$media' artist:beach house
12" Vinyl
Digital Media
12" Vinyl
Digital Media
12" Vinyl
Digital Media
12" Vinyl
Digital Media
...


Full: https://gist.github.com/kroem/38f30f3c7ca5128c4845648c4b566feb

**Comment by sampsyo** [comment]
Hmm, so the media field seems to be set correctly. Perhaps I'm misunderstanding something, but is there still a problem here?

**Comment by kroem** [comment]
Maybe I got sidetracked - the issue is that Discogs never tags media, even though it does show up as "Vinyl" in the selection (see below)

I mean, this could just be how it is, but still it would be nice if it could add a %media field (pretty "important" :) ) 

/media/vol2/rtorrent/completed/what.cd/D-Pulse - Keep On Running (320) (4 items)
Tagging:
    D-Pulse - Keep On Running
URL:
    https://www.discogs.com/D-Pulse-Keep-On-Running/release/4904968
(Similarity: 83.7%) (source, year, country, media, tracks) (Discogs, **2xVinyl**, 2013, Russia, Teardrop)
Vinyl 1
 * Keep On Running -> Keep On Running (Original Mix) (title)
Vinyl 2
[A]pply, More candidates, Skip, Use as-is, as Tracks, Group albums,
Enter search, enter Id, aBort, eDit, edit Candidates?

**Comment by sampsyo** [comment]
OK, I think I'm still confused—what do you mean by "Discogs never tags media"? Does that mean `beet ls -f '$media'` *for this album you're showing here* doesn't say "vinyl"?

**Comment by kroem** [comment]
Exactly!

**Comment by sampsyo** [comment]
OK, thanks for bearing with me!

I looked into it, and it indeed looks like the Discogs plugin sets the `media` field on the `AlbumInfo` objects it returns, but not the `TrackInfo` objects. And `beets.autotag.apply_metadata` is only sensitive to the latter.

This should be pretty straightforward to fix. If anyone's interested but needs more hints, please let me know!

**Comment by diego-plan9** [comment]
Closed by #2222
