### ISSUE TITLE
Is the music workflow I would like to achieve possible at the moment?

### ISSUE THREAD

**Issue by zuzzurro** [beetbox/beets#1924]
### Problem

The workflow I would like to have is the following:

1) Be able to run beet import against a folder containing my discs (flac, mostly)
2) Have beet move the imported folder to an "imported" folder, without affecting the original folder content
3) Have all the relevant music files added to the master beet folder with new names and tags
4) use symbolic links, hard links or reflinks from the master folder's music files to the "original" folder files
5) add the tags to the master folder (and because of point 4 to have the "original" files affected).
6) convert all files using the "convert" plugin but mirroring all changes in the master folder (file naming, additions, removals and/or metadata" changes

I'm not sure whether all these points can be done already, according to my reading of the documentation, no but I could be wrong. I am pretty sure neither hard links nor reflinks are possible right now.

**Comment by sampsyo** [comment]
Have you tried the `import.link` config option? http://docs.beets.io/en/v1.3.17/reference/config.html#link

**Comment by zuzzurro** [comment]
Yes, I was aware of that. It relates to point 4 only I guess. I could use that but I'd rather have either hard links or reflinks. Let's say that point 4 could be considered covered.
What about points 2 and 6?

**Comment by sampsyo** [comment]
Aha; thanks for clarifying. Yes, there's a symlink mode but not one for hard links or COW copies on filesystems that support that. If you're interested in writing up the feature request in more detail, we'd be happy to have a ticket specifically for one or the other as a drop-in replacement for the current `link` option.

(2) is the default behavior in copy/symlink mode, and (6) is the default behavior of the convert plugin (if I understand you correctly).

**Comment by zuzzurro** [comment]
Let's cover all the points and see what comes out in the end.

Point 2) Really? In copy and link mode, a copy is created in the destination folder, but the source folder is untouched. What I would like to achieve instead is to move from the files from the ingest folder to an archive folder (without touching any of the files at all) and then link or copy into the master directory structure just the audio files.
Point 6) The convert plugin works fine but the destination assets are totally unamaged. What I would like to have is that if a metadata update from MB comes, the tags should be applied to both the master (lossless, flac) asset AND to the various lower quality copies. Also, if I decide to delete or rename the master assets, the change should be mirrored to the lossy files.

**Comment by sampsyo** [comment]
2: OK, I think I get it now -- you want a set up with *three different folders* (ingest, archive, and library). There's no feature like that but it would probably be easy to whip up in a custom plugin that just moves files after they're done being imported.

6: Ah, so you want changes you make *later* to also be reflected in the copies. I think that's the intention of the third-party [beets-alternatives ](https://github.com/geigerzaehler/beets-alternatives) plugin.

**Comment by zuzzurro** [comment]
Will check that the beets-alternatives plugin but the first thing I noticed is that the last update was in May 2015. I wonder if it's still actively maintained

**Comment by zuzzurro** [comment]
I used Fedora and I tend to prefer to use pre-packaged software (spent a lot of time when I was younger installing tar.gz files). The issue with Fedora is that it's already difficult to have the standard beets packaged (the convert plugin is not included because its relationship with ffmpeg). Adding plugins will make it even more difficult.
Do you think that the beets-alternatives functionality/implementation could end up in the main release?

**Comment by sampsyo** [comment]
That's quite strange that Fedora doesn't package the convert plugin. I didn't know that was going on. It doesn't actually depend on ffmpeg; you can configure it to use any command to transcode. We should probably talk to someone to resolve that.

It's definitely worth considering merging that plugin in! Someone would need to take ownership and do the work to bring it up to speed with the core beets standards.

**Comment by zuzzurro** [comment]
I have the same opinion about the dependency of convert on ffmpeg. As a matter of fact I configured it for using qaac... :-) but first I had to do my own repackaging based on the fedora one.

**Comment by jrobeson** [comment]
does the convert plugin error nicely if no backends are available? If so, I'm not sure why it can't be packaged.

**Comment by sampsyo** [comment]
Yep, it should print a nice error when the command isn't found.

**Comment by afreof** [comment]
Added a bug in Fedoras bug tracker: https://bugzilla.redhat.com/show_bug.cgi?id=1409374
There seems to be no reason for deleting the plugin in the spec file.

**Comment by sampsyo** [comment]
Great; thank you!

**Comment by zuzzurro** [comment]
OK, I got the update from updates-testing and lo and behold the plugin is there. That's really nice and one step forward.
Now, I still would LOVE to use beets for automating my workflow, but every time I try it, I fail. Do you mind if we go back to what's missing?

**Comment by zuzzurro** [comment]
OK, let's go through my workflow and my expectations for using beets in it step by step: 
First step: tagging.
I do all my tagging using Picard. While I'm an old style command line oriented guy I also think that using a GUI in this phase is easier and less error prone. I can easily choose the correct disk on MB and if needed I will create/import new releases. What I see beets 100% more useful is in the later stages, when disks are already tagged and I need to manage the full collection in a batch mode. This is in my opinion where a command line tool is unbeatable.
Second step: saving the tags.
At this point the CD has been tagged. Currently I only save tags. I mostly don't use the renaming function, and the directories/file names are left as is. Currently I choose two options in Picard:
"Use standardized artist names" and "Convert Unicode punctuation characters to ASCII".
Keep these in mind because I think these three points are going to hit me later, when I try to import my files in beets.
Third step: import into beets.
At this point, I would like to import my files into beets. Let's discuss later on the precise procedure in terms of "ingest", "archive" and whatever folder, let's just concentrate on the import.
Right now beets does not easily allow me to import the files I tagged because of these reasons. Easily means without being fussy and asking lots of questions.
The questions beets asks are:
1) ID mismatch. This is unavoidable, if the disk IDs have been changed on MB there's not a lot that can be done.
2) All other sorts of mismatches, comprising the dreaded one about different CDs having to be in different subfolders with a naming convention like CD 1, CD2 etc.
This one I really would like to avoid. Is there a way to give precedence to MB so that if there's a MB disk ID match that by itself is enough?
Other mismatches come from the fact that I use those two options in Picard. beets rightly complains about the saved are tags not exactly the same as the ones online and wants to correct them. That would probably be fine (I could also uncheck the flags in Picard) as long as there are similar flags in beets. In particular the "Use standardizes artist names" I cannot live without.

What about this for the beginning?

**Comment by sampsyo** [comment]
Here's an answer to a specific question:

> This one I really would like to avoid. Is there a way to give precedence to MB so that if there's a MB disk ID match that by itself is enough?

If you like, you can turn up the weight of the ID match by a lot. This option isn't documented, but this is the setting you want to increase: https://github.com/beetbox/beets/blob/master/beets/config_default.yaml#L109

Do you have other specific questions about beets? I think I understand your workflow, but I don't quite see where the specific problems are. Maybe just give it a try and report specific problems as you go?

**Comment by zuzzurro** [comment]
OK, I tried adding this to my configuration:
```
match:
    distance_weights:
        album_id: 20.0
```
But as soon as I get to a folder that has a different structure from the one beet accepts, it stops and complains of "(missing tracks, tracks)".
The folder structure in this case is a main folder containing flac files with a subfolder called "Bonus Disc" containing the bonus CD's flacs.
All the files have been tagged already but beets tries to "recognize" using its heuristic something (the fact that there are two CDs in this release) that would be perfectly clear by just looking at the already existing tags in the files.
Can this behaviour be changed by increasing the album_id weigh more? I don't think so if I understand its logic..

**Comment by zuzzurro** [comment]
One more example. In the meantime I increased the weight of album_id to 1000, just to see if that would help...
In one case someone changed the label of one disc. The album_id is the same, the label beets find on MB is different. Why does it have to stop for confirmation? The album_id is correct, just go ahead and import the file!! No need to ask for confirmation..

**Comment by sampsyo** [comment]
Sometimes, beets isn't able to figure out which albums should be grouped together from your folder hierarchy. That's life, unfortunately—no single heuristic can cover all cases! If you want to import one folder and all its subdirectories as one album, you might try using the `--flat` flag for those specific cases.

**Comment by sampsyo** [comment]
One other idea, if you want, is to try importing with autotagging turned off (the `-A` flag). Then, use the `mbsync` plugin to download metadata from MusicBrainz—that never asks for confirmation.

**Comment by zuzzurro** [comment]
I have tried --flat on a single folder containing a BOX of 19 cds. In this case it seems to work fine, but I suspect it would not work for me in a more general case. The -A suggestion i still have to try..

About your previous comment about the single heuristic covering all cases, I totally agree with you. And that is precisely what I'm asking.. In my opinion the heuristic for determining whether a subfolder contains multiple CDs just gets in the way because that information (and without heuristics) is already directly available in each tagged file.

I don't quite understand how can I explain myself better.. It may be a matter of english not being my first language, maybe.
