### ISSUE TITLE
Failure in tagging together folders with common prefix and disc number

### ISSUE THREAD

**Issue by zuzzurro** [beetbox/beets#1925]
### Problem

The documentation says that:

_First, directories that look like separate parts of a multi-disc album are tagged together as a single release. If two adjacent albums have a common prefix, followed by “disc,” “disk,” or “CD” and then a number, they are tagged together._

However I found out that if a folder contains:

Buddha Bar, Vol. 1 Disc 1
Buddha Bar, Vol. 1 Disc 2
Buddha Bar Vol.1 track list.txt

That is not just folders following the common prefix rule, but another file, it fails the import as a single album.

**Comment by sampsyo** [comment]
Thanks for filing! So we can try to address this bug, can you please put together a reproducible test case? Ideally, that would be an archive of music that imports incorrectly and a changed version (i.e., with that file removed?) that works how you expect it to.

**Comment by zuzzurro** [comment]
Where should the archive be uploaded?

**Comment by sampsyo** [comment]
How about a Dropbox (or equivalent) link?

**Comment by zuzzurro** [comment]
Sent it by email right now.

**Comment by zuzzurro** [comment]
Did you receive the onedrive link?

**Comment by sampsyo** [comment]
Yes, thanks! I'll give it a try soon.

**Comment by zuzzurro** [comment]
So, instead of just waiting I took a look at the source code. This is what I found in importer.py:

        # Check whether this directory looks like the *first* directory
        # in a multi-disc sequence. There are two indicators: the file
        # is named like part of a multi-disc sequence (e.g., "Title Disc
        # 1") or it contains no items but only directories that are
        # named in this way.

So, there's not much to say but that the documentation is not in line with the code and that the code clearly rejects the folder structure I have in my example.

The question might be: why is it so? Why do you want the code to be so strict? There's another requirement that seems too strict to me (at that fail in at least my real world) that the folder must have strictly the same prefix.

This is not what happens in reality. I see lots of folders that have similar names (but not identical) and sometimes I see a folder containing files (for the first disc) and then a single folder for the bonus disc, for instance.

Should people spend time moving stuff around just to please beets? As beets likes asking lots of questions anyway, why can't it ask questions in these cases too?

**Comment by sampsyo** [comment]
It's strict so it can conservatively avoid doing the wrong thing when folder names are accidentally similar. Of course, specific proposals about how to make this better would always be appreciated!

**Comment by sampsyo** [comment]
I finally got around to trying this out and, oddly enough, everything worked as expected despite the presence of that file:

```sh
$ beet imp ~/[...]/downloads 

[...]/downloads/Buddha Bar/Buddha Bar, Vol. 1/Buddha Bar, Vol. 1 Disc 1
[...]/downloads/Buddha Bar/Buddha Bar, Vol. 1/Buddha Bar, Vol. 1 Disc 2 (28 items)
Tagging:
    Claude Challe - Buddha-Bar
URL:
    http://musicbrainz.org/release/54c8547f-91e6-48f7-8747-aa83451b807c
(Similarity: 100.0%) (2xCD, 2003, GB)
CD 1: Buddha's Dinner
CD 2: Buddha's Party
[...]
$ ls -R ~/[...]/downloads
Buddha Bar

[...]/downloads/Buddha Bar:
Buddha Bar, Vol. 1

[...]/downloads/Buddha Bar/Buddha Bar, Vol. 1:
Buddha Bar Vol.1 track list.txt Buddha Bar, Vol. 1 Disc 2
Buddha Bar, Vol. 1 Disc 1
```

Perhaps you're on an older version of beets?

**Comment by zuzzurro** [comment]
I am using 1.3.17

**Comment by sampsyo** [comment]
OK, thanks for checking! I really don't know what else to try, though. Please let me know if you find specific steps to reproduce that you think will work on my machine.

**Comment by arcresu** [comment]
It's been some time now and we haven't heard from you. Without more detailed information it's really hard for the community to help you with this issue. If you'd still like help with this, feel free to reopen this issue or open a new one, but make sure you [include as much relevant information](https://www.cs.cornell.edu/~asampson/blog/bugrubric.html) as possible and describe how the problem can be reproduced by other users.
