### ISSUE TITLE
Rebuilding directory structure after using modify command

### ISSUE THREAD

**Issue by zbaylin** [beetbox/beets#1929]
I have all of my music in symlinks. I imported my music with the import command, but after doing this, two separate folders were created for same artists with different capitalization styles (ex. Tears for Fears and Tears For Fears). I used beet modify -M "Tears For Fears" artist="Tears for Fears", but after executing it, I still have two separate folders for the same artist. Currently, I don't think there is a way to update my symlink directory structure according to new changes to the library file. Can this be added in a later update?

**Comment by sampsyo** [comment]
Have you tried `beet move` (which is recommended in the FAQ)?
