### ISSUE TITLE
"beet import" not honouring strong_rec_thresh

### ISSUE THREAD

**Issue by joshuaboniface** [beetbox/beets#1933]
### Problem

When running "beet import", the "strong_rec_thresh" value specified in the default config (which I changed from 0.04 to 0.10) is not being honoured; even with a result in the 91% range, the selection is not automatically accepted and in quiet mode is skipped. This happens whether I edit the stock config, or add my own user config (I moved to editing stock as a troubleshooting step).

I have some very specific settings in the command below, however the config only has two changes from stock; aside from the strong_rec_thresh it seems to otherwise work fine.

Running this command in verbose (`-vv`) mode:

``` sh
$ sudo -u debian-transmission beet -vvvvvv -c /usr/local/lib/python2.7/dist-packages/beets/config_default.yaml import /srv/media/.unsorted/Opeth\ -\ Pale\ Communion\ \[Deluxe\ Edition\]\ \(2014\)/
```

With this diff of "/usr/local/lib/python2.7/dist-packages/beets/config_default.yaml":

```
 6,7c6,7
<     copy: yes
<     move: no

---
>     copy: no
>     move: yes
89c89
<     strong_rec_thresh: 0.04

---
>     strong_rec_thresh: 0.10
```

Led to this problem:

```
no user configuration found at /var/lib/transmission-daemon/.config/beets/config.yaml
data directory: /var/lib/transmission-daemon/.config/beets
plugin paths: 
Sending event: pluginload
library database: /var/lib/transmission-daemon/.config/beets/library.db
library directory: /var/lib/transmission-daemon/Music
Sending event: library_opened
Sending event: import_begin
Sending event: import_task_created
Sending event: import_task_start
Looking up: /srv/media/.unsorted/Opeth - Pale Communion [Deluxe Edition] (2014)
Tagging Opeth - Pale Communion [Deluxe Edition]
No album IDs found.
Search terms: Opeth - Pale Communion [Deluxe Edition]
Album might be VA: False
Sending event: albuminfo_received
Sending event: albuminfo_received
Sending event: albuminfo_received
Sending event: albuminfo_received
Sending event: albuminfo_received
Evaluating 5 candidates.
Candidate: Opeth - Pale Communion
Success. Distance: 0.11
Candidate: Opeth - Pale Communion
Success. Distance: 0.08
Candidate: Opeth - Pale Communion
Success. Distance: 0.38
Candidate: Opeth - Pale Communion
Success. Distance: 0.08
Candidate: Opeth - Heritage
Success. Distance: 0.64

/srv/media/.unsorted/Opeth - Pale Communion [Deluxe Edition] (2014) (10 items)
Sending event: before_choose_candidate
Correcting tags from:
    Opeth - Pale Communion [Deluxe Edition]
To:
    Opeth - Pale Communion
URL:
    http://musicbrainz.org/release/8160d8c4-5962-45dc-8071-20800d753e1d
(Similarity: 91.9%) (unmatched tracks, album, tracks) (Digital Media, 2014, XW, Roadrunner Records)
 * Voice of Treason (7:44) -> Voice of Treason (8:00) (length)
 * Faith in Others (7:58)  -> Faith in Others (7:41) (length)
Unmatched tracks (2):
 ! Solitude (Live) (#9) (5:58)
 ! Var Kommer Barnen In (live) (#10) (5:51)
[A]pply, More candidates, Skip, Use as-is, as Tracks, Group albums,
Enter search, enter Id, aBort? b
Sending event: import
Sending event: cli_exit
```

Here's a link to the music files that trigger the bug (if relevant):

This happens to numerous artists on two different servers, one of which worked flawlessly previously.
### Setup
- OS: Debian Jessie (8.3)
- Python version: 2.7.9
- beets version: 1.3.17 via pip
- Turning off plugins made problem go away (yes/no): fresh install

My configuration (output of `beet config`) is:

Stock, with the above diff applied.

**Comment by sampsyo** [comment]
This is due to the unmatched tracks, which by default "downgrade" any match to a medium recommendation regardless of distance. You can change the `max_rec` options to fix that if you like.

FWIW, I would recommend against editing the default configuration file—that could get weird!

**Comment by joshuaboniface** [comment]
Thanks for the update. I figured I was just missing something! And yes, I'd rather go back to a user config ;-)
