### ISSUE TITLE
fetchart: When using `enforce_ratio`, optionally tolerate slightly non-square images

### ISSUE THREAD

**Issue by strifeknot** [beetbox/beets#1944]
There is quite a lot of album art out there that differs slightly on x y ratio (eg: 300x296 pixels), using the enforce_ratio plugin excludes all of this. Could we implement a 'margin' option to allow a certain amount of leeway expressed as a percentage or in total pixels when using enforce_ratio?

**Comment by sampsyo** [comment]
Good idea. Anyone have opinions about whether this should be the default or not?

**Comment by wordofglass** [comment]
I like the idea (and might actually implement it). IMO, the default should not be changed though.

What would the config option look like? Two ways that come to mind:
* `allow_margin = yes|no`
* `enforce_ration = no|10px|5%|yes`

I think I'd prefer the latter; not sure how good this fits the config parsing framework, though.

**Comment by sampsyo** [comment]
It should be OK—there are a few other similar options. The `import.resume` option comes to mind, which can be `yes`, `no`, or `ask`.

**Comment by Kraymer** [comment]
+1 for `enforce_ratio = no|10px|5%|yes`

**Comment by wordofglass** [comment]
The confit facility used for `import.resume` probably won't work here, but there's a nice alternative :) Anyway, thanks for the pointer, it lead me to the right part of confit.

**Comment by wordofglass** [comment]
@strifeknot: Beets now has this feature in its latest development version! :)
