### ISSUE TITLE
mbsync: some changes do not seem to apply

### ISSUE THREAD

**Issue by ghost** [beetbox/beets#1946]
### Problem

When running "beet mbsync" some changes keep coming back. I ran the same command several times, but the same changes keep coming back. Here is an example with "orginal_day" and "original_month": http://paste.ubuntu.com/15905204/
### Setup
- OS: Ubuntu 14.04
- Python version: 
- beets version: beets version 1.3.17
  plugins: acousticbrainz, chroma, duplicates, echonest, embedart, fetchart, lastgenre, lastimport, mbcollection, mbsubmit, mbsync, missing, replaygain, smartplaylist

**Comment by sampsyo** [comment]
Interesting! Thanks for reporting. Can you check whether these files have an `original_year`? If not, I think the other two fields might be lost (because of the way dates are stored).

**Comment by Horla** [comment]
It doesn't seem so: http://paste.ubuntu.com/15906370/

**Comment by sampsyo** [comment]
Sorry, I should have been more specific—if you use beets' built in `beet list` or the `beet info` command (after enabling the `info` plugin), you can see exactly what beets knows about a file. That's important for debugging this kind of weird behavior.

**Comment by Horla** [comment]
http://paste.ubuntu.com/15908099/

**Comment by sampsyo** [comment]
Thanks for investigating—looks like that's probably not it.

I tried reproducing this locally by importing a new album as that Yes album, but `beet mbsync` was quiet immediately after import:

```
$ beet mbsync
$
```

Any other ideas on how we might reproduce this problem?

**Comment by arcresu** [comment]
It's been some time now and we haven't heard from you. Without more detailed information it's really hard for the community to help you with this issue. If you'd still like help with this, feel free to reopen this issue or open a new one, but make sure you [include as much relevant information](https://www.cs.cornell.edu/~asampson/blog/bugrubric.html) as possible and describe how the problem can be reproduced by other users.
