### ISSUE TITLE
Random sort option

### ISSUE THREAD

**Issue by strifeknot** [beetbox/beets#1948]
I'd like to be able to produce randomly sorted tracks from the Smart Playlist plugin (I'm not a big fan of using random tracks from within mpd - especially with mpd-sima) - I could run:
`beet list ... | sort -R > playlist.m3u`
daily off a systemd timer but was wondering if random+ might be considered as a native sorting option.

**Comment by sampsyo** [comment]
Hey, yeah, this kind of thing would be good! We've discussed routes toward this functionality in #795—could you perhaps add your thoughts there?
