### ISSUE TITLE
Lyrics: Review my patch please!

### ISSUE THREAD

**Issue by wordofglass** [beetbox/beets#1953]
Yesterday I did this

https://github.com/beetbox/beets/compare/271f7c8...607f41b

because my imports were breaking (i.e. with a traceback) halfway-through. I don't know the lyric plugin's code, though. So it might be good if someone who does had a look at it. 
Maybe these checks should be at top-level and would let the plugin issue a warning already on initialization if any of the activated sources need `beautifulsoup4` or `langdetect`?

**Comment by sampsyo** [comment]
Thanks for looking into this!

I'm a little confused about the need for https://github.com/beetbox/beets/commit/607f41be430507dc5f7522c19b5ee95605e0995c where the `langdetect` check was moved *outside* of the `if lyrics:` condition. This seems fine, but I don't quite see what it solves. @Kraymer, perhaps you'd like to take a look, since this is related to #1939?

And we apparently added an undocumented dependency on BeautifulSoup for the LyricsWiki backend in #1912. It would be awesome to avoid needing BS for such a simple scraping task (as we did before). @jackwilsdon, any thoughts on whether `scrape_lyrics_from_html` is really necessary here? If it is, we at least need to document the new dependency, and we should probably disable the source by default.

**Comment by wordofglass** [comment]
The idea behind the second commit was:
- The initial change to the `beautifulsoup` import didn't fix the breakage. I catched the `ImportError`, but that would only have postponed it to a `NameError` or somesuch.
- Do not print the `langdetect` warning for every song, but only on the first. I clearly failed at actually doing that. Which probably means that I should not push anything to master at that time of day.

**Comment by Kraymer** [comment]
> Do not print the langdetect warning for every song, but only on the first.

So, should that be done in `LyricsPlugin::__init__` ?
check that langdetect can be imported if `bing_client_secret != None`. If `ImportError` occurs, print warning and set `bing_client_secret`to `None`.

**Comment by sampsyo** [comment]
Aha! Late-night coding has gotten me before too. 😇

Doing the check in `__init__` and disabling the option makes sense to me.

**Comment by jackwilsdon** [comment]
> @jackwilsdon, any thoughts on whether scrape_lyrics_from_html is really necessary here? If it is, we at least need to document the new dependency, and we should probably disable the source by default.

I believe it's needed due to to the way LyricsWiki formats their lyrics. I guess we could just use some regular expressions to remove the tags?

Here's what the unescaped lyrics look like (with added indentation):

```html
<div class='lyricbox'>
  I guess I should've known by the way you parked your car sideways<br />
  That it wouldn't last<br />
  See, you're the kinda person that believes in makin' out once<br />
  Love 'em and leave 'em fast<br />
  I guess I must be dumb 'cause you had a pocket full of horses<br />
  Trojan and some of them used<br />
  But it was Saturday night, I guess that makes it all right<br />
  And you say - "What have I got to lose?"<br />
  <br />

  ...

  <br />
  Little red Corvette, oh
  <!--
    <p>
      NewPP limit report
      Preprocessor node count: 857/300000
      Post‐expand include size: 6188/2097152 bytes
      Template argument size: 1451/2097152 bytes
      Expensive parser function count: 1/100
      ExtLoops count: 2/100
    </p>
  -->

  <div class='lyricsbreak'></div>
</div>
```

**Comment by sampsyo** [comment]
If it's just a matter of converting `<br>`s to newlines, removing the comments, and stripping that `<div>`, then perhaps the `BREAK_RE`, `COMMENT_RE`, and `DIV_RE` regular expressions we already have will suffice.

**Comment by jackwilsdon** [comment]
Aha, I didn't know we already had some expressions for those. I'll take a look.

**Comment by jackwilsdon** [comment]
Just opened #1956 with a fix, it seems we can use `_scrape_strip_cruft` instead and it works fine!

**Comment by sampsyo** [comment]
Let's call this good as of #1956.

**Comment by Kraymer** [comment]
reopening, the failing langdetect import is still ongoing

**Comment by jackwilsdon** [comment]
What exactly is the issue, @Kraymer? Does the `langdetect` warning code need moving to the constructor so that it does not print for every song?

**Comment by Kraymer** [comment]
@jackwilsdon  yep that's it #1963
