### ISSUE TITLE
Track / recording artist aliases don't always work

### ISSUE THREAD

**Issue by samdoshi** [beetbox/beets#199]
### Description
Due to a bug on MusicBrainz ([MBS-4021](http://tickets.musicbrainz.org/browse/MBS-4021)) track and recording artist-credit blocks don't always include their list of aliases; this means that the new code for translating artists (#102) won't always work for track artists (release artists do work).

This [code review](http://codereview.musicbrainz.org/r/2156/) for a proposed patch has a good description of the issue, and why it doesn't always manifest itself:

    https://github.com/mwiencek/musicbrainz-server/tree/mbs-4021

    The issue is that aliases are not loaded for recording artists - at all. 
    The only reason the "aliases" inc flag currently works for recordings 
    on single-artist albums is that aliases *are* loaded for album artists, 
    thus cached and displayed for recordings whose artists are equal 
    to the album's.

    The code is written as if recording artist aliases was not an intended
    feature at all. But, it's now expected functionality, and even depended 
    on by Picard to translate artist names.

I think the final bit about Picard is quite interesting (see [PICARD-200](http://tickets.musicbrainz.org/browse/PICARD-200)).

### Examples
Here is a quick example:
* **Martha Argerich: The Collection 3** \[[WWW](http://musicbrainz.org/release/19dba417-1ac6-40f7-8df7-83a04048211b) / [XML](http://musicbrainz.org/ws/2/release/19dba417-1ac6-40f7-8df7-83a04048211b?inc=artists+artist-credits+recordings+aliases)\]. You can see that the XML version does not contain aliases for the track artists (e.g. Сергей Васильевич Рахманинов a.k.a. Rachmaninoff), but the release artist does.
* **Rachmaninoff: "The Nutcracker" Suite / Symphonic Dances** \[[WWW](http://musicbrainz.org/release/70376719-23f7-4fc2-8cf1-4fe4fe95231a) / [XML](http://musicbrainz.org/ws/2/release/70376719-23f7-4fc2-8cf1-4fe4fe95231a?inc=artists+artist-credits+recordings+aliases)\]. The XML for this does contain aliases (and lots of them too!)

### Options
The practical upshot of all of this, is that as things currently stand, translations for release artists **do work** and that for track artists they **might work**. It's also clear that the MusicBrainz developers aren't sure what to do about at the moment (and I can't say that I blame them).

**Potential options are:**

1.  **Do nothing**: We could just see how [MBS-4021](http://tickets.musicbrainz.org/browse/MBS-4021) pans out, especially as the translation features in beets require an unreleased version of [musicbrainzngs](https://github.com/alastair/python-musicbrainz-ngs) so probably won't see a lot of use yet.

1.  **Disable translations for track artists**: At least it's consistent then.

1.  **Make an artist API call**: We could get the artists aliases with a secondary to call to the web service ([example](http://musicbrainz.org/ws/2/artist/44b16e44-da77-4580-b851-0d765904573e?inc=aliases)). It would be best to cache the result for an import session as we would most likely use the alias several times. This has the advantage of working no matter what is decided on the MuscBrainz bug.

**Comment by pprkut** [comment]
With aliases now being present for both recording and track artists in musicbrainz, is there anything left to do here?

**Comment by sampsyo** [comment]
Thanks for the reminder, @pprkut -- this is fixed.
