### ISSUE TITLE
Python 3 status wiki \ blog outdated

### ISSUE THREAD

**Issue by paskal** [beetbox/beets#1998]
There are two pages on beets vs python 3 status:
http://beets.io/blog/py3k.html
https://github.com/beetbox/beets/wiki/Python3

Both of them are not actual, for example, first have information about Flask still have no Python3 support, second what Mutagen still have no Python3 support.

Possible solution is to update current status in second article and do something about first so it won't be searched as most actual information about the status. For example, putting a link to wiki article (which will be updated) will do the thing.

**Comment by sampsyo** [comment]
Thanks for the suggestion! Could you please help out with this yourself? You can open a pull request for the blog post, and you should already have permissions to update the wiki. Your help would be greatly appreciated.

**Comment by jrobeson** [comment]
All deps seem ported except munkres, so i removed them from the wiki page.

**Comment by jrobeson** [comment]
do we really need both the blog and the wikipage? I wonder if it should be replaced by a tasklist or milestone instead

**Comment by jackwilsdon** [comment]
Well I think the blog is more of an informal discussion than a definitive source on this kind of thing, although I could be wrong. I think we'd be alright keeping both as-is and maybe creating an issue with a to-do list?

**Comment by jrobeson** [comment]
the wiki seemed like it was meant to imply the state of things today.  Normally I'd think of blog posts as the state of things on that date,, however the blog post isn't dated.

@sampsyo: how come things under the /blog prefix aren't dated? I'd prefer if they were dated, and that the post didn't change.

**Comment by jrobeson** [comment]
oh, and that we track the current status via a ticket with a tasklist or milestone.

**Comment by sampsyo** [comment]
Yeah, adding a date to the blog post would be good idea in general! I'll make a note to do that.

And yes, an issue with a task list (or multiple issues if they seem appropriate) do seem like the right way to keep track of the current status.

**Comment by jrobeson** [comment]
I reformatted the wiki page, and added a new standard ( related to `map()`).

**Comment by jrobeson** [comment]
I'm currently just adding things to the list as I come across them and they seem uncontroversial.

I still need to talk with @sampsyo to decide about the more controversial ones.

**Comment by paskal** [comment]
https://github.com/beetbox/beets/wiki/Python3 is actual now, and blog posts are now have date published, is there a reason to keep this open?

**Comment by sampsyo** [comment]
Good call; I updated the message on the wiki page.

**Comment by jrobeson** [comment]
what about the trove classification? isn't that something we can do now?

**Comment by sampsyo** [comment]
Oh yeah, good point! I didn't think to do that before 1.4.2. We should do that now.

**Comment by jrobeson** [comment]
so what should we put as the trove classification?  only the 3.x versions or also 3 itself. I don't actually know the common style in this regard.

**Comment by jrobeson** [comment]
I added 3, since we also have 2.   I published a PR here: https://github.com/beetbox/beets/pull/2328

**Comment by sampsyo** [comment]
That seems right; thanks—it's what I've seen other projects do most often.
