### ISSUE TITLE
embedart: Prompt for confirmation in command

### ISSUE THREAD

**Issue by taylorthurlow** [beetbox/beets#1999]
Most commands will prompt for changes when altering files as such:

```
$> beet modify -a album:"penguin prison" year=2011 month=10 day=18
Modifying 1 albums.
Penguin Prison - Penguin Prison
    month: 08 -> 10
    day: 00 -> 18
Really modify, move and write tags (Y/n)?
```

However, the current implementation of `embedart` has no such prompts - nor does it provide any sort of output as to which files/albums it is currently editing (at least usually). A simple confirmation prompt to confirm that the proposed changes are desired would be much more ideal:

```
$> beet embedart -f artwork.jpg album:"penguin prison"
Modifying 1 albums.
Penguin Prison - Penguin Prison
    Existing embedded artwork (300x294)
    Replacement artwork (800x800)
Really write artwork to files (Y/n)?
```

More than once I have fudged up the syntax or accidentally pressed enter when trying to insert a quote. It is a bit too eager to try and write the input artwork to every file in your library!

Thanks for `beets` by the way - it's absolutely invaluable.

**Comment by sampsyo** [comment]
Sounds like a good idea.

**Comment by taylorthurlow** [comment]
Per #2422 this looks like it's solved. Cheers to everyone involved.
