### ISSUE TITLE
Make `edit' plugin offer edit options after keeping both albums in case of album disambiguation

### ISSUE THREAD

**Issue by bartkl** [beetbox/beets#2004]
Once an album is thought to be ambiguous, I am offered to Keep both, Skip new or Remove old.
In case I choose Keep both, I would love to be able to edit some of the tags of the new one using the edit plugin. Is there any possibility this will be implemented?

Thank you!

**Comment by sampsyo** [comment]
This could definitely be a reasonable addition, but can you clarify a little bit about when it's necessary? Does it come up when the match is good, so beets doesn't bother prompting you, but you still want to edit the album? Or is it just that you made a selection *not realizing* it was a duplicate, and then it's too late to go back and edit the album? If it's the latter, maybe a better solution would be make it clear in the first place that you're tagging a duplicate.

**Comment by bartkl** [comment]
I suddenly realise that the situation I've encountered wouldn't be resolved
by this feature request.

The situation that occurred to me was as follows.
Artist - Album/
    01 - ...
    02 - ...
    Album (remastered disk2)
        01 - ...
        02 - ...

On initial import, it first matches "Artist - Album" based on the files it
contains. Then, it matches the same release with the subdirectory, which is
in fact a bonus disc of the reissue. It then offers the usual album
disambiguation prompt, and I thought editing the candidate here would make
sense, but then it would still not be merged with the prior match as a
single album entity in the library, so this won't work.

Thanks for your attention.

**Comment by sampsyo** [comment]
Aha; got it. That specific case has actually come up before, in #112. (There's even an abandoned pull request, #1535.) Does that look like a good description of the problem?

**Comment by bartkl** [comment]
Indeed! And from what I'm reading the `edit' plugin might still come in
handy in the process of (optionally?) applying some final tidying edits
after the merge (if chosen) since this might have undesired consequences as
far as the consistency of tags is concerned.

Way too in-depth for me though, at least for the time being. Good luck with
developing and thanks!

**Comment by sampsyo** [comment]
OK, sounds good! I'll close this issue for now, but your insight about `edit`ing a merged album is good. Maybe you can add your thoughts to that other ticket!
