### ISSUE TITLE
convert: Doesn't convert lossless AIFF on import

### ISSUE THREAD

**Issue by Freso** [beetbox/beets#2005]
The `convert` plugin doesn't register an AIFF file with a pcm_s16be stream as lossless, and thus imports as-is when `never_convert_lossy_files` is set.

`beet -vv import` and `beet config` output: https://gist.github.com/Freso/01e5185503ec40b78e8b43bdcc98c241
Pre-tagged data of the imported files (via `ffprobe`): https://ptpb.pw/APyUNbU6z8_185dEUL7rYMMAyAow

**Comment by Freso** [comment]
Trying to run the `convert` command post-import also makes `convert` not convert them, due to the `never_convert_lossy_files` setting I guess.

**Comment by sampsyo** [comment]
Well, that would do it! There's a hard-coded list of lossless format names, and it doesn't include AIFF: https://github.com/beetbox/beets/blob/0f4b454c206b6487207f2f7218232b3916ae45bd/beetsplug/convert.py#L42

I'll add AIFF to the list. Thanks for pointing this out.

**Comment by Freso** [comment]
Hm. That's a bit of a shortsighted approach though, we should look into doing something more clever. ".aif" can contain lossy formats too, just like ".ogg" can contain FLAC audio. Should I open a new ticket for this?

**Comment by sampsyo** [comment]
Sure! The thing to do, I suppose, would be to add a `lossy` field to MediaFile that more accurately detects lossiness per-format.
