### ISSUE TITLE
Convert deprecated confit method calls 

### ISSUE THREAD

**Issue by jrobeson** [beetbox/beets#2026]
These confit methods are deprecated and should no longer be used.

```py
    def as_filename(self):
        return self.get(Filename())

    def as_choice(self, choices):
        return self.get(Choice(choices))

    def as_number(self):
        return self.get(Number())

    def as_str_seq(self):
        return self.get(StrSeq())
```

Thus 

```py
config['foo'].as_str_seq()
```
becomes
```py
config['foo'].get(StrSeq())
```

**Comment by sampsyo** [comment]
In retrospect, I'm not even 100% sure we need to deprecate those—they did come about as part of the old Confit design, but they can actually be useful as nice, readable shortcuts for common cases. An alternative resolution here would be to un-deprecate those methods and instead document the fact that they are just shortcuts for explicit `get()` calls.

**Comment by jrobeson** [comment]
ok, we can undeprecated them then :)
