### ISSUE TITLE
Replaygaining Opus

### ISSUE THREAD

**Issue by xeverse** [beetbox/beets#2033]
Has opus rg been already implemented?
Cuz I'm not getting it for some reason.

In fact even flacs aren't replaygained on import copy.
Default backend. auto: yes

no opus rg for me with convert: auto
even with backend: gstreamer. hmmmm

Confused.
Possibly related to 
Run ReplayGain analysis after conversion #1718

**Comment by sampsyo** [comment]
As the docs say, the default (command) backend won't work but the RG and bs1770gain backends should. If it's not working for you, can you please include full bug report details?

**Comment by xeverse** [comment]
@sampsyo Many thanks! 
Seems switching to the arcane 
bs1770 backend has resloved my issue. 
Now i can see the RG tags..
