### ISSUE TITLE
Reconcile tag formats on update

### ISSUE THREAD

**Issue by smilerish** [beetbox/beets#2037]
So I've discovered something about my music library that I think beets could help with.

FLAC natively supports Vorbis comments, and I believe that's what beets uses for its metadata.

However, it's also possible (but not officially supported?) to write ID3v2 tags to FLAC files.

I've discovered a significant portion of my library has these superfluous ID3 tags, and some tools do not like them! I've been experimenting with ogg and opus transcodes, and both oggenc and opusenc complain when a FLAC file contains ID3 tags.

There's also the concern that some apps might read the ID3 tags which may not match the Vorbis comments. At the very least, they should contain identical information.

So I'm using `id3v2` to remove these tags (`--delete-all`). But it occurred to me: why hasn't beets done anything with these tags? Does it just ignore the ID3 and update vorbis comments instead?

I wonder if beets should remove these ID3 tags in given circumstances:
- all the time, because they're seemingly non-standard
- all the time if a config option is set to remove them
- part of a command/plugin that cleans any FLAC files with ID3 tags.

I wonder if any other formats have this issue too?
### Setup
- OS: Linux (raspbian) 4.1.19-v7+ #858 SMP armv7l
- Python version: 2.7.9
- beets version: 1.3.17

**Comment by djl** [comment]
👍 

I ran into this a few months back. A handful of FLAC albums had some ID3 tags and my music app read and displayed both sets of tags. It confused the hell out of me until I discovered the problem.

I'd be in favor of a plugin which allows stripping on a per-format basis. Pseudo-config:

    tagstrip:
      # would strip id3 tags from FLAC files
      flac: id3
      # strip everything *except* ID3
      mp3: !id3

Perhaps this could be integrated into the zero plugin?

**Comment by sampsyo** [comment]
Strange! Have either of you given the `scrub` plugin a try? It's perhaps not yet as configurable as what you might need, but it should remove all old tag formats and replace them with beets' default for that format. (For FLAC, that means native FLAC metadata.)

**Comment by djl** [comment]
Ah, right. I completely forgot the scrub plugin even though I do have it enabled. Looks like I started using it after I ran into this problem. If it strips non-native tags then it's good enough for me!
