### ISSUE TITLE
embyupdate: Use Emby API key

### ISSUE THREAD

**Issue by mousey** [beetbox/beets#2045]
Hi All,

In the [Emby Library Update](https://github.com/beetbox/beets/blob/master/beetsplug/embyupdate.py) plugin, rather than have the user save a Username and Password in the beets config file could beets not use an API key instead?

To me this is more practical than storing my credentials with a 3rd party, it means that if anything untoward happened I only need to reset the API Key inside Emby.

An example of this method can be seen in the [Sonarr](https://github.com/Sonarr/Sonarr/blob/7818f0c59b787312f0bcbc5c0eafc3c9dd7e5451/src/NzbDrone.Core/Notifications/MediaBrowser/MediaBrowserProxy.cs) application. Where the API Key is supplied as the Media Browser Token without needing to check a users Username and Password first:

```
private string ProcessRequest(HttpRequest request, MediaBrowserSettings settings)
        {
            request.Headers.Add("X-MediaBrowser-Token", settings.ApiKey);
            var response = _httpClient.Post(request);
            _logger.Trace("Response: {0}", response.Content);
            CheckForError(response);
            return response.Content;
        }
```

**Comment by sampsyo** [comment]
Good idea!

**Comment by mousey** [comment]
#2117 hopefully this will work correctly. User would need to add an apikey value to their config file. If they don't the plugin should still work with the old password method
