### ISSUE TITLE
Audit sorts for python 3 compatbility.

### ISSUE THREAD

**Issue by jrobeson** [beetbox/beets#2051]
Python 3 is quite a bit stricter when sorting objects. 

Here's an example:  in  [TrackInfo](https://github.com/beetbox/beets/blob/master/beets/autotag/hooks.py#L124) `index` is set to `None` and it's sorted by `index` in [show_change()](https://github.com/beetbox/beets/blob/master/beets/ui/commands.py#L283)

This fails in py3, since `None` can't be sorted by anything, even other `None`

**Comment by jrobeson** [comment]
I temporarily fixed that specific one by simply checking for None in the lambda, but I'm not sure if that's how we really want to solve it

**Comment by jrobeson** [comment]
Oh, i should mention that this is the only one that caused problems in the tests so far with these stats

```
FAILED (SKIP=21, errors=6, failures=4)
``

**Comment by sampsyo** [comment]
Hmm... do you know how index becomes none? It seems like it should always be an integer.

**Comment by jrobeson** [comment]
If it's always supposed to be an int, then we're missing a test.

**Comment by sampsyo** [comment]
Probably so. Do you have a way to reproduce the crash? We could make that into a test.

**Comment by jrobeson** [comment]
I haven't actually tested this IRL, this is all in the tests https://paste.fedoraproject.org/379763/46602655/

**Comment by jrobeson** [comment]
specifically using  `pairs.sort(key=lambda i: i[1].index if i[1].index else 0)` makes all those tests pass

**Comment by sampsyo** [comment]
OK, let's nail down what's causing this. It might, for example, be coming from the test harness, in which case that would be the right place to fix it.

**Comment by jrobeson** [comment]
How can we do that? I'm kinda browsing around, but nothing is jumping out at me.

**Comment by jrobeson** [comment]
I'm not yet sure why `show_change` is even being called in a test with a description of 'Test the short letter conflict solving.'

**Comment by jrobeson** [comment]
you fixed one specific issue here. do you trust the rest of the sorts we use?

**Comment by sampsyo** [comment]
Yeah, I think so—we can address others as they come up in testing. Otherwise, I really hope we weren't relying on this behavior (we were relying on it unintentionally in this case).
