### ISSUE TITLE
tox flake8 configuration can't handle python 3.4 or 3.5

### ISSUE THREAD

**Issue by jrobeson** [beetbox/beets#2055]
Attempting to run `tox -e py33-flake8` on py 3.4 results in an unknown interpreter error.
I assume it'll do the same thing on 3.5

CC @jackwilsdon

**Comment by jackwilsdon** [comment]
What do you mean? Do you have Python 3.3 installed when running `tox -e py33-flake8`?

**Comment by jrobeson** [comment]
no. I just had bad assumptions of how it was supposed to work. :(

**Comment by jackwilsdon** [comment]
Sadly Tox only works for Python versions that are already installed on the system. You could try [pyenv](https://github.com/yyuu/pyenv) if you want to install a specific version of Python for testing (but don't want to install it system-wide).

**Comment by jrobeson** [comment]
but can't we add (even though it's kinda ugly) the other python versions?

**Comment by jrobeson** [comment]
like
```diff
diff --git a/tox.ini b/tox.ini
index 22d4aba..939c5cf 100644
--- a/tox.ini
+++ b/tox.ini
@@ -6,9 +6,9 @@
 [tox]
 envlist = py27-test, py27-flake8, docs
 
 # The exhaustive list of environments is:
-# envlist = py{27,33,34,35}-{test,cov}, py{27,33}-flake8, docs
+# envlist = py{27,33,34,35}-{test,cov}, py{27,33,34,35}-flake8, docs
 
 [_test]
 deps =
     beautifulsoup4
@@ -36,14 +36,16 @@ files = beets beetsplug beet test setup.py docs
 passenv =
     NOSE_SHOW_SKIPPED # Undocumented feature of nose-show-skipped.
 deps =
     {test,cov}: {[_test]deps}
-    py{27,33}-flake8: {[_flake8]deps}
+    py{27,33,34,35}-flake8: {[_flake8]deps}
 commands =
     cov: nosetests --with-coverage {posargs}
     test: nosetests {posargs}
     py27-flake8: flake8 --min-version 2.7 {posargs} {[_flake8]files}
     py33-flake8: flake8 --min-version 3.3 {posargs} {[_flake8]files}
+    py34-flake8: flake8 --min-version 3.3 {posargs} {[_flake8]files}
+    py35-flake8: flake8 --min-version 3.3 {posargs} {[_flake8]files}
 
 [testenv:docs]
 basepython = python2.7
 deps = sphinx
```

**Comment by jackwilsdon** [comment]
Ah, I misunderstood the issue. I believe we decided against adding that as there's no differences in `flake8` output between 3.3 and 3.5. Is there a specific reason you need it?

**Comment by jrobeson** [comment]
so i can run it on other python versions without using pyenv :)

**Comment by jrobeson** [comment]
Alternatively, I could just stop using flake8 with tox, and just run it separately, since tox still uses my local flake8 config anyways.

**Comment by jrobeson** [comment]
I think I'll just do that. I keep getting enamored of the idea of keeping this stuff separated and then forgetting that tox doesn't actually virtualize this :(

**Comment by sampsyo** [comment]
OK, sounds like we should close this one.
