### ISSUE TITLE
bpd: Use GStreamer 1.0

### ISSUE THREAD

**Issue by jrobeson** [beetbox/beets#2057]
We're currently using the (very) deprecated gstreamer 0.10 there.

**Comment by sampsyo** [comment]
Yep, this is overdue. I haven't been inspired to work on it, though, because I don't use BPD anymore, and sometimes I feel like the only person who knows how it works. We could also consider deprecating the whole plugin.

**Comment by philippbeckmann** [comment]
I actually ported bpd to GStreamer 1.0 yesterday. I will send you a pullrequest today or tomorrow.

**Comment by jrobeson** [comment]
that'd be wonderful, thanks!

**Comment by jrobeson** [comment]
closing, since the PR was applied
