### ISSUE TITLE
functemplate AST code needs rewritten for python 3

### ISSUE THREAD

**Issue by jrobeson** [beetbox/beets#2058]
The AST code definitely can't work in python3, since the API is different.

**Comment by sampsyo** [comment]
Thanks for the reminder; I'll look into this.

**Comment by jrobeson** [comment]
@sampsyo : Can you look into what it would take to get this done?  I tried my hand at it, but failed.

According to the grammar, it should just be some additional `None`, and `[]` for the kwargs_defaults, and a few other things in `FunctionDef`, but I'm having trouble understanding how `Return` is supposed to work.   I can't seem to find a straightforward example anywhere.  Everybody wants to parse, but few want to create.

**Comment by jrobeson** [comment]
So, i tried again, and this time, succeeded! I finally found some examples via http://nullege.com

**Comment by sampsyo** [comment]
Looks like we're good here!
