### ISSUE TITLE
Album art test failures

### ISSUE THREAD

**Issue by lfam** [beetbox/beets#2064]
### Problem

I am trying to build beets 1.3.18 in [GNU Guix][0]. We have a working package of [1.3.17][1].

The following two tests fail: ```test_respect_enforce_ratio_percent_above```, ```test_respect_enforce_ratio_px_above```

Here is the output of the failing tests:
```
======================================================================
FAIL: test_respect_enforce_ratio_percent_above (test.test_art.ArtForAlbumTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tmp/guix-build-beets-1.3.18.drv-0/beets-1.3.18/test/test_art.py", line 576, in test_respect_enforce_ratio_percent_above
    self._assertImageIsValidArt(self.IMG_500x490, False)
  File "/tmp/guix-build-beets-1.3.18.drv-0/beets-1.3.18/test/test_art.py", line 532, in _assertImageIsValidArt
    self.assertIsNone(candidate)
AssertionError: <beetsplug.fetchart.Candidate object at 0x7fffef6735d0> is not None
-------------------- >> begin captured logging << --------------------
beets.fetchart: DEBUG: fetchart: trying source filesystem for album None - None
beets.test_art: DEBUG: image size: None
beets.test_art: WARNING: Could not get size of image (please see documentation for dependencies). The configuration options `minwidth` and `enforce_ratio` may be violated.
beets.fetchart: DEBUG: fetchart: using local image /tmp/guix-build-beets-1.3.18.drv-0/beets-1.3.18/test/rsrc/abbey-similar.jpg
--------------------- >> end captured logging << ---------------------

======================================================================
FAIL: test_respect_enforce_ratio_px_above (test.test_art.ArtForAlbumTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tmp/guix-build-beets-1.3.18.drv-0/beets-1.3.18/test/test_art.py", line 566, in test_respect_enforce_ratio_px_above
    self._assertImageIsValidArt(self.IMG_500x490, False)
  File "/tmp/guix-build-beets-1.3.18.drv-0/beets-1.3.18/test/test_art.py", line 532, in _assertImageIsValidArt
    self.assertIsNone(candidate)
AssertionError: <beetsplug.fetchart.Candidate object at 0x7fffef4abc50> is not None
-------------------- >> begin captured logging << --------------------
beets.fetchart: DEBUG: fetchart: trying source filesystem for album None - None
beets.test_art: DEBUG: image size: None
beets.test_art: WARNING: Could not get size of image (please see documentation for dependencies). The configuration options `minwidth` and `enforce_ratio` may be violated.
beets.fetchart: DEBUG: fetchart: using local image /tmp/guix-build-beets-1.3.18.drv-0/beets-1.3.18/test/rsrc/abbey-similar.jpg
--------------------- >> end captured logging << ---------------------

----------------------------------------------------------------------
Ran 1669 tests in 142.410s

FAILED (SKIP=30, failures=2)
```

I saved the directory of the failed build, and the file in question, 'abbey-similar.jpg', does exist and does not seem to be corrupted.

### Setup

* OS: Debian Stretch with GNU Guix
* Python version: 2.7.10
* beets version: 1.3.18
* Turning off plugins made problem go away (yes/no): I can try this if you think it's relevant.

A few things to keep in mind about the Guix build environment:
* Building occurs in a chroot that is populated *only* with the dependencies specified in the Beets package definition.
* There is no network access in the chroot.

[0]: http://www.gnu.org/software/guix/
[1]: http://git.savannah.gnu.org/cgit/guix.git/tree/gnu/packages/music.scm#n1474

**Comment by jackwilsdon** [comment]
Hmm, could this be related to this message in your test output?

```
beets.test_art: WARNING: Could not get size of image (please see documentation for dependencies). The configuration options `minwidth` and `enforce_ratio` may be violated.
```

Try installing either ImageMagick or Pillow and seeing if the tests pass then?

**Comment by lfam** [comment]
Reading the full build log, I found some lines like this from earlier in the test suite:
```test_resize_if_necessary (test.test_art.ArtForAlbumTest) ... SKIP: ArtResizer has no local imaging backend available```

**Comment by jackwilsdon** [comment]
Hmm, interesting. I might spin up Guix in a VM in a bit and do some playing around with it. Do the tests pass outside of the chroot?

**Comment by lfam** [comment]
@jackwilsdon I don't know if they would pass outside of the chroot. To be honest, having used Guix for a while now, I don't build anything outside of it if I can help it.

**Comment by lfam** [comment]
The tests pass with python2-pillow in the build environment.

Unless the features that require these tests can be made optional at build time, I think that Pillow should be named as a required dependency in setup.py. What do you think?

If you really don't have ImageMagick or Pillow specified as inputs to your CI process, I think your CI server sounds leaky ;)

**Comment by wordofglass** [comment]
Ok, this is weird. These tests and the underlying functionality are post-1.3.17, but they should be skipped in absence of an imaging backend just the same as those you found in the log. Will have a look at the code.

**Comment by lfam** [comment]
Ah. Feel free to re-open.

**Comment by jackwilsdon** [comment]
Honestly Travis seems to install a lot of things for us that we don't need, e.g. `nosetests`. We might end up having to tell Travis to create a blank image (without Python) and then install Python ourselves 😒.

**Comment by wordofglass** [comment]
This is fixed in master (they're now being skipped as they should in this situation), but that was only in 07c95a1, shortly after the release. As you noted, the tests are fine when run with a backend available, and were never run on your older builds at all.

There are two (three including the resize proxy) backends to choose from, and none will be needed unless any resize option is configured (only in plugins, namely fetchart, embedart, thumbnails or convert). Thus, it is not required dependency.

You may be right about the CI server, I'll have a look at this :)

**Comment by lfam** [comment]
@wordofglass Thanks for the clarification. I'm going to to cherry-pick 07c95a1 for our package.

**Comment by sampsyo** [comment]
Good catch; thanks, everybody. @wordofglass, adding ImageMagick to the Travis configuration seems like a good idea.
