### ISSUE TITLE
round() works differently in py3

### ISSUE THREAD

**Issue by jrobeson** [beetbox/beets#2077]
Quoting http://python3porting.com/differences.html#rounding-behavior

>The behavior of round has changed in Python 3. In Python 2, rounding of halfway cases was away from zero, and round() would always return a float.

```python
>>> round(1.5)
2.0
>>> round(2.5)
3.0
>>> round(10.0/3, 0)
3.0
```

> In Python 3 rounding of halfway cases are now always towards the nearest even. This is standard practice, as it will make a set of evenly distributed roundings average out.

> When called without the second parameter, which determines the number of decimals, round() will in Python 3 return an integer. If you pass in a parameter to set the number of decimals to round to, the returned value will be of the same type as the unrounded value. This is true even if you pass in zero.

```python
>>> round(1.5)
2
>>> round(2.5)
2
>>> round(10.0/3, 0)
3.0
```

We don't use round very often, but we do in some very important cases.

**Comment by jrobeson** [comment]
none of the tests actually fail because of this, but we don't set much there to prove that it works the way we want.

**Comment by jackwilsdon** [comment]
> In Python 3 rounding of halfway cases are now always towards the nearest even. This is standard practice, as it will make a set of evenly distributed roundings average out.

Well that's an odd way of doing it, is there a way to tell `round` in Python 3 to round *up*?

**Comment by jrobeson** [comment]
not with the  round function itself https://docs.python.org/3/library/functions.html#round

**Comment by jrobeson** [comment]
oh, if you click the link (vs just reading the quoted text), it shows an example how how to make it act like the py2 version if that's something that is important to us.

**Comment by jackwilsdon** [comment]
Does `six` provide any backwards compatibility for `round`?

**Comment by sampsyo** [comment]
Intuitively, this doesn't seem like it should be a problem -- most cases, when you use `round`, you just need a reasonable integer and don't care too much about the precise rounding behavior. @jrobeson, what are the places where this comes up, and do any of them intuitively seem like a problem?

**Comment by jrobeson** [comment]
@jackwilsdon : python-future has one that they call newround.  https://github.com/PythonCharmers/python-future/blob/master/src/future/builtins/newround.py

There's an open ticket to add a `six.round`.

**Comment by jrobeson** [comment]
@sampsyo : I have no intuition for the usages in _sc_decode/_sc_encode . I have no idea these values mean in practice and whether these differences are noticable to users or not.

**Comment by sampsyo** [comment]
Cool; I can answer that: it doesn't matter there. That's a true mathematical rounding, where we just need to limit the number of significant digits. The details about whether things go up or down on x.5 don't matter.

And it looks to me like those are the only calls to `round`:

```sh
$ ag --py '\bround\b' beets beetsplug
255:    return round(gain, 2), round(peak, 6)
271:    g1 = min(round((10 ** (gain / -10)) * 1000), 65534)
273:    g2 = min(round((10 ** (gain / -10)) * 2500), 65534)

beets/util/__init__.py
328:    # round-trip through `syspath`.
555:    """Perform a single round of path legalization steps
```

So I think we're good here!
