### ISSUE TITLE
handle reworked IO/OS Error exception hierarchy introduced in py 3.3

### ISSUE THREAD

**Issue by jrobeson** [beetbox/beets#2082]
An overview of the changes here: https://www.python.org/dev/peps/pep-3151/

This only breaks one test, but other usages should probably be looked over.

**Comment by jrobeson** [comment]
Specifically it breaks  the `test_broken_symlink` here https://github.com/beetbox/beets/blob/master/test/test_mediafile_edge.py#L191

This type check is the problem https://github.com/beetbox/beets/blob/master/beets/mediafile.py#L1366

```python
except IOError as exc:
            if type(exc) == IOError:
                # This is a base IOError, not a subclass from Mutagen or anywhere else.
```
in python > 3.3 it's `FileNotFoundError`

If the comment didn't say `anywhere else` I'd just change it to an `isinstance`, but it does :)

**Comment by sampsyo** [comment]
Aha; thanks. Yes, that's certainly a problem—but it looks like, after a cursory perusal, Mutagen may no longer subclass IOError. It looks like all of Mutagen's special exceptions now subclass `MutagenError`, which is quite sensible. We can probably refactor this handling with that in mind.

**Comment by jrobeson** [comment]
so does that mean we can just switch out the type to isinstance?

**Comment by jrobeson** [comment]
oh, we can probably do a little better i suppose

**Comment by sampsyo** [comment]
Yeah—I think we can just stick with a plain `except IOError`.

**Comment by lazka** [comment]
fyi, the next mutagen release will no longer raise IOError, only subclasses of MutagenError.

**Comment by jrobeson** [comment]
@lazka: so what do you recommend we do here https://github.com/beetbox/beets/blob/master/beets/mediafile.py#L1366  to stay compatible with existing and future mutagen versions?

**Comment by lazka** [comment]
I'll work on a PR with some proposals.

**Comment by lazka** [comment]
See https://github.com/beetbox/beets/pull/2088 and https://github.com/beetbox/beets/pull/2087

**Comment by sampsyo** [comment]
The MediaFile case is done thanks to @lazka's help. A quick grep suggests that we don't do anything else squirrelly that depends on the IOError/OSError exception hierarchy. In a few places, we catch both, but that's harmlessly redundant on Python 3. So I'll close this issue now.
