### ISSUE TITLE
beatport: Missing track numbers

### ISSUE THREAD

**Issue by stp242** [beetbox/beets#2085]
Hi,

would it be possible to add this feature? I am not sure if beatport API offers this, but if not there must be a way around it, like assign track numbers in the order they are received?

**Comment by sampsyo** [comment]
Huh! It definitely should set track numbers. Can you elaborate a little bit—that is, show an example (with real output) where the number is missing?

**Comment by stp242** [comment]
```
/media/beets/animato - tuvan (2016) (1 items)
Finding tags for album "Animato - Tuvan".
Candidates:
1. Animato - Tuvan (49.9%) (id, tracks, media, ...) (Beatport, Digital, 2016, HOMmega Productions)
2. Gaia - Tuvan (34.1%) (id, artist, missing tracks, ...) (12" Vinyl, 2009, NL, Armind)
3. Steve Hart - Decade Of Dance - Stevie Hart (20.3%) (id, artist, album, ...) (CD, 2012, AU)
4. Z‐Trip - Party For Change (16.3%) (id, artist, album, ...) (Digital Media, 2008, XW)
5. Z‐Trip - Victory Lap: The Obama Mix Pt. 2 (13.4%) (id, artist, album, ...) (Digital Media, 2009, XW)
6. Carl-Orff-Chor, Schwäbisch Metall & Animato - OC 828: Vom Himmel hoch, o Englein kommt (5.5%) (missing tracks, id, album, ...) (CD, DE)
# selection (default 1), Skip, Use as-is, as Tracks, Group albums,
Enter search, enter Id, aBort, eDit, edit Candidates? 1
Tagging:
    Animato - Tuvan
URL:
    http://beatport.com/release/tuvan/1774438
(Similarity: 49.9%) (id, tracks, media, source, year) (Beatport, Digital, 2016, HOMmega Productions)
 * Tuvan (#1) -> Tuvan (original mix) (#None) (id, source, title)
Apply, More candidates, Skip, Use as-is, as Tracks, Group albums,
Enter search, enter Id, aBort, eDit, edit Candidates?
```
also tested with 2 other albums and same result

**Comment by MolarAmbiguity** [comment]
@stp242, what does your config look like?

**Comment by stp242** [comment]
@MolarAmbiguity pretty standard, only change was adding beatport plugin:
https://gist.github.com/stp242/73fc1b27a7d9bfaa0c9737a3d3b3bc72

**Comment by sampsyo** [comment]
Thanks! That does indeed look like a problem -- @jbaiter, any chance there's a change with the new API w.r.t. track numbers?

**Comment by jbaiter** [comment]
Hmm.... The code actually just calls `enumerate` on the tracklist to determine the order, i.e. the order that the API returns the tracks in is regarded as canonical. Testing with some of my releases I could not reproduce the problem.

However, I just had a look through the returned data from the API and it turns out that there is actually a `trackNumber` field. I opened a PR to use that instead of `enumerate`, maybe it helps?
https://github.com/beetbox/beets/pull/2091

**Comment by sampsyo** [comment]
Huh! Well, I'm not sure why @stp242 was running into this, then, but that change looks good to me in any case.

**Comment by stp242** [comment]
still the same issue with @jbaiter's PR 😢 

I am not sure why this happens. I tried to throw a bunch of print() in there and it does say the track number is 1, but later when it gets passed along it's back to "None" again

you can try with any single audio file you have and manually entering this id:
http://beatport.com/release/tuvan/1774438

**Comment by sampsyo** [comment]
Oddly, I can't reproduce this—I took an arbitrary track, entered this ID, and got a proper track number (`#1`):

```
Correcting tags from:
    Aesop Rock - None Shall Pass
To:
    Animato - Tuvan
URL:
    http://beatport.com/release/tuvan/1774438
(Similarity: 11.5%) (id, album, artist, tracks, media, source, year, catalognum, label) (Beatport, Digital, 2016, HOMmega Productions)
 * None Shall Pass (#2) (4:03) -> Tuvan (original mix) (#1) (8:09) (id, title, length, source, index)
Apply, More candidates, Skip, Use as-is, as Tracks, Group albums,
Enter search, enter Id, aBort, eDit, edit Candidates? 
```

(The Aesop Rock track was the arbitrary file I used.)

So I'm stumped. Maybe you could try pruning down your config to see if some other plugin or option is interfering somehow?

**Comment by stp242** [comment]
ah! after an hour of debugging I finally found the culprit. turns out when you have "per_disc_numbering" enabled, this breaks the track numbering with beatport plugin.

thanks for the suggestion btw sampsyo. I would never have thought that setting was responsible

(this worked with beets installed from pip, so I think that PR is not needed now)

**Comment by sampsyo** [comment]
Got it! Thanks for investigating. I'll see if this might be a bug in the `per_disc_numbering` business.

**Comment by sampsyo** [comment]
OK, I found and fixed the bug! There were actually two—one in the display of the track number, and one when we applied it to the file.

For technical background, the problem is that the Beatport background doesn't currently set the `medium_index` number, i.e., the track number within the current disc on a multi-disc album. That exposed a couple of latent bugs.

**Comment by stp242** [comment]
great, thank you so much! works perfectly now 😄
