### ISSUE TITLE
lastgenre: add option to manually set genre per album/artist etc.

### ISSUE THREAD

**Issue by marlemion** [beetbox/beets#2099]
I have quite a lot of artists, which aren't matched by lastgenre and thus are transferred to a certain folder specified in the configuration. It would be neat to have an option to manually assign genres to these artists or maybe albums. These assignments could be stored in a certain file and could be read be lastgenre if a certain option is set. In this way, lastgenre would find a genre for a specific artist/album even if there is no genre provided by last.fm. If only the artist is specified (no album) it would even do so for different albums of this artist.

As I am no programmer, I can only post this idea here. Maybe this can be implemented easily. Anyway, thanks a lot for beets. I love it very much.

**Comment by sampsyo** [comment]
Hey! This is an interesting idea. Have you considered using `beet modify genre=...` to manually set genres?

**Comment by marlemion** [comment]
Thanks for the hint. I will do it the way you suggested for the time being. The other way would be very convenient, though. And I am a lazy guy. ;)

**Comment by marlemion** [comment]
Btw. I did the modify command, but the files are not moved from 'Unknown' to the respective genre folder. Also a subsequent beet update or beet move did not do the trick...

**Comment by sampsyo** [comment]
You might want to try using the `-a` flag to the `modify` command if you're changing genres for entire albums.
