### ISSUE TITLE
don't install pathlib when python >= 3.4

### ISSUE THREAD

**Issue by jrobeson** [beetbox/beets#2105]
This isn't important yet, but i wanted to have it noted. I didn't do it myself, because I didn't know the best way to adapt the tox configuration.

**Comment by sampsyo** [comment]
FWIW, recent `pip`s let you explicitly specify Python version ranges for dependencies: https://pip.pypa.io/en/stable/reference/pip_install/#requirement-specifiers

**Comment by jrobeson** [comment]
what version of pip is is in the oldest distro we wanna support? or is pip 6 really old?

**Comment by jrobeson** [comment]
so what about the pathlib in tox.ini ?

**Comment by sampsyo** [comment]
I don't know when this appeared—that's a worthy topic for a bit more research.

**Comment by jackwilsdon** [comment]
Looks like `pathlib` was added by @brunal in 39183cd5, mirroring the `setup.py` [here](https://github.com/beetbox/beets/blob/39183cd5398318b0947bc5619e0b03daca04dadb/setup.py#L98).

You might be able to do this with the `tox.ini`:

```INI
[testenv]
passenv =
    NOSE_SHOW_SKIPPED # Undocumented feature of nose-show-skipped.
deps =
    {test,cov}: {[_test]deps}
    py27: pathlib # Install pathlib on 2.7.
    py{27,34}-flake8: {[_flake8]deps}
commands =
    cov: nosetests --with-coverage {posargs}
    test: nosetests {posargs}
    py27-flake8: flake8 --min-version 2.7 {posargs} {[_flake8]files}
    py34-flake8: flake8 --min-version 3.4 {posargs} {[_flake8]files}
```

**Comment by jrobeson** [comment]
as far as I can tell, they are only supported on the cli and in requirements files, not in setup.py

**Comment by jrobeson** [comment]
oops replied to the wrong ticket, ignore that

**Comment by jrobeson** [comment]
that was the right ticket, not wrong ! :(
