### ISSUE TITLE
How can we pass -bb to python (3.x) executable via tox?

### ISSUE THREAD

**Issue by jrobeson** [beetbox/beets#2106]
Quoting the `--help` here:
```sh
-b     : issue warnings about str(bytes_instance), str(bytearray_instance)
         and comparing bytes/bytearray with str. (-bb: issue errors)
```

Sadly there seems to be no other way that I've found to control it via env var or programatically on python 3.4.

cc @jackwilsdon

**Comment by sampsyo** [comment]
I think this should be possible by replacing the `nosetests` command invocation in `tox.ini` with `python -bb -m nose`. That is, invoking `python -m nose` is the same as just `nosetests` and lets us add Python interpreter flags.

**Comment by jackwilsdon** [comment]
Good point @sampsyo. We should be able to do this, so we don't add `-bb` for anything other than `3.x`:

```
commands =
    cov: nosetests --with-coverage {posargs}
    py{34,35}-cov: python -bb -m nose --with-coverage {posargs}
    test: nosetests {posargs}
    py{34,35}-test: python -bb -m nose {posargs}
```

I've not tested this yet but I don't see why it wouldn't work.

**Comment by jrobeson** [comment]
how could it?  python isn't python 3?

**Comment by jrobeson** [comment]
is python an alias ? to whatever basepython resolves to?

**Comment by sampsyo** [comment]
In tox, I think `python` refers to whichever Python is installed in the virtualenv.

**Comment by jrobeson** [comment]
ah, neat. I can give it a try myself then unless somone gets to it first

**Comment by jrobeson** [comment]
we need to do the same for mediafile and confuse

**Comment by jrobeson** [comment]
i tried what @jackwilsdon suggested and it made the tests run twice. I assume because it ran `test` and then `py{34,35}-test`

**Comment by jackwilsdon** [comment]
Ah, you'll probably need this then:

```INI
commands =
    py27-cov: nosetests --with-coverage {posargs}
    py27-test: nosetests {posargs}
    py{34,35}-cov: python -bb -m nose --with-coverage {posargs}
    py{34,35}-test: python -bb -m nose {posargs}
```

It's not the prettiest but it will have to do 😕.

**Comment by jrobeson** [comment]
fixed in https://github.com/beetbox/beets/commit/e434074bf078e8bde63ad640831172c62e63d546

Thanks @jackwilsdon!
