### ISSUE TITLE
don't allow tox -e py34-flake8 to fail

### ISSUE THREAD

**Issue by jrobeson** [beetbox/beets#2113]
I have no idea how to reasonably accomplish this due to the way our current `allow_failures` is set up. I do think it's important that we figure out some way, so we can make sure we don't accidentally reintroduce `unicode()` or other 2.x only bits

**Comment by jrobeson** [comment]
we should probably retire `py27-flake8` altogether at this point.

**Comment by jrobeson** [comment]
@jackwilsdon : any suggestions on how best to organize our config to make this possible?

**Comment by jackwilsdon** [comment]
Well `allow_failures` allows you to define any of the values defined in the matrix, so we should be able to do this:

```diff
@@ -25,6 +25,7 @@
           env: {TOX_ENV: docs}
     allow_failures:
         - python: 3.4
+          env: {TOX_ENV: py34-test}
         - python: 3.5
```

Which will only allow `py34-test` to fail and shouldn't allow `py34-flake8` to fail.

If that doesn't work we might be better removing the `python: 3.4` line (although I'd prefer to keep it for completeness's sake).

**Comment by jrobeson** [comment]
thanks again @jackwilsdon! you're my testing hero!  Looks good: https://travis-ci.org/beetbox/beets/builds/145296406  . Fixed in https://github.com/beetbox/beets/commit/1ee7a3e2f12b7c80e0c0be609ed29ec13fda6e1b
