### ISSUE TITLE
symlinks are supported, but hard to use on windows with python >= 3.2

### ISSUE THREAD

**Issue by jrobeson** [beetbox/beets#2114]
This causes various tests to fail.

https://docs.python.org/3/library/os.html#os.symlink

> Symbolic link support was introduced in Windows 6.0 (Vista). symlink() will raise a NotImplementedError on Windows versions earlier than 6.0.

>Note

> On Windows, the SeCreateSymbolicLinkPrivilege is required in order to successfully create symlinks. This privilege is not typically granted to regular users but is available to accounts which can escalate privileges to the administrator level. Either obtaining the privilege or running your application as an administrator are ways to successfully create symlinks.

> OSError is raised when the function is called by an unprivileged user.

I'm not sure what we wanna do about this, since links are possible, but difficult to use.

We currently just check if os has the symlink attribute, but that won't do.

**Comment by sampsyo** [comment]
Got it; thanks for investigating. It looks like the right thing to do is to leave the check in (for Python version compatibility) and just catch the OSError on that call (and log a reasonable error). The tests for symlink capability can probably just be disabled on Windows.

**Comment by jrobeson** [comment]
@sampsyo : we don't have any platform checks for outside of the tests. This is the current code of `util.link`

```python
    try:
        os.symlink(path, dest)
    except OSError:
        raise FilesystemError(u'Operating system does not support symbolic '
                              u'links.', 'link', (path, dest),
                              traceback.format_exc())
```

There are other cases where a symlink would fail though aren't there? I'm considering something like this:

```python
    try:
        os.symlink(path, dest)
    except OSError:
        msg = 'what do we wanna say?'
        if hasattr('sys', 'getwindowsversion'):
            if sys.getwindowsversion()[0] < 6:  # is XP or lower
                msg = u'Operating system does not support symbolic links.'
        raise FilesystemError(msg, 'link', (path, dest),
                              traceback.format_exc())
```

The actual message on windows 10 is this: `OSError: symbolic link privilege not held`

**Comment by jrobeson** [comment]
I forgot the case where the OS supports symlinks, but the filesystem doesn't like fat32/vfat

**Comment by tschoening** [comment]
While this is old, I would just like to mention that there is something called [Junctions](https://msdn.microsoft.com/de-de/library/windows/desktop/aa365006(v=vs.85).aspx) available in Windows, which in theory are even available in very old versions of Windows, are available to all users without any special permissions and at least for directories can be a valid replacement for symlinks in 99% of the cases. So in theory at least for directories one could use those as a fallback.
