### ISSUE TITLE
Python Version Changes

### ISSUE THREAD

**Issue by jackwilsdon** [beetbox/beets#2119]
So I understand we're moving to Python 3; does this mean we're going to stop supporting 2.x altogether when we do? Or are we going to find some middle ground between them?

I understand the reason to move just to 3, as it means less compatibility code and much tidier code in general. I'd just like to clarify our intentions, as [wiki/Python3](https://github.com/beetbox/beets/wiki/Python3) isn't very clear at the moment.

CC @sampsyo and @jrobeson.

**Comment by jrobeson** [comment]
The only thing I'm 100% sure of is that the initial release will support both 2.7 and 3.4. I'm not sure when we drop 2.7 completely

**Comment by jrobeson** [comment]
If you take a look here: https://github.com/beetbox/beets/pull/2101 you'll see how little is left to have all the tests pass on linux on 3.5. Obviously those changes won't be merged as is, but you can see that there's not a lot left.

The windows changes however, I'm still trying to work that out. I could use some help on that.

**Comment by sampsyo** [comment]
Thanks for asking, @jackwilsdon. I don't think we've written this down anywhere, and it would be great to discuss it more.

Here's the plan: @jrobeson is busily porting us to a hybrid Python 2/3 state. The idea is to get to a point where Python 2 users aren't disrupted—modulo unintentional bugs we will inevitably introduce during the transition—but Python 3 users can start testing too, when the port is complete.

The current status is that the `beet` program starts up and can do a few basic things, but there's a long tail of small changes to bring the whole thing up to speed. In the mean time, @jrobeson has a pull request (#2101) with a series of hacks that make all the tests pass on Python 3. The idea is to iteratively drain changes from that series onto `master` while converting them to non-hacky, 2/3 hybrid changes.

When that's done, we can announce to the world that we're ready for people to start testing Python 3 support. (In the immediate future, I plan to release 1.4.0, but that's just to indicate that we now depend on `six`—not that Python 3 support is ready for widespread testing.) I expect that this testing will reveal more bugs on 3, and we'll wait for that to settle down. Staying in the 2/3 hybrid state for some time will help ensure that beets still works for most people while we nail down the Python 3 details.

After that, we have a choice to make: when will we drop Python 2 support? I'd like to take a moment then to get input from the community about what kind of timetable they'd like to see.

**Comment by jrobeson** [comment]
@sampsyo: btw at this point i'm blocked from proceeding any further

**Comment by sampsyo** [comment]
What's currently blocking? Happy to help find the next step.

**Comment by jrobeson** [comment]
what you see in the PR (which has massively shrunk).

**Comment by jrobeson** [comment]
@sampsyo : do you know who else works on windows?

**Comment by sampsyo** [comment]
Not specifically—I think I've been the only person pushing on it lately.

And yes, unfortunately, command-line arguments on Windows are "wide characters" (i.e., Unicode).

**Comment by jrobeson** [comment]
@jackwilsdon : are your questions answered sufficiently?

**Comment by jrobeson** [comment]
@sampsyo: so any comments on the PR stuff then? ;)

**Comment by sampsyo** [comment]
Hey, @jrobeson—I've left a slew of comments on the PR. In most cases, it looks like we just need to dig a little deeper and have a short conversation to find the right solution.

**Comment by jrobeson** [comment]
@jackwilsdon : need any more info?

**Comment by jackwilsdon** [comment]
No thanks, it seems you and @sampsyo have answered all of my questions. Thanks! 😄
