### ISSUE TITLE
-bb python arg for tests breaks additional arg usage in calls to ui._raw_main()

### ISSUE THREAD

**Issue by jrobeson** [beetbox/beets#2123]
### Problem

When running tests with args beyond `-m nose` such as the `-x`, ``-v`, `-s`  like so:

`tox -e py35-test -- -xsv` 

it ends up passing those args along in `sys.argv` thus breaking like this:

```sh
test_show_redacted_user_config (test.test_config_command.ConfigCommandTest) ... Usage: python -m nose config [options]

python -m nose config: error: no such option: -x

ERROR

======================================================================
ERROR: test_show_redacted_user_config (test.test_config_command.ConfigCommandTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/johnny/src/beets/test/test_config_command.py", line 70, in test_show_redacted_user_config
    self.run_command('config')
  File "/home/johnny/src/beets/test/helper.py", line 429, in run_command
    beets.ui._raw_main(list(args), lib)
  File "/home/johnny/src/beets/beets/ui/__init__.py", line 1274, in _raw_main
    subcommand, suboptions, subargs = parser.parse_subcommand(subargs)
  File "/home/johnny/src/beets/beets/ui/__init__.py", line 1068, in parse_subcommand
    suboptions, subargs = subcommand.parse_args(args)
  File "/home/johnny/src/beets/beets/ui/__init__.py", line 932, in parse_args
    return self.parser.parse_args(_convert_args(args))
  File "/usr/lib64/python3.5/optparse.py", line 1388, in parse_args
    self.error(str(err))
  File "/usr/lib64/python3.5/optparse.py", line 1568, in error
    self.exit(2, "%s: error: %s\n" % (self.get_prog_name(), msg))
  File "/usr/lib64/python3.5/optparse.py", line 1558, in exit
    sys.exit(status)
SystemExit: 2

```

A naive fix was to simply set `sys.argv = ['beet']` in `run_command` (in `helper.py`), but there are probably other implications that I'm not thinking of. The current tests do pass though.

EDIT: this is very likely not a 3.x specific issue, so no need for the python 3 tag.

**Comment by sampsyo** [comment]
Weird! I ave this a try here and this works fine on my system, for some reason—both on `py35-test` and `py27-test`. Maybe this has to do with versions of tox?

```
$ tox --version
2.3.1 imported from /usr/local/lib/python2.7/site-packages/tox/__init__.pyc
```

**Comment by jrobeson** [comment]
```sh
$ tox --version
2.3.1 imported from /home/johnny/.local/share/pyenv/versions/3.4.5/lib/python3.4/site-packages/tox/__init__.py
```

**Comment by sampsyo** [comment]
Bizarre. Do you get the same error when running `python -m nose` directly with arguments, not via tox?

**Comment by jrobeson** [comment]
I'd have to create a whole new user account to test that, the currenttest suite breaks totally for me when run outside of tox. It looks like it partly takes into account `$XDG_CONFIG_HOME` so it ends up writing say beets.db into `~/.config/beets`, but then can't read it.  I think this is indicative of some other missing isolation we have in there.

**Comment by jrobeson** [comment]
but in any case, don't we really want to make sure argv is clear in this case?

**Comment by sampsyo** [comment]
Definitely! I'm just interested in why it's not being isolated on your system. I don't see an obvious root cause yet.
