### ISSUE TITLE
prune_dirs breaks on Windows due to byte and string comparison with python -bb

### ISSUE THREAD

**Issue by jrobeson** [beetbox/beets#2124]
because `syspath` is used here https://github.com/beetbox/beets/blob/master/beets/util/__init__.py#L265 we end up with fnmatch comparing bytes (our clutter) and strings (the filename), so it fails.

**Comment by jrobeson** [comment]
@sampsyo : any comments on this?  This breaks the most windows tests.

**Comment by sampsyo** [comment]
Good question. It seems like the right thing might be to pass the `listdir` results through `bytestring_path`?

**Comment by jrobeson** [comment]
the results and not the args to listdir itself?? that's where i get confused about where to use syspath

**Comment by sampsyo** [comment]
Yeah. Here are a couple of rules:

- The *arguments* to OS calls must by syspath-ified. In other words, `syspath` converts from the beets representation of paths to the OS representation.
- The *results* of OS calls that return paths should likely be bytestring-ified. Analogously, `bytestring_path` converts from OS path values to beets path values.

Of course, on non-Windows OSes, both of these should be no-ops in this case.

**Comment by jrobeson** [comment]
yeah i know what they do, but OS calls is vague.. fnmatch doesn't count, but listdir does?

**Comment by sampsyo** [comment]
I believe `fnmatch` is a pure string operation, right? It doesn't actually touch the file system.

**Comment by jrobeson** [comment]
oh, you're right! that explains that. so I guess i'll just add a list comp there.

**Comment by sampsyo** [comment]
Perfect! :sparkles:
