### ISSUE TITLE
test_nonexistent_file (test_library.FilesizeTest) fails

### ISSUE THREAD

**Issue by JesseWeinstein** [beetbox/beets#2135]
### Problem
test_nonexistent_file (test_library.FilesizeTest) fails when run via `python setup.py test`, but not when run via `tox -e py27-test`.

```
    self.assertEqual(item.filesize, 0)
AssertionError: 987 != 0
```

### Setup

* OS: Debian Jessie
* Python version: 2.7.9
* beets version: master (e7428972ca88e688dcef579f4a3d363a9ba8bca1)

**Comment by JesseWeinstein** [comment]
I suspect this is a misconfiguration on my part, but I'm not sure what yet.

**Comment by JesseWeinstein** [comment]
Explicitly doing a `pip install` of the packages listed in `tests_require` (rather than allowing setup.py to simply download them to the current directory) made the problem go away.

I'm not sure whether this counts as a solution or not. Feel free to close if you think it does.

**Comment by sampsyo** [comment]
Wow; that's bizarre! Any chance you can narrow down which dependency made the difference?

**Comment by JesseWeinstein** [comment]
Sure; I'll see about doing that.

**Comment by JesseWeinstein** [comment]
Now I messed with it more, and the problem is back, even though all the test deps are installed normally... weird weird weird... :-( 

I'll keep poking at it.

**Comment by JesseWeinstein** [comment]
OK, I've nailed it down (I hope) to `test_ui.py`. If I run the tests along with that, it fails -- without it, it doesn't fail.

**Comment by JesseWeinstein** [comment]
OK, I get the error with only: 
```
_common.py  helper.py  __init__.py  testall.py	test_library.py  test_ui.py
```
in the test directory. And removing `test_ui.py` makes it go away.

**Comment by JesseWeinstein** [comment]
Found the CULPRIT. https://github.com/beetbox/beets/blob/bb15829b17a57bf8be2f8cb68db765eff9185d34/test/test_ui.py#L1076
```
 fsize_mock = patch('beets.library.Item.try_filesize').start()
```
It is never explicitly unmocked. Apparently `setup.py test` doesn't clean up as throughly as `nosetest` does.
