### ISSUE TITLE
update google code url references to their new locations

### ISSUE THREAD

**Issue by jrobeson** [beetbox/beets#2145]
I did most of them in 01483f9600918b094f6c2424c3d5090c5d592719. I couldn't find a new location for beetfs by the same person, and I didn't know how to map some of the beets issues. You can see them here: https://github.com/beetbox/beets/search?utf8=%E2%9C%93&q=%22code.google.com%22&type=Code

**Comment by sampsyo** [comment]
Thanks! I changed the last few links.
