### ISSUE TITLE
drop python 3.4 on appveyor?

### ISSUE THREAD

**Issue by jrobeson** [beetbox/beets#2157]
Is there any reason for us to use 3.4 on Windows?  Our builds are really slow, so if we can assume 3.5, that'd speed things up quite a bit.

**Comment by sampsyo** [comment]
Let's either drop it on both Linux and Windows or keep it on both places. (This makes our requirements easier to describe.) I don't generally have a strong reason to keep 3.4, except that I seem to recall Debian Jessie only has 3.4?

**Comment by jrobeson** [comment]
yep, jessie only has 3.4.   I think that's the case for trusty too. I'm not sure if we care about trusty itself or not though.  I'll close it in any case.
