### ISSUE TITLE
Python 3 alpha/beta status criteria?

### ISSUE THREAD

**Issue by jrobeson** [beetbox/beets#2164]
What's our criteria?  

With the tests passing on Linux, and almost entirely passing on Windows, I wanna know what we do next :)

I'm personally not sure, except for #2058. That's not really a showstopper though.

**Comment by jrobeson** [comment]
I'm finally asking this now, because everything on my local todo list is finally done today (except getting some version of #2151 merged)

**Comment by sampsyo** [comment]
Woohoo!

Roughly, I usually think of these definitions:

* Alpha: Still very much in development (i.e., right now).
* Beta: Nothing obvious we know of that's outstanding, but there are still plenty of bugs we don't know about (i.e., the status I imagine for 1.4.0).
* Final: We're pretty confident it's safe for normal people to use.

**Comment by jrobeson** [comment]
So what do you see as left in alpha beyond #2151?

**Comment by sampsyo** [comment]
Nothing that I can see—it seems ready after that! How about you; any lingering concerns?

**Comment by jrobeson** [comment]
Can you look into #2158 ?  It'd be cool to have that fixed for 1.4.0.

**Comment by arcresu** [comment]
Is there anything left to do here? It looks like this can probably be closed now.

**Comment by sampsyo** [comment]
Indeed—using Python 3 has been our recommendation for a while, despite [a couple of lingering Python 3 bugs](https://github.com/beetbox/beets/issues?utf8=✓&q=is%3Aopen+label%3A%22python+3%22+label%3Abug), the most significant of which is #2607 (which is unfortunately also the hardest to fix). I could imagine dropping Python 2 support at any time, assuming we announce the transition ahead of time.
