### ISSUE TITLE
"no such file or directory" while importing folders with foreign language characters - Windows 7

### ISSUE THREAD

**Issue by ghost** [beetbox/beets#2178]
### Problem

Importing folders with foreign language characters fails.

``` sh
$ beet -vv import "t大"
```

Led to this problem:

```
user configuration: C:\Users\User\AppData\Roaming\beets\config.yaml
data directory: C:\Users\User\AppData\Roaming\beets
plugin paths:
Sending event: pluginload
library database: x:\test_library.blb
library directory: x:\beets_test
Sending event: library_opened
error: no such file or directory: t?
```

SIMILAR result for:

``` sh
$ beet -vv import "ś"
```

```
user configuration: C:\Users\User\AppData\Roaming\beets\config.yaml
data directory: C:\Users\User\AppData\Roaming\beets
plugin paths:
Sending event: pluginload
library database: x:\test_library.blb
library directory: x:\beets_test
Sending event: library_opened
error: no such file or directory: s
```
### Notes

The try to restore was:
- setting console code page from default (437) with "chcp 65001".
- setting 'terminal_encoding: utf_8'.
- setting 'terminal_encoding: utf_8' and changing code page with "chcp 65001".
- changing python version from x64 to x86.
- applying "win_unicode_console" module like so:

```
import win_unicode_console
win_unicode_console.enable()
```

inside C:\Users\User\AppData\Roaming\Python\Python27\site-packages\usercustomize.py
The attemmpt to run beets 1.4.0 from today on top of Python 3.5.2 was having the same results.
The attemmpt to run beets 1.3.18(19) on top of Python 2.7.12 / Windows 10 Home Edition x64 pl_PL was having the same results with minor differences
### Setup
- OS: Windows 7 x64 Ultimate en_US, Windows 10 Home Edition x64 pl_PL
- Python version: 2.7.12
- beets version: 1.3.18 (Note: it's the output of "beet --version". However while "pip install beets" console shows that pip downloads 1.3.19. This inequality even after uninstalling python, removing its "c:\Python27" all together, and doing fresh install of Python and beets.
- Turning off plugins made problem go away (yes/no):  non using any plugins

My configuration (output of `beet config`) is:

``` yaml
directory: "x:\\beets_test"
library: "x:\\test_library.blb"

import:
        copy: yes
        move: no
        write: no
        autotag: no
```

**Comment by sampsyo** [comment]
Interesting; thanks! Look like we need someone with a Windows machine to dig and see exactly what the discrepancy between the CLI args and the filename strings is.

In the mean time, you might try importing a parent directory with an ASCII name. Recursively finding the subdirectory shouldn't be impacted.

**Comment by arcresu** [comment]
The original submitter's GitHub account has been deleted. If anyone runs into the issue again they can open a new report but it's going to be difficult to pin this down without help from someone who can reproduce the issue.

**Comment by jackwilsdon** [comment]
I think this is similar (if not the same as) #3228 anyway.
