### ISSUE TITLE
Different releases with same name conflict despite %aunique

### ISSUE THREAD

**Issue by azrdev** [beetbox/beets#2185]
### Problem

I have [this release][1] in my DB, and try to import [this one][2] - both have the same artist & name, but the first is an album and the second an EP. I expect beets to distinguish them, but instead on import it only asks me about "skip new / keep both / remove old".

My config contains a unique album path identifier, so this is not the problem:
~~~
paths:
    singleton: $albumartist/$album%aunique{}/$track $title
    comp: $albumartist/$album%aunique{}/$track $title
~~~

### Setup

* OS: Fedora 23
* Python version: 2.7.11
* beets version: git HEAD / v1.3.19-280-g27f48ef

[1]: <https://musicbrainz.org/release/f71cce3e-215d-4127-b10b-8ae919d42097>
[2]: <https://musicbrainz.org/release/17432213-49df-4389-a05a-e2f91178792f>

**Comment by sampsyo** [comment]
That's the current intended behavior---just choose "keep both" and the paths will sort themselves out.
