### ISSUE TITLE
Discogs missing field "albumartist_sort"

### ISSUE THREAD

**Issue by rain0r** [beetbox/beets#2186]
Discogs does not offer the field "albumartist_sort". How should this be handled? I think the current solution is not satisfying.

Current status:

beets will create a directory named "_" for the "field albumartist_sort".

My path:
`    default: $albumartist_sort/$album/$track-$albumartist - $title`

Importing the album "My Woman" from artist "Angel Olsen" leads to:

`music/_/My Woman/01-Angel Olsen - Intern.mp3'`

I think this is not satisfying because I was looking for the album in my file browser and was wondering where it may be. In my opinion, there should be at least a warning à la 

> we couldn't find out the albumartist_sort-value so we will create a fallback directory called '_'

**Comment by sampsyo** [comment]
You can use %if to get a fallback, i.e., `%if{$albumartist_sort,$albumartist_sort,$albumartist}`.
