### ISSUE TITLE
How to Tag + Categorize while Importing

### ISSUE THREAD

**Issue by santhoshr** [beetbox/beets#2187]
### Problem

I have iTunes music folder, I want to maintain the folder structure intact, but move it to beets library\iTunes folder as well as I want to add flexible attribute 'iTunes_Purchase: true', the order in which happens should be

1. Add flexible tag (iTunes_Purchase to files) before importing (I know files should be in db to write tags, I'm looking for feature +addTag, while importing)
2. Then move the files to custom folder based on iTunes_Purchase attribute

I have two more queries
1. beet fields does not show extended fields in iTunes m4a files, how do I show additional tags created by Apple
2. Any way to identify individual import, like from source path, so even if I moved files to existing path structure (e.g. album/artist), I would be able to update sets of files with custom attribute using imported path, does it have something like data_source_path or import_session_id ?

**Comment by wordofglass** [comment]
1. is a common feature request, but beets cannot currently do this. I'd like to implement this at some point, but throughout the next months, I'll likely not have the time.

2. You can do this using queries in your [path configuration](http://beets.readthedocs.io/en/v1.3.19/reference/config.html#path-format-configuration). For more sophisticated paths formats, you might have a look at the [inline plugin](http://beets.readthedocs.io/en/v1.3.19/plugins/inline.html).

With regard to the additional questions:

1. AFAIK, beets does not know about these fields, but will not modify/delete them either (unless you use the `scrub` plugin, that is)

2. I don't think it has. Maybe there's some other beets-readable field with iTunes specific content you can use to select the files?

**Comment by sampsyo** [comment]
https://github.com/beetbox/beets/issues/1881 proposes to set a field on the import command line. Would that cover what you'd like to do here?

**Comment by santhoshr** [comment]
#1881 is what I described as well, but I would favor short form of giving additional tag, or overwriting exiting tag, since import is free of any other tag information, we can simplify it
beet import tag:value tag:value ./folder
(could be too simple! to cause accidental metadata overwrite)

Another feature I would like is, beet should have additional tag in db only, that identifies imported files using import session id, which could be running number or guid, or some hash code, every time import is made there will be entry in each file to identify imported session, this allows us operate on large set of files easily, change path, set additional metadata etc. Each session id is mapped to master session data, which will have details like no of files imported, path imported from, date added, etc.

**Comment by sampsyo** [comment]
OK! Can you add your thoughts to that issue? To be clear, though, we're more likely to use a standard option than to invent new UI syntax.

The "unique import id" idea is intriguing but somewhat specialized. Maybe you'd be interested in prototyping a plugin for that, which shouldn't be too difficult?
