### ISSUE TITLE
AssertionError when running 'beet dup --path'

### ISSUE THREAD

**Issue by catdesk** [beetbox/beets#2188]
### Problem

Crashes trying to get duplicate paths. `beet dup` works fine, as well as other options (`beet dup --full`)

Running this command in verbose (`-vv`) mode:

```sh
$ beet -vv dup --path
```

Led to this problem:

```
Traceback (most recent call last):
  File "/home/user/.local/bin/beet", line 11, in <module>
    load_entry_point('beets==1.4.0', 'console_scripts', 'beet')()
  File "/home/user/.local/lib/python2.7/site-packages/beets/ui/__init__.py", line 1267, in main
    _raw_main(args)
  File "/home/user/.local/lib/python2.7/site-packages/beets/ui/__init__.py", line 1254, in _raw_main
    subcommand.func(lib, suboptions, subargs)
  File "/home/user/.local/lib/python2.7/site-packages/beetsplug/duplicates.py", line 167, in _dup
    fmt=fmt.format(obj_count))
  File "/home/user/.local/lib/python2.7/site-packages/beetsplug/duplicates.py", line 176, in _proce>
    print_(format(item, fmt))
  File "/home/user/.local/lib/python2.7/site-packages/beets/ui/__init__.py", line 134, in print_
    assert isinstance(strings[0], six.text_type)

```
I'm seeing a lot of messages like:

    duplicates: all keys ['mb_trackid', 'mb_albumid'] on item /home/user/Music/William Gibson/The Peripheral (Unabridged) (2014) (Lorelei King)/42-The Peripheral (Unabridged) (2014).mp3 are null or empty: skipping

Maybe because the files are symbolic links?

### Setup

* OS: Debian
* Python version: 2.7.12+
* beets version: 1.4.0
* Turning off plugins made problem go away (yes/no):  yes, it's a problem with a plugin

My configuration (output of `beet config`) is:

```yaml
paths:
    default: $albumartist/$album%aunique{}/$track-$title
    singleton: Unknown_Album/$artist/$title
    comp: $albumartist/$album%aunique{}/$track-$artist-$title
library: ~/.local/beets/library.blb

replace:
    '[\\/]': _
    ^\.: _
    '[\x00-\x1f]': _
    '[<>:"\?\*\|]': _
    \s+$: ''
    ^\s+: ''
ignore: .AppleDouble ._* *~ .DS_Store *.wmv lost+found .* *.m4v *.mp4 *.part *.avi *.mkv *.flv *.mov *.mpeg *.mpg *.mpeg4 *.zip

ui:
    color: yes
    colors:
        text_success: green
        text_warning: yellow
        text_error: red
        text_highlight: red
        text_highlight_minor: lightgray
        action_default: turquoise
        action: blue

plugins: duplicates
directory: ~/Music

import:
    copy: no
    link: yes
    autotag: no
    log: log.txt
duplicates:
    count: no
    full: no
    format: ''
    keys: []
    move: ''
    tag: ''
    path: no
    copy: ''
    tiebreak: {}
    album: no
    strict: no
    checksum: ''
    merge: no
    delete: no


```

**Comment by sampsyo** [comment]
Thank you! It looks like this is an artifact of some Python 3 refactoring. I can reproduce this by running `beet dup --path`.

Sadly, I'm also getting a similar crash when running an ordinary `beet ls -p`:

```
$ beet ls -p
Traceback (most recent call last):
  File "/Users/asampson/Library/Python/2.7/bin/beet", line 9, in <module>
    load_entry_point('beets', 'console_scripts', 'beet')()
  File "/Users/asampson/code/beets/beets/ui/__init__.py", line 1267, in main
    _raw_main(args)
  File "/Users/asampson/code/beets/beets/ui/__init__.py", line 1254, in _raw_main
    subcommand.func(lib, suboptions, subargs)
  File "/Users/asampson/code/beets/beets/ui/commands.py", line 1071, in list_func
    list_items(lib, decargs(args), opts.album)
  File "/Users/asampson/code/beets/beets/ui/commands.py", line 1067, in list_items
    ui.print_(format(item, fmt))
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 63: ordinal not in range(128)
```

Technical details: I think something's going wrong when we format a template like `$path` to substitute bytes into a Unicode template. I think this should block the release of 1.4.0.

**Comment by jrobeson** [comment]
works great in python 3 :)   I didn't expect to cause 2.x bugs.

**Comment by jrobeson** [comment]
according to the docstring of `as_str`  it should always return unicode, but it doesn't gere https://github.com/beetbox/beets/blob/master/beets/library.py#L340   That does make the following `bytes` conditional useless though.

**Comment by jrobeson** [comment]
ah, and it was always `.str(unicode)` (or `.str(six.text_type)`) until https://github.com/beetbox/beets/commit/5efd5b21c5bade84a42833140d9365c4e8e505b3

**Comment by jrobeson** [comment]
I'm guessing that that bytes conditional is actually a leftover from `unicode_literals` ?

**Comment by sampsyo** [comment]
That should do it—just needed to make some template strings into Unicode literals. @catdesk, can you confirm this has cleared things up for you?

**Comment by catdesk** [comment]
Yes, it works now, thank you!!
