### ISSUE TITLE
beetsplug/fromfilename.py python3 compatability

### ISSUE THREAD

**Issue by codyopel** [beetbox/beets#2195]
https://github.com/beetbox/beets/blob/e8afcbe7ec4bc37bb080f6f466b98807d020753b/beetsplug/fromfilename.py#L104

python2
```python2
d.values()
```
for python 3 this should be
```python3
list(d.values())
```

**Comment by sampsyo** [comment]
Thanks! Can you please open a PR? (Just hitting the "edit" button should do it.)

**Comment by codyopel** [comment]
I am not sure what the plans are for python 2 compatibility and if python 2 support is being kept, what is the preferred way to implement a fallback for python 2.

**Comment by sampsyo** [comment]
We do want to keep compatibility with py2, but fortunately, wrapping this expression in `list(...)` will also lead to exactly the same behavior on 2 and 3.
