### ISSUE TITLE
nose (1.x) is mostly unmaintained

### ISSUE THREAD

**Issue by jrobeson** [beetbox/beets#2202]
https://nose.readthedocs.io/en/latest/#note-to-users

> Nose has been in maintenance mode for the past several years and will likely cease without a new person/team to take over maintainership. New projects should consider using Nose2, py.test, or just plain unittest/unittest2.

Are there any benefits to nose2 over py.test?

The community seems to mostly use py.test (if not using unittest) at this point.  I'd like to suggest making it our default test runner.    We can decide on adapting our tests to py.test separately.

**Comment by sampsyo** [comment]
Thanks for pointing this out. This confirms our long-standing unwritten policy of not depending on nose! Test *runners* come and go, but plain `unittest` is eternal. 😇 

I don't have much experience with py.test (and zero with nose2), so I don't have a strong opinion about which to recommend.
