### ISSUE TITLE
Add support for CATALOGNUMBER and LABEL tags

### ISSUE THREAD

**Issue by apastuszak** [beetbox/beets#2207]
One of the reasons why I have duplicate albums in my collection is because I will have releases made by "audiophile" labels such as Mobile Fidelity Sound Labs, Audio Fidelity or Digital Compact Classics.

When I allow beets to [k]eep multiple versions of an album, I like that it adds some identifying information into the folder, such as the release year.  But for these releases, I would love to see something other than the year added to the end of the folder such as this.  I currently have 3 versions of Queen's "A Night At The Opera."  I would love to see this:

A Night at the Opera
A Night at the Opera (1992 - Mobile Fidelity Sound Labs)
A Night at the Opera (2000 - Digital Compact Classics)

Opinion?

Am I being overly geeky here?

**Comment by sampsyo** [comment]
Hi! That disambiguation string is actually customizable—take a look at the docs for the `%aunique{}` path function.

**Comment by apastuszak** [comment]
Looks like you already support the CATALOGNUMBER and LABEL tags.  So I guess this can be closed.
