### ISSUE TITLE
No module named acoustid

### ISSUE THREAD

**Issue by dgiffen** [beetbox/beets#2220]
I may have spoken to soon that all was working correctly. I do have a much different error now. I could have over corrected myself. But I have done a clean install of beets, tried updating pyacoustid and pip is saying newest version

** error loading plugin chroma:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/beets/plugins.py", line 253, in load_plugins
    namespace = __import__(modname, None, None)
  File "/usr/local/lib/python2.7/dist-packages/beetsplug/chroma.py", line 27, in <module>
    import acoustid
ImportError: No module named acoustid

** plugin follow not found

The program does not crash. After the error it continues on without it. I get the same error just doing
beet version

**Comment by sampsyo** [comment]
Aha—it looks like Python thinks you're missing pyacoustid. This can sometimes happen if you get into a situation with multiple Pythons and `pip` refers to the wrong one.

**Comment by dgiffen** [comment]
It is clear to me that ubuntu is making this very sloppy. I have some of these in at least 2 locations, but am not sure which ones to remove. Is there anyway I can symlink it to the correct location. I believe I actually have all the correct versions and modules.

**Comment by dgiffen** [comment]
I removed both pycoustic, audioread, every found version. I then reinstalled via PIP. No more errors. It is a bit slower importing, so I am guessing it is working. I checked the log, but it did not show anything. I also tried verbose option on the command line, but do not see fingerprinting. It did run replaygain, acousticbrainz. I am guessing that this issue is closed though. Maybe you could provide some insight as to what I should see here.

**Comment by dgiffen** [comment]
I tried a beet fingerprint and it worked as expected


Thanks
Doug

**Comment by sampsyo** [comment]
Sounds like everything is working! Woohoo.

If you think it's not running on import, please paste the full verbose log.
