### ISSUE TITLE
put singletons into default path format if there is at least one album

### ISSUE THREAD

**Issue by ghost** [beetbox/beets#2226]
### Problem

I wish to move single tracks (singleton) from Non-Album/ to the default path format folder, if there is at least one album of the artist. The advantage of this approach is to keep all files of an artist together if using an audio player with folder view support.

Some album I've in my lib:

```
manu@X220:~$ beet ls -p Ebla
/home/manu/Music/E.S. Posthumus/Unearthed/05 Ebla.mp3
```

Some single tracks:

```
manu@X220:~$ beet ls -p E.S. Posthumus
/home/manu/Music/Non-Album/E.S. Posthumus/Granicus.mp3
/home/manu/Music/Non-Album/E.S. Posthumus/Posthumus Zone.mp3
[...]
```

should move to (root) or non-album subfolder of artist

```
/home/manu/Music/E.S. Posthumus/Granicus.mp3
/home/manu/Music/E.S. Posthumus/Posthumus Zone.mp3
```
### Setup
- OS: Xubuntu 16.04 LTS
- Python version: 2.7.12
- beets version: 1.3.18

My configuration (output of `beet config`) is:

```
directory: ~/Music
library: ~/Music/lib.db
import:
    move: yes
plugins:
    edit
    info
    random
    missing
    fetchart
    embedart
    badfiles
    thumbnails
    duplicates
    fromfilename
```

**Comment by sampsyo** [comment]
Hi! I can't think of a built-in way to accomplish that. You might try defining an inline field, called $has_albums, that evaluates to 1 or 0 depending on whether a given track's artist has albums in the library. You could then combine this with an %if{} in your path template to get what you want.

Defining that field with the inline plugin might be tricky—in which case a small custom plugin might be the right approach.

**Comment by arcresu** [comment]
Looks like the original submitter's account has been deleted in the meantime. Let's close this one.
