### ISSUE TITLE
keyfinder: Output parsing error

### ISSUE THREAD

**Issue by diomekes** [beetbox/beets#2242]
### Problem

Running this command in verbose (`-vv`) mode:

``` sh
$ beet -vv keyfinder anything
```

Led to this problem:

```
user configuration: /home/diomekes/.config/beets/config.yaml
data directory: /home/diomekes/.config/beets
plugin paths:
Sending event: pluginload
inline: adding item field disc_and_track
library database: /home/diomekes/.config/beets/library.db
library directory: /home/diomekes/media/music
Sending event: library_opened
Traceback (most recent call last):
  File "/usr/bin/beet", line 9, in <module>
    load_entry_point('beets==1.3.19', 'console_scripts', 'beet')()
  File "/usr/lib/python2.7/site-packages/beets/ui/__init__.py", line 1266, in main
    _raw_main(args)
  File "/usr/lib/python2.7/site-packages/beets/ui/__init__.py", line 1253, in _raw_main
    subcommand.func(lib, suboptions, subargs)
  File "/usr/lib/python2.7/site-packages/beetsplug/keyfinder.py", line 48, in command
    self.find_key(lib.items(ui.decargs(args)), write=ui.should_write())
  File "/usr/lib/python2.7/site-packages/beetsplug/keyfinder.py", line 74, in find_key
    key_raw = output.rsplit(None, 1)[-1]
IndexError: list index out of range
```

keyfinder-cli works if run directly
### Setup
- OS:  archlinux
- Python version: 2.7.12
- beets version: 1.3.19
- Turning off plugins made problem go away (yes/no): problem is with keyfinder plugin only
- libkeyfinder-git 239.0a5ec7f-1
- keyfinder-cli-git 49.40a41ab-1

My configuration (output of `beet config`) is:

``` yaml
...
keyfinder:
    bin: keyfinder-cli
    auto: yes
    overwrite: no

plugins: badfiles chroma convert duplicates fetchart fromfilename fuzzy info inline keyfinder lastgenre lyrics mbcollection mbsync missing play random scrub smartplaylist zero
...
```

**Comment by sampsyo** [comment]
Thanks! It looks like we need to assume something slightly weaker about the tool's output. It would also help for us to add logging output to show the tool's invocation and the "malformed" output.

**Comment by xudovect79** [comment]
I also get this error. Running the keyfinder-cli command on a mp3file directly gives the key. Could this be fixed please, keyfinder-cli is the only arch keyfinder program that actually works well.

**Comment by sampsyo** [comment]
Can you please include the actual output from the tool?
