### ISSUE TITLE
lyrics: Remove Genius backend

### ISSUE THREAD

**Issue by orf** [beetbox/beets#2246]
The function [get_lyrics](https://github.com/beetbox/beets/blob/master/beetsplug/lyrics.py#L291) looks up the lyrics from a server called `genius-api.com`

As far as I can tell this address is now defunct, I can't resolve it anywhere. Should it be removed?

**Comment by sampsyo** [comment]
Yes; looks like that service has gone away forever. We should indeed remove it, which will also involve removing the backend from the configuration structure and from the docs.
