### ISSUE TITLE
Add `move` switch to import command

### ISSUE THREAD

**Issue by raffomania** [beetbox/beets#2252]
I'd like to enable the `move=yes` option when using the CLI. `beet import -m` could be a suitable switch for this.

**Comment by raffomania** [comment]
I'd be happy to provide a PR if you're ok with it :)

**Comment by sampsyo** [comment]
Sounds great to me! A PR would be appreciated.

**Comment by karpinski** [comment]
Since the thread's been inactive for some time, I took the liberty of submitting a PR for this.

**Comment by sampsyo** [comment]
Fixed by @karpinski in #2429.
