### ISSUE TITLE
acousticbrainz: Submit analyses upstream to AB

### ISSUE THREAD

**Issue by Freso** [beetbox/beets#2253]
Originally planned for being part of https://github.com/beetbox/beets/issues/1629 (which was resolved with https://github.com/beetbox/beets/pull/1787), the feature for the "acousticbrainz" plugin to run the analysis locally and submit results back to AcousticBrainz never made it in. It would still be a neat thing to have though. :)

**Comment by sampsyo** [comment]
Yes; thanks for opening a reminder ticket!

**Comment by inytar** [comment]
I'd like to pick this u if possible.

**Comment by sampsyo** [comment]
Wonderful! Let's do it. This task has two parts: running the analysis program to get data and submitting the results to the web service API. Both start with information gathering: you'll want to look into the details for how to go both things and discuss your findings here. Sound good?

**Comment by inytar** [comment]
Sound perfect! Here's my research:
Analysis:
- An extractor program is needed for the data analysis (http://acousticbrainz.org/download bottom left).
- AB would prefer if you use their static build of the extractor (http://acousticbrainz.org/faq second question).
- The extractor only works on: mp3 ogg oga flac mp4 m4a m4r m4b m4p aac wma asf mpc wv spx tta 3g2 aif aiff ape (http://acousticbrainz.org/contribute)
- The extractor will output a json file containing the `lowlevel` analysis, `metadata` and `rhythm`.

Uploading:
- Uploading should be done by using POST to the url `https://acousticbrainz.org/api/v1/<MBID>/low-level`.
- MBID is called recording id in different places, but all code uses the `musicbrainz_trackid`.
- The output file from the extractor and the sha1sum of the extractor program set to `metadata: version: essentia_build_sha` are send to the server (if you do not add the sha1sum the server responds with the error `{  "message": "Key 'metadata : version : essentia_build_sha' was not found in submitted data."}`)
- Content type header should be set to `application\json` else the server will respond with the error: `{  "message": "Cannot parse JSON document: No JSON object could be decoded"}`.

**Comment by sampsyo** [comment]
Really awesome; thank you for looking into it! This all checks out, and it sounds like it should make the implementation relatively straightforward. We can just run the extractor agains the files and use `requests` to hit the AB API.

The only tricky part is that we'll need to compute the hash of the extractor executable, which we can do in a way similar to this: https://github.com/MTG/acousticbrainz-client/blob/c135a557c61984effcdb9d7a0c2686a64829b217/abz/config.py#L115-L118

Not too hard!

So I think the next step is to start making the plugin skeleton. Maybe a good place to start would be to look at the `keyfinder` plugin, which is quite small and also needs to invoke an external tool to do its work. The key API is `util.command_output`, which is used to run another tool and collect its stdout.

Let us know if any other advice would be helpful!
