### ISSUE TITLE
fetchart uses .jpg, extractart uses .jpeg

### ISSUE THREAD

**Issue by tweitzel** [beetbox/beets#2254]
The extractart command in the embedart plugin uses the string output of imghdr.what as an extension. That's "jpeg." 
https://github.com/beetbox/beets/blob/db782a2404fa8a6827c10a6536b4a960d19af135/beets/art.py#L197

Meanwhile, over in fetchart, it seems to use the first entry in IMAGE_EXTENSIONS for mime type image/jpeg, which is .jpg.
https://github.com/beetbox/beets/blob/db782a2404fa8a6827c10a6536b4a960d19af135/beetsplug/fetchart.py#L44

To reproduce:

Import something with no art, but has jpeg art in a configured fetchart source.
beet fetchart album
beet embedart album
beet extractart album
now you have cover.jpg and cover.jpeg or sometimes cover.1.jpeg or sometimes cover.1.jpg... it's kind of a big mess and seems weirdly nondeterministic at times.

This is normally harmless, but sometimes results in excessive clutter when re-importing old things.

**Comment by sampsyo** [comment]
Thanks! We should definitely make that consistent.

**Comment by nathdwek** [comment]
This should be a quick fix. [This](http://stackoverflow.com/questions/23424399/jpg-vs-jpeg-image-formats) seems to indicate `jpg` is the most commonly used extension, so I would advocate for it to be used.

**Comment by sampsyo** [comment]
Sounds good to me. Staying consistent with `fetchart` seems more useful than obeying `extractart`, which is less commonly used.

**Comment by nathdwek** [comment]
BTW this makes me realize that my fix in #1545 should have targeted this too, but it didn't, and `extractart` fails on the same types of image for the same reason. I will try to bring all of this under one umbrella while fixing this issue.
