### ISSUE TITLE
Duplicates while importing

### ISSUE THREAD

**Issue by ggVGc** [beetbox/beets#2259]
### Problem

Importing the same folder/files twice gives us duplicates. This makes it very hard to have a growing music collection managed by beets.
My expected use case is that I can go `beet import -A /music`, then add some folders and do the same again. which would add whatever is new, rather than adding everything again and giving duplicate entries.

Personally I feel there should be a fundamental design in beets completely preventing multiple entries of the same concrete files.

**Comment by nathdwek** [comment]
You should probably look into the `duplicate_action` and `incremental` importer configuration options. They are listed [here](http://beets.readthedocs.io/en/v1.3.19/reference/config.html#importer-options).

The first requires no setup, but is obviously no the smartest in terms of performance, while the second requires you to consistently use it in order to track the directories you import, but will skip already imported directories without performing useless operations.

**Comment by ggVGc** [comment]
Thanks,
`duplicate_action` seems to only trigger when autotagging is enabled though. That is, not when using the -A option. This seems incorrect to me. Also, I still question the use case of having multiple versions in the database corresponding to the same concrete file. Is there a reasoning behind that?

**Comment by nathdwek** [comment]
* I should probably check the underlying comparisons, but if the file did not change between two imports, then the metadata fed to the "write to database" phase, straight from the file, will not change as well, and `duplicate_action` should happen.
* It seems like `incremental` would suit your use case.
* I don't really understand your worry. I you use `incremental`, the problem goes away. Even if you don't the autotagger can then catch some if not most of the duplicates. So your scenario would be reimporting with autotagger disabled and after having moved the files around in your `music/`directory.
   * This is really contrived and goes against the expected use case, so it is normal everything doesn't fit you immediately.
  * Technically, I don't really know what we could do besides some sort of hashing, which would be very computationally expensive

**Comment by nathdwek** [comment]
@ggVGc, before I close this, could you give us feedback on using `incremental` or any other solutions and the result of your reflections on using `beets` with an externally managed directory?

**Comment by ggVGc** [comment]
Yeah, incremental works as expected. I still find it somewhat strange to support the situation of multiple entries per concrete file path, but I guess with the current database design it may be technically infeasible to prevent it in an efficient manner.
I do think it would be nice to have some form of import mode that helps beets track a directory that changes from external modifications. E.g that would prevent adding paths that are already in the databse(like incremental), and that would delete entries whose files have been deleted. Maybe this is achievable in some other way easily. I have only just barely started using beets.
