### ISSUE TITLE
Setting an artistsort template or just disabling it?

### ISSUE THREAD

**Issue by bjesus** [beetbox/beets#2261]
### Problem

When Beets import my music it sets an `artistsort` tag in the format of "Surname, First name" . This seems to be a mostly regional preference, as no one where I live is used to seeing lists like that. 

Is there a way to change the tag's template so it would look like "Firstname Surname"? Or, is there a way to just tell Beets not to write it? Obvisouly I could use `modify` to edit these tags after importing, but I would have to do it after each and every import, which seems a bit too much.

and thanks for Beets!

### Setup

* OS: Arch Linux
* Python version: 2.7.12
* beets version: 1.3.18

**Comment by nathdwek** [comment]
Have you looked into the `zero` plugin?

**Comment by bjesus** [comment]
Thanks @nathdwek! Even though it doesn't let me choose a new template for the tag, this seems to be a sufficient solution.
