### ISSUE TITLE
Edit plugin can't find PromptChoice

### ISSUE THREAD

**Issue by gboysko** [beetbox/beets#2263]
### Problem

Tried to use `edit` plugin, but it complained about `PromptChoice`

```sh
** error loading plugin edit
Traceback (most recent call last):
  File "/usr/share/beets/beets/plugins.py", line 201, in load_plugins
    namespace = __import__(modname, None, None)
  File "/home/glenn/.local/lib/python2.7/site-packages/beetsplug/edit.py", line 24, in <module>
    from beets.ui.commands import _do_query, PromptChoice
ImportError: cannot import name PromptChoice
```

### Setup

* OS: Ubuntu 16.04 
* Python version: 2.7.12
* beets version: 1.3.8
* Turning off plugins made problem go away (yes/no): yes

My configuration (output of `beet config`) is:

```yaml
directory: /mnt/980425CD0425AF66/MP3s.new
import:
    move: yes
    write: yes
original_date: yes
asciify_paths: yes
id3v23: yes
plugins: edit embedart lastgenre scrub missing info
paths:
    default: $albumartist/$album%aunique{}/$track $title
replaygain:
    backend: gstreamer
```

**Comment by sampsyo** [comment]
Is there any chance you have two copies of beets installed (one in `/usr/local`, for example, and one in `/home/glenn/.local/`)?

**Comment by gboysko** [comment]
I guess I do. I'm sorry. I had followed the documentation to run `pip install beets`, but after it wasn't found on the command line, I ran `sudo apt-get install beets`. 

Should I try to uninstall one of them? If so, which one?

**Comment by sampsyo** [comment]
Yes—I'd recommend uninstalling the one you got through `apt-get`, which is probably older.

**Comment by gboysko** [comment]
Thanks. That did it. Now, I don't have it in my path. Do most people have `~/.local/bin` added to their path? Or was the `pip install` command supposed to do that?

**Comment by sampsyo** [comment]
Yep, you'll want to add `~/.local/bin` to your path. That's what I do, at least!

**Comment by nathdwek** [comment]
You can use `pip install --prefix=$HOME` instead of `pip install --user` if for some reason having binaries in `~/.local/bin` is not possible for you, but AFAIK nowadays `--user` is more recommended.

**Comment by gboysko** [comment]
Thanks, all. We can definitely close this issue up.
