### ISSUE TITLE
web: View album art

### ISSUE THREAD

**Issue by claman** [beetbox/beets#2272]
I'm not sure if this has been brought up before, but I really like being able to view album art. Is there a way to add that to the web interface, or possibly through a plugin?

**Comment by sampsyo** [comment]
Seems like a good idea! We'd really like to move to a new architecture for the web plugin so it could be extensible in this way (c.f. #718), but if you're interested, there's also no reason we couldn't hack it onto the current web interface.

**Comment by claman** [comment]
I don't think that I know enough python to be of much help here, but I'll take a look soon

**Comment by claman** [comment]
This seems like a good repo to pull ideas from: https://github.com/tkem/mopidy-local-images

Has development on https://github.com/jtemplet/beets-web stalled?

**Comment by irskep** [comment]
To answer your last question about running code in the repo, I typically create a virtualenv, and then run code like this:

```sh
python setup.py install && beet <cmd>
```

It's a little slow but you always get the freshest version of your code.

**Comment by claman** [comment]
So I was (finally) poking around the code a bit more, and it looks like flask is exposing the albumart if the item has it available, but I can't figure out how to access it.

I'm looking at these lines:
```
271 @app.route('/album/<int:album_id>/art')
272 def album_art(album_id):
273     album = g.lib.get_album(album_id)
274     if album.artpath:
275         return flask.send_file(album.artpath)
276     else:
277         return flask.abort(404)
```

**Comment by sampsyo** [comment]
Just use an image tag like `<img src="/album/(id)/art">`, given the id of the album. That should do it.
