### ISSUE TITLE
Configure metadata (itemfields) to be used

### ISSUE THREAD

**Issue by ArchangeGabriel** [beetbox/beets#2273]
I’m sorry if this has already been discussed, but I haven’t found anything related. And I’m very new to beets, so wouldn’t have been notified of any prior discussion (heard about beets years ago, but because being very maniac about my files organization, was still doing things by hand with help of ExFalso, until I finally jumped in today).

My issue is that beets write way too much metadata to my tracks (relative to my taste). I would like to configure which metadata are used/written, and also have them not written if they are empty or 0.

For instance I don’t care about ASIN, BPM, RELEASECOUNTRY and things like that, so I would like to disable writing/use of them by beets (and it would be nice to have a way to remove a given itemfields/metadata from every track in my collection).

Other than that, beets is quite an awesome piece of software, keep up the good work!

**Comment by sampsyo** [comment]
Hi! Have you checked out the `zero` plugin?

**Comment by ArchangeGabriel** [comment]
Admit having missed it. When it says “null”, does that mean empty them, set them to 0, or remove them? Last one would be quite awesome.

**Comment by sampsyo** [comment]
Great! However, no, it can't currently remove tags altogether (see also #919).

**Comment by ArchangeGabriel** [comment]
Well #919 looks staled… So I will still have the tags, but they will be empty? Then I think this issue will have to wait for #919 to land before being closed (I can change the title if needed).

So what should I do right now is setup Zero, hand edit what beets already imported to clean it, and then should be (almost) fine?

Also, what about not writing tag when they are 0 or empty? For instance, I have a release from an unknown year, so it’s set to 0, while DATE and ORIGINALDATE are set to 0000.

**Comment by sampsyo** [comment]
Yeah, if you're interested in deleting tags altogether, we could use your help! Not just with the coding: #919 and other efforts have beeen made in the past, but they all had serious drawbacks. You can help, if you're interested, by looking through the trove of related issues and filing one that summarizes the current state of things and makes a proposal.

In particular, we can't do the implicit removal thing, where zero is equivalent to a missing tag, because zero is a meaningful value for some tags.

**Comment by ArchangeGabriel** [comment]
OK, sure. :) Currently lacking a bit of time (PhD student with already a lot of other activities here), but definitively something I will want to look at when things settle down a little. ;)

**Comment by ArchangeGabriel** [comment]
Bonus question: how to disable “ALBUM ARTIST”? I want only album_artist.

**Comment by ArchangeGabriel** [comment]
In the same vein, they are:
    disc            : 1
    DISCTOTAL       : 2
    DISCC           : 2
    TOTALDISCS      : 2
And:
    track           : 1
    TRACKTOTAL      : 7
    TRACKC          : 7
    TOTALTRACKS     : 7

I want to keep disc/track, DISCTOTAL and TRACKTOTAL but not the other ones (ending with C or starting with TOTAL).

**Comment by ArchangeGabriel** [comment]
And is there a doc where I can found the description of all itemfields? There seems to be mismatches between tags and them (are some itemfields only for beets db?), at least in my understanding of them.

**Comment by ArchangeGabriel** [comment]
Side note for the nomeaningless tag writing feature: do not write sort tags if they are identical to non sort ones.

**Comment by sampsyo** [comment]
Assuming you're looking at a file format with free-form tag names (like FLAC) using a tool that lists all key/value pairs, you might want to see #350.

It might help to understand that there is not a 1-1 correspondence between the physical tag names in your favorite media format and the logical field names that beets uses. For example, `albumartist` is a beets field that is mapped to different on-disk tags for different media formats. If you want to see a full list of beets fields, you can run `beet fields`. To see how those map to files' tags, you unfortunately need to read the source code.

**Comment by ArchangeGabriel** [comment]
Yes, sorry, I’m only using FLAC files. OK for #350.

It also helped me to understand the second point. Can you give me a pointer for where to look in the code or is it too sparse?

**Comment by sampsyo** [comment]
No, it's not too hard! The tag mappings are declared here: https://github.com/beetbox/beets/blob/31b23207a81b067757048097c102b13d6a79582b/beets/mediafile.py#L1564

**Comment by ArchangeGabriel** [comment]
Nice. :) So, I should look at StorageStyle (no prefix one), right? Also, if support for other tags where to be added, that would be the right place I suppose? I might propose a PR for some when I got time (place, conductor, maybe other). (Except I’m not sure whether they exists in all 4 standards and that maybe this is what define the supported list in beets?)

**Comment by sampsyo** [comment]
Yes and yes!
