### ISSUE TITLE
The zero plugin needs a manually triggered mode

### ISSUE THREAD

**Issue by nathdwek** [beetbox/beets#2274]
As of now, the `zero` plugin is only triggered at import time, which means that if a user wants to use the plugin down the road or change its configuration, he has to re-import his whole library.

As is the case with `fetchart`, `embedart`, `convert`, ... I propose that the plugin provides a `zero` (extra points for creativity) command to compliment the import hooks.

**Comment by sampsyo** [comment]
Yes, good call.

**Comment by sampsyo** [comment]
Fixed in #2329. Thank you, @SJoshBrown!
