### ISSUE TITLE
"embedart auto" setting overrides "import write no" setting

### ISSUE THREAD

**Issue by Vrihub** [beetbox/beets#2275]
I'm not sure if this is really a bug; if this is intended behaviour, I think it should be documented in plugins/embedart.html

If you have ...
```
import:
    write: no
```
and also use the embedart plugin in auto mode...

```
embedart:
    auto: yes
```

The embedart `auto: yes` setting will override the import `write: no` setting, so at import time all metadata (including textual tags) will be written to the files.

### Setup

* OS: Linux
* Python version: 2.7.6
* beets version: 1.3.8

**Comment by sampsyo** [comment]
Hmm; yes, good point. Embedding art into files requires manipulating their tags, to this is (at least to some degree) unavoidable. It should definitely be documented, though!

As with the other ticket, any chance you could help us out by drafting a sentence or two on the appropriate page?

**Comment by Vrihub** [comment]
Uhm, actually no, I have to apologise, this is a duplicate of #1427, which has already been fixed. I was running an old version of beets from my Linux distro, and I failed to find #1427 in the BTS, so you can close this ticket, sorry about the noise.

**Comment by sampsyo** [comment]
Ah, thanks for digging that up!
