### ISSUE TITLE
By default beets should be verbose and ask for confirmation for all actions that overwrite data

### ISSUE THREAD

**Issue by Vrihub** [beetbox/beets#2276]
As a novice beets user, I'm noticing that many configuration variables have defaults values that are optimised for the experienced user, who already knows what he's doing, but that's not the case for the novice user, who is learning to use beets commands.

Especially: many commands that make irreversible changes to the database or files don't print enough information about what they are doing, and, more important, don't ask for confirmation, as one would expect. 

That's bad. It's too easy for a novice user to make mistakes and damage data. When you also consider #1286, that's pretty scary :)

Suggestion: default values for some configuration variables should be more conservative and newbie-friendly, display more information about what is being done, and ask for confirmation before overwriting data.
Some examples:
* `import` `timid` should default to `yes` (and maybe also `detail`)
* #1999 (embedart)

Other suggestions:
* Add a `timid` setting to other commands, besides `import`?
* Add a global `verbose` config variable (instead of having to add `-v` to every command invocation)?

**Comment by sampsyo** [comment]
Hi! thanks for weighing in!

Do you think you can expand with a little more detail about ways beets surprised you with data modifications? What were you doing, and what did you expect?

In general, I do think there are several places that could use a prompt (you pointed to #1999, which is a good example). But I'm a little skeptical of a blanket policy here against any disk writes without confirmation. In particular, our default import settings are crafted to avoid data loss: your files are copied somewhere else before they are written. And I'm concerned that "timid by default" could end up being *less* user friendly by making the autotagging process more onerous.

**Comment by sampsyo** [comment]
> Add a global verbose config variable (instead of having to add -v to every command invocation)?

This actually already exists (you can set `verbose` to 1 or 2 in your config file). But it appears to be undocumented—we should fix that!

**Comment by Vrihub** [comment]
> Do you think you can expand with a little more detail about ways beets surprised you with data modifications? What were you doing, and what did you expect?

Well, basically the kind of actions already fixed in #1697, sorry but I was using a version prior to 1.3.16

> you can set verbose to 1 or 2 in your config file. But it appears to be undocumented

Ah, good to know that, thanks. This should really be documented.

**Comment by sampsyo** [comment]
OK, sounds good. But yes, any help filling in the docs for verbose mode would be helpful!
