### ISSUE TITLE
info plugin: optionally support $PAGER

### ISSUE THREAD

**Issue by Vrihub** [beetbox/beets#2278]
Output from the info plugin can be quite long; it would be good to have a configuration option so that if $PAGER exists in the environment, the command output is displayed through the configured pager (`less` etc) instead of standard output.

Of course, maybe this could apply to other beet commands that potentially output a lot of stuff.

**Comment by sampsyo** [comment]
Hmm, maybe... in cases like this, though, sometimes it seems easier to just pipe the output into `less -F`. Does anyone know of any general guidelines about when pagers should be used automatically and when it's better to leave them up to the user? Should *every* command that can possibly output lots of text have an option to set up the `less` pipe for you?

**Comment by jrobeson** [comment]
There is no general guideline.  git does page by default, while lots of other programs do not.

**Comment by ArchangeGabriel** [comment]
systemd does too now. But indeed, no general guideline. But I agree that it would be nice to have things like `beets ls` use $PAGER if the output is a bit long.

**Comment by sampsyo** [comment]
OK! Personally, I usually don't find it too hard to append `| less` to commands, but I definitely do rely on the shorthand in commands like `git log`. We could consider adding a global setting that potentially-long commands, such as `list` and `info` could opt into, if that seems more convenient than typing the shell pipeline.

**Comment by tweitzel** [comment]
My opinion may be minuscule, but the testing requirements for keeping a wrapper that outputs to $PAGER for only some commands seems chaotic. Off the top of my head, what if a used bodged together a minimal plugin for their own use* that just blats things with print()? Do we override sys.stdout or print() to make sure it goes out the same path as the other commands?

* Not that I've ever done that, cough cough.

**Comment by sampsyo** [comment]
Yeah, you're very right that the implementation seems tricky—we'd need to funnel all stdout through something we can interpose on. Or, I guess, play some magic trick where we `fork` a pager process and then reassign our stdout handle to its stdin stream.

**Comment by Vrihub** [comment]
Ok nevermind, I got the idea from the mysql command line client (that has such option), but I didn't know about the beets internals, so if it's tricky to implement, please ignore this and concentrate on implementing more useful features! :)

**Comment by sampsyo** [comment]
Fair enough! We'll focus on other stuff. :smiley:
