### ISSUE TITLE
Provide a way to update paths after making changes to replace config mappings

### ISSUE THREAD

**Issue by Vrihub** [beetbox/beets#2279]
Scenario: I've made some changes to the mappings in the `replace:` config section.
How can I update the paths for the music that is already in the library, to reflect the new `replace` mappings?

Neither a simple `update` or `move` will work (for good reasons); of course removing
items and re-importing them should work, but I wonder if there is a quicker way, or if there should be (by extending `update` and or `move`).

The only workaround I found so far is to make some changes with `modify` or `edit` to metadata that will affect the path, so that a new path is created using the new `replace` mappings.

**Comment by sampsyo** [comment]
Hmm, what's wrong with `beet move`? That's exactly what the FAQ recommends for this situation.

**Comment by Vrihub** [comment]
> Hmm, what's wrong with beet move? That's exactly what the FAQ recommends for this situation.

`beet move` works if I make changes to `paths: -> default: ...` in config, but not when I make changes in `replace:` rules

**Comment by sampsyo** [comment]
That's odd; it should! Does removing and importing again work?

**Comment by RollingStar** [comment]
Maybe a flag to move to force a move attempt even if there are no detected changes to path formats?

**Comment by sampsyo** [comment]
We don't actually have a check regarding whether path formats change. We do check whether the destination path is different from the current one, but disabling that seems like it could get us into trouble. (A no-op rename is an error on some systems.)
