### ISSUE TITLE
ftintitle: extremely slow

### ISSUE THREAD

**Issue by mfiano** [beetbox/beets#2281]
ftintitle plugin, when called manually after import takes an incredibly long time to complete - infact the import with all the MB queries was faster. On top of this, its output printed seems to be in a completely random order, with several minutes between each line printed. Also the CPU usage is between 1-30% for a single CPU core for beets. It's as if it is mostly idle.

**Comment by sampsyo** [comment]
That's odd. A quick test here didn't reproduce the problem:

```
$ time beet ftintitle
beet ftintitle  0.50s user 0.16s system 97% cpu 0.670 total
```

Can you please include a verbose log? And perhaps check whether this happens for some tracks but not for others?

**Comment by mfiano** [comment]
I ran `watch lsof ...` to check out exactly what it was working on, and it seems to spend a long time on flac files compared to lossy files. I suspect it is reading the whole file stream and then writing the whole thing back to disk when it writes the tags, probably with a really small chunk size.

**Comment by sampsyo** [comment]
OK! But your configuration and the verbose log would still be helpful.
