### ISSUE TITLE
path template errors

### ISSUE THREAD

**Issue by mfiano** [beetbox/beets#2283]
I'm running 1.3.19, so not sure if this has been addressed in 1.4/HEAD yet, but I noticed a problem that is easy to reproduce with certain path format templates. The documentation states the following:

```
The characters $, %, {, }, and , are “special” in the path template syntax. 
```

I wanted to put comp into a [compilations] sub-directory, so they would be sorted near the top of the directory tree. Likewise for [soundtracks]. If the '[' character appears first in the template, beets signals an error condition:

```
expected <block end>, but found '<scalar>'.
```

I then tried with an exclamation mark (!) character, and got the same error. I then tried to escape them, by preceding a $, but the result is not escaped - the path written to disk has a literal $[ or $! first.

**Comment by sampsyo** [comment]
Interesting… I don't recognize that error message ("expected <block end>, but found '<scalar>'."). Did beets print anything else? Are you sure that message was from beets, or could it have come from somewhere else? Was there a traceback?

Can you please include your configuration and the command you ran?

**Comment by mfiano** [comment]
This was a YAML error due to unquoted special characters in strings. Closing.
