### ISSUE TITLE
asciify_paths translation is wrong

### ISSUE THREAD

**Issue by mfiano** [beetbox/beets#2284]
In at least the case of "ə", this is translated to ASCII wrongly.

Given "(həd) p.e." and "əkoostik hookah", the translation becomes: "(h@d) p.e." and "@koostik hookah", respectively. According to the correct spelling as per the artists' official websites, it should be translated to an "e".

**Comment by sampsyo** [comment]
Hi! That "asciification" uses a simple find-and-replace dictionary (c.f. http://search.cpan.org/~sburke/Text-Unidecode-1.27/lib/Text/Unidecode.pm), not any human-edited source of truth for transliterations, so it won't be able to get every case correct. For transliterations as the artist intends, we'll need to rely on MusicBrainz or some other data source.
