### ISSUE TITLE
move doesn't update path to reflect artist/albumartist

### ISSUE THREAD

**Issue by rlegrand** [beetbox/beets#2288]
### Problem

I have edited fields artist/albumartist of an album in order to remove the japanese characters.
That's done, but when I now try to move the files with a beet move, the path remains unchanged. When I force a directory ( beet mv -d /test/ album:thealbum ), the files are moved to test but the structure of the folders remains the same ( **oldalbumartist_with_jap_characters/album** instead of **albumarstist/album** ). 
I have tried to edit the path field, but it seems to be forbidden because the modification is said to be ignored...

Running this command in verbose (`-vv`) mode:

```sh
$ beet -vv mv path:.
user configuration: blabla/config.yaml
data directory: blabla.config/beets
plugin paths:
Sending event: pluginload
library database: /some/path/beets-library.blb
library directory: //some/path
Sending event: library_opened
Moving 0 items.
Sending event: cli_exit
```

### Setup

* OS: raspbian
* Python version: 2.7.9
* beets version: 1.4.1
* Turning off plugins made problem go away (yes/no): no

My configuration (output of `beet config`) is:

```yaml
import:
    group_albums: yes
library: /some/path/beets-library.blb
```

Any idea?

**Comment by sampsyo** [comment]
Hi! You probably need to use the -a flag on the `modify` command if you're changing album-level fields like albumartist.

**Comment by rlegrand** [comment]
Yep, you're right, it works perfectly, thank you for helping.
