### ISSUE TITLE
Fetch album-level metadata in singleton imports

### ISSUE THREAD

**Issue by ghost** [beetbox/beets#229]
It appears beets will not add album information for a singleton, even though it
could.

For example you can run

```
beet import -s test.mp3
```

and no album info will be added, however if you instead run

```
beet import .
```

then album info will be added, where `.` contains `test.mp3`. Again, "Picard" treats both folders and individual files as "first class citizens".

**Comment by honus100** [comment]
@svnpenn I know this is an old thread, but I have the same problem with singletons in Beets. When I follow your link it takes me to a script for creating a video from a song and picture. Is the link taking me to the wrong script?

Thank you.

**Comment by svnpenn** [comment]
@honus100 part of that script should work for your needs, maybe I could break it out into its own script.
