### ISSUE TITLE
copy/move extra files to new dir

### ISSUE THREAD

**Issue by EnduringGuerila** [beetbox/beets#2292]
### Problem

I am trying to find a way to copy the .log files from the old folder to the new organized folder. The .log files are the rip logs from the CDs using ExactAudioCopy. 

I couldn't find a better place to post this question, sorry.

Running this command in verbose (`-vv`) mode:

```sh
$ beet -vv (... paste here ...)
```

Led to this problem:

```
(paste here)
```

Here's a link to the music files that trigger the bug (if relevant): 

### Setup

* OS: 
* Python version: 
* beets version: 
* Turning off plugins made problem go away (yes/no): 

My configuration (output of `beet config`) is:

```yaml
(paste here)
```

**Comment by sampsyo** [comment]
Hi! Please see #111 and this third-party plugin: https://github.com/sbarakat/beets-copyartifacts
