### ISSUE TITLE
Single Disc Album, no disc 1/1 tags

### ISSUE THREAD

**Issue by EnduringGuerila** [beetbox/beets#2293]
### Problem

The vast majority of my albums are single disc. I prefer there not be a Disc 1/1 (or 1 of 1, etc)
I cannot find in the Docs how to avoid tagging the amount of discs unless there are 2 or more.

Running this command in verbose (`-vv`) mode:

```sh
$ beet -vv (... paste here ...)
```

Led to this problem:

```
(paste here)
```

Here's a link to the music files that trigger the bug (if relevant): 

### Setup

* OS: 
* Python version: 
* beets version: 
* Turning off plugins made problem go away (yes/no): 

My configuration (output of `beet config`) is:

```yaml
(paste here)
```

**Comment by EnduringGuerila** [comment]
I don't know if there is a way to add an if statement to the config
something like
if disctotal <= 1
make disc tag empty

**Comment by sampsyo** [comment]
Hi! Here's a relevant thread from the mailing list archives:
https://groups.google.com/forum/m/#!topic/beets-users/M3Qx6-VPoQc

In summary, you might be able to get the `zero` plugin to do what you want, but it might take some fiddling. If that doesn't work out and you can see an elegant way to extend the plugin to make this work, let's use a new feature request for that.
