### ISSUE TITLE
Feature request: hook badfiles plugin with import

### ISSUE THREAD

**Issue by mfiano** [beetbox/beets#2301]
It would be very nice to have a hook that allows the user to specify an action to perform when attempting to import a file that the badfiles plugin detects problems with. This should be similar to duplicate_action, with options to ask, ignore and import anyway, or never import.

This would allow music to never be imported if it has problems preventing it from decoding properly, or at least ask the user (in the case of the "ask" action), with the log from badfiles for that item.

**Comment by sampsyo** [comment]
Please see #1633.
