### ISSUE TITLE
Autotag without importing

### ISSUE THREAD

**Issue by alex-phillips** [beetbox/beets#2314]
Is there a way, or what is the best way, to simply use beets as an autotagger, but don't import the files? I just want to point beets to a directory, have it tag with data from MusicBrainz, but don't save anything to the database, don't rename or move the files, etc.

**Comment by sampsyo** [comment]
No, there's no option to avoid writing to the database—but you can easily configure it to not move or write to files:

```yaml
import:
    copy: no
    write: no
```

And then you can just ignore that the database exists at all. Or just `alias beet='beet ; rm ~/.config/beets/library.db` or something to delete it every time. :smiley:

**Comment by alex-phillips** [comment]
gotcha. So maybe have a second 'dummy' config that doesn't have my plugins or anything, and the alias can copy that config into place, do what I want it to, and remove the dummy DB as you said

**Comment by sampsyo** [comment]
If you want a temporary configuration for any reason, you can always use `beet -c /path/to/file.yaml` instead of copying around files.
