### ISSUE TITLE
Support multiple formats and qualities for one track or album

### ISSUE THREAD

**Issue by twrightsman** [beetbox/beets#2316]
This feature request is similar to https://github.com/beetbox/beets/issues/791 but I think it would be useful to have beets capable of managing multiple file formats of the same track and/or album in the beets directory and library. This would be similar to how Calibre can convert between and store multiple file formats of the same book for different ebook readers.

**Comment by sampsyo** [comment]
Hi! This sounds intriguing, but I don't quite understand how it would work. Can you go into a little more detail on how this would look from a UI perspective? How would the importer detect this? How would you tell beets that you're adding a second format for an existing album? What would the output of `beet ls -p` be? How would you `beet rm` one copy but not the other? This kind of thinking can help determine what needs to be done.

**Comment by twrightsman** [comment]
Sure!

> How would the importer detect this?

I am imagining that beets finds a file during the import process that, according to its metadata, is already present in the library (either from the same import run or a previous one) but is of a different file format or even same format but different quality.

> How this would look from a UI perspective?

Beets would ask similar questions when duplicates are detected:

- Do you want to keep the higher quality of the two (https://github.com/beetbox/beets/issues/791)?
- Do you want to keep the new one?
- Do you want to keep them both in the library?

> How would you tell beets that you're adding a second format for an existing album?

It seems this would be handled without a user flag, but by auto-detection of an existing album with the same (or similar) metadata to the one being imported.

> What would the output of `beet ls -p` be?

This command would simply list all filenames of all tracks like so:

```
/Library/Artist/Album/Track1.ogg
/Library/Artist/Album/Track2.ogg
/Library/Artist/Album/Track2.mp3
/Library/Artist/Album/Track3.ogg
```

Is there any problems you are imagining where this wouldn't be an ideal case? Would there be a situation where a user would want only one filename per track in `beet ls -p` output? If so, we could create a "preference" flag to output, per track, only the filename of the preferred format if multiple file formats exist for that track so that we could enforce a "one track, one filename" rule.

> How would you `beet rm` one copy but not the other?

If `beet rm` detects multiple file formats for a track matching the query then it can ask similar questions to the ones on import (if the `-d` flag is used, I would keep the default no-flag behavior of leaving the files on the disk):

- Do you want to delete all file formats?
- Which file formats do you want to delete?

If we want to do this non-interactively, we could have that preference flag again, where a file format or formats is/are preferred for deletion (and all others kept).

**Comment by jrobeson** [comment]
@twrightsman :  the missing plugin should also be  detect the example you posted:

```
/Library/Artist/Album/Track1.ogg
/Library/Artist/Album/Track2.ogg
/Library/Artist/Album/Track2.mp3
/Library/Artist/Album/Track3.ogg
```

as missing an mp3 file for Track1.    So we'd definitely wanna think about how it'd work with other plugins too.

**Comment by sampsyo** [comment]
Hmm... so far, this sounds pretty similar to just having multiple copies of some music in your library. For example, you could just choose "keep both" on import and you'd end up with two different albums with the same metadata but different files.

Any thoughts about how your proposal would improve on that?

**Comment by twrightsman** [comment]
I do agree that the situations are quite similar. However, I don't see the advantage of having two different albums with the same metadata. It would seem more user-friendly to have all the different file formats in one folder and to modify the keep both behavior to follow this.

I don't think the current `convert` plugin is the ideal implementation by transcoding all music to a single directory because I, as a user, would like the transcoded music to be organized as well.

Two big issues that go against my feature suggestion are:

- The implementation and schema changes (including future maintenance) required to facilitate multiple file formats aren't worth changing compared to dealing with the current implementation of duplicate albums
- I'm possibly in the minority when it comes to wanting organized transcoded music

**Comment by sampsyo** [comment]
Yeah! I didn't mean to suggest that this general idea isn't worth pursuing; I was just asking for a little more clarification. Specifically, where do you imagine this feature manifesting itself in the UI?

For example, above, `beet ls -p` appears to behave the same way as if the different formats were treated as separate tracks. If you want different formats to share a directory, you can remove `%aunique{}` from your path formats. So what were you imagining would be different for this feature?

**Comment by twrightsman** [comment]
That's a strong point and I didn't know about the `paths` feature; perhaps the `config` plugin should be expanded to allow a user to transcode tracks and then import them into the library (as a command-line option)? If the user hasn't configured their `paths` then the plugin could give a helpful suggestion to do so, if that's appropriate.

**Comment by sampsyo** [comment]
Cool! The idea to add something to the "convert" plugin is interesting… it wouldn't be too complicated to have its newly-converted files added to the library. I'll close this issue for now, but please feel free to open another if you're interesting in pursuing that!

**Comment by pprkut** [comment]
FWIW, this sounds pretty similar to my motivation behind #1640.

**Comment by sampsyo** [comment]
Yes! That's the issue I was looking for but somehow couldn't find. Thanks, @pprkut.
