### ISSUE TITLE
convert: symlink/hardlink instead of copying files that don't need transcoding

### ISSUE THREAD

**Issue by kierdavis** [beetbox/beets#2324]
My music workflow involves creating a copy of my library in MP3 format, so that it can be uploaded to Google Play Music. The convert plugin does this brilliantly; however, since most (but not all) of my library is in MP3 format to begin with, this results in copying a lot of files. It looks like it should be fairly straightforward to allow convert to symlink or (when supported) hardlink files that don't need to be transcoded, instead of copying them. This would make the conversion process faster and the final result would generally occupy less disk space.

**Comment by sampsyo** [comment]
Sounds like a good idea; thanks!

**Comment by Vexatos** [comment]
It might be a neat idea to allow specifying a custom copy command, like
```yaml
convert:
  copy_command: ln $source $dest
```
This would allow any sort of links, including hardlinks and reflinks, if the user knows what they are doing.

**Comment by kierdavis** [comment]
Resolved by #3348

**Comment by wisp3rwind** [comment]
For the record, there's also https://github.com/geigerzaehler/beets-alternatives
