### ISSUE TITLE
Discogs plugin saves Discogs id in mb_*id tags

### ISSUE THREAD

**Issue by Freso** [beetbox/beets#2337]
See https://github.com/beetbox/beets/issues/2336

`mb_*id` tags are for MusicBrainz identifiers and a number of programs will expect MBIDs and use those MBIDs to look up additional data or for other reasons. Putting Discogs ids into the fields is wrong.

**Comment by sampsyo** [comment]
Indeed; this needs to be fixed: see #604. This is unfortunately slightly more complicated than it sounds, but it should indeed be a priority.
