### ISSUE TITLE
mutagen 1.36 breaks a flac test 

### ISSUE THREAD

**Issue by jrobeson** [beetbox/beets#2343]
```sh
======================================================================

FAIL: test_read_audio_properties (test.test_mediafile.FlacTest)

----------------------------------------------------------------------

Traceback (most recent call last):

  File "/home/travis/build/beetbox/beets/test/test_mediafile.py", line 416, in test_read_audio_properties

    self.assertEqual(getattr(mediafile, key), value)

AssertionError: 108688 != 175120
```

1.37 has been tagged, but hasn't yet appeared on pypi.  If that doesn't fix the issue, then we'll have to look a little deeper.

If it does then we'll have to somehow avoid 1.36.

**Comment by sampsyo** [comment]
Thank you for noticing this! 1.36 actually fixed bitrate calculation for FLAC, so we just need to update the test for the newly-correct value.
