### ISSUE TITLE
acousticbrainz: Ignore already tagged items

### ISSUE THREAD

**Issue by SusannaMaria** [beetbox/beets#2347]
## Feature request 
Ignore already tagged items

I really like the acousticbrainz plugin. Starting to use it for some tests with t-SNE neighbor algorithm. https://lvdmaaten.github.io/tsne/

To work with my lib, with 30.000 items, the fetching of data takes a long time, and I thought a check if the attributes like mood_acoustic are already present can improve the speed alot, after doing the process one time. The database of acousticbrainz is continuously growing and I want to check every 4 weeks if new Songs are available.

I just made a small commit, to get a first result improving my speed. It's not really meant to be serious, it's my hello world to beet after years of using it with full of joy.
https://github.com/SusannaMaria/beets/commit/f93ee3accc6673674cfc98d2a1e09afb119d3eea

**Comment by sampsyo** [comment]
Neat! I like the idea of a t-SNE visualization of music via acoustic attributes. It could be really fun to play with.

This change actually looks reasonable already! Any chance you could open a pull request?

**Comment by SusannaMaria** [comment]
Thanks! I have started a pull request. I try to learn more about how to work on plugins. Guess a force option would be necessary?!
