### ISSUE TITLE
"path" column in the database causes issue with python

### ISSUE THREAD

**Issue by Kodac** [beetbox/beets#2362]
### Problem

I'm currently working for a small music player written in python, it using beets (wonderful) database. So I have no problem accessing the database, getting the artists, getting all infos about a specific song, but I can't get the path column. If I try to use select the path column, using : 
`cursor.execute('select path from items where albumartist=(?) and album=(?) and title=(?)', (SelectedArtist, SelectedAlbum, SelectedSong))`
I get : 
 `[(<read-write buffer ptr 0x00000000038612C8, size 89 at 0x0000000003861290>,)]`

This is caused by the column name "path". I should get an output like : 
`C:\Users\*MyUsername\Music\beets\Artist\Album\Songname.flac`

### Setup

* OS: Windows 10
* Python version:  2.7
* beets version: latest

**Comment by sampsyo** [comment]
Hi! That value is stored using the SQLite "BLOB" data type, which appears to Python 2 as a [`buffer` object](https://docs.python.org/2/c-api/buffer.html). You can just use `bytes(buf)` to get a byte string out of the buffer if you need it.
