### ISSUE TITLE
Importer: option to play bell when interaction needed

### ISSUE THREAD

**Issue by nils-werner** [beetbox/beets#2366]
It would be great if beets played a terminal bell by sending `\a` to `stdout` if the autotagger requires interaction from the user.

**Comment by sampsyo** [comment]
Sounds like a reasonable idea, and not too hard to accomplish! I'm marking this as a feature request.

**Comment by SpirosChadoulos** [comment]
Greetings, 
I am thinking about putting the print(\a) command in the commands.py file.
