### ISSUE TITLE
fetchart  python3 compatibility when using itunes

### ISSUE THREAD

**Issue by PierreRust** [beetbox/beets#2371]
### Problem

This not exactly a problem on beets it-self, but when using fetchart on a python 3 installation it fails on itune import as the module used is compatible with python 3

Running this command:

```sh
 beet fetchart genre:Classical
```

Led to this problem:

```
** error loading plugin fetchart:
Traceback (most recent call last):
  File "/home/pierre/.env_beets/lib/python3.5/site-packages/beets/plugins.py", line 254, in load_plugins
    namespace = __import__(modname, None, None)
  File "/home/pierre/.env_beets/lib/python3.5/site-packages/beetsplug/fetchart.py", line 39, in <module>
    import itunes
  File "/home/pierre/.env_beets/lib/python3.5/site-packages/itunes/__init__.py", line 94
    except urllib2.HTTPError, e:
```

Of course, the best solution (and probably only solution, except patchin python-itunes) is not to use itune as a source at all. I could be enough to mention this in the documentation.

**Comment by sampsyo** [comment]
Hmm; did that traceback get cut off? Looks like we're missing the all-important last line.

And yeah, on first glance it looks like that module is not py3-compatible. We should make it an optional import (if it's not already) and add a note to the docs.

**Comment by jrobeson** [comment]
I didn't even know we imported another module. I took the list in `setup.py` for plugin deps as gospel. I guess that was wrong. :(   I guess it's time to do a search for all imports.
