### ISSUE TITLE
beet config -e does not respect update-alternatives editor

### ISSUE THREAD

**Issue by sean-abbott** [beetbox/beets#2385]
### does not respect alternatives editor

beets does not respect my chosen editor. 

sudo update-alternatives --config editor
There are 4 choices for the alternative editor (providing /usr/bin/editor).

  Selection    Path                Priority   Status
------------------------------------------------------------
  0            /bin/nano            40        auto mode
  1            /bin/ed             -100       manual mode
  2            /bin/nano            40        manual mode
* 3            /usr/bin/vim.basic   30        manual mode
  4            /usr/bin/vim.tiny    10        manual mode

But when I run

```sh
beet config -e
```
It launches gedit.

### Setup

* OS: Ubuntu 16.04
* Python version: Python 2.7.12
* beets version: beets version 1.4.3
* Turning off plugins made problem go away (yes/no): no

My configuration (output of `beet config`) is: {}

```yaml
(paste here)
```

**Comment by sampsyo** [comment]
Hi! We use the Unix standard mechanism $EDITOR in this command. Maybe you'd like to set your $EDITOR environment variable to `/usr/bin/editor`?

**Comment by sean-abbott** [comment]
yeah, bugger, that makes sense, too.  I'll update my profile. Sorry for the extraneous bug!
