### ISSUE TITLE
bpd plugin should return integer times for status command

### ISSUE THREAD

**Issue by arcresu** [beetbox/beets#2394]
Beets' bpd plugin should return integer values for the `time` field of the `status` command, and indeed this is what the code comments claim it is doing (from [gstplayer.py#L170-L188](https://github.com/beetbox/beets/blob/23e05fe0b18dac429b7dd5952fdcec85e1bd8843/beetsplug/bpd/gstplayer.py#L170-L188)):

```python
    def time(self):
        """Returns a tuple containing (position, length) where both
        values are integers in seconds. If no stream is available,
        returns (0, 0).
        """
        fmt = Gst.Format(Gst.Format.TIME)
        try:
            posq = self.player.query_position(fmt)
            if not posq[0]:
                raise QueryError("query_position failed")
            pos = posq[1] / (10 ** 9)

            lengthq = self.player.query_duration(fmt)
            if not lengthq[0]:
                raise QueryError("query_duration failed")
            length = lengthq[1] / (10 ** 9)

            self.cached_time = (pos, length)
            return (pos, length)
    # ...
```
However this file has `from __future__ import division`, and both `pos` and `length` are the result of division operations, and so neither are integers. Any clients connecting to bpd's mpd server are getting values for `status.time` like `71.165973:97.893333333`.

It turns out that most clients can cope with this just fine, but at least one crashes since it expects an integer. The mpd protocol does seem to require integers, at least that's what the reference implementation does.

**Comment by sampsyo** [comment]
Thank you for pointing this out! Looks like we forgot to update the operators when we added `from __future__ import division`. Just pushed a fix.
