### ISSUE TITLE
Enabling "auto: yes" on the chroma plugin breaks beats.ui._input() during import by trapping stdin.

### ISSUE THREAD

**Issue by sllawap** [beetbox/beets#2396]
### Problem

Enabling "auto: yes" on the chroma plugin appears to break beets.ui._input() during import.

This appears to be caused by something in the chroma plugin or pyacoustid trapping stdin in a way that prevents beets from reading user input.

Running this command:

```sh
$ beet import -g /path/to/someartist/somealbum/
```

Led to this problem:

```
Tagging:
    Some Artist - Some Album
URL:
    https://musicbrainz.org/release/xxxxxxxx
(Similarity: 83.7%) (missing tracks) (CD, 1994, US, Something Records)
Missing tracks (1/14 - 7.1%):
 ! Album (#9) (4:13)
[A]pply, More candidates, Skip, Use as-is, as Tracks, Group albums,
Enter search, enter Id, aBort, eDit, edit Candidates?
```

User input is not echoed to the terminal and pressing enter has no effect. Ctrl-C does not work and the only way to end the process is to Ctrl-\

### Setup

* OS: Debian 8.4 (in a Docker container)
* Python version: 2.7.4
* beets version: 1.4.3
* Turning off plugins made problem go away (yes/no): yes (chroma)

The problem surfaces with this configuration:

```yaml
plugins:
  chroma

chroma:
  auto: yes
```

But not with this one:

```yaml
plugins:
  chroma

chroma:
  auto: no
```

**Comment by sampsyo** [comment]
I believe this is probably https://github.com/beetbox/audioread/issues/32. Can you please make sure you have the latest version of audioread (i.e., `pip install -U audioread`)?

**Comment by kgreav** [comment]
upgrading audioread from 1.2.1 to latest (2.1.4) fixed this issue for me

**Comment by sampsyo** [comment]
Thanks!
