### ISSUE TITLE
remove [] from %aunique

### ISSUE THREAD

**Issue by diomekes** [beetbox/beets#2397]
%aunique in a path will by default add [] around the disambiguator.  If a disambiguator is found on one album but is empty on the other, then the album name will end with [].

There may be a reason to have the brackets as default, but it seems to me a better option for the user to set any characters wanted around the disambiguator string in the path format itself.

I can do a PR, but I figured it would be easier just to post here and discuss if necessary.  Here's the line of code:

https://github.com/beetbox/beets/blob/958ad430fc4854b2589ec3a2726b7ee269e5322e/beets/library.py#L1511

**Comment by sampsyo** [comment]
Sounds reasonable! How would you propose to set up the option? As an additional argument to the %aunique function?

**Comment by diomekes** [comment]
I simply meant to remove the [] from the code, and then anyone can do, for example, this in the config:

`$artist/$album[%aunique{}]/$track. $title` or `$artist/$album(%aunique{})...`

Would that work?

**Comment by sampsyo** [comment]
Alas, not quite—the reason the brackets are hard-coded is so they don't show up if no disambiguation is necessary. Those examples would put empty () and [] pairs at the end of every album directory.

**Comment by diomekes** [comment]
Of course, that's exactly what I wanted to avoid, and I made it worse!

I'll take a look and see about how to do this within the function.
