### ISSUE TITLE
mbcollection plugin is not MIT licensed

### ISSUE THREAD

**Issue by ghost** [beetbox/beets#2402]
While reading about #2400, I decided to check out Fedora's beets package and ran across the fact that mbcollection plugin is not in MIT licensed (https://github.com/beetbox/beets/blob/master/beetsplug/mbcollection.py).  We should try to get this changed to MIT.

**Comment by jrobeson** [comment]
I'm sending him an email.

**Comment by jrobeson** [comment]
docs tag?

**Comment by jrobeson** [comment]
I did email him and ask him if he'd submit a PR to change the license to MIT.

**Comment by sampsyo** [comment]
Thanks.

About the tag: I like to have a tag on every issue to indicate that it's been triaged, and this was the closest one, since it has to do with the comments on the file. Maybe a new tag like "project" or something would be more appropriate? Or perhaps "discussion"?

**Comment by jrobeson** [comment]
i'd chose legal were such a thing often necessary, but I suppose it's not worth creating a tag for. But project level stuff might be worth having a tag for. A catchall for stuff like when i suggested moving beets to it's own organization, or if we wanted to switch CI systems or the like.

**Comment by sampsyo** [comment]
Good call.

**Comment by Freso** [comment]
This was fixed with https://github.com/beetbox/beets/commit/8638157e17c74ef54bd319958151f972317be852

**Comment by sampsyo** [comment]
Lovely! Thank you!
