### ISSUE TITLE
Choosing matching media in multiple media releases during import

### ISSUE THREAD

**Issue by bearcatsandor** [beetbox/beets#2404]
There are lots of SACDs, DVD-As and mixed media releases (such as vinyl+digital) in my collection.  These releases tend to have no differentiating fields between the track properties and media+disctitle other than subtitle.

For instance, i have the 2015 release of Rush's [Roll the Bones](https://musicbrainz.org/release/930c25c7-f039-4659-bffa-34fb263320c1) which was released as vinyl with a digital download. I have the digital download in my collection but i didn't needle drop the vinyl. In some cases i have the hybrid-sacd or DVD-A of a release but i only have the surround or the CD layer (i think most people would have one or the other but not both)

 I want to import the digital download into my collection. Since the tracks are the same and the vinyl is listed first, beets assumes that i'm tagging the vinyl which results in the incorrect md_trackid, media and disctitle.

Beets could examine the track count and sum track length per media and if it were the same as the imported track count and track length, but less than the whole release automatically suggest a matching sub media or ask the user which media they wanted. The default could be weighted by the "match" configuration option.

For what it's worth, this issue is halting my library import tasks.

**Comment by bearcatsandor** [comment]
This is related to #2203 but a different issue.

**Comment by sampsyo** [comment]
Interesting idea! Can you give an example of what you think the configuration option might look like? Even some proposed documentation for the hypothetical feature, which clearly explains to users when and how to use the option, would be very helpful.

**Comment by bearcatsandor** [comment]
Would it be feasible to use something like ncurses to give the user a side-by-side list of the tracks to import on one side and the recordings for the MB entry on the other? A user could then match up tracks the way Picard does.

**Comment by sampsyo** [comment]
Hmm… the current output already sort of lines up tracks. Maybe a mockup in a text editor or something would help illustrate your idea?

**Comment by nirvdrum** [comment]
I'm running into the Hybrid SACD issue. I have the deluxe re-release of Nine Inch Nails's "The Downward Spiral". While there are only two CDs in the case, there are four layers and the [Musicbrainz listing](https://musicbrainz.org/release/79180d6f-cace-35c7-a305-9c7924faedef/edit) breaks out each layer. Beets considers each layer and then tells me I'm missing half the CD. While strictly true, I have the full album and really don't want to report it as a four disc set, since it is only two discs:

```
[A]pply, More candidates, Skip, Use as-is, as Tracks, Group albums,
Enter search, enter Id, aBort, eDit, edit Candidates? i
Enter release ID: 79180d6f-cace-35c7-a305-9c7924faedef
Correcting tags from:
    Nine Inch Nails - The Downward Spiral Deluxe Edition
To:
    Nine Inch Nails - The Downward Spiral
URL:
    https://musicbrainz.org/release/79180d6f-cace-35c7-a305-9c7924faedef
(Similarity: 58.4%) (missing tracks, mediums, album, media, year) (4xHybrid SACD (CD layer), 2004, US, Chronicles, B0003739-36, deluxe edition)
Hybrid SACD (CD layer) 1: The Downward Spiral
 * Mr. Self Destruct (#1)                   -> Mr Self Destruct (#1-1)
 * Piggy (#2)                               -> Piggy (#1-2)
 * Heresy (#3)                              -> Heresy (#1-3)
 * March Of The Pigs (#4)                   -> March of the Pigs (#1-4)
 * Closer (#5)                              -> Closer (#1-5)
 * Ruiner (#6)                              -> Ruiner (#1-6)
 * The Becoming (#7)                        -> The Becoming (#1-7)
 * I Do Not Want This (#8)                  -> I Do Not Want This (#1-8)
 * Big Man With A Gun (#9)                  -> Big Man With a Gun (#1-9)
 * A Warm Place (#10)                       -> A Warm Place (#1-10)
 * Eraser (#11)                             -> Eraser (#1-11)
 * Reptile (#12)                            -> Reptile (#1-12)
 * The Downward Spiral (#13)                -> The Downward Spiral (#1-13)
 * Hurt (#14)                               -> Hurt (#1-14)
Hybrid SACD (CD layer) 3: Remixes, B-Sides, Demos, and Non-Album Tracks
 * Burn (#2-1)                              -> Burn (#3-1)
 * Closer (Precursor) (#2-2)                -> Closer (Precursor) (#3-2)
 * Piggy (Nothing Can Stop Me Now) (#2-3)   -> Piggy (Nothing Can Stop Me Now) (#3-3)
 * A Violet Fluid (#2-4)                    -> A Violet Fluid (#3-4)
 * Dead Souls (#2-5)                        -> Dead Souls (#3-5)
 * Hurt (Quiet) (#2-6)                      -> Hurt (Quiet) (#3-6)
 * Closer to God (#2-7)                     -> Closer to God (#3-7)
 * All the Pigs, All Lined Up (#2-8)        -> All the Pigs, All Lined Up (#3-8)
 * Memorabilia (#2-9)                       -> Memorabilia (#3-9)
 * The Downward Spiral (The Bottom) (#2-10) -> The Downward Spiral (The Bottom) (#3-10)
 * Ruiner (demo) (#2-11)                    -> Ruiner (demo) (#3-11)
 * Liar (Reptile demo) (#2-12)              -> Liar (Reptile demo) (#3-12)
 * Heresy (demo) (#2-13)                    -> Heresy (demo) (#3-13)
Missing tracks (41/68 - 60.3%):
 ! Mr Self Destruct                 (#2-1) (4:30)
 ! Piggy                            (#2-2) (4:25)
 ! Heresy                           (#2-3) (3:54)
 ! March of the Pigs                (#2-4) (2:58)
 ! Closer                           (#2-5) (6:13)
 ! Ruiner                           (#2-6) (4:59)
 ! The Becoming                     (#2-7) (5:31)
 ! I Do Not Want This               (#2-8) (5:41)
 ! Big Man With a Gun               (#2-9) (1:36)
 ! A Warm Place                     (#2-10) (3:23)
 ! Eraser                           (#2-11) (4:53)
 ! Reptile                          (#2-12) (6:52)
 ! The Downward Spiral              (#2-13) (3:56)
 ! Hurt                             (#2-14) (6:17)
 ! Mr. Self Destruct (5.1 mix)      (#2-15) (4:41)
 ! Piggy (5.1 mix)                  (#2-16) (4:24)
 ! Heresy (5.1 mix)                 (#2-17) (3:54)
 ! March of the Pigs (5.1 mix)      (#2-18) (2:59)
 ! Closer (5.1 mix)                 (#2-19) (6:14)
 ! Ruiner (5.1 mix)                 (#2-20) (5:00)
 ! The Becoming (5.1 mix)           (#2-21) (5:31)
 ! I Do Not Want This (5.1 mix)     (#2-22) (5:41)
 ! Big Man With a Gun (5.1 mix)     (#2-23) (1:36)
 ! A Warm Place (5.1 mix)           (#2-24) (3:22)
 ! Eraser (5.1 mix)                 (#2-25) (4:43)
 ! Reptile (5.1 mix)                (#2-26) (6:52)
 ! The Downward Spiral (5.1 mix)    (#2-27) (3:49)
 ! Hurt (5.1 mix)                   (#2-28) (5:46)
 ! Burn                             (#4-1) (5:00)
 ! Closer (Precursor)               (#4-2) (7:16)
 ! Piggy (Nothing Can Stop Me Now)  (#4-3) (4:03)
 ! A Violet Fluid                   (#4-4) (1:04)
 ! Dead Souls                       (#4-5) (4:53)
 ! Hurt (Quiet)                     (#4-6) (5:08)
 ! Closer to God                    (#4-7) (5:05)
 ! All the Pigs, All Lined Up       (#4-8) (7:26)
 ! Memorabilia                      (#4-9) (7:22)
 ! The Downward Spiral (The Bottom) (#4-10) (7:32)
 ! Ruiner (demo)                    (#4-11) (4:51)
 ! Liar (Reptile demo)              (#4-12) (6:57)
 ! Heresy (demo)                    (#4-13) (4:00)
```

**Comment by RollingStar** [comment]
yes

**Comment by nirvdrum** [comment]
It's still an issue. To the best of my knowledge, no consensus has been reached on how to resolve it.

**Comment by bearcatsandor** [comment]
Couldn't beets look for groups of titles or look at the disc numbers, and then if the number of tracks was less than the whole of the set, ask which disc number they wanted to apply?  This could be fired off with a 'group Tracks' of  option.

**Comment by sampsyo** [comment]
That does sound possible! If someone who is interested in the feature can write up a detailed proposal for how this should work, we can mark it as a feature request to encourage folks to go implement it!

**Comment by bearcatsandor** [comment]
I might have time to come up with a proposal over my winter break.

**Comment by Adam4348** [comment]
# Tox (http://tox.testrun.org/) is a tool for running tests
# in multiple virtualenvs. This configuration file will run the
# test suite on all supported python versions. To use it, "pip install tox"
# and then run "tox" from this directory.

[tox]
envlist = py27-test, py38-{cov,lint}, docs

[_test]
deps = .[test]

[_lint]
deps = .[lint]
files = beets beetsplug beet test setup.py docs

[testenv]
deps =
    {test,cov}: {[_test]deps}
    lint: {[_lint]deps}
commands =
    test: python -bb -m pytest {posargs}
    cov: coverage run -m pytest {posargs}
    lint: python -m flake8 {posargs} {[_lint]files}

[testenv:docs]
basepython = python2.7
deps = sphinx
commands = sphinx-build -W -q -b html docs {envtmpdir}/html {posargs}

# checks all links in the docs
[testenv:links]
deps = sphinx
allowlist_externals = /bin/bash
commands = /bin/bash -c '! sphinx-build -b linkcheck docs {envtmpdir}/linkcheck | grep "broken\s"'

[testenv:int]
deps = {[_test]deps}
setenv = INTEGRATION_TEST = 1
passenv = GITHUB_ACTIONS
commands = python -bb -m pytest {posargs}

**Comment by nirvdrum** [comment]
I missed the stalebot notification, but this is still relevant.

**Comment by sampsyo** [comment]
Cool—we'd be happy to reopen it if someone wants to try drawing up a detailed proposal for how this should work.
