### ISSUE TITLE
In importer duplicate resolution prompt, option to show more detail

### ISSUE THREAD

**Issue by sean-abbott** [beetbox/beets#2416]
### Problem

When importing songs, this is what's displayed when the album is already in the library:

```sh
This album is already in the library!
Old: 1 items, MP3, 128kbps, 4:40, 4.3 MiB
New: 1 items, MP3, 128kbps, 4:55, 4.5 MiB
```

However, I obviously don't have the complete album, so I'd like to be able to see if it's the same song or not. 

ideally, in the list of options at this point, I'd like to go from 

```sh
[S]kip new, Keep both, Remove old?
```

to something like

```sh
[S]kip new, Keep both, Show Diff, Remove old?
```

**Comment by sean-abbott** [comment]
And maybe even have an option like "item by item choice"

**Comment by sampsyo** [comment]
Interesting suggestion!

What do you think should happen when you choose "show Diff"? Should it show the different wrt the current tracks, using the same alignment algorithm as the main importer, or should it just show the two side by side? Maybe it would be helpful to mock up an example output.

**Comment by EruIluvatar** [comment]
This very much!
As a beets beginner this prompt is what troubles me most. What normally happened was that beets didn't realize it was a multidisc release with improper naming e.g. 
- "album_title CD1" and "album_title CD 2"
- "album_title" and "album_title (bonus disk)"

and so on but might as well be real duplicated albums.
So we might differentiate between cases where

- the album exists twice with the same tracks => most probably a real duplicate
- the albums have missing tracks that exist in the duplicate => multidisc release that needs merging

So I would probably make sense to:
- see the tracks side by side (show Diff)
- try merging based on album title and album title (try merge) -> no idea if this is possible

**Comment by sampsyo** [comment]
Thanks for the extra detail. You might also be interested in #112, which is about merging pieces of albums.

**Comment by sean-abbott** [comment]
I think 112 more or less covers what I want, so I'll close this one and expand that.

**Comment by JOJ0** [comment]
I implemented something a while ago that is not really a "diff" but helps distinguish if a partial album is a good idea to merge/replace: https://github.com/beetbox/beets/pull/4866

HTH
