### ISSUE TITLE
EmbedArt Plugin Should Ask for Confirmation By Default

### ISSUE THREAD

**Issue by Stunner** [beetbox/beets#2420]
### Problem

This is a feature request pertaining to the embedart plugin. Sending a command to embedart doesn't return with a success or failure message. Additionally, there is no confirmation before the artwork is written to the query you have specified:

```
$ beet embedart -f path/to/artwork.jpg Fatter Than Albert
$
```

So if you made a mistake in specifying the query you risk contaminating other files with unrelated album artwork.

A `-y, --yes` flag can be added to the plugin to prevent the confirmation dialogue from appearing.

**Comment by sampsyo** [comment]
Hi! This is a good idea—so good, in fact, that we already have a ticket for it: #1999
