### ISSUE TITLE
python 3.6 64bit inport beets reg file fix

### ISSUE THREAD

**Issue by tylerhoot** [beetbox/beets#2424]
i have fixed the reg file for python 3.6 64bit installed for all users i attached the fixed file in a zip folder to allow me t attach it to this issue since im on windows and cannot push the fix.
Windows Registry Editor Version 5.00

[HKEY_CLASSES_ROOT\Directory\shell\beets]
@="Import with beets"

[HKEY_CLASSES_ROOT\Directory\shell\beets\command]
@="\"C:\\Program Files\\Python36\\Scripts\\beet.exe\" import \"%1\""

[beets-inport-python-3.6-64bit.zip](https://github.com/beetbox/beets/files/743135/beets-inport-python-3.6-64bit.zip)

**Comment by sampsyo** [comment]
Awesome; thank you for contributing this! I've committed the updated version.

**Comment by tylerhoot** [comment]
fyi this fix is for python 3.6 64bit installed for all users.

**Comment by sampsyo** [comment]
OK, thanks. If you think we should clarify that in the docs, any chance you could open a PR to that effect? (Using the in-browser GitHub editor to do so works fine.)
