### ISSUE TITLE
Beet Import Move Command

### ISSUE THREAD

**Issue by Stunner** [beetbox/beets#2425]
This is a feature request to enhance the `beet import` command to move all contents in a directory to the new location, as opposed to just the music files. I have directories of music containing album art (both front and back covers), along with miscellaneous other files (text, rtf, etc.) that contain information about lyrics or are related to the album in some way which I would like to have auto-imported to my music's new home.

I propose the following command:
```
-m, --move            move non-music files found in the import path to the new destination (works with move/copy config options)
```

**Comment by sampsyo** [comment]
Please see #111.
