### ISSUE TITLE
Embedart: Clearart Command Should Prompt Before Proceeding

### ISSUE THREAD

**Issue by Stunner** [beetbox/beets#2427]
The `beet clearart` command should prompt the user to confirm clearing art from the listed files, much like the functionality I have [added to embedart](https://github.com/beetbox/beets/pull/2422). A `-y`/`--yes` flag can be provided to skip the prompt.

**Comment by Stunner** [comment]
No. A new PR needs to be made for the clearart command.

**Comment by nathdwek** [comment]
Okay thanks. Marking this as hacktoberfest since it should be pretty straightforward.
