### ISSUE TITLE
badfiles: Continue to other files if validator command is not found or exits with an error

### ISSUE THREAD

**Issue by karpinski** [beetbox/beets#2430]
The execution exits with an error if mp3val or flac validators aren't installed. On the other hand, for extensions other than mp3 or flac which aren't included in the plugin's config, information is logged that the validator is missing and the execution moves on to checking the rest of the files.

I think this behaviour should be consistent for all extensions, also in cases when a validator is specified in the plugin's config, but it's not actually installed.

I am happy to send a PR with a fix for this!

**Comment by sampsyo** [comment]
Good call! Yes, this is definitely how it should work—it should use `self._log.error()` to produce an error message and just continue on instead of halting the whole process.

Thanks for looking into it!

**Comment by mechanic9** [comment]
This issue should be closed

**Comment by sampsyo** [comment]
Indeed; thanks!
