### ISSUE TITLE
absubmit: Analyze music in parallel

### ISSUE THREAD

**Issue by nagisa** [beetbox/beets#2442]
### Problem

Have 8 cores capable of computation. Run beet absubmit. Wait 8 times more than strictly necessary.

### Setup

* OS: Arch
* Python version: 3.6
* beets version: 1.4.3
* Turning off plugins made problem go away (yes/no): not applicable

My configuration (output of `beet config`) is: not applicable

**Comment by sampsyo** [comment]
Sounds good; thanks for the suggestion!
