### ISSUE TITLE
Set up mention-bot for beets repository

### ISSUE THREAD

**Issue by jackwilsdon** [beetbox/beets#2451]
> [Do you have a GitHub project that is too big for people to subscribe to all the notifications? The mention bot will automatically mention potential reviewers on pull requests. It helps getting faster turnaround on pull requests by involving the right people early on.](https://github.com/facebook/mention-bot)

I think it might be an idea to set up Facebook's [mention-bot](https://github.com/facebook/mention-bot) on this repository, as it would aid in working out who the best person is to sort out an issue.

It's quite simple to set up and will use the existing @mention-bot account to do all the work, all we need to do is set up a GitHub Webhook as mentioned in the bot's [How To Use](https://github.com/facebook/mention-bot#how-to-use).

**Comment by sampsyo** [comment]
Oh wow, that looks very cool! It automates a task I often do myself—either using my intuition or looking back at the "contributors" to a file to get a reminder about who's the right "expert" to defer to.

Thanks for the suggestion! I'll try setting this up and we can see how it goes.

**Comment by sampsyo** [comment]
OK, I set it up! Let's see how this goes…

**Comment by jrobeson** [comment]
this should be fun.

**Comment by jackwilsdon** [comment]
I guess we now wait for a new PR! :laughing:

**Comment by sampsyo** [comment]
Mention-bot has been working pretty well so far, but I also recently noticed suggested reviewers showing up in my sidebar on PR pages:

<img width="222" alt="screenshot 2017-04-14 09 35 35" src="https://cloud.githubusercontent.com/assets/188033/25044664/d3f9f89e-20f5-11e7-968f-875297e72058.png">

But I don't see an announcement from GitHub or anything. Is anyone else seeing these? Maybe GitHub is sherlocking mention-bot?

**Comment by jackwilsdon** [comment]
It certainly looks like they are! Hopefully they'll add an option to be notified much like how @mention-bot works.

**Comment by jackwilsdon** [comment]
I think this can be closed now 😁
