### ISSUE TITLE
Documentation and beets.reg 

### ISSUE THREAD

**Issue by mskadu** [beetbox/beets#2460]
To start with, I am a windows user looking to install beets.

This is about 
1. contents of /master/extra/beets.reg 
2. And your excellent "Getting Started" guide, subsection "Installing for Windows" ([link](http://beets.readthedocs.io/en/v1.4.3/guides/main.html#installing-on-windows)). 

### Problem
The above-mentioned doc page mentions that I need Python 2.7. I spotted a related problem with contents the beets.reg file.

1. The path in beets.reg points to the default install path of Python 3.6 - This is in contrast with your doc page which says v2.7 is required
2. Anyone choosing to import and use the tool would run into issues since they will have Python v2.7 installed.  It might be worthwhile adding a friendly warning on the doc on the lines of "you must make sure the path within beets.reg needs to be reviewed and fixed to be in line with your own install".

Also, can I ask you to re-confirm that Python v2.7 is a strict requirement for Windows install? The section titled "Installing" starts by saying "Beets works on Python 2.7 and Python 3.4 or later."

Having said all of this, and given that this is my first interaction with the creator(s?) of the tool - kudos for the what looks like an exciting tool for managing my music files. I chuckled at the bit in your video intro which says its "for obsessive compulsive geeks who care about music". And special thanks for putting this up on github.

There's nothing better (to me) than a geek with a sense of humour :)

**Comment by sampsyo** [comment]
Hey, thanks for pointing this out! Our recommended Python version is now indeed 3.6, and beets.reg does indeed assume that. Our docs were a tad out of date; I updated them now.

I also like the idea of adding a note about needing to edit the path if you have a different Python version/install directory. Is there a chance I can convince you to make the edit in `main.rst` and open a pull request? (This is as easy as hitting the "edit" button right here on GitHub.)

I'm also glad you liked the video. :smiley: It's due for an update, but we'll try to preserve the jokes as-is.

**Comment by mskadu** [comment]
I have given it a shot. And have also made some slight 3.6 related text improvements, while I was at it. Do take a look and let me know.

**Comment by sampsyo** [comment]
Addressed via #2461. Thank you!
