### ISSUE TITLE
Incorrect handling of non-ASCII file names

### ISSUE THREAD

**Issue by djl** [beetbox/beets#2470]
On Python 3 there seems to be an issue with how beets generates paths for files with non-ASCII characters.

Here's an example of some file names generated with the smartplaylist plugin:

    music/Elza Soares/A mulher do fim do mundo/01 Coração do mar.flac
    music/Elza Soares/A mulher do fim do mundo/03 Maria da Vila Matilde (Porque se a da Penha é brava, imagina a da Vila Matilde).flac
    music/Elza Soares/A mulher do fim do mundo/08 Dança.flac

And here's the same set of files as listed in mpd's database:

    music/Elza Soares/A mulher do fim do mundo/01 Coração do mar.flac
    music/Elza Soares/A mulher do fim do mundo/03 Maria da Vila Matilde (Porque se a da Penha é brava, imagina a da Vila Matilde).flac
    music/Elza Soares/A mulher do fim do mundo/08 Dança.flac

The two look very similar but all the non-ASCII characters are slightly off.

beets generates the characters `çãé` while mpd (and `ls` and everything else I checked) all output `çãé`. This is true for every non-ASCII character, not just the ones I listed here.

The `fetchart` plugin also shows the problem:

    $ beet fetchart Piñata
    Error: No such file or directory while moving /tmp/tmp16yi4dqe.jpg to /home/djl/var/links/media/music/Freddie Gibbs & Madlib/Piñata/cover.jpg

Notice I said "Piñata" but beets tried to write to a directory called "Piñata", with the imposter characters.

`beet ls -f '$path'` shows the expected characters so I suspect this only happens when beets touches the disk in some way.

### Setup

* OS: Arch Linux
* Python version: 3.6.0
* beets version: 1.4.3
* Turning off plugins made problem go away (yes/no): no
* No config file needed - this happens using the default config

The output of `locale`, just in case it matters:

    LANG=en_US.UTF-8
    LC_CTYPE=en_US.UTF-8
    LC_NUMERIC="en_US.UTF-8"
    LC_TIME="en_US.UTF-8"
    LC_COLLATE=C
    LC_MONETARY="en_US.UTF-8"
    LC_MESSAGES="en_US.UTF-8"
    LC_PAPER="en_US.UTF-8"
    LC_NAME="en_US.UTF-8"
    LC_ADDRESS="en_US.UTF-8"
    LC_TELEPHONE="en_US.UTF-8"
    LC_MEASUREMENT="en_US.UTF-8"
    LC_IDENTIFICATION="en_US.UTF-8"
    LC_ALL

**Comment by sampsyo** [comment]
Hmm… I think I might either be going insane or missing something important. All those examples above look exactly the same to me. For example:

> beets generates the characters `çãé` while mpd (and ls and everything else I checked) all output `çãé`

And:

> Notice I said "Piñata" but beets tried to write to a directory called "Piñata", with the imposter characters.

I see precisely the same string `çãé` twice in the first sentence, and the word *Piñata* twice in the second. 

Am I losing my mind? Or is GitHub dropping characters from your comment?

**Comment by Thrilleratplay** [comment]
I am not able to rerun the command at moment but I ran into this same issue last night; same version and on Arch.  

Starting with an empty library, imported my music using `beet im -A .` without any issues.  The next command I enter is `beet clearart` and it looks for UTF8 file names but if I remember correctly, I have converted all of the filenames to be ASCII.  

Sorry I cannot give more detail at the moment, but wanted to suggested that it may have to do with the art plugin or a mismatch between tag and filename.

**Comment by djl** [comment]
Bah. It looks like GitHub (or my browser) did something to my characters.

But I think I see what happened here. The library I was using was copied from OS X where UTF-8 filenames are, er, [special](https://stackoverflow.com/questions/6153345/different-utf8-encoding-in-filenames-os-x).

I'm re-importing my library from scratch to see if this solves the issue (12 hours and counting!).

**Comment by sampsyo** [comment]
Hmm, that's certainly inconvenient! I suppose the trouble stems from different (and idiosyncratic) normal forms, right?

**Comment by Thrilleratplay** [comment]
My appologies for crashing this ticket.  My issue was unrelated.  I didn't realize in my config I had move enabled.  When I then ran the clearart command, the library had the previous location.

**Comment by djl** [comment]
Yep, that was the problem after all.

There's probably a way to handle situations like this transparently but I can't imagine this is a common enough problem to justify spending time on it.
