### ISSUE TITLE
inspect.getargspec() is deprecated, use inspect.signature() instead

### ISSUE THREAD

**Issue by mbaldessari** [beetbox/beets#2474]
### Problem

When running "beet import <folder>" on a python3.5 system (Fedora 25) users get the following warning:
/usr/lib/python3.5/site-packages/beets/plugins.py:114: DeprecationWarning: inspect.getargspec() is deprecated, use inspect.signature() instead
  argspec = inspect.getargspec(func)

While it was thought that getargspec() was bound to be removed in python 3.6, this is not the case anymore: https://bugs.python.org/issue25486

So it'd be just nice to fix the warning.

### Setup

* OS: Linux / Fedora 25
* Python version: 3.5.2
* beets version: 1.4.3 (released version, but git master still has the deprecated call)

**Comment by jrobeson** [comment]
I was gonna fix this once we dropped 2.7, but perhaps we need to do it sooner.

**Comment by sampsyo** [comment]
Thanks. This is a nasty hack in any case—we should totally remove it at some point and deal with the backwards-compatibility consequences ourselves.

**Comment by jrobeson** [comment]
the simple fix though is just to use the signature object isn't it?

**Comment by sampsyo** [comment]
Yes, indeed—the quick fix is absolutely to switch to Signature.

**Comment by arcresu** [comment]
Looks like this might have been fixed recently as part of #2826

**Comment by sampsyo** [comment]
Indeed!
