### ISSUE TITLE
Beets freezes after resuming import

### ISSUE THREAD

**Issue by dosoe** [beetbox/beets#2487]
### Problem

Running this command in verbose (`-vv`) mode:

$ beet -vv import /media/windows/Users/Dorian/Musik -Cpi

Led to this problem:

[dorian@stonearch Wed Mar 22 ~]$ -> beet -vv import /media/windows/Users/Dorian/Musik/ -Cip
user configuration: /home/dorian/.config/beets/config.yaml
data directory: /home/dorian/.config/beets
plugin paths: 
Sending event: pluginload
library database: /media/windows/Users/Dorian/Musik/library.db
library directory: /media/windows/Users/Dorian/Musik
Sending event: library_opened
Sending event: import_begin
Resuming interrupted import of /media/windows/Users/Dorian/Musik
Skipping previously-imported path: /media/windows/Users/Dorian/Musik
Skipping previously-imported path: /media/windows/Users/Dorian/Musik/[anonymous]; Gester, M., Parlement de Musique, L./Manuscrit d'Uppsala 1667 - La passion selon St Matthieu
.
about 2000 directories
.
Skipping previously-imported path: /media/windows/Users/Dorian/Musik/Vaughan, S. R. and Double Trouble/Greatest Hits
Sending event: import_task_created
Sending event: import_task_start
Looking up: /media/windows/Users/Dorian/Musik/Verdi, G./The Great Operas
Tagging Giuseppe Verdi - The Great Operas
Searching for discovered album ID: 9bcd75dd-995e-482b-8ba7-1ef074d253de
Sending event: import_task_created
Sending event: import_task_created
Sending event: import_task_created
Sending event: import_task_created
Sending event: import_task_created
Candidate: Giuseppe Verdi - The Great Operas
Sending event: import_task_created
Sending event: import_task_created
Sending event: import_task_created
Sending event: import_task_created
Sending event: import_task_created
Sending event: import_task_created
Sending event: import_task_created
Sending event: import_task_created
Sending event: import_task_created
Sending event: import_task_created
Sending event: import_task_created
Sending event: import_task_created
Sending event: import_task_created
Sending event: import_task_created
Sending event: import_task_created
Sending event: import_task_created
Sending event: import_task_created
Sending event: import_task_created
Sending event: import_task_created
Sending event: import_task_created
Sending event: import_task_created
Sending event: import_task_created
Sending event: import_task_created
Sending event: import_task_created
Skipped 1076 paths.
Success. Distance: 0.01
Album ID match recommendation is Recommendation.medium
Search terms: Giuseppe Verdi - The Great Operas
Album might be VA: False
Sending event: albuminfo_received
Candidate: Giuseppe Verdi - The Great Operas
Duplicate.
Sending event: albuminfo_received
Candidate: Giuseppe Verdi - The Great Operas

and he stays there for hours. I already had a similar problem with other music, but it finally got imported. I don't know what the 1076 paths could be. It is not the number of remaining folders (31) nor the number of remaining files (about 2000) nor the number of files in this specific album (736). 

The release that seems to block him is this one: 
https://musicbrainz.org/release/9bcd75dd-995e-482b-8ba7-1ef074d253de

Here's a link to the music files that trigger the bug (if relevant): 
(How can I upload files?)

### Setup

* OS: Arch Linux
* Python version: 3.6.0
* beets version: 1.4.3
* Turning off plugins made problem go away (yes/no): no

My configuration (output of `beet config`) is:

directory: /media/windows/Users/Dorian/Musik
library: /media/windows/Users/Dorian/Musik/library.db

import:
    copy: no
    write: no

**Comment by dosoe** [comment]
The cpu is still working, according to htop (~100% cpu load for the process on htop)

**Comment by sampsyo** [comment]
Any ideas about how we might reproduce this? Does it happen if you just import the offending album?

**Comment by dosoe** [comment]
Yes, he takes a lot of time (about 1 min for just one release, 35CDs). 
Right now he's stuck there: 


[dorian@stonearch Wed Mar 22 ~]$ -> beet -vv import /media/windows/Users/Dorian/Musik/Verdi\,\ G./ -Cip
user configuration: /home/dorian/.config/beets/config.yaml
data directory: /home/dorian/.config/beets
plugin paths: 
Sending event: pluginload
library database: /media/windows/Users/Dorian/Musik/library.db
library directory: /media/windows/Users/Dorian/Musik
Sending event: library_opened
Sending event: import_begin
Sending event: import_task_created
Sending event: import_task_start
Looking up: /media/windows/Users/Dorian/Musik/Verdi, G./The Great Operas
Tagging Giuseppe Verdi - The Great Operas
Searching for discovered album ID: 9bcd75dd-995e-482b-8ba7-1ef074d253de
Candidate: Giuseppe Verdi - The Great Operas
Success. Distance: 0.01
Album ID match recommendation is Recommendation.medium
Search terms: Giuseppe Verdi - The Great Operas
Album might be VA: False
Sending event: albuminfo_received
Candidate: Giuseppe Verdi - The Great Operas
Duplicate.
Sending event: albuminfo_received
Candidate: Giuseppe Verdi - The Great Operas

I'm puzzled about the "Duplicate", did he actually manage to import it before I canceled the previous run (after 3 hours) and then why didn't he go on in any way?
Gonna upload the culprit, but it's a 8 GB folder so it might take some time to upload. 
Thanks for the quick reaction!

**Comment by dosoe** [comment]
update: running since 5 min on the same album, still no progress.

**Comment by dosoe** [comment]
[1-Anch'io dischiuso un giorno (Abigaille).zip](https://github.com/beetbox/beets/files/862331/1-Anch.io.dischiuso.un.giorno.Abigaille.zip)

**Comment by dosoe** [comment]
a random track from the release

**Comment by sampsyo** [comment]
Aha—since this is a very large release, I think it's running up against scalability issues in the beets matching algorithm. There's more detail in #2446, but I believe the bottleneck is just the assignment of candidate tracks to actual tracks. If it's possible to track down exactly where all the time is going, this is clearly a worthy target for optimization…

**Comment by dosoe** [comment]
is that a problem only if I also have a big number of recordings or only if the release is itself very big? 
Does it help if the tracks are well numbered?

**Comment by dosoe** [comment]
Is there a way to deal with it? I still would like to import this release.

**Comment by sampsyo** [comment]
> is that a problem only if I also have a big number of recordings or only if the release is itself very big?

I'm not sure. Answering this question might be a good first step to understanding the problem!

> Does it help if the tracks are well numbered?

Also not sure, but probably not.

> Is there a way to deal with it? I still would like to import this release.

I don't have a workaround to suggest. But helping to pin down the precise problem would help with a longer-term solution!

**Comment by dosoe** [comment]
I have two other pieces of information that might help for that: 
Now that I think about it, I have a few other releases that are of comparable size (a complete edition of bach cantatas and a complete edition of bach's music) that were imported without any problem that I can remember. Therefore I think that both a high number of tracks on the release and a high number of actually present recordings are required for this problem to rise. 
Another strange problem I had is when I added a folder with a release with 2 CDs, where only one was present but it was there twice. beets tried to match the dupes with tracks of the missing CD instead of recognizing that they were actually dupes and fitted much better the already present tracks. 
To me this is actually a pretty serious issue. It means that beets will not see that obviously, a track is there twice (in my case with identical filenames and identical tags provided by musicbrainz picard). He will only try to match a recording with the missing tracks. In this case it was not problematic, because the match was bad and got signalled, but maybe I missed one. 
Maybe to avoid this I should run in singleton mode, or is there a plugin to help for that?

What this makes me say is that beets takes all the recordings and tries to find the best repartition of the recordings over the tracklist. For a release with 35 CDs, there are a lot of possibilities to try out so it's taking a stupidly long time. Trying to lok at tags like track number could drastically reduce the number of possibilities, but I guess it's already implemented (I don't know a lot about beets, I'm just discovering it).

**Comment by sampsyo** [comment]
Cases like the above, where beets has no choice but to create a fairly bad match, are impossible to avoid in general. You're right that, to a human, the problem is obvious, but it's intractable to encode all of human intuition into the beets autotagger. Fortunately, our scoring mechanism will score this kind of problem as a bad match, which means you get to intervene.

Back on the original topic, which is very large releases: would you mind continuing the discussion on #2446? The right next step is to look more closely about exactly what part of the code is taking so much time.
