### ISSUE TITLE
Regression in play plugin: no CLI output on succesful play.

### ISSUE THREAD

**Issue by nathdwek** [beetbox/beets#2490]
It seems 8d972576 and friends have introduced a small regression in the play plugin: there is no output anymore on successful play indicating the number of tracks queued. This does not seem to be desired, as there is still this snippet left in the code:
```python
# Print number of tracks or albums to be played, log command to be run.
item_type += 's' if len(selection) > 1 else ''
ui.print_(u'Playing {0} {1}.'.format(len(selection), item_type))
log.debug(u'executing command: {} {!r}', command_str, open_args)
```

I suppose the weird `ui.print_` (as opposed to use the dedicated logger) lost in there is responsible for this.

@diomekes: would it be possible for you to parse this section real quick to see what was the intention here and if there is indeed a quick fix?

Repro:
```
beets version 1.4.4
Python version 3.5.2+
plugins: chroma, convert, discogs, duplicates, embedart, fetchart, info, missing, play, random, zero
```
Ubuntu 16.10

**Comment by diomekes** [comment]
This is the output I get when exceeding the threshold:

`You are about to queue 704 track.`
`[C]ontinue, Abort?`
`Playing 704 tracks.`

@nathdwek, you don't get this output?

For what it's worth, that code you pasted was already part of the plugin, I just moved it to it's current position as part of the refactoring to add the importer prompt.

**Comment by sampsyo** [comment]
That is odd—I don't quite see why `ui.print_` wouldn't show up. (It will, FWIW, go to stdout instead of stderr, but I doubt that's the problem.)

That "you are about to queue 704 track" grammar though… we should certainly do something about that.

**Comment by nathdwek** [comment]
Woops: I fixed the content but not the title of the opening post.
* The warning certainly works!
* The plural issue was recently fixed in  920784a
* The only remaining issue is that when there is not warning, there is no output at all.

**Comment by diomekes** [comment]
I'm still confused.  If my query plays 3 albums, it says:
`Playing 3 albums.`

If it plays 13 tracks, it says:
`Playing 13 tracks.`

Could you maybe post your command and the output, or lack of output?

**Comment by nathdwek** [comment]
```
nathdwek@nathome:~[home]$ beet -vv play love in the dark
user configuration: /home/nathdwek/.config/beets/config.yaml
data directory: /home/nathdwek/.config/beets
plugin paths: 
Sending event: pluginload
library database: /home/nathdwek/.beets.db
library directory: /home/nathdwek/music/beetsdir
Sending event: library_opened
play: executing command: ds vlc --one-instance --playlist-enqueue --started-from-file -ZL [b'/home/nathdwek/music/beetsdir/Adele/25/08 Love in the Dark.flac']
```

**Comment by diomekes** [comment]
Very strange.  The only difference I can see is that I'm using Python 3.6, but I don't think that's it.

I thought it might be something with your command (I don't know what `ds` is) maybe eating the output, but the info message comes before the execution and even before the debug message.  I tried `vlc` and it worked for me, but, once again, I don't know what `ds` is.

**Comment by nathdwek** [comment]
I'll check on 3.6 asap. I'll use deadsnakes since ubuntu only ships 3.6b2 for the moment.

As far as `ui.print_` is concerned, AFAIK it is only a wrapper around print to handle the differences in error and encoding management across python2/3. What I think it lacks compared to the `logging` module (I can't remember if we have a slightly modified version (I think there are only very minor changes IIRC) or if the vanilla version is used) is:
* verbosity and stdout/stderr management
* logging on a per module management
* easy redirections for debug/testing

Still though, it doesn't change the fact that this bug is a little weird and certainly not expected!

**Comment by sampsyo** [comment]
Well, that's very strange! Just to check, it's this line that doesn't seem to be doing anything, but does if you swap it out for a `log.info`?

```py
ui.print_(u'Playing {0} {1}.'.format(len(selection), item_type))
```

Does it happen to work if you use a "real" print() call? How about if you slip in a `return` just after that to bypass the actual invocation of the player command? If both of those work, the problem is probably buffer flushing, and therefore related to 5233e0fc. That commit is #2398, which dealt with Python 3 encoding sadness by using `write` directly on the underlying `stdout` buffer. I'm guessing that we need a `sys.stdout.buffer.flush()` after the `sys.stdout.buffer.write`.

**Comment by sampsyo** [comment]
Opened a pull request with that change in #2496 to see how it goes.

**Comment by nathdwek** [comment]
I'll try these out as soon as I can

**Comment by nathdwek** [comment]
@sampsyo It seems to be definitely buffer flushing. First of all using `print` instead of `ui.print_` displays the message, but more importantly, using this
```python
    ui.print_(u'Playing {0} {1}.'.format(len(selection), item_type))
    log.debug(u'executing command: {} {!r}', command_str, open_args)
    return
```
gives this:
```
debug message: executing command ....
Playing n tracks
```
So it seems that the `ui.print_` message indeed waits for the return to display.

**Comment by sampsyo** [comment]
Got it; thanks! I'll merge #2496 now, which should do the trick.
