### ISSUE TITLE
Win10: Beets should send trashed files to recycle bin, not instantly delete them

### ISSUE THREAD

**Issue by RollingStar** [beetbox/beets#2492]
### Problem

Run beet import on an album that's already in the library. Say Remove old. The old files are instantly deleted, not sent to the recycle bin. Recycle-binning deleted files is typical behavior; I can't think of any Windows program that doesn't do this for user-facing files.

I don't know how beets operates on Linux.

Alternatively, a user-designated "Trash" folder in the library could be specified, but that's more complicated.
 (See: [duplicates plugin](https://beets.readthedocs.io/en/v1.4.3/plugins/duplicates.html?highlight=trash))

**Comment by sampsyo** [comment]
Could you please add your thoughts to #149, which describes a similar idea?

**Comment by RollingStar** [comment]
Sorry about that. I tried searching and didn't see it.
