### ISSUE TITLE
Import of a multidisc release is broken if it has subdirectories

### ISSUE THREAD

**Issue by antlarr** [beetbox/beets#2493]
### Problem

I have a directory structure like:
```
/music/artist/album/CD1/*.mp3
/music/artist/album/CD1/info/*.txt
/music/artist/album/CD1/covers/*.jpg
/music/artist/album/CD2/*.mp3
/music/artist/album/CD2/info/*.txt
/music/artist/album/CD2/covers/*.jpg
/music/artist/album/CD3/*.mp3
/music/artist/album/CD3/info/*.txt
/music/artist/album/CD3/covers/*.jpg
```

When importing such a directory structure with beets, the importer doesn't 
collapse the paths since it has subdirectories that "break" the pattern matching.
All the contents of CD1/CD2/CD3 directories should be colllapsed into the same release, as [the documentation says](http://beets.readthedocs.io/en/v1.3.17/guides/tagger.html#overview) :

```
First, directories that look like separate parts of a multi-disc album are tagged
together as a single release. If two adjacent albums have a common prefix,
followed by “disc,” “disk,” or “CD” and then a number, they are tagged together.
```

### Setup

* OS:  openSUSE Tumbleweed
* Python version: 3.6
* beets version: git master

**Comment by sampsyo** [comment]
Agreed; I can't see any reason not to collapse those paths with subdirectories. Maybe it would be nice to avoid collapsing if those subdirectories also contain music? I'm not certain—perhaps that will never be a problem.
