### ISSUE TITLE
modify: Field deletion (foo!) should work for fixed attributes by setting them to null

### ISSUE THREAD

**Issue by flesk** [beetbox/beets#2497]
### Problem

`foo!` works if foo is a flexible field, but it doesn't do anything if it's a fixed attribute.

Example from IRC Chat:

User not able to delete/reset artpath: to "None" as modify only results in artpath being the current working directory: 

```sh
# beet modify -a 2cellos artpath!
Modifying 1 albums.
No changes to make.
# beet modify -a 2cellos artpath=''
Modifying 1 albums. 
2CELLOS - 2Cellos
  artpath: /media/music/processed/2CELLOS/2011 - 2Cellos/cover.jpg -> /root  
Really modify, move and write tags? (Yes/no/select) n 
```

Led to this problem:

```
artpath: /media/music/processed/2CELLOS/2011 - 2Cellos/cover.jpg -> /root  
```
should be:
```
artpath: /media/music/processed/2CELLOS/2011 - 2Cellos/cover.jpg -> None
```
### Setup

* OS: Linux bedmoode 4.4.30-v7+ #919 SMP Tue Nov 1 16:57:28 GMT 2016 armv7l GNU/Linux 
* Python version: Python 3.4.2
* beets version: beets version 1.4.4
* Turning off plugins made problem go away (yes/no): no

**Comment by sampsyo** [comment]
Thanks! All attributes (including fixed attributes) have a null value. We should just use that when using `beet modify foo!`.

**Comment by camsteffen** [comment]
It seems confusing to me that it says "Modifying 1 albums" and then "No changes to make". Is this a bug?

**Comment by sampsyo** [comment]
That is odd! But perhaps it’s the case that your query marched one album but the new field value was equal to the old field value? That would explain it.

**Comment by camsteffen** [comment]
I think it happens any time you use `field!` on an inflexible field

**Comment by sampsyo** [comment]
Ah, indeed, because we currently don’t actually change anything when that happens. So the bug is this one, I’d say!
