### ISSUE TITLE
Import: Remove old removes an album if importing an album already in a library

### ISSUE THREAD

**Issue by RollingStar** [beetbox/beets#2499]
### Problem

Another silly one. Not a high priority by any means. I can try reproducing it with -vv enabled but it should be self explanatory. This is either a beets bug or a documentation clarity bug. Would this have worked if I pointed it at my global beets library folder rather than a subfolder for one album?

https://beets.readthedocs.io/en/v1.4.3/reference/cli.html#reimporting

>Just point the beet import command at a directory of files that are already catalogged in your library. Beets will automatically detect this situation and avoid duplicating any items.

In my case, "removing old" actually deleted the only copy of the file.

Expected behavior:

* if the new and old albums are the exact same files in the exact same spot on disk, just import the new (according to the current user path config)
* don't prompt in this case, or make a different prompt rather than the "old/new" setup, because importing the new is implicitly changing the old

Running this command in (non)verbose mode:

```sh
beet import "\Alan Menken - 1989 - The Little Mermaid (1997 CD) [96kbps MP3]"

\Alan Menken - 1989 - The Little Mermaid (1997 CD) [96kbps MP3] (1 items)
Tagging:
    Alan Menken - The Little Mermaid
URL:
    https://musicbrainz.org/release/eea4bcaa-f35e-3a7e-8d50-d6f7f1b4f17f
(Similarity: 51.3%) (missing tracks) (CD, 1997, US, Walt Disney Records, 1989 film soundtrack)
Missing tracks (19/20 - 95.0%):
 ! Fathoms Below (#1) (1:41)
 ! Main Titles (#2) (1:26)
 ! Fanfare (#3) (0:30)
 ! Daughters of Triton (#4) (0:40)
 ! Part of Your World (#5) (3:15)
 ! Part of Your World (reprise) (#7) (2:18)
 ! Poor Unfortunate Souls (#8) (4:51)
 ! Les Poissons (#9) (1:36)
 ! Kiss the Girl (#10) (2:43)
 ! Fireworks (#11) (0:38)
 ! Jig (#12) (1:34)
 ! The Storm (#13) (3:20)
 ! Destruction of the Grotto (#14) (1:55)
 ! Flotsam and Jetsam (#15) (1:25)
 ! Tour of the Kingdom (#16) (1:27)
 ! Bedtime (#17) (1:23)
 ! Wedding Announcement (#18) (2:19)
 ! Eric to the Rescue (#19) (3:43)
 ! Happy Ending (#20) (3:11)
[A]pply, More candidates, Skip, Use as-is, as Tracks, Group albums,
Enter search, enter Id, aBort?
This album is already in the library!
Old: 1 items, MP3, 96kbps, 3:16, 2.3 MiB
New: 1 items, MP3, 96kbps, 3:16, 2.3 MiB
[S]kip new, Keep both, Remove old? r
Error: No such file or directory while moving \\?\\Alan Menken - 1989 - The Little Mermaid (1997 CD) [96kbps MP3]\06. Under the Sea.mp3 to \\?\\Alan Menken - 1989 - The Little Mermaid (1997) [96kbps MP3]\06. Under the Sea.mp3
```

**Comment by sampsyo** [comment]
Hi! I think this is an instance of #702, which I consider a pretty nasty bug. Can you check whether this sounds like the same thing?

**Comment by RollingStar** [comment]
It's very similar. In this case, I passed a path to the beets importer that should have been exactly in the library! The path \library\Alan Menken - 1989 - The Little Mermaid (1997 CD) [96kbps MP3] was part of my library and beets didn't recognize this. Does it only work on the top-level \library\ path when attempting a re-import? If you have ideas on how to test this, I'm willing to try them.

Unpredictable bugs cause files to deleted that shouldn't be. This helps build the case for an intermediate trash folder (or OS-level trash handling) like #149. Those bugs go from "nasty" to "annoying" once files aren't obliterated instantly by beets.

**Comment by sampsyo** [comment]
No, re-imports should work fine even when you specify a specific path. Can you tell from the verbose output whether the new file is actually exactly the same file as the old one? If so, then not detecting that fact is a bug.

**Comment by RollingStar** [comment]
I don't have the file anymore because it got deleted but I will try reproducing it with verbose.

**Comment by dbogdanov** [comment]
This happened to me as well: 
```
This album is already in the library!
Old: 4 items, FLAC, 825kbps, 24:34, 146.2 MiB
New: 4 items, FLAC, 825kbps, 24:34, 146.2 MiB
[S]kip new, Keep both, Remove old, Merge all? r
Error: No such file or directory while moving ... 
```
Perhaps,  removing old files is done before importing the new ones (which are the same), so that they get lost on the way?

**Comment by RollingStar** [comment]
yes, could be mitigated with more forgiving trashcan functionality
