### ISSUE TITLE
Use preferred country to select release event within each release

### ISSUE THREAD

**Issue by djl** [beetbox/beets#2501]
When manually selecting a release during import (e.g. by using the MusicBrainz ID or via search) that contains multiple countries, it seems like preferred countries are ignored in favor of the first country in the list.

For example, in [this release](https://musicbrainz.org/release/f7304df7-2e3d-461a-b05f-442d330c1bf6) there are multiple countries. With the following config the preferred countries are ignored and Canada is selected instead:

    match:
      preferred:
        countries: ['XW', 'US', 'GB', 'XE']

The same also happens if you call `mbsync` and the country has been updated.

Should the importer also handle selecting preferred metadata when multiple options are available? Does it handle this already and I'm just doing it wrong?

**Comment by sampsyo** [comment]
Hmm… I think I'm a little confused. The `preferred.countries` option (and all the `preferred` things) are ways to make beets choose *between* releases. They are powerless to help if you tell beets a *specific* release—then there's no ranking to be done. Did you mean to choose between the two releases in the relevant [release group](https://musicbrainz.org/release-group/5a35595d-05c5-48df-bbd1-777aac538ae2)?

**Comment by djl** [comment]
That may have been a confusing explanation because I mentioned that it happens when manually selecting a release. It turns out that it doesn't matter how the release was selected.

I know (now) that beets only uses `preferred.countries` when selecting releases. It's surprising that it doesn't then use a preferred country for selecting a release event.

Imagine an album in MusicBrainz that has multiple release events for different countries each with a different release date. If your preferred country doesn't happen to come first alphabetically, the wrong release event will be chosen and your database will contain incorrect information.

In my case `CA` is **not** in my `preferred.countries` but beets has chosen it to store in the DB over `US`:

    $ beet ls -a -f '$albumartist - $album - $country' Orphée
    Jóhann Jóhannsson - Orphée - CA

Is that slightly clearer?

**Comment by sampsyo** [comment]
Yeah, thanks! It looks like beets' module for interacting with MusicBrainz dates to a time when there was only one release country (and only one release event). We naively just get "the country" for a release, which turns out to be the first alphabetically. Clearly, we should be fetching the complete list of release countries for every release, and you're right that this setting should probably control that.
