### ISSUE TITLE
beet lyric plugin ends with "urllib2.HTTPError: HTTP Error 403: Forbidden"

### ISSUE THREAD

**Issue by avma** [beetbox/beets#2507]
### Problem

hi

while running beet lyrics, after about 5 minutes, it stops with "urllib2.HTTPError: HTTP Error 403: Forbidden" without completing a full scan of my files

Running this command in verbose (`-vv`) mode:
$ beet -vv lyrics
pi@RASPI3-DELUGE:~ $ beet lyrics
Traceback (most recent call last):
  File "/usr/local/bin/beet", line 9, in <module>
    load_entry_point('beets==1.4.3', 'console_scripts', 'beet')()
  File "/usr/local/lib/python2.7/dist-packages/beets/ui/__init__.py", line 1209, in main
    _raw_main(args)
  File "/usr/local/lib/python2.7/dist-packages/beets/ui/__init__.py", line 1196, in _raw_main
    subcommand.func(lib, suboptions, subargs)
  File "/usr/local/lib/python2.7/dist-packages/beetsplug/lyrics.py", line 692, in func
    opts.force_refetch or self.config['force'],
  File "/usr/local/lib/python2.7/dist-packages/beetsplug/lyrics.py", line 718, in fetch_item_lyrics
    lyrics = [self.get_lyrics(artist, title) for title in titles]
  File "/usr/local/lib/python2.7/dist-packages/beetsplug/lyrics.py", line 751, in get_lyrics
    lyrics = backend.fetch(artist, title)
  File "/usr/local/lib/python2.7/dist-packages/beetsplug/lyrics.py", line 566, in fetch
    data = urllib.request.urlopen(url)
  File "/usr/lib/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python2.7/urllib2.py", line 437, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 550, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 475, in error
    return self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 558, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
urllib2.HTTPError: HTTP Error 403: Forbidden
pi@RASPI3-DELUGE:~ $

Led to this problem:

```
lyrics: lyrics not found: Scott Bradlee - Mashups by Candlelight, Volume Two - S                                                                                                                                                             tepping Out Night and Day
lyrics: lyrics not found: Scott Bradlee - Mashups by Candlelight, Volume Two - G                                                                                                                                                             ame of Thrones Piano Improvisation
lyrics: lyrics not found: Brenda Boykin  - NINE -  Hard Swing Travellin' Man (Cl                                                                                                                                                             ub Des Belugas remix)
Traceback (most recent call last):
  File "/usr/local/bin/beet", line 9, in <module>
    load_entry_point('beets==1.4.3', 'console_scripts', 'beet')()
  File "/usr/local/lib/python2.7/dist-packages/beets/ui/__init__.py", line 1209,                                                                                                                                                              in main
    _raw_main(args)
  File "/usr/local/lib/python2.7/dist-packages/beets/ui/__init__.py", line 1196,                                                                                                                                                              in _raw_main
    subcommand.func(lib, suboptions, subargs)
  File "/usr/local/lib/python2.7/dist-packages/beetsplug/lyrics.py", line 692, i                                                                                                                                                             n func
    opts.force_refetch or self.config['force'],
  File "/usr/local/lib/python2.7/dist-packages/beetsplug/lyrics.py", line 718, i                                                                                                                                                             n fetch_item_lyrics
    lyrics = [self.get_lyrics(artist, title) for title in titles]
  File "/usr/local/lib/python2.7/dist-packages/beetsplug/lyrics.py", line 751, i                                                                                                                                                             n get_lyrics
    lyrics = backend.fetch(artist, title)
  File "/usr/local/lib/python2.7/dist-packages/beetsplug/lyrics.py", line 566, i                                                                                                                                                             n fetch
    data = urllib.request.urlopen(url)
  File "/usr/lib/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python2.7/urllib2.py", line 437, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 550, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 475, in error
    return self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 558, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
urllib2.HTTPError: HTTP Error 403: Forbidden
```

Here's a link to the music files that trigger the bug (if relevant): 

### Setup

* OS: Raspbian GNU/Linux 8 (jessie)
* Python version: 2.7.9
* beets version: 1.4.3
* Turning off plugins made problem go away (yes/no): 

My configuration (output of `beet config`) is:

```yaml
# Beets configuration --------------------------------------------------------

directory: /mnt/media/music/mymusic
library:   /mnt/media/data/beets.blb
import:
    # write metadata to music files
    write: yes

    # move imported files from source to the music directory
    move: yes
    copy: no
    delete: no

    # use auto-tagging where possible
    # do not require confirmation on strong matches
    autotag: yes
    timid: no

    resume: ask
    incremental: no
    none_rec_action: ask
    log:

    quiet: no  # enable with command line option
    quiet_fallback: skip
    default_action: apply

    singletons: no
    languages: []
    detail: no
    flat: no

# use the release-date of the original (first) release of an album?
original_date: no

# on multi-disk releases, assign track numbers for the whole album.
# If "per disk", make sure tracknames do not collide ("paths" setting).
per_disc_numbering: no

# files matching these patterns are deleted from source after import
clutter: ["Thumbs.DB", ".DS_Store", "*.m3u", "*.m3u8", ".pls", "*.jpg"]

# files/directories matching one of these patterns are ignored during import
ignore: [".*", "*~", "System Volume Information"]


# Paths ----------------------------------------------------------------------

# Paths and filenames for music files
# relative to music directory
paths:
    default: %asciify{$albumartist}/%asciify{$album}%aunique{}/$track. %asciify{$title}
    singleton: Non-Album/%asciify{$artist}/%asciify{$title}
    comp: Compilations/%asciify{$album}%aunique{}/$track. %asciify{$title}
replace:
    '[\\/]': _
    '^\.': _
    '[\x00-\x1f]': _
    '[<>:"\?\*\|]': _
    '\.$': _
    '\s+$': ''

path_sep_replace: _

# filename for the album art
art_filename: cover  # results in "cover.jpg"
max_filename_length: 0  # unlimited

# General --------------------------------------------------------------------

# use mutliple threads during import
threaded: yes
timeout: 5.0
verbose: no


# User Interface -------------------------------------------------------------

color: yes
list_format_item: %upper{$artist} - $album - $track. $title
list_format_album: %upper{$albumartist} - $album
time_format: '%d-%m-%Y %H:%M:%S'
terminal_encoding: utf8

ui:
    terminal_width: 80
    length_diff_thresh: 10.0

# Auto Tagger ----------------------------------------------------------------

match:
    strong_rec_thresh: 0.1      # match 90% or better for auto import
    medium_rec_thresh: 0.25
    rec_gap_thresh: 0.25
    max_rec:
        missing_tracks: medium
        unmatched_tracks: medium
    distance_weights:
        source: 2.0
        artist: 3.0
        album: 3.0
        media: 1.0
        mediums: 1.0
        year: 1.0
        country: 0.5
        label: 0.5
        catalognum: 0.5
        albumdisambig: 0.5
        album_id: 5.0
        tracks: 2.0
        missing_tracks: 0.9
        unmatched_tracks: 0.6
    #mpdstats,
    missing,
    duplicates,
    copyartifacts,
    lastimport,
    importadded,
    web
]
pluginpath: []

# Plugins Config -------------------------------------------------------------

lyrics:
    auto: yes
    import.wrire: yes
    fallback: ''
    sources: google lyricwiki lyrics.com musixmatch genius.com
    google_API_key: XXX

echonest_tempo:
    auto: yes

lastgenre:
    auto: yes
    whitelist: yes   # ~/.config/beets/genres.txt
    canoncical: yes  #~/.config/beets/genres-tree.yaml
    fallback: ''
    source: album    #artist track
    separator: '/'

fetchart:
    auto: yes
    #maxwidth: 300
    cautious: true
    cover_names: cover folder back cd artist fold inside inlay booklet

embedart:
    auto: yes
    #maxwidth: 300

replaygain:
    auto: yes
    overwrite: yes
    albumgain: yes

scrub:
    auto: yes

copyartifacts:
    extensions: .*

# required for mpdstats
#mpd:
 #   host: localhost
 #   port: 6600
 #   password:  # none

#mpdstats:
    #rating: False
    # two ratings are calculated:
    # "rolling" based on recent development
    # "stable" based on all-time development
    # rating mix 0.0 is all "rolling", 1.0 is all "stable"
    #rating_mix: 0.75

missing:
    format: $albumartist - $album - $track - $title
    count: yes
    total: yes

duplicates:
    checksum: no  # expensive

lastfm:
    user: avma

importadded:
    preserve_mtimes: yes
    preserve_write_mtimes: yes

web:
    host: 0.0.0.0

```

**Comment by jackwilsdon** [comment]
It looks like you may be using an old version of the lyrics plugin, as line [566](https://github.com/beetbox/beets/blob/master/beetsplug/lyrics.py#L566) doesn't match the backtrace you have provided. Could you provide the contents of `/usr/local/lib/python2.7/dist-packages/beetsplug/lyrics.py`?

**Comment by sampsyo** [comment]
Thanks, @jackwilsdon!

**Comment by avma** [comment]
this is what i have:
# -*- coding: utf-8 -*-
# This file is part of beets.
# Copyright 2016, Adrian Sampson.
#
# Permission is hereby granted, free of charge, to any person obtaining
# a copy of this software and associated documentation files (the
# "Software"), to deal in the Software without restriction, including
# without limitation the rights to use, copy, modify, merge, publish,
# distribute, sublicense, and/or sell copies of the Software, and to
# permit persons to whom the Software is furnished to do so, subject to
# the following conditions:
#
# The above copyright notice and this permission notice shall be
# included in all copies or substantial portions of the Software.

"""Fetches, embeds, and displays lyrics.
"""

from __future__ import absolute_import, division, print_function

import difflib
import itertools
import json
import re
import requests
import unicodedata
import warnings
import six
from six.moves import urllib

try:
    from bs4 import SoupStrainer, BeautifulSoup
    HAS_BEAUTIFUL_SOUP = True
except ImportError:
    HAS_BEAUTIFUL_SOUP = False

try:
    import langdetect
    HAS_LANGDETECT = True
except ImportError:
    HAS_LANGDETECT = False

try:
    # PY3: HTMLParseError was removed in 3.5 as strict mode
    # was deprecated in 3.3.
    # https://docs.python.org/3.3/library/html.parser.html
    from six.moves.html_parser import HTMLParseError
except ImportError:
    class HTMLParseError(Exception):
        pass

from beets import plugins
from beets import ui
import beets


DIV_RE = re.compile(r'<(/?)div>?', re.I)
COMMENT_RE = re.compile(r'', re.S)

**Comment by avma** [comment]
although when i tried to update request, i'm getting:Requirement already satisfied: "requests in /usr/local/lib/python2.7/dist-packages"

**Comment by jackwilsdon** [comment]
You need to update beets itself to the Git version or just disable the `google` lyrics source until a new version of beets comes out (which I'd recommend doing instead of using the Git version).

**Comment by avma** [comment]
i did that too (ran  "sudo pip install -U beets" and it saya: Requirement already up-to-date)...
is there a way to remove and reinstall lyrics.py? 
i did try to manually edit lyrics.py as suggested in the  #2437 fix, but then started getting more(other) errors

**Comment by sampsyo** [comment]
Did you take a look at the FAQ entry @jackwilsdon referred to above? It shows how to run from source: http://beets.readthedocs.io/en/latest/faq.html

Or, we'll do an official release very soon!

**Comment by avma** [comment]
thanks a lot...
yes i did, i think i'll just wait for the new release, for now i just commented out the google_api_key.
