### ISSUE TITLE
Case conversion on import / tag for specific field.

### ISSUE THREAD

**Issue by exislow** [beetbox/beets#2533]
Is it possible to get case conversion to `UPPERCASE` for a specific field on import / autotag?

My problem is like this: 

I use Serato DJ and need amongst others the `key` information of a song. If I `import` audio files in with `beets` it can look up the `key` information from various sources, e.g. `MusicBrainz`.

`MusicBrainz` returns the `key` information in lowercase style, e.g. `8a`. But it should be either UPPERCASE, e.g. `8A` (Mixed in Key Format) , or the the musical notation, e.g. `Am` (in latter case it should be NOT `uppercase`, because `Serato DJ` translate the musical notation automatically into the Mixed in Key notation).

Otherwise `Serato DJ` doesn't detect it as a valid `key` (if it is detected as a valid `key` it is displayed colorful, see [here](https://abload.de/img/bildschirmfoto2017-05lib82.png)). This is important for usage of `Serato DJ`.

Is there any solution for this?

**Comment by sampsyo** [comment]
Hmm; I don't have a perfect suggestion for modifying the tags like this (although see #488). But perhaps this is a straight-up bug in our `keyfinder` or `acousticbrainz` plugins—if we should be normalizing the case from those sources for compatibility, perhaps we should just fix that!
