### ISSUE TITLE
sketchy boots

### ISSUE THREAD

**Issue by joseroubert08** [beetbox/beets#2534]
### Problem

(Describe your problem, feature request, or discussion topic here. If you're reporting a bug, please fill out this and the "Setup" section below. Otherwise, you can delete them.)

Running this command in verbose (`-vv`) mode:

```sh
$ beet -vv (... paste here ...)
```

Led to this problem:

```
(paste here)
```

Here's a link to the music files that trigger the bug (if relevant): 

### Setup

* OS: 
* Python version: 
* beets version: 
* Turning off plugins made problem go away (yes/no): 

My configuration (output of `beet config`) is:

```yaml
(paste here)
```

**Comment by sampsyo** [comment]
I've blocked @joseroubert08 and reported the user for spam.
