### ISSUE TITLE
How to keep original filename? aka do Not rename

### ISSUE THREAD

**Issue by xeverse** [beetbox/beets#2535]
beet fields?
there's no $origfname

**Comment by sampsyo** [comment]
Can you explain more about what you're trying to do?

**Comment by xeverse** [comment]
![2017-05-19_204801_740996908](https://cloud.githubusercontent.com/assets/4138036/26262325/16b77cb2-3cdd-11e7-8f81-62712345113c.png)
original files have A1..B2.. C3 etc as track number. not in the brainmuzic db yet.

**Comment by sampsyo** [comment]
I still don't quite follow, but maybe you're trying to define something called $origfname that refers to the current last part of the file's path? You might try using the `inline` plugin for that…

**Comment by Kraymer** [comment]
@xeverse please use default issue template with what command you run, and your config. Then for 1 file : what is input filename, what is output filename and what you expected it to be.

If I understand you right, your files are renamed on imports and you would expect them not to be ?

**Comment by xeverse** [comment]
@sampsyo i needed $origfname just as a quick hack.  to copy them from the orig filenames.
@Kraymer yes. but just the track numbers. with U [as-is] instead of for instance A1 i always get 00 as you can see for all tracks.  

...TRACKNUMBER=A4&..
..GENRE=Electronic....TRACKNUMBER=C5&...ALBUM=Archived :
.TRACKNUMBER=F2&...

etc..

ok i'll fill the template properly a bit later..

**Comment by sampsyo** [comment]
> @sampsyo i needed $origfname just as a quick hack. to copy them from the orig filenames.

In that case, the `inline` plugin probably is what you want.

**Comment by xeverse** [comment]
maybe as a last resort, 
but i'd perefer just a perfect copy of the 
TRACKNUMBER tags into the encoded files.

**Comment by sampsyo** [comment]
OK! It sounds like you're talking about a different issue, though: our track numbers are numbers, not strings. You might considering filing a separate issue (with lots more detail; and see also #1831).

**Comment by arcresu** [comment]
It's been some time now and we haven't heard from you. Without more detailed information it's really hard for the community to help you with this issue. If you'd still like help with this, feel free to reopen this issue or open a new one, but make sure you [include as much relevant information](https://www.cs.cornell.edu/~asampson/blog/bugrubric.html) as possible.
