### ISSUE TITLE
fetchart: Restore iTunes Store source

### ISSUE THREAD

**Issue by owcz** [beetbox/beets#2551]
`fetchart` once supported the retrieval of iTunes Store artwork with https://github.com/ocelma/python-itunes, but the package has not been maintained for the last year and was removed from the documentation (#2540) when it began throwing errors (#2371, #1610). Perhaps a py3 compatibility issue?

iTunes is, in my experience, the highest-quality album art provider outside of https://coverartarchive.org. It would be a boon to have it work with `fetchart` again. Not sure if it's possible or important to resuscitate `python-itunes` but you might also find inspiration/code in https://greasyfork.org/en/scripts/20771-stig-s-art-grabr

**Comment by Kraymer** [comment]
Thanks for the sum-up.

> Not sure if it's possible or important to resuscitate python-itunes

I had a look at it and except one trivial URL to fix, the tests pass on python 2.7.
It's then a matter to port ~700 LOC to python3.
From https://github.com/ocelma/python-itunes/issues/9 it seems @ocelma is not interested anymore to maintain the package, so we could fork it in *beetbox* (under a new name as credentials to take control of the original python-itunes package have been lost).

**Comment by nathdwek** [comment]
Closed by #2718
