### ISSUE TITLE
Google Music plugin/integration

### ISSUE THREAD

**Issue by owcz** [beetbox/beets#2553]
Feature request

A deprecated project, https://github.com/mister-walter/gbeets, describes a beets plugin that uploads tracks to a Google Music locker and searches the GM library. I don't know if that documentation page is all that ever existed, or if it ran between 2012–2014 (#624) but it's a good idea. @mister-walter

It'd be really nice to send an album straight to Google Music for mobile use from CLI, especially through beets

**Comment by sampsyo** [comment]
This does indeed seem like a cool feature, especially if there's old code to be recovered and dusted off.

**Comment by mister-walter** [comment]
Hi guys, I'm really sorry I didn't see this until now! Kudos to @tigranl, I know my old code wasn't the greatest!
