### ISSUE TITLE
discogs: Fetch "style" field

### ISSUE THREAD

**Issue by brendan-pike** [beetbox/beets#2579]
Can beets please be enhanced to pull music style in addition to Genre. In my opinion discog have the most intelligent [music categorising](https://www.discogs.com/help/doc/submission-guidelines-release-genres-styles) system available. So if like me you wish to follow this it is impossible without styles. Discog only have [15 genres](https://reference.discogslabs.com/browse/genre) but [425 styles](https://reference.discogslabs.com/browse/styles).

As an example if we search [Bob Dylan - Fallen Angels](https://www.discogs.com/Bob-Dylan-Fallen-Angels/master/1002633) we see its associated with three genres:  **Rock**; **Blues**; **Pop** and one style: **Vocal**.  The [Vocal](https://reference.discogslabs.com/style/Vocal) style is a "sub-genre" of Pop.

To my knowledge the Discog API does not support probing this genre/style relationship structure unfortunately but simply provides the tags to each album.  So in my opinion it would be adequate for at least now to simply start recording album styles simply as a STYLE metatag against each track.  This is what currently manually do, so for our Fallen Angels example I would simply have the following ```
```metatags:
genre="Rock; Blues; Pop"
style="Pop"
```
Initially I would like the ability to automatic this process from Beets.

If there was is a way Beets is able to build on this in the future then even better.  I would for example to be able to see what albums in my collection have a style of Vocal and genres that include "Folk, World, & Country".

Thank you

How to store this information within Beets

**Comment by sampsyo** [comment]
Thanks for filing the request!

(See also #465.)

**Comment by dbogdanov** [comment]
I am also voting for this feature. Discogs provides the best public data that can be used for annotation by styles (subgenres) out there.

**Comment by thedevilisinthedetails** [comment]
So I managed to get this working. I didnt add the additional feature req from https://github.com/beetbox/beets/issues/465 as I wanted to focus more on just the styles. Its grabbing all style tags from discogs for the specific album chosen and applying it as so; "style1 - style2 - style 3 - etc". If this is ok I can make a PR. Let me know

**Comment by jackwilsdon** [comment]
All feature PRs are welcome @thedevilisinthedetails! Sounds like a great addition to beets.

**Comment by thedevilisinthedetails** [comment]
Cool, noticed a slight bug i created. Will fix then make the PR

**Comment by montchr** [comment]
I would love to see this feature @thedevilisinthedetails! 

> Its grabbing all style tags from discogs for the specific album chosen and applying it as so; "style1 - style2 - style 3 - etc".

Could you consider adding a configurable setting to determine whether to write all style tags (as you suggested) or just the first style listed?

**Comment by dbogdanov** [comment]
Btw, how are multi-genres treated? The format for style strings should be consistent with that.

**Comment by thedevilisinthedetails** [comment]
> I would love to see this feature @thedevilisinthedetails!
> 
> > Its grabbing all style tags from discogs for the specific album chosen and applying it as so; "style1 - style2 - style 3 - etc".
> 
> Could you consider adding a configurable setting to determine whether to write all style tags (as you suggested) or just the first style listed?

Hmm, thing is I am currently sorting the styles by alphabetical order. So if style tags are:  "Industrial, Techno, Ambient", the output would be "Ambient - Industrial - Techno". I figured this way users can create a tree in tree type directory structure in their config file.

I really want to get this PR out there but it seems I am having issues pushing my branch into the repo. Will work on this today and get the PR open

**Comment by thedevilisinthedetails** [comment]
> Btw, how are multi-genres treated? The format for style strings should be consistent with that.

I think the discogs plugin is not working with genres. I always use discogs to tag my mp3s and the genre tagged does not seem to be consistent to what is on discogs. Seems to always be defaulted with the lastgenre plugin. I have no idea how it's working within lastgenre.

**Comment by thedevilisinthedetails** [comment]
PR opened

**Comment by dbogdanov** [comment]
For the LastGenre plugin it is said that "the genres are separated by commas by default, but you can change this with the separator config option." 

It may be useful to have a similar option for consistency (different users may prefer different separators, and they may want them to be consistent across different annotation plugins they use).

**Comment by thedevilisinthedetails** [comment]
This weeked will address the comments, change hypens to commas and adjust test
