### ISSUE TITLE
Delete all ID3 tags when importing and embed cover art to ID3 tags

### ISSUE THREAD

**Issue by plittlefield** [beetbox/beets#2589]
I would like to delete all existing id3 metatags from any imported mp3 files.

e.g.

Look up Files, Delete ID3 Tags, Copy Files to new Folder, redo ID3 tags, embed art.

Is this possible?

I have tried using info and scrub plugins but cannot seem to get it to work.

Can you help?

Thanks.

Paul

beets version 1.4.3
Python version 2.7.12
plugins: embedart, fetchart, info, scrub
linux: Ubuntu 16.04.2 LTS

directory: ~/Downloads/music/beets/done
library: ~/Downloads/music/beets/musiclibrary.db
plugins: fetchart embedart scrub info
paths:
  default: $albumartist/[$year] $album/$track $title
id3v23: yes
art_filename: cover
autotag: yes
import:
  copy: yes
  write: yes
  log: beetslog.txt
scrub:
  auto: yes

**Comment by sampsyo** [comment]
Sure—the scrub and embedart plugins are indeed supposed to do these things. Can you please elaborate on what exactly is different from the process you want?

**Comment by plittlefield** [comment]
Hi Adrian,

Thanks for replying so quickly.

If I run the usual beet import command on a source folder, the resulting
files in the destination folder don't seem to have id3v2 tags or the id3v2
embedded art.

The software correctly looks up the source folder and songs, then copies
the files to the correct destination with new correct names, and downloads
the correct cover art.

However, it's not tagging the files or embedding the art.

Can I run a debug script to show you?

Paully

**Comment by sampsyo** [comment]
Hmm, yes, just enabling the embedart plugin should do that. More details would indeed be helpful—it would be most helpful to have a complete bug report. There's advice on how to file a bug in the FAQ; in this specific case, for example, we'll want to see the commands you ran and how you tested for embedded album art.

**Comment by plittlefield** [comment]
OK, I will do that tomorrow.

**Comment by plittlefield** [comment]
Hello,

My apologies for the delay, been really busy with work and life!

Will have a good go at this tomorrow.

Regards,

Paully

**Comment by plittlefield** [comment]
OK, now have time to look at this again!

It **is** embedding the artwork and adding certain id3 tags, but it is not stripping ALL id3 tags before adding the ones it wants to.

It seems to be keeping the COMM (Comments) tag.

I would like it to delete all id3 tags, add only the bear minimum (or ones which I choose) then do the title renaming, add the cover art and copy the files to the correct location.

I know, so needy :-)

**Comment by sampsyo** [comment]
If you'd like to get rid of tags you don't like, please try the `zero` plugin. You can either list the tags you want to remove, or you can list the tags you want to keep (and remove all the rest).

**Comment by plittlefield** [comment]
I shall try that, thank you.

That `zero` plugin has made me read again about the `scrub` plugin. Perhaps I am not using it correctly. Having read the documentation, perhaps I should be NOT be specifying scrub: auto: yes at all?!

Or, have I misinterpreted the docs...

> To automatically remove files’ tags before writing new ones, just enable the scrub plugin (see Using Plugins). When importing new files (with import.write turned on) or modifying files’ tags with the beet modify command, beets will first strip all types of tags entirely and then write the database-tracked metadata to the file. This behavior **can be disabled with the auto config option**.

Thanks.

**Comment by plittlefield** [comment]
This is what I want to end up with:-

**id3v1 tag info**
`Title: Show Me A Leader`
`Artist: Alter Bridge                  `
`Album: The Last Hero`
`Year: 2016`
`Genre: Heavy Rock`
`Track: 1`

**id3v2 tag info**
`APIC (Attached picture): ()[, 3]: image/jpeg, 64425 bytes`
`TYER (Year): 2016`
`TCON (Content type): Heavy Rock (255)`
`TRCK (Track number/Position in set): 1`
`TIT2 (Title/songname/content description): Show Me A Leader`
`TPE1 (Lead performer(s)/Soloist(s)): Alter Bridge`
`TALB (Album/Movie/Show title): The Last Hero`

...and nothing else.

Thanks.

**Comment by sampsyo** [comment]
Sounds like you want to use *both* `scrub` and `zero`. The former removes the "dark matter" of tags that beets can't support and won't let you modify otherwise. The latter lets you select the tags—a subset of the ones beets supports—to keep on your files.

**Comment by plittlefield** [comment]
Yes, we are very nearly there. The zero plugin settings in my config...

    zero:
      keep_fields: title artist album year track

...give me this:-

    id3v1 tag info:
    Title  : Show Me a Leader                Artist: Alter Bridge                  
    Album  : The Last Hero                   Year: 2016, Genre: Heavy Rock (255)
    Comment:                                 Track: 1
    id3v2 tag info:
    TIT2 (Title/songname/content description): Show Me a Leader
    TPE1 (Lead performer(s)/Soloist(s)): Alter Bridge
    TRCK (Track number/Position in set): 1
    TALB (Album/Movie/Show title): The Last Hero
    TYER (Year): 2016

I just now need to stop the zero plugin from zapping the id3v2 **APIC** tag. I have tried looking up the correct APIC field name with `beet fields` but I cannot find it.

Any ideas?

**Comment by sampsyo** [comment]
Aha—this is a little tricky, but try `art`?

**Comment by plittlefield** [comment]
Alas, does not work.

I'll keep playing with a few ideas, and perhaps you could work on this too
for a new release?

**Comment by sampsyo** [comment]
OK, thanks for trying. After looking into it a little more, I'm less convinced that `zero` is the problem. Does your album art persist if you disable that plugin temporarily?

Also, can you include a verbose log from a run of beets that erroneously remove your album art?

**Comment by plittlefield** [comment]
Yes, the album art embedding works if I disable the zero plugin.

Here is a verbose log from a run of beets which shows this - https://pastebin.com/fA4jKf5Z

**Comment by sampsyo** [comment]
Sorry for the weird request, but can you run it with `-vv` instead of `--verbose`? That will get the actual output from the `zero` plugin.

**Comment by sampsyo** [comment]
In the end, though, I think I see what might be going wrong… and yes, it might be related to `keep_fields`. It might be possible to get what you want by using the "negative" approach to `zero`, where you just list the fields you want to remove. Meanwhile, we should probably mark this as a bug to request that `keep_fields` be able to support album art.

**Comment by plittlefield** [comment]
Here you go, with the `zero` plugin enabled.

(I had to run this with the `pastebinit` command as it was so long!)

http://paste.ubuntu.com/24882599/

**Comment by plittlefield** [comment]
...and this is the id3 tag for a song after beet import **with** `zero` plugin:-

https://pastebin.com/hrhvpzQ1

**Comment by sampsyo** [comment]
That's odd… I'm a little surprised to see this line in the log:

```
zero: art:  -> None
```

Could you also please include your current configuration stanza for the `zero` plugin?

**Comment by plittlefield** [comment]
https://pastebin.com/hQrNm0uC

**Comment by sampsyo** [comment]
Hmm; I don't see `art` in the `keep_fields` line here:

```yaml
zero:
    keep_fields: title artist album year track genre
    auto: yes
    update_database: no
    fields: []
```

And I'd recommend not setting `fields` at all if you're going to use `keep_fields`.

No guarantee that that will work, but it could be worth a shot.

**Comment by plittlefield** [comment]
OK, this is my config and I have not added a `fields` option (I think that's what the output of `beet config` has inserted by itself)...

    zero:
      keep_fields: title artist album year track genre art

Here is the result...

http://paste.ubuntu.com/24883079/

**Comment by plittlefield** [comment]
...and alas, still no id3v2 embedded art.

Shall I open a bug report for this?

**Comment by sampsyo** [comment]
Thanks for bearing with me! And yes, if you don't mind filing a special-purpose bug summarizing everything you've found, that would be awesome.

**Comment by plittlefield** [comment]
No problem at all, and yes I will on Monday.

**Comment by plittlefield** [comment]
As a newbie, how I do file a special-purpose bug?

**Comment by sampsyo** [comment]
Oh, sorry for being unclear! I just meant filing a separate issues with complete details about what we know so far.
