### ISSUE TITLE
Import: album is already in the library!

### ISSUE THREAD

**Issue by Mengele88** [beetbox/beets#2594]
Is there a way to go back if an album is already in the library, or add a fourth option: `edit Candidates`?

If I have an album in two different versions (Original and Deluxe Edition), I like to add both but I will change the AlbumTag from <Album> to <Album (Deluxe Edition)>.

At the moment I have to skip them and import a secondtime with the timide option where I can `edit Candidates`

`This album is already in the library!`
`Old: 12 items, FLAC, 969kbps, 48:47, 339.3 MiB`
`New: 20 items, FLAC, 938kbps, 84:37, 568.2 MiB`
`[S]kip new, Keep both, Remove old?`

**Comment by sampsyo** [comment]
Interesting suggestion! We don't currently have a way to "go back" when a duplicate is detected. There are related issues at #351 and #1131. Would something like the former solve the problem for you?
