### ISSUE TITLE
Add option to convert on import while maintaining original lossless file

### ISSUE THREAD

**Issue by apastuszak** [beetbox/beets#2604]
### Problem

My standard workflow is to import a bunch of FLAC files and then run a beet convert to convert the files to MP3 in a separate directory, as beet convert allows.  It would be nice, if you could run the convert automatically right after import completes.
Running this command in verbose (`-vv`) mode:

```sh
$ beet convert
```

Led to this problem:

```
I'm lazy and don't want to have to manually run beet import.
```

Here's a link to the music files that trigger the bug (if relevant): n/s 

### Setup

* OS: Ubuntu Linux 16.04
* Python version: 
* beets version: 2.4.4
* Turning off plugins made problem go away (yes/no):no 

My configuration (output of `beet config`) is:

```yaml
To be added later
```

**Comment by sampsyo** [comment]
Hi! I think we have a ticket covering this over in #1840.

Also, FWIW, when writing feature requests, you don't have to fill out the issue template. :smiley: That's really for bug reports.

**Comment by apastuszak** [comment]
Yes, 1840 has me covered.  Thanks!
