### ISSUE TITLE
Weird install method from Pip on Ubuntu 17.04

### ISSUE THREAD

**Issue by RollingStar** [beetbox/beets#2606]
### Problem

I have a nearly factory-fresh Ubuntu install that isn't working with pip to install beets in an intuitive way. I found a workaround.

### Doesn't work

```sh
user:~$ pip install beets
Collecting beets
Collecting jellyfish (from beets)
Collecting six>=1.9 (from beets)
  Using cached six-1.10.0-py2.py3-none-any.whl
Collecting unidecode (from beets)
  Using cached Unidecode-0.04.20-py2.py3-none-any.whl
Collecting enum34>=1.0.4 (from beets)
  Using cached enum34-1.1.6-py2-none-any.whl
Collecting munkres (from beets)
  Using cached munkres-1.0.10-py2.py3-none-any.whl
Collecting mutagen>=1.33 (from beets)
Collecting pyyaml (from beets)
Collecting musicbrainzngs>=0.4 (from beets)
Installing collected packages: jellyfish, six, unidecode, enum34, munkres, mutagen, pyyaml, musicbrainzngs, beets
Successfully installed beets-1.4.5 enum34-1.1.6 jellyfish-0.5.6 munkres-1.0.10 musicbrainzngs-0.6 mutagen-1.38 pyyaml-3.12 six-1.10.0 unidecode-0.4.20
user:~$ beet
The program 'beet' is currently not installed. You can install it by typing:
sudo apt install beets
user:~$ beets
No command 'beets' found, did you mean:
 Command 'beet' from package 'beets' (universe)
beets: command not found

user:~$ sudo pip install beets
The directory '/home/user/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/home/user/.cache/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Requirement already satisfied: beets in ./.local/lib/python2.7/site-packages
Requirement already satisfied: jellyfish in ./.local/lib/python2.7/site-packages (from beets)
Requirement already satisfied: six>=1.9 in ./.local/lib/python2.7/site-packages (from beets)
Requirement already satisfied: unidecode in ./.local/lib/python2.7/site-packages (from beets)
Requirement already satisfied: enum34>=1.0.4 in ./.local/lib/python2.7/site-packages (from beets)
Requirement already satisfied: munkres in ./.local/lib/python2.7/site-packages (from beets)
Requirement already satisfied: mutagen>=1.33 in ./.local/lib/python2.7/site-packages (from beets)
Requirement already satisfied: pyyaml in ./.local/lib/python2.7/site-packages (from beets)
Requirement already satisfied: musicbrainzngs>=0.4 in ./.local/lib/python2.7/site-packages (from beets)
```

### Does work
```
user:~$ sudo -H pip install beets
Collecting beets
  Downloading beets-1.4.5.tar.gz (1.4MB)
    100% |████████████████████████████████| 1.5MB 593kB/s 
Requirement already satisfied: enum34>=1.0.4 in /usr/lib/python2.7/dist-packages (from beets)
Collecting jellyfish (from beets)
  Downloading jellyfish-0.5.6.tar.gz (132kB)
    100% |████████████████████████████████| 133kB 2.1MB/s 
Collecting munkres (from beets)
  Downloading munkres-1.0.10-py2.py3-none-any.whl
Collecting musicbrainzngs>=0.4 (from beets)
  Downloading musicbrainzngs-0.6.tar.gz (111kB)
    100% |████████████████████████████████| 112kB 2.1MB/s 
Collecting mutagen>=1.33 (from beets)
  Downloading mutagen-1.38.tar.gz (913kB)
    100% |████████████████████████████████| 921kB 818kB/s 
Collecting pyyaml (from beets)
  Downloading PyYAML-3.12.tar.gz (253kB)
    100% |████████████████████████████████| 256kB 1.4MB/s 
Requirement already satisfied: six>=1.9 in /usr/lib/python2.7/dist-packages (from beets)
Collecting unidecode (from beets)
  Downloading Unidecode-0.04.20-py2.py3-none-any.whl (228kB)
    100% |████████████████████████████████| 235kB 1.6MB/s 
Building wheels for collected packages: beets, jellyfish, musicbrainzngs, mutagen, pyyaml
  Running setup.py bdist_wheel for beets ... done
  Stored in directory: /root/.cache/pip/wheels/dd/4b/42/e4d7f9fce863b3074b856aa119a10b96af871dc33e8b1e150d
  Running setup.py bdist_wheel for jellyfish ... done
  Stored in directory: /root/.cache/pip/wheels/0f/a8/f6/3c2f1675f6a60367a113203470a21398c178d5145df7e68d24
  Running setup.py bdist_wheel for musicbrainzngs ... done
  Stored in directory: /root/.cache/pip/wheels/b7/06/bb/c891cad2436937ba584d1823fa20373194ff73c081af84f68d
  Running setup.py bdist_wheel for mutagen ... done
  Stored in directory: /root/.cache/pip/wheels/a0/f3/eb/395cbedfd0714adf58dcf3a9efa5e1e18b13f04a0c6ad25c09
  Running setup.py bdist_wheel for pyyaml ... done
  Stored in directory: /root/.cache/pip/wheels/2c/f7/79/13f3a12cd723892437c0cfbde1230ab4d82947ff7b3839a4fc
Successfully built beets jellyfish musicbrainzngs mutagen pyyaml
Installing collected packages: jellyfish, munkres, musicbrainzngs, mutagen, pyyaml, unidecode, beets
Successfully installed beets-1.4.5 jellyfish-0.5.6 munkres-1.0.10 musicbrainzngs-0.6 mutagen-1.38 pyyaml-3.12 unidecode-0.4.20
```

For the [guide](http://beets.readthedocs.io/en/v1.4.5/guides/main.html), maybe add a tip about `-H` for sudo on Ubuntu? I don't know what causes this. I did try various `pip install beets` and `sudo pip install beets` before trying `sudo -H` so maybe installing it already changes things.

>If you have pip, just say pip install beets (you might need sudo in front of that).

**Comment by sampsyo** [comment]
Hi!

> user:~$ beets
> No command 'beets' found, did you mean:
>  Command 'beet' from package 'beets' (universe)
> beets: command not found

The command is `beet`, not `beets`. Is there any chance the first attempt actually worked?

**Comment by RollingStar** [comment]
I ran `beet` (no s) right before running `beets`. The log in my post includes that. I ran both of those after installing with pip (multiple times). I didn't show in the post, but after using `sudo` (no -H), I got the same error message I showed in the post.

**Comment by sampsyo** [comment]
Oops! I totally missed that. :flushed:

Anyway, it looks like the original non-`sudo` installation put things in `~/.local`. That means the `beet` command is probably located at `~/.local/bin/beet`, which means that the right thing to do is probably to add `$HOME/.local/bin` to your `$PATH`. (More on this in [an FAQ](http://docs.beets.io/en/v1.4.5/faq.html#say-command-not-found).)

I'm a little surprised, though, that that's the default behavior on Ubuntu (and that they didn't also add the appropriate directory to everyone's `$PATH` at the same time)… a little Googling didn't turn up any more background. Have you happened to come across any documentation that says why Ubuntu's pip behaves differently?

**Comment by arcresu** [comment]
I know that there have been a lot of long discussions in Debian and upstream about how pip should interact with the system packages. IIRC, last time I followed that discussion Debian was patching pip in a way that upstream wasn't entirely happy about, but they were working towards a better solution. I think that patch was related to making the default  `pip install` imply the `--user` flag for non-root users which might explain what was going on here.

In any case I don't thing there's anything to be done on beets' side here since the most likely issue was the misconfigured `PATH`, and the story has probably changed in the meantime. Using pip to install packages as root on a Debian-based system is not normally done. You typically want either the system packages or a local pip-based installation. For anything else you need to be more comfortable with how the different python package managers are interacting.

**Comment by sampsyo** [comment]
Got it! Indeed; I don't think there's much beets itself can do.
