### ISSUE TITLE
zero: Support album art as an option in keep_fields

### ISSUE THREAD

**Issue by plittlefield** [beetbox/beets#2609]
This is a follow up to the issue - https://github.com/beetbox/beets/issues/2589 - and I have been asked to report it here as a 'bug' or 'request'.

Problem = The `zero` plugin is not able to keep, or is interferring with the `embedart` plugin.

Here is my beet `config` - https://pastebin.com/hQrNm0uC

This is the id3 tag for a song after beet import with `zero` plugin - https://pastebin.com/hrhvpzQ1

This is the command output - http://paste.ubuntu.com/24883079

* OS: Linux - Ubuntu 16.04.2 LTS
* Python version: 2.7.12
* beets version: 1.4.4

Thanks!

**Comment by sampsyo** [comment]
Thanks! Yes, we should add special support for a key like `art` in the `keep_fields` line. In the mean time, the workaround is to use `fields`, i.e., the "negative" option—and just list all the fields *except* those you want to keep. That should preserve the album art.

**Comment by nathdwek** [comment]
I don't really understand, it seems to me that in the last pastebin provided in the other thread, with `art` listed in `keep_fields`, there is indeed no art deletion going on.

Am I understanding this issue wrong?

**Comment by sampsyo** [comment]
It’s true that the plugin doesn’t log anything about deleting the `art` field, but (unless I’m misunderstanding too!) we still end up removing the album art according to the second paste: https://pastebin.com/hrhvpzQ1

My best guess is that this comes from our having two different names in MediaFile for image data: `art` and `images`. But that really is just a guess...

**Comment by PaulFinch** [comment]
working for me with "images" keyword

**Comment by plittlefield** [comment]
I shall try this and report back.

**Comment by plittlefield** [comment]
`zero:`
`keep_fields: title artist album year track genre images`

Boom, problem solved! Thank you so much for your work on this.

:-)

**Comment by sampsyo** [comment]
Awesome! Is there any chance one of you (@plittlefield or @PaulFinch) might be able to add a note about this to the documentation for the `zero` plugin?

**Comment by plittlefield** [comment]
Yes, would love to. Do I put something in this issue page or somewhere else?

**Comment by sampsyo** [comment]
You can open a pull request by going to the `zero.rst` page here on GitHub and hitting the "edit" button.

**Comment by plittlefield** [comment]
Sorry, newbie alert  :-)  I've found [this page](https://github.com/beetbox/beets/blob/a9fd3df6810526055654ab4336fc1bac0ac66f82/docs/plugins/zero.rst) but I have no edit button.

**Comment by sampsyo** [comment]
It's the little pencil icon. :smiley: Maybe this article will help? https://help.github.com/articles/editing-files-in-another-user-s-repository/

**Comment by plittlefield** [comment]
Side note, I started writing a note about 'images' but have spotted that when you run `beet fields` it does not show `images` as a field!?!

**Comment by sampsyo** [comment]
It's true that `images` is a strange case. It is *only* an on-disk media field and not stored in the database, and therefore not accessible through normal means. For example, you can't do `beet ls images:...` or `beet ls -f '$images'`. Unlike most fields, that means it's available to `zero` but not listed in `fields`.

**Comment by plittlefield** [comment]
Ah, I did a search in the repo for zero and clicked on the result. If I browse to the file, I can edit it :-)

**Comment by plittlefield** [comment]
Re: images strange case, comment noted. I will write something to reflect that and add an example.

**Comment by plittlefield** [comment]
Edit done, hope it's OK :-)

**Comment by sampsyo** [comment]
Hmm; somehow, I don't see a pull request… did you finish up the edit with a "propose changes" click?

**Comment by plittlefield** [comment]
Yes, here is the [result](https://github.com/beetbox/beets/compare/master...plittlefield:patch-1).

**Comment by sampsyo** [comment]
Aha! If you click the "create pull request" button on that page, it will initiate a PR (which conveniently bundles code changes and discussion together).

**Comment by plittlefield** [comment]
Done, I hope  :-)

**Comment by sampsyo** [comment]
Closing thanks to @plittlefield's docs addition.
