### ISSUE TITLE
Inline doesn't look at beets scope for variable definitions

### ISSUE THREAD

**Issue by RollingStar** [beetbox/beets#2614]
### Problem

This was working earlier, but I'm not sure what in the syntax I changed (config, dateops.py, or beet command). Maybe I hallucinated it?

I have 3 very similar fields defined with Inline. I want to define 3 functions once to be used within all 3 fields. This is less buggy than keeping 3 copies of the functions, because I only have to change the function once to see results in 3 fields.

The function is:

```
def get_og_year():
	if original_year > 0:
		return str(original_year)
	if year > 0:
		return str(year)
	else:
		return ''
```

There's a similar one for year-mm and year-mm-dd. I put the above definition into a file called `dateops.py` and put that file in the appropriate place for execution within Python / scripts. Beets sees the script fine. I get errors like `NameError: name 'original_year' is not defined`, which to me looks like a scope error where `dateops.py` doesn't see beets variable definitions for `original_year`.

I can try hunting down this error and making a small config that reproduces it, but I think it comes down to me not understanding Python import syntax or not understanding how Inline works.

### Setup

* OS: win10 x64
* Python version: 3.6.0
* beets version: 1.4.4+ (git intermediate before 1.4.5)
* Turning off plugins made problem go away (yes/no): probably

Relevant bit of my configuration (output of `beet config`) is:

```yaml
album_fields:
    alb_orig_year: |
        import dateops
        return get_og_year()
```

I've also tried `from dateops import get_og_year` and `from dateops import *`, but both currently seem to fail. I believe `from dateops import *` was the only one that actually worked earlier, but I have no idea what I changed that broke it again. I can make this more reproducible if needed, but I think I might just need a hint on syntax or a tip that what I want isn't currently possible with Inline. My overall goal is to define a function once and use it in multiple `album_fields`.

**Comment by sampsyo** [comment]
Hmm—I can see how this would be helpful, but I'd be pretty surprised if this worked in the past. Here's how it works: `inline` evaluates your expression in a context where the extra variables are defined. In Python, `import` executes another source file in a new module context—which is empty initially. (That's part of Python's love for namespacing: modules are empty until you put things in them.)

I don't have an immediate recommendation for how to "librarize" functionality like this for inline expressions. Maybe switching over into a little custom plugin would be worthwhile?

**Comment by RollingStar** [comment]
Switching to a plugin does what I want. Thanks!
