### ISSUE TITLE
Fetch MusicBrainz work ID

### ISSUE THREAD

**Issue by mhendu** [beetbox/beets#2618]
My first post here, so apologies if I'm doing this completely wrong. I also know next to nothing about programming; please forgive my ignorance.

I'd like to add mb_workid to all my library tracks so I can eventually figure out when I have cover versions or alternate versions of the songs. I've read a few issues - most closely related seems to be #2452 - but I'm unable to make things work the way I'd like. I get mb_workid listed as a field when I run "beet fields" but nothing gets written there when I import tracks to my library, although other fields do get updated correctly.

Here's what I tried:

Updated __init__.py in the autotag folder with the following lines:
    item.mb_workid = track_info.work_id
   (this was placed under apply_item_metadata and under #Musicbrainz IDs)

Updated hooks.py with the following (under TrackInfo):
    - ``work_id``: MusicBrainz Work ID
As well as adding work_id=None and self.work_id = work_id to def __init__

Updated mb.py with the following (under track_info / if recording.get):
    lyricist = []
    composer = []
    composer_sort = []
    work = []
    work_disambig = []
    for work_relation in recording.get('work-relation-list', ()):
        if work_relation['type'] != 'performance':
            continue
        work_id=work_relation['work']['id']

Added the following to library.py:
        'mb_workid':            types.STRING,

Added to mediafile.py:
    mb_workid = MediaField(
        MP3UFIDStorageStyle(owner='http://musicbrainz.org'),
        MP4StorageStyle('----:com.apple.iTunes:MusicBrainz Work Id'),
        StorageStyle('MUSICBRAINZ_WORKID'),
        ASFStorageStyle('MusicBrainz/Work Id'),
    )

**Comment by mhendu** [comment]
Here are the files I updated, in case this makes things a little clearer.

[beets.zip](https://github.com/beetbox/beets/files/1117135/beets.zip)

**Comment by sampsyo** [comment]
Sounds like a good idea! Storing a work ID seems very reasonable.

It looks like you've already gotten started on making changes the code, which is awesome. To show what you've done, please open a pull request so we can see the changes. GitHub's help pages are a great resource for learning the workflow to create a fork, push your changes, and create a PR.

**Comment by mhendu** [comment]
OK, I think I set up the pull request correctly (hopefully).

https://github.com/beetbox/beets/pull/2619

**Comment by Maxr1998** [comment]
I think this can be closed since #3272 added support for it, right?

**Comment by snejus** [comment]
@Maxr1998 indeed!
