### ISSUE TITLE
musixmatch searches failing in beets but work in browser

### ISSUE THREAD

**Issue by anarcat** [beetbox/beets#2630]
### Problem

I'm trying to find the lyrics to a song that I know is on Musixmatch.

Running this command in verbose (`-vv`) mode fails:

```sh
$ beet -vv -l ./library.db lyrics richard desjardins la maison est ouverte
user configuration: /home/anarcat/.config/beets/config.yaml
data directory: /home/anarcat/.config/beets
plugin paths: 
Sending event: pluginload
lyrics: Disabling google source: no API key configured.
library database: /home/anarcat/src/lyrics-ptype/library.db
library directory: /home/anarcat/mp3
Sending event: library_opened
lyrics: failed to fetch: http://lyrics.wikia.com/Richard_Desjardins:La_Maison_Est_Ouverte (404)
lyrics: failed to fetch: https://www.musixmatch.com/lyrics/Richard-Desjardins/La-Maison-Est-Ouverte (404)
lyrics: lyrics not found: Richard Desjardins - Boom Boom - La maison est ouverte
Sending event: cli_exit
```

You can see above that it fails to find the lyrics, yet they are available on MusixMatch at:

https://www.musixmatch.com/fr/paroles/Richard-Desjardins/La-maison-est-ouverte

Notice the different capitalization. Also note that the result comes up in a search on their website as well:

https://www.musixmatch.com/fr/search/richard%20desjardins%20la%20maison%20est%20ouverte

I wonder if the latter couldn't be used to get the lyrics in a more reliable way...

Note that with the Google Search API keys in, I still fail to get the lyrics, even though it *seems* to find a good URL:

```
$ beet -vvv -l ./library.db lyrics richard desjardins la maison est ouverte
user configuration: /home/anarcat/.config/beets/config.yaml
data directory: /home/anarcat/.config/beets
plugin paths: 
Sending event: pluginload
library database: /home/anarcat/src/lyrics-ptype/library.db
library directory: /home/anarcat/mp3
Sending event: library_opened
lyrics: failed to fetch: https://www.musixmatch.com/fr/paroles/Richard-Desjardins/La-maison-est-ouverte (404)
lyrics: failed to fetch: https://www.musixmatch.com/es/letras/Richard-Desjardins-Francois-Gauthier-Mathieu-Desy-Forestare/La-Maison-est-ouverte (404)
lyrics: failed to fetch: http://lyrics.wikia.com/Richard_Desjardins:La_Maison_Est_Ouverte (404)
lyrics: failed to fetch: https://www.musixmatch.com/lyrics/Richard-Desjardins/La-Maison-Est-Ouverte (404)
lyrics: lyrics not found: Richard Desjardins - Boom Boom - La maison est ouverte
Sending event: cli_exit
```

It's interesting to note that the first URL there, works:

https://www.musixmatch.com/fr/paroles/Richard-Desjardins/La-maison-est-ouverte

### Setup

* OS: Debian stretch 9
* Python version 2.7.13
* beets version 1.4.5
* Turning off plugins made problem go away (yes/no): yes, but that's besides the point of course

My configuration (output of `beet config`) is:

```yaml
plugins: fetchart fromfilename duplicates missing copyartifacts lyrics
import:
    copy: no
    move: no
    write: no
fetchart:
    sources: coverart amazon albumart fanarttv wikipedia filesystem
copyartifacts:
    print_ignored: yes
lyrics:
    auto: no
```

This seems similar to #2546 - maybe there's something fishy going on here that makes musixmatch refuse beets requests? Indeed, if i change the `USER_AGENT` string in `lyrics.py` to `Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/42.0.2311.90 Safari/537.36`, things seem to work a little better.

Any idea how to fix this? A common fix to user agent issues is to shove the usual Mozilla crap up there and append the real user agent in the end... :/ It's hackish, but it's better than downright failures...

Too bad sites disrespect unusual UAs... :(

**Comment by sampsyo** [comment]
Yep, I’m pretty sure you’re seeing #2546. Because things were working for a while, I think Musixmatch is specifically, intentionally blocking the beets UA. That makes me less than excited about changing the UA once again to avoid the block another time. One thing we could consider is making it configurable so users can provide their own UA string, which would make it their responsibility.

**Comment by anarcat** [comment]
as i said, just changing the UA string to be a little more clever may just work... something as simple as this seems to work:

```
USER_AGENT = 'Mozilla/5.0 (Linux x86_64) (like Gecko)'
```

i was hoping this would do to, but unfortunately it doesn't:

```
USER_AGENT = 'Mozilla/5.0 (Linux x86_64) beets/{} (like Gecko)'.format(beets.__version__)
```

it does seem like beets is blacklisted. :(

i guess making it customizable would at least alleviate the issue here. would this be a config-file setting? beets-wide? or is the lyrics plugin the only one having that issue?

should we reopen #2546 or continue here?

**Comment by sampsyo** [comment]
We can continue on #2546 (it’s still open). But briefly, yes, the UA string does work for now—but so did the current UA string, briefly, which is why we switched to it from th built-in requests UA. Unless we exactly replicate a popular browser UA, which feels weird, I think we’ll just be continuing the Whac-a-Mole game.

**Comment by anarcat** [comment]
okay, let's move to #2546 then :)
