### ISSUE TITLE
lyrics: Detect when you get blocked by Musixmatch

### ISSUE THREAD

**Issue by anarcat** [beetbox/beets#2632]
### Problem

My IP seems to have been blocked by musixmatch. Some of the lyrics downloaded say:

```
We are human after all

Human After All
DAFT PUNK

We detected that your IP is blocked.
It looks like you’re a bot or more likely your network may have been blacklisted for some reason.
Please confirm you are a human by checking the box below.
```

It seems the problem is resolved now because I can't reproduce with a regular web browser. It would be nice, however, to detect such scenarios and not record the problematic lyrics. I am not sure how to do this - I don't know if a different status code gets sent, but maybe we can do a simple regex-based pattern-matching technique?

Thanks!

**Comment by anarcat** [comment]
workaround: to reset the state of the database and clear those bad entries, use the following command:

```
sqlite3 ~/.config/beets/library.db "UPDATE items SET lyrics = '' WHERE lyrics LIKE '%We detected that your IP is blocked%';"
```

seems to me we should have a way to do throttling or something to workaround that block. FWIW, i was able to download about 20k titles before getting blocked.

**Comment by sampsyo** [comment]
Sure; sounds good. Just checking whether the string "We detected that your IP is blocked." is in the response should do it. Until someone writes a hit song about rate limiting… :smiley:

**Comment by anarcat** [comment]
hehe... i also figured out this is just a CAPTCHA page you can fill in to get your free pass... so it's not as bad as a complete UA block, it seems.

**Comment by anarcat** [comment]
PR coming up in #2634.
