### ISSUE TITLE
Can I query MusicBrainz XML metadata from music files with beets?

### ISSUE THREAD

**Issue by crocket** [beetbox/beets#2649]
### Problem

It seems MusicBrainz XML metadata cannot be stored in vorbis comment or matroska tag.

I'd like to search for music by querying MusicBrainz XML metadata.

Is there a way to do it with beets? Can beets convert MusicBrainz XML metadata into vorbis comment without losing information?

**Comment by sampsyo** [comment]
We don't currently store the entire MusicBrainz API response in the database or files' tags. In fact, that would be a little unwieldy—there are lots of parameters to the web service (such as `include`) that can vastly change the kind of information returned. What sort of things are you hoping to extract from the web service responses?

**Comment by crocket** [comment]
I have been into touhou vocal.

https://musicbrainz.org/recording/70ca4293-7863-48ef-8669-9dc89b3e8ae2 is an overview of a song.
The information for that webpage was extracted from http://vgmdb.net/album/60536

Is it possible to preserve as much information as possible from the overview?
I want to search for arranger, vocal, lyricst, etc, ...

**Comment by sampsyo** [comment]
The Beets Way™ is to fetch each such field into the beets database, which lets you run interesting queries over them. In fact, if you search this issue tracker, you’ll find lots of ongoing and recent efforts to increase the number of fields we fetch is this way.

AFAIK, however, MusicBrainz does not have a genre field by design; they see genres as too subjective for their catalog of ground-truth data. We have other sources for genre data (cf. the lastgenre plugin).

**Comment by crocket** [comment]
What do you think would be the minimal solution to the problem of finding touhou vocals according to some criteria?

**Comment by sampsyo** [comment]
Hmm; it’s hard to say without more specifics. For example, if you want to query by composer, you can just use `beet list composer:foo`. If you have other fields you’d like to associate with music, you can use the `beet modify command. Are there specific things missing?

**Comment by crocket** [comment]
things like the name of game, movie, or anime.

In case of touhou vocals, there are multiple touhou games under touhou project.
I want to search by the names of specific games or media projects(like touhou project).

**Comment by sampsyo** [comment]
OK, then have you tried setting that data on your music using `beet modify`?

Or, if you know of a data source that contains all this information, you can also imagine writing a plugin that gathers the information and stores if your you.

**Comment by crocket** [comment]
I haven't tried `beet modify` because I haven't figured out a good way to fetch metadata **and** record it in a standard way.

**Comment by jansol** [comment]
It seems to me that this is a matter of mapping musicbrainz semantics into beets (and actually entering all the data in musicbrainz). One likely problem with this is that musicbrainz may be lacking some fields.

@crocket how about ping me on IRC? We could draft up some spec for OSTs / arranges on musicbrainz that beets could use.

**Comment by crocket** [comment]
@jansol I tried to ping you at #beets on freenode, but you weren't there.
IRC is not really convenient because it is not asynchronous. Why don't we keep talking here or move the talk to another asynchronous communication channel?

**Comment by jansol** [comment]
I am there 24/7 (with a different nick) and noticed you 10 minutes after you left. IRC is very much asynchronous to me, as it is to a lot of other people. If having to be online to receive messages bothers you, you could try [Matrix](https://matrix.org/) using the https://riot.im/ client, they have (almost) all of freenode bridged, support email and push notifications and you stay in the room even if you close your client; you'll get whatever messages you missed when you check back (much like gitter).

Anyway let's keep the plan on [etherpad](https://etherpad.net/p/musicbrainz-ost) so we can keep all ideas in one place without spamming this thread too much.

**Comment by sampsyo** [comment]
We also have a shiny new [Discourse](https://discourse.beets.io/) that can be sometimes nice for sustained conversations.

**Comment by crocket** [comment]
Further planning goes to https://discourse.beets.io/t/how-to-organize-game-movie-anime-osts-and-touhou-vocal/160

**Comment by crocket** [comment]
I found a cheap solution to my problem.

I could just add numbers of artists, album artists, genres, and so on to achieve what I want.
IDv2.4 allows multiple entries in a single tag.

mpd can handle multiple values in a tag.
