### ISSUE TITLE
Albumdismbig is empty, but Musicbrainz has a disambiguation entry

### ISSUE THREAD

**Issue by RollingStar** [beetbox/beets#2655]
### Problem

I encountered this on two releases of Lady Gaga - Born This Way. I started by removing every trace of those albums from my beets db with `beet rm`. I imported both dummy tracks (attached) by forcing the MBID. The autotagger won't find the right release; you must force the MBID.

`$albumdisambig` is returning nothing. Yet one of these is listed in Musicbrainz as `special edition`. The other is a normal release with no disambiguation tag. See:

* https://musicbrainz.org/release/f4ecda8e-1ece-4f5c-8be7-471c14c6ab63/edit
* https://musicbrainz.org/release/7057bbc3-ba54-3a8b-aa18-a324f8a63ad8/edit

Should this show up in the $albumdisambig tag?

```
PS C:\Users\RollingStar> beet ls album:born way -f '$album $alb_orig_year_mm_dd $albumartist $al
bumstatus $albumtype.. $country $label $catalognum $albumdisambig zz'
Born This Way 2011-05-23 Lady Gaga Official album.. GB Streamline Records 0602527718408
zz
Born This Way 2011-05-23 Lady Gaga Official album.. XE Interscope Records 0602527718385
zz
```

I also have beets set to keep duplicates, maybe that is an issue?

```
found duplicates: [674]
default action for duplicates: k
```

Here's a link to the (dummy) music files that trigger the bug (if relevant): 

[gaga dummy.zip](https://github.com/beetbox/beets/files/1227061/gaga.dummy.zip)

### Setup

* OS: Win10 x64
* Python version: 3.6.0
* beets version: 1.4.4 (**outdated**)
* Turning off plugins made problem go away (yes/no): untested

I also tested on a minimal beets config / setup on Ubuntu 17.04.

* Ubuntu 17.04
* Python 2.x
* Beets 1.4.5

It also gave me a similar result for this command (no albumdisambig result).

```
beet ls album:born way -f '$album $alb_orig_year_mm_dd $albumartist $al
bumstatus $albumtype.. $country $label $catalognum $albumdisambig zz'
```

**Comment by sampsyo** [comment]
Huh! That's interesting. There's something going on with the MusicBrainz web service API that I don't understand. Here's the XML response for the album that should have the disambiguator "special edition": https://musicbrainz.org/ws/2/release/f4ecda8e-1ece-4f5c-8be7-471c14c6ab63

As you can see, the disambiguation string doesn't show up. However, another version of that album where the disambiguator is "Special Edition" (caps *sic*) does have the string appear in the web service response: https://musicbrainz.org/ws/2/release/b695de30-91da-4cd4-8491-5740a4bbb6fb

I'm not sure what the difference is between these two. Anyway, you're right that the information should show up in $albumdisambig; we pull it out of the `disambiguation` field in the XML. It's just a mystery as to why the MB server isn't providing it in that one case.

**Comment by reosarevok** [comment]
Eh, but that's the one that should *not* have a disambiguation. 
https://musicbrainz.org/ws/2/release/7057bbc3-ba54-3a8b-aa18-a324f8a63ad8/ should - and it does.

**Comment by sampsyo** [comment]
Oops; thanks for catching that, @reosarevok. :flushed:

Just now I tried importing the test files using the (manually specified) id 7057bbc3-ba54-3a8b-aa18-a324f8a63ad8, and it *did* get an $albumdisambig field. Maybe give it another shot, @RollingStar?

**Comment by RollingStar** [comment]
I've also made a silly error. I specified the wrong MBID when I tried to reproduce on my other PC. It works as it should.
