### ISSUE TITLE
add `import --nomove` switch

### ISSUE THREAD

**Issue by dermetfan** [beetbox/beets#2657]
It would be nice if `import` had a `--nomove` / `-M` switch to override the `import.move` config key.
Currently I need to temporarily comment it out in my `config.yaml`.

After reading about `--copy` / `--nocopy` and `--write` / `--nowrite`, I expected to find `--nomove` as well.

**Comment by sampsyo** [comment]
Good idea! Also relevant here is #2627, where the proposal is to clean up all of these options into a single, mutually exclusive “file action” option.

**Comment by dermetfan** [comment]
I see, that would take care of this then.

Closing in favor of #2627.

**Comment by dertuxmalwieder** [comment]
Just wanted to push this issue as I had this very problem just an hour ago - I needed an `import --nomove` command for the first time and there is none.
