### ISSUE TITLE
Problems with gmusic plugin: Authentication Error

### ISSUE THREAD

**Issue by gboysko** [beetbox/beets#2660]
### Problem

I'm having a problem using the new `gmusic` plugin with my Google Music account (which has two factor authentication). I ran it first to collect the OAuth token. That works fine, however, when I run this command:

```sh
$ beet -vv gmusic-songs bonobo
```

Led to this problem:

```
user configuration: /home/glenn/.config/beets/config.yaml
data directory: /home/glenn/.config/beets
plugin paths: 
Sending event: pluginload
library database: /home/glenn/.config/beets/library.db
library directory: /mnt/980425CD0425AF66/MP3s.new
Sending event: library_opened
Traceback (most recent call last):
  File "/usr/local/bin/beet", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/beets/ui/__init__.py", line 1256, in main
    _raw_main(args)
  File "/usr/local/lib/python2.7/dist-packages/beets/ui/__init__.py", line 1243, in _raw_main
    subcommand.func(lib, suboptions, subargs)
  File "/usr/local/lib/python2.7/dist-packages/beetsplug/gmusic.py", line 79, in search
    'Authentication error. Please check your email and password.'
  File "/usr/local/lib/python2.7/dist-packages/beets/ui/__init__.py", line 134, in print_
    assert isinstance(strings[0], six.text_type)
AssertionError
```

### Setup

* OS: Ubuntu 16.04
* Python version: 2.7
* beets version: 1.4.5
* Turning off plugins made problem go away (yes/no): no--needed to run the `gmusic` plugin.

My configuration (output of `beet config`) is:

```yaml
directory: /mnt/980425CD0425AF66/MP3s.new
import:
#    move: yes
    write: yes
original_date: yes
asciify_paths: yes
id3v23: yes
plugins: edit embedart fetchart lastgenre scrub missing info replaygain gmusic
paths:
    default: $albumartist/$album%aunique{}/$track $title
replaygain:
    backend: gstreamer
embedart:
    ifempty: yes
    remove_art_file: yes
gmusic:
    email: 'REDACTED'
    password: 'REDACTED'
```
I can assure you that the email and password is correct.

**Comment by sampsyo** [comment]
Thanks for reporting! It also looks like there was a bug in the error handling code, which led to the ugly traceback. I committed a quick fix for that.

I don't know enough about the Google auth mechanism here to comment intelligently, but perhaps @tigranl (who contributed this version of the plugin) can help? Any ideas here?

One question that comes to mind: if you have two-factor auth enabled for your Google account, you may need to generate an application-specific password.

**Comment by gboysko** [comment]
Thanks @sampsyo. Do you know if there is any logging for plugins (the `gmusic` plugin, in particular) that I can investigate?

**Comment by tigranl** [comment]
@sampsyo you are right, if you want to use the plugin with 2FA you need to setup app-specific password.

**Comment by sampsyo** [comment]
> Thanks @sampsyo. Do you know if there is any logging for plugins (the gmusic plugin, in particular) that I can investigate?

The thing to try is verbose mode (i.e., `-vv`), but you've already done it—so, in this case, it looks like there's no more logging information available. Sorry!

**Comment by tigranl** [comment]
@gboysko I've just added app-specific password and used it in my config file — now plugin works without any issues.

**Comment by gboysko** [comment]
Thanks @tigranl. What are the steps in Google to do that? Do I need to remove a previously stored OAuth token?

**Comment by tigranl** [comment]
No, you can keep your token. Just visit https://security.google.com/settings/security/apppasswords to add a new password.

**Comment by tigranl** [comment]
Well, I guess, we need to update the doc file for 2FA users.

**Comment by gboysko** [comment]
That did it! Thanks so much. I guess that the application name can be anything (I chose `beets`). I like the red-white-blue coloring of the output.

**Comment by sampsyo** [comment]
Great! I’m glad it’s working!

Would either of you be willing to add to the documentation for the plugin to mention this wrinkle?
