### ISSUE TITLE
Directory unexpectedly imported as "Various Artists" release

### ISSUE THREAD

**Issue by arcctgx** [beetbox/beets#2669]
### Problem
I noticed something unexpected when using beets, but maybe it's just my lack of understanding of an intended behavior. I first noticed this when importing a big directory of "various" tracks, but later I narrowed it down to the following minimal example.

There are three files inside a directory (each of them just a few seconds of silence, tagged using EasyTAG).

```
~/temp/testdir $ ls
artist1_song1.mp3  artist2_song2.mp3  artist3_song3.mp3

~/temp/testdir $ tagread -l *.mp3
Artist One	Album One	2017	 3	 0:08	128 kbps	Title One
Artist Two	Album Two	2017	 6	 0:08	128 kbps	Title Two
Artist Three	Album Three	2017	 4	 0:08	128 kbps	Title Three
```

For the record, these files are tagged with both Artist and Album Artist fields (e.g. both Artist and Album Artist fields of Title One are set to Artist One). Since they are already tagged, I don't want to tag them again, so I'm using the following settings for importing:
```yaml
import:
    copy: no
    write: no
    autotag: no
```

Here's what happens when I import this directory:
```
~/temp $ > beet -vv im testdir/
user configuration: /home/arcctgx/.config/beets/config.yaml
data directory: /home/arcctgx/.config/beets
plugin paths: 
Sending event: pluginload
library database: /home/arcctgx/.config/beets/database
library directory: /home/arcctgx/music
Sending event: library_opened
Sending event: import_begin
Sending event: import_task_created
/home/arcctgx/temp/testdir
0 of 3 items replaced
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: import_task_files
Sending event: album_imported
Sending event: import
Sending event: cli_exit

~/temp $ beet ls
Artist One - Album One - Title One
Artist Three - Album Three - Title Three
Artist Two - Album Two - Title Two

~/temp $ beet stats -e
Tracks: 3
Total time: 24.8 seconds (24.75 seconds)
Total size: 392.8 KiB (402186 bytes)
Artists: 3
Albums: 1
Album artists: 1

~/temp $ beet ls -a
Various Artists - Album One
```

The output of ```beet ls``` looks OK, what is not expected is the output of ```beet stats -e``` and ```beet ls -a```. I expected to see:
```
~/temp $ beet ls -a
Artist One - Album One
Artist Three - Album Three
Artist Two - Album Two
```
...and also to see 3 albums and 3 album artists in the output of ```beet stats -e```. The behavior is the same if I remove Album Artist fields from mp3 tags. Why did "Various Artists" artist appear? Is this behavior intended?

### Setup

* OS: Slackware Linux 14.2
* Python version: 2.7.13
* beets version: 1.4.5
* Turning off plugins made problem go away (yes/no): no

My configuration (output of `beet config`) is:

```yaml
directory: ~/music

import:
    copy: no
    write: no
    autotag: no
play:
    command: /usr/bin/audacious
    use_folders: no
    raw: no
    warning_threshold: 100
    relative_to:
library: ~/.config/beets/database

plugins: play
```

**Comment by sampsyo** [comment]
Hello! Yes, we do try to automatically detect when an album is a VA compilation. The idea is to help avoid misclassifications—in non-VA cases, we just guess that the first artist we find is the album artist. That can lead to confusing imports when an entire album gets filed under a single artist. So, we have a little heuristic that guess when the artists are heterogeneous enough to warrant being marked as a VA album.

You can see more discussion of the pitfalls here at https://github.com/beetbox/beets/issues/1099.

And here's where the detection happens in the code: https://github.com/beetbox/beets/blob/8833fef24945f11c16858ec2507bbdaf3120f127/beets/importer.py#L655-L664

**Comment by arcctgx** [comment]
OK, got it. Thank you for clarification.

BTW, I noticed that I can achieve the behaviour I expect by importing like this:

```
~/temp $ > beet im testdir/*
```

It's clarified now, so I guess this issue can be closed.
