### ISSUE TITLE
error: database "path" could not be opened

### ISSUE THREAD

**Issue by TheWingedCow** [beetbox/beets#2677]
### Problem

I keep getting this error when i try to import music

P.S: I have full permissions to the folder

**Comment by sampsyo** [comment]
Our apologies, but this is not enough detail to understand the problem. Please follow the instructions in the issue template for reporting bugs and (carefully) read the FAQ entry about reporting bugs.

**Comment by arcresu** [comment]
It's been some time now and we haven't heard from you. Without more detailed information it's really hard for the community to help you with this issue. If you'd still like help with this, feel free to reopen this issue or open a new one, but make sure you [include as much relevant information](https://www.cs.cornell.edu/~asampson/blog/bugrubric.html) as possible and describe how the problem can be reproduced by other users.
