### ISSUE TITLE
lyrics fetch can get stuck without timeout

### ISSUE THREAD

**Issue by Horla** [beetbox/beets#268]
When I use the command "beet lyrics", at some point (it seems to be random) it will hang forever and never finish. Using -vvv doesn't show anything.

I guess you need a library big enough to experience that bug.

**Comment by jackwilsdon** [comment]
It looks like we moved over to `requests` in 802579783699272b940845b708fba906ea3f5f4d, is this issue resolved?

**Comment by sampsyo** [comment]
Yeah, let's call this done. :heavy_check_mark:

**Comment by jrobeson** [comment]
did you folks test it? I ran into this a few months ago, but forgot to report the bug.

**Comment by sampsyo** [comment]
Hmm; no. Any ideas as to what circumstances caused it (e.g., connectivity loss)?

**Comment by jackwilsdon** [comment]
So after doing some research it looks like `requests` doesn't have a timeout set by default. Maybe we should set one?
