### ISSUE TITLE
When importer asks, giving multiple letters leads to it assuming a command

### ISSUE THREAD

**Issue by RollingStar** [beetbox/beets#2681]
### Problem

If the importer gives the user an option like import as-is, group albums, enter Id, etc., the user can mash the keyboard and still have beets interpret that as a deliberate user choice. Either beets acts on the first valid letter, or acts on the first letter if it is valid. I'm not sure which.

It would be nice if beets asked the same question again if the user response has length >1, or some other sanity check.

Windows 10 x64
Powershell
Python 3.6.2
Beets 1.4.5

**Comment by sampsyo** [comment]
Interesting point. It was built that way intentionally—so you could enter the entire word or part of it, like `skip` or `more op`, and still have the option activated—but I can see how it could create accidental errors. Maybe it would be worth looking into how other interactive tools work when you type too many letters?

**Comment by RollingStar** [comment]
the real reason this is a problem for me is when i've polluted the cmd window with output and i don't know what i'm being prompted for.

anyway, do we need full word responses as a supported feature?

**Comment by sampsyo** [comment]
I do confess that I actually like this behavior, which seems a little less pedantic than strictly requiring a single letter.

If you've lost the prompt, one way to get it back is to hit "return" after entering *nothing* to get the prompt again.

**Comment by RollingStar** [comment]
Fair enough.
