### ISSUE TITLE
Coverart file too large

### ISSUE THREAD

**Issue by plittlefield** [beetbox/beets#2684]
When importing an album yesterday, each track increased by 24Mb because the cover.jpg that was downloaded was too large.

I eventually found the reasonably sized 115Kb 500 pixels x 500 pixels cover from MusicBrainz, downloaded it manually with wget into the original folder and ran import again.

Is there a way to try MusicBrainz first and/or limit the size of the cover art file to say 500Kb?

Thanks,

Paully

beets version 1.4.5
Python version 2.7.12
plugins: embedart, fetchart, zero

**Comment by Kraymer** [comment]
Look at `maxwidth` option of embedart plugin cf http://beets.readthedocs.io/en/v1.3.17/plugins/embedart.html#configuration

**Comment by plittlefield** [comment]
Fantastic! Thanks.
