### ISSUE TITLE
`duplicates` plugin thinks there is a duplicated recording in an album with actually a duplicated recording.

### ISSUE THREAD

**Issue by doronbehar** [beetbox/beets#2690]
### Problem

There are releases in the musicbrainz database which actually have a certain recording multiple times and this causes the `duplicates` plugin report these recordings are as duplicated. I'll examine with the following example:
This release by Frank Sinatra: [`Three Original Hit Albums`](https://musicbrainz.org/release/c8a5e4d1-6656-4e09-90f5-fe4c37728729), has the recording of the track [`I Get Along Without You Very Well`](https://musicbrainz.org/recording/80a7fb9c-edf8-49aa-a900-6cdcca3529db) twice, as you can see in [this](https://musicbrainz.org/track/a3b6d068-0c45-32c1-afe7-dcedf24407fa) and [this](https://musicbrainz.org/track/f2f23b35-6928-3c6c-9c48-4b2f7ff5cf38) tracks.

IMO, the `duplicates` plugin should check before reporting whether or not these tracks appear in the database twice as well as within the local files.

**Comment by sampsyo** [comment]
Interesting point! I'd be interested to hear more thoughts on exactly how this should work. The current algorithm for the `duplicates` plugin is pretty simple: look at all your tracks (or all the tracks that match the given query) and look for duplicates among them. There are no queries to the MusicBrainz Web service. There is also no interaction with the album structures in the beets database; items are processed completely independently.

How should an algorithm work that respects the fact that some duplicates might be intentional? It's not completely clear to me how this would work—or how we could make it efficient, without querying the MBWS for every album.

**Comment by doronbehar** [comment]
Well I think that even if we only check the `track` tag for each of those files, and see if it's different, we should be OK.

**Comment by sampsyo** [comment]
Hmm… if that's enough, may I recommend just adding `track` to the `keys` section of your `duplicates` config? http://docs.beets.io/en/v1.4.5/plugins/duplicates.html#configuration

That should consider items with different `track` values to be different.

**Comment by doronbehar** [comment]
OK.., I had no idea I can configure all of these options, it's great, but still there is one question that should bother us:

We can see that the different tracks which are reported as duplicates are:

https://musicbrainz.org/track/a3b6d068-0c45-32c1-afe7-dcedf24407fa
https://musicbrainz.org/track/f2f23b35-6928-3c6c-9c48-4b2f7ff5cf38

Both have a different ID. Are those supposed to be the values of `mb_trackid`? Because if so, then the problem is not with the `duplicates` plugin but with the value `mb_trackid` gets in general. It's a fact that on my machine, the value of this tag is not different for the reported duplicated files.

**Comment by sampsyo** [comment]
Yes. For historical reasons, mb_trackid actually holds the recording ID. See also #406.

**Comment by doronbehar** [comment]
Hmm, it seems no one responded @mineo's https://github.com/beetbox/beets/issues/406#issuecomment-40938938 which asserts pretty much what I was saying as well. I think a PR should be made.

**Comment by sampsyo** [comment]
Indeed! Any help would be appreciated.

**Comment by doronbehar** [comment]
Is `mb_recordingid` being used in beets' database?

**Comment by sampsyo** [comment]
Nope, we don't have a field by that name. The recording ID goes in `mb_trackid`. (This is because, prior to MusicBrainz "NGS," that ID was called the "track ID," and changing the name now would break some configurations.)
