### ISSUE TITLE
Beets LastGenre Plugin Doesn't Find Many Genres vs LastFM.NG

### ISSUE THREAD

**Issue by Enverex** [beetbox/beets#2691]
I'm trying to switch from using Picard with LastFM.NG to Beets due to the Picard GUI dying if you throw too much at it at once (and I can't break my collection down small enough for it not to crash on just individual letters).

Anyway, the issue is that LastGenre, even when set more permissive than LastFM.NG, still either A) doesn't find any tags at all, B) seems to have less tags or C) seems to use less relevant tags.

If this is something someone can look into, I can provide albums that exhibit this more clearly. As an initial example, "Don't Get Smart" by "Jim's Big Ego" finds no tags at all with LastGenre, but LastFM.NG tags them with "Rock" and "Humor".

**Comment by sampsyo** [comment]
Interesting! It's hard to know exactly what's going on without doing some more digging. Please update this thread if you find any evidence (by looking at the verbose log, digging into the code, examining the responses from the Last.fm API, looking over the whitelist, temporarily disabling the whitelist, etc.) about why the genres you like aren't being found.

**Comment by arcresu** [comment]
It's been some time now and we haven't heard back from you. Without more detailed information it's really hard for the community to help you with this issue. If you'd still like help with this, feel free to reopen this issue or open a new one, but make sure you [include as much relevant information](https://www.cs.cornell.edu/~asampson/blog/bugrubric.html) as possible and describe how the problem can be reproduced by other users.
