### ISSUE TITLE
beets/test/rsrc/only-magic-bytes.jpg reportedly contains Windows-XP-era virus

### ISSUE THREAD

**Issue by rayrrr** [beetbox/beets#2698]
### Problem

When running a virus scan on `/beets/test/rsrc/only-magic-bytes.jpg` (or viewing the file on GitHub with antivirus protection enabled), it is reported to contain ye olde [MS04-028](https://www.trendmicro.com/vinfo/us/threat-encyclopedia/malware/expl_ms04-028.a) virus.

<img width="320" alt="screen shot 2017-09-24 at 9 43 36 pm" src="https://user-images.githubusercontent.com/7869818/30790159-5251a52c-a178-11e7-9af8-bccef4ebb56b.png">

### Setup

* OS: Mac
* Antivirus version: Avast Free
* beets version: 1.4.5
* Turning off plugins made problem go away (yes/no): n/a

**Comment by sampsyo** [comment]
Hmm; that’s odd. That file is only 622 bytes, so it’s somewhat hard to believe it’s actually harboring malware. Is there a chance Avast is just being overzealous here?

**Comment by nathdwek** [comment]
I personally built this file by hand. It is just a one pixel jpeg file with no exif header to check that recognizing a jpeg based only on the magic bytes works.
I guess it can trip some other applications, after all, it trips python, but to the best of my abilities (I do not sign my commits anymore, yada yada), I can guarantee it is safe.
