### ISSUE TITLE
Tag some issues for hacktoberfest?

### ISSUE THREAD

**Issue by nathdwek** [beetbox/beets#2703]
For [Hacktoberfest 2017](https://hacktoberfest.digitalocean.com/), we could tag some entry-level difficulty/size issues with the `Hacktoberfest`url label in order to attract new contributors.

**Comment by sampsyo** [comment]
Very cool! It looks like all we have to do is apply that label to participate? I’m all for it.

We can start with issues tagged `bitesize`, which we usually use for “entry-level” tasks.

**Comment by arcresu** [comment]
Looks like this has come and gone, and some issues got the `Hacktoberfest` label. I think we can close this until the next time this comes around :)
