### ISSUE TITLE
edit operation fails badly when albumart file missing

### ISSUE THREAD

**Issue by Vrihub** [beetbox/beets#2724]
### Problem

If I delete the albumart.jpg file from a directory in the beets tree and then I run an `edit` command that implies renaming the directory (e.g. because I changed a variable that is used in the directory name), beets exits badly and leaves me with two corrupted directories.

```
moving album art (oldpath) to (newpath)
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/beets-1.4.4-py2.7.egg/beets/util/__init__.py", line 471, in move
    shutil.copyfile(path, dest)
  File "/usr/lib/python2.7/shutil.py", line 82, in copyfile
    with open(src, 'rb') as fsrc:
IOError: [Errno 2] No such file or directory: (the albumart.jpg file that I had deleted)
```

Also, I'm left with two incomplete directories:
- The new directory, renamed as per my `edit` command, containing only the first file of the album
- The old directory, containing the remaining files

Suggested fix: the edit operation should ignore silently if the albumart file is missing.

### Setup

* OS: Linux
* Python version: 2.7.13
* beets version: 1.4.4

**Comment by sampsyo** [comment]
Indeed! This is, I think, the same root issue as in #1926—that is, we should log an error instead of crashing when moving fails *in any command*. (I think we can probably address this with some centralized logic instead of changing every command that moves files.) Does that look right to you?

**Comment by Vrihub** [comment]
> Does that look right to you?

Yes, I thought it was only an `edit` problem; sorry but I couldn't catch #1926 and  #2419 before opening this issue. So I think you can mark this as a duplicate and try to find a more general solution to the problem.

**Comment by sampsyo** [comment]
OK! No problem at all. :sparkles:
