### ISSUE TITLE
README and Documentation should warn users to back up library

### ISSUE THREAD

**Issue by andrewbenedictwallace** [beetbox/beets#2727]
At present, it seems that some difficult bugs are resulting in songs being incorrectly marked as duplicates and deleted:
https://github.com/beetbox/beets/issues/2608
https://github.com/beetbox/beets/issues/2499

Under the circumstances, I think it's essential to put a warning near the top the README and somewhere prominent in the Documentation, telling users to back up their collections first!

**Comment by sampsyo** [comment]
If you're interested in something like this, please consider making a pull request adding a note to the "Using the Auto-Tagger" guide or perhaps the "Getting Started" guide. A warning at the top of the README is not appropriate.

**Comment by andrewbenedictwallace** [comment]
Also, https://github.com/beetbox/beets/issues/149!

**Comment by andrewbenedictwallace** [comment]
And I disagree about the readme. Like, losing songs is pretty serious and can make people pretty angry! Especially when obvious ways to mitigate the problem have been sitting around in the issues for 9 years!

But I don't shouldn't be so harsh. This _is_ really cool software and I totally appreciate all your work on it! I'll try to make some contributions (starting with the docs) when I get some free time!

**Comment by sampsyo** [comment]
Thank you for the input! I do agree that we should be warning people, but I gently disagree about a big warning on the README. We encourage people heavily to go through the guides in the documentation (beets can be bewildering without doing that), so I think that's the natural home for a suggestion to start with good backups.

**Comment by andrewbenedictwallace** [comment]
Submitted a pull request! Could probably be worded better, and maybe discuss different options (e.g. Dropbox works but is a pain, a local copy is super fast and easy if you have a copy-on-write filesystem).

**Comment by RollingStar** [comment]
None of the "beets deleted my files" bugs would be all that bad, if beets sent files to the trash or a trash folder instead of outright deleting them. #149 was already mentioned.

**Comment by RollingStar** [comment]
yes, some warning belongs somewhere

**Comment by RollingStar** [comment]
There's an open question of where the warnings should go.

**Comment by justinmayer** [comment]
I submitted PR #3796 to address this issue, adding a section to the _Getting Started_ documentation encouraging users to back up their music libraries and databases.

**Comment by RollingStar** [comment]
FYI:

> Note: The Linux implementation is not very good and not maintained. Help welcome. If no one steps up to help maintain it, I will eventually remove Linux support.

**Comment by justinmayer** [comment]
I’m still working on this. Must allocate some time to split the related PR into two.

**Comment by wisp3rwind** [comment]
Not stale; PRs are underway

**Comment by justinmayer** [comment]
This issue is still relevant.

**Comment by sampsyo** [comment]
Just checking, @justinmayer: do you think we still need anything in this issue that's not already covered by #149, which is about the "move to trash" option? (And if so, what should this issue focus on? I've sort of lost track.)
