### ISSUE TITLE
hook: Crash when trying to access {item.track} in command

### ISSUE THREAD

**Issue by broddo** [beetbox/beets#2740]
I'm playing around with hook in the hope to use it to keep a lossy version of my flac lib. I came across this issue when trying to generate a new path based on the imported item.

Here's the relevant part of the config:

```
hook:
    hooks:
        - event: write
          command: echo "writing track number {item.track}"
```

And the error:

```
File "/usr/local/lib/python2.7/site-packages/beetsplug/hook.py", line 68, in convert_field
    converted = converted.decode(self._coding)
AttributeError: 'int' object has no attribute 'decode'
```

This on Freebsd

**Comment by sampsyo** [comment]
Thank you! It looks like the plugin has a problem handing non-string fields. I’d guess that other numeric fields, like `year` or `disc`, would have the same problem.

**Comment by jhermann** [comment]
Solved, can be closed.

**Comment by sampsyo** [comment]
Indeed; thanks!
