### ISSUE TITLE
Updating library / Tagging only one field

### ISSUE THREAD

**Issue by firewater2** [beetbox/beets#2744]
Hello. I'm new to the program and am slightly confused regarding basic usage of it. 

I keep all my music in one folder, and want to keep it there. My config file has:

```
directory:  M:/Media/Audio
import:
    copy: no
```

I want to know two things:

1. When I add new music to this path, am I correct in thinking beets won't automatically recognize the new files? It seems I have to tell it to update. In which case, should I rerun `beet import -A "M:/Media/Audio"` , or is it the command `beet update`?

2. Beets imports the metadata as it was when I imported the files, right? So for example, if I manually change the date field of an album (without beets) after import, beets will have in its database the file listed with the old unmodified date, right?

3. I'm only interested on tagging the date field. What command should I run to scan through my library and autotag only that field? And, will it use the original date, or will it try to guess what particular release I've got and go with that? Because I'm much more interested on the former.

**Comment by sampsyo** [comment]
1. import. See also Incremental mode.
2. Yes.
3. Sorry, this isn’t current;t possible.
