### ISSUE TITLE
Backing up tags

### ISSUE THREAD

**Issue by firewater2** [beetbox/beets#2745]
I'm interested on setting up a backup for all my tags, some of them unrecoverable (<first played>, <play count>), in case my drive fails. I don't have a backup of the actual audio files, as my collection is quite big (1Tb+) and I don't have the space for a backup like that.

Is there any way beets can backup my tags, and then import them? The ideal scenario would obviously not require the original files to be present for the tags to be imported, rather it would recognize them by similar metadata.

**Comment by sampsyo** [comment]
Sorry, we don’t have a feature like that.
