### ISSUE TITLE
beet import deletes my files

### ISSUE THREAD

**Issue by imp1sh** [beetbox/beets#2746]
### Problem

I've been running through import procedures quite a lot of time.
What I just did now is rebuild my database, cause for other reasons I don't have my db file. So I run`beet import /mnt/audio/alben` while the target directory for imported files is exactly the same as the source.
All just worked fine up until there was a piece from Anouk that wanted some updating.
https://paste.debian.net/997152/

I already was working on the next import iteration when suddenly an error message appeared saying "No such file or directory". The beet import procedure suddenly aborted. Now my files are gone.
That's what's left:
```
/mnt/audio/alben/Anouk % find .
.
./Anouk - Who,s Your Momma
./Anouk - Who,s Your Momma/AlbumArt_{46F6B46A-5CE7-47E5-B325-E1EC83B621DC}_Small.jpg
./Anouk - Who,s Your Momma/AlbumArt_{46F6B46A-5CE7-47E5-B325-E1EC83B621DC}_Large.jpg
./Anouk - Who,s Your Momma/album.nfo
./Anouk - Who,s Your Momma/Folder.jpg
./Anouk - Who,s Your Momma/desktop.ini
./Anouk - Who,s Your Momma/AlbumArtSmall.jpg
./Anouk - Who,s Your Momma/12 Good God (The Anonymous Remix).mp3
./Who's Your Momma
```

Running this command in verbose (`-vv`) mode:
can't do it again...

Here's a link to the music files that trigger the bug (if relevant): 
gone

### Setup

* OS: FreeBSD Jail 11.0
* Python version: 2.7.14
* beets version: 1.4.2
* Turning off plugins made problem go away (yes/no): 
no plugins loaded

My configuration (output of `beet config`) is:

```yaml
beet config
directory: /mnt/audio/alben

import:
    move: yes
library: ~/beetslibrary.blb
```

**Comment by sampsyo** [comment]
Hi! FWIW, this setup is not recommended: having the source and destination point to the same place can cause trouble. Instead, turn off moving of files with -M.

In any case, the data loss is troubling! Do you have instructions to reproduce the problem?

**Comment by imp1sh** [comment]
I recovered the files from an older ZFS snapshot and tried to import it again. The difference this time was that beets did not say: 
```
This album is already in the library!
Old: 11 items, MP3, 320kbps, 38:49, 90.7 MiB
New: 11 items, MP3, 320kbps, 38:49, 90.7 MiB
[S]kip new, Keep both, Remove old? R
```
FYI, there are two subfolders in ./alben/Anouk/
1563 drwxrwxr-x    2 Jonathan  Jonathan     9B 23 Nov. 09:58 Anouk - Who,s Your Momma
5247 drwxrwxr-x+   2 Jonathan  Jonathan     2B 23 Nov. 09:58 Who's Your Momma

The files originally came from the folder "Anouk - Who,s Your Momma".
The step above moved them in the folder named "Who's Your Momma".

After first successfull import I **copied** the mp3 files back to "Anouk - Who,s Your Momma" and imported again.
This time I was able to reproduce the problem. With the same choice I made roginally [A] for "Apply" and [R] for "Remove old" my files were gone once again.

**Comment by sampsyo** [comment]
Hmm, I think I might partially understand… could this be #702 or #716? When you selected "remove old," which files were deleted? Were they the same files as the ones being imported?

**Comment by imp1sh** [comment]
The files that I tried to import were the exact same as those that were already in the database.
I chose R for "remove old" during the import process. So the files in the destination are being deleted which is expected behaviour.
The files that are being imported are not copied to the destination folder though. That's the problem.
I don't know if it connects to one of your listed issues.
Anyhow, beets should not just delete my files, I consider that harmful. In my case it's not that bad but damage might be bigger in other scenarios.

**Comment by sampsyo** [comment]
Hmm… I guess I still don't quite understand. If you try to import files that are already in your library, this triggers a "re-import" (see the docs), so they won't be detected as a duplicate. Can you verify exactly which files were involved here? (Or, can you check whether any of the bugs I liked above are relevant?)

**Comment by jr0n** [comment]
This is a pretty nasty bug that is simple to reproduce on my machine. 

`user@DESKTOP:~/.config/beets$ beet remove -d
error: No matching items found.
user@DESKTOP:~/.config/beets$ beet import /mnt/c/Users/1/Desktop/testtag/

/mnt/c/Users/1/Desktop/testtag/(2007) Future Future Future Perfect (Limited Edition) (FLAC) (13 items)
Correcting tags from:
    Freezepop - Future Future Future Perfect (Limited Edition)
To:
    Freezepop - Future Future Future Perfect
URL:
    https://musicbrainz.org/release/a82503b2-3bda-4fa1-ac72-be0bc7698d49
(Similarity: 98.2%) (album, tracks) (CD, 2007, US, Archenemy Record Company, limited edition)
 * Get Drunk With Me         -> Get Drunk With Milk (title)
 * Do You Like My Wang?      -> Do You Like My Wang™? (title)
 * Afterparty (Extended Mix) -> Afterparty (extended mix)
[A]pply, More candidates, Skip, Use as-is, as Tracks, Group albums,
Enter search, enter Id, aBort? A
Error: No such file or directory while copying /mnt/c/Users/1/Desktop/testtag/(2007) Future Future Future Perfect (Limited Edition) (FLAC)/08 - Freezepop - Do You Like My Wang .flac to /mnt/c/Users/1/Desktop/beets/F/Freezepop-Future_Future_Future_Perfect-2007/08-Do_You_Like_My_Wang™?.flac
user@DESKTOP:~/.config/beets$ beet remove -d

/mnt/c/Users/1/Desktop/beets/F/Freezepop-Future_Future_Future_Perfect-2007/01-Less_Talk_More_Rokk.flac - Less Talk More Rokk
/mnt/c/Users/1/Desktop/testtag/(2007) Future Future Future Perfect (Limited Edition) (FLAC)/02 - Freezepop - Pop Music Is Not a Crime.flac - Pop Music Is Not a Crime
/mnt/c/Users/1/Desktop/testtag/(2007) Future Future Future Perfect (Limited Edition) (FLAC)/03 - Freezepop - Frontload.flac - Frontload
/mnt/c/Users/1/Desktop/testtag/(2007) Future Future Future Perfect (Limited Edition) (FLAC)/04 - Freezepop - Thought Balloon.flac - Thought Balloon
/mnt/c/Users/1/Desktop/testtag/(2007) Future Future Future Perfect (Limited Edition) (FLAC)/05 - Freezepop - Get Drunk With Me.flac - Get Drunk With Milk
/mnt/c/Users/1/Desktop/testtag/(2007) Future Future Future Perfect (Limited Edition) (FLAC)/06 - Freezepop - Ninja of Love.flac - Ninja of Love
/mnt/c/Users/1/Desktop/testtag/(2007) Future Future Future Perfect (Limited Edition) (FLAC)/07 - Freezepop - Brainpower.flac - Brainpower
/mnt/c/Users/1/Desktop/testtag/(2007) Future Future Future Perfect (Limited Edition) (FLAC)/08 - Freezepop - Do You Like My Wang .flac - Do You Like My Wang™?
/mnt/c/Users/1/Desktop/testtag/(2007) Future Future Future Perfect (Limited Edition) (FLAC)/09 - Freezepop - He Says She Says.flac - He Says She Says
/mnt/c/Users/1/Desktop/testtag/(2007) Future Future Future Perfect (Limited Edition) (FLAC)/10 - Freezepop - Do You Like Boys .flac - Do You Like Boys?
/mnt/c/Users/1/Desktop/testtag/(2007) Future Future Future Perfect (Limited Edition) (FLAC)/11 - Freezepop - Retired Tennis Pro.flac - Retired Tennis Pro
/mnt/c/Users/1/Desktop/beets/F/Freezepop-Future_Future_Future_Perfect-2007/12-Swimming_Pool.flac - Swimming Pool
/mnt/c/Users/1/Desktop/beets/F/Freezepop-Future_Future_Future_Perfect-2007/13-Afterparty_(extended_mix).flac - Afterparty (extended mix)
Really DELETE 13 files (y/n)? y`

As you can see, beets is deleting from both the source and destination path.

Beets config:
`library: library.db
directory: /mnt/c/Users/1/Desktop/beets/
import:
    timid: yes
 #   autotag: no

musicbrainz:
    searchlimit: 10

match:
    preferred:
        media: ['CD']
        original_year: yes
    ignored: missing_tracks unmatched_tracks

replace:
    '\s+': _

paths:
    default: %left{$albumartist,1}/$albumartist-$album-$year/$track-$title`

Removing the replace option in the config eliminates the issue.

**Comment by jr0n** [comment]
Please let me know if additional info is needed. This could wipe out someone's entire collection.

**Comment by sampsyo** [comment]
Sure! A complete verbose log and some theories about how someone else can trigger the problem would be useful.
