### ISSUE TITLE
Import should have a replace option

### ISSUE THREAD

**Issue by sekjun9878** [beetbox/beets#2760]
### Problem

At the moment, there is no way to alter the incoming metadata from auto-taggers, such as converting "typographical / smart quotes" into normal ASCII quotes. The global `replace` option only applies to filenames, so it cannot be used for this purpose.

A replace option for the importer that works globally for all metadata while importing would fix the problem.

**Comment by sekjun9878** [comment]
In the meantime I'm using the edit plugin to manually alter all typographical quotes :(

**Comment by sampsyo** [comment]
This falls under the purview of https://github.com/beetbox/beets/issues/488.
