### ISSUE TITLE
Impossible to use FetchArt if using nowrite, nocopy mode

### ISSUE THREAD

**Issue by msjyoo** [beetbox/beets#2761]
### Problem

When `write: no, copy: no` mode is used for keeping a lossless library, the album's item_path is set to the folder containing the original files. This means that album art cannot be imported without cluttering the folder containing original files.

I was expecting the album art to be stored under beet's own `directory` and `path` setting, even if there would be no other file there.

Alternatively, there could be an art_directory override config directive for use with this case.

**Comment by sampsyo** [comment]
Interesting! Is your goal here to store album art files separately from music files? You're right that the current architecture doesn't really allow anything like that.

**Comment by sekjun9878** [comment]
@sampsyo That's correct. If you imagine a read-only FLAC library mount for example, I don't think the current behaviour would allow fetchart to work in `write: no, copy: no` mode. In my use case I didn't want to overwrite the original cover files (i.e. torrent seeding needs original files preserved), so simply setting the cover name to something unique i.e. `beets_cover.ext` was sufficient as a workaround.
