### ISSUE TITLE
Discogs: Create Discogs-specific ID3 TXXX tags

### ISSUE THREAD

**Issue by nicolahinssen** [beetbox/beets#2763]
Hi,

The Discogs plugin currently uses the "TXXX:MusicBrainz Album ID" custom field for the Discogs release code. This results in "Album not found on MusicBrainz" issues in other software.

My suggestion is to create the following fields for Discogs (TXXX is customizable so that wouldn't be a problem).

Old | New
--- | ---
TXXX:MusicBrainz Album Artist Id=_1560798_ | TXXX:Discogs Album Artist Id=_1560798_
TXXX:MusicBrainz Album Id=_3175577_ | TXXX:Discogs Album Id=_3175577_
TXXX:MusicBrainz Album Release Country=_Netherlands_ |  TXXX:Discogs Album Release Country=_Netherlands_
TXXX:MusicBrainz Album Type=_Album_ | TXXX:Discogs Album Type=_Album_
TXXX:MusicBrainz Artist Id=_1560798_ | TXXX:Discogs Artist Id=_1560798_

**Comment by sampsyo** [comment]
Hello! Yes, this is very much a problem, and any help would be appreciated. Can you please leave your thoughts on #604?
