### ISSUE TITLE
MIT License

### ISSUE THREAD

**Issue by clounie** [beetbox/beets#2770]
### Problem

Curious - if beets is using Mutagen (GPLv2), then how can it validly state that it has an MIT license? Am I missing something here?

**Comment by sampsyo** [comment]
IANAL, so I don't have an authoritative answer to this question. But from my completely uninformed perspective, we're not distributing Mutagen code at all, so I don't see beets as derived work. The distribution does include instructions to obtain and install Mutagen yourself, but we don't package any dependencies or anything. This would be a problem if we, for example, bundled up a complete executable package for Windows and offered it for download—that whole would seem to be a derived work and need to be licensed under the GPL, even though the pieces are dynamically linked.

A little googling suggests that there is not a definitive answer to this question—it seems to be a gray area in the GPL. This thread, for example, summarizes some of the disagreement: https://stackoverflow.com/questions/6748333/import-a-library-that-imports-a-gpl-library

**Comment by alfiepates** [comment]
Yeah, IANAL but at no point does Mutagen code actually mix with code distributed by beets. 

It'd be different if beets offered a tarball/etc with all the deps included, but as of right now that isn't the case (and is unlikely to be the case, considering how easy installing deps is these days)

**Comment by clounie** [comment]
Makes sense - thank you for the replies.
