### ISSUE TITLE
Issue with plugins, and unable to find tags for majority of music

### ISSUE THREAD

**Issue by bigDaddyS1oth** [beetbox/beets#2779]
## Problem 1

Some issues with loading plugins.

### Led to this problem:

Running a lot of commands brings this up;

```
** error loading plugin fetchart:
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/beets/plugins.py", line 254, in load_plugins
    namespace = __import__(modname, None, None)
  File "/usr/lib/python2.7/site-packages/beetsplug/fetchart.py", line 25, in <module>
    import requests
ImportError: No module named requests

** error loading plugin lyrics:
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/beets/plugins.py", line 254, in load_plugins
    namespace = __import__(modname, None, None)
  File "/usr/lib/python2.7/site-packages/beetsplug/lyrics.py", line 28, in <module>
    import requests
ImportError: No module named requests

** error loading plugin lastgenre:
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/beets/plugins.py", line 254, in load_plugins
    namespace = __import__(modname, None, None)
  File "/usr/lib/python2.7/site-packages/beetsplug/lastgenre/__init__.py", line 27, in <module>
    import pylast
ImportError: No module named pylast

```
But I have both the `requests` and `pylast` modules.

## Problem 2

Beets seems to not be able to find tags for some of the music that I've...100% legally obtained through legal means legally (a.k.a. `youtube-dl -x`). 

#### Led to this problem:

Running `beets import /home/my_user/Music` even with the Chroma plugin gives; 

```
/home/my_user/Music (82 items)
No matching release found for 82 tracks.
For help, see: http://beets.readthedocs.org/en/latest/faq.html#nomatch
[S]kip, Use as-is, as Tracks, Group albums, Enter search, enter Id, aBort?

```

My best guess is that I should just use the fromFilename plugin, or try Discogs?

* OS: Void Linux
* Python version: 2.7.14 
* beets version:  1.4.6
* Turning off plugins made problem go away (yes/no): yes

My configuration (output of `beet config`) is:

```
directory: ~/Music

import:
    copy: no
library: ~/data/library.db
plugins: chroma
chroma:
    auto: yes

```

**Comment by sampsyo** [comment]
Hi! Although you mentioned:

> But I have both the requests and pylast modules.

These installations didn't work. Please take a look at your Python setup—sometimes this happens, for example, when you install the modules for Python 2 but run beets on Python 3.

**Comment by bigDaddyS1oth** [comment]
@sampsyo 

So 

>  for example, when you install the modules for Python 2 but run beets on Python 3.

Since `beet version` lists the Python version being 2.7.14, does that mean `pip install` is defaulting to install Python3 modules?

**Comment by bigDaddyS1oth** [comment]
@sampsyo 
 
oh, wait, hold on. I decided to `pip install beets` for shits and giggles to see if using the `pip` version would make any difference than using Void's package for it. `beet version` now returns `Python: 3.6.4`. lol wut. I'll give doing `beet import` another shot and see if anything changes.

**Comment by sampsyo** [comment]
Sounds like you've resolved this problem! Please open another ticket if you're running into a different issue.
