### ISSUE TITLE
How to install beets on Windows 10

### ISSUE THREAD

**Issue by ItsKonix** [beetbox/beets#2781]
So, Im trying to install Beets on windows. I already installed Python on my computer but I just don't get how to proceed from now on. Maybe someone can explain to me what I have to do in a step-by-step guide? And yes, Im a complete newbie to Python

**Comment by sampsyo** [comment]
Hello! Maybe you can start by describing what wasn't clear about our existing guide for installing on Windows?
http://docs.beets.io/en/v1.4.6/guides/main.html#installing-on-windows

**Comment by ItsKonix** [comment]
![grafik](https://user-images.githubusercontent.com/34820956/34557188-ac68f658-f139-11e7-98c1-56714c63986c.png)

This is the error I get every time. The console I'm using is the Python3.6(32-bit).exe
and I also installed pip double-clicking the get-pip.py file

**Comment by Vesnyx** [comment]
I believe you need to launch pip from the base line command prompt, not from the python command line. Try opening a cmd.exe window then running `pip install beets`

**Comment by ItsKonix** [comment]
Yea, thank you!
