### ISSUE TITLE
Tagging only one field

### ISSUE THREAD

**Issue by 2V3EvG4LMJFdRe** [beetbox/beets#2783]
I'm requesting this feature as I believe it would be a great addition to the program. The main use for this would be to avoid overwriting fields were one differs from the great music databases - for example a case were one has their own standard for how the "feat." part of a song is to be stored ("on the artist field" or "as a parenthesis"), or a case were one wants certain words not be capitalized ("of", "the", "an", etc). Especially difficult releases with quirky aspects, like those of classical music, would be particularly benefited as it would be common for one to have their own standards on how these are to be tagged.

**Comment by arcresu** [comment]
The use cases you describe (capitalisation of certain words, feat.) seem like they're better handled by plugins that implement the behaviour you want. There's already the [FtInTitle plugin](https://beets.readthedocs.io/en/v1.4.7/plugins/ftintitle.html) and the [The plugin](https://beets.readthedocs.io/en/v1.4.7/plugins/the.html) that sound similar to what you describe. The [Edit plugin](https://beets.readthedocs.io/en/v1.4.7/plugins/edit.html) adds a new action to the importer that allows you to manually edit the individual fields before accepting new items.

Do you think plugins (the ones I mentioned or a new one) could satisfy your requirements or is there really a case for changing beets' behaviour here? If so, how do you think this would work in terms of the interface? A new flag to any command that can modify tags? Or were you thinking more along the lines of a new option in the importer?

**Comment by GuilhermeHideki** [comment]
One thing I needed when I started using beets was "partially syncing fields" (blacklisting or whitelisting fields for update or write), for things that fell between the "use regex for this, but have a lot of false positives" and "do manually, very boring", like format artist credits like "a;b". The edit plugin helped a lot, but if I could apply the pending changes (write/update) to all fields I know I wouldn't edit, the next time I executed the command with the ``--pretend`` field, the change list would be a lot smaller

**Comment by firewater2** [comment]
I honestly feel very disconnected from my original request, I'm not sure I even understand it, specifically in how it relates to an use I could have for it. The way beets works is mostly fine for me nowadays, and any problems I have aren't related to this. Perhaps I'll remember what triggered this interest when it resurfaces as an issue, but for now I'd consider this as closed. However I'm not closing it on the basis that someone else commented their personal interest on this, up to you guys.
