### ISSUE TITLE
Python 3.6.3 ArgumentParser bug

### ISSUE THREAD

**Issue by gderber** [beetbox/beets#2784]
### Problem

Last login: Sat Jan  6 09:38:02 2018 from 192.168.2.95
Traceback (most recent call last):
  File "/usr/local/bin/beet", line 11, in <module>
    load_entry_point('beets==1.4.6', 'console_scripts', 'beet')()
  File "/usr/local/lib/python3.6/dist-packages/beets/ui/__init__.py", line 1256, in main
    _raw_main(args)
  File "/usr/local/lib/python3.6/dist-packages/beets/ui/__init__.py", line 1243, in _raw_main
    subcommand.func(lib, suboptions, subargs)
  File "/usr/local/lib/python3.6/dist-packages/beets/ui/commands.py", line 1682, in print_completion
    for line in completion_script(default_commands + plugins.commands()):
  File "/usr/local/lib/python3.6/dist-packages/beets/ui/commands.py", line 1723, in completion_script
    for opts in cmd.parser._get_all_options()[1:]:
AttributeError: 'ArgumentParser' object has no attribute '_get_all_options'

Beets works okay, I get that error message every time I log in.
### Setup

* OS: Ubuntu 17.10
* Python version: 3.6.3
* beets version: 1.4.6

**Comment by sampsyo** [comment]
Hello—it sounds like you may have installed a bash completion script, which is causing this problem. Perhaps it's out of sync with the version of beets you have installed?

**Comment by gderber** [comment]
It's possible.  I do have bash completion enabled, and I have upgraded beets a few times, including a switch from using beets with python 2.7 to python 3.6.  From my bashrc:

if [[ -x $(command -v beet) ]]; then
eval "$(beet completion)"
fi

Do you have suggestions on how to check the sync between the two?

**Comment by gderber** [comment]
I isolated some of it.  If I disable loading the 'alternate' plugin (unofficial I know). The error goes away.  Sorry it's not a beets issue, it's a plugin issue.

Any chance of incorporating the alternate into beets, that plugin hasn't been updated in a while?

**Comment by sampsyo** [comment]
Got it—yes, I think we can chalk it up to an issue in that plugin.

I don’t think anyone has proposed to make that part of the beets distribution. If you’re interested, all it requires is someone to take ownership and bring the code quality & documentation up to speed.

**Comment by gderber** [comment]
I'm certainly willing to help.  I've already had to do some modifications to get the plugin to work.  Python 3.6 didn't like the Unicode functions it was using.

For your awareness:
1. I'm still fairly new at python.  As a result I've only used python 3.x.  
2. I don't have a good python 2.7 development environment.
3. I do not know the differences between the python 2 and 3 well.  From reading the beets docs, at least part of your long term plan is a shift towards python 3.  Will it be a problem for me to use straight python3 and not worry about python 2 compatibility?  If not, is there a way I could get help with that at some point?
4. I'm super busy in real life.  So while I can do one time updates to the code, I don't feel comfortable committing to maintaining it regularly afterwards.

**Comment by sampsyo** [comment]
Yes! I’m happy to weigh in on Python 2/3 issues. Having your help to get things rolling would be super useful, even if you can’t help shepherd the plugin in the future. Maybe we can find other users to help out.

**Comment by wisp3rwind** [comment]
Do you mean the [alternatives plugin](https://github.com/geigerzaehler/beets-alternatives)? Or is there actually a `alternate` plugin (never heard of that, but maybe there is)?

If so, there's fixes for Python 2 and 3 support around in the various forks (disclaimer: including my own) of the plugin (not sure about the `ArgumentParser` thing), the original repository does not appear to be maintained anymore, though.

**Comment by gderber** [comment]
Yes, that's correct. The alternatives plugin.  I'll check out the forks, maybe use one of those as a good starting point for updating the plugin.  Thank you.
