### ISSUE TITLE
bs1770gain parameters

### ISSUE THREAD

**Issue by ghost** [beetbox/beets#2808]
(Sorry for disregarding the template, I'm waiting for Gentoo to update before starting to use beets.)
I've read replaygain.py and I wondered why bs1770gain isn't using the --replaygain option (to set the reference level to -18 LUFS). Could someone enlighten me?

**Comment by sampsyo** [comment]
Hi! FWIW, this king of general question might feel more at home in our Discourse:
https://discourse.beets.io/

But no worries. I don't think we have a good reason, other than---for some formats---we actually store BS1770 data in BS1770-specific tags.

**Comment by arcresu** [comment]
Looks like the original author's GitHub account has been deleted. Since there's nothing really actionable here, let's close this.
