### ISSUE TITLE
Special chars insensitive listing

### ISSUE THREAD

**Issue by OnekO** [beetbox/beets#2811]
Hi!

I've problems listing songs with special chars on them (like áéíóú), because in spanish is quite common forget the special accents. So if I'm looking for every song with 'versión' as part of the title, I need to look for 'versión' and 'version'. That's not a problem, i can do the search twice. But for plugins like lastimport... yes, there is a problem, I've tons of missing songs for that.

Any solution?

(If you need more explanations due to my english, just ask for them!)

**Comment by sampsyo** [comment]
Hello! In fact, that was the original idea behind the fuzzy plugin:
http://beets.readthedocs.io/en/v1.4.5/plugins/fuzzy.html

Of course, that’s not exactly the same as ASCII-normalized matching, but perhaps worth a try?
