### ISSUE TITLE
Beets incorrectly renames and tags files

### ISSUE THREAD

**Issue by gammelon** [beetbox/beets#2812]
### Problem

When moving files into my library folder beets applies a strange mapping to some characters (file/foldernames):
- ? -> _
- : -> _
- \- -> ☐ OR _
- . -> _ (only if . is the last character excluding potential file extensions)
I am not 100% sure about the last one though...

This is not limited to specific files or albums afaik.
The tags become corrupted too, but differently.
Example:
"blink-182"
foldername: "blink☐182"
artist-tag: "blink?182"

EDIT:
I just noticed that the tags are really messed up. All kinds of special characters (e.g. german, spanish) are missing.
I assume the problem does not occur because of the musicbrainz database being wrong, since filename and tags do not exhibit the same errors. Is this a sane assumption?

### Setup

* OS: Debian
* Python version: 3.5.3
* beets version: 1.4.6
* plugins: copyartifacts, duplicates, fromfilename, mbsync, replaygain, rewrite

**Comment by sampsyo** [comment]
Hi!

1. Please see the `replace` configuration.
2. Can you check whether your console is configured to display a suitable Unicode encoding, such as UTF-8? You may need to configure your locale to be able to display these characters in your console.

**Comment by gammelon** [comment]
Thank you for the quick response!
I used putty and ssh inside termite to access the machine beets is installed on. Both of them display the same filenames and I have seen termite correctly displaying some UTF-8 characters. Also, I just checked the filenames using FileZilla with the same result.
Concerning replace... Nice hotfix, but unfortunately it wont be able to guess whether '_' previously was '?' or ':'

**Comment by sampsyo** [comment]
Hmm... it's notoriously tricky to get putty to do the right thing for Unicode. One part of the problem may be that it's not setting the locale environment variables appropriately (e.g., `LC_ALL` may be `C`). It's worth trying to set those or use beets' own terminal encoding config settings to force UTF-8.

The replace option only affects filenames, so your Unicode data is still safe in the database.

**Comment by gammelon** [comment]
Ok, I can confirm this also happens ssh'ing in termite.
output of locale looks good to me:
LANG=en_US.UTF-8
LANGUAGE=en_US:en
LC_CTYPE=en_US.UTF-8
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_PAPER="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT="en_US.UTF-8"
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=

I have seen the `terminal_encoding` option in the docs but not how exactly it is set. Is this correct (in top-level of `config.yaml`)?
`terminal_encoding: UTF-8`

**Comment by sampsyo** [comment]
Yep.

**Comment by RollingStar** [comment]
You may also want to see `config_default.yaml` within your beets install. https://github.com/beetbox/beets/blob/master/beets/config_default.yaml#L37

My config.yaml contains some potentially useful information about `replace` options. It is mostly tested on Windows so be cautious when using it.

https://github.com/RollingStar/dial-beets/blob/master/config.yaml#L53

Finally, pay attention to `path_sep_replace`. That frustrated my efforts to remap `/`.

**Comment by gammelon** [comment]
Ok, enforcing UTF-8 in the config seems to have done the trick.
But I first need to finish importing all of my library. After that, I am going to delete the beets database and reimport it (move does not work with `copyartifacts` plugin).
So I am going to close this issue for the moment and reopen if the problems persist.
Also, thank you @RollingStar, I am probably using replace if I still get weird filenames after reimporting.
