### ISSUE TITLE
Record Bird integration

### ISSUE THREAD

**Issue by jackwilsdon** [beetbox/beets#2820]
It would be nice to have some form of [Record Bird](http://www.recordbird.com/) integration for synchronizing your music library with their site. They provide email updates (or mobile with their app) when artists have announced new songs or they have been released.

They don't appear to offer an official API, but after some snooping I've worked out these requests;

----

### Signing in
```
POST https://api.recordbird.com/v2/login/user
{
  "user": {
    "email": "mail@example.com",
    "password": "password123"
  }
}
```

This returns a load of profile information, and also sets the session cookie (named `connect.sid`), which will be needed for future requests.

----

### Searching for artists
```
GET https://api.recordbird.com/v2/search/{{query}}
```

This returns an array of matching artists with a score of how close of a match they are. From a preliminary look, it seems that anything above 10 is a pretty good match.

It also appears that this request can be made without any authorisation.

----

### Following artists
```
POST https://api.recordbird.com/v2/me/artist/{{artist_id}}
```

This request requires the `connect.sid` cookie from earlier.

----

### Unfollowing artists
```
DELETE https://api.recordbird.com/v2/me/artist/{{artist_id}}
```

This request requires the `connect.sid` cookie from earlier.

----

### List followed artists
```
GET https://api.recordbird.com/v2/me/artists
```

This request requires the `connect.sid` cookie from earlier.

----

The way I'd imagine this working would be having a `rbsync` command, which would follow any artists in the user's library and unfollow any artists which are followed on Record Bird but aren't in the user's library (although I imagine the unfollow feature being configurable via either the config file, a command line argument or both).

**Comment by sampsyo** [comment]
Neat! This looks useful—a somewhat slicker alternative to [Muspy](https://muspy.com) (c.f. [beets-follow](https://github.com/nolsto/beets-follow)).

**Comment by jackwilsdon** [comment]
Wow, didn't know Muspy existed! Looks like a nice open source project (as opposed to Record Bird which isn't open source and has no official API :cry:).

**Comment by jackwilsdon** [comment]
I'm going to go ahead and close this, as Record Bird has been sadly discontinued.
