### ISSUE TITLE
Customizing the "featured artist" format/tag

### ISSUE THREAD

**Issue by vredesbyyrd** [beetbox/beets#2832]
I am new to beets and for the last few days have been tweaking the config to my liking.  Everything is working great, but there is one thing I would like to do before I start importing my library....

I am trying to figure out a way to alter the 'featured artist' string that writes to the artist tag.  I would like to leave it in the Artist field as normal, but edit the format. 

Reason:

I could be misunderstanding how this tag works, but printing out the main artists name (AlbumArtist) seems redundant, and takes up a lot of space if the artists name is long. 

Example:

    Normal Behavior:   Clams Casino feat. A$AP Rocky 
    Wanted Behavior:   feat. A$AP Rocky 

The 'FtInTitle'  plugin moves the featured artists from the 'Artist' field to the 'Title' field...so I was going to see if I could trick it into leaving the featured artists in its normal field, but editing the format to my liking. So far no luck. 

Would this be possible through any means? Calling a bash script perhaps? I admit I am probably in a little over my head on this one. 

Hope this made sense...and if I should be asking this elsewhere or need clarification please let me know. Any pointers would be greatly appreciated. 

EDIT:

Here are a couple images further showing what I am trying to accomplish. I used to use foobar2000, and liked the way it could interpret the 'Artist' tag. It would strip whatever preceded "feat". I now use lollypop, and am attempting to get similar behavior. IMO, the way foobar displays featuring artists is cleaner. Both are still being read from the 'Artist' tag, just displaying it differently.  I usually have lollypop tiled half screen, so even a little extra space counts. If Its not possible to 'batch' edit this tag, maybe ill approach this from the player side and see if the developer of lollypop would be willing to hear me out

(BTW, the contrast on both these screenshots is all borked for some reason, looks extremely flat. Good enough to illustrate my point I suppose)

Foobar  <https://imgur.com/a/Im93U> 
Lollypop  <https://imgur.com/a/f5EwU>

**Comment by sampsyo** [comment]
Interesting! I can’t think of a way to get this batch edit to go through easily. But this might be a reasonable mode to add to the `ftintitle` plugin, which can already drop the “feat” part or move it to the title—so why not drop the other part of the $artist field?

This could also conceivably be addressed in the MusicBrainz module, where we construct the artist string by concatenating the main artist with the featuring artists.

Both of these are possible if you’re interested in doing some hacking, but I unfortunately don’t have an easy setting to offer you.

**Comment by vredesbyyrd** [comment]
> Interesting! I can’t think of a way to get this batch edit to go through easily. But this might be a reasonable mode to add to the ftintitle plugin, which can already drop the “feat” part or move it to the title—so why not drop the other part of the $artist field? 

Thanks for getting back so quick. Yeah, I was thinking the same thing regarding the ftintitle plugin. With a little hacking, i dont see why it couldn't work...in theory. I initially posted with hopes that i might have missed something obvious in the beets documentation.  When my brain power re-ups and time abides I am going to take a closer look at the plugins code. See if I can figure it out. 

And love beets btw, thanks for sharing all your awesome work!
