### ISSUE TITLE
move art_filename option to fetchart plugin config

### ISSUE THREAD

**Issue by dkanada** [beetbox/beets#2833]
It seems like cover art is not supported by default in beets, and the cover art plugin has to be installed first. In that case, shouldn't art_filename be moved to the fetchart specific config options?

**Comment by dkanada** [comment]
I have a different question then, when I imported some new albums the cover art was properly named but did not get movied with the songs. Is that a bug or is there a setting I am missing?

**Comment by sampsyo** [comment]
It’s hard to say! We can investigate if you have a way to reproduce the problem and can make detailed report.

**Comment by dkanada** [comment]
Sure! The albums causing problems were moved by the asciify_paths option, so maybe that feature was the issue.
