### ISSUE TITLE
edit plugin is not showing some fields for albums

### ISSUE THREAD

**Issue by dkanada** [beetbox/beets#2834]
I tried to add disc and artist to the album edit but they aren't showing up in the generated text file. Perhaps the edit plugin has limitations on certain tags in album mode?

Some of my albums don't have a disc number listed and I was hoping to manually fix that, but I would rather not have to fix each song. The same problem arises with the artist tag sometimes.

**Comment by dkanada** [comment]
I just found #488 which solved a lot of my automatic tagging issues in the third paragraph, I think those changes can be handled with the modify command and template functions.

**Comment by sampsyo** [comment]
Disc and artist are track-level fields (because they don’t apply to entire albums), so you’ll need to apply those to tracks instead of albums. The edit plugin can’t currently edit track fields in album mode.

**Comment by dkanada** [comment]
Ah okay, thanks for the information. I may look into expanding the edit functionality in the future, please let me know if there are any other discussions about that.
