### ISSUE TITLE
Some hyphen from MusicBrainz are the wrong hyphen

### ISSUE THREAD

**Issue by jones1008** [beetbox/beets#2839]
### Problem

In some releases/release groups/artists/recordings (etc....) there is the following hyphen -> Unicode: [(U+2010)](http://unicode.scarfboy.com/?s=%E2%80%90)
> ‐

but it should be the following hyphen -> Unicode: [(U+002D)](http://unicode.scarfboy.com/?s=-)
> \-

example: [Third Eye Blind - Semi-Charmed Life](https://musicbrainz.org/recording/a5988926-e106-43b1-ba4a-84d7da3d9626)

This can lead to some problems with plugins when searching in other databases than MusicBrainz.

### possible solution
I know that this is a MusicBrainz database mistake but it could be replaced within the beets code before writing a tag to an item.
maybe like this:
`tag = tag.replace("‐", "-")`

But since I don't know where to add this code I am asking here...

**Comment by sampsyo** [comment]
Hello! If you think data is wrong in MusicBrainz, that's the right place to fix it—you can read up on MB's style guidelines and make edits there. (But I think you may find that they actually recommend dashes, not hyphens, in cases where that's typographically correct. Reading the Chicago Manual of Style might also help. :smiley:)

If you prefer ASCII hyphens over proper dashes, you can change that in your down database with `beet modify`. Or see https://github.com/beetbox/beets/issues/488 for a proposal that would help with automatically replacing these characters in tags.

**Comment by lbesnard** [comment]
@sampsyo I would like to comment on this, but happy to lodge a new issue but as it seems to be the same, I decided to add it here as it could also help someone else like I. 

I'm importing this artist named "**-M-**" . However, to ```cd``` to the artist folder, I have to do the following
```cd `echo -e '\u2010'm'\u2010'```

Definitely not practical.

I tried to go around the issue by adding the following lines in my beet config (see http://unicode.scarfboy.com/?s=%E2%80%90):
```yaml
replace:                                                                                                                                                                   
    b'\xe2\x80\x90': '-'                                                                      
    u'\u2010': '-' 
```

However after doing a ```beet move```, i get
```
beet move albumartist:"-M-"
Moving 0 items (11 already in place).
```

I'm pretty sure my unicode is probably not written the proper way

**Comment by wisp3rwind** [comment]
> ```yaml
> replace:                                                                                                                                                                   
>     b'\xe2\x80\x90': '-'                                                                      
>     u'\u2010': '-' 
> ```

> I'm pretty sure my unicode is probably not written the proper way

I don't think you should put those `b` and `u` prefixes there: The configuration file is YAML after all, not a Python source file, cf. [the documentation](https://beets.readthedocs.io/en/stable/reference/config.html?highlight=replace#replace).

**Comment by lbesnard** [comment]
thanks, for the record the following fixed it (at least one of the three...):

```yaml
replace:
    '[\xe2\x80\x90]': '-'
    '[\u2010]': '-'
    '‐': '-'

```
