### ISSUE TITLE
BEETSDIR environment variable being ignored?

### ISSUE THREAD

**Issue by AndyIbanez** [beetbox/beets#2842]
### Problem

In macOS, I want to keep all beets files in a location I control (/Vault/Music/Beets) to keep things organized. My config file is located in /Vault/Music/Beets/Configs/config.yaml, so I have set the env var BEETSDIR as described in the tutorial.

So I did `vim ~/.bash_profile` and copied and wrote the following:

`BEETSDIR=/Volumes/Vault/Music/Beets/Configs`

To write the directory I just dragged the directory into terminal to minimize typing errors, so I can say that the path is 100% correct.

So I reloaded my profile (`source ~/.bash_profile`) and Beets is still trying to use the config file at the default path.

Running this command in verbose (`-vv`) mode:

I'm pasting a very minimal version of the first lines of the command:

```
Andys-iMac:~ andyibanez$ echo $BEETSDIR
/Volumes/Vault/Music/Beets/Configs
Andys-iMac:~ andyibanez$ beet -vv import /Volumes/Anime\ 2/Music/Sorted/__four/Marchen\ Madchen\ ED\ Single\ -\ sleepland 
no user configuration found at /Users/andyibanez/.config/beets/config.yaml
data directory: /Users/andyibanez/.config/beets
plugin paths: 
Sending event: pluginload
library database: /Users/andyibanez/.config/beets/library.db
library directory: /Users/andyibanez/Music
```
Like you can see there seem to be no references to the new config file.

I noticed this because I disabled autotagging on my config file, but Beets insists on using MusicBrainz anyway.

### Setup

* OS: macOS High Sierra 10.13.3
* Python version: Python version 3.6.4
* beets version: beets version 1.4.6
* Turning off plugins made problem go away (yes/no): I have no plugins loaded.

**Comment by sampsyo** [comment]
Did you use `export` to set the environment variable so invoked processes can see it?

**Comment by AndyIbanez** [comment]
Thanks, I forgot about `export` the env var. My apologies for wasting your time.

I have solved the issue. I was coming across different issues but they were entirely my fault. I got Beets running as I like it.

Thanks again for your help.

**Comment by sampsyo** [comment]
Fantastic!

No, don't worry about that. That file will get written when there's state to store (i.e., some imports complete, or incremental mode is used).
