### ISSUE TITLE
Option to clear terminal after each album during import

### ISSUE THREAD

**Issue by gramster** [beetbox/beets#2853]
### Problem

It can be hard to see what's going on; the display can get pretty noisy. It would help at least if I knew what I was looking at was all relevant to the current album being imported.

**Comment by sampsyo** [comment]
Sounds like a reasonable option! I could have sworn that there was a previous suggestion like this, but all I can find is #1593.

**Comment by jackwilsdon** [comment]
@sampsyo possibly #151?

**Comment by sampsyo** [comment]
Awesome; yes! Thanks, @jackwilsdon!
