### ISSUE TITLE
lastgenre: Command option to fetch track genres 

### ISSUE THREAD

**Issue by jones1008** [beetbox/beets#2856]
When you run the the lastgenre plugin manually with `beet lastgenre [QUERY]` [according to the documentation](http://beets.readthedocs.io/en/v1.4.6/plugins/lastgenre.html#running-manually) it is only possible to

    "fetch genres for albums matching a certain query"

but not on a track/item level...
Why shouldn't it be possible to also match items/tracks when executing this plugin manually? Can this feature be implemented?

(this issue is a follow up from #2843)

**Comment by sampsyo** [comment]
Thanks! I think this should be reasonable.

**Comment by kopfing** [comment]
would love this!

**Comment by pyyhttu** [comment]
Shouldn't this feature request be closed as resolved, as I see [#3220](https://github.com/beetbox/beets/pull/3220) pull request merged, and [lastgenre docs](https://beets.readthedocs.io/en/stable/plugins/lastgenre.html#running-manually) now also mention: _"To match individual tracks or singletons, use the -A switch: beet lastgenre -A [QUERY]."_?

Different thing is if lastgenre plugin is working atm. at all (if anyone can confirm). I wasn't able to set it up to fetch or write track, nor artist/album level genres, but that's a separate issue to be opened.

**Comment by sampsyo** [comment]
Yes indeed, looks like it!

And also yes—please do open a separate bug if it looks like communicating with last.fm is broken altogether.
