### ISSUE TITLE
Beets is Slow Compared to Other Taggers

### ISSUE THREAD

**Issue by xerofoify** [beetbox/beets#2858]
### Problem
I have no idea what your tagger is this slow but it's so slow it actually stalls. How are you indexing files as I am doing 60GBs of music and it's so slow I have to kill it.
(Describe your problem, feature request, or discussion topic here. If you're reporting a bug, please fill out this and the "Setup" section below. Otherwise, you can delete them.)

Running this command in verbose (`-vv`) mode:

```sh
$ beet -vv (... paste here ...)
```

Led to this problem:

```
(paste here)
```

Here's a link to the music files that trigger the bug (if relevant): 

### Setup

* OS: 
* Python version: 
* beets version: 
* Turning off plugins made problem go away (yes/no): 

My configuration (output of `beet config`) is:

```yaml
(paste here)
```

**Comment by wisp3rwind** [comment]
Beets is certainly not the fastest for some of the operations, but to my knowledge it usually won't stall. 

However, you did not provide any detail on what you did (and what part of it seemed slow) and under which environemnt (OS/kernel, file systems, beets version and plugins) you are working. That's what the issue template you pasted unmodified should contain. The way you explained your issue, it is plainly impossible to tell where the actual problem might be. Closing this for now.
