### ISSUE TITLE
"surrogates not allowed"-Error when executing from php script

### ISSUE THREAD

**Issue by jones1008** [beetbox/beets#2868]
## Surrogates Problem:
So I try to execute a `beet list` query within a bash script. Here is a simplified version of it called `test.sh`:
```shell
#!/bin/bash
set -e

replacechar=$'\xe2\x80\x90'
tracks=$(beet -vv list $replacechar)
echo "$tracks"
```
With that script I want to search for items in my library containing [this special character](http://unicode.scarfboy.com/?s=%E2%80%90).

When I call this bash script as user `root` or user `www-data` manuelly via the command line the script runs perfectly.
But when I call it via the following php script it throws me an error from beets.
```php
<?php
    shell_exec('/path/to/test.sh >> /path/to/log 2>&1');
?>
```
### Error:
```python
user configuration: /var/www/.config/beets/config.yaml
data directory: /var/www/.config/beets
plugin paths:
Sending event: pluginload
lyrics: Disabling google source: no API key configured.
library database: /primary/beets/musiclibrary.db
library directory: /primary/nextcloud/Jones/files/Musik
Sending event: library_opened
Traceback (most recent call last):
  File "/usr/local/bin/beet", line 11, in <module>
    load_entry_point('beets==1.4.6', 'console_scripts', 'beet')()
  File "/usr/local/lib/python3.5/dist-packages/beets/ui/__init__.py", line 1256, in main
    _raw_main(args)
  File "/usr/local/lib/python3.5/dist-packages/beets/ui/__init__.py", line 1243, in _raw_main
    subcommand.func(lib, suboptions, subargs)
  File "/usr/local/lib/python3.5/dist-packages/beets/ui/commands.py", line 1053, in list_func
    list_items(lib, decargs(args), opts.album)
  File "/usr/local/lib/python3.5/dist-packages/beets/ui/commands.py", line 1048, in list_items
    for item in lib.items(query):
  File "/usr/local/lib/python3.5/dist-packages/beets/library.py", line 1377, in items
    return self._fetch(Item, query, sort or self.get_default_item_sort())
  File "/usr/local/lib/python3.5/dist-packages/beets/library.py", line 1352, in _fetch
    model_cls, query, sort
  File "/usr/local/lib/python3.5/dist-packages/beets/dbcore/db.py", line 898, in _fetch
    rows = tx.query(sql, subvals)
  File "/usr/local/lib/python3.5/dist-packages/beets/dbcore/db.py", line 709, in query
    cursor = self.db._connection().execute(statement, subvals)
UnicodeEncodeError: 'utf-8' codec can't encode character '\udce2' in position 1: surrogates not allowed
```
Hope you can help me with that :)

### Setup

* OS: Debian Jessie 4.9.58+
* Python version: 3.5.3
* beets version: 1.4.6

My configuration is:

```yaml
directory: /path/to/new/music
library: /path/to/library.db

import:
 move: yes
 copy: no
 log: /var/log/beets/import.log
 duplicate_action: remove
 quiet_fallback: asis

match:
 strong_rec_thresh: 0.10
 medium_rec_thresh: 0.25
 max_rec:
  missing_tracks: strong
 preferred:
  original_year: yes

plugins: lyrics lastgenre acousticbrainz popularity info zero web fromfilename smartplaylist
lyrics:
 force: yes
lastgenre:
 canonical: yes
 force: no
 count: 2
zero:
 fields: comments
 update_database: true
web:
 reverse_proxy: true
```

**Comment by sampsyo** [comment]
Wow; that's pretty subtle. I don't know what the solution here will be, but the problem is your system's locale. The `LC_*` environment variables tell programs (like beets) what encoding to use for command-line arguments; somehow, your PHP environment is instructing beets to use an encoding that can't represent the characters you want to use. Python is trying to muddle through but eventually can't progress when it needs to know what the encoded arguments are as a Unicode string.

The thing to do in your case is to set your locale environment variables in your PHP setup to something sensible like UTF-8. Or, if you can't do that, restrict the invocation to only provide arguments that match the encoding dictated by the locale.

**Comment by jones1008** [comment]
Thanks for your hint!
I could solve it with adding `LC_ALL=en_US.UTF-8` before my command within the `shell_exec`:
```php
shell_exec('LC_ALL=en_US.UTF-8 /path/to/test.sh >> /path/to/log 2>&1');
```
This adds the correct value to the environment variable LC_ALL, because it is empty when you run it via PHP.

Closing this issue now :)

**Comment by sampsyo** [comment]
Perfect! Nice work. :sparkles:
