### ISSUE TITLE
Maintain original folder structure

### ISSUE THREAD

**Issue by dbogdanov** [beetbox/beets#2869]
I have a nested folder structure for music being grouped by genres, labels and artists. The leaf folders are release folders.  Is it possible to maintain this original folder structure when importing?

**Comment by sampsyo** [comment]
Certainly! Have you tried playing with the `paths:` section in your config? You can set up nearly any nesting of directory and filenames you like based on rules like the ones you've outlined.

**Comment by dbogdanov** [comment]
The thing is I am not interested in automatic grouping according metadata fields. I did my manual grouping and my folders are more like playlists, grouping similar stuff together, being it bunches of labels, artists, or styles.

**Comment by sampsyo** [comment]
The “beets way” to deal with that would be to transfer that information from the filesystem into the beets database so it can be involved in queries, name generation, etc.

**Comment by dbogdanov** [comment]
Agreed on that, I guess I could parse the original file paths to extract and store that information. 

A more general question is, could it be more flexible to be agnostic to how the audio files are organized in folders (e.g., store where you find it after cleaning the metadata) instead of copying music to a specific library folder location and forcing a specific configurable file structure.

**Comment by sampsyo** [comment]
It's certainly possible to turn off renaming/copying! Just setting the `import.copy` option to false will leave things in place. Is that enough?

**Comment by dbogdanov** [comment]
Would it still be possible to use [paths](http://beets.readthedocs.io/en/v1.3.17/reference/config.html#path-format-configuration)? My idea is to rename release folders, but keep those folder in their original location.

**Comment by sampsyo** [comment]
No; sorry. Renaming is an all-or-nothing thing.

**Comment by dbogdanov** [comment]
I see. I guess I could have a plugin that parses the original file paths on ```beet import``` and passes that information to the beets database.

**Comment by laker-93** [comment]
I would also be interested in having this feature.
As a possible solution do you think the following could work?

Using the inline plugin: https://beets.readthedocs.io/en/stable/plugins/inline.html define a new key 'original_directory_structure' whose value is set by using some python code to inspect the original directory of the track being imported. The question is, at what stage does the inline code run? Will it have access to the original directory structure? I'm guessing if you set `move=False` then the file path of the import will still be available on disk so in theory it could be found...
