### ISSUE TITLE
Template for plugins

### ISSUE THREAD

**Issue by dosoe** [beetbox/beets#2875]
### Problem

Hi! 
I'm trying to make beets do what I would like it to do, and for that it turned out I needed to code some additional stuff, some of it in the form of a plugin. Now, I'm not a programmer and for loops are pretty much the pinnacle of my knowledge. However, what I want to do doesn't need more than that, if there wasn't a variety of additional code to just create the basic architecture of a plugin, stuff like 
```
class KeyFinderPlugin(BeetsPlugin):

    def __init__(self):
        super(KeyFinderPlugin, self).__init__()
        self.config.add({
            u'bin': u'KeyFinder',
            u'auto': True,
            u'overwrite': False,
        })

        if self.config['auto'].get(bool):
            self.import_stages = [self.imported]

    def commands(self):
        cmd = ui.Subcommand('keyfinder',
                            help=u'detect and add initial key from audio')
        cmd.func = self.command
        return [cmd]

    def command(self, lib, opts, args):
        self.find_key(lib.items(ui.decargs(args)), write=ui.should_write())

    def imported(self, session, task):
        self.find_key(task.items)
```
Would there be a way to make a plugin template that does various stuff like: 
-modify a tag
-add a tag
-parses an option from the config file and uses it
-parses an option from the CLI and uses it
-has an option set by default
-the test file corresponding to the plugin
-maybe you have other ideas
I feel like many plugins are fetching/adding/modifying tags, I think such a template could be useful. I tried to make a plugin using the template above (from the keyfinder plugin) but I can't make it work. Now this is a selfish demand but I believe it could make it easier to make beets more accessible.

**Comment by sampsyo** [comment]
Sure; sounds reasonable! Especially if you're willing to lead the charge. Could you perhaps start off a skeleton for one of these use cases and, when you run into trouble, ask so the community can help? This stripped-down `keyfinder` would be a good place to start—what's going wrong for you here?

**Comment by dosoe** [comment]
I don't know what's wrong, but I'm trying to make a working plugin using keyfinder as a template ( here https://github.com/beetbox/beets/pull/2580 ) but it doesn't work for reasons that seem to be completely independent of what is actually done in the plugin (fetching a new tag and writing it to the files). I feel like if I had a template that does all the technical stuff (setting up the class, the test etc) it could be easier in the future.

**Comment by sampsyo** [comment]
> Genuine question: How do I ask the community for help?

Posting here is a great step! You might also consider calling for help on the Discourse forum and pointing people to this thread.

> I don't know what's wrong, but I'm trying to make a working plugin using keyfinder as a template ( here #2580 ) but it doesn't work for reasons that seem to be completely independent of what is actually done in the plugin (fetching a new tag and writing it to the files). I feel like if I had a template that does all the technical stuff (setting up the class, the test etc) it could be easier in the future.

If you can report the errors you're getting, where you're getting stuck, etc., perhaps we can help you create a template that would be useful! I think this is more likely to happen quickly than someone stepping up and creating one from scratch that matches your expectations.
