### ISSUE TITLE
case insensitive regex querys

### ISSUE THREAD

**Issue by jones1008** [beetbox/beets#2877]
Is it currently possible to make a case insensitive regex query?
In the documentation it says, that [regex querys will be case sensitive](http://beets.readthedocs.io/en/v1.4.6/reference/query.html#regular-expressions).
In the python regex documentation there is a switch called [IGNORECASE](https://docs.python.org/3/library/re.html#re.IGNORECASE).

Why are regex querys in beets not case insensitive by default? Does it bring some advantage to use case sensitive regex querys?

**Comment by sampsyo** [comment]
The reason beets regexes are case sensitive is that regexes are usually case sensitive by default. See `grep`, for example.

Or, put differently, it's possible to get case insensitivity in a case sensitive context, by using character classes like `[Aa]`, but it's not possible to go the other way: to get case sensitive behavior in a case-insensitive context.

You can also include `(?i)` in your regex to switch to case insensitive mode. See [the Python docs](https://docs.python.org/3/library/re.html) for details.
