### ISSUE TITLE
txt-import: Ability to import tags from .txt file

### ISSUE THREAD

**Issue by stoits** [beetbox/beets#2884]
Hey I recently noticed that there was no plugin to allow for the importing of premade tag lists from .txt files, so I decided to write a plugin to solve that: [https://github.com/stoits/beets-plugins](url)

I'm hoping to try and integrate a variety of other aspects to it (ability to export .txt files in the correct formatting from the beets list, ability to parse and export to .csv files, etc.), for now it just performs a basic parse and import. If there's any other features that people are interested in, I would be more than happy to try and implement them!

**Comment by GuilhermeHideki** [comment]
https://github.com/stoits/beets-plugins/blob/master/txt-import.py
