### ISSUE TITLE
Docs: description of listeners is outdated

### ISSUE THREAD

**Issue by kageru** [beetbox/beets#2885]
### Problem
According to https://beets.readthedocs.io/en/v1.4.6/dev/plugins.html, `BeetsPlugin` should have a `listen` decorator. This is not the case on my system.

```py
In [1]: from beets.plugins import BeetsPlugin

In [2]: BeetsPlugin.listen
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-2-714d0503bfef> in <module>()
----> 1 BeetsPlugin.listen

AttributeError: type object 'BeetsPlugin' has no attribute 'listen'
```
Using `register_listener` works fine. Someone just removed the decorator without updating the docs.

### Setup

* OS: Arch Linux
* Python version: 3.6.4
* beets version: 1.4.6

**Comment by sampsyo** [comment]
Thanks for pointing this out! Any chance you might be able to open a PR to fix the docs?
