### ISSUE TITLE
Lyrics plugin error when writing lyrics to file

### ISSUE THREAD

**Issue by akindofcode** [beetbox/beets#2886]
### Problem

In my setup I am sharing my library between linux and windows systems. The setup works fine except when I try to write lyrics. With songs imported in my windows machine, I can't write lyrics from my unix partition and vice versa. 

For example, I import a record in windows and then I fetch the lyrics and try to write them, it works fine. If I try to do the same in linux, it doesn't work. Paths seem to be hardcoded.

The same happens with records imported in linux, same error in windows.

It seems the lyrics plugin is trying to write to the path the music was imported to originally, instead of using the music path from the config file, which points to the same directory.

Running this command in verbose (`-vv`) mode from my linux partition:

```sh
beet -vv lyrics -f ABBA 
```

Led to this problem:

```
user configuration: /home/chema/.config/beets/config.yaml
data directory: /home/chema/.config/beets
plugin paths: 
Sending event: pluginload
lyrics: Disabling google source: no API key configured.
library database: /run/media/chema/Music/musiclibrary.blb
library directory: /run/media/chema/Music
Sending event: library_opened
lyrics: got lyrics from backend: LyricsWiki
lyrics: fetched lyrics: ABBA - Gold: Greatest Hits [1992] - Dancing Queen
Sending event: write
open failed: [Errno 2] No such file or directory: b'E:\\FLAC\\ABBA\\ABBA [1992] Gold_ Greatest Hits {Polydor - 314 517 007-2}\\01 - Dancing Queen.flac'
error reading E:\FLAC\ABBA\ABBA [1992] Gold_ Greatest Hits {Polydor - 314 517 007-2}\01 - Dancing Queen.flac: [Errno 2] No such file or directory: b'E:\\FLAC\\ABBA\\ABBA [1992] Gold_ Greatest Hits {Polydor - 314 517 007-2}\\01 - Dancing Queen.flac'
Sending event: database_change
[...]
```

Path should be /run/media/chema/Music/FLAC/ABBA/ABBA [1992] Gold_ Greatest Hits {Polydor - 314 517 007-2}/01 - Dancing Queen.flac

**Comment by akindofcode** [comment]
Thank you for your answer. I am aware that the library can be relocated, I just thought that the lyrics plugin should get the files path based on the music folder stated in the beets configuration file, instead of using the absolute path.

I have currently no problem in querying the database from my windows and unix systems, no matter which system I am when importing new music. That's why I infered no absolute paths were being used, but if that's the way it works I suppose I can live with it.

**Comment by sampsyo** [comment]
Yep! Like everything that accesses files, the `lyrics` plugin uses absolute paths.
