### ISSUE TITLE
album art does not always follow music files

### ISSUE THREAD

**Issue by dkanada** [beetbox/beets#2916]
### Problem

When importing music or changing the asciify-paths option, sometimes the album art will stay in the old location.

Running this command in verbose mode:
https://pastebin.com/REFfXYJE

Led to this problem:
I think that spaces or special characters trigger this issue, such as the album name R·E·S·O·R·T or the artist Alizée. Including any special characters in the source or destination directory will break the cover import.

### Setup

os: arch linux
python version: 3.6.4
beets version: 1.4.6
no plugins enabled

My configuration is:
https://pastebin.com/8uLDt7sF

**Comment by sampsyo** [comment]
Please complete the issue template and include specific steps to reproduce.

**Comment by dkanada** [comment]
Should be good now. Just to be certain, beets should move cover art to the library if found in the album directory? I ran the check with a single album that had nine songs and one image named cover.jpg which was not moved over with the songs.

**Comment by sampsyo** [comment]
Yes, if `fetchart` is enabled and in its default configuration.
