### ISSUE TITLE
Lyrics plugin groups songs by 'artist' rather than 'albumartist'

### ISSUE THREAD

**Issue by Abrackadabra** [beetbox/beets#2924]
### Problem

When you use the lyrics plugin to create rst files with the lyrics themselves, the resulting files are grouped by the items' `artist` field rather than `albumartist`, which would arguably be more reasonable. When an artist has many collaborations where for a song the two fields are different, it may lead to situations like this:

![image](https://user-images.githubusercontent.com/1352887/39959925-3f86ed96-562a-11e8-94d2-2b2b21285b5c.png)

after a three line change ([commit link](https://github.com/Abrackadabra/beets/commit/62d5fe3692f0e93663da6c87818578a7ccef8d7c)):

![image](https://user-images.githubusercontent.com/1352887/39959931-6a219286-562a-11e8-9e78-dc76f4a6f60e.png)

Let me know if you want me to create a push request with this.

**Comment by sampsyo** [comment]
Good point! Yes, this would be useful as a PR. (Especially if you include a changelog entry.) Thanks! :sparkles:
