### ISSUE TITLE
Request for update File name,,,

### ISSUE THREAD

**Issue by KwonWon** [beetbox/beets#2955]
### Problem
Actually this is not a Problem but you guys know that File has Real name inside it. But this beetbox just shows Just his file name on the lists. If I change file name into 111.mp3, list add this as 111.

I'm not professional programmer so doesn't know how to.

I wanna change this python program into Java and activate on Windows with windowbuilder just with use this programming algorithms.
(Describe your problem, feature request, or discussion topic here. If you're reporting a bug, please fill out this and the "Setup" section below. Otherwise, you can delete them.)

Running this command in verbose (`-vv`) mode:

```sh
$ beet -vv (... paste here ...)
```

Led to this problem:

```
(paste here)
```

Here's a link to the music files that trigger the bug (if relevant): 

### Setup

* OS: 
* Python version: 
* beets version: 
* Turning off plugins made problem go away (yes/no): 

My configuration (output of `beet config`) is:

```yaml
(paste here)
```

**Comment by sampsyo** [comment]
I’m sorry; I don’t understand what you’re asking. Can you please try being more specific?

Also, trying to port beets to Java is not a good idea, if that’s what you’re proposing.

**Comment by KwonWon** [comment]
@sampsyo No, If i add abc.mp3 in beet,, We just can see abc.mp3 as a song name but
It actually has it's real name though

**Comment by KwonWon** [comment]
@sampsyo And To make bridge between Android Phone. Many of Asian use android phone that They can easily contract with it

**Comment by sampsyo** [comment]
I don’t know what you mean by “real name” or where you’re seeing the file name.

**Comment by KwonWon** [comment]
I can print File name on File lists now.
but I want to print Song Name(Each mp3 File has it's own name/ not File name) bcz some of songs' file name is different as it's real song name..
If you cannot understand what i say, i can add with Screenshot to your Email.
My purpose as this is to be contributor, I can translate into korean for Some Korean Contributors
and I'm learning Python :+1: 
Thank you

**Comment by sampsyo** [comment]
Maybe you're looking for the `beet list` command, which prints the names of songs?

**Comment by arcresu** [comment]
It's been some time now and we haven't heard from you. Without more detailed information it's really hard for the community to help you with this issue. If you'd still like help with this, feel free to reopen this issue or open a new one, but make sure you [include as much relevant information](https://www.cs.cornell.edu/~asampson/blog/bugrubric.html) as possible and describe how the problem you're trying to solve can be reproduced by other users.
