### ISSUE TITLE
Add new function I made

### ISSUE THREAD

**Issue by KwonWon** [beetbox/beets#2956]
### Problem
Let me add new function. Add two Musics into one.
It's not serial Playing system, we can Mix two musics.
I code with java.
I'm not Professional Programmer So, I just can add with Java Code.
This is what I made and Request for adding this System.
(Describe your problem, feature request, or discussion topic here. If you're reporting a bug, please fill out this and the "Setup" section below. Otherwise, you can delete them.)

Running this command in verbose (`-vv`) mode:
`public class Mixing {
	   
	   public String path;
	   public String noisePath;
	   public String noiseFileName;
	   public double f_noise_playtime;
	   public double e_noise_playtime;
	   public String savePath;
	   public ArrayList<String> filePathsList;
	   
	   
	   /**
	    * @param path
	    *            :  path filePathsList : first music path noisePath : second music path
	    *            noiseFilePath : secondmusic Name path f_noise_playtime : first music playtime
	    *            e_noise_playtime : second playtime savePath : save mixed music path
	    */
	   
	   public void runMixing(String path,ArrayList<String> wavFilesName,String noisePath, String noiseFileName,
	         double f_noise_term,double e_noise_term,String savePath) throws UnsupportedAudioFileException, IOException {

	      short[] oriData = null;
	      short[] noiseData = null;
	      
	      this.path =path;
	      this.noisePath =noisePath;
	      this.noiseFileName = noiseFileName;
	      this.f_noise_playtime = f_noise_term;
	      this.e_noise_playtime = e_noise_term;
	      this.savePath = savePath;

	      this.filePathsList = new ArrayList<String>();
	      this.filePathsList = wavFilesName;
	      //filePathsList.add("Untitled 2.wav");
	      
	      System.out.println("================================================");
	      System.out.println(path);
	      System.out.println(noisePath);
	      System.out.println(noiseFileName);
	      System.out.println(f_noise_term);
	      System.out.println(e_noise_term);
	      System.out.println(savePath);
	      

	      for (int t = 0; t < filePathsList.size(); t++) {
	         String fileName = filePathsList.get(t);
	         String savedFilePath = savePath + "_" + fileName;

	         int n = 0;

	         try {
	            DataInputStream in1;
	            // 원본파일
	            in1 = new DataInputStream(new FileInputStream(path + fileName));
	            ByteArrayOutputStream bos = new ByteArrayOutputStream();

	            try {

	               while ((n = in1.read()) != -1) {
	                  bos.write(n);
	               }
	            } catch (IOException e) {
	               e.printStackTrace();
	            }

	            ByteBuffer bb = ByteBuffer.wrap(bos.toByteArray());
	            bb.order(ByteOrder.LITTLE_ENDIAN);
	            ShortBuffer sb = bb.asShortBuffer();
	            oriData = new short[sb.capacity()];

	            for (int i = 0; i < sb.capacity(); i++) {
	               oriData[i] = sb.get(i);
	            }

	         } catch (IOException e) {
	            e.printStackTrace();
	         }

	         try {
	            DataInputStream in1;
	            // second
	            in1 = new DataInputStream(new FileInputStream(noisePath + noiseFileName));
	            ByteArrayOutputStream bos = new ByteArrayOutputStream();

	            try {

	               while ((n = in1.read()) != -1) {
	                  bos.write(n);
	               }
	            } catch (IOException e) {
	               e.printStackTrace();
	            }

	            ByteBuffer bb = ByteBuffer.wrap(bos.toByteArray());
	            bb.order(ByteOrder.LITTLE_ENDIAN);
	            ShortBuffer sb = bb.asShortBuffer();
	            noiseData = new short[sb.capacity()];

	            sb.get(noiseData);

	            System.out.println();
	         } catch (IOException e) {
	            e.printStackTrace();
	         }

	         // find the max:
	         float max = 0;

	         // 비율 구하기
	         String noiseFilePath = noisePath + noiseFileName;

	         AudioInputStream audioInputStream = AudioSystem.getAudioInputStream(new File(noiseFilePath));
	         AudioFormat format = audioInputStream.getFormat();
	         long frames = audioInputStream.getFrameLength();
	         double durationInSeconds = (frames + 0.0) / format.getFrameRate();
	         double f_noise_rate = f_noise_playtime / durationInSeconds; // percentage
	         double e_noise_rate = e_noise_playtime / durationInSeconds; // percentage

	         int f_noise_size = (int) (noiseData.length * f_noise_rate);
	         int e_noise_size = (int) (noiseData.length * e_noise_rate);
	         System.out.println(durationInSeconds);
	         System.out.print("noiseDataSize:");
	         System.out.println(noiseData.length);
	         System.out.print("f_noise_size:");
	         System.out.println(f_noise_size);
	         System.out.print("e_noise_size:");
	         System.out.println(e_noise_size);
	         System.out.print("oriDataSize:");
	         System.out.println(oriData.length);
	         System.out.print("sum:");
	         System.out.println(f_noise_size + oriData.length + e_noise_size);
	         int totalsize = f_noise_size + oriData.length + e_noise_size;
	         if (totalsize > noiseData.length)
	            e_noise_size = noiseData.length - f_noise_size - oriData.length;
	         System.out.print("bujung sum:");
	         System.out.println(f_noise_size + oriData.length + e_noise_size);
	         totalsize = f_noise_size + oriData.length + e_noise_size;

	         for (int i = 22; i < oriData.length; i++) {
	            if (Math.abs(oriData[i] + noiseData[i]) > max)
	               max = Math.abs(oriData[i] + noiseData[i]);
	         }

	         System.out.println("" + (Short.MAX_VALUE - max));
	         System.out.println(f_noise_size);
	         int c;

	         // now find the result, with scaling:
	         for (int i = 22; i < totalsize; i++) {
	            c = 0;
	            if (i < f_noise_size)
	               c = Math.round(Short.MAX_VALUE * (noiseData[i]) / max);
	            else if (i < oriData.length + f_noise_size - 3500)
	               c = Math.round(Short.MAX_VALUE * (oriData[i + 22 - f_noise_size] + noiseData[i]) / max);

	            else
	               c = Math.round(Short.MAX_VALUE * (noiseData[i]) / max);

	            if (c > Short.MAX_VALUE)
	               c = Short.MAX_VALUE;
	            if (c < Short.MIN_VALUE)
	               c = Short.MIN_VALUE;

	            noiseData[i] = (short) c;

	         }
	         //

	         // to turn shorts back to bytes.
	         /*
	          * byte[] end = new byte[noiseData.length * 2];
	          * ByteBuffer.wrap(end).order(ByteOrder.LITTLE_ENDIAN).asShortBuffer().put(
	          * noiseData);
	          */
	         byte[] ends = new byte[totalsize * 2];
	         ByteBuffer bbe = ByteBuffer.wrap(ends);
	         bbe.order(ByteOrder.LITTLE_ENDIAN);

	         ShortBuffer sbb = bbe.asShortBuffer();

	         for (int i = 0; i < totalsize; i++) {
	            sbb.put(noiseData[i]);
	         }

	         try {
	            OutputStream out = new FileOutputStream(savedFilePath);

	            for (int i = 0; i < totalsize * 2; i++) {
	               out.write(ends[i]);
	               out.flush();
	            }

	            out.close();

	         } catch (IOException e) {
	            // TODO Auto-generated catch block
	            e.printStackTrace();
	         }
	      }
	   }
`

We can check that We add First time and End Time to make sure when we want to put new music into.
Maybe people want to listen or make Mixed Music or they can practice with Mixed System.
Thank you !
```sh
$ beet -vv (... paste here ...)
```

Led to this problem:

```
(paste here)
```

Here's a link to the music files that trigger the bug (if relevant): 

### Setup

* OS: 
* Python version: 
* beets version: 
* Turning off plugins made problem go away (yes/no): 

My configuration (output of `beet config`) is:

```yaml
(paste here)
```

**Comment by sampsyo** [comment]
I don’t think mixing audio is in scope for a music library management tool like beets. Also, it is not possible to add Java code to beets.

**Comment by KwonWon** [comment]
@sampsyo Can I make Java ver. of beets?

**Comment by sampsyo** [comment]
You can certainly try, but beets is the result of many years’ work by many people. It does not seem like a good idea to start from scratch.

**Comment by arcresu** [comment]
I don't think there's anything beets can do here. If you have any specific ideas or changes related to beets itself then feel free to open a new issue. If you'd like to discuss writing separate software that's inspired by beets, somewhere like our Discourse forum might be more appropriate than the issue tracker.
