### ISSUE TITLE
MIN/MAX function for querys

### ISSUE THREAD

**Issue by jones1008** [beetbox/beets#2957]
### What I want to achieve:
getting the X best (or best known) songs of a specific albumartist, artist, album or genre with a query command.

### What could be a possible future implementation to achieve that:
adding a **MIN/MAX function** to beets querys.
The Syntax rules could be:
```
beet list -m MAX(<LimitOfResults>, <numericalTagToInspect>, <referenceTag>) <query>
```
- `-m` - initiates the MIN/MAX function
- `<LimitOfResults>` - the limit of results it should return
- `<numericalTagToInspect>` - a numerical tag it should get the min or max result to
- `<referenceTag>` - this only allows `albumartist`, `artist`, `album` or `genre` and refers to the group of tracks the MIN/MAX-Tracks searches
- `<query>` - the actual query itself

This would for example result in the following command (This would get the best 5 songs of each albumartist searched with the genre "rock"):
```
beet list -m MAX(5,popularity,albumartist) genre:rock
```
(I use the [beets-popularity plugin](https://github.com/abba23/beets-popularity) to get the popularity tag)

What do you think about that idea? Do you think this makes sense? Can you find other use cases than mine? Do you think it is implementable?

### OR

Is there already a way to achieve this with some other plugin?

**Comment by sampsyo** [comment]
Interesting! Except for the "reference tag" concept, it is possible to get a similar max/min effect using sorting. For example:

    beet list popularity- | head -n5

will give you the top 5 tracks by popularity in your library. I am, of course, relying on another shell command to limit the number of results to 5, but that could also be addressed as in #750.

I'm a little perplexed by how to conceive of the "reference tag" concept. It would be nice if this could somehow be seen as orthogonal to maximization and sorting, so the two ideas could be applied independently, but perhaps that's impossible.

**Comment by jones1008** [comment]
I had the intention to use the max-function within a query for creating a playlist with [the smart playlist plugin](http://beets.readthedocs.io/en/v1.4.7/plugins/smartplaylist.html).

The goal is to create a playlist of the best songs from artists with a specific genre (for example "rock") and configure that in the `smartplaylist:` part within the config.yaml.

To query that you would need a "reference tag" in the MAX-function, because I don't want the best songs from a specific genre, but the best songs of the albumartists with a specific genre.

The problem with using sorting is that this sorts the whole result but not the seperate results of the albumartists.
But maybe we could use the existing sorting mechanism within this MAX/MIN-function extension...

**Comment by sampsyo** [comment]
Yeah, that would be the ideal thing—some way to combine individual pieces of small functionality (sorting, limiting, and grouping) to get the desired effect. Maybe we can take inspiration from SQL queries? Is there an equivalent SQL query that would do what you want?

**Comment by jones1008** [comment]
I tried to fiddle around with a SQL query oneliner but this seems to be too complex with too many subselects... Instead I have the following two SQL querys but wasn't able to combine those two with a "for each albumartist"-logic:

- simple query to get the tracks from the genre
`SELECT * FROM tracks WHERE genre="rock";`

- query to get the best 5 songs of the albumartist "AC/DC":
`SELECT popularity FROM tracks WHERE albumartist="AC/DC" ORDER BY popularity DESC LIMIT 5;`


Taking an equivalent example in beets `beet list -m MAX(5,popularity,albumartist) genre:rock` this would lead to the following steps in python:

1. execute the query (`genre:rock`)
2. from this result, get all different values from the given reference tag (here: `albumartist`) into an array
3. loop over this albumartist-array and query the 5 (`<LimitOfResults>`) MAX/MIN tracks in relation to the popularity-tag (`<numericalTagToInspect>`) of each albumartist.

**Comment by sampsyo** [comment]
Got it; thanks for the thoughts. I'm still interested in any bright ideas about how to disentangle the three concepts (sorting, which we already have; limiting, as in #750; and grouping, as in `referenceTag` here) so they can be combined in unexpected ways.
