### ISSUE TITLE
Clarification on tags update options -w/-a

### ISSUE THREAD

**Issue by architek** [beetbox/beets#2970]
Hello,

I fail to precisely understand two options relating to tag/metadata update. 

```bash
  -w, --write           write new metadata to files' tags (default)
  -W, --nowrite         don't write metadata (opposite of -w)
  -a, --autotag         infer tags for imported files (default)
  -A, --noautotag       don't infer tags for imported files (opposite of -a)
```

- -a/-A

From the readthedocs documentation and the option name (autotag...), it's obvious that this will update the metadata in the files. The sentence "infer tags for imported files" could be clarified to "infer and **update tags** for imported files" so that we clearly see the action that will be taken. 

- -w/-W

This is not clear to me and how this relates to the previous one. The documentation at readthedocs doesn't help much. Will infered tags be written to db vs to files metadata? What will -wA do?

Did I miss some other documentation? Can you clarify? 

Thank you to all involved for providing us this gread software!

**Comment by architek** [comment]
Knew it, the -w documentation is more detailed in its stanza for config file : [Importer option](https://beets.readthedocs.io/en/v1.4.7/reference/config.html#importer-options)

_**Write**
Either yes or no, controlling whether metadata (e.g., ID3) tags are written to files when using beet import. Defaults to yes. The -w and -W command-line options override this setting._

It's still a bit unclear to me compared to -a.
Thanks

**Comment by sampsyo** [comment]
Hi! The -A flag doesn’t even try to find out what the tags should be on your files. If you keep autotagging enabled but don’t write the resulting metadata to tags (-W), updated metadata will still live in the beets library database.
