### ISSUE TITLE
How do I set the BEETSDIR variable?

### ISSUE THREAD

**Issue by CiniqueL** [beetbox/beets#2976]
### Problem

My problem is simple and explained the the title, but the documentation needs clarification.

How do I set the `BEETSDIR` Environment Variable in Windows?

I went into Windows environment variables, and I created a new variable called `BEETSDIR`.
but it had no effect.

I'm using relative paths in the config file; so, when I run "beet config -p" I see that beets thinks it should check from my main, C: Drive

`error: database file C:\artists\beets_artists.db could not be opened`

### Setup

* OS: Windows
* Python version: 2.7
* beets version:  1.4.7
* Turning off plugins made problem go away (yes/no): no

My configuration (output of `beet config`) is:

`directory: /artists`
`library: /artists/beets_artists.db`
`pluginpath: bin/plugins`

**Comment by sampsyo** [comment]
Hello, and welcome!

> How do I set the BEETSDIR Environment Variable in Windows?
> 
> I went into Windows environment variables, and I created a new variable called BEETSDIR.
> but it had no effect.

Hmm, that sounds right to me. But I myself don't know how to use Windows—maybe it would be best to ask on [SuperUser](https://superuser.com) or something about setting environment variables in general?

> I'm using relative paths in the config file; so, when I run "beet config -p" I see that beets thinks it should check from my main, C: Drive
> 
> error: database file C:\artists\beets_artists.db could not be opened

> My configuration (output of beet config) is:
> 
> directory: /artists
> library: /artists/beets_artists.db
> pluginpath: bin/plugins

Those are actually absolute paths, because they start with a `/`. You probably want to drop that leading `/`, or start with `./` instead.

**Comment by CiniqueL** [comment]
Thanks!

The `./` makes the config portable.

I have the same issue with the environment variables. It's not clear in the documentation if the `BEETSDIR` is supposed to be a _system variable_ or if it's something set in the config file or somewhere in the beets code.

I can set Windows environment paths as I described earlier: 
- for example: I could go into the Windows env variables, name `C:\Music = BEETSDIR` - then I can type can use `%BEETSDIR%` in any script, in the Windows explorer, etc and call that path...

but beets isn't seeing that. It still goes to the default directory.

If I ask at SuperUser they'll tell me what I already know. So, it's either something to do with Python or beets not using/seeing the variable.

**Comment by sampsyo** [comment]
It is indeed supposed to be an environment variable, which is something you set up external to beets. I’m unfortunately not sure what else to suggest! Maybe other Windows users can help out.

**Comment by CiniqueL** [comment]
Hmm, I discovered that...

I can use relative paths for `library`, `pluginpath`, and `log`...

But, I have to specify `directory`.

So, maybe `BEETSDIR` is working, but I have to specify the directory destination for the music?

Is that expected behavior - or am I not required to enter `directory` if `BEETSDIR` works?

**Comment by sampsyo** [comment]
Hmm, I’m not quite sure what you’re asking. BEETSDIR controls where beets looks for the configuration, and the configuration decides where the music directory is located (via `directory`). As the docs describe, the default for `directory` is *not* relative to the configuration file.

If you’re curious about which config file is being read, you can type `beet -v version` to get some verbose output.

**Comment by CiniqueL** [comment]
I think that answers my question.

The documentation isn't clear about what the `BEETSDIR` variable does and how to set it.

From reading the documentation I thought `BEETSDIR` was where everything would be stored. So, I could set `BEETSDIR` then it would be understood as the main directory for _everything_...
then I could put relative directories in the config.yaml and everything would stem from `BEETSDIR`.

but, if I'm understanding correctly, you're saying `BEETSDIR` only tells beets where to find the _config.yaml_ file - and the config file tells beets the path of everything else.

**Comment by sampsyo** [comment]
If you have an idea for how to improve the documentation, please consider helping out! Thoughtful docs pull requests are always welcome.
