### ISSUE TITLE
Subsonic library update plugin

### ISSUE THREAD

**Issue by maffo999** [beetbox/beets#3000]
Hello all,
as I use Subsonic to stream my music library (which Beets manages **awesomely**) I have always felt a bit let down by the fact that there is no plugin to automate the library update once new music is imported (such plugins are available for Plex, XMBC, and MPD for example).

I am definitely not a programmer, however as part of my Python learning path I though it would be fun to write such plugin and eventually submit it to you.

I have followed the indications on how to submit a new plugin: I have forked the repo and submitted the changes to my fork, I still have to update the documentation for the plugin.

The plugin file can now be found [here](https://github.com/beetbox/beets/pull/3001) in my forked repo, I would really appreciate if someone could take some time to help me with a couple of things:
1) review the code (missed best practices, etc.)
2) explain me how to run the tests with **tox** which I never used

Apologies if this is not the correct place for this kind of request, in which case I would appreciate if you could tell me where else I could bring this up.

**Comment by maffo999** [comment]
Thanks for the quick response!
I must have missed the wiki page about the testing, but it was very straightforward.
I fixed all the problems that caused the tests to fail.

**Comment by lbesnard** [comment]
will be amazing to have this one in the next release ! thanks

**Comment by Stele77** [comment]
Hi, any news on this? 
Thanks!

**Comment by jef** [comment]
This has been released in [v1.4.8](https://github.com/beetbox/beets/releases/tag/v1.4.8).
