### ISSUE TITLE
`beet ls` not outputting with more than one format value

### ISSUE THREAD

**Issue by MichelfrancisBustillos** [beetbox/beets#3014]
### Problem
`beet ls` and `beet ls -f '$/any one value/'` output as expected but adding a second format value (i.e. `bet ls -f '$artist $title'`) outputs nothing.

### Setup

* OS: Windows 10
* Python version: 3.7.0
* beets version: latest
* Turning off plugins made problem go away (yes/no): no plugins used

My configuration (output of `beet config`) is:

```yaml
directory: Z:\Music
library: Z:\Music\musiclibrary.db
```

**Comment by sampsyo** [comment]
Hi! Could this be a shell escaping issue? For example, you could try backslashes or double quotes. Or using bash instead of the Windows command prompt.

**Comment by MichelfrancisBustillos** [comment]
Wow! It was as simple as using double quotes instead of single. Thanks!!
