### ISSUE TITLE
Found a way to fix 'database is locked'

### ISSUE THREAD

**Issue by holocronweaver** [beetbox/beets#3016]
Want to report a solution I found for the 'database is locked' error.

My problem occurred after reinstalling my OS and attempting to access my good 'ol beet SQLite database stored on a network drive. The first time I started beet I got `database file /media/Air/audio/musiclibrary.db cannot not be opened: database is locked`.

Here is my fix:
1. Move the database from network / external storage to a local drive.
2. Change your config.yam `library` field to point to the local database.
3. Run `beet`. It should work without issue.
4. Move the database back to the network / external drive and update your config.yaml to point to there.
5. Run `beet` again. Lo and behold, it should work.

Is there a good place to document this trick?

**Comment by holocronweaver** [comment]
Hm...while this sort of worked, I still get occasional failures and have to reapply the trick. Am guessing this is due to a SQLite timeout issue.

**Comment by arcresu** [comment]
Thanks for your suggestion! It's probably better to focus on thinking about a fix for the underlying issue. Without being sure that it's related to network latency it's hard to say if it's good general advice to try moving the database around.
