### ISSUE TITLE
chroma: Bias toward looking up more relevant releases using date/country

### ISSUE THREAD

**Issue by Archer4499** [beetbox/beets#3017]
By default, the releases provided by the `chroma` plugin are effectively random, because it just presents the first five that are in the list supplied by Acoustid.

I would like to suggest a change that first sorts them according to the date of release and then their country depending on the `match` configuration options. The default config will still result in the same behaviour as before.

Archer4499@7a8f980

For example the following configuration:
```
match:
    preferred:
        countries: ['US', 'GB|UK']
        original_year: yes
```
will sort by date (oldest first) then by the preferred countries (US then GB/UK then others).

I find this useful because when I have just one or two songs from an artist I like tagging them with the original album that they were released in.

The main point of this being posted as an issue was to check if I should just make it sort by date by default (and still doing countries as an option), because I think it picking random releases isn't actually useful.
<br>
There is also possibly the separate issue of the [mb.py (Line 119)](https://github.com/beetbox/beets/blob/0c033bdaf10b78be04e6ebc8f998d9d3d5f70e3d/beets/autotag/mb.py#L119) file not using regex entries in the `countries` entry.

**Comment by sampsyo** [comment]
Hi! This sounds like an interesting proposal. I think I might be misunderstanding one thing, though: in the importer interface, we typically sort releases by their similarity (i.e., the most "likely" match goes first). In what context are you talking about sorting stuff?

**Comment by Archer4499** [comment]
The Acoustid lookup returns a list of recordings with sublists of releases which contain the MusicBrainz ID and a few other details including the date and country [Acoustid API](https://acoustid.org/webservice) (The request the plugin uses is recordings+releases).

The current behaviour (on line 190) uses the prefix function to just take the first five releases in the list from the Acoustid lookup then look them up in MusicBrainz and return those options, but since the order of the list seems to be semi random (possibly based on date submitted or something) it basically returns random albums that contain the song/s, which a lot of the time are best of or various artist albums.

This would sort the full list from Acoustid first (before the prefix and MusicBrainz lookups occur) to hopefully provide more useful options. And since the whole point of this plugin is to get the info from the fingerprint rather than the metadata in the file, I don't think there are many other ways of selecting relevant results. And beets still gives a few options based on any tags the file may have.

**Comment by sampsyo** [comment]
Got it; thanks! That helps a lot. So the goal is to make some guesses about which releases are likely to be the most "productive" ones to look up. That sounds great!

If we do implement this, it would be nice to have some side-by-side comparisons where matching failed (or went poorly) before the change but went well after the change.

**Comment by Archer4499** [comment]
Same settings used for all:
```
match:
  preferred:
    countries: ['GB|UK', 'AU', 'US']
    original_year: yes
```
I removed all the tags from the files to show that the results are just from the fingerprinting

#### Tom's Diner by Suzanne Vega:
Old:
```
    Finding tags for album " - ".
    Candidates:
    1. DNA feat. Suzanne Vega - Tom's Diner (23.8%) (album, artist, missing tracks, ...) (CD, 1990, GB, A&M Records, cd wrongly shows track 2 as "tired of sleeping")
    2. DNA feat. Suzanne Vega - Tom's Diner (23.8%) (album, artist, missing tracks, ...) (CD, 1990, GB, A&M Records, cd wrongly shows track 2 as "tired of sleeping (reprise)")
    3. Suzanne Vega - Retrospective: The Best of Suzanne Vega (8.4%) (missing tracks, album, artist, ...) (2xCD, 2003, GB, Universal Music TV)
    4. Various Artists - Munich City Nights, Volume 31 (6.9%) (missing tracks, album, tracks)
    5. Various Artists - BBC Radio Group 2 Acoustics Test CD (2.5%) (missing tracks, album, tracks)
```
New:
```
    Finding tags for album " - ".
    Candidates:
    1. Suzanne Vega - Solitude Standing (13.9%) (missing tracks, album, artist, ...) (CD, 1987, US, A&M Records)
    2. Suzanne Vega - Solitude Standing (13.9%) (missing tracks, album, artist, ...) (12" Vinyl, 1987, US, A&M Records)
    3. Suzanne Vega - Solitude Standing (13.9%) (missing tracks, album, artist, ...) (CD, 1987, US, A&M Records)
    4. Suzanne Vega - Solitude Standing (13.0%) (missing tracks, album, artist, ...) (CD, 1987, DE, A&M Records, Distribution code POL 900, GEMA on disc, MADE IN W. GERMANY BY PDO in matrix.)
    5. Suzanne Vega - Solitude Standing (13.0%) (missing tracks, album, artist, ...) (CD, 1987, CA, A&M Records, Inc.)
```

#### Mr Blue Sky by Electric Light Orchestra:
Old:
```
    Finding tags for album " - ".
    Candidates:
    1. Various Artists - The 70's Collection: 1978 - Back in the Groove (10.7%) (missing tracks, album, tracks) (2xCD, 1994, GB, Time-Life Music)
    2. Electric Light Orchestra - Out of the Blue (6.9%) (missing tracks, album, artist, ...) (CD, 2007, US, Epic)
    3. Electric Light Orchestra - The Best of Electric Light Orchestra (6.2%) (missing tracks, album, artist, ...)
    4. Various Artists - Back to the Seventies (5.8%) (missing tracks, album, tracks, ...) (2xCD, 1994, DE, Magnum)
    5. Electric Light Orchestra - Flashback (5.2%) (missing tracks, album, artist, ...) (3xCD, 2000, GB, Epic)
```
New:
```
    Finding tags for album " - ".
    Candidates:
    1. Electric Light Orchestra - Mr. Blue Sky / One Summer Dream (23.1%) (album, artist, missing tracks, ...) (7" Vinyl, 1977, NL, United Artists)
    2. Electric Light Orchestra - Out of the Blue (12.1%) (missing tracks, album, artist, ...) (2x12" Vinyl, 1977, GB, Jet Records)
    3. Electric Light Orchestra - Out of the Blue (12.1%) (missing tracks, album, artist, ...) (2x12" Vinyl, 1977, GB, Jet Records)
    4. Electric Light Orchestra - Out of the Blue (10.7%) (missing tracks, album, artist, ...) (2x12" Vinyl, 1977, US, Jet Records, Club Edition)
    5. Electric Light Orchestra - Out of the Blue (10.7%) (missing tracks, album, artist, ...) (2x12" Vinyl, 1977, US, Jet Records)
```

**Comment by sampsyo** [comment]
Cool! Would you mind opening a pull request with those changes so we can discuss them?
