### ISSUE TITLE
Split release and release-group disambiguation into separate fields

### ISSUE THREAD

**Issue by djl** [beetbox/beets#3024]
Back in #87, @sampsyo mentioned that the two disambiguation fields beets uses may need to be split into separate fields. Five and a half years later, I agree!

As it stands, some albums (like the Weezer albums mentioned in the pull request) have doubled disambiguation fields:

    $ beet ls -a -f '$albumatist - $album [$albumdisambig]' weezer ^albumdisambig::^$
    Weezer - Weezer [Green Album, Green Album]
    Weezer - Weezer [Red Album, Red Album]
    Weezer - Weezer [Blue Album, Blue Album, BMG club release]

This ugliness keeps me awake at night.

Opening this as a tracking issue until I (or someone else) can find time to fix this.

**Comment by sampsyo** [comment]
Argh; yeah, that result isn't very pretty at all. Splitting these two fields (and making `$albumdisambig` itself more sensible in the process) seems like the thing to do.

**Comment by djl** [comment]
Fixed in #3025.
