### ISSUE TITLE
chroma: Allow queries in `submit` command

### ISSUE THREAD

**Issue by ilianaw** [beetbox/beets#3026]
Similar to #1084 but a different request.

I have releases in my library that I am thoroughly uninterested in submitting AcoustID fingerprints for, often because I know that the files I have aren't exactly what match the release metadata. I'd like to be able to specify a query to limit what fingerprints are submitted.

**Comment by ilianaw** [comment]
Wait, this is already the case :sweat_smile: 

The subcommand `--help` doesn't make it terribly obvious that it supports a query...

**Comment by sampsyo** [comment]
Great! :smiley: Yeah, our infrastructure for subcommands makes it hard to provide detailed help for positional arguments to subcommands. Sorry about that!
