### ISSUE TITLE
Cleaning up left over files after event import with hooks

### ISSUE THREAD

**Issue by oakbrad** [beetbox/beets#3027]
### Problem
I'd like to delete the left over source files/directories after a successful import. It seems the hooks plugin, returning the "paths" list from the import event, is what I want.

I am not sure how to process the list. I have tried

`echo {paths} | xargs -0 rm -rf`

But this gives me

Running this command in verbose (`-vv`) mode:

```
Sending event: import
hook: running command "echo ['Blue Oyster Cult - Metal Battle/'] | xargs -0 rm -rf" for event import
['Blue Oyster Cult - Metal Battle/'] | xargs -0 rm -rf
Sending event: cli_exit
```

Similarly if I try to write the list to a file 

`echo {paths} >> /home/brad/imported_list.txt`

It does the same thing, just replaces {paths} but does not execute the actual command

Am I going about this wrong, or what would be the best way to approach this? A simple rm -rf would work on the individual albums, but the album.path on the album_imported event is the destination not the source.

### Setup

* OS: Debian Stretch
* Python version: 2.7.13
* beets version: 1.4.7

```
hook:
  hooks:
    - event: import
      command: echo {paths} | xargs -0 rm -rf

```

**Comment by sampsyo** [comment]
I have two answers:

1. It looks like you’re trying to use shell syntax, so you probably want to use `sh -c` to make that work.
2. Check out the `clutter` configuration option! (Along with using import.move instead of import.copy.) That’s specifically meant for helping beets prune leftover files after each album is imported.

**Comment by sampsyo** [comment]
Those clutter entries are glob patterns:
https://docs.python.org/3/library/glob.html

So you can certainly match everything if you want! It seems a little dangerous, though, so I’d try it on s backup if I were you.

**Comment by oakbrad** [comment]
Simply setting 

`clutter: '*'`

Seems to do what I am looking for. I will explore some safer options with the shell and hooks maybe. Thanks for the help

**Comment by xthursdayx** [comment]
oakbrad, if you find a safer way of doing this with the shell and hooks can you update this issue thread? I'm trying to figure out this same issue, but a bit nervous about using the clutter option. Thanks!
