### ISSUE TITLE
%title{ } Capitalize after apostrophe

### ISSUE THREAD

**Issue by 6GVp8WcnM9TPDBrw** [beetbox/beets#3033]
### Problem

When you add %title{} to something for example %title{$title}, the capitalization is also done after an apostrophe, leading to some weird capitalization like "Can'T" "Don'T" "I'M" ...

Example : 

"50 Cent - If I Can't" become "50 Cent - If I Can'T"

### Setup

* OS: Arch Linux
* Python version: Latest 
* beets version: Latest
* Turning off plugins made problem go away (yes/no): N/A

**Comment by jackwilsdon** [comment]
Looks like replacing it with `capwords` should do it: https://stackoverflow.com/a/8199981/2664985

**Comment by sampsyo** [comment]
Awesome; good find, @jackwilsdon. Do you know whether it works with Unicode punctuation like ‘’?

**Comment by jackwilsdon** [comment]
Looks like it works as expected :+1:

```
>>> import string
>>> string.capwords("Testing the q‘uote’s", " ")
'Testing The Q‘uote’s'
```
