### ISSUE TITLE
Path query failing for some items

### ISSUE THREAD

**Issue by Infinisil** [beetbox/beets#3035]
### Problem

I have a minimized database of 2 items, and I'm trying to query each of them using its `path` attribute. One of them succeeds but the other fails. The problem started happening some time ago while I was fixing up some item paths manually in the database (it has about 2000 items in it). I thought I just messed something simple up, but I couldn't find the problem and I'm still wondering today where I went wrong. I have a feeling it's got something to do with encoding.

Running this command:

```sh
beet ls -f '$id - $path'

beet ls path:"/home/infinisil/music/data/Non-Album/Savant/Slasher.mp3"
beet ls path:"/home/infinisil/music/data/Non-Album/Wolfgang Amadeus Mozart/Koncert A dur pro klarinet a orchestr K 622.opus"
```

Led to this problem:

```
1763 - /home/infinisil/music/data/Non-Album/Savant/Slasher.mp3
2666 - /home/infinisil/music/data/Non-Album/Wolfgang Amadeus Mozart/Koncert A dur pro klarinet a orchestr K 622.opus

Wolfgang Amadeus Mozart -  - Koncert A dur pro klarinet a orchestr K 622
```

Note that the first path query failed, while the second succeeded.

Here's a repository for reproducibility: https://github.com/infinisil/beets-path-query

Direct database (36KB) download: https://github.com/Infinisil/beets-path-query/blob/master/beets.db?raw=true

This doesn't depend on anything else, only the database itself seems to enable me to reproduce the problem. I'm really just trying to find where I went wrong, there must be some way to fix up the database to have these commands work again.

### Setup

* OS: NixOS
* Python version: 3.6.6
* beets version: master (e993e252f652e1bf460d4435630e8e47aa8998c3)
* Turning off plugins made problem go away (yes/no): no

No beets config is necessary to reproduce this, it works with an empty one.

**Comment by Infinisil** [comment]
This seems related: Doing such path queries directly in sqlite3, it's exactly the opposite, the first one succeeds, but the second one fails:

```
$ sqlite3 beets.db                                                                                                                        master
-- Loading resources from /home/infinisil/.sqliterc
SQLite version 3.24.0 2018-06-04 19:24:41
Enter ".help" for usage hints.
> .width 150
> select path from items;
path
--------------------------------------------------------------------------------------------------------------------
/home/infinisil/music/data/Non-Album/Savant/Slasher.mp3
/home/infinisil/music/data/Non-Album/Wolfgang Amadeus Mozart/Koncert A dur pro klarinet a orchestr K 622.opus
> select path from items where path = '/home/infinisil/music/data/Non-Album/Savant/Slasher.mp3';
path
--------------------------------------------------------------------------------------------------------------------
/home/infinisil/music/data/Non-Album/Savant/Slasher.mp3
> select path from items where path = '/home/infinisil/music/data/Non-Album/Wolfgang Amadeus Mozart/Koncert A dur pro klarinet a orchestr K 622.opus';
>
```

**Comment by sampsyo** [comment]
Hi! Wow, this is a super weird situation!

Looking at your database (thanks for providing it!), here's the root cause of the inconsistency:

```
sqlite> select typeof(path) from items;
text
blob
```

For some reason, one of your items got its path stored as a proper SQLite string. Beets is *supposed* to store all paths as SQLite binary blobs, which lets it store the exact filenames from the filesystem losslessly. It also queries paths using blobs, of course, which is why its path queries are failing to match the string-typed path.

The mystery is how this happened. I don't know how beets could have let a proper string slip into the database. Do you remember doing anything funky to your database directly?

**Comment by Infinisil** [comment]
@sampsyo Ah, nice!

Well I mentioned it in the issue:

> The problem started happening some time ago while I was fixing up some item paths manually in the database [...]. I thought I just messed something simple up, ...

I guess I should've explained this a bit better. Not beets fault, I was messing with the database myself :)

Do you know how I could fix this though?

**Comment by Infinisil** [comment]
Asking on #sqlite on Freenode, user LACampbell informed me that sqlite pretty much doesn't do any checks on whether the inserted values are of the type of the column by default, see https://www.sqlite.org/datatype3.html.

Considering that path queries stop working if a `path` really is of type `text` but should be `blob`, I think it would be nice to add a type constraint to the path column. In sqlite this can be done with a `CHECK(typeof(path) = 'blob')` constraint on the `items` table.

**Comment by sampsyo** [comment]
Great! That seems like the right solution. :+1:

And a type constraint on that column could be a good idea, even if this is sort of an edge case. Please feel free to open a PR if you’re interested!
