### ISSUE TITLE
Does beets support multiple songs in one file?

### ISSUE THREAD

**Issue by coseltech** [beetbox/beets#3036]
I have multiple "mixtapes" ripped from youtube, i.e. one file containing multiple songs. Can beets deal with this and identify the songs comprising the mixtape?

**Comment by sampsyo** [comment]
Hi! Have you read the "Getting Started" guide? It's really, really helpful in getting oriented to what beets can do. You probably want the "singleton" importer mode.

**Comment by coseltech** [comment]
The manual says

> The importer typically works in a whole-album-at-a-time mode. If you instead want to import individual, non-album tracks, use the singleton mode by supplying the -s option.

This does not seem to relate to files per se. Beets seems to assume that one file contains one song at all times.

**Comment by sampsyo** [comment]
Aha! In one *file*! Sorry I read that too quickly. Please see https://github.com/beetbox/beets/issues/1640 and https://github.com/beetbox/beets/issues/136.
