### ISSUE TITLE
BPD, a query matching the current song played

### ISSUE THREAD

**Issue by coseltech** [beetbox/beets#3037]
I would like to manipulate a song as it is being played (e.g. add a user tag). It this presently possible?

**Comment by sampsyo** [comment]
Hmm, I'm not sure what you mean—does the MPD protocol allow tag changes?

**Comment by coseltech** [comment]
No, the MPD protocol does not relate to my question.

There are many queryies described in [the manual](https://beets.readthedocs.io/en/v1.3.17/reference/query.html) but that doesn't help me if I want to operate on the song currently playing in BPD.

It's just an easier workflow, to add user tags to currently playing songs as they come to mind.

**Comment by sampsyo** [comment]
Aha! No, we don't have a query that gets the currently-playing song from an MPD server (BPD or otherwise). Sounds cool, though, if you want to write a plugin to do that!
