### ISSUE TITLE
extraction failed: local variable 'archive' referenced before assignment

### ISSUE THREAD

**Issue by rain0r** [beetbox/beets#3041]
### Problem

When trying to import a mp3-file as a singleton, I get the following error:
`extraction failed: local variable 'archive' referenced before assignment`

The file is is a mp3-version of [this song](https://www.youtube.com/watch?v=JibljZBesgM) (`youtube-dl -x ...`).

After digging in the code, I found this line: [importer.py](https://github.com/beetbox/beets/blob/master/beets/importer.py#L1064)
```
ipdb> handler_class(util.py3_path(self.toppath), mode='r')
*** OSError: [Errno 22] Invalid argument
```
If `handler_class()` throws an error, `archive.close()` is not assigned when called in the `finally` block.

By the way, why does beets try to extract a mp3-file?

Here's a link to the music files that trigger the bug (if relevant): 

https://www.youtube.com/watch?v=JibljZBesgM

### Setup

* OS: Gentoo Linux
* beets version 1.4.7
* Python version 3.6.6
* plugins: chroma, embedart, fetchart, info, lastgenre, mpdstats, play, replaygain

**Comment by sampsyo** [comment]
Thanks!! I've fixed the immediate problem. Can you please give that a try?

As for why beets is trying to extract an ordinary MP3, I don't have an answer for you… maybe that deserves closer investigation?

**Comment by sampsyo** [comment]
Actually, now that I think of it:

```py
for path_test, handler_class in self.handlers():
    if path_test(util.py3_path(self.toppath)):
        break
```

This stanza doesn't seem to bail out if there are no matching handlers. It seems to just continue on with the last handler, even if it didn't claim to be able to extract the file. I think we need to add:

```py
else:
    return
```

to abort when there is no match. Would that make sense?

**Comment by rain0r** [comment]
Getting this result now:

```
$ beet -vv import -s Ill_Breed_-_Act_Up-JibljZBesgM.mp3 
user configuration: /home/rain0r/.config/beets/config.yaml
data directory: /home/rain0r/.config/beets
plugin paths: 
Sending event: pluginload
artresizer: method is (2, (7, 0, 8))
library database: /home/rain0r/.local/share/beets/musiclibrary.blb
library directory: /mnt/archivefs/music
Sending event: library_opened
Sending event: import_begin
state file could not be read: 'ascii' codec can't decode byte 0xcc in position 75: ordinal not in range(128)
Extracting archive: /home/rain0r/to-tag/hiphop/Ill_Breed_-_Act_Up-JibljZBesgM.mp3
extraction failed: [Errno 22] Invalid argument
No files imported from /home/rain0r/to-tag/hiphop/Ill_Breed_-_Act_Up-JibljZBesgM.mp3
Sending event: import
Sending event: cli_exit
```

**Comment by sampsyo** [comment]
Weird! For what it's wort, I'm able to reproduce this if I use the `--audio-format mp3` flag to youtube-dl to create the MP3 file. In this case, Python's built-in [zipfile](https://docs.python.org/3.7/library/zipfile.html) module returns true for `is_zipfile()` on that file. The `file` command on my system, however, disagrees:

```
$ file Ill\ Breed\ -\ Act\ Up-JibljZBesgM.mp3
Ill Breed - Act Up-JibljZBesgM.mp3: Audio file with ID3 version 2.4.0, contains:MPEG ADTS, layer III, v1,  64 kbps, 48 kHz, Stereo
```

I'm not exactly sure what to suggest. We could whitelist filename extensions, for example, or fall back to an ordinary import procedure if extraction fails?
