### ISSUE TITLE
Bucket plugin doesn't work for artist with 4 digits in their names

### ISSUE THREAD

**Issue by elnull** [beetbox/beets#3045]
Bucket plugin doesn't work for artist with 4 digits in their names.
With setup like this:

bucket:
    bucket_alpha: ['0']
    bucket_alpha_regex:
        '0': ^[0-9]

paths:
    default: %bucket{$albumartist}/${albumartist}/%if{$year,$year-}$album/$disc-$track--$title

artists 047 and 417.3 are placed in directories 0/047 and 0/417.3, but artists 1099 and 1900 are placed in directories 1099/1099 and 1900/1900.

**Comment by sampsyo** [comment]
Hi! Does this persist even if you use `beet modify` to manually add a digit to one of those three-digit names, or remove a digit from one of the four-digit names?

**Comment by elnull** [comment]
Please note, I changed resulting directories names in bug report.

I've tried:
beet modify 047 artist="2047" 
beet modify 1900 artist="19001"

Tag artist was changed but directory structure remains the same.

**Comment by sampsyo** [comment]
Hmm, but your configuration uses albumartist, not artist. Does that have an effect?

**Comment by elnull** [comment]
I think the trouble is in function:
    def _tmpl_bucket(self, text, field=None):
        if not field and len(text) == 4 and text.isdigit():
            field = 'year'
        if field == 'year':
            func = self.find_bucket_year
        else:
            func = self.find_bucket_alpha

It seems it moves all 4 digits text in year bucket.

**Comment by sampsyo** [comment]
Got it! So it’s just assuming any 4-digit number is a year, not text. Is there a way to approach this in a backwards compatible manner?

**Comment by elnull** [comment]
I think, field argument should be defined when function is calling but I don't know how to do it.

**Comment by sampsyo** [comment]
Interesting... is there a way to describe abstractly what change you think would be warranted? I might be able to help pinpoint what actual lines of code need to change if you have specific suggestions about how the behavior needs to be modified.

**Comment by sampsyo** [comment]
Got it. Have you tried just using `%bucket{$albumartist,text}` or something? This will invoke the `_tmpl_bucket` function with `"text"` as the value for the second parameter.

**Comment by elnull** [comment]
After changing to `%bucket{$albumartist,text}` I have right directory structure (0/1900, 0/1099). Thank you.

**Comment by sampsyo** [comment]
Great! Maybe we should mention this in the documentation? Any chance you'd be willing to make a quick pull request with a sentence about that?

**Comment by elnull** [comment]
Sorry, I don't want to do pull request, because of my bad english. I'd describe this situation like this:

If template function `%bucket` is called with single argument those value contains 4 digits only then rules for year ranges are applied to it. To use alpha ranges for such values you should call `%bucket` with two arguments and value of the second must not equal `year`, for example, `%bucket{$artist,artist}`.
