### ISSUE TITLE
Fetch album art for singletons

### ISSUE THREAD

**Issue by rain0r** [beetbox/beets#3047]
This is a suggestion. I got over 1,000 singletons which are missing an album art and I think that's a pitty. Since 1,000 is way too much to search and download the album art, it would be nice if beet could support me with that. For this, I suggesst the following:

Case 1: The singleton has the id3 tag `album` set (for whatever reason): fetch the cover and save it as id3 tag.
Case 2: The singleton has no album set: consult Musicbrainz for possible albums that may contain this track, use the first one or prompt the user for a selection.

Thoughts on this?

**Comment by sampsyo** [comment]
Great idea! 😄 Please see #132.
