### ISSUE TITLE
invalid regex in zsh completion

### ISSUE THREAD

**Issue by mrossinek** [beetbox/beets#3050]
### Problem

When trying to use the auto completion function in zsh, I get the error:

```
_beet:zregexparse:4: invalid regex : )
```
Obviously, since I am trying to complete the command and am not actually running it, I cannot help with any error messages from beets.

However, the `_complete_debug` zsh function returns this before the error is thrown:
```
       +(eval):1> _beet                                                                                                  
        +_beet:1> local _ra_p1 _ra_p2 _ra_left _ra_right _ra_com expl tmp nm=0                                           
        +_beet:2> local _ra_actions _ra_line=$'beet\C-@'                                                                 
        +_beet:3> _ra_actions=( )                                                                                        
       +_beet:4> zregexparse -c _ra_p1 _ra_p2 $'beet\C-@' $'/[^\C-@]##\C-@/' '(' '(' $'/-c\C-@/' $'/[^\C-@]##\C-@/' ':_ra_comp $'\''file:file:_files'\' '|' $'/-v\C-@/' '|' $'/-l\C-@/' $'/[^\C-@]##\C-@/' ':_ra_comp $'\''file:file:_files'\' '|' $'/-h\C-@/' '|' $'/-d\C-@/' $'/[^\C-@]##\C-@/' ':_ra_comp $'\''dir:directory:_dirs'\' '|' '/[]/' ':_ra_comp $'\''options:global options:(( -c\\:path\\ to\\ configuration\\ file -v\\:print\\ debugging\\ information -l\\:library\\ database\\ file\\ to\\ use -h\\:show\\ this\\ help\\ message\\ and\\ exit -d\\:destination\\ music\\ directory ))'\' ')' '#' ')' ')'
 _beet:zregexparse:4: invalid regex : )                                                                                  
        +_beet:5> case 3 (0 | 2)                                                                                         
         +_beet:5> case 3 (1)                                                                                             
         +_beet:5> case 3 (3)                                                                                             
         +_beet:17> _message 'invalid regex'                                                                              
```

As a further note:
Replacing the current `_beet` file in `/usr/share/zsh/site-functions/` with its version from before the commit https://github.com/beetbox/beets/commit/7e0fbef solves the issue.

### Setup

* OS: Arch Linux 4.18.12
* Python version: 3.7.0
* beets version: 1.4.7
* Turning off plugins made problem go away (yes/no): no

My configuration (output of `beet config`) is: irrelevant for this type of issue

**Comment by sampsyo** [comment]
@vapniks, can you please take a look?

**Comment by vapniks** [comment]
@mrossinek did you check that the values of BEETS_LIBRARY and BEETS_CONFIG are set correctly in _beet ?

**Comment by mrossinek** [comment]
@vapniks Yes I did check that.

At first I realized that my library.db is not in the default path so I tried a few things: symlinking it, editing _beet to the correct path and even exchanging ~ for /home/... but none of the modifications changed the result.

**Comment by stefanor** [comment]
There's a similar report in https://bugs.debian.org/914569 of an issue with `beet import ../<TAB>`.

**Comment by mrossinek** [comment]
I am not sure what has changed, but this issue no longer occurs for me. Closing this as outdated.
