### ISSUE TITLE
Get genres from MusicBrainz

### ISSUE THREAD

**Issue by Freso** [beetbox/beets#3053]
### Problem

Next release of MusicBrainz will have genre support. An example can be seen at https://beta.musicbrainz.org/release-group/3bd76d40-7f0e-36b7-9348-91a33afee20e (JSON web service output: https://beta.musicbrainz.org/ws/2/release-group/3bd76d40-7f0e-36b7-9348-91a33afee20e?fmt=json&inc=genres )

beets should fetch these and allow MusicBrainz to be used as "genre authority".

**Comment by sampsyo** [comment]
Whoa! That's so cool! Somehow I had missed the buzz about this update. We should certainly support it!!

**Comment by jackwilsdon** [comment]
Looks like a PR will be needed on [musicbrianzngs](https://github.com/alastair/python-musicbrainzngs), as it currently doesn't support `genre` as a field (it's not in the whitelist), and it doesn't try to do any parsing either.

It should be relatively simple to add as genres are laid out just like tags, so it's a pretty simple case of adding it to the right dicitonaries and using `parse_tags`.

**Comment by Moonbase59** [comment]
I’ve been using [fdemmer’s last.fm.ng](https://github.com/fdemmer/Picard-Last.fm.ng-Plugin) plugin with MusicBrainz Picard for ever and a while. I wonder if something like this could be implemented instead?

MusicBrainz genres will surely take a while to gain momentum, since almost nobody currently tags genres in MusicBrainz.

**Comment by trolley** [comment]
I'd love to see this feature, implemented similar to how Picard does it. With Picard it will only use the genres I've tagged with, and will fall back to the album artist's genre if I didn't tag a release or release group with one.

It looks like there's a partially completed PR for musicbrainzngs that adds the support: https://github.com/alastair/python-musicbrainzngs/pull/243.

**Comment by jef** [comment]
Looks like a stale PR https://github.com/alastair/python-musicbrainzngs/pull/243

@trolley messaged a couple days ago.
