### ISSUE TITLE
Import produces duplicate albums

### ISSUE THREAD

**Issue by fortysixandtwoahead** [beetbox/beets#3057]
### Problem

Running this command
```sh
$ beet import /my/directory
```

led to this problem:

I'm letting beets move files during import, which so far worked fine. However, I have two cases where importing the files did not produce the result I expected. Instead of having x files in one single directory, I now have x directories, each containing one file.

Here's an example, this is what the directory looks like:
```
total 0
drwxrwxrwx+ 1 xxx users 1070 Oct 19 14:49 .
drwxrwxrwx+ 1 xxx users 6998 Oct 19 10:17 ..
drwxrwxrwx+ 1 xxx users   34 Oct 19 10:08 Космодром [672]
drwxrwxrwx+ 1 xxx users   36 Oct 19 10:08 Космодром [673]
drwxrwxrwx+ 1 xxx users   44 Oct 19 10:08 Космодром [674]
drwxrwxrwx+ 1 xxx users   34 Oct 19 10:08 Космодром [675]
drwxrwxrwx+ 1 xxx users   46 Oct 19 10:08 Космодром [676]
drwxrwxrwx+ 1 xxx users   30 Oct 19 10:08 Космодром [677]
drwxrwxrwx+ 1 xxx users   32 Oct 19 10:08 Космодром [678]
drwxrwxrwx+ 1 xxx users   30 Oct 19 10:08 Космодром [679]
drwxrwxrwx+ 1 xxx users   46 Oct 19 10:08 Космодром [680]
drwxrwxrwx+ 1 xxx users   30 Oct 19 10:08 Космодром [681]
drwxrwxrwx+ 1 xxx users   48 Oct 19 10:08 Космодром [682]
drwxrwxrwx+ 1 xxx users   50 Oct 19 10:08 Космодром [683]
drwxrwxrwx+ 1 xxx users   36 Oct 19 10:08 Космодром [684]
drwxrwxrwx+ 1 xxx users   34 Oct 19 10:08 Космодром [685]
drwxrwxrwx+ 1 xxx users   28 Oct 19 10:08 Космодром [686]
drwxrwxrwx+ 1 xxx users   30 Oct 19 10:08 Космодром [687]
drwxrwxrwx+ 1 xxx users   42 Oct 19 10:08 Космодром [688]
drwxrwxrwx+ 1 xxx users   38 Oct 19 10:08 Космодром [689]
drwxrwxrwx+ 1 xxx users   50 Oct 19 10:08 Космодром [690]

Each directory contains one file:

Космодром [672]:
total 9420
drwxrwxrwx+ 1 xxx users      34 Oct 19 10:08 .
drwxrwxrwx+ 1 xxx users    1084 Oct 19 14:49 ..
-rwxrwxrwx+ 1 xxx users 9645330 Oct 19 10:08 1-01 Energiya.mp3

Космодром [673]:
total 8868
drwxrwxrwx+ 1 xxx users      36 Oct 19 10:08 .
drwxrwxrwx+ 1 xxx users    1084 Oct 19 14:49 ..
-rwxrwxrwx+ 1 xxx users 9080014 Oct 19 10:08 1-02 Telemetry.mp3
```
I guess this has to do with the non-ascii characters in the album name. As you can see, the album has a name written in cyrillic letters. The directory is named fine with those letters, but it seems that beets assumes that there need to be new directories when importing.

Here's a link to both albums, which cause this behaviour. Please note that both are albums with 2 CDs. The second album does not have non-ascii characters in its album name, the the artist's name starts with a colon.
https://musicbrainz.org/release/e2602ea1-83d1-4926-8494-bf7fb6eba13f
https://musicbrainz.org/release/68181ffa-720e-3a4d-bd8b-d1e15f337fbb

### Setup
* OS: Synology DSM 6
* Python version: 3.5.1
* beets version: 1.47
* Turning off plugins made problem go away (yes/no): not tried

**Comment by sampsyo** [comment]
We will need more detail: what did the original files look like that you imported? Also, please follow the issue template and include verbose output from the command.

**Comment by fortysixandtwoahead** [comment]
The original files reside in a single directory following this scheme: <root>/artist/album/*.mp3
The files were tagged with Picard before importing.

I attached my config and the log generated during an import (I re-did the import with an empty beets db and the files in question only).

[config.yaml.txt](https://github.com/beetbox/beets/files/2501336/config.yaml.txt)
[import.log.txt](https://github.com/beetbox/beets/files/2501337/import.log.txt)

**Comment by sampsyo** [comment]
The configuration link is 404ing. Can you please try again?

**Comment by fortysixandtwoahead** [comment]
Done.

I checked on a SuSE linux and the import works as expected. I'll try to reproduce this on my Synology.

**Comment by sampsyo** [comment]
Hmm; that's weird! The import log does show beets creating only a single album.

What's the output of `beet ls -a` and `beet ls -ap` after one of these imports goes wrong?

**Comment by fortysixandtwoahead** [comment]
Tried to reproduce the behaviour on my Synology NAS and again the import worked fine. Seems I'm chasing a ghost here ...
The only thing I can think of is that the files did not reside in a single directory. That's what I really cannot confirm. I'm pretty sure they were, but I cannot confirm. I'm currently migrating from iTunes and maybe iTunes put those files into separate directories because of their tags and the derived file names. That would explain the behaviour I have seen. I'll check my backups later this evening, maybe I'll be able to answer that question.

**Comment by fortysixandtwoahead** [comment]
I checked, and the files resided in one directory. However, I can‘t reproduce the issue, so I‘m closing this.

**Comment by sampsyo** [comment]
OK, thanks! It remains a mystery for now. Please feel free to reopen this if it resurfaces.
