### ISSUE TITLE
beets doesn't import from directory which name ends in ~

### ISSUE THREAD

**Issue by elnull** [beetbox/beets#3066]
beets doesn't import from directory which name ends in ~
For example, I had directory Iamthemoring/2012-~ and import operation skipped it. After renaming 2012-~ to anything that doesn't have ~ at the end import worked fine.

**Comment by sampsyo** [comment]
Hi! This is really not enough detail for anyone to understand your issue. Please follow the issue template (that's why it's there).

**Comment by sampsyo** [comment]
See also the default ignore configuration:
http://docs.beets.io/en/v1.4.7/reference/config.html#ignore
