### ISSUE TITLE
inconsistency with $format wildcard and some ideas

### ISSUE THREAD

**Issue by hitsfromdabong** [beetbox/beets#3076]
### Problem

In practical terms the problem is:

The beets duplicates plugin does not know the key $format, while beets itself does.

This in particular messy, as there could be two identical albums, say one in crappy mp3 quality and one in superb FLAC. As the duplicates plugin does not know the key $format, it treats both as equal. This is no desirable behaviour, is it?

Also the concept of the album folder as the most complex information structure that beets handles can be expanded, and especially modularised! (i.e. keep a .beets file in every directory which includes info about deeper directories)

What I detest about beets:
* It copies every imported file. (Try importing ~500GB of music.)
* Once a folder has been added to beets and you add some albums to the folder, import again, each previously imported album will have a duplicate entry. There is an option to prevent this, but why not make it the default behaviour?
* Why is all the database info saved in one database file? Why not choose an approach like git? In every directory that has been identified as an album, place a ".beets" file there, which contains all the info beets needs. Nice to have would be an option to declare an album, or tracks on it, as "broken". This would be very handy, as you could simply edit the file, as you stumble across a broken file. So there is no need to remove the file from the folder, but beets handles broken files transparently.
* Why does the beets metadata structure not have an entry for quality? This could be a simple score dependent on format and bitrate. So when beets duplicates merges albums, it will automatically pick the one with best quality.
* Anything that is not ascii, will fuck up (as it almost always does). Sure, you can specify that the imported beets folder structure will contain only ascii characters, but when using the -l flag in the duplicates plugin, and therein are non ascii characters, good luck writing a little script that just move every not imported under one "roof" (= folder). Yeah, once you're at this point, and realise this, first you now need to write a script that removes all non-ascii characters from the folder structure, then from the list of non imported folders, and then you're good to go.
Why not have a little remainder: "Hey, it is advised, if you have a lot of music, to first ensure that there are only ascii characters in dir and file names! Look, there is even a command which does this automatically for you. Just run: 'find dir -depth -exec rename -n 's/[^[:ascii:]]/_/g' {} \; | cat -v' ".

That's about it for the ideas! (Which I came up when importing about 700GB of music. Still not completely sorted... :/)

PS: You're encouraged to bash at me for how 'messy' this bug report is ;)

**Comment by sampsyo** [comment]
Hi!

> The beets duplicates plugin does not know the key $format, while beets itself does.

Just taking a wild guess here, but I'd bet you're using the duplicates plugin to detect duplicate *albums*? The `format` field is item-level.

For your other questions, can I perhaps ask you the favor of engaging in a fun exercise? Try imagining answers to your own questions. I would bet you can get most of them—for example, in response to:

> Why is all the database info saved in one database file?

Try thinking of a few reasons why this might be the case. Doing this for several questions might be a useful exercise. The overall lesson is that there are complex trade-offs here—and everything does indeed happen for a reason.

> Anything that is not ascii, will fuck up (as it almost always does).

I actually don't agree with this one—I use Unicode in all my metadata (and filenames) everywhere (and I like it!).
