### ISSUE TITLE
Comma breaks path formatting

### ISSUE THREAD

**Issue by rendeko** [beetbox/beets#3078]
### Problem

Placing a comma in the path formatting will cause the rest of the path to print as cleartext. 

```
default: $albumartist - $album ($year) [$albumtype $media %if{$catalognum,$catalognum}] [$format]/$disc.$track - $title
results in:
Beyonc - B'Day (2007) [album CD 88697 11111 2] [FLAC]
```

```
default: $albumartist - $album ($year) [$albumtype, $media %if{$catalognum,$catalognum}] [$format]/$disc.$track - $title
results in:
Beyonc - B'Day (2007) [album, $media %if{$catalognum,$catalognum}] [$format]
```
notice the comma after $albumtype

### Setup

* OS: Debian 9 running in a Proxmox container
* Python version: 2.7.13
* beets version: 1.3.18
* Turning off plugins made problem go away (yes/no): no

**Comment by sampsyo** [comment]
Hi! Can you please try putting quotes around the template in your config to force the YAML parser to see it as a single, literal string?

**Comment by sampsyo** [comment]
Just to be clear: I couldn't reproduce this by typing:

```
$ beet ls -f '$artist, $artist'
```

Which works fine.

**Comment by rendeko** [comment]
The following still produces the plaintext output.
```
default: '$albumartist - $album ($year) [$albumtype, $media %if{$catalognum,$catalognum}] [$format]/$disc.$track - $title'

Beyonc - B'Day (2007) [album, $media %if{$catalognum,$catalognum}] [$format]
```

Additionally, beet ls produces the same error.
```
$ beet ls -f '$artist, $artist'
Beyonc?, $artist
Beyonc?, $artist
Beyonc?, $artist
Beyonc?, $artist
Beyonc?, $artist
```

**Comment by sampsyo** [comment]
I notice you're on an old version of beets (1.3.18). Can you try the latest?

**Comment by rendeko** [comment]
That seemed to be the problem, I didn't notice how far the Jessie repo was behind with beets. An uninstall from the package manager and installing through pip seems to have fixed it.
