### ISSUE TITLE
Delete option

### ISSUE THREAD

**Issue by trippinshrumes** [beetbox/beets#3096]
When moving to a fuse file system, it see's a mutagen error, I believe this is caused due to the fact that you cannot move to a fuse file system and you can only copy. 

nevertheless, I need a delete after copy option. I know the delete syntax isn't supposed to be used anymore as you've replaced it with move, although the move functionality is useless when used with fuse. 

Any ideas?

**Comment by sampsyo** [comment]
Interesting! Have you tried using the deprecated `delete` option? It's obviously not often used, but it might still work.

**Comment by trippinshrumes** [comment]
I have not yet, I wanted to get the thoughts of any developers to see if they have ever worked with fuse systems and if there were any recommendations. 

I was able to find some documentation on the delete option and that it was not recommended.
