### ISSUE TITLE
Add "details" choice when the autotagger asks the user during import

### ISSUE THREAD

**Issue by Holzhaus** [beetbox/beets#3102]
Sometimes it's hard to decide if the release candidate presented by the Autotagger is the correct one, because important information is not shown to the user, e.g. the Barcode/UPC.

What I usually do to decide if the release is correct:
1. Open the musicbrainz URL in a browser
2. Open a second terminal and call `mutagen-inspect /path/to/my/file.flac`

In my opinion, there should be a "Show details" choice where the user can see all information from MusicBrainz and also tags from local files (e.g. the "comment" tag) to be able to make better decisions without opening a browser.

**Comment by sampsyo** [comment]
Interesting idea! Sounds like it could be worth exploring.

I'd be interested to hear more details about how you'd like this to work. Would the output look like what the `info` plugin produces, which can be quite long?

**Comment by Holzhaus** [comment]
Yes, detailed information is always nice. However, for some usecases a tracklist + some per-album metadata (if available) like year, UPC, catalog number or label would also suffice.
