### ISSUE TITLE
Beets 1.4.7.0.1 QNAP NAS .qpkg config.yaml Plugins

### ISSUE THREAD

**Issue by mrtargaryen** [beetbox/beets#3103]
### Problem

Beets is the thing I have desperately needed for a long time, I'm so glad I came across it.

I am relatively new to Command Line & YAML, still learning. I am seeking some help for installing my first Plugin, Discogs (I have a new account with Discogs). 

I have figured out how to add the tracks to my Library & add tags to my Library of 21,000(ish) songs. However, as I take a break from doing that I would like to figure out how to install the plugin.

I have read this  [Beets Configuration](https://beets.readthedocs.io/en/v1.4.7/reference/config.html#plugins)
)

I've created the config.yaml 

share/CE_CACHEDEV1_DATA/.qpkg/Beets/.config/beets/config.yaml

However, I'm still a bit unsure about what to do.

Any help with this is appreciated. 

### Setup

* OS: QNAP QTS 
* Python version: 
* beets version: 1.4.7.0.1

**Comment by sampsyo** [comment]
Hi! Put this in that file:

```yaml
plugins: discogs
```

Good luck!
