### ISSUE TITLE
convert: Add id3v23 option

### ISSUE THREAD

**Issue by Holzhaus** [beetbox/beets#3104]
The `convert` plugin can be used to convert files, so that they can be copied to a media player or devices that does not have support for all file formats in the music library, e.g. if parts of my library are FLAC but my media player only supports MP3.

Similarily,  only reason to use ID3v2.3 is that certain mediaplayers and devices don't support ID3v2.4 tags. Thus, I'd be nice to use id3v24 for you local library but use the `convert` to not only convert audio data but also tag data to a format that my playback device understands.

Thus, it'd be nice to have an `id3v23` option in the `convert` plugins settings, to make sure that ID3v2.3 tags are written to all files that are copied/converted using this plugin.

**Comment by sampsyo** [comment]
Sounds useful!
