### ISSUE TITLE
"language-specific" folder inside main directory

### ISSUE THREAD

**Issue by daviddoji** [beetbox/beets#3106]
Is there a way to have a "Language-specific" folder inside the main directory folder? 
I have a bunch of spanish hiphop albums, which I haven't imported yet, and it could be awesome to have them in a separate folder from the american ones.
In the docs, it's mentioned that "at the moment, you can specify three special paths: `default` for most releases, `comp` for “various artist” releases with no dominant artist, and `singleton` for non-album tracks".

Thanks in advance.

P.S.: Wonderful piece of software!

**Comment by sampsyo** [comment]
Hello—have you tried a query-based path, as described in [this section of the docs](http://docs.beets.io/en/v1.4.7/reference/config.html#path-format-configuration)? The `albumtype:soundtrack` example therein sounds similar to what you want.

**Comment by daviddoji** [comment]
Sorry for the delay.
I tried to add the following line to my config.yaml:
`paths:
    albumtype:spanish: Spanish/$album/$track $title
`
After that, I imported a couple of spanish cd's I had in my collection, but they ended up in my "general" collection, instead in a separate "Spanish" folder as I wanted.

Am I missing something else?

**Comment by sampsyo** [comment]
Great! I'll close this issue then.
