### ISSUE TITLE
export: Don't try to compute unused fields, and probably don't include `filesize` by default in library exports

### ISSUE THREAD

**Issue by kuzi-moto** [beetbox/beets#3108]
### Problem

The main issue is that using the export plugin on large libraries (10k+ files) with a simple query is very slow. It took roughly an hour to export just the path and added fields from the library.

Running this command in verbose (`-vv`) mode:

```sh
$ beet -vv export -l -i "path" ultradyne theory
user configuration: /home/kuzi/.config/beets/config.yaml
data directory: /home/kuzi/.config/beets
plugin paths:
Sending event: pluginload
inline: adding item field multidisc
inline: adding item field disc_and_track
lastgenre: Loading canonicalization tree /usr/lib/python3.7/site-packages/beetsplug/lastgenre/genres-tree.yaml
library database: /home/kuzi/.config/beets/library.db
library directory: /home/kuzi/media/music
Sending event: library_opened
could not get filesize: [Errno 2] No such file or directory: b'/home/kuzi/media/music/Ultradyne/(2002) Unknown Works/01 - Theory Proliferation (Ultradyne Remix).mp3'
[
    {
        "path": "/home/kuzi/media/music/Ultradyne/(2002) Unknown Works/01 - Theory Proliferation (Ultradyne Remix).mp3"
    }
Sending event: cli_exit
]
```
Note: I purposely renamed that songs album to prove a point (otherwise nothing is mentioned). Why scan for the filesize if it's not needed? I'm not even querying the file metadata, just the library. Surely this will incur huge performance penalties in larger libraries.

Additionally there could be more verbose output for the plugin.

Here's a link to the music files that trigger the bug (if relevant): 
N/a

### Setup

* OS: arch linux
* Python version: 3.7.1
* beets version: 1.4.8
* Turning off plugins made problem go away (yes/no): no

My configuration (output of `beet config`) is:
Will post if needed

**Comment by sampsyo** [comment]
Got it; thanks for investigating! You may notice that items have a $filesize field that gets the actual size of the underlying file:

```
$ beet ls -f '$filesize'
```

I'm not sure this is the wisest idea in the world—we should investigate why this field exists in the first place. But in ordinary circumstances, it doesn't matter—code that doesn't use this field doesn't need to compute it. The export plugin is an exception, of course. There are two things we should probably do:

- Don't access all the fields when we only want one. That is, don't get the value of $filesize when you only want $path.
- Probably don't include $filesize at all in the default settings when exporting from the library.
