### ISSUE TITLE
More helpful message than "moving 0 albums"

### ISSUE THREAD

**Issue by RollingStar** [beetbox/beets#3117]
### Problem

When running beet mv, beets filters the move job to remove any move operations that have the same source and destination. But this can be unintuitive: albums will show up in "beet ls" then vanish when you run "beet mv".

https://github.com/beetbox/beets/blob/9556ab30face1faf5b5d756dd071cd1705a3f282/beets/ui/commands.py#L1485

```
λ beet ls -a Bad
Michael Jackson - Bad
“Weird Al” Yankovic - Bad Hair Day

λ beet mv -p -a Bad
Moving 0 albums.

λ beet mv -a Bad
Moving 0 albums.
```

# Proposed Solution

Save the results of `objs` into something like `orig_objs` and compare it to `objs` after the filter operation is complete. The new output message could be something like:

```
Moving 0 albums (found 2 with same source/destination)
```

**Comment by sampsyo** [comment]
Good call; this would be a useful thing to print.

**Comment by RollingStar** [comment]
https://github.com/beetbox/beets/compare/master...RollingStar:verbose-move

Here it is in action, with different output depending on if there are any objects filtered out.

```
λ beet mv -a bad                                          
Moving 0 albums (found 3 with same source & destination). 

λ beet mv -a bad                                          
Moving 3 albums.                                          

λ beet mv jackson                                         
Moving 71 items (found 11 with same source & destination).

λ beet mv jackson                                         
Moving 82 items.                                          

λ beet mv -a weird al                                     
Moving 1 album (found 15 with same source & destination). 
```

I think I have some work to do on my forked repo to not make this change have six git commits attached to it. Then I can submit a PR.

**Comment by sampsyo** [comment]
Awesome! Thank you!!

May I suggest some slightly simpler wording: for example, “15 already in place”?

**Comment by RollingStar** [comment]
Good idea.

https://github.com/beetbox/beets/pull/3120
