### ISSUE TITLE
Windows Unicode? issue displaying "something"

### ISSUE THREAD

**Issue by crkellen** [beetbox/beets#3122]
### Problem
![image](https://user-images.githubusercontent.com/6870231/51432877-c27e1300-1c04-11e9-9195-5099c0f0cd01.png)

I can't seem to find anyone else having this issue, and it doesn't even look like the characters themselves aren't displaying, but some sort of data around them. I'm not really certain. Either way, it makes it horrible to try and import things, and none of the Windows unicode fixes seem to be working.

Led to this problem:
```
Using "beet import FILEPATH"
```

### Setup

* OS: Window 10
* Python version: 3.7.2 
* beets version: 1.4.7
* Turning off plugins made problem go away (yes/no): No plugins are loaded in the first place.

My configuration (output of `beet config`) is: 
```yaml
directory: D:/MUSIC
library: D:/MUSIC_LIBRARY/library.db
```

**Comment by sampsyo** [comment]
Please see https://github.com/beetbox/beets/issues/2607.
