### ISSUE TITLE
replaygain: bs1770gain backend is associated with white nationalism

### ISSUE THREAD

**Issue by nichobi** [beetbox/beets#3127]
### Problem

It appears the creator of the bs1770gain backend used as an optional backend in the replaygain plugin is a staunch white nationalistAnd has dedicated the project "to [his] European heritage". This seems like something beets should distance itself from.
I've included the full quote from the [project website](http://bs1770gain.sourceforge.net) which is linked to in the [replaygain plugin manual](https://beets.readthedocs.io/en/v1.3.17/plugins/replaygain.html#bs1770gain). Clicking through to the creator's [personal site](http://home.snafu.de/pbelkner/) reveals much more of a similar nature.
> Nanos gigantum humeris insidentes: This project is dedicated to my European heritage. It is strictly to be understood as a statement against the saccarine "sweet" liberal lie of "multiculturalism" which is going to destroy Europe as we know it, in particular against the Merkel regime selling out Europe for nothing as we watch. #TeamWhite

**Comment by RollingStar** [comment]
"This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 2 of the License, or
(at your option) any later version."

Looks like it's ripe for someone to make a not racist fork. If that is not viable, I would support removing it entirely from beets.

**Comment by jackwilsdon** [comment]
We could consider linking to the [SourceForge.net project page](https://sourceforge.net/projects/bs1770gain/) directly, as opposed to the SourceForge project homepage? It's not ideal, as there's still a link back to the project homepage (and is still "supporting" the author to some extent).

Debian seems to be simply [patching out the message](https://sources.debian.org/src/bs1770gain/0.5.1-3/debian/patches/2000-non-controversial-usage.patch/) (see related issue [here](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=913352)) so it doesn't appear in the tool's output, which isn't something that really affects us.

[It appears that someone did fork it a while back, however it is no longer being maintained.](https://github.com/radiorabe/centos-rpm-bs1770gain), they suggest using [ffmpeg-normalize](https://github.com/slhck/ffmpeg-normalize) instead, which is certainly something we could look into.

**Comment by sampsyo** [comment]
Thank you for starting the discussion, @nichobi.

I think we should start by removing this backend from the plugin's documentation. This is an easy step that will avoid linking to the project's website. We can do this right now without breaking anyone's configuration. Would someone mind making a PR along those lines?

Then we can consider just dropping the backend altogether. #3056 (which uses ffmpeg's built-in gain analysis) is a very good candidate for replacing it, with very few downsides—I have fallen down on reviewing that (extremely complete, well written) PR, but any help I can get in doing a code review there would help us merge that new backend.

**Comment by nichobi** [comment]
I've made a pull request removing all references and any configuration options that are unique to this backend. I found no references to it in any other doc pages so hopefully I've got it all.

**Comment by Moonbase59** [comment]
Too sad that some apparently technically knowledgeable people feel the need to publish politically confused thoughts, misuse the saying "Standing on the shoulders of gaints", and even dedicate whole projects to their nationalism.

If only they could stand back, say about 238,714 miles, and see how laughable it is to draw things like "borders" on this beautiful little golf ball called "Earth", and defend those with their lives … instead of caring for each other and this planet we all call "Home".

I am Terran, born in Germany by pure chance, and I support the removal.

**Comment by sampsyo** [comment]
Thanks for the note. We have actually removed this from the docs already in #3130 (so at least we no longer link to the project site).
