### ISSUE TITLE
Cut a new release

### ISSUE THREAD

**Issue by bemeurer** [beetbox/beets#3141]
Since it's been a while since beets saw a release, and the current trunk has a number of nice features and has accumulated about the same number of commits as in between the last two releases, I would like to request for a new release to be cut.

Hope this is on-topic, thanks!

**Comment by sampsyo** [comment]
On-topic and a very reasonable thing to request! I know this is desperately needed and hope to bite the bullet as soon as I possibly can. (In future cycles, I would love to remove myself as a SPOF for releases...)
