### ISSUE TITLE
ImportError: cannot import name 'NoReturn'

### ISSUE THREAD

**Issue by DarkVirtue** [beetbox/beets#3143]
### Problem

Any invocation of beet immediately fails. This was working as recently as three weeks ago.

Running this command in verbose (`-vv`) mode:

```sh
$ beet -vv import Amaranthe
Traceback (most recent call last):
  File "/usr/local/bin/beet", line 7, in <module>
    from beets.ui import main
  File "/usr/local/lib/python3.5/dist-packages/beets/ui/__init__.py", line 42, in <module>
    from beets.autotag import mb
  File "/usr/local/lib/python3.5/dist-packages/beets/autotag/__init__.py", line 26, in <module>
    from .match import tag_item, tag_album, Proposal  # noqa
  File "/usr/local/lib/python3.5/dist-packages/beets/autotag/match.py", line 24, in <module>
    from munkres import Munkres
  File "/usr/local/lib/python3.5/dist-packages/munkres.py", line 20, in <module>
    from typing import Union, NewType, Sequence, Tuple, NoReturn, Optional, Callable
ImportError: cannot import name 'NoReturn'
```

### Setup

* OS: Debian 9
* Python version: 3.5.3
* beets version: 1.4.7 (I think; beet --version fails with the above error)
* Turning off plugins made problem go away (yes/no): no

My configuration (output of `beet config`) is:

```yaml
directory: /home/media/music
library: /var/lib/beets/data/musiclibrary.db
plugins: fetchart lyrics lastgenre multidisc missing scrub
import:
  move: yes
  language: en
paths:
  default: $albumartist_sort - $album ($year)/%if{$multidisc,Disc $disc%if{$disctitle, - $disctitle}/}/$track - $title
asciify_paths: yes
missing:
  format: $albumartist_sort - $album ($year)/%if{$multidisc,Disc $disc%if{$disctitle, - $disctitle}/}/$track - $title
  count: no
  total: no
```

**Comment by ethanrjones97** [comment]
Seconding this bug report. 
```
Traceback (most recent call last):
  File "/home/erj/.local/bin/beet", line 7, in <module>
    from beets.ui import main
  File "/home/erj/.local/lib/python3.5/site-packages/beets/ui/__init__.py", line 42, in <module>
    from beets.autotag import mb
  File "/home/erj/.local/lib/python3.5/site-packages/beets/autotag/__init__.py", line 26, in <module>
    from .match import tag_item, tag_album, Proposal  # noqa
  File "/home/erj/.local/lib/python3.5/site-packages/beets/autotag/match.py", line 24, in <module>
    from munkres import Munkres
  File "/home/erj/.local/lib/python3.5/site-packages/munkres.py", line 20, in <module>
    from typing import Union, NewType, Sequence, Tuple, NoReturn, Optional, Callable
ImportError: cannot import name 'NoReturn'
```

# Setup 

* OS: Trisquel 8
* Python version:  3.5.2
* beets version: 1.4.7 - freshly installed from `pip3`
* Turning off plugins made problem go away (yes/no): no

# Config
```
directory: ~/Muisc
library: ~/.config/beets/musiclibrary.db
plugins: fetchart lyrics badfiles scrub zero duplicates missing
zero:
    fields: comments images acoustid_fingerprint
    update_database: true
```
However, my other machine **does not** have this error:

# Setup 

* OS: Ubuntu 18.04
* Python version: 3.6.7
* beets version: 1.4.7 - freshly upgraded with `pip3`

My guess is a recent library update broke Python 3.5.x support.

**Comment by jackwilsdon** [comment]
It seems that munkres has changed it's minimum Python version - their [changelog](https://github.com/bmc/munkres/blob/master/CHANGELOG.md) says that it still supports 3.5, however the typings they've added require 3.6.5 ([`typing.NoReturn` was only introduced in Python 3.6.5](https://docs.python.org/3/library/typing.html#typing.NoReturn)).

**Comment by sampsyo** [comment]
Yep! That sounds like exactly what's going on, @jackwilsdon. Thanks for looking into it.

I recommend we do both: pin the version for now, and also file an issue to tell the Munkres developers that their requirements don't align with the code.

**Comment by jackwilsdon** [comment]
After doing a little bit more digging, it seems it was actually added in Python 3.5.4 and the Python docs are wrong! This is still less than ideal, so I'm opening a PR on munkres to remove uses of `typing.NoReturn` until they drop support for <3.5.4.

**Comment by sampsyo** [comment]
Fantastic! Thank you for digging into the issue. :sparkles:

**Comment by jackwilsdon** [comment]
munkres 1.1.2 has been released with a fix for <3.5.4.

@DarkVirtue @ethanrjones97 could you try `pip install -U beets`? It should update the version of `munkres` installed.

If that doesn't work try `pip install -U munkres==1.1.2`, but you shouldn't need to do that as updating beets should sort it out for you.

**Comment by DarkVirtue** [comment]
Pip grabbed the new version of munkres and beets is working fine for me now.

Thanks a ton!

**Comment by sampsyo** [comment]
Wow; that was quick!! Thanks for the fast work, @jackwilsdon!
