### ISSUE TITLE
Issue Tracker: Use different colors for bug/needinfo/feature labels

### ISSUE THREAD

**Issue by Holzhaus** [beetbox/beets#3156]
Most issues are tagged with one of the following labels:

- [bug](https://github.com/beetbox/beets/issues?utf8=%E2%9C%93&q=label%3Abug)
- [needinfo](https://github.com/beetbox/beets/issues?utf8=%E2%9C%93&q=label%3Aneedinfo)
- [feature](https://github.com/beetbox/beets/issues?utf8=%E2%9C%93&q=label%3Afeature)

Unfortunately, their label badges all have the same color, which makes it hard to visually distinguish them.

**Comment by sampsyo** [comment]
Yeah, this is a good idea. I originally thought it would be nice for these three “core” category tags to be visually similar, but that was obviously wrongheaded. 😃 

I know this is inviting literal bikeshedding, but any thoughts about what the colors should be? I’ll try some random ones now and folks are welcome to suggest better ones.

**Comment by jackwilsdon** [comment]
Maybe red for bugs, orange/yellow for needinfo and current pink for feature?

**Comment by Holzhaus** [comment]
@jackwilsdon Yup, sounds reasonable.
