### ISSUE TITLE
Musicbrainz' "Artist as credited" not honored

### ISSUE THREAD

**Issue by Holzhaus** [beetbox/beets#3161]
### Problem

Beets does not honor the "Artist as credited" field when importing releases. For example, I imported this release:
- https://musicbrainz.org/release/a3a961c9-d482-4c05-aea0-10e3199bb8c1

It is by *Todd Terry All Stars feat. Kenny Dope, DJ Sneak, Terry Hunter & Tara McDonald*, where Kenny Dope is actually *Kenny "Dope" Gonzales*, but he's just credited as *Kenny Dope*. However, beets seems to ignore that. Files/folders created/moved by beets still use the long name and the tags written by beets contain the long name as well.

```
$ beet ls artist:"Todd Terry All Stars"
Todd Terry All Stars feat. Kenny “Dope” Gonzalez, DJ Sneak, Terry Hunter & Tara McDonald - Get Down - Get Down (The Shapeshifters vocal mix)
Todd Terry All Stars feat. Kenny “Dope” Gonzalez, DJ Sneak, Terry Hunter & Tara McDonald - Get Down - Get Down (Mousse T Classic club mix)
Todd Terry All Stars feat. Kenny “Dope” Gonzalez, DJ Sneak, Terry Hunter & Tara McDonald - Get Down - Get Down (Warren Clarke remix)
Todd Terry All Stars feat. Kenny “Dope” Gonzalez, DJ Sneak, Terry Hunter & Tara McDonald - Get Down - Get Down (Kenny Dope original)
Todd Terry All Stars feat. Kenny “Dope” Gonzalez, DJ Sneak, Terry Hunter & Tara McDonald - Get Down - Get Down (Woody Bianchi Shakedown remix)

$ metaflac --list --block-type=VORBIS_COMMENT *.flac
[...]
01-04 - Todd Terry All Stars feat. Kenny _Dope_ Gonzalez, DJ Sneak, Terry Hunter & Tara McDonald - Get Down (Kenny Dope original).flac:    comment[3]: ALBUM ARTIST=Todd Terry All Stars feat. Kenny “Dope” Gonzalez, DJ Sneak, Terry Hunter & Tara McDonald
01-04 - Todd Terry All Stars feat. Kenny _Dope_ Gonzalez, DJ Sneak, Terry Hunter & Tara McDonald - Get Down (Kenny Dope original).flac:    comment[4]: ALBUMARTIST=Todd Terry All Stars feat. Kenny “Dope” Gonzalez, DJ Sneak, Terry Hunter & Tara McDonald
01-04 - Todd Terry All Stars feat. Kenny _Dope_ Gonzalez, DJ Sneak, Terry Hunter & Tara McDonald - Get Down (Kenny Dope original).flac:    comment[5]: ALBUMARTIST_CREDIT=Todd Terry All Stars feat. Kenny Dope, DJ Sneak, Terry Hunter & Tara McDonald
[...]
```

### Setup

* OS: Arch Linux
* Python version: 3.7.2
* beets version: 3973efc  
* Turning off plugins made problem go away (yes/no): no

My configuration (output of `beet config`) is: https://gist.github.com/Holzhaus/500b790c06fe2250ac9182bd8a6760da

**Comment by sampsyo** [comment]
Hi! have you checked out the $artist_credit field?

**Comment by Holzhaus** [comment]
Whoops, you're right. Sorry for the noise. There is no bug, I'm just dumb ;-)

However, maybe should change the default config so that the `_credit` version of the `$artist`/`$albumartist` fields are used ([lines 85- 86](https://github.com/beetbox/beets/blob/master/beets/config_default.yaml#L85-L86) and [85-97](https://github.com/beetbox/beets/blob/master/beets/config_default.yaml#L95-L97)), because that's how artists should be credited.

**Comment by jackwilsdon** [comment]
My concern with changing that now is that it's somewhat a breaking change — people upgrading and then importing songs will end up with them in different directories (using the `_credit` variants of the fields).

It wouldn't affect people manually overriding that configuration option, but I'd hazard a guess that a majority don't

**Comment by sampsyo** [comment]
That's a good insight, @Holzhaus, but here I tend to agree with @jackwilsdon. For my own personal preference, for example, I actually like using the "canonical" artist name for filenames—this way, artists who are credited differently on different releases still consistently get mapped to the same directory name, for example.

Maybe we can document somewhere that getting the "credit" version is an easy config change to make!
