### ISSUE TITLE
Jumbled Interface

### ISSUE THREAD

**Issue by bryangauvin** [beetbox/beets#3175]
### Problem

Import interface jumbled with random characters. How do I fix this?

# selection (default [36;01m1[39;49;00m), [34;01mS[39;49;00mkip, [34;01mU[39;49;00mse as-is, as [34;01mT[39;49;00mracks, [34;01mG[39;49;00mroup albums,

### Setup

* OS: Windows 10

**Comment by jackwilsdon** [comment]
It looks like this is a known issue, see #2607.
