### ISSUE TITLE
convert plugin estimate size

### ISSUE THREAD

**Issue by steven-murray** [beetbox/beets#3178]
I actually have two requests to do with the ``convert`` plugin. 

The first is that it would be awesome if one could do a dry run that just estimates the total size of the output. This is useful if one is attempting to use ``convert`` to copy over files to a mobile device, for instance, that has limited space. 

The second request is to have some way of keeping track of the output from ``convert``, so that a second run doesn't convert every file, but notices if it is already there. This would be a way to "sync" two music directories (again, I am thinking of mobile devices here).

To me, the first request sounds reasonably simple (but perhaps I'm naive), while the second may be a little more complicated.

**Comment by sampsyo** [comment]
Interesting… how would you anticipate the size estimation working? Currently, the `convert` option just passes flags off to another tool. It doesn't actually know what the bitrate of the target format is, for example. Would you have to configure "by hand" an expected output size per minute?

Incremental conversion could be interesting, however!

**Comment by jackwilsdon** [comment]
`beet convert` won't replace any files in the target directory, so it does somewhat "incremental" converts (but it doesn't update metadata, which is why it's not truly incremental).

**Comment by steven-murray** [comment]
@sampsyo Ah, so it would be more difficult than I first suspected to do the size estimation. I guess it would have to be by hand. I guess I was thinking that ``convert`` has information about the current bitrate of each track, and also has the max bitrate for the conversion. Perhaps it could at least give an upper estimate? I.e. for each track that will be converted, use either current bitrate (if below max bitrate) or else max bitrate, multiplied by length, to get an estimate. 

@jackwilsdon That's good to know! What happens if you change the max bitrate setting? Will it then overwrite the files, knowing that they have updated information? I guess it can't know whether those files have a different bitrate then requested, right?

**Comment by jackwilsdon** [comment]
> I guess I was thinking that convert has information about the current bitrate of each track, and also has the max bitrate for the conversion.

beets doesn't know what the output bitrate will actually be and doesn't even set a cap on what the output bitrate _could_ be. `max_bitrate` is used as a threshold to decide what should be converted (anything with a bitrate above `max_bitrate` is converted, anything below is just copied).

The `convert` plugin just has a list of commands which can be override by the user in their configuration, which makes it very difficult to calculate filesize without just performing the conversion;

https://github.com/beetbox/beets/blob/1e075675d0d84cd8158f291d03735ef94a6f32b3/beetsplug/convert.py#L120-L138

--- 

> I guess it can't know whether those files have a different bitrate then requested, right?

Correct, it only does a simple existence check based on the filename;

https://github.com/beetbox/beets/blob/1e075675d0d84cd8158f291d03735ef94a6f32b3/beetsplug/convert.py#L286-L289

**Comment by steven-murray** [comment]
Ahh. I understand a little better now. So that is super flexible and simple, since the user can just specify the format/command themselves, but on the other hand, doesn't provide much information to ``convert``. 

I'll have a poke around in ``convert.py`` and see what I can come up with. Thanks for your help!

**Comment by sampsyo** [comment]
Awesome! Thanks for weighing in with all the background, @jackwilsdon. I'll close this for now, but please feel free to continue to ask questions.

**Comment by wisp3rwind** [comment]
@steven-murray: With regard to your second question, have a look at the [beets-alternatives](https://github.com/geigerzaehler/beets-alternatives) plugin, that might be exactly what you're looking for (if your usecase is indeed mobile devices).

**Comment by steven-murray** [comment]
Oh wow, I don't know I hadn't seen that before! Amazing, thanks!
