### ISSUE TITLE
How can I set a template for the year in a tag?

### ISSUE THREAD

**Issue by msdos** [beetbox/beets#3181]
In the past, when setting `year` manually on my tags, this value was `YYYY`. After using beets and musicbrainz autotagger, I'm getting `YYYY-MM-DD`. I prefer the `YYYY` format. Is this possible in an easy way (and I'm missing something in the documentation), not possible or do I have to create beets plugin for this?

**Comment by sampsyo** [comment]
You should be able to use the `zero` plugin to zero out the month and day.

**Comment by msdos** [comment]
I don't want to `zero` them, just have in the `year` tag of the file itself the pattern `YYYY`. Are you telling me this is not possible unless I really `zero` these fields and them beets is going to write the ID3 tag with just the `year`?

**Comment by sampsyo** [comment]
Depending on the file format, there may be no other special field for the month and day. So the beets-level fields that beets calls `month` and `day` are backed—in the tag storage—by fragments of the date field. (In some formats, including ID3, this date field is misnamed the "year" field, even though the standard says that it can hold a complete date.)

**Comment by msdos** [comment]
I see. I think I will just keep the way beets handles these things. I'l not try to outsmart the design. Thanks!
