### ISSUE TITLE
Can FetchArt ignore a pattern from cover_names?

### ISSUE THREAD

**Issue by msdos** [beetbox/beets#3182]
`cover_names: Prioritize images containing words in this list. Default: cover front art album folder.`

Here is my problem: I have an image that has `cover` substring but if it can have another substring that, if present, that jpg should be ignored.

- my-image-cover.jpg - it's ok, can be used.
- my-image-cover-something.jpg - it has 'cover', but since it has 'something' too it should be ignored.

Is this possible? Or this should be a feature request? Like a `cover_names_ignore` option?

**Comment by sampsyo** [comment]
The global "ignore" config option works for cover art files:
http://docs.beets.io/en/v1.4.7/reference/config.html#ignore

Maybe give that a try? There's not currently a fetchart-specific ignore setting.

**Comment by msdos** [comment]
I'm sorry. After your message, I just found out this is a duplicate of https://github.com/beetbox/beets/issues/1632.

I'm using beets 1.4.7. I need to wait for 1.4.8 release for this fix. Where can I find documentation about the release cycle of beets?

**Comment by sampsyo** [comment]
This might be some useful context. :)
https://discourse.beets.io/t/forming-a-beets-core-team/639

**Comment by msdos** [comment]
I'm not the ideal person here to create new releases 😆 

But thanks for the insight. I suggest mentioning everyone who is still active from https://github.com/beetbox/beets/graphs/contributors to help you. I agree with your post and thanks for the great work so far. You indeed answer everything that happens here!
