### ISSUE TITLE
Help Total Newbie to all this.

### ISSUE THREAD

**Issue by buster-uk** [beetbox/beets#3191]
Trouble is I have no coding clue.

this is my default config file location as in beet config -p

**/var/services/homes/admin/.config/beets/config.yaml**

and this is the folder were my music is stored.

**/volume1/Audio**

I have no clue how to rewrite the config file to point to the directory.

using ssh into synology DS218+, Python 2.7.

Can anyone help?

**Comment by sampsyo** [comment]
Can you please point to the step in the “Getting Started” guide where you got stuck?

**Comment by buster-uk** [comment]
[http://iamanerd.org.uk/beets-installation-on-synology-nas/](url)

Following this Guide.

I am Stuck after entering the beet config -p command. I have the default path that is were I am Stuck. How to edit it to point to my music folder. I think I need a dummies dummy guide.

**Comment by sampsyo** [comment]
Please try our own "Getting Started" guide.

**Comment by buster-uk** [comment]
![beet1](https://user-images.githubusercontent.com/49002764/55116897-ca64a280-50e0-11e9-819f-598f54795469.jpg)

This is as far as I get Now I am stuck??

**Comment by sampsyo** [comment]
The question I’m asking is: what place in the guide (i.e., which paragraph) do you not understand? What specific directions in there are you unable to follow?

**Comment by jackwilsdon** [comment]
I'm going to go ahead and close this if that's alright with  you @sampsyo, as this is really a discussion to be taken to the [forums](https://discourse.beets.io/).
