### ISSUE TITLE
Removing all external album art images?

### ISSUE THREAD

**Issue by mkono87** [beetbox/beets#3218]
So I have been having a lot a of trouble with airsonic and album art. Beets has been awesome in renaming my collection but having an issue with getting the proper albums covers. Each of the album folders has a albumart.jpg but its a picture of the album with the cd. I tried removing the metadata and refetching but nothing seems to work. Beets will just say album already album art. Is there anyway to remove all the jpg and not just the images from metadata? I know in airsonic I can just click each album and use last.fm to download the art but I was hoping Beets can correctly do it all for me at once. By default airsonic is looking for cover.jpg or png.

**Comment by sampsyo** [comment]
Hi! Have you tried running the fetchart command with the force option to replace existing art?

**Comment by mkono87** [comment]
Actually I just found that option and used it. I did notice a few that could be replaced again if possible. Any way to trigger a new search of one album?

**Comment by jackwilsdon** [comment]
Try this;
```
beet fetchart -f [album name]
```

**Comment by mkono87** [comment]
Just tried, gives me the same art.

**Comment by jackwilsdon** [comment]
When you say "same art", what do you mean? The art it's finding is probably what beets thinks is the optimal art based on your sources. Could you provide the output of `beet config`?

**Comment by mkono87** [comment]
It is the correct album but has a bunch of Japanese writing on it. Here you go:
`plugins: fetchart embedart convert scrub replaygain lastgenre chroma web
directory: /music
library: /config/musiclibrary.blb
art_filename: albumart
threaded: yes
original_date: no
per_disc_numbering: no

convert:
    auto: no
    ffmpeg: /usr/bin/ffmpeg
    opts: -ab 320k -ac 2 -ar 48000
    max_bitrate: 320
    threads: 1
    
paths:
    default: $albumartist/$album%aunique{}/$track - $title
    singleton: Non-Album/$artist - $title
    comp: Compilations/$album%aunique{}/$track - $title
    albumtype_soundtrack: Soundtracks/$album/$track $title 
        
import:
    write: yes
    copy: no
    move: yes
    resume: ask
    incremental: yes
    quiet_fallback: skip
    timid: no
    log: /config/beet.log

lastgenre:
    auto: yes
    source: album

embedart:
    auto: yes

fetchart:
    auto: no
    cautious: yes
    
    
replaygain:
    auto: no

scrub:
    auto: yes

replace:
    '^\.': _
    '[\x00-\x1f]': _
    '[<>:"\?\*\|]': _
    '[\xE8-\xEB]': e
    '[\xEC-\xEF]': i
    '[\xE2-\xE6]': a
    '[\xF2-\xF6]': o
    '[\xF8]': o
    '\.$': _
    '\s+$': ''

web:
    host: 0.0.0.0
    port: 8337

chroma:
    auto: no
    
discogs:

musicbrainz:
    user: user
    pass: pass

    `

**Comment by jackwilsdon** [comment]
What album is it specifically you're having the issue with? Beets will try and use sources in this order;

 - filesystem (unless `-f / --force`)
 - coverart (coverartarchive.org)
 - itunes
 - amazon
 - albumart (albumart.org)
 - wikipedia
 - google (only if API key is provided)
 - fanarttv (only if API key is provided)

**Comment by mkono87** [comment]
One if for a Limp Bizkit album https://imgur.com/a/2Q42VVP. This time im going to just manually add it to the folder.

**Comment by sampsyo** [comment]
Hi, @mkono87—as @jackwilsdon explained, it would be a good idea to look into where this "bad" album art is coming from. You can configure the plugin to use many different sources, and you might want to eliminate the source that gave you the cover art you don't like.

**Comment by mkono87** [comment]
Yes I noticed that this particular one is coming from MusicBrainz but the first entry is a version from Japan thus the unwanted image was pulled. I guess in this case I would have to choose a different source all together? Can I specify sources for each fetchart command or do I have to disable it completely in config?

Beets has been a lifesaver though since Lidarr doesn't seem to do anything for album/artist art.

**Comment by jackwilsdon** [comment]
What is the exact MBID of the album in question? This should give you it;

```
beet ls -af '$album - $albumartist - $mb_albumid'
```

**Comment by mkono87** [comment]
@jackwilsdon cf3e8681-b4e1-4487-a2eb-80953c007df8

which is odd as there is no album art tied to that ID.

**Comment by jackwilsdon** [comment]
So it looks like what happens is that the CoverArtArchive source provides a list of candidates consisting of the release ID and also the release group ID. Because there is no artwork for the release on CoverArtArchive it falls back to the release group.

You can tell beets to fall back to release group artwork as a last resort after running through other sources, which should sort out your problem nicely.

```YAML
fetchart:
    sources:
        - coverart: release
        - '*'
        - coverart: releasegroup
```

**Comment by mkono87** [comment]
@jackwilsdon Great il check that out and do some trial and error as time goes on. One more question and this issue can be closed. What would be the proper procedure to tell beets only look for US releases for example?

**Comment by jackwilsdon** [comment]
I'm not really sure regarding that sorry, I'm not really an expert on `beet import` functionaliyt.

**Comment by sampsyo** [comment]
See the [import.preferred](http://docs.beets.io/en/v1.4.7/reference/config.html#preferred) config options.

**Comment by mkono87** [comment]
Thanks I tried using the prefered option and even though there is a US release it just wont budge from being tagged Japan. Any of those gets the Japanese album art. I have no choice it seems but to change them manually

**Comment by sampsyo** [comment]
@mkono87, if you want help with a problem like this, we will need more detail. It's really hard to say what's going on with those high-level impressions. Please feel free to open a new issue with complete details.
