### ISSUE TITLE
LastGenre for Singletons?

### ISSUE THREAD

**Issue by rain0r** [beetbox/beets#3219]
Is it possible to fetch genre tags for singletons after the import?

Currently, `beet lastgenre --force --source=track singleton:true` is not doing anything, but when I import new singletons, the plugin fetches genre tags.

**Comment by sampsyo** [comment]
Can you include the verbose output?

**Comment by sampsyo** [comment]
Aha, actually, belay that! Looking back at the code, it looks like the command _only_ matches albums, not individual tracks. That's an artificial limitation, of course, so it shouldn't be too hard to add a track-matching mode if anyone's interetsted.

**Comment by rain0r** [comment]
... or just do the magic that happens when doing an `beet import -s`?

Could you point me to the corresponding location in the the code, please?

**Comment by rain0r** [comment]
I think i found it.
https://github.com/beetbox/beets/pull/3220
