### ISSUE TITLE
Beatport Genres 

### ISSUE THREAD

**Issue by elvinos** [beetbox/beets#3229]
**Feature Request** 

Due to most of my music being electronic, Last Fm struggles to find a lot of my music's genres. 

Beatport, on the other hand, has a much more comprehensive electronic library with most of the genres of my missing tracks. 

Could an option to add Beatport genres to track matches be added? This would be a great feature which I don't believe someone with slightly more understanding of this software could quickly implement.

Thanks

**Comment by sampsyo** [comment]
Hi! Please see #2080—that covers genre and other metadata that we should fetch from Beatport.
