### ISSUE TITLE
Unhandled UnicodeEncodeError exception when logging actions on album with unicode characters

### ISSUE THREAD

**Issue by ababyduck** [beetbox/beets#3240]
### Problem

Skipping the import of an album with unicode characters in the directory throws a `UnicodeEncodeError` exception if logging is enabled.

Steps to reproduce:
- Enable log output (set the `import:log:` node in config.yaml)
- Attempt to import an album which already exists in your library, which has unicode characters  in the filename (e.g. ö, •)
- When prompted to skip/keep/remove/merge, choose any action that would normally be logged, such as Skip or Remove

Running this command in verbose (`-vv`) mode:

```sh
$ beet -vv import test
```
(Contains a subdirectory with a Björk album)

Led to this problem:

```
S:\Music\old\test\Björk -2017- Utopia (FLAC) (14 items)
Tagging:
    Björk - Utopia
URL:
    https://musicbrainz.org/release/35d473b5-8a54-4fbd-a830-1cf7aadf17ee
(Similarity: 100.0%) (CD, 2017, US, One Little Indian Records, tplp1381cd, special edition)
This album is already in the library!
Old: 14 items, FLAC, 863kbps, 71:47, 456.7 MiB
New: 14 items, FLAC, 863kbps, 71:47, 449.7 MiB
[S]kip new, Keep both, Remove old, Merge all? s
--- Logging error ---
Traceback (most recent call last):
  File "c:\python\python37-32\lib\logging\__init__.py", line 1037, in emit
    stream.write(msg + self.terminator)
UnicodeEncodeError: 'cp932' codec can't encode character '\xf6' in position 35: illegal multibyte sequence
Call stack:
  File "c:\python\python37-32\lib\threading.py", line 885, in _bootstrap
    self._bootstrap_inner()
  File "c:\python\python37-32\lib\threading.py", line 917, in _bootstrap_inner
    self.run()
  File "c:\python\python37-32\lib\site-packages\beets\util\pipeline.py", line 312, in run
    out = self.coro.send(msg)
  File "c:\python\python37-32\lib\site-packages\beets\util\pipeline.py", line 171, in coro
    task = func(*(args + (task,)))
  File "c:\python\python37-32\lib\site-packages\beets\importer.py", line 1399, in user_query
    resolve_duplicates(session, task)
  File "c:\python\python37-32\lib\site-packages\beets\importer.py", line 1461, in resolve_duplicates
    session.log_choice(task, True)
  File "c:\python\python37-32\lib\site-packages\beets\importer.py", line 264, in log_choice
    self.tag_log(u'duplicate-skip', paths)
  File "c:\python\python37-32\lib\site-packages\beets\importer.py", line 249, in tag_log
    self.logger.info(u'{0} {1}', status, displayable_path(paths))
  File "c:\python\python37-32\lib\logging\__init__.py", line 1383, in info
    self._log(INFO, msg, args, **kwargs)
  File "c:\python\python37-32\lib\site-packages\beets\logging.py", line 91, in _log
    return super(StrFormatLogger, self)._log(level, m, (), exc_info, extra)
Message: <beets.logging.StrFormatLogger._LogMessage object at 0x0373E450>
Arguments: ()
```
[(full output)](https://hastebin.com/tucafigazu.bash)

### Setup

* OS: Windows 10
* Python version: 3.7.3
* beets version: 1.4.8
* Turning off plugins made problem go away (yes/no): no

My configuration (output of `beet config`) is:

```yaml
$ beet config
directory: S:/Music/sorted
pluginpath: S:/Music/beets/plugins
library: S:/Music/beets/library_windows.db

import:
    log: S:/Music/beets/log.txt
    bell: yes
terminal_encoding: utf8

ui:
    color: yes

match:
    preferred:
        countries:
        - US
        - JP
        - XE
        - XW
        media: [CD, Digital Media|File]
        original_year: yes
    required: year

paths:
    default: '%the{$albumartist}/%if{$original_year,$original_year,$year} - $album/$disc_and_track - $title'
    singleton: '%the{$artist}/Singletons/$artist - $title'
    comp: (Compilations)/%if{$original_year,$original_year,$year} - $album/$disc_and_track - $artist - $title
languages: en jp
per_disc_numbering: yes
item_fields:
    media_simple: "media_lookup = {\n    '7\" Vinyl': 'Vinyl',\n    '10\" Vinyl': 'Vinyl',\n    '12\" Vinyl': 'Vinyl',\n    'Compact Disc': 'CD',\n    'Digital Media': 'Web'\n}\nreturn media_lookup.get(media, media)\n"
    disc_and_track: u'[%02i] %02i' % (disc, track) if disctotal > 1 else u'%02i' % (track)
chroma:
    auto: yes
acoustid:
    apikey: N7veFJKSsk
ftintitle:
    auto: yes
    drop: no
embedart:
    auto: yes
    maxwidth: 600
fetchart:
    auto: yes
    sources: coverart itunes amazon albumart
    store_source: yes
    minwidth: 300
    maxwidth: 2000
lyrics:
    auto: no
    sources: genius musixmatch
replaygain:
    backend: bs1770gain
zero:
    fields: month day genre
extrafiles:
    patterns:
        cuelog: ['*.cue', '*.log']
        info: [info.txt, source.txt, release.txt]

    paths:
        cuelog: $albumpath/$album
    info:
        info: $albumpath/info
convert:
    never_convert_lossy_files: yes
    format: wav
    formats:
        wav:
            command: flac -d $source $dest
        flac:
            command: flac -8 -V $source -o $dest
        mp3:
            command: lame -V 0 -q 2 --noreplaygain $source $dest
rewrite:
    artist A New Found Glory: New Found Glory
    artist Ben Folds Five: Ben Folds
    artist Bob Marley * The Wailers: Bob Marley
    "artist CHVRCH\u039ES": CHVRCHES
    artist Freddie Mercury*: Freddie Mercury
    artist Jenny Lewis * Watson Twins: Jenny Lewis
    artist Makaveli: 2Pac
    artist Prince * Revolution: Prince
    artist Sting: The Police
    artist The Jackson 5: Michael Jackson
    artist The Jimi Hendrix Experience: Jimi Hendrix
    artist Tom Petty * Heartbreakers: Tom Petty
    "artist \u30AE\u30ACP": "GigaP (\u30AE\u30ACP)"
    "artist \u6D5C\u5D0E\u3042\u3086\u307F": "Hamasaki, Ayumi (\u6D5C\u5D0E\u3042\u3086\u307F)"
    "artist \u5E83\u6A4B\u771F\u7D00\u5B50": "Hirohashi, Makiko (\u5E83\u6A4B\u771F\u7D00\u5B50)"
    "artist \u4E45\u77F3\u8B72": "Hisaishi, Joe (\u4E45\u77F3\u8B72)"
    "artist \u304D\u306E\u3053\u5E1D\u56FD": "Kinoko Teikoku (\u304D\u306E\u3053\u5E1D\u56FD)"
    "artist \u6C34\u7530\u76F4\u5FD7": "Mizuta, Naoshi (\u6C34\u7530\u76F4\u5FD7)"
    "artist \u68EE\u306F\u751F\u304D\u3066\u3044\u308B": "Mori Wa Ikiteiru (\u68EE\u306F\u751F\u304D\u3066\u3044\u308B)"
    "artist \u308C\u3092\u308B": "Reol (\u308C\u3092\u308B)"
    "artist \u51DB\u3068\u3057\u3066\u6642\u96E8": "Rin Tosite Sigure (\u51DB\u3068\u3057\u3066\u6642\u96E8)"
    "artist \u798F\u5C45\u826F": "Fukui, Ryo (\u798F\u5C45\u826F)"
    "artist \u30B7\u30CA\u30EA\u30AA\u30A2\u30FC\u30C8": "Scenario Art (\u30B7\u30CA\u30EA\u30AA\u30A2\u30FC\u30C8)"
    "artist \u7956\u5805\u6B63\u6176": "Soken, Masayoshi (\u7956\u5805\u6B63\u6176)"
    "artist \u690D\u677E\u4F38\u592B": "Uematsu, Nobuo (\u690D\u677E\u4F38\u592B)"
    "artist \u5B87\u591A\u7530\u30D2\u30AB\u30EB": "Utada, Hikaru (\u5B87\u591A\u7530\u30D2\u30AB\u30EB)"
    "artist VHS\u30C6\u30FC\u30D7\u30EA\u30EF\u30A4\u30F3\u30C0\u30FC": "VHS Tape Rewinder (VHS\u30C6\u30FC\u30D7\u30EA\u30EF\u30A4\u30F3\u30C0\u30FC)"
    "artist \u5C71\u5D0E\u30CF\u30B3": "Yamasaki, Hako (\u5C71\u5D0E\u30CF\u30B3)"
    "artist \u30E8\u30EB\u30B7\u30AB": "Yorushika (\u30E8\u30EB\u30B7\u30AB)"
```
Plugins disabled in the above output for testing, [full config here](https://gist.github.com/ababyduck/7ab6c834b73b9824c9615795db00e644) if relevant.

**Comment by ababyduck** [comment]
Also occurs with the following album: `E•MO•TION Side B`

**Comment by sampsyo** [comment]
Wow! This is really bad—and it may be really really hard to fix, because of the way Python 3 works. Here, we are trying to log a perfectly well-behaved Unicode string using Python's built-in `logging` module, but due to your system's configuration, Python is trying use an encoding that doesn't support the characters in the filename.

(One really frustrating thing about using Python 3 is that it can run into situations like this: where the system's configuration leads to exceptions in perfectly well-behaved Unicode-using programs.)

Can you try configuring your system to use a proper Unicode locale, so that Windows tells Python to use something like UTF-8? Beyond that, I'm not sure whether it's feasible for beets itself to do anything.

**Comment by arogl** [comment]
I currently use conemu as my wrapper around cmd.exe and have very few issues with unicode, however while researching I found the following:

https://stackoverflow.com/questions/388490/how-to-use-unicode-characters-in-windows-command-line

Which led to

https://stackoverflow.com/questions/39736901/chcp-65001-codepage-results-in-program-termination-without-any-error/39745938#39745938

and a possible solution

https://pypi.org/project/win_unicode_console/

I'll add the win_unicode_console and test in a standard cmd.exe

**Comment by ababyduck** [comment]
Unfortunately, I work with legacy software that requires a Japanese system locale to function properly, so it's not practical for me to switch back to English for every day use.

I suspect the most practical workaround would be to run my imports through the Windows Subsystem for Linux, although then I run into the issue where the db only gets linux file paths and doesn't know how to find them when I switch back to Windows (By the way, I would love to add or see this feature. If not storing both paths in the db, maybe a user-configurable way to translate something like `/mnt/c/Music` to `C:\Music`)

What about catching the exception and running a regex replace on strings before logging them, and just printing a warning that the filename may not be 100% accurate?

**Comment by sampsyo** [comment]
The right solution to something like this will require digging deep into Python's logging module. We already work around issues like this with our `print` replacement in our `ui_` module, where we do the encoding ourselves to avoid the bad behavior in Python 3's built-in `print`; we will need to orchestrate a similar dance for the `logging` calls.

**Comment by ababyduck** [comment]
Finally got around to looking at this again. [The workaround that @arogl posted](https://pypi.org/project/win_unicode_console/) seems to work great! 

Not only did this fix the `UnicodeEncodeError` exception, it enabled colored output in the default command prompt (which I previously had to use MINGW for on Windows.) Perhaps this could be added to FAQ or a separate troubleshooting section of the docs, or as a side note in the installation instructions for users with non-English locales.
