### ISSUE TITLE
Make `none_rec_action` respect `timid`

### ISSUE THREAD

**Issue by RollingStar** [beetbox/beets#3242]
### Problem

https://github.com/beetbox/beets/blob/9abfc45adc5dd864840c9b72f35239c6204d39fa/beets/ui/commands.py#L493

When you have a none_rec and you set the none_rec_action to "asis", beets will import as-is even in timid mode. More predictable behavior would be having timid override the none_rec_action.

**Comment by sampsyo** [comment]
Got it; yes, that does make sense! It does seem like `--timid` should override all "summary judgments."

**Comment by RollingStar** [comment]
https://github.com/beetbox/beets/pull/3357

**Comment by sampsyo** [comment]
Fixed in #3357.
