### ISSUE TITLE
Inconsistency in "original date" tag naming

### ISSUE THREAD

**Issue by ababyduck** [beetbox/beets#3248]
After running a large import I'm noticing that "original date" information is not being saved to one consistently-named tag. For some albums _(e.g. the 2014 remasters of old Bruce Springsteen records,)_ it is saved to `ORIGINALDATE`, while for others _(e.g. the 1992 re-issue of Abbey Road)_ it is saved to `ORIGINAL RELEASE DATE`.

Are these tag names pulled directly from MusicBrainz? If not, why the inconsistency? Is it possible to configure beets to map both of these fields to a single tag, or would this require additional code?

Here's [my current config file](https://gist.github.com/ababyduck/c1465445ef7de336648567d028dacf3e), if relevant.

**Comment by sampsyo** [comment]
Hi! Can you please check whether those files came with those tags *before* beets touched them? The only tag name we use is ORIGINALDATE:
https://github.com/beetbox/beets/blob/master/beets/mediafile.py

**Comment by ababyduck** [comment]
[First track before import](https://i.imgur.com/GeKOOOM.png)
[First track after import](https://i.imgur.com/C7uYAXw.png)

**Comment by sampsyo** [comment]
That's odd! Is there a way we can reproduce this here?

**Comment by ababyduck** [comment]
Short of sending you the actual album files, I'm not sure. Possible that it occurs with any copy of Abbey Road, if you've got access to a copy of it?

I get the same results after deleting the album, removing it from the database (`beet rm`), and re-importing in verbose/timid. [Here's the full output](https://www.hastebin.com/nokiveyine.makefile), although I'm not seeing anything in there that would help track down the issue.

When I have more time, I'll try to hunt down any other albums that received the `ORIGINAL RELEASE DATE` tag and try to identify a pattern, and maybe implement some additional logging to try and figure out when/where that tag is being written.

**Comment by ababyduck** [comment]
Mystery partially solved.

Of 676 albums imported:
- 502 received the `ORIGINAL RELEASE DATE` tag. All are in **MP3** format.
- 170 received the `ORIGINALDATE` tag. All are in **FLAC** format.
- 4 received neither. All are semi-obscure Japanese releases in **AAC** format.

**Comment by sampsyo** [comment]
Sounds like this is an artifact of VLC then: it’s choosing to display the standard ID3 frame “TDOR” using that string.

**Comment by ababyduck** [comment]
Foobar2000 actually, but yeah, that makes more sense. It looks like Mp3tag displays the same field as `ORIGYEAR`. Ah, well. Sorry for the false alarm and thanks for looking.
