### ISSUE TITLE
Item's destination() is incorrect if the import is configured not to move or copy files

### ISSUE THREAD

**Issue by RodrigoLeiteF** [beetbox/beets#3256]
I'm currently writing a plugin to upload files to a Funkwhale instance after importing from beets. However, as I don't plan on having a local library, I disabled the `copy` and `config`. As such, in the `album_imported` event, calling `item.destination()` returns where the items would be imported to, as opposed to their current location.

```
from beets.plugins import BeetsPlugin
import operator
import subprocess

class Funkwhale(BeetsPlugin):
    def __init__(self):
        super(Funkwhale, self).__init__()
        self.files = []
        self.register_listener('after_write', self.imported)
        self.register_listener('cli_exit', self.upload)

    def imported(self, item):
        self.files.append(item.destination())

    def upload(self):
        # If the importer was run as `beet import ~/M.I.A.` with config and move disabled,
        # here `files` wil be `$HOME/Music/M.I.A./etc` instead of `~/M.I.A./etc`
        files = [str(x, "utf-8") for x in self.files]
        proc = operator.add(["funkwhale-cli", "upload", "-l", self.config['library'].get()], files)
        if len(self.files) > 0:
            subprocess.call(proc)
```

### Problem

Running this command in verbose (`-vv`) mode:

```sh
$ beet -vv
user configuration: /home/rodrigo/.config/beets/config.yaml
data directory: /home/rodrigo/.config/beets
plugin paths: 
Sending event: pluginload
library database: /home/rodrigo/.config/beets/library.db
library directory: /home/rodrigo/Music
Sending event: library_opened
```

Led to this problem:

```
(paste here)
```

### Setup

* OS: Linux Antergos
* Python version: 3.7.3
* beets version: 1.4.8
* Turning off plugins made problem go away (yes/no): no

My configuration (output of `beet config`) is:

```yaml
plugins: funkwhale ftintitle

import:
    copy: no
    move: no
    write: yes
ftintitle:
    drop: yes
    format: (feat. {0})
    auto: yes
funkwhale:
    library: Default
```

**Comment by sampsyo** [comment]
Interesting! This sounds like a cool plugin.

It makes sense that's what you need here! The `destination` method is not supposed to predict where something will end up when a particular import session completes. It's a property of the item itself, independent of any particular import session, so it will stay that way.

Instead, since you're hooking into the `after_write` event, you can just use `item.path`, i.e., the item's current location. The item has already been moved/copied at this point, so this is its final resting place.

**Comment by RodrigoLeiteF** [comment]
Makes sense. I'll change it to `item.path` then. Thanks! :)

**Comment by sampsyo** [comment]
Great!
