### ISSUE TITLE
Make mailing list open for non-Googlers

### ISSUE THREAD

**Issue by rnkn** [beetbox/beets#3259]
### Use case

I'm trying to send an email to the mailing list `beets-users@googlegroups.com` but receive the response:

> We're writing to let you know that the group you tried to contact (beets-users) may not exist, or you may not have permission to post messages to the group. A few more details on why you weren't able to post:
>
> * You might have spelled or formatted the group name incorrectly.
> * The owner of the group may have removed this group.
> * You may need to join the group before receiving permission to post.
> * This group may not be open to posting.

### Solution

I believe that Google Groups can be set to allow non-members to participate.

### Alternatives

- https://groups.io/
- https://lists.sr.ht/
- https://www.gnu.org/software/mailman/
- http://librelist.com/

**Comment by arcresu** [comment]
Just in case you're not aware of it, the beets community is more active [on Discourse](https://discourse.beets.io/) rather than Google Groups these days and you're more likely to attract a wider audience for your questions there.

**Comment by rnkn** [comment]
Thanks Carl. I'm just after a regular mailing list though. No account 
signups. No profile pics or internet points. Just good ol' reliable 
email.

**Comment by sampsyo** [comment]
I can't seem to find an option to do that in Google Groups. Sorry! Something like lists.sr.ht would be good too, but we're pretty happy with Discourse right now.

**Comment by rnkn** [comment]
> I can't seem to find an option to do that in Google Groups. Sorry!

For reference, it is under Manage Group > Permissions > Basic 
permissions & Posting permissions.

> but we're pretty happy with Discourse right now.

No worries. The question I was trying to post:

> Is it possible for beets to find files within a given path that are 
> not already in the library?
>
> Thanks. I <3 beets.

**Comment by wisp3rwind** [comment]
> Is it possible for beets to find files within a given path that are not already in the library?

AFAIK, no. A workaround might be something along the lines of `beets ls -f '$path'` and diffing that against `find <librarydir> -type f`

**Comment by rnkn** [comment]
> AFAIK, no. A workaround might be something along the lines of `beets 
> ls -f '$path'` and diffing that against `find <librarydir> -type f`

Genius! That worked, thanks :) Can't believe I didn't think of this...
