### ISSUE TITLE
Add a -f parameter so beet command can use specific config file when executing

### ISSUE THREAD

**Issue by msdos** [beetbox/beets#3263]
### Use case

I use beets on a Linux and a macOS machine and have realized that at least in my case, it would be easier if I had two libraries.

This is discussed in https://github.com/beetbox/beets/issues/221. I do know *it's not an easy task* so I thought about a different approach that, from my POV (I'm not familiar with the code so forgive me if I'm being naive), is easier.

### Solution

If beets provided a parameter, let's say `-f` that you can specify an alternative config file, it would suffice, since all other information about where is the database and such is inside the config file. Example: `beet -f ~/.config/beets/lossless_library.yaml` or `beet -f ~/.config/beets/lossy_library.yaml`

Since you already provide an `include` option, we could have a `~/.config/beets/common.yaml` with all common configuration, with no duplicated info.

Bonus: this parameter would make it easier to experiment and to test other people's configurations.

### Alternatives

The alternative is to create yourself a bunch of scripts with symbolic links that change the link of the `~/.config/beets/config.yaml`. Although feasible, it seems too much _hackish_.

**Comment by sampsyo** [comment]
Hi! We already have this: it's called `--config`. :rocket:

**Comment by msdos** [comment]
> Command-Line Option Alternatively, you can use the --config command-line option to indicate a YAML file containing options that will then be merged with your existing options (from BEETSDIR or the default locations). This is useful if you want to keep your configuration mostly the same but modify a few options as a batch. For example, you might have different strategies for importing files, each with a different set of importer options.

I'm glad you're so kind to be so polite with useless issues like this.
