### ISSUE TITLE
make replaygain multithreaded

### ISSUE THREAD

**Issue by audiomuze** [beetbox/beets#3265]
### Use case

I'm trying to use beets to calculate r128 replaygain.  The current plugin is not multi-threaded so the process takes a lot longer than it needs to.

### Solution
In the past I’ve used r128gain - Fast audio loudness scanner & tagger to undertake r128 replaygain analysis (https://github.com/desbma/r128gain) - it’s multithreaded and performs a LOT faster than the existing plugin. Given it’s also coded in Python, LGPL-2.1 and “can also be used as a Python module from other Python projects to scan and/or tag audio files” I was wondering whether it’d be worthwhile considering it as a replacement or alternative to the existing replaygain plugin?

**Comment by sampsyo** [comment]
Please see #2224 for an existing feature request about analyzing in parallel. We also have #3056 open, which is basically ready to go and uses ffmpeg directly—the r128gain Python module is a wrapper around ffmpeg too.
