### ISSUE TITLE
How exactly the ordering logic for candidates works when you have multiple candidates that are 99,9% match?

### ISSUE THREAD

**Issue by msdos** [beetbox/beets#3266]
Using beets 1.4.7.

I have an album, named `Riverside - Second Life Syndrome`. The album is a `CD` release, the files have tags and the year is `2005`. When I try to import in beets and get the matches in musicbrainz:

```
1. Riverside - Second Life Syndrome (99.9%) (tracks) (2x12" Vinyl, 2011, DE, InsideOut Music)
2. Riverside - Second Life Syndrome (99.9%) (tracks) (CD, 2005, PL, Mystic Production)
3. Riverside - Second Life Syndrome (99.9%) (tracks) (CD, 2005, XE, InsideOut Music)
4. Riverside - Second Life Syndrome (99.9%) (tracks) (CD, 2009, DE, InsideOut Music)
```

As you can see, it wrongly chooses the Vinyl release as the first option. I can "force" the engine to prefer CD releases. Adding to config:

```yaml
match:
    preferred:
        media: ['CD']
```

I get *exactly* what I was looking for:

```
1. Riverside - Second Life Syndrome (99.7%) (tracks) (CD, 2005, PL, Mystic Production)
2. Riverside - Second Life Syndrome (99.7%) (tracks) (CD, 2005, XE, InsideOut Music)
3. Riverside - Second Life Syndrome (99.7%) (tracks) (CD, 2009, DE, InsideOut Music)
4. Riverside - Second Life Syndrome (95.9%) (media, tracks) (2x12" Vinyl, 2011, DE, InsideOut Music)
```

Fact is: shouldn't beets have chosen the CD release instead of the 2011 Vinyl, since the `year` in the tags are 2005 and we have candidates with this year as well, with the same 99,99% ratio? 

Is there a configuration to take the `year` of the tag into account that I'm unaware of? Or is this really a bug?

**Comment by sampsyo** [comment]
Hello! The matching system does indeed use the release year. It's generally really hard to tell from a single example what caused a match to be scored exactly how it was—there are so many factors, coming from all manner of different metadata sources, that it's hard to "blame" any particular factor. For example, there's a chance beets wasn't able to deduce a "consensus" release date for your current music files.

If you're interested, I encourage you to dig into the matching logic in `beets.autotag.match` to see if you can sort out whether the "year" penalty triggered for the non-CD matches that were proposed.

**Comment by RollingStar** [comment]
You can edit `distance_weights` in your config, but I don't know if it does anything.

https://github.com/beetbox/beets/blob/def5ff0e24aa0289f30e378a0f17dca094571c75/beets/config_default.yaml#L114

https://github.com/beetbox/beets/blob/6d020e3d2ba675b1e4a21e8c1b753ec88134ca4f/beets/autotag/hooks.py
