### ISSUE TITLE
Plugin to allow cusomization of the albumartist field

### ISSUE THREAD

**Issue by tehniemer** [beetbox/beets#3268]
There is a plugin called [AlbumArtist Extension](https://picard.musicbrainz.org/plugins/) for musicbrainz picard that allows different formats for the ```albumartist``` field. In particular ```_aaeStdPrimaryAlbumArtist``` or ```_aaeCredPrimaryAlbumArtist``` so the first (primary) album artist would only be used instead of all credited artists. It would be very useful to avoid having a folder structure like this:

![Image 1558005638](https://user-images.githubusercontent.com/11021632/57850121-c4b34100-77a2-11e9-8bfe-e61240df7b95.png)

Ideally they would all fall under ```Xavier Rudd```

**Comment by sampsyo** [comment]
Hi! That's an interesting link—I think this is more or less the same idea as #3176; would you mind adding your thoughts there?

**Comment by tehniemer** [comment]
@sampsyo sure thing.
