### ISSUE TITLE
Unknown files in music directory

### ISSUE THREAD

**Issue by mbrandis** [beetbox/beets#3280]
### Problem

This is more a question than a bug report. Maybe it is a feature request. ;-)

I searched for music via `beet ls` and couldn't find the items, but was sure that they are in the music directory. I found them via `find` and re-imported them. I'm pretty sure that I imported them before. Maybe I moved them in the music directory by hand. 

Is it possible to find the files in the configured music directory which are not in the database?

### Setup

* OS: Debian Stable
* Python version: 3.5.3
* beets version: 1.4.8

**Comment by sampsyo** [comment]
We don't really have a way to do that. You might try doing a `beet ls -p` to get all the paths of everything in the database, and using something like `find .` to list all the files in the directory. Then something like [comm](https://linux.die.net/man/1/comm) could show you the differences.

**Comment by mbrandis** [comment]
Something like this works pretty well:

`beet ls -p -a | perl -pe 's@.+/@@g' | sort`
`find <MUSICPATH> -mindepth 2 -type d | perl -pe 's@.+/@@g' | sort`

I use <GENRE/ALBUM - ARTIST> for path separation. Summary, there is some cleaning up to be done in my music collection... ;-)
