### ISSUE TITLE
New option for move to make links

### ISSUE THREAD

**Issue by dosoe** [beetbox/beets#3281]
### Use case

Now that the parentworks plugin is almost complete, I have to decide on a library setup: 
do I want to sort my recordings by release or by work? 
Maybe I can do both: have one filesystem that contains the first setup and the files, and another one that contains the second setup and links to the actual files in the first filesystem. 

### Solution
Could there be a supplementary option ```--link``` for ```move``` that would not move the files but just create links to where the files currently are, and that would have its own ```paths```?

There would be further complications if for example after another ```move``` command the links have to be updated. If we want the links to follow the files, we would need the library to keep track of the links as well as the files and update them each time the corresponding file gets moved. That would be awesome, but I would be content of a system where I would just recreate the links each time I move stuff around. 

I could do this by myself, but that would require that I understand how beets handles files and how the different move commands, functions and methods work and interact. 

### Alternatives
I haven't heard of any.

**Comment by sampsyo** [comment]
Hi! That sounds like what beets-alternatives does with its "symlink views" capability:
https://github.com/geigerzaehler/beets-alternatives#symlink-views

Or perhaps a little bit like #153. Maybe take a look at those?

**Comment by dosoe** [comment]
ok thanks, I'm checking it out.
