### ISSUE TITLE
Better import-time duplication checks

### ISSUE THREAD

**Issue by djl** [beetbox/beets#3310]
The current import-time duplication check is a little naive. Any albums the same name and album artist are treated as duplicates. This leads to "The Weezer Problem":

```
~% beet import .

Weezer [Green Album] (10 items)
Tagging:
    Weezer - Weezer
URL:
    https://musicbrainz.org/release/a9897d0b-b05a-41d9-baa5-68a754e917c3
(Similarity: 98.6%) (country) (CD, 2001, CA, Geffen Records, 0694930452, Green Album)
[A]pply, More candidates, Skip, Use as-is, as Tracks, Group albums,
Enter search, enter Id, aBort, Copy tracks, Print tracks, Open URL? a
This album is already in the library!
Old: 10 items, FLAC, 1020kbps, 37:43, 276.2 MiB
Old: 10 items, FLAC, 995kbps, 36:23, 260.3 MiB
Old: 10 items, FLAC, 975kbps, 41:18, 284.2 MiB
Old: 10 items, FLAC, 932kbps, 41:53, 274.2 MiB
Old: 10 items, FLAC, 1034kbps, 28:34, 211.6 MiB
New: 10 items, FLAC, 1034kbps, 28:34, 211.6 MiB
[S]kip new, Keep both, Remove old, Merge all?
```

Clearly, this is less than ideal.

This particular example could be solved by also checking for duplicate `mb_releasegroupid` fields but I'm not sure if that would also work with other tagging backends like Discogs.

If I'm wrong and that *does* work for all taggers, then great! Otherwise, it might make more sense to allow users to specify what fields should be used for dupe checking.

Perhaps someone can come up with a simpler or more robust solution?

**Comment by sampsyo** [comment]
Hi! We've discussed this in #1133, and it's a tricky issue—we have a proposal there for how to proceed. Maybe take a look and see if that plan makes sense to you?
