### ISSUE TITLE
Extend replace configuration to support 'strange' dash characters

### ISSUE THREAD

**Issue by fortysixandtwoahead** [beetbox/beets#3313]
### Use case
Some people on MusicBrainz started using a character which looks like a dash ( - ), but it is actually something else. They might have some reason to do that but this leads to the situation that directories created by beets for artists or albums, which contain such a character are hard to type on the command line, as it's not possible to enter this dash-like character out of the box.

I am aware of the replace-configuration and I'm wondering if the default configuration could support replacing those dash-like things out of the box for convenience?

An example for what I'm talking about is this:
https://beta.musicbrainz.org/release/25be2217-f411-4858-b936-1acd649fd152
(The Song Diaries by Sophie Ellis-Baxtor)

Now do the following: open the webpage, press Ctrl-A to select all and copy the content into your favourite text editor. In the text editor open the search dialog and enter the dash character ( - ) with your keyboard. You won't find the string in 'Ellis-Baxtor' because this other character has been used.

Another example is https://beta.musicbrainz.org/release/e82d7965-6eb8-4d6f-882f-392be09b02e4

**Comment by jackwilsdon** [comment]
Are you looking to have these replaced in filenames or in metadata? It looks like that hyphen is a [U+2010 HYPHEN](https://www.fileformat.info/info/unicode/char/2010/index.htm), whereas the normal keyboard hyphen is [U+002D HYPHEN-MINUS](https://www.fileformat.info/info/unicode/char/002D/index.htm).

**Comment by fortysixandtwoahead** [comment]
Yes, they should be replaced in file names as it's hard to type the U+2010 when you are on the keyboard/command line. I don't care about the meta data.

**Comment by sampsyo** [comment]
Hi! This should be something you can do already—just like any other pair of characters, you can set up the replace configuration to replace `–` with `-`. Have you given that a try? (And if so, is this issue about making it the _default_ for everyone?)

**Comment by jackwilsdon** [comment]
I read this issue as making it a default for everyone @sampsyo.

**Comment by sampsyo** [comment]
Cool. FWIW, I'm (mildly) opposed to such a change—I like having typographically correct filenames, and philosophically, I'd like to avoid being dragged down forever by the tyranny of ASCII. :smiley: It's not too hard for folks to add this to their config if they want it.

**Comment by jackwilsdon** [comment]
I think the `asciify_paths` option probably covers this use-case well personally (but that's just my opinion).

**Comment by fortysixandtwoahead** [comment]
Yes, I opened the issue to have this as a convenient default - as I think that a dash is such a common character. I wouldn't have opened the issue for other chars. However, it was just an idea - so I guess we can close the issue.

**Comment by sampsyo** [comment]
Cool; thanks for clarifying! Indeed; I think we'll leave the defaults how they are, but thank you for bringing up the idea!!
