### ISSUE TITLE
fallback directory if don't match

### ISSUE THREAD

**Issue by jee-r** [beetbox/beets#3327]
Hello,
and first of all a BIG THANK YOU for this amazing tool that i use for may be 3 years now.

### Use case
I have a full automation set up to import music on my Nas.
Directories tree :
```
|-- Incomming_music/
|-- Media/
    `-- Music/
```
My workflow is the following [inotify-wait](https://linux.die.net/man/1/inotifywait) watch `Incomming_music` directory for new directory if it's happens he call beets to import it in `/Media/Music/`.

All work great but the "issue" is if an album don't match we have actually two choices for the `quiet_fallback` option `asis` or `skip`. It is sometimes complicated to find which albums have been skipped or imported "asis", especially because the logs are not very verbose.

### Solution

What I propose is to add a third option which consists of copy `asis` in a fallback directory if the imported album don't match eg. `/Media/Music/Unsure` or whatever  you call this directory.
This directory can be easily reviewed and re-import manually later. 

### Alternatives
Alternatively it cant be interesting to make import's log more verbose. 
I don't find any plugins who can do something like this.

**Comment by sampsyo** [comment]
Interesting idea! I think the natural way to do this would be to use a query-qualified path format. If you haven't seen these before, they let you determine your path format based on attributes of the music. You could check whether the music has an MBID attached or, even better, use the $data_source field, which contains `MusicBrainz` or `Discogs` or whatever, indicating how the music was matched. If this field is empty, you can file the music under your `.../Unsure` directory.

**Comment by jee-r** [comment]
@[GitHub](github.com)

Thank’s for your answer and sorry for my late reply. It’s look like a little bit tricky for me, do you have some example how to do that please ?

After reading this issue [https://github.com/beetbox/beets/issues/3444](https://github.com/beetbox/beets/issues/3444) i’d be more comfortable with an “real” <code>exit code</code> when beets failed to import music <code>skip</code>.

My watch script look like this he run in background in a docker container on my Nas :


    <code>#!/bin/bash

    beets_dir="/config/beets"
    beets_config="/config/config.yaml"
    WATCH_DIR="/Incoming/Music"

    BEETSDIR=/config
    export BEETSDIR
    FPCALC=/usr/bin/fpcalc
    export FPCALC

    inotifywait -m -e create,moved_to --format '%w%f' "$WATCH_DIR" | while IFS= read -r dir_path; do
        /usr/local/bin/beet -c "$beets_config" import -q -i --flat "$dir_path"
    done
    </code>

I might add a condition in the loop after Beets’s job like this (not tested):


    <code>#set my variable from beets's exit code
    beets_exit_code="$?"

    if [ ! "$beets_exit_code = 0 ]
    then
       cp -rf "$dir_path" /my/fallback_dir/
      echo "[$date] Not imported  $dir_path" &gt;&gt; $log_file
    fi
    </code>

Another solution i said previously, can be to add a third option <code>custom_script</code> alongside <code>asis</code> or <code>skip</code> for the <code>quiet_fallback</code> “mode” who run script instead of implement code that i would be may be the only one who use it.

#beets #fallback #exit #code #automation #music #import

(Originally published at: https://jeer.fr/micro/1580319995)
