### ISSUE TITLE
Add iTunes media type frame

### ISSUE THREAD

**Issue by ozelot379** [beetbox/beets#3333]
### Use case

I'm trying to use beets to manage different media types (Music, audio books, podcats, music videos, ...)

It would be great that beets would support this media field, so I can restrict for instance some media types with the smartplaylist beets plugin

### Solution
I think iTunes uses a composition with the mp4 `stik` frame and file extension (Like m4b, m4r), and for podcast media type the frame is `PCST`, but it's very complex to cover all possible cases and values

### Alternatives
There exists already a media field called `media` (https://github.com/beetbox/mediafile/blob/f62224fea854524fb86e7dcd211dfb4f70e183ff/mediafile.py#L1825) in beets, but I think, this is somewhat different and is not what I need

I wrote a plugin https://github.com/ozelot379/beets-plugins/blob/master/media_type.py for me

**Comment by sampsyo** [comment]
Interesting! Can you link to any writing or code somewhere that does this correctly? Before we make a plan for a new feature around this, we'll need to know exactly what we're supposed to implement.

**Comment by ozelot379** [comment]
mutagen seems it can already parse `stik` (but without integer mapping) and `pcst` frames

More infos
- https://github.com/sergiomb2/libmp4v2/wiki/iTunesMetadata#media-type-stik
- https://help.mp3tag.de/main_tags.html
- https://github.com/quodlibet/mutagen/search?q=stik&unscoped_q=stik
- https://github.com/quodlibet/mutagen/search?q=pcst&unscoped_q=pcst

**Comment by sampsyo** [comment]
OK, thanks for kicking this off! The main body of work here, I think, will be figuring out how to represent a single enumerated flag like this across multiple formats.

**Comment by ozelot379** [comment]
I wrote a beets plugin for me, which add the media_type field to beets

https://github.com/ozelot379/beets-plugins/blob/master/media_type.py

Feel free to take it in to beets
