### ISSUE TITLE
lyrics: add tekstowo.pl as a source

### ISSUE THREAD

**Issue by octos** [beetbox/beets#3344]
### Use case

It would be nice if beets could fetch lyrics from https://www.tekstowo.pl/ – especially for more obscure Polish releases.

### Solution

https://github.com/hryniuk/tekstowo is pretty simple and works perfectly. We could integrate it into the Lyrics plugin.

**Comment by sampsyo** [comment]
Sounds like a reasonable request! And it looks like the screen-scraping required is pretty light.

**Comment by wisp3rwind** [comment]
Closed by https://github.com/beetbox/beets/pull/3519
