### ISSUE TITLE
discogs: add 'Featuring' artists to the 'artist' field

### ISSUE THREAD

**Issue by kergoth** [beetbox/beets#3353]
### Use case

Currently the Discogs importer throws away info about 'featuring' artists, as this is in the `credits` / `extraartists`, not `artists`, along with other roles like `Producer`. This is quite different from the behavior of the musicbrainz importer due to how MusicBrainz stores this information. I'd expect the artist to match up when importing the same album from two different importers, other than cosmetic differences due to differing database guidelines.

### Solution

For feature/behavior parity with the default MusicBrainz importer, I think we should append these to the artist field, i.e. ` feat. SomeArtist, AnotherArtist`.

**Comment by kergoth** [comment]
Ex. this track from [The Amazon Groove](https://www.discogs.com/the-amazon-groove/release/2088224), via the [API](https://api.discogs.com/releases/2088224):
```json
        {
            "artists": [
                {
                    "anv": "",
                    "id": 576190,
                    "join": ",",
                    "name": "Matty G",
                    "resource_url": "https://api.discogs.com/artists/576190",
                    "role": "",
                    "tracks": ""
                },
                {
                    "anv": "DJ Rupture",
                    "id": 63742,
                    "join": ",",
                    "name": "DJ /rupture",
                    "resource_url": "https://api.discogs.com/artists/63742",
                    "role": "",
                    "tracks": ""
                },
                {
                    "anv": "",
                    "id": 26561,
                    "resource_url": "https://api.discogs.com/artists/576190",
                    "role": "",
                    "tracks": ""
                },
                {
                    "anv": "DJ Rupture",
                    "id": 63742,
                    "join": ",",
                    "name": "DJ /rupture",
                    "resource_url": "https://api.discogs.com/artists/63742",
                    "role": "",
                    "tracks": ""
                },
                {
                    "anv": "",
                    "id": 26561,
                    "join": "",
                    "name": "Lloop",
                    "resource_url": "https://api.discogs.com/artists/26561",
                    "role": "",
                    "tracks": ""
                }
            ],
            "duration": "3:39",
            "extraartists": [
                {
                    "anv": "",
                    "id": 1685603,
                    "join": "",
                    "name": "Autumn Rain",
                    "resource_url": "https://api.discogs.com/artists/1685603",
                    "role": "Featuring",
                    "tracks": ""
                },
                {
                    "anv": "",
                    "id": 103499,
                    "join": "",
                    "name": "Elizabeth Alexander",
                    "resource_url": "https://api.discogs.com/artists/103499",
                    "role": "Featuring",
                    "tracks": ""
                }
            ],
            "position": "22",
            "title": "Layin In Bed",
            "type_": "track"
        },
```

For comparison, we can examine the [MusicBrainz Release](https://musicbrainz.org/release/a32deed2-088c-41e4-a23d-72d9af74dac4), but their info on this album is even worse, including the featuring artists in the track titles (already a nono, though better than leaving them out entirely) and record label of the track. Presumably this is how they were listed on the album, but it doesn't align with MusicBrainz guidelines afaict.

**Comment by kergoth** [comment]
https://github.com/beetbox/beets/compare/master...kergoth:prototype-discogs-featuring is an ugly first prototype of the sort of thing I'm looking for.

**Comment by sampsyo** [comment]
Sounds good! Something like this seems like the right thing to do.

**Comment by kergoth** [comment]
Thanks for the quick feedback. I'll see about cleaning up what I have and submitting a pull req.

**Comment by sanpoChew** [comment]
@kergoth just curious on the status of this fix? find this very annoying personally

**Comment by JOJ0** [comment]
This feature was implemented in https://github.com/beetbox/beets/pull/4515

 FYI @sanpoChew @kergoth
