### ISSUE TITLE
config: show path in stderr

### ISSUE THREAD

**Issue by RollingStar** [beetbox/beets#3356]
### Use case

`beet config` shows the config file. On a fresh install, it's nothing. `-v` (global option) or `-p` / `--paths` show the path the config is loaded from.

I can't think of a situation where I wouldn't want the path shown.

### Solution

Always print the path loaded by the config when running `beet config`. Remove `--paths` and optionally create a `--quiet -q` to replicate the old behavior.

### Alternatives

- Keep as-is
- only print path on empty config

**Comment by sampsyo** [comment]
Cool, I see the point. One nice thing about the current behavior (as confusing as it may be on first run) is that the command only ever outputs YAML in its default setting. That is, as with any proper Unix command, you could do `beet config > foo.yaml` and get a well-formed file. Printing out the path every time would violate this expectation, in the same way that having `beet ls` print out a message when there are no matches would violate standard Unixy expectations.

However, we could print something to stderr every time, which would certainly be less confusing.

**Comment by RollingStar** [comment]
yes

**Comment by jtpavlock** [comment]
I'm gonna have to disagree with this proposal and say I prefer the way it is now due to reasons @sampsyo mentioned as it conforms to expectations.

**Comment by RollingStar** [comment]
The proposal is bad, but sampsyo's alternative is good. Would stderr path output break anything?

**Comment by jtpavlock** [comment]
That seems like an anti-pattern to me. Could you just alias `beet config` to `beet config -p && beet config` for your use?
