### ISSUE TITLE
On some Linux systems, Beets default locale of utf-8 disagrees with subprocess

### ISSUE THREAD

**Issue by afontenot** [beetbox/beets#3358]
### Summary

First a description that should help to understand the problem, then I'll fill out the issue template.

Beets attempts to encode with the system default encoding when crafting strings for external programs, [for example here](https://github.com/beetbox/beets/blob/master/beetsplug/convert.py#L229). It does this with [`util.arg_encoding()`](https://github.com/beetbox/beets/blob/master/beets/util/__init__.py#L328):

    def arg_encoding():
        try:
            return locale.getdefaultlocale()[1] or 'utf-8'
        except ValueError:
            return 'utf-8'

On this Ubuntu install which didn't configure a locale, `locale.getdefaultlocale()[1]` is `None`. So Beets intelligently defaults to utf-8. However, it then passes that string to `subprocess`, which isn't so intelligent. It calls [Python's `fork_exec`](https://github.com/python/cpython/blob/3.6/Modules/_posixsubprocess.c#L557), which calls [`PyUnicode_FSConverter`](https://docs.python.org/3/c-api/unicode.html#c.PyUnicode_FSConverter) on each argument. When this attempts to encode the arguments, [according to the documentation](https://docs.python.org/3/c-api/unicode.html#c.PyUnicode_EncodeFSDefault), 

> If Py_FileSystemDefaultEncoding is not set, fall back to the locale encoding.

So what is the locale encoding? We can get it with `locale.getpreferredencoding()`. Unfortunately, the [documentation](https://docs.python.org/3/library/locale.html#locale.getpreferredencoding) doesn't say what the default encoding is, but we can check [the code](https://github.com/python/cpython/blob/3.6/Lib/locale.py#L610):

                res = getdefaultlocale()[1]
                if res is None:
                    # LANG not set, default conservatively to ASCII
                    res = 'ascii'
                return res

(Mournfully) "oh..."

### Problem

On a Linux with no locale set (e.g. minimal Ubuntu install), add a track with a non-ASCII filename to your database, then do 

    beet convert -d outdir

Result:

    UnicodeEncodeError: 'ascii' codec can't encode character '\u2019' in position 23: ordinal not in range(128)

The issue is [fixed](https://askubuntu.com/a/227513) with `locale-gen` and `dpkg-reconfigure locales`, followed by logging out and in again. 

Expected result: I'm actually not sure. Possible solutions:

1. Check if `locale.getpreferredencoding()` is an ASCII, and if so, coerce the filename to ASCII before passing it to `subprocess`. 
2. On commands that will involve `subprocess`, check if locale is undefined and error out early with an intelligent message for the user. 
3. Maybe there's someway to force `subprocess` to use UTF-8? I don't know of one, and I'm not sure if this might have some side effects. 

### Setup

* OS: Ubuntu 18.04.1 LTS
* Python version: 3.6.8
* beets version: 1.4.6-2
* Turning off plugins made problem go away (yes/no): n/a

My configuration (output of `beet config`) is: n/a

**Comment by sampsyo** [comment]
Hi, and thanks for the detailed writeup!

I think the right solution (on Unix, at least) will need to avoid Unicode altogether for the command arguments and make sure that we always pass raw bytes. We can choose whatever method we want to generate filenames that match the desired encoding, but that should be under our control. Namely, the way to invoke commands with filenames as arguments is not to take text strings and encode them with the argument encoding (although that is what the Python standard library wants to do 😞)—it is to take the _literal bytes for the filename_ and pass those as the argument bytes. Unix is a bytes-based API and thus it shall always be, AFAICT.

We actually do this in most places in beets! But apparently not here. Could you please include the full traceback so we can see where in the plugin the offending command invocation is coming from?

**Comment by afontenot** [comment]
Sure, although it's exactly where you'd expect it to be given the problem (it's on the line where the arg gets passed to subprocess). 

```
Traceback (most recent call last):
  File "/usr/bin/beet", line 11, in <module>
    load_entry_point('beets==1.4.6', 'console_scripts', 'beet')()
  File "/usr/share/beets/beets/ui/__init__.py", line 1256, in main
    _raw_main(args)
  File "/usr/share/beets/beets/ui/__init__.py", line 1243, in _raw_main
    subcommand.func(lib, suboptions, subargs)
  File "/usr/share/beets/beetsplug/convert.py", line 453, in convert_func
    pipe.run_parallel()
  File "/usr/share/beets/beets/util/pipeline.py", line 445, in run_parallel
    six.reraise(exc_info[0], exc_info[1], exc_info[2])
  File "/usr/lib/python3/dist-packages/six.py", line 693, in reraise
    raise value
  File "/usr/share/beets/beets/util/pipeline.py", line 358, in run
    self.coro.send(msg)
  File "/usr/share/beets/beetsplug/convert.py", line 302, in convert_item
    self.encode(command, original, converted, pretend)
  File "/usr/share/beets/beetsplug/convert.py", line 229, in encode
    util.command_output(encode_cmd)
  File "/usr/share/beets/beets/util/__init__.py", line 821, in command_output
    shell=shell
  File "/usr/lib/python3.6/subprocess.py", line 729, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.6/subprocess.py", line 1295, in _execute_child
    restore_signals, start_new_session, preexec_fn)
UnicodeEncodeError: 'ascii' codec can't encode character '\u2019' in position 23: ordinal not in range(128)
```

**Comment by sampsyo** [comment]
Hmm, that's odd. If you look at the surrounding context to the `util.command_output` line in `convert.py`, we're already encoding those arguments (on Python 3, at least). So I don't immediately see how this could be triggering an encoding error.

This deserves a little more investigation into why `encode_cmd` there contains `str` objects, when it should only contain `bytes` objects.

**Comment by afontenot** [comment]
I was under the (perhaps mistaken) impression that no matter what you sent to `subprocess`, whether `str` or `bytes`, it would get encoded / reencoded to the locale that Python detects when it starts up. So I thought Beets was successfully encoding to bytes, but subprocess was trying to convert that to ASCII anyway. Did I miss something?

If you like I can add a debugging line to `convert.py` to print the type of the arguments right before the call to `subprocess`.

**Comment by sampsyo** [comment]
Huh—I was under the impression that, if you passed bytes, at least on Unix OSes, those bytes would go directly to the operating system without being converted at all. (Or at least, I think that's how Python *should* work…) But I'd be interested to be proven wrong.

**Comment by afontenot** [comment]
Looks to me like it's passing bytes.

```
convert: Encoding /mnt/data/music/AJJ/Cant Maintain/01 - Heartilation.flac
DEBUG: b'ffmpeg' <class 'bytes'>
DEBUG: b'-i' <class 'bytes'>
DEBUG: b'/mnt/data/music/AJJ/Can\xe2\x80\x99t Maintain/01 - Heartilation.flac' <class 'bytes'>
DEBUG: b'-acodec' <class 'bytes'>
DEBUG: b'libopus' <class 'bytes'>
DEBUG: b'-ab' <class 'bytes'>
DEBUG: b'96k' <class 'bytes'>
DEBUG: b'/mnt/data/opus/AJJ/Cant Maintain/01 - Heartilation.opus' <class 'bytes'>
Traceback (most recent call last):
  File "/usr/bin/beet", line 11, in <module>
    load_entry_point('beets==1.4.6', 'console_scripts', 'beet')()
  File "/usr/share/beets/beets/ui/__init__.py", line 1256, in main
    _raw_main(args)
  File "/usr/share/beets/beets/ui/__init__.py", line 1243, in _raw_main
    subcommand.func(lib, suboptions, subargs)
  File "/usr/share/beets/beetsplug/convert.py", line 455, in convert_func
    pipe.run_parallel()
  File "/usr/share/beets/beets/util/pipeline.py", line 445, in run_parallel
    six.reraise(exc_info[0], exc_info[1], exc_info[2])
  File "/usr/lib/python3/dist-packages/six.py", line 693, in reraise
    raise value
  File "/usr/share/beets/beets/util/pipeline.py", line 358, in run
    self.coro.send(msg)
  File "/usr/share/beets/beetsplug/convert.py", line 304, in convert_item
    self.encode(command, original, converted, pretend)
  File "/usr/share/beets/beetsplug/convert.py", line 231, in encode
    util.command_output(encode_cmd)
  File "/usr/share/beets/beets/util/__init__.py", line 821, in command_output
    shell=shell
  File "/usr/lib/python3.6/subprocess.py", line 729, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.6/subprocess.py", line 1295, in _execute_child
    restore_signals, start_new_session, preexec_fn)
UnicodeEncodeError: 'ascii' codec can't encode character '\u2019' in position 23: ordinal not in range(128)
```

**Comment by afontenot** [comment]
Oh, right, I remember now. `convert.py` calls `util.command_output`. That calls [`convert_command_args`](https://github.com/beetbox/beets/blob/master/beets/util/__init__.py#L791) which converts everything back into strings. 

                    arg = arg.decode(arg_encoding(), 'surrogateescape')

**Comment by sampsyo** [comment]
Huh. I don't recall exactly why we're decoding there, but I suspect it likely has to do with Windows, where Python really wants Unicode.

The thing is that, for more Python OS interfaces, it _should_ encode strings with `surrogateescape`, which is why we're using that. I'm also somewhat surprised that our `arg_encoding()` turns out to be `utf-8` whereas, when Python gets around to encoding the same strings, it tries to use `ascii`.

**Comment by afontenot** [comment]
Yeah, it's kind of odd that you're using `locale.getdefaultlocale()[1]` to get the encoding instead of `locale.getpreferredencoding()` which falls back to Python's default instead of `None`. Also notice that the way you're encoding here is going to crash anyway if an environment happens to have a latin-1 encoding. 

Is there some way to make passing utf-8 encoded arguments to `subprocess` work in all Python 3 environments? Seems to me like this is the only possible approach, since 

1. we have to pass bytes, because strings are going to get encoded to ascii by Python on systems with no locale set, and
2. if we encode with non-utf8 (e.g. system preferred), we crash on systems with unusual locales. If we did something fancy, (like the `replace` error handler for `.encode()`), ffmpeg wouldn't be able to find the files any more.
