### ISSUE TITLE
The letter after a slash (/) isn't affected by functions

### ISSUE THREAD

**Issue by TheFrenchGhosty** [beetbox/beets#3362]
### Problem

When using %title at the beginning of the path, it will not be applied to the letter after a slash (/) (but will still be applied to everything else

IE: With this path: ``default: Music/%asciify{%title{$albumartist/$albumartist - $albumtype - $original_year - $album/$track - $artist - $album - $title}}``

The path will be: ``Music/Red Hot Chili Peppers/red Hot Chili Peppers - Album - 1984 - The Red Hot Chili Peppers``

Instead of: ``Music/Red Hot Chili Peppers/Red Hot Chili Peppers - Album - 1984 - The Red Hot Chili Peppers``

I'm not sure but it might also break every other functions.

### Setup

* OS: ArchLinux
* Python version: 3.7.4
* beets version: 1.4.9
* Turning off plugins made problem go away (yes/no): N/A

**Comment by sampsyo** [comment]
Hi! Please see #3298.
