### ISSUE TITLE
Mod file support

### ISSUE THREAD

**Issue by Dalzot** [beetbox/beets#3369]
### Use case

I would like to use beets to also manage my mod file (chiptunes) collection. Notice that beet currently doesn't support mod files (mo3, mod, it, xm, s3m.)

### Solution
Might have to use an external library like BASS or implement it into a separate plugin.

**Comment by sampsyo** [comment]
Hi! Interesting proposal. Do you know what kind of metadata these files use? Beets will want to store tags on the files. As a prerequisite, [Mutagen](https://mutagen.readthedocs.io/en/latest/) will need to support whatever metadata format is standard for these files.

**Comment by Dalzot** [comment]
I'm actually not 100% sure on what type they use. I'll have to do some digging around and see what I have on them.
