### ISSUE TITLE
Plugin development: How to see what updates were made in a database update?

### ISSUE THREAD

**Issue by doronbehar** [beetbox/beets#3379]
Hey,

I wrote a plugin that saves in a certain file the history of all my imports. Is it possible to make the plugin update the imports history file whenever certain changes were made to the database? I need to see the differences which were made to the database (a sort of diff) in order for that to be possible. I thought of `self.register_listener` a function to the `database_change` event but I'm if I'll be able to get a diff like that.

**Comment by sampsyo** [comment]
Hi! Good question. You're right that `database_change` might not quite do it—you get that after an object is added to, removed from, or changed in the library.

Since you're interested in imports, I think a higher-level strategy might work: use an event that specifically targets the import pipeline. In particular, `import_task_apply` and `import_task_choice` will let you observe the newly imported music and what the user has chosen to do with them.

**Comment by doronbehar** [comment]
Thanks for responding so quickly! I've already had that import event covered up using the `import_stages`. Do you think an event would have suited better? TBH, I was thinking of using the event `album_imported` but I couldn't get the original path(s) the album was imported from so it didn't help me much, nor did any other events.

I would like to discuss the API in regard to helping a plugin see exactly what changes were made to the library. Do you think there's a way to do it with the current API?

**Comment by sampsyo** [comment]
Yeah, adding an import stage might be good too. It's true that `album_imported` only sees the *post facto* state of the database.

> I would like to discuss the API in regard to helping a plugin see exactly what changes were made to the library. Do you think there's a way to do it with the current API?

With this idea, are you asking about *any* changes or just those performed by the importer? It might help to know a little more about what your use case is—what do you plan on using these changes for?

**Comment by doronbehar** [comment]
Basically, what my plugin does, is maintaining a dumb simple sqlite table with the following columns: MusicBrainz album ID & original path from which the album was imported from.

The idea, is to record this information so that in case of a catastrophic data loss of all music, it'll be a little bit easier to reimport everything from it's original source and know exactly what path provided what album.

> With this idea, are you asking about _any_ changes or just those performed by the importer?

Any changes. I'll explain:

What if the `mb_albumid` tag changes in an `update`? To solve that, the plugin needs to know about every change to the database and check if it includes a change to a `mb_albumid` tag. And, if so, update the plugin's table.

**Comment by sampsyo** [comment]
Got it! I have a random idea that you might like and that might simplify this a little bit: make a plugin that adds an `original_path` field to the _beets_ database. That way, you'll automatically get the path associated with the MBID (and all other metadata), and if anything ever changes, it will "automatically" be up to date. If you want, you could periodically dump a CSV or something that just contains the MBID and the `original_path` field.

I suggest this because it seems somewhat complex to let plugins view every change that we ever make to the database—and it could even be a performance problem to intervene on every modification. So perhaps using the data where it already exists would be just as good.

**Comment by doronbehar** [comment]
Yea I thought about it but I wasn't sure exactly how to do it.. Would you have used an event or an `import_stage` for that? Besides that, can I just send arbitrary SQL commands to the database? Is there a known plugin that maintains a separate column in the database + adds a query syntax that I can learn from?

**Comment by sampsyo** [comment]
Try the `import_task_apply` event. That's where metadata gets updated for a given album or item, but it happens before any files are moved/copied, so the task's paths should still reflect the original location.

> Besides that, can I just send arbitrary SQL commands to the database? Is there a known plugin that maintains a separate column in the database + adds a query syntax that I can learn from?

You can use a flexible attribute! :tada: Your code can work similar to the `beet modify` command, in that it can add arbitrary attributes to any album or item. No need for direct access to SQL. For example, the command `beet modify -a some_album foo=bar` command is roughly equivalent to doing `some_album.foo = 'bar'` in Python.

Most current plugins do something like this. For example, the lyrics plugin does this to assign to the `lyrics` field.

**Comment by doronbehar** [comment]
> You can use a flexible attribute! tada Your code can work similar to the beet modify command, in that it can add arbitrary attributes to any album or item. No need for direct access to SQL. For example, the command beet modify -a some_album foo=bar command is roughly equivalent to doing some_album.foo = 'bar' in Python.

Boy that's excellent! It's so much easier now.. Thanks a lot! :smile:.

> Try the import_task_apply event. That's where metadata gets updated for a given album or item, but it happens before any files are moved/copied, so the task's paths should still reflect the original location.

Just out of curiosity, why do you recommend the `import_task_apply` over adding an import stage for my use case?

I have 1 more question please: I'd like to use to use the `item_removed` event in order to suggest the user (using `input_options`) to delete the item's source file / source directory (using `os.path.dirname`). I noticed that the function registered for the `item_removed` event doesn't get a `Library` argument. What would be the best way to access the library inside that function?

To be a little bit more specific, I need to access the library in order to get all the items that _their_ `source_path` matches the currently removed item's `source_path`'s dirname.

**Comment by sampsyo** [comment]
Hmm, not much of a reason---I actually can't recall at the moment whether import stages run before or after the files are moved, but you could find that out experimentally.

For the removal event, it's odd that that one doesn't get a library object. You should be able to recover it by looking at `item.lib`, however.

**Comment by doronbehar** [comment]
The `item` doesn't have a `lib` attribute :disappointed:.

**Comment by sampsyo** [comment]
Oops; sorry—I meant `item._db`. That should do it.

**Comment by jackwilsdon** [comment]
Is there a reason we use `_db` instead of something like `lib` or just `db`? The `_` prefix seems to somewhat indicate that it is private.

**Comment by sampsyo** [comment]
It is kinda generally private—it's typically not necessary for clients to use the database object directly. Instead, they can do things like `item.store()` to update the database. But it is there, just in case. :)

**Comment by doronbehar** [comment]
Oh right, thanks a lot @sampsyo! I think my plugin is finished by now and I wouldn't have been able to accomplish this without you so I greatly appreciate your help :grinning:.

**Comment by sampsyo** [comment]
Excellent news! I'm glad it's working.
