### ISSUE TITLE
"Original date" is something different for albums and tracks!

### ISSUE THREAD

**Issue by Moonbase59** [beetbox/beets#3382]
This is mainly a reminder to talk about:

Without actually doing much testing: You _are_ aware that the "original date" for an _album_ and a _track_ are two completely different things?

Just because I ran across `library.py` today and I _think_ there was something flakey regarding the original year/month/day …

The original date for an _album_ should be the earliest date _this complete **album** has been released_. (Note: Production and Copyright year can be different, some albums are first released long after!)

The original date for a _track_ should be the earliest date _this single **track** has been released_ (even as a single or on a completely different album). Using MusicBrainz (or Picard with track/work relations enabled), this is usually derived from the release date of the oldest _recording_ found. (And should _not_ be confused with the _recording_, _production_, _remastering_ or _remixing_ dates.)

Example (fictional):

A "Greatest Hits" compilation came out in 2010 and has been re-released in 2018. The tracks on this compilation stem from years between 1969 and 2008.

* _Album Date for 1st release:_ `2010-03-23`
* _Album Date for 2nd release:_ `2018-09-23`
* _Album Original Date for both releases:_ `2010-03-23`
* _Track 1 Original Date (for both releases):_ `1969-03` (we don’t know the day)
* _Track 2 Original Date (for both releases):_ `1972` (again, we only know the year)
* _Track 3 Original Date (for both releases):_ `1998-04-01` (we know the exact date)
* …

Doing this right would also automagically get rid of any problems people have with (often manually tagged) large Various Artists compilations with many tracks from different years.

Purely selfish, I know. Just because I want to
```bash
beet ls original_date:1959-07   # look for TRACKS first released in July, 1959
```
and get all tracks that have been released in my birth month, be it on a compilation or not … :smile: 

Or maybe find all albums I own that have been released in 1959:
```bash
beet ls -a original_date:1959   # look for ALBUMS first released in 1959
```

**Comment by sampsyo** [comment]
Please see #1498, where this has been discussed before. There's even a community-contributed plugin to get track release dates linked there!
