### ISSUE TITLE
Filename/path lengths

### ISSUE THREAD

**Issue by Moonbase59** [beetbox/beets#3383]
https://github.com/beetbox/beets/blob/00ac5928c1a55e1ed07e0b4069f6fe02ac29f04a/beets/util/__init__.py#L39

Is this the _filename_ or the _total path_ length?

On Windows (NTFS), individual components of a filename (i.e. each subdirectory along the path, and the final filename) are limited to 255 characters, and the total path length is limited to 32,767 characters.

However, on Windows, you can't exceed `MAX_PATH` value (259 characters for files, 248 for folders). See http://msdn.microsoft.com/en-us/library/aa365247.aspx for details.

Linux has a maximum filename length of 255 characters for most filesystems (including EXT4), and a maximum path of 4096 characters.

That said, I’m currently using paths of about (max.) 1,000 characters and am _so_ happy I don’t have to restrict myself to 259 anymore … And I _do_ have some filenames/parts of paths that _are_ longer than 200 (Unicode) characters, quickly asserted using
```bash
cd ~/Musik/Tagged/
find "$PWD" -regextype posix-extended -regex '.*[^/]{200,}$'
```

Just an example (234 chars filename, path=303 chars):
```
/home/matthias/Musik/Tagged/Rush/Rush - Hemispheres (1997 album, GB)/Rush - Cygnus X-1, Book II_ Hemispheres_ I. Prelude _ II. Apollo_ Bringer of Wisdom _ III. Dionysus_ Bringer of Love _ IV. Armageddon_ The Battle of Heart and Mind _ V. Cygnus_ Bringer of Balance _ VI. The Sphere: A Kind of Dream.mp3
```
This one is also nice (but only 215 chars):
```
/home/matthias/Musik/Tagged/Český symfonický orchestr & Morricone, Ennio/Český symfonický orchestr & Morricone, Ennio - [compilations]/Český symfonický orchestr & Morricone, Ennio - The Good, The Bad & The Ugly.mp3
```

**Comment by sampsyo** [comment]
An individual path component. But that's not the whole story—see also the `max_filename_length` function in the same file.

**Comment by Moonbase59** [comment]
Could this be pushed to 255? Otherwise, not all files might be recognized?

**Comment by sampsyo** [comment]
Here are a couple of things to note before seriously exploring changing that constant:

- We'll ingest any filename, so this isn't a problem with files being _recognized_. It's just about generating new filenames.
- It's already configurable, so please feel free to change the `max_filename_length` setting if you like.
- A conservative built-in default is probably a good policy when we don't know what filesystem the user will bring, as opposed to living right on the edge of what we think will be safe.

**Comment by Moonbase59** [comment]
Thanks for this, didn’t know it was configurable. 👍
