### ISSUE TITLE
Genre search deficiency (database/tags abstraction)

### ISSUE THREAD

**Issue by Moonbase59** [beetbox/beets#3384]
Doing a simple search like
```bash
beet ls genre:aor
```
doesn’t find a big part of my collection.

Reason:
Part of my library is MP3, and the genre tag contains `Hard Rock; AOR`.
Another big part is FLAC, which has of course _two_ genre tags `Hard Rock` and `AOR`.

* For MP3 (with ID3v2.3), the search is no problem, because `AOR` is contained in the text `Hard Rock; AOR`.
* For FLAC (possibly also MP3 ID3v2.4), depending on which tag comes first, `AOR` is _not_ found, because `genre` only takes _one_ of the many genre tags (the first, I think).

Looking at the `beet info` for a FLAC file, it shows:
```
genre: Hard Rock
genres: Hard Rock; AOR
grouping: Hard Rock
```

Aha, you think, no problem, it has constructed a (plural) `genres` field for me that contains all genres. Great.

_Nope. Bad luck._ `genres` is again a field that _can’t be queried!_ Beets will not complain about
```bash
beet ls genres:aor
```
but take a long time on a 150k track collection, just to return … _nothing!_

**This is not intuitive and users might miss a lot of results.**

---

**We should really think about making these abstractions queryable in an intuitive manner.**

These are not "constructed edge cases", but things I need to do every day. I accidentally found this out on a relatively simple playlist query which was lacking an album I had just added:
```bash
beet ls -p year:2015..2019 genre:'melodic' ^genre:metal, year:2015..2019 genre:aor ^genre:metal > '2015-2019 melodic+aor.m3u'
```

**Comment by sampsyo** [comment]
Hello! This is a known issue—multi-valued tags are a very large architectural change. They have been discussed in other issues around here—most notably, #505.
