### ISSUE TITLE
2-CD album import changes track numbers to nonsensical values

### ISSUE THREAD

**Issue by Moonbase59** [beetbox/beets#3386]
When importing the 2-CD Peter Gabriel album "[2009-03-22 Buenos Aires, Argentina - Latin American Tour](https://musicbrainz.org/release/270b53b9-c76f-4081-9ad4-3fd4f56f9642)", I get the track numbers of the 2nd CD changed to be a "continuation" of the track numbers from the first CD.

We’re talking about _media_. A CD is a separate medium that starts counting track numbers from 1, so beets shouldn’t try to "make up" new track numbers.

```
/home/matthias/Musik/Tagged/Gabriel, Peter/Gabriel, Peter - 2009-03-22 Buenos Aires, Argentina - Latin American Tour (2009 album, live, AR) (20 items)
Correcting tags from:
    Peter Gabriel - 2009-03-22 Buenos Aires, Argentina - Latin American Tour
To:
    Peter Gabriel - 2009‐03‐22 Buenos Aires, Argentina – Latin American Tour
URL:
    http://musicbrainz.org/release/270b53b9-c76f-4081-9ad4-3fd4f56f9642
(Similarity: 100.0%) (2xCD, 2009, AR, Real World)
CD 1
CD 2
 * Big Time (#1)        -> Big Time (#12)
 * Secret World (#2)    -> Secret World (#13)
 * Solsbury Hill (#3)   -> Solsbury Hill (#14)
 * Sledgehammer (#4)    -> Sledgehammer (#15)
 * Signal to Noise (#5) -> Signal to Noise (#16)
 * In Your Eyes (#6)    -> In Your Eyes (#17)
 * Red Rain (#7)        -> Red Rain (#18)
 * Father Son (#8)      -> Father Son (#19)
 * Biko (#9)            -> Biko (#20)
```

**Comment by jackwilsdon** [comment]
Does the [`per_disc_numbering`](https://beets.readthedocs.io/en/latest/reference/config.html#per-disc-numbering) option fix your issue? (you'll need to change your path format too as suggested by the documentation)

**Comment by Moonbase59** [comment]
Brilliant, that worked! Thanks for the heads-up!
