### ISSUE TITLE
Using beets as a library

### ISSUE THREAD

**Issue by rain0r** [beetbox/beets#3403]
### Use case

Is it possible to use beets in another Python application? I would like to gather some information from the database without accessing the raw sqlite-database. Since this is a standalone application, I can't go the same way as with the plugins.

If so, some additional docs on this would be great.

**Comment by sampsyo** [comment]
Hi! Yeah, it's definitely possible. May I direct you to this old mailing list thread as a starting point?
https://groups.google.com/forum/#!msg/beets-users/tcdPBkkonrw/vX63oi3nIzIJ

You'll see in the last message that another user even wrote a blog post with some pointers about how to get started.

**Comment by rain0r** [comment]
Thanks for the link!
Unfortunately I run into the same problem as before. When using a python script like that:

```
from beets import config
from beets import importer
from beets.ui import _open_library
```

I get import errors, although beets is installed via pip in the active virtualenv.

```
    from beets import config
ImportError: cannot import name 'config' from 'beets
```

**Comment by sampsyo** [comment]
That's odd! I can't seem to reproduce that here. Could there be something wrong with the Virtualenv? Can you try just doing `import beets` and printing out `dir(beets)` on the REPL, for example?

**Comment by rain0r** [comment]
Solved it! I started the script in a dir which was a Python module also named `beets`. 🤦‍♂️

Thanks for your time.
