### ISSUE TITLE
convert uses wrong ${format} string on destination path

### ISSUE THREAD

**Issue by scruloose** [beetbox/beets#3407]
### Problem

What I'm hoping to accomplish is to have my collection of albums available in up to three formats, all intermingled under the same parent directory. My default path entry is this:

    $albumartist_sort/${albumtype}s/$original_year - $album [${format}]/$track $title

That works as expected on a regular `beet import` operation, which is frankly pretty nifty in its own right! For example, `beet import rips/1973 - Queen (Remaster Deluxe 2CD)` consolidates all the tracks from both disks into `beets_test/Queen/albums/1973\ -\ Queen\ \[FLAC\]/`

But then doing a `beet convert Queen` (with no path specified, so it reuses the default shown above) cheerfully creates the path 'converted/Queen/albums/1973\ -\ Queen\ \[FLAC\]/' and transcodes all the mp3 files into it.

I would expect the created output directory to be `1973\ -\ Queen\ \[MP3\]/', to correspond to the format of the transcoded files in it. 

This would allow me to use the same directory *and* the same path string for the 'convert' plugin and the beets library, so when I do a directory listing of `beets_test/Queen/albums/` I could see at a glance that I have both FLAC and MP3 versions of their 1973 self-titled album.  If I don't remember what format I originally got a given album in, I don't want to look in beets to see whether it's a phone-friendly mp3 or ogg there, find the FLAC, and then have to go drill down through one or both of separate ogg and mp3 directory trees to find the lossy compressed version...

Interestingly, if I set convert's `auto:` option to `yes`, then during a `beet import` operation it *does* correctly create the directory with the format identifier of the converted format. This doesn't really help me, because I want to keep the converted version along with the original, not replace it, but I thought it might be a helpful data-point.

My hope is to use the 'alternatives' plugin to manage the transcoded versions, but because 'alternatives' relies on the built-in 'convert' plugin for transcoding, it is also affected by this wrong `${format}` issue.

### Setup

* OS: Debian Bullseye
* Python version: 3.7.5
* beets version: 1.4.9

My configuration is:

[a rapidly-changing test setup]

**Comment by sampsyo** [comment]
Hello! Please see https://github.com/beetbox/beets/issues/1360.
