### ISSUE TITLE
Lollypop integration

### ISSUE THREAD

**Issue by tecosaur** [beetbox/beets#3414]
### Use case

I'm trying to use beets to keep track of my library and listening, while using [lollypop](https://wiki.gnome.org/Apps/Lollypop) as my music player.

### Solution

Beets seems to have very nice mpd integration, it would be great if it would be possible to do something similar with lollypop (a nice, fairly popular, linux music player). I'm not sure how hard this would be, for example I have a sqlite database at `~/.local/share/lollypop/lollypop.db` with all some potentially useful columns (popularity, loved, rate).

### Alternatives

Not aware of anything that can currently help with this other than switching apps etc.

**Comment by tecosaur** [comment]
### More Info
I had a look in `~/.local/share/lollypop/` and there seem to be four databases:
### lollypop.db
#### 
#### 
#### 
### history.db
#### History table
| Field | Vale |
|---|---|
|id|int|
|name|text|
|duration|int|
|ltime|int|
|popularity|int|
|rate|int|
|mtime|int
|album_rate|int|
|loved|int|
|album_loved|int|
|album_synced|int|
|album_popularity|int|

**Comment by tecosaur** [comment]
### More Info
Perhaps this could be useful.
I had a look in `~/.local/share/lollypop/` and there seem to be four databases:
### lollypop.db
<details>
<summary>Tables</summary>

#### album_artists
| Field | Vale |
|---|---|
|album_id|int|
|artist_id|int|
#### album_genres
| Field | Vale |
|---|---|
|album_id|int|
|genre_id|int|
#### albums
| Field | Vale |
|---|---|
|id|int|
|name|text|
|mb_album_id|text|
|no_album_artist|bool|
|year|int|
|timestamp|int|
|uri|text|
|popularity|int|
|rate|int|
|loved|int|
|mtime|int|
|synced|int|
#### artists
| Field | Vale |
|---|---|
|id|int|
|name|text|
|sortname|text|
|mb_artist_id|
#### genres
| Field | Vale |
|---|---|
|id|int|
|name|text|
#### track_artists
| Field | Vale |
|---|---|
|track_id|int|
|name|text|
#### track_genres
| Field | Vale |
|---|---|
|track_id|int|
|name|text|
#### tracks
| Field | Vale |
|---|---|
|id|int|
|name|text|
|uri|text|
|duration|int|
|tracknumber|int|
|disknumber|int|
|album_id|int|
|year|int|
|timestamp|int|
|popularity|int|
|loved|int|
|rate|int|
|ltime|int|
|mtime|int|
|mb_track_id|text|
|bpm|double|

</details>

### history.db

<details>
<summary>Tables</summary>

#### History
| Field | Vale |
|---|---|
|id|int|
|name|text|
|duration|int|
|ltime|int|
|popularity|int|
|rate|int|
|mtime|int
|album_rate|int|
|loved|int|
|album_loved|int|
|album_synced|int|
|album_popularity|int|

</details>

### playlists.db
<details>
<summary>Tables</summary>

#### playlists
| Field | Vale |
|---|---|
|id|int|
|name|text|
|synced|int|
|smart_enabled|int|
|smart_sql|text|
|mtime|bigint|
#### tracks
| Field | Vale |
|---|---|
|playlist_id|ont|
|uri|text|

</details>


### radios.db
<details>
<summary>Tables</summary>

#### radios
| Field | Vale |
|---|---|
|id|int|
|name|text|
|url|text|
|rate|int|
|popularity|int|

</details>

**Comment by sampsyo** [comment]
Interesting! That does look like a really nice player. It seems like there are a few options for what to do for "integration":

- A beets plugin that provides a command to export the beets database as a Lollypop database.
- A beets plugin that triggers Lollypop to re-scan files when a change happens (like the other `*update` plugins we already have).
- Some sort of addition to Lollypop that makes it read the beets library directly.
- Provide a network API that Lollypop can use to access the beets library, as in [this proposal](https://gitlab.gnome.org/World/lollypop/issues/1757) to do something similar for Funkwhale.

Not sure what the best strategy is, but it would be worth exploring all of these options!

**Comment by tecosaur** [comment]
Thanks for the eager response! I was a bit tentative creating this so it's great to see :)
To me **3** sounds the best, followed by **2**, **4** then **1**.

To that end I've now created https://gitlab.gnome.org/World/lollypop/issues/2077 now I'll just cross my fingers and await a reply :crossed_fingers:

**Comment by tecosaur** [comment]
Update from Gnome GitLab: Unfortunately doesn't look like lollypop will integrate anything, but it was suggested to make a beets extension that uses MPRIS. It seems this could even work for rating updates.
```xml
        <interface name="org.mpris.MediaPlayer2.ExtensionSetRatings">
            <method name="SetRating">\
                <arg direction="in" name="TrackId" type="o"/>
                <arg direction="in" name="Rating" type="d"/>\
            </method>\
            <property name="HasRatingsExtension" type="b" access="read"/>\
        </interface>
```
So, if we could get a plugin that uses MPRIS to update the beets database that may work, and it would apply to many more music players that just Lolypop!

**Comment by sampsyo** [comment]
Hmm… sounds interesting, but maybe you can help me understand a thing. I thought MPRIS was a protocol for controlling _players_? That is, if you have a background music player and want to make a system tray tool thing to play/pause/skip, for example, the controller could send messages to the player via MPRIS.

For Lollypop+beets, however, we'd need a protocol for accessing _music libraries_, i.e., getting access to the actual underlying audio files. Is that right? FWIW, that's kind of the focus of our fledgling [Aura](https://github.com/beetbox/aura) effort…

**Comment by tecosaur** [comment]
I'm not sure, I for one have never heard of dbus before now. Doing some googling though I've managed to do this
```sh
$ dbus-send --print-reply --type=method_call --dest='org.gnome.Lollypop' /org/mpris/MediaPlayer2 org.freedesktop.DBus.Properties.Get string:'org.mpris.MediaPlayer2.Player' string:'Position'

method return time=1572097404.734851 sender=:1.2252 -> destination=:1.3016 serial=1816 reply_serial=2
   variant       int64 111604349
```
Still no clue how to get `Rating` though.

**Comment by tecosaur** [comment]
@sampsyo I asked the maintainer and he said it was possible and pointed out this https://github.com/JasonLG1979/gnome-shell-extension-mpris-indicator-button as an example.

Do you think you could do something with that?

**Comment by sampsyo** [comment]
Hmm… I'm still not sure I 100% understand the plan here. That example shows how to control playback in Lollypop—skip tracks, view the current playlist, etc. Is that what you'd want to do with beets?

**Comment by tecosaur** [comment]
Oh no, I'm just hoping to pass rating, playcount, etc. information from lollypop to beets — much like can be done with MPD. I think the example was given to show how dbus method arguments can be read, but I'm not sure (I'd never even heard of dbus before this).

**Comment by sampsyo** [comment]
Aha, got it. It might be possible to query stuff from the library over MPRIS! I unfortunately don't know much about the protocol either, but it is worth looking into to see if it's possible to build a totally standalone script that can pull the information you want. If so, then the next step might be to try to build a beets plugin.

**Comment by tecosaur** [comment]
@tecosaur I'm currently woefully strapped for time, but I'm very interested in getting this functionality. Given the apparent popularity of Lollypop, I imagine a bunch of other users would really appreciate this as well. Are you willing to give this a shot or should I look to someone else? :sweat_smile:

**Comment by tecosaur** [comment]
_@sampsyo \*cough_

**Comment by sampsyo** [comment]
:smiley: Sorry, I myself can't do it. Happy to provide advice to anyone who wants to pitch in, though.

**Comment by pprkut** [comment]
I've done something similar for amarok in the metasync plugin (which is actually meant for ideas like this). It also fetches rating, playcount, etc from amarok via dbus and stores it in beets' db. If you're interested you can take a look at [beetsplug/metasync/amarok.py](https://github.com/beetbox/beets/blob/master/beetsplug/metasync/amarok.py)

**Comment by tecosaur** [comment]
@pprkut Thanks for that! So, might the result be in the form of `beetsplug/metasync/lollypop.py`?
For development, would I be able to do so by running that file by itself?

**Comment by pprkut** [comment]
Correct, a plugin for Lollypop would end up in a file like that. There's also a small update that would need to be done on [beetsplug/metasync/__init__.py](https://github.com/beetbox/beets/blob/master/beetsplug/metasync/__init__.py). But that should be about it.
However, I'm afraid you can't just call that file during development. You have to call the metasync plugin through beets. Check the documentation for how use and configure the plugin: https://beets.readthedocs.io/en/stable/plugins/metasync.html

The `-p` switch should help a bit during development :)
