### ISSUE TITLE
When a filename contains % and is treated as a track, it never resolves to a track ID

### ISSUE THREAD

**Issue by djsmiley2k** [beetbox/beets#3416]
MP3 file name: `No Doubt - Acoustic - %n - Just a Girl.mp3`

It appears when Beets imports this file, and I hit t, to treat as a track rather than a album, it gets 100% match to No Doubt - Just a Girl, and then loads the same Album dialog as before.
```
# selection (default 1), Skip, Use as-is, as Tracks, Group albums,
Enter search, enter Id, aBort? t
Sending event: import_task_choice
Sending event: import_task_created
Sending event: import_task_start
Looking up: /home/tim/server/media/music/No Doubt - Acoustic - %n - Just a Girl.mp3
Item search terms: No Doubt - Just a Girl
Sending event: trackinfo_received
Sending event: trackinfo_received
Sending event: trackinfo_received
Sending event: trackinfo_received
Sending event: trackinfo_received
Sending event: trackinfo_received
Sending event: trackinfo_received
Sending event: trackinfo_received
Sending event: trackinfo_received
Sending event: trackinfo_received
chroma: acoustid item candidates: 5
Sending event: trackinfo_received
Sending event: trackinfo_received
Sending event: trackinfo_received
Sending event: trackinfo_received
Sending event: trackinfo_received
Found 10 candidates.

/home/tim/server/media/music/No Doubt - Acoustic - %n - Just a Girl.mp3
Sending event: before_choose_candidate
Tagging track: No Doubt - Just a Girl
URL:
    https://musicbrainz.org/recording/693e1e1e-04b8-441f-bcaa-5c0c33acdff2
(Similarity: 100.0%)
Sending event: import_task_choice
```
at which point it shows the album selection again. I've pastebinned the entire log here: https://pastebin.com/A6MKAHRf as I'm unable to attach it for some reason.

### Setup

* OS: Gentoo
* Python version: 3.6.9
* beets version: tim@MushaV3 ~/server/media/music $ beet version
beets version 1.4.9
Python version 3.6.9
plugins: chroma

* Turning off plugins made problem go away (yes/no): No. :(

My configuration (output of `beet config`) is:

```
 import:
 write: yes
 move: yes
 resume: ask
 incremental: yes
 incremental_skip_later: yes
 languages: en
 group_albums: yes
 duplicate_action: merge
 log: ~/.config/beets/import.log
 default_action: none

directory: ~/server/media/sorted_music/

match:
    preferred:
	countries: ['US', 'GB|UK']

#plugins:

chroma:
  auto: yes

threaded: no

**Comment by sampsyo** [comment]
Can you please include the command you ran, as indicated by the issue template?

**Comment by sampsyo** [comment]
Also, it would be interesting to try these things:

- What happens when you just import this as an album?
- How about if you just use a singleton import, and not the "as Tracks" interactive option?
- Is it _really_ the % sign? How do you know that? If you remove the % sign from the filename, does anything change?

**Comment by djsmiley2k** [comment]
Whoops sorry,

Command I ran is `beet -v import ~/server/media/music`

I'll try the things suggested.

**Comment by djsmiley2k** [comment]
Out of interest, I've just had another crash which I'll raise a bug for, but I notice the odd symbols in the file name again might be an issue -- https://pastebin.com/YNN71zYg

**Comment by djsmiley2k** [comment]
Log of me selecting 'as Tracks' over and over again without it actually adding the file as a track, even with 100% match.

tim@MushaV3 ~/beettest $ ls
'No Doubt - Acoustic - %n - Just a Girl.mp3'
tim@MushaV3 ~/beettest $ beets -i ./No\ Doubt\ -\ Acoustic\ -\ %n\ -\ Just\ a\ Girl.mp3 
bash: beets: command not found
tim@MushaV3 ~/beettest $ beet -v import ./No\ Doubt\ -\ Acoustic\ -\ %n\ -\ Just\ a\ Girl.mp3 
user configuration: /home/tim/.config/beets/config.yaml
data directory: /home/tim/.config/beets
plugin paths: 
Sending event: pluginload
library database: /home/tim/.config/beets/library.db
library directory: /home/tim/server/media/sorted_music
Sending event: library_opened
Sending event: import_begin
Sending event: import_task_created
Sending event: import_task_created
Sending event: import_task_start
Looking up: /home/tim/beettest/No Doubt - Acoustic - %n - Just a Girl.mp3
Tagging No Doubt - Just a Girl
No album ID found.
Search terms: No Doubt - Just a Girl
Album might be VA: False
Searching for MusicBrainz releases with: {'release': 'just a girl', 'artist': 'no doubt', 'tracks': '1'}
Requesting MusicBrainz release 2a0c2214-7fdb-4f8b-9fcb-ab2851f8e383
primary MB release type: single
Sending event: albuminfo_received
Candidate: No Doubt - Just a Girl (2a0c2214-7fdb-4f8b-9fcb-ab2851f8e383)
Computing track assignment...
...done.
Success. Distance: 0.10
Requesting MusicBrainz release 0d0d8e4a-f0fc-410a-9af3-8a311d157f37
primary MB release type: single
Sending event: albuminfo_received
Candidate: No Doubt - Just a Girl (0d0d8e4a-f0fc-410a-9af3-8a311d157f37)
Computing track assignment...
...done.
Success. Distance: 0.29
Requesting MusicBrainz release a5cca710-51cc-4dd5-9c05-602ff4b4e4e7
primary MB release type: single
Sending event: albuminfo_received
Candidate: No Doubt - Just a Girl (a5cca710-51cc-4dd5-9c05-602ff4b4e4e7)
Computing track assignment...
...done.
Success. Distance: 0.22
Requesting MusicBrainz release 9df72dcc-a683-4808-bf25-baf7c85a6aea
primary MB release type: single
Sending event: albuminfo_received
Candidate: No Doubt - Just a Girl (9df72dcc-a683-4808-bf25-baf7c85a6aea)
Computing track assignment...
...done.
Success. Distance: 0.26
Requesting MusicBrainz release eaf28c20-49df-4eda-a2a1-593159a81eba
primary MB release type: single
Sending event: albuminfo_received
Candidate: No Doubt - Just a Girl (eaf28c20-49df-4eda-a2a1-593159a81eba)
Computing track assignment...
...done.
Success. Distance: 0.28
chroma: acoustid album candidates: 0
Evaluating 5 candidates.

/home/tim/beettest/No Doubt - Acoustic - %n - Just a Girl.mp3 (1 items)
Sending event: before_choose_candidate
Tagging:
    No Doubt - Just a Girl
URL:
    https://musicbrainz.org/release/2a0c2214-7fdb-4f8b-9fcb-ab2851f8e383
(Similarity: 90.4%) (missing tracks) (CD, 1996, US, Interscope Records, INTDS-98116)
Missing tracks (1/2 - 50.0%):
 ! Different People (# 2) (4:34)
Apply, More candidates, Skip, Use as-is, as Tracks, Group albums,
Enter search, enter Id, aBort? m
Finding tags for album "No Doubt - Just a Girl".
Candidates:
1. No Doubt - Just a Girl (90.4%) (missing tracks) (CD, 1996, US, Interscope Records, INTDS-98116)
2. No Doubt - Just a Girl (77.7%) (missing tracks, country) (CD, 1996, DE, Interscope Records, IND 80034)
3. No Doubt - Just a Girl (73.7%) (missing tracks, country) (CD, 1997, GB, Trauma Records, IND 95539, CD1)
4. No Doubt - Just a Girl (72.4%) (missing tracks, country, tracks) (CD, 1997, GB, Trauma Records, INDX 95539, CD2)
5. No Doubt - Just a Girl (71.4%) (missing tracks, country) (CD, 1997, DE, Interscope Records, IND 95537)
# selection (default 1), Skip, Use as-is, as Tracks, Group albums,
Enter search, enter Id, aBort? t
Sending event: import_task_choice
Sending event: import_task_created
Sending event: import_task_start
Looking up: /home/tim/beettest/No Doubt - Acoustic - %n - Just a Girl.mp3
Item search terms: No Doubt - Just a Girl
Sending event: trackinfo_received
Sending event: trackinfo_received
Sending event: trackinfo_received
Sending event: trackinfo_received
Sending event: trackinfo_received
Found 5 candidates.

/home/tim/beettest/No Doubt - Acoustic - %n - Just a Girl.mp3
Sending event: before_choose_candidate
Correcting track tags from:
    No Doubt - Just a Girl
To:
    No Doubt - Just A Girl
URL:
    https://musicbrainz.org/recording/ae436657-3305-4cfb-8a19-a4bd86682695
(Similarity: 100.0%)
Sending event: import_task_choice
found duplicates: [3124]
default action for duplicates: m
Sending event: import_task_start
Looking up: /home/tim/beettest/No Doubt - Acoustic - %n - Just a Girl.mp3; /home/tim/server/media/sorted_music/Non-Album/No Doubt/Just A Girl.mp3
Tagging No Doubt - Just a Girl
No album ID found.
Search terms: No Doubt - Just a Girl
Album might be VA: False
Searching for MusicBrainz releases with: {'release': 'just a girl', 'artist': 'no doubt', 'tracks': '2'}
Requesting MusicBrainz release 2a0c2214-7fdb-4f8b-9fcb-ab2851f8e383
primary MB release type: single
Sending event: albuminfo_received
Candidate: No Doubt - Just a Girl (2a0c2214-7fdb-4f8b-9fcb-ab2851f8e383)
Computing track assignment...
...done.
Success. Distance: 0.19
Requesting MusicBrainz release 0d0d8e4a-f0fc-410a-9af3-8a311d157f37
primary MB release type: single
Sending event: albuminfo_received
Candidate: No Doubt - Just a Girl (0d0d8e4a-f0fc-410a-9af3-8a311d157f37)
Computing track assignment...
...done.
Success. Distance: 0.32
Requesting MusicBrainz release a5cca710-51cc-4dd5-9c05-602ff4b4e4e7
primary MB release type: single
Sending event: albuminfo_received
Candidate: No Doubt - Just a Girl (a5cca710-51cc-4dd5-9c05-602ff4b4e4e7)
Computing track assignment...
...done.
Success. Distance: 0.27
Requesting MusicBrainz release 9df72dcc-a683-4808-bf25-baf7c85a6aea
primary MB release type: single
Sending event: albuminfo_received
Candidate: No Doubt - Just a Girl (9df72dcc-a683-4808-bf25-baf7c85a6aea)
Computing track assignment...
...done.
Success. Distance: 0.30
Requesting MusicBrainz release eaf28c20-49df-4eda-a2a1-593159a81eba
primary MB release type: single
Sending event: albuminfo_received
Candidate: No Doubt - Just a Girl (eaf28c20-49df-4eda-a2a1-593159a81eba)
Computing track assignment...
...done.
Success. Distance: 0.31
chroma: acoustid album candidates: 0
Evaluating 5 candidates.

/home/tim/beettest/No Doubt - Acoustic - %n - Just a Girl.mp3
/home/tim/server/media/sorted_music/Non-Album/No Doubt/Just A Girl.mp3 (2 items)
Sending event: before_choose_candidate
Tagging:
    No Doubt - Just a Girl
URL:
    https://musicbrainz.org/release/2a0c2214-7fdb-4f8b-9fcb-ab2851f8e383
(Similarity: 81.5%) (tracks) (CD, 1996, US, Interscope Records, INTDS-98116)
 * Just A Girl (#0) (3:23) -> Different People (#2) (4:34) (id, title, length)
Apply, More candidates, Skip, Use as-is, as Tracks, Group albums,
Enter search, enter Id, aBort? t
Sending event: import_task_choice
Sending event: import_task_created
Sending event: import_task_start
Looking up: /home/tim/beettest/No Doubt - Acoustic - %n - Just a Girl.mp3
Item search terms: No Doubt - Just a Girl
Sending event: trackinfo_received
Sending event: trackinfo_received
Sending event: trackinfo_received
Sending event: trackinfo_received
Sending event: trackinfo_received
Found 5 candidates.

/home/tim/beettest/No Doubt - Acoustic - %n - Just a Girl.mp3
Sending event: before_choose_candidate
Correcting track tags from:
    No Doubt - Just a Girl
To:
    No Doubt - Just A Girl
URL:
    https://musicbrainz.org/recording/ae436657-3305-4cfb-8a19-a4bd86682695
(Similarity: 100.0%)
Sending event: import_task_choice
found duplicates: [3124]
default action for duplicates: m
Sending event: import_task_start
Looking up: /home/tim/beettest/No Doubt - Acoustic - %n - Just a Girl.mp3; /home/tim/server/media/sorted_music/Non-Album/No Doubt/Just A Girl.mp3
Tagging No Doubt - Just a Girl
No album ID found.
Search terms: No Doubt - Just a Girl
Album might be VA: False
Searching for MusicBrainz releases with: {'release': 'just a girl', 'artist': 'no doubt', 'tracks': '2'}
Requesting MusicBrainz release 2a0c2214-7fdb-4f8b-9fcb-ab2851f8e383
primary MB release type: single
Sending event: albuminfo_received
Candidate: No Doubt - Just a Girl (2a0c2214-7fdb-4f8b-9fcb-ab2851f8e383)
Computing track assignment...
...done.
Success. Distance: 0.19
Requesting MusicBrainz release 0d0d8e4a-f0fc-410a-9af3-8a311d157f37
primary MB release type: single
Sending event: albuminfo_received
Candidate: No Doubt - Just a Girl (0d0d8e4a-f0fc-410a-9af3-8a311d157f37)
Computing track assignment...
...done.
Success. Distance: 0.32
Requesting MusicBrainz release a5cca710-51cc-4dd5-9c05-602ff4b4e4e7
primary MB release type: single
Sending event: albuminfo_received
Candidate: No Doubt - Just a Girl (a5cca710-51cc-4dd5-9c05-602ff4b4e4e7)
Computing track assignment...
...done.
Success. Distance: 0.27
Requesting MusicBrainz release 9df72dcc-a683-4808-bf25-baf7c85a6aea
primary MB release type: single
Sending event: albuminfo_received
Candidate: No Doubt - Just a Girl (9df72dcc-a683-4808-bf25-baf7c85a6aea)
Computing track assignment...
...done.
Success. Distance: 0.30
Requesting MusicBrainz release eaf28c20-49df-4eda-a2a1-593159a81eba
primary MB release type: single
Sending event: albuminfo_received
Candidate: No Doubt - Just a Girl (eaf28c20-49df-4eda-a2a1-593159a81eba)
Computing track assignment...
...done.
Success. Distance: 0.31
chroma: acoustid album candidates: 0
Evaluating 5 candidates.

/home/tim/beettest/No Doubt - Acoustic - %n - Just a Girl.mp3
/home/tim/server/media/sorted_music/Non-Album/No Doubt/Just A Girl.mp3 (2 items)
Sending event: before_choose_candidate
Tagging:
    No Doubt - Just a Girl
URL:
    https://musicbrainz.org/release/2a0c2214-7fdb-4f8b-9fcb-ab2851f8e383
(Similarity: 81.5%) (tracks) (CD, 1996, US, Interscope Records, INTDS-98116)
 * Just A Girl (#0) (3:23) -> Different People (#2) (4:34) (id, title, length)
Apply, More candidates, Skip, Use as-is, as Tracks, Group albums,
Enter search, enter Id, aBort? t
Sending event: import_task_choice
Sending event: import_task_created
Sending event: import_task_start
Looking up: /home/tim/beettest/No Doubt - Acoustic - %n - Just a Girl.mp3
Item search terms: No Doubt - Just a Girl
Sending event: trackinfo_received
Sending event: trackinfo_received
Sending event: trackinfo_received
Sending event: trackinfo_received
Sending event: trackinfo_received
Found 5 candidates.

/home/tim/beettest/No Doubt - Acoustic - %n - Just a Girl.mp3
Sending event: before_choose_candidate
Correcting track tags from:
    No Doubt - Just a Girl
To:
    No Doubt - Just A Girl
URL:
    https://musicbrainz.org/recording/ae436657-3305-4cfb-8a19-a4bd86682695
(Similarity: 100.0%)
Sending event: import_task_choice
found duplicates: [3124]
default action for duplicates: m
Sending event: import_task_start
Looking up: /home/tim/beettest/No Doubt - Acoustic - %n - Just a Girl.mp3; /home/tim/server/media/sorted_music/Non-Album/No Doubt/Just A Girl.mp3
Tagging No Doubt - Just a Girl
No album ID found.
Search terms: No Doubt - Just a Girl
Album might be VA: False
Searching for MusicBrainz releases with: {'release': 'just a girl', 'artist': 'no doubt', 'tracks': '2'}
Requesting MusicBrainz release 2a0c2214-7fdb-4f8b-9fcb-ab2851f8e383
primary MB release type: single
Sending event: albuminfo_received
Candidate: No Doubt - Just a Girl (2a0c2214-7fdb-4f8b-9fcb-ab2851f8e383)
Computing track assignment...
...done.
Success. Distance: 0.19
Requesting MusicBrainz release 0d0d8e4a-f0fc-410a-9af3-8a311d157f37
primary MB release type: single
Sending event: albuminfo_received
Candidate: No Doubt - Just a Girl (0d0d8e4a-f0fc-410a-9af3-8a311d157f37)
Computing track assignment...
...done.
Success. Distance: 0.32
Requesting MusicBrainz release a5cca710-51cc-4dd5-9c05-602ff4b4e4e7
primary MB release type: single
Sending event: albuminfo_received
Candidate: No Doubt - Just a Girl (a5cca710-51cc-4dd5-9c05-602ff4b4e4e7)
Computing track assignment...
...done.
Success. Distance: 0.27
Requesting MusicBrainz release 9df72dcc-a683-4808-bf25-baf7c85a6aea
primary MB release type: single
Sending event: albuminfo_received
Candidate: No Doubt - Just a Girl (9df72dcc-a683-4808-bf25-baf7c85a6aea)
Computing track assignment...
...done.
Success. Distance: 0.30
Requesting MusicBrainz release eaf28c20-49df-4eda-a2a1-593159a81eba
primary MB release type: single
Sending event: albuminfo_received
Candidate: No Doubt - Just a Girl (eaf28c20-49df-4eda-a2a1-593159a81eba)
Computing track assignment...
...done.
Success. Distance: 0.31
chroma: acoustid album candidates: 0
Evaluating 5 candidates.

/home/tim/beettest/No Doubt - Acoustic - %n - Just a Girl.mp3
/home/tim/server/media/sorted_music/Non-Album/No Doubt/Just A Girl.mp3 (2 items)
Sending event: before_choose_candidate
Tagging:
    No Doubt - Just a Girl
URL:
    https://musicbrainz.org/release/2a0c2214-7fdb-4f8b-9fcb-ab2851f8e383
(Similarity: 81.5%) (tracks) (CD, 1996, US, Interscope Records, INTDS-98116)
 * Just A Girl (#0) (3:23) -> Different People (#2) (4:34) (id, title, length)
Apply, More candidates, Skip, Use as-is, as Tracks, Group albums,
Enter search, enter Id, aBort?
