### ISSUE TITLE
export in itunes xml format for DJing software

### ISSUE THREAD

**Issue by FaGuoMa** [beetbox/beets#3419]
### Use case

I hate itunes with a passion but sadly two of the main DJing softwares (Traktor from Native Instrument and Rekordbox) can read the xml itunes DB but, of course, cannot talk to one another. They're also disgraceful engineering and horrible library management systems.
Now, Apple is phasing our Itunes for some other random software ("Music", ha!) but xml support is probably here to stay (itunes endures on windows)
Music management is absolutely essential to DJing, and having a mirror of the properly managed track collection to some format both Rekordbox and Traktor would be really cool (smartplaylists based on flexible fields or tags for example are pure awesomeness). Straight to Rekordbox is not an option; [this joke](https://rekordbox.com/en/support/developer.php) is their developer support
 
### Solution

MBSync does sync the other way, so some of the groundwork is done already. The xml generation might not be tooo hard to pull off and maybe this 
[library](https://github.com/perminovs/iTunesXmlGen/tree/master/itunesxmlgen) could be a start

### Alternatives
Writing tags to files, and pushing to itunes, using [this example](https://randomgeekery.org/2017/10/01/beets-and-itunes/) to hook  a command to run an applescript. Which, in my case, means I can't stick to my *nix amazing desktop, and will have to endure Itunes, on top of the absolute engineering disgrace that is Rekordbox.

**Comment by sampsyo** [comment]
Hi! This is a good idea—so good, in fact, that it's been proposed before in #1403. Please consider contributing to the discussion there.

**Comment by slogsdon7** [comment]
I actually wrote a plugin that did a basic full export in iTunes XML format last year for the same purpose. I didn't manage to get around to playlists but I'll see if I can dig it up.
