### ISSUE TITLE
Failed to import single Album collection >450 songs ...

### ISSUE THREAD

**Issue by Hogola** [beetbox/beets#3423]
### Problem

Running:
beet import --flat "The Rolling Stone Magazines 500"

Returns
C:\Users\Thomas\Project Music Oct-2019\The Rolling Stone Magazines 500 (500 items)
Finding tags for album " - ".
Candidates:
1. Guns N' Roses - Use Your Illusion I (2.6%) (unmatched tracks, tracks, album, ...) (Discogs, CD, Europe, Geffen Records, GED 24415)
blablabla etc, pp and so on.

selection (default 1), Skip, Use as-is, as Tracks, Group albums,
Enter search, enter Id, aBort?  I

Enter release ID: b3484a66-a4de-444d-93d3-c99a73656905

Led to this problem:
No matching release found for 500 tracks.
For help, see: http://beets.readthedocs.org/en/latest/faq.html#nomatch
[S]kip, Use as-is, as Tracks, Group albums, Enter search, enter Id, aBort?
```
Musicbrainz - link: https://musicbrainz.org/series/b3484a66-a4de-444d-93d3-c99a73656905
```
Not sure if I am making a mistake but I have checked everything and it looks OK to me.

Cheers Thomas

![Beet Failing to Tag](https://user-images.githubusercontent.com/57359339/68128797-b0adf800-ff18-11e9-8f46-4b3b02ab7e89.jpg)

**Comment by sampsyo** [comment]
Hi! Please use the issue template. In particular, use the Markdown code blocks so that the output is readable. And include your system setup and configuration.

**Comment by sampsyo** [comment]
I also note that the link you have pasted is to a series, not a release. Use a MusicBrainz release ID, as the prompt indicates.

**Comment by Hogola** [comment]
I just saw that it is a recording series (in small font under the main title) on the the mainpage of the release, which is not obvious from the MBID I used.  For me the MBID represents the ID requested by Beet when pressing "I" to tag an album or multiples thereof.  If that is incorrect I apologize.
I

**Comment by sampsyo** [comment]
Yes, it must be a release ID. What you see there is the error—there is no release found with that ID. It is not feasible to check whether it happens to be every other type of ID.
