### ISSUE TITLE
Replace for written tags - HowTo

### ISSUE THREAD

**Issue by weilbith** [beetbox/beets#3429]
Hey there! :wave: 
I wonder if there is no option to use the `replace` functionality that is used for the path and filenames for the tags which are written to the files. So for example do I hate when album or track titles contain the `Explicit` or `Deluxe` keywords. I would love to be able define such kind of patterns for replacements (here deletion) as well. 
I've read through the documentation, plugins and issues. Unfortunately couldn't find a solution for it. Any suggestion? Thanks for your help!

**Comment by sampsyo** [comment]
Hi! Here's one idea: how about using the `inline` plugin to define a field called `$album_alt` that is like `$album`, but with a definition like:

```
album_alt: "album.replace('Explicit', '').replace('Deluxe', '')"
```

so it reflects the modifications you want?

I am also obligated to mention #488, which seems like it would be a good fit for this use case if it were implemented.

**Comment by weilbith** [comment]
Thanks for your fast reply!

I'm confused. The `inline` plugin itself states that it is meant for custom tags which can be used within the `path` templates. This is a nice feature yes, but does not relate to the described use-case.

Good reference. This sounds like what I need to reach my goal. Unfortunately this issue is inactive for over a year. I subscribed to it, but this doesn't look promising. That's sad because this is a big issue for me with this tool. 😞

**Comment by weilbith** [comment]
Maybe it's worth to checkout the developer documentation for plugins. Maybe it is easily affordable to write something on my own.

**Comment by sampsyo** [comment]
Ah yes, sorry—I read too quickly and missed the bit about "tags which are written to the files." But yes, a custom plugin might be just the thing! Shouldn't be too hard to do.

**Comment by weilbith** [comment]
No worries. Thanks for your help!
I'll probably leave a comment if I have something implemented. Just if someone stumble over this issue.

**Comment by amogus07** [comment]
any news? I think I would also have a usecase. If the album artist is "Various Artists", it should be set to whatever the label is. I tried using inline like so:

```yaml
album_fields:
    albumartist: label if albumartist == "Various Artists" else albumartist
```

but this yields an RecursionError. Possibly related to #2612
