### ISSUE TITLE
Business Cooperation Invitation from BTFS

### ISSUE THREAD

**Issue by yss0407** [beetbox/beets#3430]
Hello Beets Team,

This is Shusen, BD manager from BitTorrent File System (BTFS). In order to build application ecosystem in BTFS, we send you this invitation letter.

BTFS is both a protocol and network implementation that provides a content-addressable, peer-to-peer mechanism for storing and sharing digital content in a decentralized file system. BTFS represents the first scalable implementation of a decentralized storage system that can be used by decentralized application developers. Paired with the TRON ecosystem, and the BitTorrent network, the application of BTFS in the form of an addressable and permanent web advances the user experience.

We're interested in your IPFS music metadata 
[BTFS Deck (Nov. 2019).pptx](https://github.com/beetbox/beets/files/3862640/BTFS.Deck.Nov.2019.pptx)

product Beets. We have prepared sufficient marketing resource, funding assistance, and technical support to explore business cooperation opportunities with you. 

If you have interest, please find a time here that works for you: https://calendly.com/shusen-yang

Shusen Yang
BD Manager丨Developer Community Department

Email: shusen.yang@tron.network
Telegram: @ShusenTron
WeChat: @yss0407

**Comment by sampsyo** [comment]
Please feel free to make concrete proposals here on GitHub, but we are not really interested in a face-to-face meeting. Thanks!
