### ISSUE TITLE
Import with chroma sits idle for many minutes

### ISSUE THREAD

**Issue by scruloose** [beetbox/beets#3433]
### Problem

Running `beet -v import <dir>` with `chroma` plugin set to `auto: yes:`
* `<dir>` is a single album and has a match in the MusicBrainz database.
* Terminal output gets as far as `Sending event: import_task_start`
* Polling the cpu usage of the import with a Bash loop executing `ps -q $(pgrep beet) -o %cpu=` once per second shows a spike of CPU usage for the first few seconds, then it quickly drops off. 45 seconds in, it's below 10% and stays there.
* Nothing changes for ~10 minutes. No further output from beets.
* Then suddenly a flurry of activity! `Looking up <dir>`, `Searching for discovered album ID`, `Requesting MusicBrainz release`... all the way up to prompting with a candidate. All of this happens in a handful of seconds.

If I import the same album with `chroma` auto-fingerprinting disabled, and then run `beet fingerprint` on it, it runs at a steady CPU usage of about 115% and completes in less than 30 seconds.

Running an import on a folder of singletons results in erratic long pauses, with a wait of a couple of minutes between tracks sometimes, but confirmation prompts coming as fast as I can address them other times. CPU usage hovers around 5% the whole time.

`beetslog.txt` shows nothing but two timestamped entries showing when the import started and finished.

I fully expect chroma's acoustid fingerprinting to take some time, but by my understanding that should be a CPU-bound process, probably taking a few seconds per track, not minutes of waiting with the system mostly idle.
It's behaving as if it were waiting for a lock or a network resource to become available or something, but only when chroma fingerprinting is enabled.

### Setup

* OS: Debian Buster
* Python version:  3.7.3
* beets version: 1.4.7
* Turning off plugins made problem go away (yes/no): yes, disabling `chroma` or setting it to `auto: no` 

System is a KVM virtual machine using native `.qcow2` storage volume via `virtIO` driver. Both the input dir and the beets library are in the same volume, which resides on an internal SATA drive on the host system. So the storage is essentially a single internal HD.

Edited to add: this seems *very* similar to what's described in [this post](https://discourse.beets.io/t/chroma-auto-suddenly-slow/996) on the Discourse forum.

My configuration (output of `beet config`) is:

    import:
        move: yes
        write: yes
        log: beetslog.txt
        languages: en fr de es
        none_rec_action: skip
        duplicate_action: ask
    asciify_paths: yes
    art_filename: albumart
    pluginpath: ~/beets/myplugins

    ui:
        color: yes

    plugins: 'fetchart scrub convert lastgenre duplicates missing chroma primaryartistpath'

    paths:
        singleton: $primary_artist_sort/00 - Loose Tracks/$artist - $title
        comp: Compilations/$original_year - $album [${format}]/$track $title
        albumtype:soundtrack: Soundtracks/$year - $album [${format}]/$track $title
        default: $primary_albumartist_sort/${albumtype}/$original_year - $album [${format}]/$track $title
    replaygain:
        backend: gstreamer
        overwrite: yes
    chroma:
        auto: yes
    lastgenre:
        auto: no
        whitelist: yes
        min_weight: 10
        count: 1
        fallback:
        canonical: no
        source: album
        force: yes
        separator: ', '
        prefer_specific: no
    duplicates:
        album: no
        checksum: ''
        copy: ''
        count: no
        delete: no
        format: ''
        full: no
        keys: []
        merge: no
        move: ''
        path: no
        tiebreak: {}
        strict: no
        tag: ''
    convert:
        dest:
        pretend: no
        threads: 2
        format: mp3
        formats:
            aac:
                command: ffmpeg -i $source -y -vn -acodec aac -aq 1 $dest
                extension: m4a
            alac:
                command: ffmpeg -i $source -y -vn -acodec alac $dest
                extension: m4a
            flac: ffmpeg -i $source -y -vn -acodec flac $dest
            mp3: ffmpeg -i $source -y -vn -aq 2 $dest
            opus: ffmpeg -i $source -y -vn -acodec libopus -ab 96k $dest
            ogg: ffmpeg -i $source -y -vn -acodec libvorbis -aq 3 $dest
            wma: ffmpeg -i $source -y -vn -acodec wmav2 -vn $dest
        max_bitrate: 500
        auto: no
        tmpdir:
        quiet: no
        embed: yes

        paths: {}
        no_convert: ''
        never_convert_lossy_files: no
        copy_album_art: no
        album_art_maxwidth: 0
    missing:
        count: no
        total: no
        album: no
    fetchart:
        auto: yes
        minwidth: 0
        maxwidth: 0
        enforce_ratio: no
        cautious: no
        cover_names:
        - cover
        - front
        - art
        - album
        - folder
        sources:
        - filesystem
        - coverart
        - itunes
        - amazon
        - albumart
        google_key: REDACTED
        google_engine: 001442825323518660753:hrh5ch1gjzm
        fanarttv_key: REDACTED
        store_source: no
    scrub:
        auto: yes

**Comment by sampsyo** [comment]
Well, that's interesting! I don't immediately have any clear theories about why this would be happening.

As background, the plugin (indirectly) uses the [audioread](https://github.com/beetbox/audioread) library to decode audio. That library can use several different backends for decoding. Do you know which codec it might be using on your system? GStreamer or ffmpeg, for example?

**Comment by scruloose** [comment]
I *think* it's using GStreamer. I know for sure that I have GStreamer installed, and when I enable the replaygain plugin I have it configured to use GStreamer. But of course GStreamer pulled in ffmpeg as a dependency, so both are installed on the system.

Naive question, but is there an easy way to check for sure which one audioread is actually using? If there are debug flags I can set to get detailed logs from audioread and/or the backend codec, I'm happy to do give that a try.

On a loosely related note, is there a log-level setting somewhere for beets, or an option to  redirect the output of the verbose flag to the log? Rather than have my interactive import session drowned in -v or -vv output (making it hard to tell when I'm supposed to be responding to a prompt), I'd love to dump all the debug output into the log file instead, if that's an option.

**Comment by sampsyo** [comment]
It is, unfortunately, pretty hard to tell. The design of the audioread library tries to be as transparent as possible. However, you can try running [decode.py](https://github.com/beetbox/audioread/blob/master/decode.py), which does print out the name of the selected backend. Experimenting with this script in isolation might also help diagnose whether the delay comes from reading the audio or something else, like the fingerprinting process itself.

**Comment by scruloose** [comment]
Okay, I have done a little playing around with that script, and the preliminary result surprised me a little: from one mp3 to another, it sometimes picks the `gstdec` backend and sometimes `ffdec`. It does seem to be consistent about which one it prefers for which file, though, so I wonder whether that has to do with quirks of the metadata or CBR vs VBR encoding, or something along those lines.

Regardless of that little quirk, it doesn't appear that audioread is to blame for the delays. Running decode.py in a loop over a directory of 25 mp3 files completes in ~2 minutes, with CPU usage bouncing around a bunch but averaging 65%. I've done several runs, and the total time and average CPU usage varied by less than 1%.

**Comment by sampsyo** [comment]
That's interesting! The audioread library uses a sort of "cascade," so it tries one backend and, if it fails, moves on to the next one. So a CBR/VBR difference could matter, for example, if one backend has limited codec support.

The second finding is disappointing, however—that would have been a convenient excuse. Another random idea is that the plugin might be generating lots of spurious MusicBrainz requests, which would be slow and low-CPU because it's bottlenecked on the MB rate limiting. Is there any way to reproduce the problem for a single album in verbose mode and see at which point the log messages "hang"?

**Comment by scruloose** [comment]
Here's another interesting thing: I can't reproduce it at all now! Importing the same album from the same directory location (on the same system, obviously), using the same config (except `chroma`'s  `auto:` has been switched back and forth from 'yes' to 'no' a few times along the way)... Now it works as it should. In addition to `chroma`, I've re-enabled the `replaygain`, `discogs`, and `fromfilename` plugins (which were enabled when I first saw the delay and disabled during troubleshooting), and it chews through an 11-track album in ~1m 15s at an average CPU usage of ~60%.

Maybe it depends on the phase of the moon... 😉

This is bad news for isolating the bug, but good news for my plans to import a sprawling mess of mp3s into beets.

If & when the issue comes up again, I'll come back with details on exactly where in process it hangs, but if I don't add anything to this thread for ages, that's why.

**Comment by regagain** [comment]
I was facing the same issue, and even though I didn't pitch in I've been following the discussion closely.

I can't reproduce it either since today. I didn't change my configuration or anything else since my last import (about a week ago).

**Comment by regagain** [comment]
For what it's worth: I've not seen this issue since my last comment.
