### ISSUE TITLE
multidisc album and fetchart cover location

### ISSUE THREAD

**Issue by lbesnard** [beetbox/beets#3434]
### Use case
When importing a multidisc album, fetchart stores by default the cover in the CD1 folder. how to get fetchart to store the cover.jpg to the main folder of the album as well as the sub-folders (CD1, CD2...).

My use case is using airsonic (alongside dsub) as the media player. The app always looks for the cover in the folder where the tune is stored.

**Comment by sampsyo** [comment]
Please see https://github.com/beetbox/beets/issues/231.
