### ISSUE TITLE
[Q] Fix previously wrongly tagged tracks (Blindly using MB existing IDs)

### ISSUE THREAD

**Issue by Extarys** [beetbox/beets#3443]
I'm trying to use beets to...
detect audio signature and check if it makes sense with the current track title/mb ID.

Last time I cleaned up my library I used Picard. In the last week, I noticed some tracks where wrongfully tagged by Picard as something else (Romeo and Juliet Soundtrack as a heavy metal group for example).

I'm half way through my library (Now at the letter M). Is it possible to use beets to check and compare existing (and future) tracks during import to make sure they are what they are and not just blindly use current MB IDs?

**Comment by sampsyo** [comment]
The beets importer does not have a mode in which it "blindly" trusts MBIDs. It always uses a combination of factors, including the MBIDs, the other metadata, track lengths, and (if the plugin is enabled) the Chromaprint acoustic fingerprint.

Maybe you'd like to try the `-t` or `timid` mode, which never automatically accepts any match and always gives you an interactive option?

**Comment by Extarys** [comment]
Yes I started with timid mode but it took too much time :laughing: but for each letter (A, B, C) there is at least one song disappearing that I cannot find anymore lol.

I activated the logs so I can see which one was misplaced but you reassured me and maybe it was picard who misidentified it as something and beet got it right and I think something is missing while it was just labelled wrong in the first place. I have a pretty exotic library and I didn't listen to everything so...

Thanks for your input, as always :heart:
