### ISSUE TITLE
Beatport Albums not found

### ISSUE THREAD

**Issue by Lysergi** [beetbox/beets#3456]
I have lots of music from Beatport and I'm trying to tag it with the beatport plugin, but beets mostly displays wrong albums from MusicBrainz or sometimes Beatport, but all of them are aviable on Beatport.

https://pastebin.com/HdqHuiJ4

Running this command in verbose (`-vv`) mode:
https://pastebin.com/aGPShSww

### Setup

* OS: Win10
* Python version: 3.8.0
* beets version: 1.4.9
* Turning off plugins made problem go away (yes/no): no

My configuration (output of `beet config`) is:

directory: E:/DownloadsVM/testing
library: C:/Users/1312/Documents/musiclibrary.db
import:
    copy: no
plugins: beatport fromfilename

beatport:
   source_weight: 0.7

I'm trying to tag albums from Titan Records (http://classic.beatport.com/label/titan-records/21489)
Before, I tried all releases from this label http://classic.beatport.com/label/dividid/68224 and it worked perfectly, so I'm confused why it doesen't work now.

I'm still a noob with beets, maybe I'm just doing a dumb mistake?

**Comment by sampsyo** [comment]
Hello! Can you link to the exact album you're hoping would match? Have you tried the "enter Id" option to force the match? Can you please include the verbose output, as the issue template suggests?

**Comment by Lysergi** [comment]
http://classic.beatport.com/release/diverted-simple/1448847
http://classic.beatport.com/release/courier-energy/2580366

Sorry for forgetting the verbose output:
https://pastebin.com/aGPShSww

**Comment by sampsyo** [comment]
Cool! And how about the other thing: have you tried pasting the IDs into the "enter Id" prompt?

**Comment by sampsyo** [comment]
Hmm,. this verbose output doesn't indicate that the Beatport plugin is working at at all. Can you try typing `beet version`?

**Comment by Lysergi** [comment]
Yes I have tried that and it works but with big folders this would take a very long time. 

C:\Users\1312>beet version
beets version 1.4.9
Python version 3.8.0
plugins: beatport, fromfilename

**Comment by sampsyo** [comment]
Strange! It really seems like this is probably "Beatport's fault": i.e., the search engine is for some reason not finding the "right" matches for these albums. That's hard for us to do anything about!

One small thing you could try: the Beatport plugin has changed significantly in the last few weeks. Can you try running beets from the latest source to see if anything more interesting appears in the logs?

Aside from this, I'm afraid there's not much that's even possible for us to do.

**Comment by Lysergi** [comment]
Thanks for your help.
I tried it with more different albums and it works fine with almost all of them. It looks like the label/albums were part of the problem.
