### ISSUE TITLE
Append operator in modify command

### ISSUE THREAD

**Issue by Aquan1412** [beetbox/beets#3464]
Currently the modify command replaces any existing metadata for the given field. It would be nice if there was an alternative mode, that allowed to merely append the new metadata to the field. Depending on the implementation it might also be useful to have a second flag, --delimiter, to specify which delimiter will be used between the original metadata and the appended part.

Use case:
I mostly use the modify command fo two things: 
1) adding additional genres to a title while maintaining the original genres from the lastgenre plugin
2) adding custom fields to a title, mostly to coordinate smart playlists. These keywords indicate for example the mood of the title or certain characteristics I use to build playlists. I often add additional keywords over time.

For both use cases I have to adjust the modify command for every single title to preserve existing metadata. This makes it tedious to modify multiple files and prohibits batch processing.

**Comment by sampsyo** [comment]
Interesting! Seems like something we could do with the "formatted modify" proposal, #488. For example:

```
$ beet modify foo genre='$genre new_genre'
```

What do you think about exploring that?

If that seems too verbose, I think I'd prefer changing the "modification" syntax rather than adding a CLI flag. The syntax would look like `genre+='new_genre'`. This way, the "append" semantics are attached to an individual field instead of being global for an entire modification.

**Comment by Aquan1412** [comment]
Interesting, seems I missed that proposal. I like both approaches, the "formatted modify" would definitely be more versatile, since you could also include values from other fields, and also it wouldn't be necessary to set a "global" delimiter, as you could just adjust the command from 
`beet modify foo genre='$genre new_genre'`
to 
`beet modify foo genre='$genre, new_genre'` 
or something like that.
However, I believe your second proposal is closer to what I intended. To me it seems more straight forward, and it would probably be easier to allow for empty fields. Because I'm not sure how you would catch an empty field with the "formatted modify"? If `$genre` is empty, the entry would probably end up with surplus whitespace or, if you used another delimiter, with surplus comma or semicolons...
But in general I think both approaches could solve my problem.

**Comment by sampsyo** [comment]
Cool; sounds good! I will mark this as a feature request because it sounds interesting and has that one advantage about delimiters you mentioned. But I think it would be a good idea to tackle "formatted modify" first because it covers so many related use cases.

**Comment by Aquan1412** [comment]
Great, nice to hear.

**Comment by JOJ0** [comment]
Should we close this @Aquan1412 @sampsyo ? I think since "formatted modify" is implemented there is not much need for this.

**Comment by Aquan1412** [comment]
I'm fine with closing the issue, my original use case is covered by the "formatted modify". Thanks!

**Comment by phirestalker** [comment]
What if you are modifying multiple files and one of them does not already have a value? This would make its value ", tag". Is there no way for it to check if the tag is there first or something. The best would be if it made sure not to add a tag twice, and had a method to remove a tag. Is there any way to do this? Should it just be a plugin?

**Comment by JOJ0** [comment]
@phirestalker Try asking in the discussion q&a section, maybe someone has an idea how to solve this smartly with the current featureset and some shell magic.
