### ISSUE TITLE
Add a way to know where the tags come from.

### ISSUE THREAD

**Issue by flovanc** [beetbox/beets#3469]
Hello. 
Since it is impossible to deactivate musicbrainz, is there a way to redirect the tagged music to different folders depending on where the tags come from? simply so that you can put the files processed by musicbrainz aside. this could help a lot of users who request a way that music is only handled by plugins.

**Comment by sampsyo** [comment]
The $data_source field contains this information.

**Comment by flovanc** [comment]
My Bad 😉. Enjoy the beer.
