### ISSUE TITLE
replaygain: bs1770gain v0.6.0 XML output can't be parsed

### ISSUE THREAD

**Issue by ybnd** [beetbox/beets#3479]
### replaygain: bs1770gain v0.6.0 XML output can't be parsed

Running `beet -vv replaygain` with the `bs1770gain` backend results in 
```
replaygain: analyzing Nyul -  When The Path Fades - Floatfall
replaygain: executing bs1770gain --ebu --xml -p /home/ybnd/code/beets/library/Nyul/2014 -  When The Path Fades/05 Floatfall.flac
replaygain: analysis finished: <!-- scanning 1 -->
<!-- analyzing ... -->
<bs1770gain norm="-23.00">
  <track total="1" number="1" file="05 Floatfall.flac">
    <integrated lufs="-10.99" lu="-12.01"/>
    <sample-peak spfs="-0.10" amplitude="0.99"/>
  </track>
  <integrated lufs="-10.99" lu="-12.01"/>
  <sample-peak spfs="-0.10" amplitude="0.99"/>
</bs1770gain>
<!-- done. -->

replaygain: ReplayGain error: The bs1770gain tool produced malformed XML. Using version >=0.4.10 may solve this problem.
```
for all tracks.

1. The actual XML output `text` that gets parsed at https://github.com/beetbox/beets/blob/ca3142b1d92d177a2d789775a4ff2ee5569b9ba6/beetsplug/replaygain.py#L318-L324 gets spliced with some progress percentages 
    ```
    b'<!-- scanning 1 -->
    <!-- analyzing ... -->
    <bs1770gain norm="-23.00">
      <track total="1" number="1" file="05 Floatfall.flac">
    0%\x08\x080%\x08\x080%\x08\x080%\x08\x08 ...
    ... 100%\x08\x08\x08\x08    \x08\x08\x08\x08    <integrated lufs="-10.99" lu="-12.01"/>
        <sample-peak spfs="-0.10" amplitude="0.99"/>
      </track>
      <integrated lufs="-10.99" lu="-12.01"/>
      <sample-peak spfs="-0.10" amplitude="0.99"/>
    </bs1770gain>
    <!-- done. -->'
    ```
2. The parser expects `factor` instead of `amplitude` in the `sample-peak` element, which *used to be* what the output looked like based on https://github.com/beetbox/beets/issues/2983): https://github.com/beetbox/beets/blob/ca3142b1d92d177a2d789775a4ff2ee5569b9ba6/beetsplug/replaygain.py#L296-L299
    

### Setup

* OS: 5.4.14-2-MANJARO
* Python version: 3.8.1
* beets version: [current master](https://github.com/beetbox/beets/tree/ca3142b1d92d177a2d789775a4ff2ee5569b9ba6)
* Turning off plugins made problem go away (yes/no): n/a

My configuration (output of `beet config`) is:

```yaml
replaygain:
    backend: bs1770gain
    method: ebu
```

with 

```
$ bs1770gain --version
bs1770gain 0.6.0, Copyright (C) Peter Belkner 2014-2019.
```

**Comment by ybnd** [comment]
I can solve the progress percentage issue with
```python
temp = text.decode('ascii')
while '\x08' in temp:
    temp = re.sub('[^\x08]\x08', '', temp)
parser.Parse(text, True)
```
but this still leaves the second issue and the following error
```
start_element_handler
    state['peak'] = float(attrs[u'factor'])
KeyError: 'factor'
```

**Comment by ybnd** [comment]
With other `bs1770gain` methods, the `integrated` element includes `db` instead of `lu`

* default, `method: replaygain`
    ```
  <integrated dbfs="-10.99" db="-7.01"/>
  <sample-peak dbfs="-0.10" amplitude="0.99"/>
    ```
* `method: atsc`
    ```
  <integrated dbfs="-10.99" db="-13.01"/>
  <sample-peak dbfs="-0.10" amplitude="0.99"/>
    ```
resulting in the following error
```
start_element_handler
    state['gain'] = float(attrs[u'lu'])
KeyError: 'lu'
```

**Comment by sampsyo** [comment]
Thanks for tracking it down; happy to merge a patch that adapts to the new names.
