### ISSUE TITLE
A new plugin was born: beets-bpmanalyser

### ISSUE THREAD

**Issue by adamjakab** [beetbox/beets#3490]
### News
Hi! I am an obsessive music geek. I realised this only since I installed Beets. I greatly enjoy this application and it helped me a great deal to sort out my music library. I played around the application and most of the plugins - actually the last two days I didn't do much else ;)

Anyways, I thought that with the tempo(bpm) information on the songs stored on acousticbrainz I would have all songs with tempo information once I imported my library. Only later I realised that this was not the case and I still have a good 30% of my music without tempo information. Since I am also a runner and I choose the music I take with me based on the type of training I am going out to do, this info for me is crucial (...yes,  I know, I am obsessive ... ;)). 

So I set out to make two plugins:
- a tempo(bpm) analyser for media files (beets-bpmanalyser)
- a file song exporter made for runners (beets-goingrunning)

While the second one may be interesting only for a limited number of people, the first one `beets-bpmanalyser` might be interesting for many people also for other reasons.

The good news is that I already created this plugin (`beets-bpmanalyser`) and it is available on [PyPi](https://pypi.org/project/beets-bpmanalyser/) and [Github](https://github.com/adamjakab/BeetsPluginBpmAnalyser).

### Question
I would like this plugin to be listed on the Plugins page under the [Other Plugins](https://beets.readthedocs.io/en/stable/plugins/index.html#other-plugins) section. I also thought about adding it as an internal plugin, but it has two quite heavy dependencies: [numpy](https://pypi.org/project/numpy/) and [aubio](https://pypi.org/project/aubio/) and maybe keeping it optional is a better choice. So, can you please add it? Thanks

PS: I realise this is not the best place for this - it is more like a forum post - but I don't know where else to post it.

**Comment by sampsyo** [comment]
Awesome! I'm glad everything's going well for you so far!

This looks pretty rad, and we'd be happy to add a link to that "Other Plugins" section. Please open a pull request and we'll merge it! You can find the source under `docs`.

Just for fun, I'm going to link to the included bpm plugin, which is obviously very different but worth mentioning in this context: https://beets.readthedocs.io/en/stable/plugins/bpm.html

Also, while discussion issues like this are fine, we do also have a forum, if you're interested: https://discourse.beets.io

**Comment by adamjakab** [comment]
Super! Thanks for the forum link.

**Comment by sampsyo** [comment]
Fixed in #3491.
