### ISSUE TITLE
modifications on documentations on beets.readthedocs.io

### ISSUE THREAD

**Issue by adamjakab** [beetbox/beets#3496]
In reference to the merged PRs #3491 and #3494 - I cannot see the modifications to the plugin index page on https://beets.readthedocs.io/en/stable/plugins/index.html. Is it just a question of time? Thanks

**Comment by GuilhermeHideki** [comment]
The /stable/ should be the latest pushed tag (1.4.9), from what I know.

The footer on https://beets.readthedocs.io/en/latest/plugins/index.html says "© Copyright 2016, Adrian Sampson Revision d43d54e2.". I don't know when this should be updated to the last commit

**Comment by adamjakab** [comment]
Thanks @GuilhermeHideki, I see. I have not worked with readthedocs.io before and for some reason I imagined that each merged pull request to the master branch  was automatically appearing there.

**Comment by sampsyo** [comment]
Hi, @adamjakab—try `/latest/` to see the current docs from master. (One of the nice things about RTD is that it preserves a snapshot of the docs for each version, so users don't get confused about documented features that don't exist in the released code, for example.)
