### ISSUE TITLE
`flac -t` for flacs on import to check for corruption

### ISSUE THREAD

**Issue by sneak** [beetbox/beets#3512]
### Use case

I'm trying to use beets to... import flacs that might be corrupt.

### Solution

Beets should probably test flacs (`flac -t`) on import to make sure they're not corrupt.

### Alternatives

This could be done with a plugin, of course.  For now I am just running a `find . -type f -iname '*.flac' -print0 | xargs -0 -n 1 -P 64 flac --silent -t 2>&1  | tee ~/checklog.txt` on my whole library periodically but it would be nice if it could happen on import.

**Comment by sampsyo** [comment]
Yo! How about the hook plugin?
https://beets.readthedocs.io/en/stable/plugins/hook.html

It lets you run any command you like on any event in beets.

**Comment by sneak** [comment]
I can dig into the source if you don't know, but does `item_imported` in the hook plugin fire before or after an autoconvert?  If I am importing an alac but it converts to a flac I don't need to test it, but if I am importing a flac (regardless of what the conversion destination is) it should be checked.

**Comment by jackwilsdon** [comment]
Looking at the code, I'm pretty sure `item_imported` runs after everything — the item is done when this event is emitted. You'll need to add some code to your hook to ensure that you only run on FLAC files, but I don't think that's too difficult.

**Comment by sneak** [comment]
I suppose I can implement this with that plugin, but it would be cool if beets would do it anyway on importing flacs; I can't imagine anyone who wants corrupted files in their library.

**Comment by sneak** [comment]
Nevermind.  I'll just manually test all flacs in an import batch before I import them.

**Comment by sneak** [comment]
For anyone else who finds this thread: the `beets-check` plugin does what I wanted, and not just for flacs (although it does do a `flac --test` on each flac on import):

https://github.com/geigerzaehler/beets-check
