### ISSUE TITLE
A way to auto-approve candidate if certain treshold is passed, ortherwise reject

### ISSUE THREAD

**Issue by chromafunk** [beetbox/beets#3522]
Is there a way to automatically apply when prompted if a certain % threshold is set ? 

Like, for example, if the candidate > 80%, approve, otherwise, don't do anything with this album.

I am trying to automate the import / meta-tagging and I don't mind not adding albums that don't pass 70-80% threshold, I don't want to be asked about it. Just do it if say candidate > 70% or don't do it.

The goal is to have this running in background and avoid having to mess with prompts.

Is there a way to do it while running beets from a Python script ?

Also, is there a way to import beets as a library and automate this process, maybe via parsing the results from candidates,etc ?

Thanks!

**Comment by wisp3rwind** [comment]
I guess you're searching for the [`-q` (quiet) ](https://beets.readthedocs.io/en/stable/reference/cli.html#import) option of the importer, also see the [importer options](https://beets.readthedocs.io/en/stable/reference/config.html#importer-options) and the [autotagger matching options](https://beets.readthedocs.io/en/stable/reference/config.html#autotagger-matching-options).

> Also, is there a way to import beets as a library and automate this process, maybe via parsing the results from candidates,etc ?

In principle, nothing hinders you from importing beets, cf. the test cases and the `ui` module. AFAICT, this is completely unsupported though. The internal API is neither documented nor are there any stability guarantees. The closest supported thing is writing plugins that hook into the various import stages.

**Comment by sampsyo** [comment]
Indeed, quiet mode is what you're looking for!

See #3403 and the old mailing list thread linked therein for discussion on using beets as a library.
