### ISSUE TITLE
`beet move` doesn't move existing album art files

### ISSUE THREAD

**Issue by jallbrit** [beetbox/beets#3528]
Let's say I have an album that's already in the beets database, but I change the default `path` to something else. Now, beets is supposed to move the existing folders to fit the new naming scheme.

However, it leaves behind the album art in the old folder, thus leaving a shell of the old folder structure with a bunch of `cover.png`s in it, and I have to manually place them in the new, correct location.

If it is relevant, I downloaded this album art myself (as opposed to using a beets plugin).

### Problem

You can see `cover.png` inside the folder, and that there's 140 files in the folder:

```bash
$ ls files/Game/Paper\ Mario_\ The\ Thousand\ Year\ Door/ | grep cover.png
cover.png
$ ls -1 files/Game/Paper\ Mario_\ The\ Thousand\ Year\ Door/ | wc -l
140
```

Running `beet move` doesn't pick up the album art, and only sees 139 items:

```sh
$ beet move -p
Moving 139 items (3758 already in place).
/home/john/Music/files/Game/Paper Mario_ The Thousand Year Door/01 Story of The Thousand Year Door.mp3 
  -> /home/john/Music/files/Yoshito Hirano & Yuka Tsujiyoko/Paper Mario_ The Thousand Year Door/01 Story of The Thousand Year Door.mp3
/home/john/Music/files/Game/Paper Mario_ The Thousand Year Door/03 Title Theme.mp3 
  -> /home/john/Music/files/Yoshito Hirano & Yuka Tsujiyoko/Paper Mario_ The Thousand Year Door/03 Title Theme.mp3
/home/john/Music/files/Game/Paper Mario_ The Thousand Year Door/04 Mail for the Mario Brothers.mp3 
  -> /home/john/Music/files/Yoshito Hirano & Yuka Tsujiyoko/Paper Mario_ The Thousand Year Door/04 Mail for the Mario Brothers.mp3
/home/john/Music/files/Game/Paper Mario_ The Thousand Year Door/05 A New Adventure Begins.mp3 
  -> /home/john/Music/files/Yoshito Hirano & Yuka Tsujiyoko/Paper Mario_ The Thousand Year Door/05 A New Adventure Begins.mp3


... [truncated] ...


  -> /home/john/Music/files/Yoshito Hirano & Yuka Tsujiyoko/Paper Mario_ The Thousand Year Door/137 A Last View at Rogueport.mp3
/home/john/Music/files/Game/Paper Mario_ The Thousand Year Door/138 Here We Go Again.mp3 
  -> /home/john/Music/files/Yoshito Hirano & Yuka Tsujiyoko/Paper Mario_ The Thousand Year Door/138 Here We Go Again.mp3
/home/john/Music/files/Game/Paper Mario_ The Thousand Year Door/139 Staff Roll.mp3 
  -> /home/john/Music/files/Yoshito Hirano & Yuka Tsujiyoko/Paper Mario_ The Thousand Year Door/139 Staff Roll.mp3
/home/john/Music/files/Game/Paper Mario_ The Thousand Year Door/140 Game Over.mp3 
  -> /home/john/Music/files/Yoshito Hirano & Yuka Tsujiyoko/Paper Mario_ The Thousand Year Door/140 Game Over.mp3
```

### Setup

* OS: Debian Testing
* Python version: `3.7.7`
* beets version: `1.4.9`
* Turning off plugins made problem go away (yes/no): no

### Beet config

```yaml
directory: ~/Music/files
library: ~/.cache/beet/musiclibrary.db

ui:
  color: yes

import:
  autotag: no
  move: yes
  languages: en
```

**Comment by sampsyo** [comment]
Indeed; your art needs to be tracked by beets in order to be moved when this happens. You can use the `fetchart` plugin to pick up local art (aside from fetching art from web sources—you can disable those if you like).

**Comment by jallbrit** [comment]
To me, It seems like strange default behavior to completely ignore non-music files inside imported directories. It is my opinion that beets should pick up on possible art files, or at least have a flag to move *all* files inside the imported folder, not just music.

That being said, thank you for pointing this out to me! I did notice the plugin but failed to realize it could be restricted to local art.

**Comment by sampsyo** [comment]
Yes—it is certainly a common request to track arbitrary non-music files in the beets database. A long-standing idea to address that _completely_ is "attachments" (#111), but it's a big job that no one has yet taken on. Separately, the third-party plugin [copyartifacts](https://github.com/sbarakat/beets-copyartifacts) solves most of the problem for most people.
