### ISSUE TITLE
fetchart: Add last.fm source

### ISSUE THREAD

**Issue by jallbrit** [beetbox/beets#3530]
## Use case

When downloading album art via `fetchart`, it would be useful to be able to query [last.fm](https://last.fm). This functionality is present in [airsonic](https://github.com/airsonic/airsonic), and I tried to find how it works and came across [this commit](https://github.com/airsonic/airsonic/commit/72851f072128134f4ef8c103146aa7596735183d) which seems to implement this functionality.

## Solution

The `fetchart` plugin should have a new source called `lastfm` or `last.fm` that queries last.fm.

## Alternatives

For some releases, the sources currently available for album art don't suffice. Thus, the only suitable alternative is to grab the art manually.

**Comment by sampsyo** [comment]
Sounds good! Seems like it shouldn't be that complicated if someone wants to jump in.

**Comment by jackwilsdon** [comment]
I wouldn't mind picking this up - seems rather straighforward.
