### ISSUE TITLE
genius: Tolerate missing lyrics div in Genius scraper

### ISSUE THREAD

**Issue by myfreeweb** [beetbox/beets#3535]
```
  File "/home/greg/.local/lib/python3.7/site-packages/beetsplug/lyrics.py", line 410, in fetch
    return self.lyrics_from_song_api_path(song_api_path)
  File "/home/greg/.local/lib/python3.7/site-packages/beetsplug/lyrics.py", line 376, in lyrics_from_song_api_path
    lyrics = html.find("div", class_="lyrics").get_text()
AttributeError: 'NoneType' object has no attribute 'get_text'
```

Missing error handling when processing lyrics downloads, this shouldn't fail that hard.

**Comment by sampsyo** [comment]
Thanks! Looks like this needs a null check.

**Comment by thejli21** [comment]
Hi, I'm new to open source and this seemed like a newer good first issue. If this fix hasn't been implemented yet could I take a look at it?

**Comment by sampsyo** [comment]
Awesome! Yes, this would be a great place to start! We just need to check whether that value is None and bail out early. Please jump right in! You may find our "Hacking" wiki page helpful:
https://github.com/beetbox/beets/wiki/Hacking

**Comment by odeshpande16** [comment]
Hi, I am working with thejli21 on this issue, but we had a question. We have implemented a fix, but are wondering if you have any recommendations on writing a test to confirm it? I can't seem to find a way to mock a Genius call that would allow us to produce this bug. We looked at the Google tests in test_lyrics.py but it doesn't look like the same approach works for Genius. We would really appreciate any guidance or tips, thank you so much!

**Comment by sampsyo** [comment]
Great! Testing here will be tricky, so it would be OK to merge a fix without exhaustive tests… but if you're motivated to figure it out, all the better.

I do think mocking the `fetch_url` method of `Backend`, as the Google tests do:

```py
@patch.object(lyrics.Backend, 'fetch_url', MockFetchUrl())
```

…could be the right path. The `MockFetchUrl` thing itself is pretty complicated, and uses a set of files pre-fetched by the `lyrics_download_samples.py` script. But you could create a different mock just to hold a contrived sample response that looks like a Genius page. Would that make sense?

**Comment by thejli21** [comment]
We'll try to look into creating a mock for a Genius page. Just to make sure we're on the right path it would be possible to do something like right?
`@patch.object(requests, 'get', NewGeniusPatch())`
Our initial concern was that fetching the html page with requests.get and the parsing the html with BeautifulSoup are both done within Genius.lyrics_from_song_api_path, and we were unsure of how to separate the fetching and the portion we want to test (the parsing).

**Comment by sampsyo** [comment]
Yep, something just like that should do well! Using a "real" Genius page, and then just stripping out all the actual lyrical content, might be a good way to start.
