### ISSUE TITLE
Content Security Policy on discourse is making it hard to visit the forum

### ISSUE THREAD

**Issue by DjSlash** [beetbox/beets#3544]
Hi,

I am trying to visit the forum, but I can't get it to load due CSP:

![2020-04-07-12:13:09](https://user-images.githubusercontent.com/538802/78657614-5222e680-78c9-11ea-8ebe-b87d5f0a74c3.png)

**Comment by sampsyo** [comment]
Huh, that's odd. The forum is run by the fine folks at [Discourse](https://www.discourse.org)—if this persists (e.g., in different browsers), would you mind filing a bug with them?

**Comment by jackwilsdon** [comment]
That CSP error in your console is just from Tridactyl (which I assume you have installed) - the interesting ones are the two JS files that failed to load. Are you still seeing this issue?

**Comment by DjSlash** [comment]
@jackwilsdon Ugh, I wasn't paying attention. I had a few more errors before using a private window, but can't reproduce anymore. 

The issue was happening on multiple browsers, on multiple computers, at different locations. However, the issue has disappeared. So, closing for now.

**Comment by jackwilsdon** [comment]
Sounds like Discourse may have been having issues — glad it's solved!

**Comment by DjSlash** [comment]
In the end it was probably my own connection. It was just a minor symptom, which didn't add up at first. But it became worse later and a lot of connections were getting unstable. It resulted in contacting my ISP and getting a replacement modem.
