### ISSUE TITLE
Trying to set cover image mtime after fetchart

### ISSUE THREAD

**Issue by agross** [beetbox/beets#3547]
#### Problem

I'm trying to set the cover's time by hooking into `art_set`.

The first problem is that `art_set` only receives the album, but not the full path that I could use to query without the risk of ambiguous matches (at least I understand it). I fixed this by setting `format_album: $path`.

With this out of the way, I want to get the mtime that beets stored when it imported the album.

I'm trying to get this bit on the album-level from the library:

```sh
$ beet -vv info --library --format='$mtime' --summarize -- '/Users/agross/Nextcloud/Music/Hird - Moving on'
user configuration: /Users/agross/.config/beets/config.yaml
data directory: /Users/agross/.config/beets
plugin paths: 
Sending event: pluginload
inline: adding item field albumartist_no_va
inline: adding item field maybe_disc
inline: adding item field maybe_soundtrack
artresizer: method is (2, (7, 0, 10), False)
library database: /Users/agross/.config/beets/library.db
library directory: /Users/agross/Nextcloud/Music
Sending event: library_opened
acoustid_fingerprint: 
         acoustid_id: 
               added: 2008-09-26 14:40:38
               album: Moving on
            album_id: 184
         albumartist: Hird
  albumartist_credit: 
   albumartist_no_va: Hird - 
    albumartist_sort: 
       albumdisambig: 
         albumstatus: 
          albumtotal: 0
           albumtype: 
            arranger: 
              artist: Hird
       artist_credit: 
         artist_sort: 
             artpath: /Users/agross/Nextcloud/Music/Hird - Moving on/cover.jpg
                asin: 
            bitdepth: 0
             bitrate: 192kbps
                 bpm: 0
          catalognum: 
            channels: 2
            comments: 
                comp: False
            composer: 
       composer_sort: 
             country: 
                 day: 00
                disc: 00
           disctitle: 
           disctotal: 00
             encoder: 
            filesize: [various]
              format: MP3
               genre: 
            grouping: 
                  id: [various]
         initial_key: 
               label: 
            language: 
              length: [various]
            lyricist: 
              lyrics: 
          maybe_disc: 
    maybe_soundtrack: 
    mb_albumartistid: 
          mb_albumid: 
         mb_artistid: 
   mb_releasegroupid: 
   mb_releasetrackid: 
          mb_trackid: 
               media: 
               month: 00
               mtime: 2008-09-26 14:40:38
        original_day: 00
      original_month: 00
       original_year: 0000
     r128_album_gain: 000000
     r128_track_gain: 000000
releasegroupdisambig: 
       rg_album_gain: 0.0
       rg_album_peak: 0.0
       rg_track_gain: 0.0
       rg_track_peak: 0.0
          samplerate: 44kHz
              script: 
           singleton: False
               title: [various]
               track: [various]
          tracktotal: 00
                year: 0000
Sending event: cli_exit
```

Unfortunately this returns all the information about this album, and not just the mtime.

Running the same command without `--summarize` yields the expected results, but for each of the album's tracks:

```sh
$ beet -vv info --library --format='$mtime' -- '/Users/agross/Nextcloud/Music/Hird - Moving on'
user configuration: /Users/agross/.config/beets/config.yaml
data directory: /Users/agross/.config/beets
plugin paths:
Sending event: pluginload
artresizer: method is (2, (7, 0, 10), False)
inline: adding item field albumartist_no_va
inline: adding item field maybe_disc
inline: adding item field maybe_soundtrack
library database: /Users/agross/.config/beets/library.db
library directory: /Users/agross/Nextcloud/Music
Sending event: library_opened
2008-09-26 14:40:38

2008-09-26 14:40:38

2008-09-26 14:40:38

2008-09-26 14:40:38

2008-09-26 14:40:38

2008-09-26 14:40:38

2008-09-26 14:40:38

2008-09-26 14:40:38

2008-09-26 14:40:38
Sending event: cli_exit
```

### Setup

* OS: macOS
* Python version: 1.4.9
* beets version: 3.7.7
* Turning off plugins made problem go away (yes/no): no

**Comment by agross** [comment]
As a workaround I'm using `| head -n1`:

```
hook:
  hooks:
    # format_album must be set to $path or something uniquely queryable, because
    # this is the only argument we receive.
    - event: art_set
      command: |-
        sh -c '
          set -e
          mtime="$(beet info --library --format "\$mtime" -- "{album}" | head -n1)"
          ts="$(date -d "$mtime" +%s)"
          cover="$(beet info --library --format "\$artpath" -- "{album}"| head -n1)"
          echo "$mtime = $ts for $cover"
          touch -m --date @$ts -- "$cover"
        '
```

It would be nice to receive the album ID (unique item to query) and the summarized `mtime` and `artpath`.

**Comment by sampsyo** [comment]
Hi! Because the `album` argument is an `Album` object, you don't just have to format it as a string and get the default formatting information about it. Can you try `{album.artpath}` to get the filename directly? Or `{album.path}` to get its enclosing directory?

**Comment by agross** [comment]
Hi @sampsyo,

wow, I didn't expect to receive a real object in the hook! The `artpath` solves the search for the cover. But unfortunately, the `Album` does not expose its `mtime`. So I am still required to query this with at least `beet info --library --format "\$mtime" -- "album_id:{album.id}" | head -n1`.

The question remains: Why are `--summarize` and `--format` kind of mutually exclusive? Or are there better alternatives?

Current hook:

```yaml
hook:
  hooks:
    - event: art_set
      command: |-
        sh -c '
          set -e

          mtime="$(beet info --library --format "\$mtime" -- "album_id:{album.id}" | head -n1)"
          if [ -z "$mtime" ]; then
            >&2 printf "No mtime for {album}\n"
            exit 1
          fi

          ts="$(date -d "$mtime" +%s)"

          printf "$mtime = $ts for {album.artpath}\n"
          touch -m --date @$ts -- "{album.artpath}"
        '
```

**Comment by wisp3rwind** [comment]
> wow, I didn't expect to receive a real object in the hook! The `artpath` solves the search for the cover. But unfortunately, the `Album` does not expose its `mtime`. So I am still required to query this with at least `beet info --library --format "\$mtime" -- "album_id:{album.id}" | head -n1`.

The `Album` exposes all of its attributes, however beets treats `mtime` as an `Item`-level field. An album's items can be accesed using the `Album.items()` method, however, that is not going to work in the format string I suppose.  I'm not familiar with the hooks plugin, really, but I guess that currently there is no easy way to obtain the mtime from the album object only.

Maybe, the hooks plugin could be extended to use Pythons `f""` strings if running a sufficiently recent Python, which would allow a format string like `{next(iter(album.items())).mtime}`. Or it might add custom field akin the `inline` plugin (probably the better option, for sharing code and since it is more powerful).

> The question remains: Why are `--summarize` and `--format` kind of mutually exclusive? Or are there better alternatives?

I guess that should be considered a bug, https://github.com/beetbox/beets/blob/master/beetsplug/info.py#L213 forgets to pass the `fmt` option.

**Comment by sampsyo** [comment]
> Or it might add custom field akin the `inline` plugin (probably the better option, for sharing code and since it is more powerful).

Yeah, that might be the best way—as a bonus, you get to use the inline-defined field in other contexts too, not just the hook script.

> I guess that should be considered a bug, https://github.com/beetbox/beets/blob/master/beetsplug/info.py#L213 forgets to pass the `fmt` option.

Indeed; looks like a bug to me!

**Comment by agross** [comment]
Alright, thank you both for the clarification. Should I create separate issues for the format bug and the feature request?

**Comment by wisp3rwind** [comment]
I'll attempt a quick fix of the format bug (should be a one-liner, but I don't use the `info` command myself, so I'm not super familiar with it and things might be more complicated). So need for a new issue there. If you could open a feature request about more powerful format syntax for the hooks plugin, that'd be perfect :tada:
