### ISSUE TITLE
Info request: next release

### ISSUE THREAD

**Issue by alebianco** [beetbox/beets#3555]
Hi,
sorry for opening an issue for this but I can't find the info elsewhere.

I just started using the project and, after spending a considerable amount of time to configure it to my likings, it's great!

I was just wondering why there hasn't been any new release since last year despite the codebase being very active.

Is some major work on the project in progress and it just takes time?
Is it safe to use the master branch? Do the documented configurations work with it?

Thank you very much for the great work.

**Comment by jackwilsdon** [comment]
[This discourse thread should hopefully answer your questions](https://discourse.beets.io/t/what-is-the-timeframe-for-the-v1-5-0-release/1145) (and is a generally better place to discuss this I think).
