### ISSUE TITLE
Beets Web plugin raises TypeError when filtering by IDs

### ISSUE THREAD

**Issue by bartkl** [beetbox/beets#3565]
Hi,

It's been quite a while since I've last used the Web plugin, and now that I do I immediately get the following issue.

### Problem

Running this command in verbose (`-vv`) mode:

```sh
$ beet -vv web
```

and then requesting some album or item by ID, like `/album/1`, led to this problem:

```
bart@oblomov:/opt/genre-buddy/genre-buddy $ beet -vv web
user configuration: /home/bart/.config/beets/config.yaml
data directory: /home/bart/.config/beets
plugin paths: /opt/whatlastgenre/plugin/beets/beetsplug
Sending event: pluginload
library database: /media/droppie/libraries/music/.config/beets/beets.db
library directory: /media/droppie/libraries/music
Sending event: library_opened
web: Enabling CORS with origin: *
 * Serving Flask app "beetsplug.web" (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
 * Running on http://0.0.0.0:8337/ (Press CTRL+C to quit)
[2020-04-25 12:27:37,452] ERROR in app: Exception on /album/1 [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/flask/app.py", line 2446, in wsgi_app
    ctx.push()
  File "/usr/local/lib/python3.7/dist-packages/flask/ctx.py", line 396, in push
    self.match_request()
  File "/usr/local/lib/python3.7/dist-packages/flask/ctx.py", line 350, in match_request
    result = self.url_adapter.match(return_rule=True)
  File "/usr/local/lib/python3.7/dist-packages/werkzeug/routing.py", line 1873, in match
    rv = rule.match(path, method)
  File "/usr/local/lib/python3.7/dist-packages/werkzeug/routing.py", line 902, in match
    new_path = "|".join(self.build(result, False))
  File "/usr/local/lib/python3.7/dist-packages/werkzeug/routing.py", line 1040, in build
    return self._build(**values)
  File "<werkzeug routing>", line 1, in <builder:'/album/<idlist:ids>'>
  File "/usr/local/lib/python3.7/dist-packages/beetsplug/web/__init__.py", line 172, in to_url
    return ','.join(value)
TypeError: sequence item 0: expected str instance, int found
192.168.178.22 - - [25/Apr/2020 12:27:37] "GET /album/1 HTTP/1.1" 500 -
```
Just to try out, I changed that line 172:

```python
    return ','.join(value)
```

to:

```python
    return ','.join(str(value))
```

and this fixes the problem. This possible bug is part of the `IdListConverter`, so it applies also to other requests (such as `/item/<id>`).

If this is indeed a bug, I'd be amazed since it regards such basic functionality that I would suspect no one still uses this plugin. Anyways, I would love to hear what is the proper way forward from here.

Thanks!
Bart

### Setup

* OS: Raspbian Buster (Raspberry Pi 3B+)
* Python version: 3.7.3
* beets version: 1.4.9
* Turning off plugins made problem go away (yes/no): 

My configuration (I've selected parts that I think are relevant):

```yaml

web:
    host: 0.0.0.0
    cors: '*'
    port: 8337
    cors_supports_credentials: no
    reverse_proxy: no
    include_paths: no
```

**Comment by nmeum** [comment]
For me this was fixed with d43d54e21cde97f57f19486925ab56b419254cc8

**Comment by bartkl** [comment]
Thanks for that link. That sounds like a slight improvement on my own patch. Now that I know this is known and there's a workaround, I think this issue can be closed (but I'll leave it open in case someone feels it's useful to leave it open).

**Comment by guikubivan** [comment]
Phew, this save my butt. Was debugging this through mopidy and Iris web client, and while there seems to be bugs in Iris communicating with beets, search functionality was broken due to this. Switching my beets docker image to nightly fixed the issue (at least for search within Iris client).
