### ISSUE TITLE
Wrong `albumtotal` on multi-disc albums with missing discs

### ISSUE THREAD

**Issue by dbogdanov** [beetbox/beets#3570]
The `albumtotal` value is wrong for multi-disc albums if some of the discs are missing and _per_disc_numbering_ is enabled.

### Problem

The code that computes `albumtotal` assumes that the total number of tracks on an album is a sum of `tracktotal` for all discs found among the album's items. However, the case when some of the discs are entirely missing (no items at all) is not considered. 

https://github.com/beetbox/beets/blob/master/beets/library.py#L1140

To fix this, `albumtotal` should be assigned in the tagger at the import time directly from the chosen candidate's metadata, [together with `tracktotal`](https://github.com/beetbox/beets/blob/master/beets/autotag/__init__.py#L127).

Imagine importing a 2xCD album where one of the CDs is missing.  Here is an example (shortened the info output to keep only relevant fields): 
```
Finding tags for album "Various Artists - Artcore 3: Expressions in Drum & Bass".
Candidates:
1. Various Artists - Artcore 3 - Expressions In Drum & Bass (48.7%) (missing tracks, tracks, id, ...) (Discogs, 2xCD, 1997, UK, React, REACT CD99)
2. Various Artists - Artcore 3 (37.1%) (tracks, id, album, ...) (Discogs, 3xVinyl, 1997, UK, React, REACTLP99)
3. Various Artists - Artcore 3 - Expressions In Drum & Bass (36.2%) (tracks, id, missing tracks, ...) (Discogs, CD, 1997, US, React America, RML66010-2)
4. Dr. S. Gachet, Peshay - Artcore 3 - Expressions In Drum & Bass (35.7%) (tracks, id, missing tracks, ...) (Discogs, CD, 1997, UK, React, REACT CDX99)
5. Dr. S. Gachet, Peshay - Artcore 3 - Expressions In Drum & Bass (33.2%) (tracks, id, missing tracks, ...) (Discogs, Cassette, 1997, UK, React, REACT MC99)
# selection (default 1), Skip, Use as-is, as Tracks, Group albums,
Enter search, enter Id, aBort, eDit, edit Candidates, plaY? 1
Correcting tags from:
    Artcore 3: Expressions in Drum & Bass
To:
    Artcore 3 - Expressions In Drum & Bass
URL:
    https://www.discogs.com/Various-Artcore-3-Expressions-In-Drum-Bass/release/72349
(Similarity: 48.7%) (missing tracks, tracks, id, country) (Discogs, 2xCD, 1997, UK, React, REACT CD99)
CD 2
 * Reincarnation               -> Reincarnation (id)
 * The Bear                    -> The Bear (id)
 * On the Nile                 -> On The Nile (id)
 * Mystical People             -> Mystical People (id, artist)
 * The Sea (PFM remix)         -> The Sea (PFM Remix) (id)
 * Motions (VIP mix)           -> Motions (VIP Mix) (id)
 * Homeland X-Pressive Journey -> Homeland X-Pressive Journey (id)
 * Pulse (VIP mix)             -> Pulse (VIP Mix) (id)
 * F-Jam                       -> F-Jam (id, artist)
 * Ave Maria                   -> Ave Maria (id, artist)
Missing tracks (10/20 - 50.0%):
 ! The Journey                             (#1-1) (6:34)
 ! Stretch (Shogun Remix)                  (#1-2) (7:42)
 ! The Crossing Pt.II (Words)              (#1-3) (6:14)
 ! Expressions Pt.2                        (#1-4) (7:45)
 ! Electric Soul                           (#1-5) (6:16)
 ! Solar Glide                             (#1-6) (7:36)
 ! Death By Sax                            (#1-7) (7:06)
 ! Milk (Goldie's VIP Trash Your Sh*t Mix) (#1-8) (7:43)
 ! Skylab                                  (#1-9) (6:19)
 ! Shadow Boxing                           (#1-10) (7:58)
Apply, More candidates, Skip, Use as-is, as Tracks, Group albums,
Enter search, enter Id, aBort, eDit, edit Candidates, plaY? a

$ beet info "Artcore 3" --library
/.../tagged/Various Artists - 1997 - Artcore 3 - Expressions In Drum & Bass (React) [REACT CD99] #cd/2-01 DJ Die - Reincarnation.flac
               album: Artcore 3 - Expressions In Drum & Bass
         albumartist: Various Artists
          albumtotal: 10
           albumtype: Compilation
              artist: DJ Die
          catalognum: REACT CD99
         data_source: Discogs
                disc: 02
     discogs_albumid: 72349
    discogs_artistid: 194
     discogs_labelid: 436
           disctitle:
           disctotal: 02
              length: 6:08
               media: CD
               title: Reincarnation
               track: 01
           track_alt: 2-1
          tracktotal: 10
                year: 1997
```

Configuration: 
```
plugins: discogs missing
per_disc_numbering: yes
```

**Comment by sampsyo** [comment]
Thanks for pointing this out. That field was indeed originally intended as a best-effort kind of thing—to make the best guess possible given the existing metadata. It can certainly be wrong! But that's the deal with making guesses based on metadata.

We could consider preserving the complete track count in a separate field, but it would need to be a new one—so that this computed field could continue to be useful when the music is _not_ autotagged from MusicBrainz.

**Comment by dbogdanov** [comment]
Can you clarify on that? I am not using MusicBrainz in my use-case.  The `albumtotal` is wrong and inconsistent when comparing `per_disc_numbering: yes` and `per_disc_numbering: no`. Why having another new field instead of fixing it?

**Comment by sampsyo** [comment]
Here's the problem: `albumtotal` is a computed field. That means it's based on the _current_ metadata of the track. So it's making the best guess it can given the circumstances: it's looking at the current disc and track numbers and trying to figure out what the total number of tracks might be. We can of course consider improving the way it deduces information from the current metadata, but this is not an option:

> `albumtotal` should be assigned in the tagger at the import time directly from the chosen candidate's metadata

because it requires autotagging. The current `albumtotal` functionality does not require autotagging. You can still use it if you just set all your metadata manually, for example.

If we want to preserve extra information from autotagging, we can consider that too—but we shouldn't take away the current functionality of the field, which is not based on autotagger candidates.

**Comment by dbogdanov** [comment]
Going back to this issue. Any further reasons why the `albumtotal` field can not be changed to an autotagging field? How is `albumtotal` currently used? 

If we go for storing a new metadata field, what is a good field name to use? (e.g. `tracktotal`) I'm afraid that both `tracktotal` and `albumtotal` field names aren't intuitive to clearly see a distinction between auto-computed vs  auto-tagger fields.

**Comment by jtpavlock** [comment]
Could a solution be to default to a value set by the autotagger, and if it isn't present, fallback on the computed one?
