### ISSUE TITLE
Use Discogs as an album art source for FetchArt

### ISSUE THREAD

**Issue by dbogdanov** [beetbox/beets#3571]
### Use case
Discogs has a vast collection of album art accessible via the API,  but it is not supported by FetchArt.

It would work very well in combination with the [Discogs](https://beets.readthedocs.io/en/stable/plugins/discogs.html) plugin.

**Comment by jackwilsdon** [comment]
Looks like this is a duplicate of #429, I'll go ahead and close this in favour of that one.
