### ISSUE TITLE
Bulk move fails when source file missing

### ISSUE THREAD

**Issue by kgmoore431** [beetbox/beets#3575]
Beet exists with a python error when attempting to move a library item where the source file is missing.

**Environment:**

```
MyMac:~$ uname -a
Darwin MyMac.local 18.7.0 Darwin Kernel Version 18.7.0: Thu Jan 23 06:52:12 PST 2020; root:xnu-4903.278.25~1/RELEASE_X86_64 x86_64
MyMac:~$ python3 --version
Python 3.7.5
MyMac:~$ pip3 freeze |grep beet
beets==1.4.9
MyMac:~$ pip3 install -U beets
Requirement already up-to-date: beets in /usr/local/lib/python3.7/site-packages (1.4.9)
Requirement already satisfied, skipping upgrade: unidecode in /usr/local/lib/python3.7/site-packages (from beets) (1.0.22)
Requirement already satisfied, skipping upgrade: mutagen>=1.33 in /usr/local/lib/python3.7/site-packages (from beets) (1.43.0)
Requirement already satisfied, skipping upgrade: musicbrainzngs>=0.4 in /usr/local/lib/python3.7/site-packages (from beets) (0.6)
Requirement already satisfied, skipping upgrade: munkres>=1.0.0 in /usr/local/lib/python3.7/site-packages (from beets) (1.1.2)
Requirement already satisfied, skipping upgrade: six>=1.9 in /usr/local/lib/python3.7/site-packages (from beets) (1.11.0)
Requirement already satisfied, skipping upgrade: jellyfish in /usr/local/lib/python3.7/site-packages (from beets) (0.7.2)
Requirement already satisfied, skipping upgrade: pyyaml in /usr/local/lib/python3.7/site-packages (from beets) (5.3)
```

**Result:**

```
MyMac:~$ beet move
Moving 6097 items (32 already in place).
Traceback (most recent call last):
  File "/usr/local/bin/beet", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/site-packages/beets/ui/__init__.py", line 1266, in main
    _raw_main(args)
  File "/usr/local/lib/python3.7/site-packages/beets/ui/__init__.py", line 1253, in _raw_main
    subcommand.func(lib, suboptions, subargs)
  File "/usr/local/lib/python3.7/site-packages/beets/ui/commands.py", line 1551, in move_func
    opts.timid, opts.export)
  File "/usr/local/lib/python3.7/site-packages/beets/ui/commands.py", line 1540, in move_items
    obj.move(operation=MoveOperation.MOVE, basedir=dest)
  File "/usr/local/lib/python3.7/site-packages/beets/library.py", line 818, in move
    self.move_file(dest, operation)
  File "/usr/local/lib/python3.7/site-packages/beets/library.py", line 726, in move_file
    destination=dest)
  File "/usr/local/lib/python3.7/site-packages/beets/plugins.py", line 489, in send
    result = handler(**arguments)
  File "/usr/local/lib/python3.7/site-packages/beets/plugins.py", line 143, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/beetsplug/importadded.py", line 87, in record_import_mtime
    mtime = os.stat(util.syspath(source)).st_mtime
FileNotFoundError: [Errno 2] No such file or directory: b'/Volumes/media/iTunes/iTunes Music/Music/Adiemus/Songs of Sanctuary/01 Adiemus.m4p'
```

**Expectation:**

I expected beets to trap this error and ideally offer the user some options for triage. e.g. skip missing file, remove offender from library etc

**Comment by sampsyo** [comment]
Hi! Can you expand with a little more context? How did you manage to import a file that does not exist?

**Comment by fleur** [comment]
I'm having the same problem, and when I go look, the file is actually there.  So far, the paths that are "not found" have always included at least one non-ascii character.  Sometimes the pathname printed out has the bytecode expansions of a unicode char in them.

**Comment by fleur** [comment]
Just happened again.  And strangely, when I copy the path beets spits out, including the quotes, and try to ls, it fails.  But the file is there, I can tab-complete to it.  The paths looks the same:

```
admin@ogma:~$ beet -v move
user configuration: /var/services/homes/admin/.config/beets/config.yaml
data directory: /var/services/homes/admin/.config/beets
plugin paths: 
Sending event: pluginload
inline: adding item field multidisc
library database: /volume2/Media/Music/beets-music-library.db
library directory: /volume2/Media/Music
Sending event: library_opened
Moving 11924 items (853 already in place).
moving: /volume2/Media/Music/beets/A-F/Beck/Guero/02 - Qué onda güero.mp3
Sending event: before_item_moved
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/beets/util/__init__.py", line 485, in move
    shutil.copyfile(path, dest)
  File "/usr/lib/python2.7/shutil.py", line 82, in copyfile
    with open(src, 'rb') as fsrc:
IOError: [Errno 2] No such file or directory: '/volume2/Media/Music/beets/A-F/Beck/Guero/02 - Que\xcc\x81 onda gu\xcc\x88ero.mp3'
admin@ogma:~$ ls '/volume2/Media/Music/beets/A-F/Beck/Guero/02 - Qué onda güero.mp3'
ls: cannot access /volume2/Media/Music/beets/A-F/Beck/Guero/02 - Qué onda güero.mp3: No such file or directory
admin@ogma:~$ ls /volume2/Media/Music/beets/A-F/
Display all 191 possibilities? (y or n)
admin@ogma:~$ ls /volume2/Media/Music/beets/A-F/Beck/Guero/02\ -\ Qué\ onda\ güero.mp3 
/volume2/Media/Music/beets/A-F/Beck/Guero/02 - Qué onda güero.mp3
```

**Comment by sampsyo** [comment]
Delightful—looks like an exciting encoding or Unicode normalization problem. Alas, these things can be _extremely_ hard to debug. Does it work to remove and import the file again?

**Comment by fleur** [comment]
Another data point:  While trying to get the move to work, I gave the physical path has the argument.  It skipped stuff that was verified to be in the db by listing later.   The things it skipped all had a non-ascii character somewhere in the artist/album/item.  THEN I discovered that it only skipped _some_ of them.  Some were copied.

In terms of deleting and reimporting, unfortunately it's not easy to do.  Since beets doesn't seem to do the move in any specific order.  I removed and re-imported, but when I started the move again, it didn't try to move the one i just re-imported, it errored out on a different album.

I tried from scratch:
* created a new config.yaml pointing to new places
* import an album that had errored out before
* changed config'ed directory to a different place
* did `beets move`
...and it was successful.  I also tried fingerprinting and a write and a move again, and it was still fine.

**Comment by sampsyo** [comment]
Very strange! Thanks for continuing to dig into this. If you come up with a way to reproduce the problem "from scratch" locally, maybe we can pin down a cause…

**Comment by fleur** [comment]
I'm going to try reimporting everything a little at a time, doing the things I was originally doing in smaller batches (fingerprint, write, etc.), so if I find a pattern, I'll follow up.

In the meantime I will echo the op's suggestion to put in an option to skip errors at the very least, so triage can be done at the end.  Right now, any "missing" errors require intervention each time to make any progress doing a move, which is prohibitively painful.

Thanks.
