### ISSUE TITLE
Get audio features from spotify

### ISSUE THREAD

**Issue by flovanc** [beetbox/beets#3578]
hello, i'm a Home DJ who use beets for tag music with mostly beatport plugin and thanks for this great feature .

Since i have discover http://www.playlistmachinery.com/ i use these tools for adding tag like Genre, Energy, Danceability and Valence in the comment section of id3 for help me to make smooth playlist for my DJ software "traktor"

for do this i ..

- in 1 add music in "to tag"playlist inside spotify 

- in 2 open http://organizeyourmusic.playlistmachinery.com/#

- in 3 manually copy those tag to the comment section of id3 tag

needless to say it takes a very long time  , so I'm looking for a way to automate everything.

is anyone interested in this and would like to help me implement this with the help of the spotify API ?

https://developer.spotify.com/documentation/web-api/reference/tracks/get-audio-features/

FLO

**Comment by sampsyo** [comment]
Hi! Have you seen the AcousticBrainz plugin that ships with beets? It provides another (open-source) way to get these acoustic metrics.

**Comment by flovanc** [comment]
yes it only works with musicbrainz. But in my case I use 100% the beatport plugin and forbid access to musicbrainz, because they are new releases of electronic music from beatport.

**Comment by sampsyo** [comment]
Aha, that's too bad. But it looks like the Spotify API there requires a Spotify ID—do your files have that?

**Comment by Laski** [comment]
@flovanc if your files don't have an Spotify ID you can probably import or adapt the code from https://github.com/beetbox/beets/blob/master/beetsplug/spotify.py in order to get the IDs first.

P.S: Just discovered all the data that is available in the Spotify API, thanks! Now I'm looking forward to having an automated way to import that data into my library too. Let me know how can I help you.

**Comment by flovanc** [comment]
No i don't have spotify ID inside my files .
i make a try to import with spotify plugin but i have this error:

> beet -vv import /home/payason/downloads/music\ in
user configuration: /home/payason/.config/beets/config.yaml
data directory: /home/payason/.config/beets
plugin paths:
Sending event: pluginload
library database: /home/payason/.config/beets/musiclibrary.db
library directory: /home/payason/Music
Sending event: library_opened
Sending event: import_begin
Sending event: import_task_created
Sending event: import_task_start
Looking up: /home/payason/downloads/music in/DEADWALKMAN - Valleys Of Saturn EP
Tagging DEADWALKMAN - Valleys Of Saturn EP
No album ID found.
Search terms: DEADWALKMAN - Valleys Of Saturn EP
Album might be VA: False
Searching for MusicBrainz releases with: {'release': u'valleys of saturn ep', 'tracks': u'4', 'artist': u'deadwalkman'}
Requesting MusicBrainz release afb76f46-99bf-4388-9414-86a9ccc19f85
primary MB release type: ep
Sending event: albuminfo_received
Candidate: DEADWALKMAN - Tools Of The Trade (afb76f46-99bf-4388-9414-86a9ccc19f85)
Computing track assignment...
...done.
Success. Distance: 0.50
Requesting MusicBrainz release d9090c36-585d-477a-a8cc-8437918b1d69
Sending event: albuminfo_received
Candidate: Various Artists - Club Saturn EP (d9090c36-585d-477a-a8cc-8437918b1d69)
Computing track assignment...
...done.
Success. Distance: 0.66
Requesting MusicBrainz release 71482349-e25e-4af4-9215-7053679c6179
primary MB release type: album
Sending event: albuminfo_received
Candidate: Andrew Morris - Valleys (71482349-e25e-4af4-9215-7053679c6179)
Computing track assignment...
...done.
Success. Distance: 0.83
Requesting MusicBrainz release 49f85c86-b650-4506-947b-28da6a8b5364
Sending event: albuminfo_received
Candidate: John Sokoloff - Valleys (49f85c86-b650-4506-947b-28da6a8b5364)
Computing track assignment...
...done.
Success. Distance: 0.82
Requesting MusicBrainz release 852dddd0-3c61-4adc-9e02-5badffca393d
primary MB release type: ep
Sending event: albuminfo_received
Candidate: Gliese 614 - Saturn (852dddd0-3c61-4adc-9e02-5badffca393d)
Computing track assignment...
...done.
Success. Distance: 0.79
Traceback (most recent call last):
  File "/home/payason/.local/bin/beet", line 11, in <module>
    load_entry_point('beets==1.5.0', 'console_scripts', 'beet')()
  File "/home/payason/.local/lib/python2.7/site-packages/beets/ui/__init__.py", line 1267, in main
    _raw_main(args)
  File "/home/payason/.local/lib/python2.7/site-packages/beets/ui/__init__.py", line 1254, in _raw_main
    subcommand.func(lib, suboptions, subargs)
  File "/home/payason/.local/lib/python2.7/site-packages/beets/ui/commands.py", line 956, in import_func
    import_files(lib, paths, query)
  File "/home/payason/.local/lib/python2.7/site-packages/beets/ui/commands.py", line 926, in import_files
    session.run()
  File "/home/payason/.local/lib/python2.7/site-packages/beets/importer.py", line 329, in run
    pl.run_parallel(QUEUE_SIZE)
  File "/home/payason/.local/lib/python2.7/site-packages/beets/util/pipeline.py", line 445, in run_parallel
    six.reraise(exc_info[0], exc_info[1], exc_info[2])
  File "/home/payason/.local/lib/python2.7/site-packages/beets/util/pipeline.py", line 312, in run
    out = self.coro.send(msg)
  File "/home/payason/.local/lib/python2.7/site-packages/beets/util/pipeline.py", line 194, in coro
    func(*(args + (task,)))
  File "/home/payason/.local/lib/python2.7/site-packages/beets/importer.py", line 1353, in lookup_candidates
    task.lookup_candidates()
  File "/home/payason/.local/lib/python2.7/site-packages/beets/importer.py", line 641, in lookup_candidates
    autotag.tag_album(self.items, search_ids=self.search_ids)
  File "/home/payason/.local/lib/python2.7/site-packages/beets/autotag/match.py", line 467, in tag_album
    extra_tags):
  File "/home/payason/.local/lib/python2.7/site-packages/beets/plugins.py", line 577, in decorated
    for v in generator(*args, **kwargs):
  File "/home/payason/.local/lib/python2.7/site-packages/beets/autotag/hooks.py", line 647, in album_candidates
    extra_tags):
  File "/home/payason/.local/lib/python2.7/site-packages/beets/plugins.py", line 387, in candidates
    extra_tags):
TypeError: candidates() takes exactly 5 arguments (6 given)

@Laski thanks for the help but i'm a complete noob . my coding skills are close to zero. 
I am already happy to have installed beets and to configure it properly.
But I admit that I am happy that you also want to import its data into your music

maybe this [https://spotipy.readthedocs.io/en/2.12.0/](url) would help us .

Flo

**Comment by flovanc** [comment]
No i don't have spotify ID inside my files because the use of beatport plugin .

But i  make a import with the spotify plugin and "mb tag" are updated with spotify ID.

**Comment by flovanc** [comment]
@Laski thanks for the help, you should know that my programming level is close to zero. I am already happy to be able to install beets and configure it.

But I am relatively curious and I discovered spotipy

https://spotipy.readthedocs.io/en/2.12.0/

Can be that can be useful to us

Flo

**Comment by rhlahuja** [comment]
I implemented the Spotify plugin and can help add these audio features. Since it'll require an extra API call per track, perhaps we should separate this into a subcommand rather than grab this additional metadata by default on `beet import`?

**Comment by flovanc** [comment]
Sounds like a good idea to me. is there the possibility to keep the initial ID coming from (musicbrainz, plugin:discogs, plugin:beatport) to allow the use of plugin as mbsync (in my case use of bpsync) in the future?
And where to add these "audio feature"?

**Comment by rhlahuja** [comment]
Hmm that might be possible if we add separate database fields for Spotify IDs, similar to [those added for Discogs](https://github.com/beetbox/beets/blob/560d374a526893b0b9b5399ba5b83348541abe26/beets/library.py#L452-L453). Perhaps @sampsyo or someone else may have a better suggestion.

And [like the AcousticBrainz plugin](https://github.com/beetbox/beets/blob/897100cb3b3790fc24f8b4b2a69d7056acebd583/beetsplug/acousticbrainz.py#L226), I was thinking these audio features would be stored as item-level attributes.

**Comment by sampsyo** [comment]
Sure! Storing the Spotify ID in a flexible attribute seems like a perfectly good idea.

**Comment by flovanc** [comment]
Hello, I'm the only one interested in this feature.
Unfortunately my lack of coding experience prevents me from doing anything, but I thought it would have interested more people.

Flo
