### ISSUE TITLE
Original year + Year of the release

### ISSUE THREAD

**Issue by juanenbici** [beetbox/beets#3581]
I have a large Jazz library and for some albums I have more than one different release. For example I have one CD release from the 90's and then a release of a Special Remaster edition of some years later, both from a Vinyl from the 50's. So I have two albums with the same original release year but different release years. 
I see that it's not possible to import both original year and release year form MusicBrainz, and in this case It would be important to have both info.
Thank you.

**Comment by sampsyo** [comment]
Hi! In the default configuration, beets does in fact fetch both the $year and $original_year fields. Is this not what you’re after?

**Comment by juanenbici** [comment]
Oh, I'm sorry. I tested it before and I was thinking that to fetch the original_year you had to put the original_year option as 'yes' in the configuration.  I don't know what happened, because now I've trayed it and it worked. Thank you for your time.

**Comment by sampsyo** [comment]
Great!
