### ISSUE TITLE
Running web server for production

### ISSUE THREAD

**Issue by laBecasse** [beetbox/beets#3593]
Hello,

I wonder why I have this message, when I run the web plugin: 
```
* Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
```

Does it mean that I should not use the web plugin in production ? If it is the case, how can I change my configuration to solve this issue ?

**Comment by sampsyo** [comment]
Hi! You can certainly use a a fancier server, such as Gunicorn or uWSGI. But it won't just be a matter of configuring beets—you will need to set up one of those servers just as you would to serve any other Flask (or other WSGI) application in production.

**Comment by laBecasse** [comment]
Thank for your answer. Someone can tell me which command to run using Gunicorn, for example, please.
