### ISSUE TITLE
How to do camel case for file names?

### ISSUE THREAD

**Issue by weilbith** [beetbox/beets#3597]
I would love to get the camel case for the file names when I import music to my library. Example: the artist `'Armin van Buuren'` should become `'ArminVanBuuren'`.
With the global `replace` options this should not be possible, because it uses plain strings for the replacement. So I would do the entry `'\s([a-zA-Z])'`. Now I want to replace it with a upper case version of group one in the expression. With plain python I would put a `lambda r: r.group(1).upper()`. But this is not possible. Sure I can access the group in the replacement string with `'\1'`, but I can't find a way to transform this to upper case. In bash this would be like `${var^^}`. Any idea how I can achieve that?

**Comment by sampsyo** [comment]
Hello! I think this is a perfect use case for the inline plugin:
https://beets.readthedocs.io/en/stable/plugins/inline.html

Where you could use a Python expression like `''.join([p.title() for p in s.split()])`.

This would be even better, of course, if it were possible to define path _functions_ with inline, which would be a great new feature. As it stands, this would need to be repeated per field.
