### ISSUE TITLE
dry run

### ISSUE THREAD

**Issue by tcurdt** [beetbox/beets#3599]
### Use case

I want to run beets but make sure nothing gets changed inside the import directory (for now).
The docs imply this could possibly the case with:

    import:
        copy: no
        write: no

But this is not made clear and I am also unsure this could exclude plugins.
It seems my best guess is to run it on a read-only mount for now.

**Comment by sampsyo** [comment]
Hi! That should probably do it. (But as always, I strongly recommend taking a backup first!)

Is there a specific bug or request you’re filing here?

**Comment by tcurdt** [comment]
@sampsyo I think the very least it would be great to make this clearer in the documentation. That certainly is the main request. So that's a request for documentation.

But it could also serve as feature request for a dry-run option. An option that just shows what would be done - but not doing any changes on disc. I was expecting something like that.

I ended up mounting the drive read-only to try. While the above `import` configuration seems to work OK, it needs to be pointed out that plugins do not adhere to this. Glad I went the read-only route - backup or not.

**Comment by sampsyo** [comment]
Sure; sounds great! We really appreciate documentation contributions from the community—if you can think of a good way to explain this and the right place to put it, please consider opening a pull request.

You might also be interested in the `beet import --pretend` option, but it only shows you which files would be imported:
https://beets.readthedocs.io/en/stable/reference/cli.html#import

**Comment by tcurdt** [comment]
I'll see what I learn in the process and will try to write things up.
