### ISSUE TITLE
How to move files without changing file name?

### ISSUE THREAD

**Issue by null-python** [beetbox/beets#3601]
Hi, I was wondering how I could import a file as a singleton, fix its metadata, but keep the original file name upon importing it.

**Comment by sampsyo** [comment]
Hello! You will want to disable the `move` and `copy` options of the importer if you don't want to change filenames.

If you mean that you still want to move files around but keep the original _base_ filename in the new _directory_, however, that is not really supported. There may be hacks to accomplish it, but the "beets way" is to generate filenames from metadata.

Here are some relevant threads:
https://discourse.beets.io/t/edit-filenames-in-place/1043/2
https://discourse.beets.io/t/keeping-source-original-folder-name/308

**Comment by null-python** [comment]
thanks for the info
