### ISSUE TITLE
timid mode should show all 100.0% matches, but doesn't

### ISSUE THREAD

**Issue by afontenot** [beetbox/beets#3603]
### Use case

I care about all my music being tagged accurately, so I use timid mode all the time. (In my experience, Beets gets the right album about 99% of the time, but the wrong release of that album about 50% of the time.)

I recently discovered that a bunch of my music was tagged incorrectly because I had trusted the "100.0%" matches when they came up. This way of describing them is already misleading, because it suggests that there's no possible way the wrong MusicBrainz release could be found, but that's not the case.

But the real problem with the 100.0% matches is not that they're not guaranteed to be accurate, but that Beets _hides_ all of them except the first one! I can't think of any justification for doing that, especially in timid mode. I think the average user will get the misleading impression that there's only one plausible match for an album, when that is often not the case. I'm looking at an album right now with _five_ 100.0% matches (and I don't have that much confidence Beets is not hiding more from me). That's two CD releases from two different record companies, one vinyl release from one of those companies, and digital releases in two different countries. All are 100.0% matches.

Unfortunately this meant I had to spend many hours retagging every single album in my collection, because I couldn't think of any way to check which albums this issue might have affected at some point in the past.

### Solution

Possible solutions:

1. always show any plausible match in timid mode (say, within 2% of the top match) - my preferred solution
2. always show all 100.0% matches
3. include a configuration option to do either 1 or 2

It's possible 3 already exists, but if it does I wasn't able to find it in the documentation. 

### Version

beets 1.4.9 official Arch Linux package

**Comment by sampsyo** [comment]
Hello! The similarity metric is based on the available metadata, so 100% means "beets did not detect any metadata conflicts," not "we are certain this is correct." Correctness is pretty ineffable!

Anyway, if we were to add such an option, I think the way to do it would be that beets *always* shows you a menu of candidates, and you have to press 1 to pick the best one. It would *never* automatically select the first one and ask you to apply it.

In fact, it's already possible to get something close to this with the `strong_rec_thresh` option and other, similar options in the config:
https://beets.readthedocs.io/en/stable/reference/config.html#autotagger-matching-options

If you set that and `medium_rec_thresh` to 0.0 (or maybe even something weird like -1.0 to be sure?) then beets will never make "strong" recommendations—which is what causes beets to show you the "best" match instead of a menu of options.

**Comment by afontenot** [comment]
Hey, sorry for not following up on this. Things got crazy for me for a while.

Having thought about it, I agree with you that there's no way for beets to ever be certain it's got the right release, but I still think it's very weird to only show *one* release when there's a tie between several "best" releases. This bug is about beets giving the user the wrong impression, and I think that impression is that there's only one plausible match for the album. 

If you think about going through a few hundred albums on timid mode, much of time time beets is going to show you multiple candidates, and ask you to pick one. And then some of the time it only shows you one candidate, with a very high match rating. I wrongly assumed this meant that beets found only one match, and selected it. I suspect many other people would make the same mistake?

> Anyway, if we were to add such an option, I think the way to do it would be that beets always shows you a menu of candidates, and you have to press 1 to pick the best one. It would never automatically select the first one and ask you to apply it.

I like this idea quite a lot, it seems to be like what timid mode is intuitively supposed to be doing. I'll try the workaround for my needs, but I think this issue should stay open in case there's interest in changing the behavior around timid.

**Comment by afontenot** [comment]
@sampsyo Would you be interested in a PR fixing this issue? Let me quickly redescribe the issue and the behavior I would like to see:

From the docs:

> To control how *tolerant* the autotagger is of differences, use the `strong_rec_thresh` option, which reflects the distance threshold below which beets will make a "strong recommendation" that the metadata be used. Strong recommendations are accepted automatically (except in "timid" mode), so you can use this to make beets ask your opinion more or less often.

This is actually (in my opinion) a misleading description of what happens. What *actually* happens is that Beets sorts the possible matches by closeness, and if the strongest match meets the strong recommendation threshold, that match becomes the strong recommendation. This is ambiguous in the case that there are *multiple* matches that meet the threshold.

The behavior I would like to see: suppose the best candidate meets threshold X (strong, medium, etc). Suppose there is another candidate that also meets threshold X. In this case, `_recommendation` will return `Recommendation.none` which will force Beets to show the list of matches.

I can think of 3 possible ways to surface this behavior:

 * Put it behind its own config option (`always_show_close_matches`)
 * Only activate this behavior in timid mode
 * Add a different config option (`max_rec_gap`). Instead of bailing out when multiple candidates meet a threshold, bail out when the second best candidate is within `max_rec_gap` of the best candidate. This would have the same effect, but would be a bit more flexible than only looking at thresholds. This would also default to off (or maybe zero - meaning that equal-scoring top matches result in a bail out?).

Thoughts on whether you'd consider merging this feature? Preferred way to expose it?

**Comment by sampsyo** [comment]
Interesting! You're certainly right that the wording is a bit ambiguous; we should says something like "the top strong recommendation is accepted automatically."

The "multiple recommendations within a tier" option is an interesting proposal. It is reminiscent of, but not precisely the same as, the "gap threshold" logic (embodied in the [`rec_gap_thresh`](https://beets.readthedocs.io/en/stable/reference/config.html#autotagger-matching-options) option). (That one "upgrades" some matches if there is a big gap between the top match and the second-ranking match.)

Is there any sense in generalizing that logic—that is, requiring enough of a gap to exist before issuing a strong recommendation automatically?

**Comment by afontenot** [comment]
> Is there any sense in generalizing that logic—that is, requiring enough of a gap to exist before issuing a strong recommendation automatically?

I think that would be a good idea. Seems like it would be a useful feature for *all* modes, since it would avoid mistagging something with `timid=off` just because one result had a strong match. I think something a little more robust would be needed for timid mode.

As I see it, the problem is that when I'm in timid mode and the best match is 100%, Beets doesn't warn me that there are other albums that also get a 100% match. Or a 98% match and there's another one which is 97%, but is actually the correct one because of tiny differences in track naming. Demoting the recommendation to medium or low is not sufficient to solve this problem, because in this case Beets will still issue a recommendation and not show other matches unless you explicitly request it to. Granted, you'll have a slightly better clue about what's going on because "Accept" is not highlighted automatically, but still...

**Comment by sampsyo** [comment]
Sure. Maybe it would be worthwhile to dive into the code and see how the current "gap" logic works (start with the `beets.autotag.match` module), and try to think through exactly how the semantics of a "required gap" would work. It would be great to come up with a concept that is simple to explain in English for the docs.

**Comment by afontenot** [comment]
Cool, I'll take a look at that when I have some time.
