### ISSUE TITLE
import: support extraction of bzip2 and gzip tarballs

### ISSUE THREAD

**Issue by cota** [beetbox/beets#3606]
### Use case

I'm trying to use beets to import albums from a set of bzip2/gzip tarballs, i.e. .tar.bz2 and .tar.gz files. Would be nice if we could just import them instead of having to extract them first.

### Solution

I see that the `tarfile` module can process tar archives with [gzip or bzip2 compression](https://docs.python.org/2/library/tarfile.html), so hopefully this is not too hard to do. Unfortunately I don't know Python so I cannot provide a patch.

### Alternatives

As a workaround I am extracting the tarballs first. Not the end of the world but it would be nice to be able to just point beets to the files, just like we do with rar and zip files.

Thanks for maintaining this great piece of software!

**Comment by jackwilsdon** [comment]
Have you tried importing `.tar.bz2` or `.tar.gz`? It looks like we should already support it from the source:

https://github.com/beetbox/beets/blob/19ab28e1412dbf4130e015a94557d277b4c699ed/beets/importer.py#L1037-L1038

**Comment by cota** [comment]
Note that `TarFile` only works for uncompressed tar archives. Quoting from `/usr/lib/python3.8/tarfile.py`:
```
    def __init__(self, name=None, mode="r", fileobj=None, format=None,
            tarinfo=None, dereference=None, ignore_zeros=None, encoding=None,
            errors="surrogateescape", pax_headers=None, debug=None,
            errorlevel=None, copybufsize=None):
        """Open an (uncompressed) tar archive `name'. `mode' is either 'r' to                                                                                          
           read from an existing archive, 'a' to append data to an existing                                                                                            
           file or 'w' to create a new file overwriting an existing one. `mode'                                                                                        
           defaults to 'r'.
[...]
```

The method that we want is `TarFile.open`, not the constructor:
```
   def open(cls, name=None, mode="r", fileobj=None, bufsize=RECORDSIZE, **kwargs):                                                                                    
        """Open a tar archive for reading, writing or appending. Return                                                                                                
           an appropriate TarFile class.                                                                                                                               
                                                                                                                                                                       
           mode:                                                                                                                                                       
           'r' or 'r:*' open for reading with transparent compression
[...]
```
I'll send a patch. Please double check the tests, this is the first time I write anything in Python and I've given up trying to get the necessary packages :(
