### ISSUE TITLE
discogs-client now deprecated

### ISSUE THREAD

**Issue by grawlinson** [beetbox/beets#3608]
As of today, the [discogs-client](https://github.com/discogs/discogs_client) package has been deprecated. This will become an issue when upstream breaks API compatibility.

> This repository is no longer maintained. You can still use a REST client like [Requests](https://pypi.org/project/requests/) or other third-party Python library to access the [Discogs REST API](https://www.discogs.com/developers).

**Comment by sampsyo** [comment]
That's too bad! Perhaps a volunteer is interested in forking it and attempting to maintain the library independently?

**Comment by grawlinson** [comment]
Yeah, I'll make a fork as I use this quite extensively.

For now, are you OK to depend on the current package? I don't expect it to break compatibility anytime soon!

**Comment by sampsyo** [comment]
Yes, sounds good! No need to drop it if it's not currently causing problems. Thanks for being willing to adopt it! :smiley:

**Comment by grawlinson** [comment]
I've forked the current package [here](https://github.com/grawlinson/python-discogs-api), feel free to update documentation/code pointing to it.

Also, I'd appreciate if feedback could be made regarding improvements to the code as-is. It'll take me a bit of time to look at the closed issues/PRs on discogs-client.

**Comment by jhuldtgren** [comment]
is there timeline to get the code updated to use discogs_api vs discogs_client? I maintain the discogs_client port/package for OpenBSD and was looking to replace it with discogs_api but until the appropriate code is updated in beets that can't happen.

**Comment by grawlinson** [comment]
A pull request will need to be proposed. I wish I had the time to do this, so if you could do that, it would be great.

It should be as simple as replacing all calls made to `discogs_client` with `discogs_api`.

Any further issues, I'll be happy to help.

**Comment by sampsyo** [comment]
That would be great! And indeed; I don't think the change should be hard.

**Comment by pbnoxious** [comment]
I think all you need to do codewise is replace the imports, the API seems to have mostly stayed the same.

I actually did the changes and wanted to do a PR [(here is the branch)](https://github.com/pbnoxious/beets/tree/discogs_api), but realized that there are now multiple forks, also one that keeps the package named [discogs_client](https://github.com/joalla/discogs_client).
Using that one would likely only require to change the dependency `discogs-client -> python3-discogs-client` in setup.py (and maybe the documentation).

What are your thoughts? Which of the forks should be used?

**Comment by sampsyo** [comment]
Can we trust your judgment on that? Does any one fork look more promising than the others?

**Comment by grawlinson** [comment]
Considering that the discogs community have converged on [joalla/discogs_client](https://github.com/joalla/discogs_client) rather than others (including my fork), it would be preferable to go with that one.
