### ISSUE TITLE
feat(ci): proper caching

### ISSUE THREAD

**Issue by jef** [beetbox/beets#3615]
### Use case

From https://github.com/beetbox/beets/pull/3602#issuecomment-639520863

We want to have caching for our pipelines to speed up build process. The current solution doesn't cache properly.

### Solution

I believe we should probably cache around `tox.ini` rather `requirements.txt`. Potentially have some other use case since we use install dependencies through editable mode (`pip install -e .`).

[Here](https://github.com/actions/cache/blob/v2/examples.md#python---pip) are some more examples using actions/cache@v2.

**Comment by bal-e** [comment]
I don't know exactly how far caching can go in improving the CI, but I believe #5266 has done what this issue is asking for, and this can be closed now.

**Comment by jef** [comment]
Thanks @bal-e!
