### ISSUE TITLE
Make "paths:" more user-friendly and expandable

### ISSUE THREAD

**Issue by ScuttleSE** [beetbox/beets#3616]
I use the paths:-part of beets a lot to automatically sort imported albums into different subfolders depending on the content of the import, which I'm sure a lot of people do.

Problem is, after a while, if you are using %if in the paths, they can be incredibly complex and hard to read

For example, the line I have for Soundtracks looks like this:

`albumtype:soundtrack: Library/%if{$musical,Theater,Soundtracks}/%if{$disney,Disney,%if{$marvel,Marvel,%if{$musical,,Various}}}/%the{$album}/%if{$multidisc,Disc $disc/}$track - $title`

The problem as I see it is that if I use `albumtype:soundtrack:` as a way to match, that is it. I have to match every single soundtrack I import on that line.

I would suggest that you would be able to structure the flow differently. If you don't get a match on line #1, go on to line #2 and so on until you hit the "default:" section.

So my line from above could instead look like this:

`albumtype:soundtrack: %if{$musical,Library/Soundtracks/Theater/%the{$album}/%if{$multidisc,Disc $disc/}$track - $title`
`albumtype:soundtrack: %if{$disney,Library/Soundtracks/Disney/%the{$album}/%if{$multidisc,Disc $disc/}$track - $title`
`albumtype:soundtrack: %if{$marvel,Library/Soundtracks/Marvel/%the{$album}/%if{$multidisc,Disc $disc/}$track - $title`
`albumtype:soundtrack: Library/Soundtracks/Various/%the{$album}/%if{$multidisc,Disc $disc/}$track - $title`
`default:Library/Default/%the{$album}/%if{$multidisc,Disc $disc/}$track - $title`

So if I import the soundtrack to Avengers, it his the third line, if I import the soundtrack for the latest Bond-movies, it hits the fourth line, and if I import the latest album from Run the Jewels it hits the last, default-line

**Comment by sampsyo** [comment]
Hi!

> I would suggest that you would be able to structure the flow differently. If you don't get a match on line 1, go on to line 2 and so on until you hit the "default:" section.

In fact, it already works that way! Just not with `%if` functions inside the format—the "get a match" decision depends on the query, to the left of the colon in YAML syntax.

So you could try something like this:

```yaml
'albumtype:soundtrack musical:1':  Library/Soundtracks/Theater/%the{$album}/%if{$multidisc,Disc $disc/}$track - $title
'albumtype:soundtrack disney:1':  Library/Soundtracks/Theater/%the{$album}/%if{$multidisc,Disc $disc/}$track - $title
```

Or maybe you don't even need the `albumtype:soundtrack` part of the query if that's redundant.

**Comment by ScuttleSE** [comment]
Aah, interesting. I never realized you could have more than one criteria before the path. The documentation wasn't very...exhaustive on that part :)

**Comment by ScuttleSE** [comment]
Yep, this behaves just like I wanted, so closing :)

**Comment by sampsyo** [comment]
Great! If you're interested, we can always use help improving the docs. The synopsis here is that the left-hand side can be any beets query—i.e., anything that can come after `beet ls` on the CLI.
