### ISSUE TITLE
Support Musicbrainz genres

### ISSUE THREAD

**Issue by trolley** [beetbox/beets#3620]
### Use case

I'd like for beets to tag the genres I use on Musicbrainz the way Picard does. According to this page it should be possible: https://wiki.musicbrainz.org/Genre

### Solution
A new `mbgenres` plugin that allows for either `genres` or `user-genres` queries.

### Alternatives
Don't know.

**Comment by sampsyo** [comment]
Please see #3053.

**Comment by trolley** [comment]
I swear I searched...I may have accidentally been looking at closed issues though. Thanks :)
