### ISSUE TITLE
Album metadata is not what is displayed by beet info -l

### ISSUE THREAD

**Issue by agross** [beetbox/beets#3624]
### Problem

I currently wonder if the following makes sense. My main concern is the `album` field.

```sh
$ beet info -l 'a grand love story' | head
/Users/agross/Nextcloud/Music/Kid Loco - A grand Love Story/Kid Loco - A grand Love Story CD 1 - 01 - A grand love theme.mp3
acoustid_fingerprint:
         acoustid_id:
               added: 2005-08-27 15:18:09
               album: A grand Love Story
            album_id: 213
         albumartist: Kid Loco
  albumartist_credit:
   albumartist_no_va: Kid Loco -
    albumartist_sort:
```

The album here is `A grand Love Story`. The `move command uses `A grand Love Story CD 1`, so I was wondering where this piece of data came from. I could not find a way to display album metadata, which is sad.

So I tried modifying the album's metadata. As we see the album has different (including `CD 1` in my case) metadata than the item.

```sh
$ beet modify -a album='A grand Love Story' 'a grand love story'
Modifying 1 albums.
/Users/agross/Nextcloud/Music/Kid Loco - A grand Love Story
  album: A grand Love Story CD 1 -> A grand Love Story
Really modify? (Yes/no/select)
```

I then thought I might be more specific by specifying the album by ID.
```
$ beet modify -a album='A grand Love Story' album_id:213
error: No matching albums found.
```

I can't explain why.
### Setup

* OS: macOS
```
beets version 1.4.9
Python version 3.7.7
plugins: badfiles, discogs, embedart, fetchart, hook, importadded, info, inline, zero
```

**Comment by sampsyo** [comment]
Indeed; `beet info` is showing you track-level information.

> I could not find a way to display album metadata, which is sad.

Try this: `beet ls -af '$album' kid loco`.

> I then thought I might be more specific by specifying the album by ID.

Try this: `beet ls -a id:213`.

**Comment by agross** [comment]
Thanks for your quick reply, @sampsyo!

> Try this: `beet ls -af '$album' kid loco`.

That displays a list of albums but Kid Loco:

```
A grand Love Story
Another late night
DJ Kicks
```

I was interested in *everything* that is stored for `A grand Love Story`, because `beet move` was putting the `CD 1` bit into the file paths and that piece of data was not displayed for the individual tracks. How would you have tracked it down to the album? And how can I check albums for correct metadata?

> Try this: `beet ls -a id:213`.

That works, thank you. It's not very discoverable, though. Would it be possible to alias `id` to `album_id`?

**Comment by agross** [comment]
> I was interested in everything that is stored for `A grand Love Story`

Something like this:

```sh
#!/usr/bin/env bash

# Display album metadata.
#
# beet-album-info <query>
# beet-album-info id:213

set -euo pipefail

green='\e[1;32m'
reset='\e[0m'

mapfile -t fields < <(beet fields)

now=
for field in "${fields[@]}"; do
  if [[ "$field" == 'Album fields:' ]]; then
    now=1
    continue
  fi

  if [[ -z "$now" ]]; then
    continue
  fi

  if [[ "$field" != \ \ * ]]; then
    break
  fi

  field_trimmed="${field#  *}"

  printf '%b%s%b: ' "$green" "$field_trimmed" "$reset"
  beet list --album --format "\$$field_trimmed" "$@"
done
```

**Comment by sampsyo** [comment]
I suppose the way I would have gone about it would be to use that `-f '$album'` thing, because it seems like it was indeed coming from the `$album` field—so I'd start by inspecting that field. It can also be helpful to use `-f` with your entire path format string to help debug it.

> That works, thank you. It's not very discoverable, though. Would it be possible to alias `id` to `album_id`?

Database row IDs are kind of an internal detail, so these are indeed not really intended to be exposed in an obvious way—although of course there are some cases where using them is unavoidable. (I think exposing the database column name, `id`, directly is probably the right thing to do here.)
