### ISSUE TITLE
New Release

### ISSUE THREAD

**Issue by lovesegfault** [beetbox/beets#3625]
Beets master is approaching 1000 commits since the last release, and so I'm here to ask for a new release to be cut :)

I can help with testing if an alpha/preliminary release is cut

**Comment by sampsyo** [comment]
Hello! This post has more context on why releases are slow to come:
https://discourse.beets.io/t/forming-a-beets-core-team/639

The synopsis is that the project organization is currently bottlenecked on me to do releases, and I have somewhat extreme time constraints that make that hard. I'm still looking for help with this sort of thing if anyone wants to step up! :smiley:

**Comment by nektro** [comment]
> and I have somewhat extreme time constraints that make that hard

the last message here was Jun 17. have you had no time in the last 4 months to do allocate to this?

**Comment by lovesegfault** [comment]
@nektro Please do not harangue maintainers.

Adrian maintains this wonderful piece of software for free, despite the fact that I'm sure his day-job keeps him quite busy. If things take time, it is what it is.

Trying to guilt him, or any OSS maintainer, into doing work on _your_ pace is wrong. Please reconsider your approach to collaborating.
