### ISSUE TITLE
Don't remove item from db when deleting the file failes

### ISSUE THREAD

**Issue by rain0r** [beetbox/beets#3626]
I'm not sure if this is a bug report oder rather a feature request.

Let's assume the music library is located at `~/music/` but it's mounted read-only or the user lacks the permission to delete files.

The command `beet rm -d foobar` should remove affected items from the database *and* delete the corresponding files from `~/music/`.

But: if it's not possible to delete the actual file, beets will not display an error message and the file get's removed from the database. This leads to inconsistencies (the file is still under `~/music/` but beet knows nothing about it).

This beheaviour is suboptimal in my opinion so I suggest:

 When specifing the `-d` parameter to `beet rm` and deleting the file is not possible, we could instead:

- Show an error message that the file could not be deleted
- Don't remove the file from the database (this could be overwritten with the `-f` flag)

**Comment by sampsyo** [comment]
Huh, that's surprising! If the file can't actually removed, I would have expected `beet rm -d` to error out on the first failed I/O operation. Any chance you could include a verbose (`-vv`) log from such a failed operation?

**Comment by rain0r** [comment]
You're right - I must have mixed something up!
Sorry for the inconvenience!
