### ISSUE TITLE
Rewrite Plugin does replace-all instead of replace

### ISSUE THREAD

**Issue by fortysixandtwoahead** [beetbox/beets#3629]
### Problem
Not sure, if this an actual bug of the rewrite plugin, at least I expected something else ...

I have this album in my collection:
https://musicbrainz.org/release/04066267-68ff-40be-8895-cbe71b1cb561

The files end up in a folder named after both artists/album:
MUSIC_HOME/Борис Михайлович Феоктистов & Bill Laswell/Russian Chants_ Parastas (Ambient Mix)

As I don't like the Russian characters in the folder name I used the rewrite plugin with this setting:

```yaml
rewrite:
  artist Борис Михайлович Феоктистов: Boris Mikhailovich Feoktistov
```

and did a reimport of the album (beet import -L). The album was reimported, however the artist folder is now
MUSIC_HOME/**Boris Mikhailovich Feoktistov**/Russian Chants_ Parastas (Ambient Mix)
instead of 
MUSIC_HOME/**Boris Mikhailovich Feoktistov & Bill Laswell**/Russian Chants_ Parastas (Ambient Mix)

I expected the latter, but rewrite seems to replace the whole string with the substitution instead of only the matched part. Is this the expected behaviour?
### Setup

* OS: Synology OS 6
* Python version: 3.5.6
* beets version: 1.4.9

**Comment by sampsyo** [comment]
Hi! Yes, this is how the plugin is supposed to behave. For your particular use case, you might consider using the importer.languages setting:
https://beets.readthedocs.io/en/stable/reference/config.html

**Comment by fortysixandtwoahead** [comment]
Thanks a lot, good idea. Tried it out and it didn't work with a reimport. I ended up having kyrillic letters in both filenames and metadata. Does that only work in fresh imports?

**Comment by sampsyo** [comment]
It should work for re-imports, but it depends on the data being available on MusicBrainz. (There are other issues and forum threads discussing the specifics about what needs to be on MB, FWIW—and one option is to add the data yourself so others can benefit too. :smiley:)
