### ISSUE TITLE
Beets Update blocked

### ISSUE THREAD

**Issue by entuccio** [beetbox/beets#3632]
### Problem

Running this command in verbose (`-vv`) mode:

$ beet -vv (

daniele@DanieleMacBookAir2 ~ % python3  -m pip install --upgrade --force-reinstall  beets
Processing ./Library/Caches/pip/wheels/c5/55/b2/704ca92820a2bd10ef623baa76b1d168a5c4687aa406fae968/beets-1.4.9-py3-none-any.whl
Processing ./Library/Caches/pip/wheels/12/9e/c1/46af1db49a60a4adf555196c0ead132e4a36a2bd69b078e740/jellyfish-0.8.2-cp37-cp37m-macosx_10_15_x86_64.whl
Collecting munkres>=1.0.0
  Using cached munkres-1.1.2-py2.py3-none-any.whl (6.8 kB)
Collecting musicbrainzngs>=0.4
  Using cached musicbrainzngs-0.7.1-py2.py3-none-any.whl (25 kB)
Processing ./Library/Caches/pip/wheels/5e/03/1e/e1e954795d6f35dfc7b637fe2277bff021303bd9570ecea653/PyYAML-5.3.1-cp37-cp37m-macosx_10_15_x86_64.whl
Collecting six>=1.9
  Using cached six-1.15.0-py2.py3-none-any.whl (10 kB)
Collecting mutagen>=1.33
  Using cached mutagen-1.44.0-py3-none-any.whl (212 kB)
Collecting unidecode
  Using cached Unidecode-1.1.1-py2.py3-none-any.whl (238 kB)
Installing collected packages: jellyfish, munkres, musicbrainzngs, pyyaml, six, mutagen, unidecode, beets
  Attempting uninstall: jellyfish
    Found existing installation: jellyfish 0.8.2
    Uninstalling jellyfish-0.8.2:
      Successfully uninstalled jellyfish-0.8.2
  Attempting uninstall: munkres
    Found existing installation: munkres 1.1.2
    Uninstalling munkres-1.1.2:
      Successfully uninstalled munkres-1.1.2
  Attempting uninstall: musicbrainzngs
    Found existing installation: musicbrainzngs 0.7.1
    Uninstalling musicbrainzngs-0.7.1:
      Successfully uninstalled musicbrainzngs-0.7.1
  Attempting uninstall: pyyaml
    Found existing installation: PyYAML 5.3.1
    Uninstalling PyYAML-5.3.1:
      Successfully uninstalled PyYAML-5.3.1
  Attempting uninstall: six
    Found existing installation: six 1.15.0
    Uninstalling six-1.15.0:
      Successfully uninstalled six-1.15.0
  Attempting uninstall: mutagen
    Found existing installation: mutagen 1.44.0
    Uninstalling mutagen-1.44.0:
      Successfully uninstalled mutagen-1.44.0
  Attempting uninstall: unidecode
    Found existing installation: Unidecode 1.1.1
    Uninstalling Unidecode-1.1.1:
      Successfully uninstalled Unidecode-1.1.1
  Attempting uninstall: beets
    Found existing installation: beets 1.4.9
    Uninstalling beets-1.4.9:
      Successfully uninstalled beets-1.4.9
Successfully installed beets-1.4.9 jellyfish-0.8.2 munkres-1.1.2 musicbrainzngs-0.7.1 mutagen-1.44.0 pyyaml-5.3.1 six-1.15.0 unidecode-1.1.1
daniele@DanieleMacBookAir2 ~ % beet
Usage: 
  beet COMMAND [ARGS...]
  beet help COMMAND

Options:
  --format-item=FORMAT_ITEM
                        print with custom format
  --format-album=FORMAT_ALBUM
                        print with custom format
  -l LIBRARY, --library=LIBRARY
                        library database file to use
  -d DIRECTORY, --directory=DIRECTORY
                        destination music directory
  -v, --verbose         log more details (use twice for even more)
  -c CONFIG, --config=CONFIG
                        path to configuration file
  -h, --help            show this help message and exit

Commands:
  clearart          remove images from file metadata
  config            show or edit the user configuration
  duplicates (dup)  List duplicate tracks or albums.
  edit              interactively edit metadata
  embedart          embed image files into file metadata
  extractart        extract an image from file metadata
  fetchart          download album art
  fields            show fields available for queries and format strings
  help (?)          give detailed help on a specific sub-command
  import (imp, im)  import new music
  lastimport        import last.fm play-count
  list (ls)         query the library
  lyrics            fetch song lyrics
  missing (miss)    List missing tracks.
  modify (mod)      change metadata fields
  move (mv)         move or copy items
  random            choose a random track or album
  remove (rm)       remove matching items from the library
  splupdate         update the smart playlists. Playlist names may be passed
                    as arguments.
  stats             show statistics about the library or a query
  update (upd, up)  update the library
  version           output version information
  write             write tag information to files
daniele@DanieleMacBookAir2 ~ % beet stats
Tracks: 560
Total time: 1.5 days
Approximate total size: 3.8 GiB
Artists: 56
Albums: 87
Album artists: 47
daniele@DanieleMacBookAir2 ~ % beet random
Bob Marley & The Wailers - Classic Bob Marley & The Wailers - Play Play
daniele@DanieleMacBookAir2 ~ % beet random
Original Sicilian Style - Kuttigghiari - 37° nord 14° est
daniele@DanieleMacBookAir2 ~ % beet update
^C%                                                                                                            daniele@DanieleMacBookAir2 ~ % beet -vv
user configuration: /Users/daniele/.config/beets/config.yaml
data directory: /Users/daniele/.config/beets
plugin paths: 
Sending event: pluginload
lyrics: Disabling google source: no API key configured.
lyrics: The Genius backend requires BeautifulSoup, which is not installed, so the source is disabled.
library database: /Users/daniele/.config/beets/library.db
library directory: /Volumes/GoogleDrive/My Drive/DaniSynologyNas/Musica
Sending event: library_opened
Usage: 
  beet COMMAND [ARGS...]
  beet help COMMAND

Options:
  --format-item=FORMAT_ITEM
                        print with custom format
  --format-album=FORMAT_ALBUM
                        print with custom format
  -l LIBRARY, --library=LIBRARY
                        library database file to use
  -d DIRECTORY, --directory=DIRECTORY
                        destination music directory
  -v, --verbose         log more details (use twice for even more)
  -c CONFIG, --config=CONFIG
                        path to configuration file
  -h, --help            show this help message and exit

Commands:
  clearart          remove images from file metadata
  config            show or edit the user configuration
  duplicates (dup)  List duplicate tracks or albums.
  edit              interactively edit metadata
  embedart          embed image files into file metadata
  extractart        extract an image from file metadata
  fetchart          download album art
  fields            show fields available for queries and format strings
  help (?)          give detailed help on a specific sub-command
  import (imp, im)  import new music
  lastimport        import last.fm play-count
  list (ls)         query the library
  lyrics            fetch song lyrics
  missing (miss)    List missing tracks.
  modify (mod)      change metadata fields
  move (mv)         move or copy items
  random            choose a random track or album
  remove (rm)       remove matching items from the library
  splupdate         update the smart playlists. Playlist names may be passed
                    as arguments.
  stats             show statistics about the library or a query
  update (upd, up)  update the library
  version           output version information
  write             write tag information to files
Sending event: cli_exit
daniele@DanieleMacBookAir2 ~ % clear

user@DanieleMacBookAir2 ~ % beet -vv
user configuration: /Users/daniele/.config/beets/config.yaml
data directory: /Users/daniele/.config/beets
plugin paths: 
Sending event: pluginload
lyrics: Disabling google source: no API key configured.
lyrics: The Genius backend requires BeautifulSoup, which is not installed, so the source is disabled.
library database: /Users/daniele/.config/beets/library.db
library directory: /Volumes/GoogleDrive/My Drive/DaniSynologyNas/Musica
Sending event: library_opened

### Setup

* OS: Mac Catalina 10.15.5
* Python version: 3
* beets version: last
My configuration (output of `beet config`) is:

```yaml

directory: /Volumes/GoogleDrive/My Drive/DaniSynologyNas/Musica

import:
    move: yes
    copy: no
    write: yes

plugins: edit fetchart smartplaylist mpdupdate random embedart random lastimport duplicates missing lyrics

embedart:
    auto: yes                              


mpd:
    host: localhost
    port: 6600


smartplaylist:
    relative_to: /Volumes/GoogleDrive/My Drive/DaniSynologyNas/Musica
    playlist_dir: ~/.mpd/playlists
    playlists:
        - name: allBattiato.m3u
          query: 'artist:Franco Battiato'

        - name: allMuse.m3u
          query: 'artist:Muse'

        - name: allSystemOfaDown.m3u
          query: 'artist:System of a Down'

        - name: allLucioBattisti.m3u
          query: 'artist:Lucio Battisti'
```

**Comment by sampsyo** [comment]
This seems like it's working as expected. What seems to be the problem?

**Comment by entuccio** [comment]
Sam, all solved. Simply I updated my mac, and it works perfectly. Thank you

**Comment by entuccio** [comment]
Thank you
