### ISSUE TITLE
Fix Cover Art Archive request if thumbnail size doesn't exist

### ISSUE THREAD

**Issue by trolley** [beetbox/beets#3638]
I introduced a change with PR#3637 to fetch the particular Cover Art Archive thumbnail image if the `maxwidth` option of `fetchart` is set to exactly one of the values the Cover Art Archive API exposes.

When testing it I tested with an album that had an original cover art with dimensions greater than the largest supported thumbnail, which is 1200px. That worked fine for that album, but I've now realised that if the original cover art size is less than 1200px then there will be no 1200px thumbnail image available to fetch.

To fix this I will make an additional change to ensure that the thumbnail exists, and fall back to the non-thumbnail URL if it does not.

**Comment by sampsyo** [comment]
Aha; makes sense! I merged the reversion PR—feel free to open a new one whenever you like.
