### ISSUE TITLE
would be nice to have an option to not descend into child directories on import

### ISSUE THREAD

**Issue by mikeantonacci** [beetbox/beets#3640]
### Use case

I'm trying to use beets to import my very chaotic, poorly organized music library which requires a lot of manual intervention and often has single tracks in the same directory as many albums. I tried importing with `beet import -q -l log Music` and was going manually through the skipped directories, but when there are large directories containing a mix of single tracks and albums which get skipped, coming back to import them causes it to try to import everything, requiring a lot of manual intervention on the duplicates.

### Solution
It would be nice to have a command line option to prevent `ImportTaskFactory.paths` descending into albums in the same directory.

### Alternatives
I eventually gave up on the way I was trying to import and started over with a combination of `incremental: yes`,  `incremental_skip_later: yes` and `resume: yes`, but it would still be nice to have an option to import the music files in a directory without descending into child directories.

**Comment by sampsyo** [comment]
Interesting! Sounds tricky. To be honest, this is a pretty specialized use case—I wonder if there's a clever `find` invocation that could help here. One option would be to move aside all the second-level directories from your directory structure, like this:

```
mv music/*/*/ music_nested_dirs
```

And then import the single-level hierarchy that remains. Would that make any sense?

**Comment by mikeantonacci** [comment]
Yeah, I guess that would also work. I was really hoping to run the entire import process completely non-destructively, with 550 permissions on everything in the original directory, but it's looking like I'm going to have to abandon that approach and rely on a zfs snapshots if I need to revert.
