### ISSUE TITLE
feat(ci): Add github action that runs weekly(?) for integrated api tests

### ISSUE THREAD

**Issue by jtpavlock** [beetbox/beets#3645]
### Use case

Having integration tests that hit actual APIs and make real requests every once in a while can be a good idea to try and catch when they change things up on us. 

### Solution
Add something like the following to any tests making an actual request:
```
@unittest.skipUnless(os.environ.get(
        'INTEGRATION', '0') == '1', 'real integration tests not enabled')
```

Then, have a github action that runs all tests weekly with this flag enabled.

For a better idea of what the individual tests may look like, [check this out.](https://realpython.com/testing-third-party-apis-with-mocks/#conditionally-testing-scenarios)

I'm not super confident in what the appropriate terminology is here, but I think you get the idea.

Also, if this is implemented. Documentation in the [Testing wiki page](https://github.com/beetbox/beets/wiki/Testing) should include guidance on writing/skipping integration tests

**Comment by sampsyo** [comment]
That's a cool idea. For the lyrics plugin in particular, there are several integration tests that hit the real network that (IIRC) are disabled by default.

Also, this is only semi-related, but #3332 is tracking some poorly behaving tests that are _supposed_ to be unit tests but are actually hitting the network even now.

**Comment by jtpavlock** [comment]
> That's a cool idea. For the lyrics plugin in particular, there are several integration tests that hit the real network that (IIRC) are disabled by default.

That's actually what inspired this :D I noticed those tests have a flag to get skipped normally, but I can't imagine they ever actually get run...
