### ISSUE TITLE
Special name for songs

### ISSUE THREAD

**Issue by entuccio** [beetbox/beets#3652]
Hello :-)

Please don't hate me, but I'm really happy with Beets :-) 

Question:

How can I delete specific letters/symbols whil I'm import in the filename of the song?

In specific I would like to delete "ì$&()+òàè"é*'_-?!" characters in file name, for for example:

Example: non voglio più?.mp3 -> non voglio pi.mp3
Example: mi- piace - l'ho.mp3 -> mi piace  lho.mp3

I assume I can do this defining a path in the configuration of beets, but how?

Thank you very much

**Comment by entuccio** [comment]
nope. Found "replace" 
Sorry ,

**Comment by entuccio** [comment]
added this to configuration:

replace:
    '[\\/]': ''
    '^\.': _
    '[\x00-\x1f]': ''
    '[<>:"\?\*\|]': ''
    '\.$': ''
    '\s+$': ''
    '^\s+': ''
    '[\xf9]': ''
    '[\xfa]': ''
    '[ù]': ''


Why it doesn't replace the character "ù" in files?
beet update seems doesn't work.

thank you

**Comment by sampsyo** [comment]
Hi! That should do it. If your configuration isn't doing what you expect, please file a complete bug so we can reproduce the problem.

**Comment by entuccio** [comment]
Thanks I'll do
