### ISSUE TITLE
Handling case sensitivity of filesystem paths when streaming library between OSes

### ISSUE THREAD

**Issue by Ruin0x11** [beetbox/beets#3654]
### Use Case

I have a beets library I want to share on my home network using Samba, so my Windows machines can access them. The beets instance is running on a Linux server in the same network. However, Windows is case-insensitive, while Linux is not. This means that if an artist gets matched as the same name with different cases (e.g. "Boredoms" and "BOREDOMS") then one of the two directories will show up as "empty" in Windows even though it contains files in Linux, so some of the music in the library will not be visible on those machines only.

Based on [this code](https://github.com/beetbox/beets/blob/9392256993b0cf6f4e2a545d9c504decb71542d9/beets/util/__init__.py#L964) I'm assuming there's already detection in place that is supposed to handle this, but it only checks the operating system of the host that runs the `beet` command, not necessarily the consuming operating systems accessing the files.

### Solution

It would be nice to have a config option like `force_case_insensitive_filesystem` since I know that I will be using Windows to play the files, which would always merge artists with the same case-insensitive name into one folder (so "BOREDOMS" would auto-resolve to an already existing artist in the library named "Boredoms" instead).

### Alternatives

There could be a script that runs periodically that will automatically fix all the artist names that conflict in this way on case-insensitive operating systems, which relieves the user of having to manually rename them all.

**Comment by sampsyo** [comment]
That sounds like a tricky situation! Unfortunately, I don't think a mode like this will be as straightforward as it seems.

Here's how it would work. Every time we do a filesystem operation, check for files on disk that conflict only in case with the new name (by listing the entire directory and comparing one by one, doing this recursively at every level in the directory tree). If there is, modify the path *and store the new path back to the database* so we know where to find the file case-sensitively in the future. Aside from the performance cost of all those directory listings, the downside here is that this creates an unpleasant "feedback loop" between the database and the filesystem: DB changes need to be reflected in the FS, and now FS modifications will need to go back and be reflected in the DB.

So it may be possible to do, but regrettably it's not all that simple. Maybe a good place to start would be prototyping a plugin that does the "periodic fix-up pass" approach just to see how hard it is.
