### ISSUE TITLE
during pluginload ... Name node can't be used with 'None' constant

### ISSUE THREAD

**Issue by rmNULL** [beetbox/beets#3674]
### Problem

running `beet <any command>` crashes
> ValueError: Name node can't be used with 'None' constant

Running this command in verbose (`-vv`) mode:

```sh
$ beet -vv help
```

Led to this problem:

```
user configuration: /home/rmnull/.config/beets/config.yaml
data directory: /home/rmnull/.config/beets
plugin paths: 
Sending event: pluginload
Traceback (most recent call last):
  File "/home/rmnull/.local/bin/beet", line 8, in <module>
    sys.exit(main())
  File "/home/rmnull/.local/lib/python3.8/site-packages/beets/ui/__init__.py", line 1266, in main
    _raw_main(args)
  File "/home/rmnull/.local/lib/python3.8/site-packages/beets/ui/__init__.py", line 1249, in _raw_main
    subcommands, plugins, lib = _setup(options, lib)
  File "/home/rmnull/.local/lib/python3.8/site-packages/beets/ui/__init__.py", line 1144, in _setup
    lib = _open_library(config)
  File "/home/rmnull/.local/lib/python3.8/site-packages/beets/ui/__init__.py", line 1201, in _open_library
    get_path_formats(),
  File "/home/rmnull/.local/lib/python3.8/site-packages/beets/ui/__init__.py", line 619, in get_path_formats
    path_formats.append((query, template(view.as_str())))
  File "/home/rmnull/.local/lib/python3.8/site-packages/beets/util/functemplate.py", line 571, in template
    return Template(fmt)
  File "/home/rmnull/.local/lib/python3.8/site-packages/beets/util/functemplate.py", line 581, in __init__
    self.compiled = self.translate()
  File "/home/rmnull/.local/lib/python3.8/site-packages/beets/util/functemplate.py", line 614, in translate
    func = compile_func(
  File "/home/rmnull/.local/lib/python3.8/site-packages/beets/util/functemplate.py", line 155, in compile_func
    prog = compile(mod, '<generated>', 'exec')
ValueError: Name node can't be used with 'None' constant
```

Here's a link to the music files that trigger the bug (if relevant):

### Setup

* OS: `Linux eos 5.7.9_1 #1 SMP Thu Jul 16 10:02:50 UTC 2020 x86_64 GNU/Linux`
* Python version:  `3.8.4`
* beets version: `1.4.9`(referred from pip list, `beet --version` crashes)
* Turning off plugins made problem go away (yes/no): no

My configuration (output of `beet config`) is:
beet config crashes with the same error mentioned above.
However `beet config -e` works fine

```yaml
directory: /tmp/Music/
library: /tmp/Music/beets_library.db
import:
  move: no
```

### Other Notes
The problem persists on reinstall
 ```sh
$ pip3 uninstall beets
$ pip3 install beets
$ beet help  # same crash
```

I don't see this as a problem in beets,
There was no problem installing beets in docker.
**Clarification**: Asking it as a question to have this issue resolved rather than pointing it as bug in beets.

**Comment by wisp3rwind** [comment]
See https://github.com/beetbox/beets/pull/3621

**Comment by rmNULL** [comment]
@wisp3rwind thanks

**Comment by noodle-** [comment]
Any workaround while we wait for the next release?

**Comment by jackwilsdon** [comment]
[Running the latest source version of beets](https://beets.readthedocs.io/en/latest/faq.html#run-the-latest-source-version-of-beets) is probably the simplest option for the time being.

**Comment by AssenD** [comment]
64bit W10, 64bit Py3.9.0 - same problem

**Comment by jackwilsdon** [comment]
@AssenD please see #3621 and #3625 (as mentioned in [this comment](https://github.com/beetbox/beets/issues/3674#issuecomment-660491334)).

**Comment by davidheijkamp** [comment]
A simple workaround on my Ubuntu machine was to force a specific version of python by changing the shebang in `~/.local/bin/beet` from:

```
#!/usr/bin/python3
```

to:

```
#!/usr/bin/python3.6
```

Probably 3.7 would work as well, if that version of Python is installed on your machine.

**Comment by wisp3rwind** [comment]
> Probably 3.7 would work as well, if that version of Python is installed on your machine.

Yeah, most likely, the relevant Python change wasn't backported to 3.7 as far as I can tell.

**Comment by mores** [comment]
> [Running the latest source version of beets](https://beets.readthedocs.io/en/latest/faq.html#run-the-latest-source-version-of-beets) is probably the simplest option for the time being.

sudo python3 setup.py install hangs after

`...
creating /usr/local/lib/python3.8/dist-packages/beets-1.5.0-py3.8.egg
Extracting beets-1.5.0-py3.8.egg to /usr/local/lib/python3.8/dist-packages
Adding beets 1.5.0 to easy-install.pth file
Installing beet script to /usr/local/bin

Installed /usr/local/lib/python3.8/dist-packages/beets-1.5.0-py3.8.egg
Processing dependencies for beets==1.5.0
Searching for mediafile>=0.2.0
Reading https://pypi.org/simple/mediafile/

< HANGS HERE >
`

**Comment by adamjakab** [comment]
> Probably 3.7 would work as well, if that version of Python is installed on your machine.

Yes, I confirm that it will run with Python 3.7. (`Linux jMac 5.8.0-48-generic #54~20.04.1-Ubuntu SMP Sat Mar 20 13:40:25 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux`) You can easily set up a (mini)conda environment with that specific version version without having to tamper with Python on the OS level.

**Comment by themana** [comment]
Anyone running the docker container from Linuserver.io that is still getting the error if you switch to the nightly build seems to work as a temporary fix until this gets patched in the stable version.
