### ISSUE TITLE
Remove feat from folder name 

### ISSUE THREAD

**Issue by screwfaze** [beetbox/beets#3676]
Hi,

I am a new beets user needing some assistance, I am trying to setup beets so it does not add feat to the folder name at all but cannot find a way to do this. I tried the plugin FtInTitle but does not seem to do what I want. Appreciate any help you can give.

Thanks

**Comment by jtpavlock** [comment]
Hey @screwfaze, welcome to beets! Would you mind posting your question to [our discourse](https://discourse.beets.io/)? We like to keep this issue tracker for bugs and feature requests, thanks!
