### ISSUE TITLE
Questions re the "directory" global option, config.yaml and posix word expansion.

### ISSUE THREAD

**Issue by jaimet** [beetbox/beets#3684]
Hi all.

Could someone please confirm whether or not the options specified in config.yaml are subject to any form(s) of "posix-style" [word expansion](https://pubs.opengroup.org/onlinepubs/009695399/utilities/xcu_chap02.html#tag_02_06) such as [parameter expansion](https://pubs.opengroup.org/onlinepubs/009695399/utilities/xcu_chap02.html#tag_02_06_02) and/or [command substition](https://pubs.opengroup.org/onlinepubs/009695399/utilities/xcu_chap02.html#tag_02_06_03)?

The reason why I am asking is that I was *considering* putting something like:

`directory: $(xdg-user-dir MUSIC)`

into my config.yaml but seeing as:

`beet -v 2>&1 | grep "library directory"`

now returns:

`library directory: /home/user/.config/beets/$(xdg-user-dir MUSIC)`

and running

`beet import ...`

results in the output being copied into:

`~/.config/beets/$(xdg-user-dir MUSIC)` (yes, that's the literal directory name!)

then I guess this is a no-no. TIA, J

Edit: And, presumably, neither `$HOME/music` nor `~/music` are acceptable either.

**Comment by sampsyo** [comment]
Indeed; the configuration does not do shell evaluation. However, `~` _is_ supported as a shorthand for your home directory.

In case you're interested in the code, here's where that `~` expansion happens:
https://github.com/beetbox/confuse/blob/6ffb622d86766e8833be7bcad648be0a714ea958/confuse/templates.py#L533

**Comment by jaimet** [comment]
That's brilliant - thank you for implementing tilde expansion. (And a huge "thank you" for creating beets too!)
