### ISSUE TITLE
Minor documentation correction:  correct id3.org url

### ISSUE THREAD

**Issue by jaimet** [beetbox/beets#3699]
https://github.com/beetbox/beets/blob/master/docs/faq.rst#L303
refers to:
http://www.id3.org/id3v2.4.0-structure
as a reference url for a copy of the ID3v2.4 standard documentation, but this returns a "Not found" error. I've found 2 possibilities for the replacement:
https://id3.org/id3v2.4.0-structure
(with adverts) or
https://github.com/id3/ID3v2.4/raw/master/id3v2.40-structure.txt
(without adverts)

**Comment by sampsyo** [comment]
That's great; thank you! If you have a moment, a pull request would not go amiss. :smiley:
