### ISSUE TITLE
TypeError raised when loading plugin paths

### ISSUE THREAD

**Issue by Victrid** [beetbox/beets#3717]
### Problem

Due to #3674, I've installed the latest source version with command `pip install https://github.com/beetbox/beets/tarball/master` under the [FAQ](https://beets.readthedocs.io/en/stable/faq.html#run-the-latest-source-version-of-beets) guidance.

but it seems that I've got problem in plugin loading. Every command including `beet config` crashes.

Running this command in verbose (`-vv`) mode:

```sh
$ beet -vv 
user configuration: /home/victrid/.config/beets/config.yaml
data directory: /home/victrid/.config/beets
plugin paths: 
Traceback (most recent call last):
  File "/usr/bin/beet", line 8, in <module>
    sys.exit(main())
  File "/usr/lib/python3.8/site-packages/beets/ui/__init__.py", line 1267, in main
    _raw_main(args)
  File "/usr/lib/python3.8/site-packages/beets/ui/__init__.py", line 1250, in _raw_main
    subcommands, plugins, lib = _setup(options, lib)
  File "/usr/lib/python3.8/site-packages/beets/ui/__init__.py", line 1136, in _setup
    plugins = _load_plugins(config)
  File "/usr/lib/python3.8/site-packages/beets/ui/__init__.py", line 1115, in _load_plugins
    beetsplug.__path__ = paths + beetsplug.__path__
TypeError: can only concatenate list (not "_NamespacePath") to list
```

Led to this problem:

Every command leads here.

### Setup

* OS: Arch Linux x86_64
* Python version: Python 3.8.5
* beets version: 1.5.0 (Installed with `pip install https://github.com/beetbox/beets/tarball/master`)
* Turning off plugins made problem go away (yes/no): no

My configuration (output of `beet config`) is:

(Even beet config outputs like this, and this is copied from `~/.config/beets/config.yaml`)
```yaml
directory: ~/Documents/Music
library: ~/Documents/Music/musiclibrary.db
import:
    move: yes
paths:
    default: $album%aunique{}/$disc-$track
    singleton: Non-Album/$artist/$title
    comp: Compilations/$album%aunique{}/$track $title
    ext:jpg: $albumpath/art
    ext:png: $albumpath/art
```

**Comment by Victrid** [comment]
After modifying this https://github.com/beetbox/beets/blob/b89a2650cc8728d21a8aaa48b82e9b24564e44b0/beets/ui/__init__.py#L1115
to 
```python
    beetsplug.__path__ = paths + list(beetsplug.__path__)
```
It get works again.

However, I have little knowledge with python and I don't use any plugins, so I'm not sure this syntax and explicit type convertion is correct. as `_NamespacePath` could be a special list, and not like a normal list, it will be renewed in some circumstances.

**Comment by sampsyo** [comment]
Huh, this is odd. On my machine, which also is running Python 3.8.5, this value has type `list`:

```
$ python3 -c 'import beetsplug; print(type(beetsplug.__path__))'
<class 'list'>
$ python3 --version
Python 3.8.5
```

But it looks like it's doing something quite different on your machine? I am pretty confused about why this is the case, but maybe it can't hurt to add that `list` wrapper defensively…

**Comment by davidswarbrick** [comment]
Also running under Arch, installed beets from git repository (so currently running the master branch), I'm unable to recreate the issue:
```python
~ python
Python 3.8.5 (default, Jul 27 2020, 08:42:51)
[GCC 10.1.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import beetsplug
>>> print(type(beetsplug.__path__))
<class 'list'>
```
`beet <command>` functions correctly

**Comment by wisp3rwind** [comment]
Related: https://github.com/pypa/setuptools/issues/885 and https://docs.python.org/3/reference/import.html#namespace-packages

However, I don't see right now whether this is something we need to cope with, or a broken installation.

**Comment by Victrid** [comment]
Thanks @wisp3rwind, I found that there's another `beetsplug` folder in the .local library, which might be broken and causing this issue.
After removing the folder now beets functions correctly. Maybe this issue can be closed.
