### ISSUE TITLE
ValueError when using application

### ISSUE THREAD

**Issue by chayward1** [beetbox/beets#3719]
### Problem

When using the program a ValueError is returned and the program does not function

Running this command in verbose (`-vv`) mode:

```sh
~ ❯❯❯ beet -vv
user configuration: /home/chris/.config/beets/config.yaml
data directory: /home/chris/.config/beets
plugin paths: 
Sending event: pluginload
Traceback (most recent call last):
  File "/sbin/beet", line 11, in <module>
    load_entry_point('beets==1.4.9', 'console_scripts', 'beet')()
  File "/usr/lib/python3.8/site-packages/beets/ui/__init__.py", line 1266, in main
    _raw_main(args)
  File "/usr/lib/python3.8/site-packages/beets/ui/__init__.py", line 1249, in _raw_main
    subcommands, plugins, lib = _setup(options, lib)
  File "/usr/lib/python3.8/site-packages/beets/ui/__init__.py", line 1144, in _setup
    lib = _open_library(config)
  File "/usr/lib/python3.8/site-packages/beets/ui/__init__.py", line 1201, in _open_library
    get_path_formats(),
  File "/usr/lib/python3.8/site-packages/beets/ui/__init__.py", line 619, in get_path_formats
    path_formats.append((query, template(view.as_str())))
  File "/usr/lib/python3.8/site-packages/beets/util/functemplate.py", line 571, in template
    return Template(fmt)
  File "/usr/lib/python3.8/site-packages/beets/util/functemplate.py", line 581, in __init__
    self.compiled = self.translate()
  File "/usr/lib/python3.8/site-packages/beets/util/functemplate.py", line 614, in translate
    func = compile_func(
  File "/usr/lib/python3.8/site-packages/beets/util/functemplate.py", line 155, in compile_func
    prog = compile(mod, '<generated>', 'exec')
ValueError: Name node can't be used with 'None' constant
~ ❯❯❯ 
```

Led to this problem:

Cannot use the program

```
(paste here)
```

Here's a link to the music files that trigger the bug (if relevant):

### Setup

* OS: Arch Linux 
* Python version: Python 3.8.5
* beets version: 1.4.9 (Latest from pacman)
* Turning off plugins made problem go away (yes/no): 
no

My configuration (output of `beet config`) is:

Command throws the same error as above

```yaml
directory: ~/Music
import:
  move: yes
```

**Comment by sampsyo** [comment]
Please see https://github.com/beetbox/beets/issues/3674.

**Comment by chayward1** [comment]
Can you be more specific? That issue just links to two other issues none of which I can find a fix within?

**Comment by wisp3rwind** [comment]
Those two issues would have told you that this is a known problem which is fixed in a development version but is not released yet due to limited free time of the maintainers. You could also have found a link that explains how to install the latest source as a workaround:

> see the ["How do I run the latest source version of beets?"](https://beets.readthedocs.io/en/stable/faq.html#run-the-latest-source-version-of-beets) section of the FAQ — that should hopefully get you started.

**Comment by chayward1** [comment]
> Those two issues would have told you that this is a known problem which is fixed in a development version but is not released yet due to limited free time of the maintainers. You could also have found a link that explains how to install the latest source as a workaround:
> 
> > see the ["How do I run the latest source version of beets?"](https://beets.readthedocs.io/en/stable/faq.html#run-the-latest-source-version-of-beets) section of the FAQ — that should hopefully get you started.

Didn't see those but I appreciate your help, thank you.
