### ISSUE TITLE
Interactively correct false positive track matches

### ISSUE THREAD

**Issue by tsibley** [beetbox/beets#3724]
### Use case

I imported [an album](https://musicbrainz.org/release/731fb3b3-8edf-41c2-8a15-c5dde34a9f6c) where my copy of a track is misnumbered, and got this:

![image](https://user-images.githubusercontent.com/79913/89724807-89f78300-d9bc-11ea-9d4a-2adadab08905.png)

Notice the complete title change from "Samba Que Nem Rita a Dor" → "Hagua", indicating a very poor match and in this case a false positive match. The file is mis-tagged as track 7 when it should be track 8. The actual track 7, Hagua, is missing from my collection (corruption, argh!), but presumably was mis-tagged as track 8 when I had the file.

### Solution

I don't fault beets for not being able to figure this and trusting the track number, but what I'd love is a way during import to interactively correct the issue.

I have Acoustid enabled, and it also seems like that should be information usable to prevent this sort of false positive. Maybe there could be an interactive option to say "use acoustid info" for a specific track?

### Alternatives

Currently, my only option to correct this is to skip the album or abort the import, re-tag the to-be-imported file outside of beets, and then redo the import.

**Comment by tsibley** [comment]
This seems related but distinct from #2981.

**Comment by sampsyo** [comment]
Hi! This is the idea behind the very old issue #154, although you have explained it much better here. In the modern era, the nicest way to address this would be with an extension to the `edit` plugin, which already lets you edit metadata "on the fly," but IIRC does not let you change the mapping of tracks (or to drop tracks entirely from the match).
