### ISSUE TITLE
Workaround to getting FtInTitle to work when albumartist and artist are the same (when beets is the one assiging the two to be the same)?

### ISSUE THREAD

**Issue by ktrain1** [beetbox/beets#3728]
I've exhausted all search methods of trying to find a solution to this. On importing songs with feat artists, beets is renaming `albumartist` and `artist` to be the same. The issue is that FtInTitle will not work for me unless I manually change the `albumartist` and `artists` fields to be different (as shown in post #1766). There's another couple posts referencing the same issue (#2990 #1983) that were closed without resolution.

Is it possible to maybe change the import settings of beets to assign an individual `artist` while keeping the `albumartist` the same so that FtInTitle will work?

**Comment by ktrain1** [comment]
`# Root directory of your music
directory: /music
# Location where your beets database is saved
library: /config/musiclibrary.blb

# Configure the importing process --------------------------------------------------------

import:
    # write metadata to music files
    write: yes

    # move imported files from source to the music directory
    move: yes
    copy: no
    delete_originals: yes

    # use auto-tagging where possible
    # do not require confirmation on strong matches
    autotag: yes
    timid: no

    resume: ask
    incremental: no
    none_rec_action: ask
    log: /config/beet.log

    quiet: no  # enable with command line option
    quiet_fallback: skip
    default_action: apply

    singletons: no
    languages: []
    detail: no
    flat: no

# Use the original release date of an album when a re-release is added
original_date: yes

# Start counting track numbers back at one for each disc
per_disc_numbering: yes

# files matching these patterns are deleted from source after import
clutter: ["Thumbs.DB", ".DS_Store", "*.m3u", ".pls", "*.jpg"]

# files/directories matching one of these patterns are ignored during import
ignore: [".*", "*~", "System Volume Information"]


# Plugins ---------------------------------------------------------------------

plugins: [

    convert, # Converts parts of your collection to a directory/format of choice
    fetchart, # Downloads album covers
    embedart, # Adds the cover art to the metadata of the audio files
    scrub, # Removes extraneous metadata from files’ tags
    lastgenre, # Downloads genres from last.fm
    #discogs, # Add Discogs as a metadata source
    #beatport, # Add BeatPort as a metadata source
    web, # Web UI
    lyrics, # Downloads lyrics
    #echonest_tempo, #Fetches and stores a track’s tempo
    #mbsync, # Fetch metadata for albums and tracks that already have MusicBrainz ID
    metasync, # Fetch certain metadata from other sources (iTunes, Amarok)
    #fromfilename, # Helps to tag albums that are missing tags altogether
    inline, # Uses small python scripts to add logic the automated file sorting
    #plexupdate, # Notify plex about new media
    ftintitle, # Moves “featured” artists from the artist field to the title field
    #replaygain, # Normalizes audio playback levels
    info,
    #drop2beets,
    
    
    
]


# Plugin Config ---------------------------------------------------------------------    
    
convert:
  auto: yes
  never_convert_lossy_files: no
  ffmpeg: /usr/bin/ffmpeg
  format: alac
  dest: /music
  threads: 2

fetchart:
#   #minwidth: 800
#   #maxwidth: 800
#   #enforce_ratio: yes
  auto: yes
  sources: filesystem coverart itunes amazon albumart fanarttv

embedart:
  auto: yes

scrub:
  auto: yes

lastgenre:
  auto: yes
  canonical: yes
  count: 2
  force: yes
  source: album
  whitelist: yes
  min_weight: 10
  fallback: N/A
  separator: ', '
  prefer_specific: no

#discogs:
  source_weight: 0.0

web:
  host: 0.0.0.0
  port: 8337

Lyrics:
  auto: yes
  fallback: ''
  force: yes
  google_API_key:
  google_engine_ID: 009217259823014548361:lndtuqkycfu
  sources: google lyricwiki musixmatch genius

#echonest_tempo:
 #   auto: yes

#mbsync:

metasync:
  source: itunes
  itunes:
     Library: /config/iTunes.xml alias

#fromfilename:

inline:

#plexupdate:
  host: 
  port: 
  token: 
  
ftintitle:
  auto: yes
  drop: no
  format: (feat. {0})
  
replaygain:
  auto: no
  
#drop2beets:
  dropbox_path: 


# User Interface -------------------------------------------------------------

color: yes
list_format_item: %upper{$artist} - $album - $track. $title
list_format_album: %upper{$albumartist} - $album
time_format: '%Y-%m-%d %H:%M:%S'
terminal_encoding: utf8

ui:
    terminal_width: 80
    length_diff_thresh: 10.0


# General ---------------------------------------------

# Use multiple cores?
threaded: yes
timeout: 5.0
verbose: no


# Paths ----------------------------------------------------------------------

paths:
# For the normal albums and eps. Used when none of the other paths should be used
# boysetsfire/(2000) After the Eulogy [Album]/02 - Rookie.flac
# Oliver Koletzki/(2019) We Are All Lost/1 - 02 - Oliver Koletzki; Monolink - We Are All Lost.flac
  #default: $albumartist/($year) $album%aunique{}$myAlbumType/%if{$isMultidisc,$disc - }$track - $mySongartist$title
  default: $albumartist/$album%aunique{}/$track - $title

# For single songs. Used when 'singleton:true' is set 
  singleton: Non-Album/$artist - $title

# For sampler and compilations. Used when 'comp:true' is set
# Compilations/Giegling/(2017) Planet Giegling/03 - Kettenkarussell - Walk With Me.flac
  #comp: $albumartist/($year) $album%aunique{}/$myDisc$track - $artist - $title
  #comp: Compilations/$album%aunique{}/$track - $title
  comp: $album ($year)/$track - $artist - $title

# For Soundtracks. Used when 'albumtype:soundtrack'
# Soundtracks/Trent Reznor & Atticus Ross/Watchmen_ Volume 1 (Music From the HBO Series) (2019)/04 - Trent Reznor & Atticus Ross - Nun With a Motherf_&_ing Gun.flac
  #albumtype:soundtrack: Soundtracks/$albumartist/$album%aunique{} ($year)/$myDisc$track - $artist - $title
  albumtype_soundtrack: Soundtracks/$album%aunique{}/$track $title

# replace special characters in generated filenames
replace:
    '[\\/]': _
    '^\.': _
    '[\x00-\x1f]': _
    '[<>:"\?\*\|]': _
    '\.$': _
    '\s+$': ''
    
path_sep_replace: _

# filename for the album art
art_filename: cover  # results in "cover.jpg"

max_filename_length: 0  # unlimited

aunique:
    keys: albumartist album
    disambiguators: albumtype year label catalognum albumdisambig releasegroupdisambig
    bracket: '[]'

item_fields:
# 'Nine Inch Nails - ' or '' depending if the artist differs from the album artist
  mySongartist: artist + ' - ' if artist != albumartist and artist != '' else ''

# Release with multiple discs? For boolean operations
  isMultidisc: 1 if disctotal > 1 else 0

# Changes the case of the album type 
  myAlbumType: ('' if albumtype == '' else ' [' + ('EP' if albumtype == 'ep' else albumtype.capitalize()) + ']')

# '1 - ' or '' depending if there are multiple discs or not
  myDisc: ('' if disctotal <= 1 else str(disc) + ' - ')

# Same as above but on album basis
#album_fields:
#  bitrate: |
#          total = 0
#          for item in items:
#              total += item.bitrate
#          return total / len(items)



# Auto Tagger ----------------------------------------------------------------

match:
    strong_rec_thresh: 0.1      # match 90% or better for auto import
    medium_rec_thresh: 0.25
    rec_gap_thresh: 0.25
    max_rec:
        missing_tracks: medium
        unmatched_tracks: medium
    distance_weights:
        source: 2.0
        artist: 3.0
        album: 3.0
        media: 1.0
        mediums: 1.0
        year: 1.0
        country: 0.5
        label: 0.5
        catalognum: 0.5
        albumdisambig: 0.5
        album_id: 5.0
        tracks: 2.0
        missing_tracks: 0.9
        unmatched_tracks: 0.6
        track_title: 3.0
        track_artist: 2.0
        track_index: 1.0
        track_length: 2.0
        track_id: 5.0
    preferred:
        countries: []
        media: []
        original_year: no
    ignored: []
    track_length_grace: 10
    track_length_max: 30
`

**Comment by ktrain1** [comment]
import:
    # write metadata to music files
    write: yes

    # move imported files from source to the music directory
    move: yes
    copy: no
    delete_originals: yes

    # use auto-tagging where possible
    # do not require confirmation on strong matches
    autotag: yes
    timid: no

    resume: ask
    incremental: no
    none_rec_action: ask
    log: /config/beet.log

    quiet: no  # enable with command line option
    quiet_fallback: skip
    default_action: apply

    singletons: no
    languages: []
    detail: no
    flat: no

# Use the original release date of an album when a re-release is added
original_date: yes

# Start counting track numbers back at one for each disc
per_disc_numbering: yes

# files matching these patterns are deleted from source after import
clutter: ["Thumbs.DB", ".DS_Store", "*.m3u", ".pls", "*.jpg"]

# files/directories matching one of these patterns are ignored during import
ignore: [".*", "*~", "System Volume Information"]


# Plugins ---------------------------------------------------------------------

plugins: [

    convert, # Converts parts of your collection to a directory/format of choice
    fetchart, # Downloads album covers
    embedart, # Adds the cover art to the metadata of the audio files
    scrub, # Removes extraneous metadata from files’ tags
    lastgenre, # Downloads genres from last.fm
    discogs, # Add Discogs as a metadata source
    #beatport, # Add BeatPort as a metadata source
    web, # Web UI
    lyrics, # Downloads lyrics
    #echonest_tempo, #Fetches and stores a track’s tempo
    #mbsync, # Fetch metadata for albums and tracks that already have MusicBrainz ID
    metasync, # Fetch certain metadata from other sources (iTunes, Amarok)
    #fromfilename, # Helps to tag albums that are missing tags altogether
    inline, # Uses small python scripts to add logic the automated file sorting
    #plexupdate, # Notify plex about new media
    ftintitle, # Moves “featured” artists from the artist field to the title field
    #replaygain, # Normalizes audio playback levels
    info,
    #drop2beets,
      
    
]


# Plugin Config ---------------------------------------------------------------------    
    
convert:
  auto: yes
  never_convert_lossy_files: no
  ffmpeg: /usr/bin/ffmpeg
  format: alac
  dest: /music
  threads: 2

fetchart:
#   #minwidth: 800
#   #maxwidth: 800
#   #enforce_ratio: yes
  auto: yes
  sources: filesystem coverart itunes amazon albumart fanarttv

embedart:
  auto: yes

scrub:
  auto: yes

lastgenre:
  auto: yes
  canonical: yes
  count: 2
  force: yes
  source: album
  whitelist: yes
  min_weight: 10
  fallback: N/A
  separator: ', '
  prefer_specific: no

discogs:
  source_weight: 0.0

web:
  host: 0.0.0.0
  port: 8337

Lyrics:
  auto: yes
  fallback: ''
  force: yes
  google_API_key:
  google_engine_ID: 009217259823014548361:lndtuqkycfu
  sources: google lyricwiki musixmatch genius

#echonest_tempo:
 #   auto: yes

#mbsync:

metasync:
  source: itunes
  itunes:
     Library: /config/iTunes.xml alias

#fromfilename:

inline:

#plexupdate:
  host: 
  port: 
  token: 
  
ftintitle:
  auto: yes
  drop: no
  format: (feat. {0})
  
replaygain:
  auto: no
  
#drop2beets:
  dropbox_path: 


# User Interface -------------------------------------------------------------

color: yes
list_format_item: %upper{$artist} - $album - $track. $title
list_format_album: %upper{$albumartist} - $album
time_format: '%Y-%m-%d %H:%M:%S'
terminal_encoding: utf8

ui:
    terminal_width: 80
    length_diff_thresh: 10.0


# General ---------------------------------------------

# Use multiple cores?
threaded: yes
timeout: 5.0
verbose: no


# Paths ----------------------------------------------------------------------

paths:
# For the normal albums and eps. Used when none of the other paths should be used
# boysetsfire/(2000) After the Eulogy [Album]/02 - Rookie.flac
# Oliver Koletzki/(2019) We Are All Lost/1 - 02 - Oliver Koletzki; Monolink - We Are All Lost.flac
  #default: $albumartist/($year) $album%aunique{}$myAlbumType/%if{$isMultidisc,$disc - }$track - $mySongartist$title
  default: $albumartist/$album%aunique{}/$track - $title

# For single songs. Used when 'singleton:true' is set 
  singleton: Non-Album/$artist - $title

# For sampler and compilations. Used when 'comp:true' is set
# Compilations/Giegling/(2017) Planet Giegling/03 - Kettenkarussell - Walk With Me.flac
  #comp: $albumartist/($year) $album%aunique{}/$myDisc$track - $artist - $title
  #comp: Compilations/$album%aunique{}/$track - $title
  comp: $album ($year)/$track - $artist - $title

# For Soundtracks. Used when 'albumtype:soundtrack'
# Soundtracks/Trent Reznor & Atticus Ross/Watchmen_ Volume 1 (Music From the HBO Series) (2019)/04 - Trent Reznor & Atticus Ross - Nun With a Motherf_&_ing Gun.flac
  #albumtype:soundtrack: Soundtracks/$albumartist/$album%aunique{} ($year)/$myDisc$track - $artist - $title
  albumtype_soundtrack: Soundtracks/$album%aunique{}/$track $title

# replace special characters in generated filenames
replace:
    '[\\/]': _
    '^\.': _
    '[\x00-\x1f]': _
    '[<>:"\?\*\|]': _
    '\.$': _
    '\s+$': ''
    
path_sep_replace: _

# filename for the album art
art_filename: cover  # results in "cover.jpg"

max_filename_length: 0  # unlimited

aunique:
    keys: albumartist album
    disambiguators: albumtype year label catalognum albumdisambig releasegroupdisambig
    bracket: '[]'

item_fields:
# 'Nine Inch Nails - ' or '' depending if the artist differs from the album artist
  mySongartist: artist + ' - ' if artist != albumartist and artist != '' else ''

# Release with multiple discs? For boolean operations
  isMultidisc: 1 if disctotal > 1 else 0

# Changes the case of the album type 
  myAlbumType: ('' if albumtype == '' else ' [' + ('EP' if albumtype == 'ep' else albumtype.capitalize()) + ']')

# '1 - ' or '' depending if there are multiple discs or not
  myDisc: ('' if disctotal <= 1 else str(disc) + ' - ')

# Same as above but on album basis
#album_fields:
#  bitrate: |
#          total = 0
#          for item in items:
#              total += item.bitrate
#          return total / len(items)



# Auto Tagger ----------------------------------------------------------------

match:
    strong_rec_thresh: 0.1      # match 90% or better for auto import
    medium_rec_thresh: 0.25
    rec_gap_thresh: 0.25
    max_rec:
        missing_tracks: medium
        unmatched_tracks: medium
    distance_weights:
        source: 2.0
        artist: 3.0
        album: 3.0
        media: 1.0
        mediums: 1.0
        year: 1.0
        country: 0.5
        label: 0.5
        catalognum: 0.5
        albumdisambig: 0.5
        album_id: 5.0
        tracks: 2.0
        missing_tracks: 0.9
        unmatched_tracks: 0.6
        track_title: 3.0
        track_artist: 2.0
        track_index: 1.0
        track_length: 2.0
        track_id: 5.0
    preferred:
        countries: []
        media: []
        original_year: no
    ignored: []
    track_length_grace: 10
    track_length_max: 30>

**Comment by sampsyo** [comment]
Hi! I'm having some trouble understanding exactly what's going on here and what you're hoping for. Can you give concrete examples of a case you wish were handled differently?

**Comment by ktrain1** [comment]
Sorry for the confusion-

FtInTitle will not do anything for me on import. If I import a song featuring someone, beets changes both the `artist` and the `albumartist` fields to "artist 1 featuring artist 2". This makes organization a nightmare for albums containing an individual song that features another artist.

The only way I can get get FtInTitle to function properly (that I know of), is to follow your manual recommendation from back in 2015 in post #1776 

> Yep, you're expecting the right thing! I think the problem is this:
>
> `albumartist: Avicii feat. Salem Al Fakir'
>
> The plugin wants to work on songs where the albumartist is the single "real" artist and the plain artist field has the "feat." in it. Here, the "feat." shows up in both artist names. I think it would work if the albumartist were just Avicii. Perhaps you can confirm this using something like beet modify albumartist=Avicii ... as a test.

I really don't want to have to manually adjust every imported song as such, so I was hoping that there would be another way to get FtInTitle to function automatically on import.

**Comment by sampsyo** [comment]
> FtInTitle will not do anything for me on import. If I import a song featuring someone, beets changes both the `artist` and the `albumartist` fields to "artist 1 featuring artist 2".

This is not always true—remember that beets is just pulling data from MusicBrainz. In MusicBrainz, most albums are attributed to single artists, like this one:
https://musicbrainz.org/release/281db302-3455-4794-a41d-db78b86b4bcc

Track 4 is by "Taylor Swift feat. Bon Iver" but the album is by "Taylor Swift." This is the kind of case that `ftintitle` targets.

As that old comment suggested, perhaps you can confirm that this is what's actually going on by manually modifying a single album and seeing if it works then? If so, then the next step would be to propose a strategy to deal with albums in this format. It might be useful to start with the current policy, which is implemented here:
https://github.com/beetbox/beets/blob/eb6bbaeee8c2cb9ac143cbdc41be0f4c62d1fb94/beetsplug/ftintitle.py#L48

**Comment by ktrain1** [comment]
> Track 4 is by "Taylor Swift feat. Bon Iver" but the album is by "Taylor Swift." This is the kind of case that `ftintitle` targets.

Ahh ok. I think that's where my disconnect on FtInTitle's expectations is. The song that I've been using for my trial and error is a single release, not a full album- Happy Anywhere (feat. Gwen Stefani), by Blake Shelton. I didn't think the two album types (full album vs single) would be treated differently, but it makes sense that they are.

> As that old comment suggested, perhaps you can confirm that this is what's actually going on by manually modifying a single album and seeing if it works then?

You are correct. After import, if I manually change the 'albumartist' to just Blake Shelton, FtInTitle will finally adjust the song title to "Happy Anywhere (feat. Gwen Stefani)". So as you say- what I'm looking to accomplish (with Single releases at least) isn't currently within FtInTitle's capabilities.

Thank you for the clarification.
