### ISSUE TITLE
Option to rewrite file if max padding size exceeded

### ISSUE THREAD

**Issue by jvanhie** [beetbox/beets#373]
I have quite a large selection of music with some very big artwork in it, due to bad tagging in the past or overzealous artists that pack seemingly uncompressed artwork in their files. This combined with XBMC on the Raspberry Pi that only reads the first MiB to try and detect the format gives quite a few unplayable albums.

I tried re-importing the albums using beets and the maxwidth option of the embedart plugin, but noticed that the filesize stays the same (and thus the way-too-big ID3v2 tags, that contain mainly padding now).

It would be great to have an option to let beets rewrite the files it tags if the amount of padding in the ID3v2 tag reaches a certain (user editable) limit. I only found this option in Tag&Rename, a Windows tagging tool.

**Comment by lazka** [comment]
mutagen will remove padding if it is larger than a certain amount since 1.31 for all formats. I think this can be closed.

**Comment by sampsyo** [comment]
Great; thanks, @lazka.
