### ISSUE TITLE
New field: filename

### ISSUE THREAD

**Issue by pimpsky** [beetbox/beets#3734]
### Use case
`~/youtube-dl/bunch-of-mostly-unreleased-poorly-tagged-soundcloud-music/` has 2,000+ tracks, with few if any tags, and I'm not interested in tagging any of it properly, even if perhaps some of it is released.
The filename pattern for each track, as indicated in my config for youtube-dl, is:  `%(upload_date)s-%(uploader_url)s-%(uploader)s-%(title)s.%(ext)s`. Plenty of information to tell each track apart.
`beet ls` outputs 2000+ lines that look like this: ` - - ` because by default the formatting is `$artist - $album - $title` yet there are no artist, album, or title tags in any of the files 
### Solution

A field for filenames would be useful for me because often the music I download from SoundCloud via youtube-dl doesn't have any tags, and so there's nothing to identify the tracks except the filename. Here's how I might use a `filename` field to address the scenario above:

`beet ls -f '$filename' filename+`
This would output the filenames of all of the 2000+ tracks, in alphabetical order.

Also, because Plex, and media players generally, don't have filename columns, only columns for title, year, album, artist, etc, I'd like to be able to copy the filename to the title tag; This might be done via:
`beet modify 'path=~/youtube-dl/bunch-of-unreleased-poorly-tagged-soundcloud-music/' 'title=filename'`. 

Both of these things are possible in Mp3Tag.
![Mp3tag_3uT8Mlot0b](https://user-images.githubusercontent.com/70082105/90999035-84d92d00-e593-11ea-83b3-d691e27d94c8.png)
![image](https://user-images.githubusercontent.com/70082105/90998003-04193180-e591-11ea-8800-5a0b090984c1.png)

In addition to the `filename` tag, I would also appreciate a `filename_ext` tag, which includes the extension in the filename, i.e. `01 Jahkra.flac` as opposed to `01 Jahkra`

### Alternatives

I have not found any plugin that does something similar.

**Comment by sampsyo** [comment]
There is already a `$path` field that you can use for this purpose. Combined with the `inline` plugin, you can use `os.path.basename`, for example, to get the filename out.

**Comment by pimpsky** [comment]
I'm sorry, I didn't notice `$path` when I did `beet fields` but now I see it. Also, I looked at the docs again to check out what the `inline` plugin can do and see that one of the example with `os.path.basename` is literally a copy & paste solution to my problem. I'm able to do `beet ls -f '$filename' filename+` now. Thanks!
