### ISSUE TITLE
Set Field to the value of another field

### ISSUE THREAD

**Issue by pimpsky** [beetbox/beets#3735]
### Use case
`~/youtube-dl/bunch-of-mostly-unreleased-poorly-tagged-soundcloud-music/` has 2,000+ tracks, with few if any tags, and I'm not interested in tagging any of it properly, even if perhaps some of it is released. The filenames contain information about the name of the track on SoundCloud, the uploader's account name, the date the track was uploaded, etc. Plex, the media player I use to stream my music, doesn't have filename columns— only columns for title, year, album, artist, etc. Since my SoundCloud music doesn't have any title tags, there's no way for Plex to tell me what I'm listening to. 

### Solution

I propose a feature that allows you to set the value of one field to the value of another. If that was possible, I'd be able to solve my problem by setting each track's title tag to their filenames. The command for this could look like:

`beet modify 'path=~/youtube-dl/bunch-of-unreleased-poorly-tagged-soundcloud-music/' 'title=$filename'`. 

(where $filename is a template field, which I've defined exactly as it's defined in the example code under "Block Definitions" in the "Inline Plugin" section of the Beets documentation.)

This is is possible in Mp3Tag:
![image](https://user-images.githubusercontent.com/70082105/90998003-04193180-e591-11ea-8800-5a0b090984c1.png)

### Alternatives

I have not found any plugin that does something similar.

**Comment by sampsyo** [comment]
Please see #488.
