### ISSUE TITLE
Cannot split album

### ISSUE THREAD

**Issue by wokast** [beetbox/beets#3736]
There does not seem to be a way to split an album, dividing up the tracks into two new albums. 

Simply changing the album field on the individual tracks leads to inconsistencies, since they apparently remain associated to one and the same album object. For example, a path using the $album field does ignore the change of the tracks album field and uses the old album field stored on some album level. Using the -a option for modify or edit does not solve this either because this applies to all tracks in the album, with no possibility to specify a a subset.

The use case for me is the following: I am organizing all classical music differently, such that artist is the composer and album the composition (adding a field for performer). In other words, I try to create virtual albums that do not correspond to some lumped together released CD but to the logical structure of the body of work of a composer. For this, I was trying to get all fields pre-filled by the autotagger so I don't have to manually enter everything, just copy and paste between fields.

**Comment by sampsyo** [comment]
Hello! Indeed; the canonical way to do this currently is a re-import. If you `beet import` a subset of the files, I think (hope) they should be gathered into a new album and separated from the old one. Can you give that a shot (after making a backup in case I'm wrong)?

**Comment by wokast** [comment]
Thanks for the quick response. I tried to re-import, but ran into similar problems. Since the imported files in the collection are all in the same directory, I used the -L option to import instead for disambiguation, querying for the per-track modified album name. The same query with beet ls gives me the correct subset. The re-import apparently picked up the modified album name from the single tracks. With the edit plugin I could see that only the subset I specified was present. Selecting the Use-as-is option, they were indeed gathered into a new album with the correct name. The problem is that the complementary subset was also assigned to this album. Effectively,  the re-import of the subset just renamed the whole album to the album name used in the subset. 

I note that even if the approach would have worked, it is still more cumbersome than manually splitting files into two folders before importing them for the first time (the kind of workflow I hoped to avoid). If splitting already imported album is difficult, is there a way to split an album during first import? For example, could I simply use the edit plugin to set different album names for each to-be-imported file?

**Comment by sampsyo** [comment]
Arg; I am actually not very sure why that didn't work—I would have expected it to create a new album structure. If not, maybe this is something we should add.

Unfortunately, I am not aware of another way to split albums during import. The `--group-albums` flag is not exactly what you want because it is not an interactive option, but it is along similar lines.

**Comment by wokast** [comment]
All right. Moving the files to different folders before import worked reasonably well, so splitting existing albums is not a must-have feature for me. For reference here is the version I was using (installed via the Arch Linux package):

$beet --version
beets version 1.4.9
Python version 3.8.5
plugins: chroma, duplicates, edit, fetchart, lastgenre, missing, replaygain, scrub, zero
