### ISSUE TITLE
Add traktor plugin

### ISSUE THREAD

**Issue by 16pierre** [beetbox/beets#3738]
### Use case

Export library to Traktor:
- ratings
- musical information (bpm, key etc.) ?
- playlists / smartPlaylists

Import Traktor -> beets ?

Extra fanciness:
- utils to handle custom tags in Traktor (for example "energy" etc.), see below about [another project of mine](https://github.com/16pierre/traktorPlaylistExport)

Related to:
- https://github.com/beetbox/beets/issues/3419 (replaced by https://github.com/beetbox/beets/issues/1403)

### Solution

**Export to Traktor**:

When exporting beets -> traktor, it's probably too hacky to insert songs that have not been analyzed yet into Traktor's collection. I would suggest a workflow like this:
- open Traktor, analyse the songs found in the beets directory
- close Traktor: `collection.nml` is then updated by Traktor, new tracks are added
- run `beet traktor export` (or sth of the sort) to export the tracks metadata (write directly to `collection.nml`)

**Metadata storage in beets**: 
- use core tags when available (i.e.: initialKey etc. https://github.com/beetbox/beets/issues/637)
- add custom tags for everything else

**Playlist export**:

I'm open to suggestions about playlist export. In my [previous project](https://github.com/16pierre/traktorPlaylistExport), I used a hacky workflow based on the smartPlaylist plugin, there's probably a better integration to write here.

**Other**:

For the record: useful library to read/write to Traktor nml library: https://github.com/wolkenarchitekt/traktor-nml-utils

### Alternatives

I wrote a quick and dirty project to sync ratings & playlists to Traktor:
https://github.com/16pierre/traktorPlaylistExport

In this repo, I also used the smartplaylist plugin to generate the playlists, then sync them to Traktor.
I also added a "scanner" to help tag the songs and then generate the smartplaylists + comments on the track (this helps me generate playlists like "genre:House energy:5 mood:dark" etc.)

Back then I was too lazy to write a plugin, but I think it'd be better to have a clean integration in beets through a plugin instead of an external CLI: that's why I'm opening this issue. 

Happy to have your suggestions to design cool features & an implementation for this !

**Comment by sampsyo** [comment]
Hi! This sounds interesting, although I don't know much at all about Traktor or how one would import to/export from it.

Is there anything specific we can do to help you get started with the plugin-ification of your existing work?

**Comment by 16pierre** [comment]
I'll add more information about the exact export mechanism alongside some code, that'd probably be clearer

> Is there anything specific we can do to help you get started with the plugin-ification of your existing work?
I'll navigate the existing `beets` codebase and ask for help if needed, thanks ! Overall I should be OK in terms of code, the main question is rather the _range of features_ to be included in this plugin.

For example in my previous project, I added a bunch of utils to prompt tags for the different tracks (like "genre?", "House/Techno/etc.", "rating? 1/2/3..."), and utils to generate a `beets` config file that includes the `smartPlaylists` associated with these tags - that was extremely useful for me, because Traktor doesn't support filtering/sorting by custom tags : I used playlists instead. (Note: I'd implement a cleaner solution for this project though, re-generating the beets config file was really quick and dirty. We probably don't need the `smartPlaylist` dependency here)

So my main concern would be: how much features should I implement in this plugin ? Is there any guidelines about the scope of plugin development ? (i.e. one could argue that prompting for tags is out of scope of a `traktor` plugin)

But I guess I can start with very basic features like syncing ratings, and then we can iterate over it.

**Comment by sampsyo** [comment]
I think the best way to go would be to start developing the plugin independently, i.e., not as part of beets—that will let you go wild and include anything you want! Then perhaps you will find that you have core functionality that will be relevant to others, at which point it would be a good time to include the plugin with the beets distribution.

I do think that prompting for tags is probably not necessary. We do already have `beet modify` for setting field values. Starting with syncing seems like a good idea.

**Comment by RollingStar** [comment]
Traktor is DJ software if anyone was wondering. https://en.wikipedia.org/wiki/Traktor

**Comment by 16pierre** [comment]
Have been adding a bunch of features and docs to my external tool (renamed repo: https://github.com/16pierre/traktorBeetsIntegration)

Now sync between Traktor and Beets works both ways, I tried to illustrate that in a quick video https://youtu.be/Mryh9AjpmfU
