### ISSUE TITLE
Differentiate between box set and genuine multi-disc releases

### ISSUE THREAD

**Issue by menelaos** [beetbox/beets#3753]
Is it possible for `beets` to differentiate between genuine multi-disc releases and box set releases?

By "genuine multi-disc" releases I mean releases that have been planned as multi-disc releases from the get-go (like https://musicbrainz.org/release/b346202e-433b-4baf-8838-2d54c169f2f0). 

A "box set" release refers to a collection of previously released items that have been boxed as a sales unit (e.g. https://musicbrainz.org/release/eae52693-c8f9-422b-93c7-9630d3d14832 or Original Album Classics).

In the first case, I want to retain both the release title (`$album`) and the `$disctitle`.
In the second case, I basically want to drop the release title (Original Album Classics) and use the `$disctitle` value
for `$album`.

The way MusicBrainz currently differentiates between the two cases is via the [`included in`](https://musicbrainz.org/relationship/589447ea-be2c-46cc-b9e9-469e1d06e18a) relationship.

**Comment by sampsyo** [comment]
Interesting! It seems like the main thing we need to do is to fetch & store the relevant data from MusicBrainz (from that "included in" relationship), and then downstream tools (either fancy `modify` commands or custom plugins) can use it to implement the policy that you want.

Do you have any ideas about how exactly beets might represent that information? That is, what field should beets create, and how should it be populated according to information available via the MusicBrainz web service?

**Comment by menelaos** [comment]
Well, maybe there's an even easier way. I guess in most cases, a box set release will have the individual album titles as the disc titles. So maybe something like the following (pseudo-Haskell) would work:
```haskell
if isBoxSet
  then populateALBUMFieldWith discTitle
  else populateALBUMFieldWith releaseTitle -- what we currently do
```

**Comment by sampsyo** [comment]
I suppose I was getting at an even more basic question: how are we going to populate the `isBoxSet` field? If we collect that, then beets doesn't have to bake in any specific policy, about which reasonable people may disagree. We can leave the question of "what does the album field get populated with?" up to users.

**Comment by RollingStar** [comment]
I get around this Beets behavior by using the disc name in my paths. It relies on people filling in the disc name, and doesn't change the tags, so my last.fm results are screwy.

**Comment by menelaos** [comment]
Couldn't that be done via `release-group-rels`? Something like https://musicbrainz.org/ws/2/release-group/98e078fe-37d9-43f7-8bb4-96526727c4e0?inc=aliases+artist-credits+releases+release-group-rels&fmt=json

Then:
```Use disc title for album field <=> Disc title appears in the list of included titles```

Another possibility could be a flag `--use-disc-title-for-album-field`.

**Comment by sampsyo** [comment]
I'm still a little stumped here. Could you perhaps explain at one level of greater detail how we'd use a MusicBrainz API response to determine the "Disc title appears in the list of included titles" predicate?

To do this manually instead of automatically, maybe you'd be interested in https://github.com/beetbox/beets/issues/488.
