### ISSUE TITLE
Windows: Thumbnails crashes 

### ISSUE THREAD

**Issue by Manueloccorso** [beetbox/beets#3757]
fetchart crashes after downloading one new album cover, then if restarted it downloads another one and crashes again, and so on and so forth. 
I think the problem is more related to the plugin thumbnails, since the last log is about it, and disabling it make the crash disappear. 

### Problem

Running this command in verbose (`-vv`) mode:
```sh
$ beet -vv fetchart
```
Led to this problem:
gist of the traceback and verbose log: https://gist.github.com/Manueloccorso/41d6802466da45893eac210b628cd2be

### Setup

* OS:  Windows 10
* Python version: 3.7
* beets version: latest (? installed today via pip)
* Turning off plugins made problem go away (yes/no): -

**Comment by Manueloccorso** [comment]
Ok, probably it's the same bug as in #3455 .

**Comment by sampsyo** [comment]
Indeed!
