### ISSUE TITLE
Fields should differentiate plugin and inline fields from base fields

### ISSUE THREAD

**Issue by RollingStar** [beetbox/beets#3760]
### Use case

I'm trying to use beets to develop beets and understand my library. Right now `beet fields` dumps a huge pile of fields on the user and there's a lot going on.

Current (truncated) output of `beet fields`:

``` 
Item flexible attributes:   
  data_source               
  track_alt                 
  alt.sd                    
  condition
```

### Solution

Proposed new format (open to suggestions):

``` 
Item flexible attributes:   
  data_source               
  track_alt                 
* alt.sd                    
+ condition
```

 `*` for plugin fields and `+` for inline fields. It's [not documented](https://beets.readthedocs.io/en/latest/reference/cli.html#fields), but are plugins and inline fields listed last in "flexible attributes" anyway? For album fields they are definitely not separated. I poked around in the code and didn't get anywhere on how plugin fields are read by beets.

### Alternatives

Don't make the change since it's not a big deal. Make it a command line switch to preserve some compatibility.

**Comment by sampsyo** [comment]
This is an interesting suggestion! For what it's worth, there is actually no such thing as a "plugin field" in beets—there are *flexible attributes*, which plugins often use, but you can also set flexattrs yourself manually using `beet modify`, for example, and there is no way to track where an attribute "came from."

However, there is such a thing as "computed fields," of which you can read more about in `db.py`:
https://github.com/beetbox/beets/blob/master/beets/dbcore/db.py#L208-L209

Computed fields are typically from plugins, although some (namely, `singleton` and `filesize`) are built in. Fields from the `inline` plugin are computed fields.

We could imagine distinguishing between those three types: fixed, flexible, and computed. But I'm not 100% sure how helpful that would be for users by itself.

**Comment by RollingStar** [comment]
I agree; minimal value from differentiating fixed/flexible/computed. What would the path be for distinguishing base/plugin fields in beets? Adding some kind of attribute to plugins that is voluntary at first, then required? Is it too much work for (admittedly) little benefit?

There might be a side benefit beyond reducing user confusion - more understandable code and pipeline.

**Comment by sampsyo** [comment]
Yeah, that's the thing—it would require additional bookkeeping in the database, somewhere or other. We don't currently keep track anywhere of where values came from. In fact, there may be no well-defined answer to that: for example, what if you originally set the value with `beet modify` and then a plugin later changes it? It's hard to say who to "blame" in that case.
