### ISSUE TITLE
MQA

### ISSUE THREAD

**Issue by Extarys** [beetbox/beets#3768]
### Use case

I'd like a way for beet to detect MQA file so we can properly tag them in the folder name/path.

### Solution
Implement a `$is_mqa` variable. example: `$if{$is_mqa, [MQA]}`

I won't be buying MQA files again, but I'm sure other users would like to properly tag them.

**Comment by sampsyo** [comment]
Hi! Can you explain a little bit more about what an MQA file is and how software might detect them?

**Comment by RollingStar** [comment]
https://github.com/redsudo/mqaid

https://en.wikipedia.org/wiki/Master_Quality_Authenticated

**Comment by Extarys** [comment]
I'm having a hard time understanding how it works but from what I understood: It is a proprietary file format that "hides" more data in the lower band into a FLAC container. A decoder could use the hidden lossy info in the lower band to generate 96-24+ files. Tidal uses this. It allows for a smaller file size with debatable higher audio quality and there is quite a lot of controversy surrounding this format.

I didn't know about mqaid, looks neat!

**Comment by sampsyo** [comment]
Huh, that's interesting! Do y'all know whether beets can currently import these files—i.e., do they "look" like FLAC files to the Mutagen library? Or would Mutagen need to learn about a new container format?

**Comment by Extarys** [comment]
@sampsyo I didn't test it but MQA is not in their docs nor it is mentioned on their github repo (quodlibet/mutagen). So I presume an issue/PR there is required.

**Comment by sampsyo** [comment]
I suppose what I meant to clarify is: what happens currently if you try to import such a file into beets with the `beet import` command? Does it do anything at all?

**Comment by Extarys** [comment]
Well the file look like flac files and beet can import them and tag them. I can also fingerprint them and use acousticbrainz on them.

The only difference I found in the metadata is that some files/albums have "MQAEncoder" value as the "Encoder".
