### ISSUE TITLE
Docs: LyricsWiki was shut down. Link is still up

### ISSUE THREAD

**Issue by Jonta** [beetbox/beets#3776]
https://github.com/beetbox/beets/blob/2b8a2eb96bcaf418cdfcc0cfe762a18e31cff138/docs/plugins/lyrics.rst

Or does beets use a content dump of it?

Link is 404 anyway

Shutdown was on 21sep2020. More info: https://community.fandom.com/wiki/Thread:1991490

**Comment by sampsyo** [comment]
The source was removed in #3766.
