### ISSUE TITLE
beet config with empty configuration could show a message

### ISSUE THREAD

**Issue by Sudo-kun** [beetbox/beets#3779]
I'm new to the project so maybe I just forgot to do something.

 I was just looking around and found that when calling config while nothing was configured showed an empty array.

Maybe there could be a text that says "No existing configuration".

**Comment by sampsyo** [comment]
Sure, sounds good. But I'd phrase it as "empty configuration" instead of "no configuration" because the symptom would be the same if there is just an empty file there.

**Comment by jackwilsdon** [comment]
Fixed by #3782.
