### ISSUE TITLE
mpdstats plugin needs updating to work with python-mpd2 2.0.0

### ISSUE THREAD

**Issue by smcv** [beetbox/beets#3798]
(Sorry, this is just from source code inspection and a search of dependent packages in Debian, rather than a crash that I've genuinely reproduced - I don't currently use beets myself, although I keep meaning to try it.)

https://github.com/Mic92/python-mpd2 version 2.0.0 dropped support for the `use_unicode` parameter to the `MPDClient` constructor. This parameter doesn't do anything in Python 3, which always behaves like `use_unicode=True`. It was important in Python 2.

In Debian's python3-mpd package I've added back compatibility with the use_unicode parameter for now (see Mic92/python-mpd2#142) but I don't know whether that will be accepted upstream.

If beets only supports Python 3, dropping the parameter should be a sufficient fix: replace `MPDClient(use_unicode=True)` with `MPDClient()`.

If it still supports Python 2, something similar to https://github.com/multani/sonata/pull/116 should work.

**Comment by sampsyo** [comment]
Thank you for the report, traceback or no! A simple check like in Sonata should do well.
