### ISSUE TITLE
Original year vs release year

### ISSUE THREAD

**Issue by DjSlash** [beetbox/beets#382]
With this issue I'd like to offer some ideas/discussionpoints about release dates of albums. Main idea is that one would like to have the original year of an album so an collection of albums is sortable according to the discography of an artist. The other side is being able to still determine which release it _really_ is.
- People who have `original_date: no`, may still want to store the original release date in the metadata of the file. This can be done by using the `TDOR` (2.4) / `TORY` (2.3) id3 tags for the orignal release date. Con is that this tag is most likely not very much supported in players.
- It would be nice to have `$orignal_year` for usage in Path Formats, even with `original_date: no`.

**Comment by radiosilence** [comment]
If we are setting `original_date` to `true`, could it instead of just losing the info, perhaps set it the `RELEASEDATE`/`RELEASEYEAR` tag (or simply do this anyway)?
