### ISSUE TITLE
I would like beets to ask for clarification in the case of multiple strong matches, but auto-select a single strong match

### ISSUE THREAD

**Issue by thessem** [beetbox/beets#3823]
### Use case

I'm trying to use beets to automatically match albums to musicbrainz releases when there is zero ambiguity about the match. My music collection is from when I was quite young, and I did not record the origin of my music, thus I don't know what actual release the tracks came from. I do not want this data in the database, I would prefer it missing rather than incorrect.

#### Case 1: Single strong match
```
# beet import -L album:"One Time for All Time"

/Volumes/Media/Music/Albums/65daysofstatic/One Time for All Time (9 items)
Tagging:
    65daysofstatic - One Time for All Time
URL:
    https://musicbrainz.org/release/a41e4735-76af-4ee3-aa0f-1d12eda2bf25
(Similarity: 100.0%) (CD, 2005, GB, Monotreme Records, MONO-16)
[A]pply, More candidates, Skip, Use as-is, as Tracks, Group albums,
Enter search, enter Id, aBort? m
Finding tags for album "65daysofstatic - One Time for All Time".
Candidates:
1. 65daysofstatic - One Time for All Time (100.0%) (CD, 2005, GB, Monotreme Records, MONO-16)
# selection (default 1), Skip, Use as-is, as Tracks, Group albums,
Enter search, enter Id, aBort?
```
`65daysofstatic - One Time for All Time` is an album I added to my collection years ago. I have lost track of the actual provenance of the album. Matching it in the automatcher finds a single strong match for the audio files I have. My configuration is set to ignore small track title issues, and to really only concern itself with the stuff I'm sure of (e.g., name of artist, name of album, number of tracks, their lengths, small variations in title). The [Release group](https://musicbrainz.org/release-group/bb2fb79a-5235-37a7-81e1-9af3b3d05b22) has 5 releases in it, but there's only 1 with 9 tracks, and I have 9 tracks. **I would like import mode to automatically select this option and move on** since this (`MONO-16`) is definitely the actual release my music came from.

#### Case 2: Multiple strong matches
```
# beet import -L album:"replicr, 2019"

/Volumes/Media/Music/Albums/65daysofstatic/replicr, 2019 (14 items)
Tagging:
    65daysofstatic - replicr, 2019
URL:
    https://musicbrainz.org/release/2a871e0f-3ca9-4b55-8c1d-de098c8cda36
(Similarity: 100.0%) (CD, 2019, GB, Superball Music, 19075972592)
[A]pply, More candidates, Skip, Use as-is, as Tracks, Group albums,
Enter search, enter Id, aBort? m
Finding tags for album "65daysofstatic - replicr, 2019".
Candidates:
1. 65daysofstatic - replicr, 2019 (100.0%) (CD, 2019, GB, Superball Music, 19075972592)
2. 65daysofstatic - replicr, 2019 (100.0%) (Digital Media, 2019, XW, Superball Music, 886447778425)
# selection (default 1), Skip, Use as-is, as Tracks, Group albums,
Enter search, enter Id, aBort?
```
In the automatching system the above presents exactly like case 1, but upon asking for `More` it shows me that there are two strong matches for this album.  My music could have reasonably come from either `GB, Superball Music, 19075972592` or `XW, Superball Music, 886447778425`. The information I have currently isn't enough to definitely say which one.
1. I would have liked the **original prompt to show me that there are two potential strong matches** without `m`
2. I would like to **not automatically accept the first match** (the only reason it didn't is I have `strong_rec_thresh: 0` right now), but given the same settings to accept the match in **Case 1**
3. I understand this is well outside the bounds of a feature request and probably breaks the architecture of beets somewhat (sorry for even bringing it up), but it'd be insanely cool if beets could tag my tracks with the similar aspects of the two strong matches in this case (track names, release group, album artist, etc etc etc) without tagging them with information that comes from a specific release (e.g., release_group_id, country, label, medium)

### Potential Solution
An addition of a setting that will cause the autotagger to ask for input about a strong match in the case where there are two strong matches. I believe through other options in beets, I should be able to achieve what I'm after with just this.

### Alternative Solution
I would like some way of causing beets to stop writing
> catalognum country comments label media mb_albumid mb_releasetrackid mb_trackid asin albumdisambig

into it's database without an single 100% match, as those values come from specific releases, whereas I can only personally vouch for a release group a lot of the time.

### See Also
I think this feature is what https://github.com/beetbox/beets/issues/898 was asking for, "Preferred Media" is not a good solution here, since "CD" and "Digital Release" are often exactly the same match strength and I don't actually know where my music came from.

A person was also asking for additional configuration about what to do in the case of multiple indistinguishably good matches here: https://github.com/beetbox/beets/issues/3603

**Comment by sampsyo** [comment]
Hello! There's no perfect built-in way to do this, but you might try fiddling with the `match.rec_gap_thresh` config option: https://beets.readthedocs.io/en/stable/reference/config.html#autotagger-matching-options

Maybe by turning `strong_rec_thresh` all the way down to zero and adjusting the gap threshold, you can get something similar to what you want.

**Comment by thessem** [comment]
That's close to what I want, but I'm after the automation aspect of this! I'll provide a better example, given the needinfo tag 😛. I get that my use-case is probably a little orthogonal to the actual purpose of beets (tagging old poorly managed libraries VS. managing a library constructed initially where providence is tracked, or by people who are happy with "best guess" label, country information).

### Case 1: Single strong match
```
# beet import -L album:"One Time for All Time"

/Volumes/Media/Music/Albums/65daysofstatic/One Time for All Time (9 items)
Tagging:
    65daysofstatic - One Time for All Time
URL:
    https://musicbrainz.org/release/a41e4735-76af-4ee3-aa0f-1d12eda2bf25
(Similarity: 100.0%) (CD, 2005, GB, Monotreme Records, MONO-16)
[A]pply, More candidates, Skip, Use as-is, as Tracks, Group albums,
Enter search, enter Id, aBort? m
Finding tags for album "65daysofstatic - One Time for All Time".
Candidates:
1. 65daysofstatic - One Time for All Time (100.0%) (CD, 2005, GB, Monotreme Records, MONO-16)
# selection (default 1), Skip, Use as-is, as Tracks, Group albums,
Enter search, enter Id, aBort?
```
`65daysofstatic - One Time for All Time` is an album I added to my collection years ago. I have lost track of the actual provenance of the album. Matching it in the automatcher finds a single strong match for the audio files I have. My configuration is set to ignore small track title issues, and to really only concern itself with the stuff I'm sure of (e.g., name of artist, name of album, number of tracks, their lengths, small variations in title). The [Release group](https://musicbrainz.org/release-group/bb2fb79a-5235-37a7-81e1-9af3b3d05b22) has 5 releases in it, but there's only 1 with 9 tracks, and I have 9 tracks. **I would like import mode to automatically select this option and move on** since this (`MONO-16`) is definitely the actual release my music came from.

### Case 2: Multiple strong matches
```
# beet import -L album:"replicr, 2019"

/Volumes/Media/Music/Albums/65daysofstatic/replicr, 2019 (14 items)
Tagging:
    65daysofstatic - replicr, 2019
URL:
    https://musicbrainz.org/release/2a871e0f-3ca9-4b55-8c1d-de098c8cda36
(Similarity: 100.0%) (CD, 2019, GB, Superball Music, 19075972592)
[A]pply, More candidates, Skip, Use as-is, as Tracks, Group albums,
Enter search, enter Id, aBort? m
Finding tags for album "65daysofstatic - replicr, 2019".
Candidates:
1. 65daysofstatic - replicr, 2019 (100.0%) (CD, 2019, GB, Superball Music, 19075972592)
2. 65daysofstatic - replicr, 2019 (100.0%) (Digital Media, 2019, XW, Superball Music, 886447778425)
# selection (default 1), Skip, Use as-is, as Tracks, Group albums,
Enter search, enter Id, aBort?
```
In the automatching system the above presents exactly like case 1, but upon asking for `More` it shows me that there are two strong matches for this album.  My music could have reasonably come from either `GB, Superball Music, 19075972592` or `XW, Superball Music, 886447778425`. The information I have currently isn't enough to definitely say which one.
1. I would have liked the **original prompt to show me that there are two potential strong matches** without `m`
2. I would like to **not automatically accept the first match** (the only reason it didn't is I have `strong_rec_thresh: 0` right now), but given the same settings to accept the match in **Case 1**
3. I understand this is well outside the bounds of a feature request and probably breaks the architecture of beets somewhat (sorry for even bringing it up), but it'd be insanely cool if beets could tag my tracks with the similar aspects of the two strong matches in this case (track names, release group, album artist, etc etc etc) without tagging them with information that comes from a specific release (e.g., release_group_id, country, label, medium)

**Comment by thessem** [comment]
Also I just want to say that beets is a lovely tool. Thank you. It can't be easy to work in this area, there are a lot of strongly held and orthogonal opinions and it's amazing how beets seems to be adaptable enough to cover most of them.

**Comment by sampsyo** [comment]
Got it; thanks for the additional explanation. FWIW, in beets terms, what you want from the importer is "no recommendation" when there are two or more closely-ranked matches (e.g., two distance-0 matches), but maintain a "strong recommendation" when there is only one good match.

I'd like to keep drilling down to understand exactly what needs to change, however. Does the aforementioned proposed fiddling (that is, turning `strong_rec_thresh` to 0) work part of the way, in the sense that it gets Case 2 right but not Case 1? If not, maybe fiddling with `medium_rec_thresh` too might help?

How does it work in a  case where there are *two* matches, one of which is much better than the other? (This is like Case 1 but subtly different because I'm guessing beets does not activate its "gap" logic when there is just one match.)

Maybe the thing to do is to have a different threshold for when there is only one match, which works sort of like the "gap" logic?

As you can tell, I'm trying to boil down the proposed behavior to an actual change we can make to the matching logic, and it requires some creativity to think through what the algorithm might look like. Getting specific about how the logic should work will help understand how hard it will be to implement.

**Comment by thessem** [comment]
This is still relevant, I am going to eventually get back and answer the questions posed here. I just don't go through a music tagging spree very often so I haven't had an opportunity to test.
