### ISSUE TITLE
is fetchart source fanarttv currently working for anyone?

### ISSUE THREAD

**Issue by xekon** [beetbox/beets#3826]
I am 100% new to beets as well as musicbrainz, however I have been using linux for years.

I am on Ubuntu 20.04 and could not get beets to work with pip3 install beets (https://github.com/beetbox/beets/issues/3674)
I did however get up and running by using pip3 to install beets dependencies and then installing beets itself by cloning from gihub

### Problem

fanarttv does not seem to work for fetchart

The fetchart plugin is working otherwise because if I add additional sources then the cover is found, just trying to diagnose fanarttv.

In The below command you will notice the verbose output for fetchart searching filesystem, but you never see one for fanarttv.

```sh
$ sudo beet -vv import -A -C -W -t "/media/md0/DL/_music/Rock-Hard/Soundgarden/1994 - Superunknown/"
```

shows this output:

```
user configuration: /root/.config/beets/config.yaml
data directory: /root/.config/beets
plugin paths:
Sending event: pluginload
library database: /root/.config/beets/library.db
library directory: /root/Music
Sending event: library_opened
Sending event: import_begin
Sending event: import_task_created
/media/md0/DL/_music/Rock-Hard/Soundgarden/1994 - Superunknown
0 of 16 items replaced
Sending event: database_change
...
Sending event: database_change
fetchart: trying source filesystem for album Soundgarden - Superunknown
Sending event: database_change
...
Sending event: database_change
Sending event: import_task_files
Sending event: album_imported
Sending event: import
Sending event: cli_exit
```

Because the above command never says trying source for fanarttv I decided to try manually:

```sh
$ sudo beet -vv fetchart -f "/media/md0/DL/_music/Rock-Hard/Soundgarden/1994 - Superunknown/"
```

shows this output:

```
user configuration: /root/.config/beets/config.yaml
data directory: /root/.config/beets
plugin paths:
Sending event: pluginload
library database: /root/.config/beets/library.db
library directory: /root/Music
Sending event: library_opened
fetchart: trying source filesystem for album Soundgarden - Superunknown
fetchart: trying source fanarttv for album Soundgarden - Superunknown
fetchart: Soundgarden - Superunknown: no art found
Sending event: cli_exit
```

you can now see that it does say trying source for fanarttv however it reports no art found.

However I manually searched fanart.tv using firefox and the album art is absolutely there.

I am wondering if fanart.tv is working with beets for anybody else? or if I have somehow set something up incorrectly.

### Setup

* OS: Ubuntu 20.04
* Python version: 3.8.5
* beets version: 1.5.0 (beets-1.5.0-py3.8.egg)
* Turning off plugins made problem go away (yes/no): no (the issue/question is about the plugin fetchart?)

My configuration (output of `beet config`) is:

```yaml
plugins: fetchart
fetchart:
    fanarttv_key: REDACTED
    minwidth: 1000
    cover_names:
    - cover
    - front
    - art
    - album
    - folder
    sources:
    - filesystem
    - fanarttv
```

**Comment by xekon** [comment]
Also it seems on import it never tries anything other than filesystem for fetchart, its not until I do -f that it actually tries online sources. This is even on directories with nothing but .mp3 files, no images or anything else in the directory.

**Comment by sampsyo** [comment]
Interesting! It's hard to say without digging a bit more into the code, since it seems like there is not enough logging to say _why_ the art wasn't found. Maybe throwing some `print` statements into the appropriate backend would help reveal what's going wrong.

**Comment by xekon** [comment]
I am really interested in getting fanart.tv working, so I will work on this within the next day or so :)

**Comment by xekon** [comment]
I found the FanartTV class in fetchart.py and I can see there are already some debug messages such as error receiving response and error loading response.... 

got an suggestions for some debug lines I could add? if you have time a copy paste of the couple lines surrounding a suggested added debug line would be awesome. I am not very proficient at python and not at all familiar with fanart.tv api

**Comment by xekon** [comment]
I found the problem, after looking at the fanart.tv api it appears you can only search with mbid: https://fanarttv.docs.apiary.io/#reference/music/get-album/get-album

I was using beets to scan for album art without tagging, I already spent a lot of time on my tags and did not want to change them.

Is there a way to get beets to add just the album mbid tag but not change any of the other tags when importing.

**Comment by wisp3rwind** [comment]
The `write` config option might be what you're looking for https://beets.readthedocs.io/en/stable/reference/config.html#write.
