### ISSUE TITLE
Library relative paths

### ISSUE THREAD

**Issue by benneti** [beetbox/beets#3833]
### Use case

I just moved my music library (the file path) and then had to see how my library was completely deleted on beets up (luckily I created a backup before).
Apparently beet right now hardcodes the file paths in the `library` to simplify moving the `directory` it would be nice to use paths relative to the `directory` such that changing the directory would make it unnecessary to reimport the whole library.

### Solution
As `directory` is already a setting it would be nice to have an option to use relative paths in the `library` and compute the absolute path using the `directory` setting.

### Alternatives
sed can help here for now:
As the path in the library are visible for sed manually running `sed "s/old_dir/new_dir/" library_old > library`) when the directory is moved works, too.

**Comment by sampsyo** [comment]
Hello! Please see #133.
