### ISSUE TITLE
How to search Album?

### ISSUE THREAD

**Issue by entuccio** [beetbox/beets#3835]
Is there a way to search the album for a specified song without import? 
Example: 

I would like to know what album is for the song "Blowin' in the Wind" and the answer should be 
--> Bob Dylan, Album: The Freewheelin' Bob Dylan

Note: I don't have this song in the library, I would like only to know it via command line.

Thank you

**Comment by wisp3rwind** [comment]
I don't think so, and personally, I would also claim that this is out of scope for beets: After all, beets is mostly about managing your existing music.

I guess you're aware of the musicbrainz web-interface? In Musicbrainz-lingo, you'd want to search for a [recording with that name](https://musicbrainz.org/search?query=Blowin%27+in+the+Wind&type=recording&method=indexed). I'm not aware of any command-line tool to do the same thing (which doesn't mean that it doesn't exist).
