### ISSUE TITLE
Unknown characters when importing music

### ISSUE THREAD

**Issue by Droppisalt** [beetbox/beets#3843]
I'm having [unknown characters](https://imgur.com/a/FAjC0Yj) when trying to import new music . I read issue https://github.com/beetbox/beets/issues/2607 that I thought had the same error but turning off color doesn't fix it.

I'm a complete beginner with beets and I was trying to import a partial copy of my library to test it out. I've included the contents of my config.yaml (mostly taken from someone else's file). I don't know much about any programming language but I love tech so I tried to figure it out on my own but didn't get it. If anyone could help, I would really appreciate it.

`
# This sets where I want my music stored (directory), and where the database file is located (library).
directory: M:\Music\LibraryTEST
library: M:\Music\Data\Musiclibrary.db

import:
    # write metadata to music files
    write: yes

    # move imported files from source to the music directory
    move: yes
    copy: no
    delete: no

    # use auto-tagging where possible
    # do not require confirmation on strong matches
    autotag: yes
    timid: no

    resume: ask
    incremental: no
    none_rec_action: ask
    log:

    quiet: no  # enable with command line option
    quiet_fallback: skip
    default_action: apply

    singletons: no
    languages: []
    detail: no
    flat: no    
    
plugins:
    - fetchart
    - embedart
    - ftintitle
    - lastgenre
    - lastimport
    - duplicates
    - importfeeds
    - plexupdate
    - rewrite
    - the
    

fetchart:
    sources:
        - filesystem
        - coverart: release
        - itunes
        - coverart: releasegroup
        - '*'

embedart:
    ifempty: yes
    
ftintitle:
    format: (feat. {0})
    
lastgenre:
    canonical: yes
    count: 4
    fallback: ''
    separator: '; '
    
lastfm:
    user: ******
       

importfeeds:
    formats: m3u
    dir: ~\imports\
    relative_to: M:\Music\Data\
    m3u_name: newfiles.m3u
    
plex:
    host: localhost
    port: 32400

rewrite:
    artist .*jimi hendrix.*: Jimi Hendrix
    artist .*devin townsend.*: Devin Townsend

# use the release-date of the original (first) release of an album?
original_date: yes

# on multi-disk releases, assign track numbers for the whole album.
# If "per disk", make sure tracknames do not collide ("paths" setting).
per_disc_numbering: yes

# files matching these patterns are deleted from source after import
clutter: ["Thumbs.DB", ".DS_Store", "*.m3u", ".pls"]

# files/directories matching one of these patterns are ignored during import
ignore: [".*", "*~", "System Volume Information"]

# Paths ----------------------------------------------------------------------

# Paths and filenames for music files
# relative to music directory
paths:
    default: %the{%left{$albumartist_sort,1}}/$albumartist_sort/[$year] $album/$disc-$track $title
    singleton: Non-Album/$artist - $title
    comp: $album ($year)/$track - $artist - $title

# replace special characters in generated filenames
replace:
    '[\\/]': _
    '^\.': _
    '[\x00-\x1f]': _
    '[<>:"\?\*\|]': _
    '\.$': _
    '\s+$': ''

asciify_paths: yes

path_sep_replace: _

# filename for the album art
art_filename: cover  # results in "cover.jpg"

max_filename_length: 0  # unlimited

# General --------------------------------------------------------------------

# use mutliple threads during import
threaded: yes
timeout: 5.0
verbose: no

# User Interface -------------------------------------------------------------

color: no

ui:
    terminal_width: 80
    length_diff_thresh: 10.0

# Auto Tagger ----------------------------------------------------------------

match:
    strong_rec_thresh: 0.1      # match 90% or better for auto import
    medium_rec_thresh: 0.25
    rec_gap_thresh: 0.25
    max_rec:
        missing_tracks: medium
        unmatched_tracks: medium
    distance_weights:
        source: 2.0
        artist: 3.0
        album: 3.0
        media: 1.0
        mediums: 1.0
        year: 1.0
        country: 0.5
        label: 0.5
        catalognum: 0.5
        albumdisambig: 0.5
        album_id: 5.0
        tracks: 2.0
        missing_tracks: 0.9
        unmatched_tracks: 0.6
        track_title: 3.0
        track_artist: 2.0
        track_index: 1.0
        track_length: 2.0
        track_id: 5.0
    preferred:
        countries: []
        media: []
        original_year: no
    ignored: []
    track_length_grace: 10
    track_length_max: 30`

**Comment by sampsyo** [comment]
You will need to indent the `color` option under the `ui:` section.

**Comment by Droppisalt** [comment]
> 
> 
> You will need to indent the `color` option under the `ui:` section.

Oh wow, that was a simple fix. Thanks!
