### ISSUE TITLE
Show albums with not 100% similarity by missing plugin

### ISSUE THREAD

**Issue by catap** [beetbox/beets#3846]
### Use case

Sometimes when mass import is happened a user can selected a wrong release for specified release group at musicbrainz because he is very lazy to add a new one :)

Usually it means that track length is a bit wrong. 

In some future someone can introduce a new (the right one) album to musicbrainz.

### Solution

Introduce a way to show albums that isn't 100% matched with musicbrainz ID.

Future this feature might be extended at mbsync to switch better candidate if it existed, or make something like partitaly re-import.

**Comment by sampsyo** [comment]
Interesting situation! Any chance you could elaborate on how exactly you imagine this working? What would the plugin need to request from the MusicBrainz API to find the information you're looking for, and how exactly does that differ from the way the plugin currently works?

**Comment by catap** [comment]
I have in mind a bit more complex solution. Let me explain it here.

1) Add a new option for `missing` plugin to show all albums that hasn't got 100% similarity with musicbrainz, likes it does for `-a` when show missed albums.

2) Add a way to repeat step from `import` when a user selected a music brain release for this album. I feel that `mbsync` is good place to do it.

Also, it may requires some additional work near `mbupdate` because ID of tracks/album after step (2) may be changed.

**Comment by sampsyo** [comment]
I suppose this is the bit I'm interested in more detail on:

> 1. Add a new option for `missing` plugin to show all albums that hasn't got 100% similarity with musicbrainz, likes it does for `-a` when show missed albums.

Can you elaborate a bit on what you mean by "albums that hasn't got 100% similarity with musicbrainz"? I'm actually not entirely sure what that looks like, or how the plugins would work to find them.

**Comment by catap** [comment]
@sampsyo I doubt that I can explain how :) because I don't know how execley beet works.

Anyway, I can try to make a high level algorithm:
1. User runs `missing --similarity-check`
2. `beet` re-run Auto-Tagger for the each album and
3. It expects that at least one candidate has 100% match, otherwise it should be reported by this feature.

Somewhere here I feel that a new feature for `mbsync` should be introduced to run (2) step and ask similar questions that is asked during the import.

**Comment by catap** [comment]
BTW if you feel that it is overengineering I will agree with you :)

**Comment by wisp3rwind** [comment]
You can [re-import](https://beets.readthedocs.io/en/stable/reference/cli.html#reimporting) which I think solves part of your issue. Detecting such albums in the first place might be quite difficult, since once the initial import is complete, previous metadata isn't retained and you might just get a 100% match for whatever release was chosen. One clear exception to this rule is of course the length field, which is not stored in the database, but calculated from the media file (I think).

**Comment by catap** [comment]
@wisp3rwind metadata? Yes. But I'm talking more about different release of some album when a tracks has a bit different length.
