### ISSUE TITLE
How to update after %asciify{text} modify.

### ISSUE THREAD

**Issue by entuccio** [beetbox/beets#3855]
Hello :-)

Probably this is a stupid question, but I didn't find the answer in the documentation.

I changed my "path" in the configuration of Beets.

....
paths:
    default: $albumartist/%asciify{$album}%aunique{}/$track %asciify{$title}
    singleton: Non-Album/$artist/$title
    comp: Compilations/%asciify{$album}%aunique{}/$track %asciify{$title}
....

Simply I added che "%asciify{text}" function.

My question is: how to apply this to my library?
I tried beet update, but it seems to have no effect on the file system. On the opposite, if I re-import something, It works perfectly.

Is there a way to adjust all my library without reimporting all the music?

Thanks

**Comment by jackwilsdon** [comment]
[`beet move`](https://beets.readthedocs.io/en/stable/reference/cli.html#move) should do what you're looking for - try `beet move -p` to perform a dry-run first and see what changes beets will make.

**Comment by sampsyo** [comment]
Indeed; this is in the FAQ, FWIW: https://beets.readthedocs.io/en/stable/faq.html#rename-my-files-according-to-a-new-path-format-configuration

**Comment by entuccio** [comment]
Thank you very much. I missed that part. Thanks. Solved perfectly :-)
