### ISSUE TITLE
web: GET /album/<n> hides artpath even when INCLUDE_PATHS is set

### ISSUE THREAD

**Issue by GrahamCobb** [beetbox/beets#3866]
### Problem

`beet web` provides GET operations to fetch track items and albums. By default this removes paths
from the returned data, but the config setting INCLUDE_PATHS should allow the paths to be returned.

This works correctly for GET /item/... but not GET /album/... In the album case, the artpath is unconditionally deleted from the results.

### Setup

Add to config file:

web:
    include_paths: true

Use `beet web` to make a webserver available and do a GET /album/N, where N is the album id of an album in the database which has a cover art set. The JSON result should include the 'artpath' value but does not.

* OS: Linux (Debian Testing)
* Python version: 3.9.1-1
* beets version: 1.4.9-7
* Turning off plugins made problem go away (yes/no): bug in web plugin

Note this is a small issue, although I have hit it. I have a fix (and a regression test) which I will submit as a small PR once my first PR has been finished (so I can learn from the mistakes I made in that!).

**Comment by sampsyo** [comment]
Sounds great!

**Comment by GrahamCobb** [comment]
I see it as a bug, rather than a feature (as it works correctly for the item path) but I guess it doesn't really matter! 

Anyway, I will submit the PR once the first one is completed. I forgot to create a separate branch for that one so I think it will be easier to manage once that is closed.
