### ISSUE TITLE
Cue plugin not working

### ISSUE THREAD

**Issue by wargreen** [beetbox/beets#3892]
### Problem

Running this command in verbose (`-vv`) mode:

```sh
$ beet -vv import .
```

Led to this problem:

```
--Return--
> /usr/share/beets/beetsplug/cue.py(29)candidates()->None
-> pdb.set_trace()
(Pdb) 

```

### Setup

* OS: Debian SID
* Python version: 3.9.1
* beets version: 1.4.9
* Turning off plugins made problem go away (yes/no): yes

My configuration (output of `beet config`) is:

```yaml
plugins: cue
```
In the plugin's code, the candidates method call PDB, and in item_candidates we have :
```
            title = "dunno lol"
            track_id = "wtf"
```
We find it in the Debian's release.

**Comment by wisp3rwind** [comment]
Well that's an interesting one: I don't think that plugin is meant to exist, but was accidentally committed in https://github.com/beetbox/beets/commit/8f5bae26fd557dd886f192e90fe0ba3c2c4b739b. @brunal is that indeed what happened here?

**Comment by sampsyo** [comment]
Wow; strange! Yes indeed, looks like this got added by accident. It would be interesting to hear more from @brunal, but yeah, for now let's just remove it!
