### ISSUE TITLE
Lyrics plugin crashing on tekstowo.pl

### ISSUE THREAD

**Issue by njelich** [beetbox/beets#3904]
I just found it crashing while searching tekstowo.pl (I'm on https://github.com/beetbox/beets/commit/afc072801c4a254e6b4114d89133d6bebc3e34b9).

These are the relevant lines of error.

```
    return html.find("div", class_="song-text").get_text()
AttributeError: 'NoneType' object has no attribute 'get_text'
```

I also printed the html to the console, but I am unsure why the error is appearing. The div with the class song-text seems to exist and I've never worked on beets before. Could it have something to do with there being two divs with the class?

I uploaded the html, but had to do it with txt extension due to GitHub limitations.

[temp.txt](https://github.com/beetbox/beets/files/6292601/temp.txt)

_Originally posted by @njelich in https://github.com/beetbox/beets/issues/3903#issuecomment-817359091_

**Comment by sampsyo** [comment]
Paging @xhocquet, as per the other issue.

**Comment by xhocquet** [comment]
Looking!

**Comment by njelich** [comment]
The error is still happening with the new version.

**Comment by xhocquet** [comment]
@njelich Would you mind giving me a specific track this is failing for?

**Comment by xhocquet** [comment]
@njelich After parsing out your txt file to find the track/artist, Capitalist Casualties - Gig Violence, I was not able to reproduce your issue with the latest code (ignore the 'eye' piece of the file tags, I use that for convenience when I was testing other files but it is not used in the lyrics search):

```
[~/Coding/src/beets](tekstowo-fixes)$ beet -vv lyrics eye -p -f
user configuration: /Users/meesles/Library/Application Support/beets/config.yaml
data directory: /Users/meesles/Library/Application Support/beets
plugin paths:
Sending event: pluginload
library database: /Users/meesles/Library/Application Support/beets/library.db
library directory: /Users/meesles/Music
Sending event: library_opened
lyrics: got lyrics from backend: Tekstowo
lyrics: fetched lyrics: Capitalist Casualties - u n eye - Gig Violence
Sending event: write
Sending event: after_write
Sending event: database_change
Tekst piosenki:

Don't make us stop playing
We'll take you outside ourselves
& beat in your fucking face
Wrecking our gigs, keep your distance
Shut your trap & swallow your shit

Historia edycji tekstu
Sending event: cli_exit

[~/Coding/src/beets](tekstowo-fixes)$ beet ls eye -f '$lyrics'
Tekst piosenki:

Don't make us stop playing
We'll take you outside ourselves
& beat in your fucking face
Wrecking our gigs, keep your distance
Shut your trap & swallow your shit

Historia edycji tekstu
```

Lyrics search executes as expected without error and saves the lyrics to the file. If this is still an issue, can you please provide more information like the commands used, the stack of the issue, etc.? cc @sampsyo
