### ISSUE TITLE
Non matching albumdisambigs should be penalized higher

### ISSUE THREAD

**Issue by RollingStar** [beetbox/beets#3916]
### Problem

I imported a film OST and it collided with the broadway OST, a totally different recording. 

```sh
Stephen Schwartz - 1992 - Godspell (13 items)
Tagging:
    Stephen Schwartz - Godspell
URL:
    https://musicbrainz.org/release/aa4c4bbe-7b6e-4e40-8415-20c8c5538c30
(Similarity: 99.4%) (albumdisambig) (CD, 1992, US, Arista, ARCD-8337, 1973 film cast)
This album is already in the library!
Old: 15 items, FLAC, 801kbps, 44.1kHz/16 bit, 45:43, 263.6 MiB
New: 13 items, FLAC, 829kbps, 44.1kHz/16 bit, 45:30, 267.5 MiB
[S]kip new, Keep both, Remove old, Merge all? r
```

I see in the config that `albumdisambig` only provides a 0.5 penalty.

https://github.com/beetbox/beets/blob/master/beets/config_default.yaml#L128

At least, I think the collision happened. I have a folder for the 1971 album that was empty after `r`emoving it.

https://musicbrainz.org/release-group/15a2ef94-f8c5-31e9-b9d1-9ff32fa8833f

https://musicbrainz.org/release-group/13e39859-625b-3f9d-964f-d53124923011

**Comment by sampsyo** [comment]
That seems like a good idea! Would you mind experimenting with different values for this penalty to make a proposal for what it should be adjusted to? It would be great, for example, if it avoided this "collision" without rendering other potential scenarios completely out of whack.

**Comment by RollingStar** [comment]
Release group vs. release will be a big factor, if possible. Different release groups will have different disambigs. Releases will too, but they don't matter much.

https://musicbrainz.org/release-group/055be730-dcad-31bf-b550-45ba9c202aa3

Here we have "The White Album" as a rg-disambig but "stereo" as a r-disambig.

How does the matching work? does beets pick single releases out of release groups for the matching? (I think it does). Rather than an albumdisambig problem, it might be a subset of a release group penalty problem. Different release groups are not dupes in almost all cases.

**Comment by sampsyo** [comment]
Beets queries MusicBrainz for _just_ releases, and it doesn't currently apply an RG-related penalties. This is the function you'd find that in, FWIW:
https://github.com/beetbox/beets/blob/e1a901dce5c7b867a5c84a438044c4093bcbed05/beets/autotag/match.py#L162

Of course, most of this is only relevant if there are MBIDs or existing disambiguation strings (which it sounds like your files have, which is cool).
