### ISSUE TITLE
Multiple "ModuleNotFoundError"'s after updating to latest beets HEAD

### ISSUE THREAD

**Issue by scztt** [beetbox/beets#4028]
### Problem

Multiple "ModuleNotFoundError"'s after updating to latest beets HEAD

I updated to the latest beets HEAD:
```
git checkout master
git pull
```

I installed my local copy:
```
pip3 install .
```

Upon running any `beet` command, I see:
```
** error loading plugin discogs:
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/beets/plugins.py", line 269, in load_plugins
    namespace = __import__(modname, None, None)
ModuleNotFoundError: No module named 'beetsplug.discogs'
```
...and equivalent errors for all of my plugins.

I've also tried:
- `setup.py` installation
- `pip3 install -e` installation
- manually removing my `site-packages` beets files and re-installing
- Importing plugins directly in python REPL (`import beetsplug` works, but importing specific plugins does not)

### Setup

* OS: MacOS 11.4
* Python version: 3.9
* beets version: HEAD (75223eedb76ecc1e610e1781065c36105ee900b4)

**Comment by dbogdanov** [comment]
Happens to me with `pip3 install -e .`

**Comment by wisp3rwind** [comment]
Closing this: Probably not an issue with beets itself, but rather with the specific installation.
