### ISSUE TITLE
Folder Structure Bug with -A

### ISSUE THREAD

**Issue by 641i130** [beetbox/beets#4051]
After using `beet import -A /Big/Music` my folder structure has a weird system:
![image](https://user-images.githubusercontent.com/46945263/132951747-90a1a1bc-2062-49a8-bd4e-7efa50c51e28.png)

### Problem

```sh
$ beet import -A /Big/Music
```

My folders getting mixed up with what seemed to be a tag from a file named `【original】#あくあ色ぱれっと【ホロライブ/湊あくあ】.mp3`

Here's a link to the music files that trigger the bug (if relevant): https://mega.nz/file/cGQX2STT#0IAHmasO9NQOoUCgcaNgXwkbsQuKsV85DOd3ELCx4kY

### Setup

* OS: Arch Linux x86_64
* Python version: Python 3.9.6
* beets version: beets version 1.5.0
* Turning off plugins made problem go away (yes/no): no
(I had no plugins)

My configuration (output of `beet config`) is:

```yaml
directory: /Big/Beets            # The default library root directory.
import:
      move: yes
```

Its my first time using Beets, maybe I messed up. Any tips on fixing this? I could probably move everything up a dir using bash but I'm still a noob...

**Comment by sampsyo** [comment]
Do you think you could explain in more detail what is "weird" about this output? Without more detail, it's hard to see what's going wrong.

**Comment by 641i130** [comment]
Nearly all the folders have a subfolder titled `#あくあ色ぱれっと` . This isn't right because none of the files are even related to it. Its like it escaped a string somehow and got itself into each album.

**Comment by sampsyo** [comment]
Maybe it would be useful to see the output of `beet info` run on these files? (You'll need to enable the `info` plugin first.) It's possible that the `$album` field contains that string for all these files…
