### ISSUE TITLE
Add the musicbrainz_releasetrackid tag

### ISSUE THREAD

**Issue by mineo** [beetbox/beets#406]
We decided to call it musicbrainz_releasetrackid at the summit (https://wiki.musicbrainz.org/MusicBrainz_Summit/13#Elephant_IDs). The commit adding it to Picard is https://github.com/musicbrainz/picard/commit/04c30355e2743b7f0bd2cbfce89472483a0d5b85 so you can just reuse the tag names for all the different formats.

**Comment by Rawrmonkeys** [comment]
What is the status on this? I see that https://github.com/beetbox/beets/issues/2690 has some discussion.

Is there anything getting in the way of adding support for the musicbrainz_releasetrackid tag and tossing the possible DB change of mb_trackid ->  mb_recordingid into it's own issue?

**Comment by sampsyo** [comment]
Yep, just adding the recording ID would be totally fine. Any help would be appreciated.

**Comment by Rawrmonkeys** [comment]
You mean the release track id?

**Comment by sampsyo** [comment]
Oops, yes!

**Comment by arcresu** [comment]
It looks to me like this has been implemented and can be closed now, so I'll do so. If I've missed something and that's not the case, please repoen this or leave a comment :)
