### ISSUE TITLE
Google Play Music is dead, let's remove the gmusic plugin

### ISSUE THREAD

**Issue by wisp3rwind** [beetbox/beets#4089]
It might be possible (desirable?) to replace it with Youtube music, but so far, I don't think anyone has requested that feature. There seems to be a new client library: https://github.com/sigma67/ytmusicapi. In any case, I'm not interested in porting the plugin myself.

Are there any objections? If not, I'll remove the plugin soon.

## TODO
- remove the plugin + docs + tests
- Close related issues:
    - https://github.com/beetbox/beets/issues/2997
    - https://github.com/beetbox/beets/issues/1569

**Comment by sampsyo** [comment]
Certainly no objections. RIP. 💀
