### ISSUE TITLE
[Lyrics Plugin] Genius failed to find artist

### ISSUE THREAD

**Issue by kjboa** [beetbox/beets#4137]
Hi, uppon requesting lyrics with beet -vv lyrics the genius source always fails and regardless of artist and song always gives this message.
In the Case of Halsey:
`lyrics: Genius failed to find a matching artist for 'Halsey'`
Maybe this is a problem with how the plugin handles Charactersets or smth, since on the regular Genius Site Lyrics for this song exist.

**Comment by sampsyo** [comment]
That's odd! To try debugging this, you might try seeing what a search like `https://api.genius.com/search?q=Halsey` produces directly from the Genius API. You'll need to provide an API key (you could try using beets's own, which is in its source code) and figure out the appropriate curl or httpie incantation to authenticate the request.

**Comment by kjboa** [comment]
Sorry for the late answer. I could find the API key in lyrics.py but sadly I wasn't able to figure out how to make the proper request. I however would really like to have genius lyrics in the file tags, and solve this problem. Is there any other way I could debug this?

**Comment by wisp3rwind** [comment]
> Sorry for the late answer. I could find the API key in lyrics.py but sadly I wasn't able to figure out how to make the proper request. I however would really like to have genius lyrics in the file tags, and solve this problem. Is there any other way I could debug this?

There are a few related comments at the bottom of https://github.com/beetbox/beets/issues/3903 (fwiw, the query still doesn't seem to work for me...)

**Comment by kjboa** [comment]
I had tried some other curl commands  but none worked for me using the given API key. One time though beet lyrics worked for a very short time, but pulled the same lyrics for all songs in the album...

**Comment by kjboa** [comment]
After few more tries with various installs this problem still persists. Is there maybe an option to use an own genius api key? Does redacted in this context mean that the genius api key option can't be used any longer or that it will be retired soon? 1.5.1 also seems to include some changes with genius is there a way to upgrade to the unfinished version using pip?

**Comment by sampsyo** [comment]
No, "redacted" is just our way of preventing people from accidentally leaking secrets when they post their config online.

To run the latest version from source, there are instructions in the FAQ.

**Comment by kjboa** [comment]
Thanks! Now I have 1.5.1, and want to put in a own api key. Does it make any difference at all what I pick for redirection url in the genius api panel?

**Comment by kjboa** [comment]
Still haven't figured it out
