### ISSUE TITLE
"No matching recordings found" when supplied with MBID

### ISSUE THREAD

**Issue by butter-radish** [beetbox/beets#4149]
I'm using `beet v1.5.0` to try to tag a single release by manually supplying a Musicbrainz ID. For some reason the app fails to validate it; I've checked, the ID works on musicbrainz.org. Am I supplying the wrong ID? I don't believe that's for a release group (like the documentation warns against).

The verbose output for the operation was:
```
Sending event: before_choose_candidate
Tagging track: Ava Max - My Head & My Heart
URL:
    https://musicbrainz.org/recording/a726563a-c958-49fb-bfbd-350e787977c5
(Similarity: 100.0%)
[A]pply, More candidates, Skip, Use as-is, Enter search, enter Id, aBort? i
Enter recording ID: b1514b18-f337-4907-a531-a7a039bdbbe1
Searching for track ID: b1514b18-f337-4907-a531-a7a039bdbbe1
Track ID match failed.
Sending event: before_choose_candidate
No matching recordings found.
[S]kip, Use as-is, Enter search, enter Id, aBort? b
Sending event: import
Sending event: cli_exit
```

### Setup

* OS: Artix Linux (rolling; up-to-date)
* Python version: 3.9.7-2
* beets version: 1.5.0
* Turning off plugins made problem go away: no

**Comment by sampsyo** [comment]
That does not seem to be a recording ID (this URL is a 404): https://musicbrainz.org/recording/b1514b18-f337-4907-a531-a7a039bdbbe1

**Comment by butter-radish** [comment]
No, it's the release ID (?), the url is: https://musicbrainz.org/release/b1514b18-f337-4907-a531-a7a039bdbbe1

Is that something else?

**Comment by sampsyo** [comment]
You are tagging a single track here (in singleton mode), so beets is expecting a recording ID. You can either supply the ID for the individual recording, or you can import it in album mode.

**Comment by butter-radish** [comment]
Ohhh. Hehe, sorry, I didn't expect singeton mode to work like that. 

Thank you <3
