### ISSUE TITLE
discogs: Set `medium_total` in TrackInfo

### ISSUE THREAD

**Issue by sampsyo** [beetbox/beets#415]
The Discogs plugin currently doesn't set `medium_total`, which can lead to incorrect `tracktotal` fields when `per_disc_numbering` is on.

Overall, the situation with medium grouping leaves something to be desired in the current implementation. We're duplicating a lot of information across the `TrackInfo.index`, `TrackInfo.medium_index`, `TrackInfo.medium`, and `TrackInfo.medium_total` fields along with the ordering in the `AlbumInfo.tracks` list and the `AlbumInfo.mediums` field.

Maybe we should overhaul these so that the information is stored in one place—for example, by allowing `tracks` to be a list of lists, or using a `medium_lengths` field to indicate the size of each medium. The goal here would be to minimize the headache for the data source author necessary to get the numbering correct.

**Comment by diego-plan9** [comment]
Added `medium_total` to `TrackInfo` during imports from the discogs plugin on #2222 (fb398c5f2c65c894a4c2887ec378919fd7952a52). I'm leaving the issue open as the overhauling of the fields did not take place (and seems like it would indeed be a good idea, organization-wise).

**Comment by sampsyo** [comment]
Great; thank you! If it's OK with you, I'll close this issue since we no longer have a bug here. The refactoring would still be good to consider, but we can leave that to a separate effort.
