### ISSUE TITLE
lyrics: Tekstowo.pl backend includes non-lyric content

### ISSUE THREAD

**Issue by eternaleye** [beetbox/beets#4161]
The Tekstowo.pl backend (as of 1.5.0) looks for the div with the class "song-text", but this div contains several things besides the actual lyrics, resulting in some Polish text before and after the lyrics. Changing the end of its `extract_lyrics` method from this:
```
        return lyrics_div.get_text()
```
to this:
```
        lyrics_inner = lyrics_div.find('div', class_="inner-text")
        if not lyrics_inner:
            return None
        
        return lyrics_inner.get_text()
```

resolves the issue.

**Comment by sampsyo** [comment]
Awesome---any chance you could open a PR with this change?
