### ISSUE TITLE
`confuse` dependency requirement permits invalid versions

### ISSUE THREAD

**Issue by billyjanitsch** [beetbox/beets#4167]
### Problem

Beets declares a dependency on `confuse>=1.0.0`:

https://github.com/beetbox/beets/blob/e3f4e19298cb9296dc636b7a15ab77d98087b635/setup.py#L92

But it uses `confuse.Optional`, which was only [added in `confuse@1.5.0`](https://github.com/beetbox/confuse/blob/e7a6566659f31bc4f39a9ac608e0d60bb48da471/docs/changelog.rst#v150):

https://github.com/beetbox/beets/blob/3b531811b982119c6e598433e413e8ca9f2ad068/beetsplug/fetchart.py#L984

This causes beets to crash if you happen to have an earlier version of `confuse` installed, e.g., 1.4.0:

```
AttributeError: module 'confuse' has no attribute 'Optional'
```

I assume the fix is to increase the dependency requirement to `confuse>=1.5.0`.

### Setup

* OS: macOS 12.0.1
* Python version: 3.9.9
* beets version: 1.6.0
* Turning off plugins made problem go away (yes/no): 

My configuration (output of `beet config`) is:

```yaml
n/a
```

**Comment by sampsyo** [comment]
Thanks! I had not noticed we had started using more recent Confuse features. I'll change the dependency now. :sparkles:

**Comment by basings** [comment]
I just ran into this problem as well, I looked into https://github.com/beetbox/beets/blob/master/setup.py yet the requirements is properly specified.

beets v 1.6.9. 
python 3.11.1

I solved it by installing the right confuse version `pip install --force-reinstall -v "confuse==1.5.0"`
