### ISSUE TITLE
spotify: Use pagination to fetch beyond the first 50 tracks of a release

### ISSUE THREAD

**Issue by dschrempf** [beetbox/beets#4180]
Not sure if this is a problem related to the plugin, or if the Spotify API doesn't serve more than 50 tracks per release. The other tracks are reported "Unmatched" during import.

**Comment by sampsyo** [comment]
Interesting! Do you know if there's anything to be done about this? (That is, does the API support any method for getting the remaining tracks?)

**Comment by sampsyo** [comment]
Great; thanks! Seems like a (maybe) straightforward feature to add if anyone’s interested.

**Comment by arsaboo** [comment]
I wish I could code :)

Looks like Spotify integration needs some love. We should also capture the `albumid` while we are at it.

**Comment by dschrempf** [comment]
I just realized that this may also be a problem for `deezer`. I can only fetch the first 25 tracks per album.

**Comment by dschrempf** [comment]
I do not really use deezer, so I don't open an issue for this plugin now. Should we create a separate issue for `deezer` pagination?

**Comment by sampsyo** [comment]
Yeah, a separate issue is a pretty good idea!
