### ISSUE TITLE
-A adds new unknown numeration

### ISSUE THREAD

**Issue by aibradford** [beetbox/beets#4194]
Starting today, when I try to run `"beet import -A (location)"`, 

The output of the file inputs a series of numbers in the folder title that appear to by a catalog of albums it has scanned, as each new album it scans it gives a consecutive number to. This is extremely problematic because it adds extra things into the folder title, so every time it runs the scan, it re-scans each folder, and creates a new folder with a new number in it.

For Example:
<img width="1032" alt="Screen Shot 2021-12-08 at 7 08 10 PM" src="https://user-images.githubusercontent.com/3916519/145310912-21ad4548-c68b-408f-8567-358e1793a205.png">

my config is here: https://pastebin.com/Q0yi1mes

This only started today. 
I also get this error when running it:

```
> /opt/homebrew/lib/python3.9/site-packages/beets/util/confit.py:19: UserWarning: beets.util.confit is deprecated; use confuse instead
  warnings.warn("beets.util.confit is deprecated; use confuse instead")
```

not sure if its related to why I'm getting this added info...

Any help would be greatly appreciated.

**Comment by sampsyo** [comment]
Looking at your `paths:` configuration could probably help. It seems likely those are from `%aunique`, perhaps, which could occur if you have similar/duplicate albums in your library.
