### ISSUE TITLE
discogs: discogs_albumid is always 0

### ISSUE THREAD

**Issue by jordanbs** [beetbox/beets#4225]
Most of my music is imported using the discogs plugin (beets v1.6.0, formerly imported via beets 1.4.9), but the every single discogs_albumid field is equal to 0. I do notice, however, the mb_albumid field contains what should be in discogs_albumid.

E.g.
```
         data_source: Discogs
     discogs_albumid: 0
    discogs_artistid: 1954908
     discogs_labelid: 1085864
    mb_albumartistid: 1954908
          mb_albumid: 10346192
   mb_releasegroupid: 1185315
```

Reproduce this by importing an album and using Discogs as the source. Re-importing will do.

**Comment by sampsyo** [comment]
Thanks! I expect that something changed in the Discogs API about reporting IDs, as I mentioned in https://github.com/beetbox/beets/discussions/4224#discussioncomment-1915369:

> It is probably related to #4080. I think #4085 probably should have eliminated `extract_release_id` altogether and replaced it with the new `extract_release_id_regex` or similar.

To debug this, the first step would be to dump out the argument to `extract_release_id` and see what it consists of. If it's a URL, it probably works to just call `extract_release_id_regex` instead.

**Comment by jordanbs** [comment]
That works.

**Comment by JOJ0** [comment]
@jordanbs have you found the time to open a PR for this? Or can you describe the fix here. I'm also interested in getting this fixed. Thanks :-)

**Comment by jordanbs** [comment]
Unfortunately I'm not able to do that.

But you can!

On line 317 of beetsplug/discogs.py, replace `extract_release_id` with `extract_release_id_regex`.

**Comment by JOJ0** [comment]
> Unfortunately I'm not able to do that.
> 
> But you can!
Yes I can but you can too :-) For such a small fix you could even edit this directly on github without any git CLI knowledge necessary at all (if that is what was holding you back)! Did you know that?

**Comment by jordanbs** [comment]
I'm sorry, I'm legally not allowed to contribute to open source :(
