### ISSUE TITLE
Discogs plugin treats headings as index tracks

### ISSUE THREAD

**Issue by musiczetetic** [beetbox/beets#4234]
**The Problem**

I recently upgraded to a newer version of beets and discovered the implementation of [index tracks](https://github.com/beetbox/beets/pull/3459) into the discogs plugin. Great quick implememtation. One problem I quickly discovered is that the plugin treats headings as index tracks. Possibly because the [original example](https://www.discogs.com/release/2026070-Handel-Sutherland-Kirkby-Kwella-Nelson-Watkinson-Bowman-Rolfe-Johnson-Elliott-Partridge-Thomas-The-A) from the [original request](https://www.discogs.com/release/2026070-Handel-Sutherland-Kirkby-Kwella-Nelson-Watkinson-Bowman-Rolfe-Johnson-Elliott-Partridge-Thomas-The-A) was actually an example of headings and not index tracks.

Quick discogs background: Before index tracks were implemented there were only headings so the original example was a correct submission in the past but would be treated differently if it was submitted now or updated.

Here is an [example of index tracks](https://www.discogs.com/release/11024529-Ludwig-van-Beethoven-Wilhelm-Kempff-Path%C3%A9tique-Mondschein-Moonlight-Appassionata) versus the [example of headings](https://www.discogs.com/release/2026070-Handel-Sutherland-Kirkby-Kwella-Nelson-Watkinson-Bowman-Rolfe-Johnson-Elliott-Partridge-Thomas-The-A)

While the use of headings in classical music is probably mostly the same as the use of index tracks, for most other genres of music treating headings like index tracks is not useful.

I am assuming the plugin treats actual index tracks the same. It is a bit confusing for those who are well versed in discogs terminology to treat headings as index tracks.

Update: I just used beets for [this release](https://www.discogs.com/release/8377799-Uri-Caine-Jenny-Lin-The-Spirio-Sessions) with index tracks and it worked fantastic, exactly as I would expect it to.

**The Solution**

Treat headings differently to index tracks.

**1.** 
index_tracks: yes/no
headings: yes/no

**2.**
I think headings for most other genres would work better as album subtitles. For example on [this realease](https://www.discogs.com/release/5352922-David-Lynch-The-Big-Dream) or [this release](https://www.discogs.com/release/21636949-David-Bowie-Toy) I discovered the problem on.

index_tracks: yes/no
headings: name/album/no

On both those linked releases the heading for the first disc are the same as the album name, it would be good if that was checked and ignored if that was the case.

**Comment by ybnd** [comment]
Did a bit of digging:
* Looks like this is happening [here](https://github.com/beetbox/beets/blob/ee77b6fbe2967fc0d6df7b56b3cfa650661f2e9a/beetsplug/discogs.py#L410-L417)
  For the [Handel example](https://www.discogs.com/release/2026070-Handel-Sutherland-Kirkby-Kwella-Nelson-Watkinson-Bowman-Rolfe-Johnson-Elliott-Partridge-Thomas-The-A) the headings pass through there since they don't have a `position`
* We could filter them out ~ `track['type_'] != 'index'`, but we'd have to be careful not to disrupt [this mechanism for setting disc titles](https://github.com/beetbox/beets/blob/ee77b6fbe2967fc0d6df7b56b3cfa650661f2e9a/beetsplug/discogs.py#L464-L472) which uses those same "index tracks"
* I noticed that we're also messing up some tracks, compare the Discogs page to this excerpt of the resulting tracklist in beets:
  ```
  5-05    Athalia, Act III, Scene 2: Chorus- Shall We Of Servitude Complain
  5-06    Athalia, Act III, Scene 2: Aria- Praise The Lord With Cheerful Noise
  5-07.a  Athalia, Act III, Scene 2: Aria- Sing Songs Of Praise, Bow Down The Knee

  5-07    Athalia, Act III, Scene 2: Scene 3
   -> should be "5-07.b  Recitative- How Have Our Sins Provoked The Lord!"
  5-08    Athalia, Act III, Scene 2: Chorus- Ye Sons Of Israel Mourn
  5-09.a  Athalia, Act III, Scene 2: Aria- O Jordan, Jordan, Sacred Tide

  5-09    Athalia, Act III, Scene 2: Scene 4
   -> should be "5-09.b  Recitative- Why Sits That Sorrow On Thy Brow?"
  5-10    Athalia, Act III, Scene 2: Aria- Dread Not, Righteous Queen, The Danger
  5-11    Athalia, Act III, Scene 2: Aria- Tears Assist Me, Pity Moving
  ```
  * Some headings are interpreted as tracks
  * Override the _actual_ first track of their section, leaving the prefix unchanged
  * Haven't checked with other releases yet so I don't know how often this occurs, but we should probably also fix this

**Comment by ybnd** [comment]
1. I'm not sure it's a good idea to essentially drop support for releases like the Handel example; we still need to use the headings in those cases
2. [We already extract disc titles](https://github.com/beetbox/beets/blob/ee77b6fbe2967fc0d6df7b56b3cfa650661f2e9a/beetsplug/discogs.py#L464-L472) from these headings.
   We'd have to add some extra logic to get rid of the prefix but keep the disc title, but if we do keep the "headings as index tracks" case for compatibility I can't think of a good way to distinguish when we want the prefix... Relying on the name of the album/heading won't ever work 100%

**Comment by musiczetetic** [comment]
Thanks for your comments.

1. This option wouldn't drop support it would just give users the option of treating them differently. In my case I would have headings off for track naming and run a separate process with them on for the few times I needed it. Others might do the opposite.

2. Can I make use of this disctitle function in any way? I haven't seen it mentioned anywhere. I note that in that code it refers to index tracks rather than headings. Is it referring to index tracks or headings or both? I can't help but think there is still a misunderstanding of the difference between headings and index tracks, there are no prefixes (track numbers?) for headings. Headings and index tracks in discogs are different and used in different ways, it is just that headings existed before index tracks so you will find cases of old submissions using headings where index tracks would be better suited.

**Comment by sampsyo** [comment]
Thanks for starting the discussion! As an outsider to Discogs standards, can I ask some extremely basic questions about what's currently happening?

Namely, what exactly does beets currently do with index tracks, and what should it do (perhaps behind a config option)? Are we treating these index tracks as normal tracks, which then are guaranteed never to match any files the user has? Or are we treating them only as disc titles, and we _should_ be treating them as tracks?

(Again, apologies for being slow, but I don't quite understand yet exactly what the current behavior is…)

**Comment by musiczetetic** [comment]
Hi Adrian,
As someone who has been using Discogs for 20 years I am happy to answer any questions you might have.

Currently with the "index_tracks" config option turned on beets adds the index tracks to the beginning of the sub tracks name, which seems like the correct way to handle them. They are being treated as part of the name of the sub tracks. They are part of the name of the sub tracks most commonly in classical music. We shouldn't be treating them as separate tracks, I think the way they are handled now is correct.

I can't describe the purpose of index tracks any better than the [Discogs guidelines ](https://support.discogs.com/hc/en-us/articles/360005055373-Database-Guidelines-12-Tracklisting#Index_Tracks_And_Headings)does:
_Index Tracks are used whenever the Index Track Title is the title of a musical piece and the Sub-tracks below are parts or movements of that piece._

The problem I am raising is that **headings** are being treated the same way as **index tracks** which is wrong except for legacy discogs submissions that were made before index tracks were introduced. Index tracks and Headings have different purposes.

As per Discogs guidelines _Use a "Heading" whenever there is a block of text on the release that is descriptive of the tracks below, but is not the title of a musical piece._

We might not be able to do anything useful with them because they are used for varying diffferent purposes. Sometimes for disc titles on multidisc sets, sometimes for a sub heading on an album. I could probably find examples if required.

The best option may be just to leave how it works as is but add an option to turn off treating Headings the same way.

I am not sure what the disc titles function is doing. I have never seen it added to my tags, maybe it is something in the beets database only.

**Comment by ybnd** [comment]
AFAIK `disctitle` is taken pretty loosely in beets already, so it's probably not a big issue if it's not super consistent

We should be able to address this by making our configuration a bit more fine-grained, e.g. with 4 options:
* Index tracks
  - Use for prefix?
  - Use for `disctitle`
* Headings
  - Use for prefix?
  - Use for `disctitle`?

Given how index tracks are described above and the fact how headings like the ones on the Bowie & Lynch examples you gave above don't make much sense with the headings as a prefix, I think it's reasonable to go with the following defaults:
* Index tracks -> prefix, but not `disctitle`
* Headings -> `disctitle` but not prefix



I'd suggest postponing this until I can fix the data loss issue in #4235 though, since it involves a lot of the same functionality & seems more critical

**Comment by ybnd** [comment]
> Can I make use of this disctitle function in any way? I haven't seen it mentioned anywhere.
It's one of our metadata fields, you can use it in queries and formatting.
I suppose a common usage would be for path configuration, e.g. to divide albums into multiple folders

**Comment by ybnd** [comment]
There's also a small bug right now that causes `disctitle` to only appear on the first track of each section

**Comment by musiczetetic** [comment]
Yes, ytill relevant.

**Comment by sampsyo** [comment]
It would be great to hear from other folks on the thread about what exactly the new behavior should be… @musiczetetic says:

> The best option may be just to leave how it works as is but add an option to turn off treating Headings the same way.

Is that what folks want? If so, how _would_ Headings be treated?

**Comment by emanuele-virgillito** [comment]
hi @sampsyo, as a heavy discogs user i would find perfect the behavior proposed by @ybnd !

**Comment by ybnd** [comment]
Shouldn't be closed; there's still an in-progress PR to try and adress this & in the meantime this issue should stay open to gather more feedback from users

**Comment by musiczetetic** [comment]
> Given how index tracks are described above and the fact how headings like the ones on the [Bowie](https://www.discogs.com/release/21636949-David-Bowie-Toy) & [Lynch](https://www.discogs.com/release/5352922-David-Lynch-The-Big-Dream) examples you gave above don't make much sense with the headings as a prefix, I think it's reasonable to go with the following defaults:
> 
>     * Index tracks -> prefix, but not `disctitle`
> 
>     * Headings -> `disctitle`, but not prefix

I agree with this proposal for defaults settings.

It would be good when manually approving each match that an option to use or ignore them would be presented. Not sure how this would look or if it is even possible. Because of the inability to turn off MusicBrainz matches I have to manually select the discogs option for every search at the moment anyhow.

**Comment by musiczetetic** [comment]
Still relevant.

**Comment by JOJ0** [comment]
Hi, thanks for reporting this and starting a PR, I'm just here to report examples of where the current implementation renders using Discogs as the source plugin unusable. These 2 releases both would lead to the importer grabbing just two tracks:

https://www.discogs.com/release/831995-Various-The-Eclectic-Sound-Of-Vienna-1-2

```
beet import eclectic volume 1 -L -t -S 831995

/remote/data/music-library/Christl CD collection/Compilations/1997 - The Eclectic Sound of Vienna, Volume 1 (10 items)
Correcting tags from:
    The Eclectic Sound of Vienna, Volume 1
To:
    The Eclectic Sound Of Vienna 1 + 2
URL:
    https://www.discogs.com/release/831995-Various-The-Eclectic-Sound-Of-Vienna-1-2
(Similarity: 28.6%) (id, unmatched tracks, tracks, catalognum, album, year) (Discogs, CD, 2003, Austria, Spray Records, 82876 51669 2)
 * Fuckdubworksong (Uptight mix) -> Fuckdubworksong (Uptight Mix) / Bazaar / Closer To God / Elephants Walk / Close2eve / Si Commandante! (Real Shit Mix) / The Wanna Do Track / Speechless Drum & Bass / Aquaribass / How Will He Touch? (id, title)
 * Bazaar                        -> Children Of The Ghetto (Eclectic Mix) / Keepin' Da Funk Alive / Happy (Uptight Anti-Stress Workout) / Get Off My Wall (All American Soulstar Radio Edit) / Sand Rabbit / What Goes Up (FM4 Edit) / The Plan (Aphrodite Remix) / Jewel Of The Day (Earth Edit) / Blue / Rollin' On Chrome (Wild Motherfucker Dub) / Holy Smoke / Carpenter / Let The Peace Come On / 10 / Traces (id, artist, title)
Unmatched tracks (8):
 ! Closer to God                  (# 3) (6:55)
 ! Elephants Walk                 (# 4) (5:35)
 ! Close2eve (feat. Timea)        (# 5) (3:28)
 ! Si Commandante (Real Shit mix) (# 6) (5:28)
 ! The Wanna do Track             (# 7) (5:25)
 ! Speechless (Drum & Bass)       (# 8) (6:51)
 ! Aquaribass                     (# 9) (8:34)
 ! How Will He Touch?             (#10) (7:58)
Apply, More candidates, Skip, Use as-is, as Tracks, Group albums,
Enter search, enter Id, aBort, eDit, edit Candidates, plaYi     

```


https://www.discogs.com/release/1125261-Kruder-Dorfmeister-The-KD-Sessions

Sorry, just an example of trying to use the Discogs release. It's the wrong files! Anyway:

```
Enter release ID: 1125261
Correcting tags from:
    Various Artists - The Eclectic Sound of Vienna, Volume 1
To:
    Kruder & Dorfmeister - The K&D Sessions™
URL:
    https://www.discogs.com/release/1125261-Kruder-Dorfmeister-The-KD-Sessions
(Similarity: 16.9%) (id, unmatched tracks, tracks, album, artist, catalognum, label, year) (Discogs, CD, 1998, Germany, !K7, !K7073CD)
 * Fuckdubworksong (Uptight mix) -> Part One (id, title)
 * Bazaar                        -> Part Two (id, title)
Unmatched tracks (8):
 ! Closer to God                  (# 3) (6:55)
 ! Elephants Walk                 (# 4) (5:35)
 ! Close2eve (feat. Timea)        (# 5) (3:28)
 ! Si Commandante (Real Shit mix) (# 6) (5:28)
 ! The Wanna do Track             (# 7) (5:25)
 ! Speechless (Drum & Bass)       (# 8) (6:51)
 ! Aquaribass                     (# 9) (8:34)
 ! How Will He Touch?             (#10) (7:58)
Apply, More candidates, Skip, Use as-is, as Tracks, Group albums,
Enter search, enter Id, aBort, eDit, edit Candidates, plaY? 
```

**Comment by ybnd** [comment]
@JOJ0 IMO this should probably be handled in a separate issue/PR though, as to avoid more scope creep & delays with this one (mostly on me, but still)

**Comment by JOJ0** [comment]
Yeah sure, totally agree! I dont want to pollute the current pr's fix. Was just wondering if I'm hitting the same thing. thanks for clarifying! appreciated!

**Comment by musiczetetic** [comment]
> * A neat way to be a bit more flexible while still retaining this functionality could be to generate _two_ candidates for such albums: one where we combine the "subtracks" and one where we don't. Then we can leave it up to the matcher to figure out which representation fits best with the files we're importing.

This sounds like a good solution
