### ISSUE TITLE
Discogs-Client Not Found

### ISSUE THREAD

**Issue by OliTechFR** [beetbox/beets#4242]
Hello everyone, I wanted to try to use the software with discogs for some songs I have but then I have this error. I tried some commands found on the internet but I can't find any solutions. Can you help me? I get this error when I type any command.
### Problem
```
** error loading plugin discogs:
Traceback (most recent call last):
  File "/Users/olitech/Library/Python/3.9/lib/python/site-packages/beets/plugins.py", line 276, in load_plugins
    namespace = __import__(modname, None, None)
  File "/Users/olitech/Library/Python/3.9/lib/python/site-packages/beetsplug/discogs.py", line 26, in <module>
    from discogs_client import Release, Master, Client
ModuleNotFoundError: No module named 'discogs_client'
```
### Setup
* OS: MacOS 12.1
* Python version: 3.9.7
* beets version: 1.5.0

**Comment by sampsyo** [comment]
As the docs for the plugin say:
https://beets.readthedocs.io/en/stable/plugins/discogs.html

You'll need to `pip install` the relevant library.
