### ISSUE TITLE
No such file or directory error with non english characters on Windows 

### ISSUE THREAD

**Issue by JohnKara** [beetbox/beets#4282]
### Problem

When I type this command in cmd: 

```sh
beet -vv import ~/Music/Γιάννης
```
I get this error: 
```
user configuration: C:\Users\giann\AppData\Roaming\beets\config.yaml
data directory: C:\Users\giann\AppData\Roaming\beets
plugin paths:
Sending event: pluginload
library database: C:\Users\giann\AppData\Roaming\beets\library.db
library directory: C:\Users\giann\Music
Sending event: library_opened
error: no such file or directory: ~/Music/
```

Also I get this output from the below commands in cmd: 

```cmd
>chcp
Active code page: 737
```
```python
>>> import sys, locale
>>> sys.stdout.encoding
'utf-8'
>>> locale.getpreferredencoding()
'cp1253'
>>> sys.stdout.buffer.write('Γιάννης'.encode('utf-8'))
Γιάννης14
>>> sys.stdout.buffer.write('Γιάννης'.encode('cp1253'))
�������7
>>> sys.stdout.buffer.write('Γιάννης'.encode('cp737'))
��ᤤ��7
```

I tried to fix this error but, I'm very confused about how the encoding works on Windows and python. Can anyone please help me understand why am I getting this error and how the encoding works on Windows so that I can fix this error? 
From what I've read, Windows uses two encodings or code pages (Windows or ANSI code page and MS-DOS or OEM code page), mine are cp1253 (ANSI) and cp737 (OEM). 

If I change ```arg_encoding()``` function in ```util\__init__.py``` to return 'utf-8', the problem seems to be solved.

### Setup

* OS: Windows 10 x64
* Python version: 3.7.4
* beets version: Downloaded from github
* Turning off plugins made problem go away (yes/no): no

My configuration (output of `beet config`) is:

```yaml
import:
    move: yes
plugins: fromfilename fetchart
paths: 
    default: $albumartist/$album/$title
```

**Comment by sampsyo** [comment]
Thank you for the report. Unfortunately, problems like this involving argument encodings are extremely hard to diagnose, even with direct access to the system. 

It's interesting that "faking" the argument encoding as UTF-8. Could you check the value of `locale.getdefaultlocale()[1]` on your system to see what it currently reports as the argument encoding?

As you can see here, we attempt to _encode_ the Unicode paths as bytes using this encoding:
https://github.com/beetbox/beets/blob/5f45e9e10894ea94d35a885d25c4c4ffffcfaa91/beets/ui/commands.py#L970-L971

**Comment by JohnKara** [comment]
```locale.getdefaultlocale()[1]``` returns 'cp1253' same as ```locale.getpreferredencoding()```.

I think that Windows console now supports Unicode, that's why modifying ```arg_encoding()``` to return 'utf-8' works. 
https://docs.python.org/3/whatsnew/3.6.html#whatsnew36-pep528
https://stackoverflow.com/questions/388490/how-to-use-unicode-characters-in-windows-command-line

Also, if I apply the below solution instead (and not changing the ```arg_encoding()``` function), the problem is solved and I get the following output from the previous commands:
https://stackoverflow.com/questions/57131654/using-utf-8-encoding-chcp-65001-in-command-prompt-windows-powershell-window
```cmd
>chcp
Active code page: 65001
```
```python
>>> import sys, locale
>>> sys.stdout.encoding
'utf-8'
>>> locale.getpreferredencoding()
'cp65001'
>>> locale.getdefaultlocale()[1]
'cp65001'
```
So can we use ```'utf-8'``` on Windows instead of ```locale.getdefaultlocale()[1]``` or will this cause other problems?

**Comment by sampsyo** [comment]
Interesting; that's a useful data point!

> So can we use `'utf-8'` on Windows instead of `locale.getdefaultlocale()[1]` or will this cause other problems?

That is indeed the $1M question. It's great that this works on your setup, but I think the next steps here would be to do some digging to understand if this is a correct solution universally… or whether it might cause other problems for other configurations.
