### ISSUE TITLE
discogs: "3 vinyl split" release not possible to add

### ISSUE THREAD

**Issue by JOJ0** [beetbox/beets#4290]
Sorry for being brief here for now. I will elaborate the problem later. Not sure if it is a discogs tagger only problem. Will investigate.

Not-technically speaking the problem is: Sometimes albums (releases in discogs speak) were put out on several vinyls (catalog numbers MM129A, MM129B, MM129C in this case). They all **_share the same master release_**. For example these 2 vinyls were available to buy separately:

![Screen Shot 2022-02-20 at 12 01 40](https://user-images.githubusercontent.com/2733783/154839392-30cfbda4-91ee-4449-9fa3-47af31693843.png)

https://www.discogs.com/release/830530-Dave-Clarke-Remixes-Rarities-1992-2005

https://www.discogs.com/release/830537-Dave-Clarke-Remixes-Rarities-1992-2005

(There is a third one MM129C but I don't want to tag it because I don't have the mp3, if that matters...)

Importing the first one works fine but when trying to import the second one, beets always wants to overwrite the previously imported one:

```
Enter release ID: 830537
Tagging DJ Rush - Dave Clarke Presents Remixes & Rarities Part B-(MM 129B) Vinyl
Searching for album ID: 830537
Requesting MusicBrainz release 830537
Invalid MBID (830537).
discogs: Searching for release 830537
discogs: Searching for master release 93537
Sending event: albuminfo_received
Candidate: Dave Clarke - Remixes & Rarities 1992-2005 (830537)
Computing track assignment...
...done.
Success. Distance: 0.57
Evaluating 1 candidates.
Sending event: before_choose_candidate
Correcting tags from:
    DJ Rush - Dave Clarke Presents Remixes & Rarities Part B-(MM 129B) Vinyl
To:
    Dave Clarke - Remixes & Rarities 1992-2005
URL:
    https://www.discogs.com/release/830537-Dave-Clarke-Remixes-Rarities-1992-2005
(Similarity: 43.0%) (tracks, artist, album, source, country) (Discogs, Vinyl, 2006, Belgium, Music Man Records, MM129B)
 * Freaks on Hubbard (Dave Clarke Remix).Mp3 - Cm - 143             -> Freaks On Hubbard (Dave Clarke Remix) (id, title)
 * B2-Lie to Me (Dave Clarke Full Vocal Version).Mp3 - Gm - 66 (#3) -> Lie To Me (Dave Clarke Remix) (#2) (title, index)
 * B1-La La Land (Dave Clarke Remix).Mp3 - Abm - 136 (#2)           -> La La Land (Dave Clarke Remix) (#3) (id, index, title)
Apply, More candidates, Skip, Use as-is, as Tracks, Group albums,
Enter search, enter Id, aBort, plaY, eDit, edit Candidates? a
Sending event: import_task_choice
found duplicates: [123]
default action for duplicates: a
This album is already in the library!
Old: 3 items, MP3, 221kbps, 15:27, 24.7 MiB
New: 3 items, MP3, 209kbps, 17:49, 26.8 MiB
[S]kip new, Keep all, Remove old, Merge all?
```

Not sure if it's because the album/release name is the same or it is because of the same master release (https://www.discogs.com/master/93537-Dave-Clarke-Remixes-Rarities-1992-2005)

### Setup

* OS: macOS 10.13 
* Python version: 3.9.x
* beets version: git latest
* Turning off plugins made problem go away (yes/no): no

My configuration (output of `beet config`) is:

```yaml
FIXME
```

**Comment by sampsyo** [comment]
FWIW, it's because they have the same artist and title—that's how beets' "duplicate detection" works. #4199 may be relevant to you, or you may just choose "Keep all" at this prompt.

**Comment by JOJ0** [comment]
I'll try keep all... thanks!

**Comment by JOJ0** [comment]
Yes, sorry for the hassle I though I tried out all the options on import but obviously I didn't realize that choosing "Keep All" does just what I want:

```
(beets) jojo@gin ~/git/beets (skip_write) $ beet ls 'catalognum::MM129.*'
Dave Clarke - Remixes & Rarities 1992-2005 - 01 - Hot In The Heels Of Love (Dave Clarke Remix) (2006/Belgium) [MM129A]  211kbps  m:2016-09-14 08:06:06  a:2016-09-14 08:06:06 relaxed:$mood_relaxed
Dave Clarke - Remixes & Rarities 1992-2005 - 01 - Freaks On Hubbard (Dave Clarke Remix) (2006/Belgium) [MM129B]  216kbps  m:2016-09-14 08:06:09  a:2016-09-14 08:06:09 relaxed:$mood_relaxed
Dave Clarke - Remixes & Rarities 1992-2005 - 02 - Cars (Dave Clarke Remix) (2006/Belgium) [MM129A]  223kbps  m:2016-09-14 08:06:06  a:2016-09-14 08:06:06 relaxed:$mood_relaxed
Dave Clarke - Remixes & Rarities 1992-2005 - 02 - Lie To Me (Dave Clarke Remix) (2006/Belgium) [MM129B]  201kbps  m:2016-09-14 10:38:17  a:2016-09-14 08:06:09 relaxed:$mood_relaxed
Dave Clarke - Remixes & Rarities 1992-2005 - 03 - Road Tour (Dave Clarke Remix) (2006/Belgium) [MM129A]  229kbps  m:2016-09-14 08:06:06  a:2016-09-14 08:06:06 relaxed:$mood_relaxed
Dave Clarke - Remixes & Rarities 1992-2005 - 03 - La La Land (Dave Clarke Remix) (2006/Belgium) [MM129B]  209kbps  m:2016-09-14 08:09:31  a:2016-09-14 08:06:09 relaxed:$mood_relaxed
(beets) jojo@gin ~/git/beets (skip_write) $
(beets) jojo@gin ~/git/beets (skip_write) $
(beets) jojo@gin ~/git/beets (skip_write) $
(beets) jojo@gin ~/git/beets (skip_write) $
(beets) jojo@gin ~/git/beets (skip_write) $
(beets) jojo@gin ~/git/beets (skip_write) $ beet ls -a 'catalognum::MM129.*'
Dave Clarke - 2006 [MM129A] - Remixes & Rarities 1992-2005  a:2016-09-14 08:06:06
Dave Clarke - 2006 [MM129B] - Remixes & Rarities 1992-2005  a:2016-09-14 08:06:09
(beets) jojo@gin ~/git/beets (skip_write) $
```

**Comment by JOJ0** [comment]
And thanks for the issue link, I just had the idea that in my case taking the catalognumber into account with dup finding would have helped. Awesome you are working on a configurable solution already! :-)

**Comment by JOJ0** [comment]
Just here to say thanks: The feature in the linked PR that was recently merged, fixes exactly the problem I had with this "3 vionyl split" album/release.

Adding this to config now does the trick:
```
import:
    album: albumartist album catalognum
    item: artist title catalognum
```
