### ISSUE TITLE
Write custom tags to files on import

### ISSUE THREAD

**Issue by AlexChalk** [beetbox/beets#4294]
###### Originally discussed in https://github.com/beetbox/beets/discussions/4293

Hi,

Using the plugin infrastructure, I'm trying to add a custom tag when importing files. The idea is that my plugin will add an `AlbumSort` field customized as `$year $album`, since my mp3 player uses this tag to change how albums are ordered.

Based on https://beets.readthedocs.io/en/stable/dev/plugins.html, here's what I've got so far:
```
from beets.plugins import BeetsPlugin
from beets import config
import mediafile


# pip install ./beets-albumsort
class AlbumSortPlugin(BeetsPlugin):
    def __init__(self, *args, **kwargs):
        super(AlbumSortPlugin, self).__init__(*args, **kwargs)
        field = mediafile.MediaField(
            mediafile.MP3DescStorageStyle(u'AlbumSort'),
            mediafile.StorageStyle(u'AlbumSort')
        )
        self.add_media_field('AlbumSort', field)

        self.register_listener('write', self.write)

    def write(self, item, path, tags):
        tags["AlbumSort"] = f"{tags['original_year']} {tags['album']}"
```

The above code does not work :/. Writing the custom value to `tags["album"]` works just fine, so I guess I'm going wrong somewhere with how I'm registering the custom tag name. Can anyone help me out? Thanks!

**Comment by sampsyo** [comment]
I think a discussion thread (https://github.com/beetbox/beets/discussions/4293) is the right place to work on this.
