### ISSUE TITLE
lyrics: Genius backend includes heading in lyrics

### ISSUE THREAD

**Issue by ybnd** [beetbox/beets#4305]
### Problem

Lyrics fetched from the Genius backend include text from the heading above the lyrics
For example, [this page](https://genius.com/Ttng-chinchilla-lyrics) results in
```
Chinchilla LyricsSo far we've lost focus
Let's just concentrate on words that could mean everything
...
```
AFAIK this heading is always `<track> Lyrics` so there's no reason for us to keep it in.

**Comment by sampsyo** [comment]
Thanks for noticing this! Could be a recent change in their markup.

**Comment by dannn-o** [comment]
Encountering this issue as well after recently upgrading beets to 1.6.0 (to get fixes for other lyrics-related issues like #4228).

**Comment by olgarrahan** [comment]
Could I work on this?

**Comment by ybnd** [comment]
@olgarrahan Sure!
