### ISSUE TITLE
Disabling plugins CLI option

### ISSUE THREAD

**Issue by JOJ0** [beetbox/beets#4325]
The current CLI option:
```
-p PLUGINS, --plugins=PLUGINS
                        a comma-separated list of plugins to load
```
is tedious to use when many plugins are in use. Often a user might just want to disable a single plugin or a tiny list of plugins to try something/do something in a specific beets run. 

### Proposed solution

Add a CLI option named eg. `--disable-plugins/-P` that allows mentioning a comma separated list of plugin-names to stay disabled for that beets run.

**Comment by sampsyo** [comment]
Sounds OK to me! It is probably worth noting that `--plugins` already can disable _all_ plugins, so I suppose this would just be about disabling one plugin?

It could also be worth looking at the #3765 thread for inspiration about how to tackle this.

**Comment by arbanhossain** [comment]
Hey, if I am understanding this right, I sort of have an implementation of this in my fork. It uses `-x/--exclude`. Should I do a PR for you to review?

**Comment by sampsyo** [comment]
A PR would be great!

**Comment by arsaboo** [comment]
Can we close this issue since #4332 is merged?

**Comment by sampsyo** [comment]
Yes, thanks for the reminder!!
