### ISSUE TITLE
Cannot run tests on an Ubuntu 20.04.3 AWS server

### ISSUE THREAD

**Issue by alicezou** [beetbox/beets#4328]
Hi, I am trying to run tests on Ubuntu 20.04.3(an AWS server).

### Problem
I am able to run 
```
pip install -e .
pip install -e .[test]
```
in beets/ directory

However, when I run tox, it failes.

```(py39) ubuntu@ip-xxx$~/beets$ tox
GLOB sdist-make: /home/ubuntu/beets/setup.py
ERROR: invocation failed (exit code 1), logfile: /home/ubuntu/beets/.tox/log/GLOB-0.log
======================================= log start ========================================
sphinx-build -b man -d _build/doctrees   . _build/man
Running Sphinx v1.8.5

Extension error:
Could not import extension sphinx.builders.latex (exception: cannot import name 'contextfunction' from 'jinja2' (/home/ubuntu/.local/lib/python3.8/site-packages/jinja2/__init__.py))
make: *** [Makefile:117: man] Error 2
/usr/lib/python3/dist-packages/requests/__init__.py:89: RequestsDependencyWarning: urllib3 (1.26.9) or chardet (3.0.4) doesn't match a supported version!
  warnings.warn("urllib3 ({}) or chardet ({}) doesn't match a supported "
Traceback (most recent call last):
  File "setup.py", line 52, in <module>
    build_manpages()
  File "setup.py", line 36, in build_manpages
    subprocess.check_call(['make', 'man'])
  File "/usr/lib/python3.8/subprocess.py", line 364, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['make', 'man']' returned non-zero exit status 2.

======================================== log end =========================================
ERROR: FAIL could not package project - v = InvocationError('/usr/bin/python3 setup.py sdist --formats=zip --dist-dir .tox/dist', 1)
```

### Setup

* OS: NAME="Ubuntu"
VERSION="20.04.3 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.3 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
* Python version: 3.8
* beets version: the current master 1167453ed8f2f74e0acb286b7c35f9cddb70fdc6
* Turning off plugins made problem go away (yes/no): not relevant

My configuration (output of `beet config`) is: not relevant

**Comment by sampsyo** [comment]
Hmm; it looks like the problem is coming from running [Sphinx](https://www.sphinx-doc.org/en/master/) to build the manpage that goes in the source distribution. I'm guessing that there is a partial Sphinx installation from the Debian packages (because Debian likes to "atomize" packages to install components separately).

Maybe try `pip install -U sphinx` to get the latest version from PyPI?

**Comment by alicezou** [comment]
Yes, it works (with some more errors that can be found on stackoverflow.)
BTW, can you check my pull request at #4327 ?
The integration tests as well as the local tests on AWS have passed.

**Comment by sampsyo** [comment]
Great! Leaving some notes here about how you fixed the problem might help other people in the future. :smiley:

It's in my queue (and hopefully that of other beets contributors as well).

**Comment by alicezou** [comment]
Yes, sure.
I got this error
```
ModuleNotFoundError: No module named 'virtualenv.seed.via_app_data'
```
I resolved it by
```
sudo apt remove --purge python3-virtualenv
```
from [this](https://stackoverflow.com/questions/63491221/modulenotfounderror-no-module-named-virtualenv-seed-embed-via-app-data-when-i) post on stackoverflow.
