### ISSUE TITLE
Move command should support copying files without modifying database

### ISSUE THREAD

**Issue by fortes** [beetbox/beets#435]
Currently the `copy` flag on the `move` command will copy files _and_ change their paths in the database. It would be useful to have a version of this that copies without modifying the library.

**Comment by BitterEarth** [comment]
Hey we would like to tackle this issue, if anyone is planning on working on this anytime soon let me know so we can find another issue. Thanks!

**Comment by BeetsStudentTeam** [comment]
Hey guys! we would like to tackle this issue, if anyone is going to work on this soon let me know so we can look at other issues! We're planning to start working on this on Monday February 1st. Thanks! -Jake

**Comment by SpirosChadoulos** [comment]
Greetings..I was thinking about tackling this issue but it is really old. Is it worth tackling it or not? Thanks a lot.

**Comment by sampsyo** [comment]
Absolutely, if you're interested!

**Comment by SpirosChadoulos** [comment]
Nice, could you explain me what you want me to do exactly?

**Comment by sampsyo** [comment]
The idea would be to add a flag to the `move` command, with one of the names above, that works *like* the current -c (copy) option but slightly different. Where the current option does two things—it copies the files and also updates the library database—the new -e option would instead copy the file *but leave the database unchanged*. I think that will involve a call along the lines of `util.copy(item.path, item.destination(basedir=...))`.

**Comment by SpirosChadoulos** [comment]
Should I do that in the commnad.py file or somewhere else?

**Comment by sampsyo** [comment]
Right in commands.py is the right place.

**Comment by SpirosChadoulos** [comment]
Could you explain to me briefly how the `move_items` function works in commands.py(line1453)? 
Thanks a lot.

**Comment by sampsyo** [comment]
I'd be happy to explain more, but can I please ask you to be specific with your question? The comments we've put there are already my best effort at explaining what's going on. What part specifically are you wondering about?

**Comment by SpirosChadoulos** [comment]
I see that the `move_items` function is where the move command is executed but I can distinguish where database interaction is happening.

**Comment by sampsyo** [comment]
Aha! Good question. That's the `obj.remove` call, which invokes either `Item.remove` or `Album.remove`, which are defined in `library.py`.

**Comment by SpirosChadoulos** [comment]
In line 1491 in command.py `obj.move` is called. `obj.remove` is called at line 1217. I am kind of confused with the code that is executed when the user uses the move command.

**Comment by sampsyo** [comment]
Oops! I'm so sorry; I lost track of what we were talking about and looked at the wrong function (`delete_items`). Anyway, you're right—the call to `obj.move` is the one you're looking for. That *both* moves the file and updates the stored path to reflect the new location.

**Comment by SpirosChadoulos** [comment]
So should I make changes to the `move_items` function in `commands.py` or in the `move` function in the `Item` class in `library.py`?

**Comment by sampsyo** [comment]
Good question! Just in the `move_items` function there. Let's leave the core library functionality unchanged—we can just change the way we invoke it.

**Comment by SpirosChadoulos** [comment]
I think that the move command is specifically happening at line 1491:`obj.move(copy, basedir=dest)`. If this is true how am I supposed to make it so that the database path doesn't change?

**Comment by sampsyo** [comment]
There's no current way to make `item.move` not update the database—updating the database is its purpose in life—but I suggested an alternative solution above in https://github.com/beetbox/beets/issues/435#issuecomment-292718100. Alternatively, if you think it would be easier to just add a simple change to library.py, we can of course discuss that too.

**Comment by SpirosChadoulos** [comment]
What do you mean by adding a flag to the move command?

**Comment by sampsyo** [comment]
I just mean adding one more command-line option, like these ones:
https://github.com/beetbox/beets/blob/master/beets/ui/commands.py#L1506-L1524

**Comment by SpirosChadoulos** [comment]
Something like: `move_cmd.parser.add_option(
    u'-e', u'--export', default=False, action='store_true',
    help=u'...'
)` ??  And then where do I write the main code of the feature??

**Comment by sampsyo** [comment]
Yep, like that! Then, you'll notice that the options get exposed in the `opts` argument to the command function, and then those values get passed to the `move_items` function. That last function is where the actual work will go.

**Comment by SpirosChadoulos** [comment]
What do you mean by exposed?

**Comment by sampsyo** [comment]
The values are available—for example, as `opts.pretend` and `opts.force` here: https://github.com/beetbox/beets/blob/master/beets/ui/commands.py#L1562

**Comment by SpirosChadoulos** [comment]
So the work that will happen in the `move_items` function should be in an if statement like `if export` ??

**Comment by sampsyo** [comment]
Yep, exactly!

**Comment by SpirosChadoulos** [comment]
Okay I will start the work and stay in touch for any further explanation. Thanks a lot!
