### ISSUE TITLE
Drop Python 3.6

### ISSUE THREAD

**Issue by wisp3rwind** [beetbox/beets#4372]
>> Thanks!
>> 
>> We do still support Python 3.6, don't we? I think we should keep testing it then.
>
> 3.6 has been dropped from support since Sept 2021
>
> https://peps.python.org/pep-0494/

_Originally posted by @arogl in https://github.com/beetbox/beets/issues/4092#issuecomment-1154750575_

-> We should drop Python 3.6 (unless there are any objections?). Beyond CI, this includes the docs in various places, `setup.py`, etc. This should also be mentioned in the next release announcement/the changelog.

**Comment by sampsyo** [comment]
No, no objections—this seems like the right thing to do! Thank you for getting started on this. I will look at the commits in #4374 in more detail in a moment.
