### ISSUE TITLE
Allow importing from logfile

### ISSUE THREAD

**Issue by Holzhaus** [beetbox/beets#4379]
When importing large collections, it makes sense to do the automated import first, then do the manual part afterwards:

    $ beet import -l skipped.log -q /path/to/library

It would be great if it was possible to continue the import using the logfile instead of a directory:

    $ beet import skipped.log

Beets should be able to parse the logfile and call import on each directory that was skipped.

**Comment by Holzhaus** [comment]
My current workaround:

```
$ grep -v "^import" missing.log | sed "s/^[a-z-]\+ //" | python <(cat << EOF
import sys
import os.path
for line in sys.stdin:
    print(os.path.commonpath(line.rstrip("\n").split("; ")))
EOF
) | xargs -d $'\n' beet import 
```

**Comment by antonellocaroli** [comment]
I use a sricpt sh for that:

```
date=$(date '+%Y%m%d' | cut -c 3-)

grep skip ~/.config/beets/import.log | sed 's/skip //' > ~/.config/beets/skipped_import.log

mv ~/.config/beets/import.log ~/.config/beets/import.log."$date"

manual_import() {
until [ ! -s ~/.config/beets/skipped_import.log ]
do
  chek=$(head -n 1 ~/.config/beets/skipped_import.log)
  beet import -CW "$chek" &&
  sed -i '1d' ~/.config/beets/skipped_import.log
done
}

manual_import
```

**Comment by wisp3rwind** [comment]
I'm pretty sure that a feature like this has been discussed before; but I can't find the issue right now.

**Comment by Holzhaus** [comment]
Well, it looks like the log file format is intended to be machine-readable, so it's not really far-fetched to assume that such a feature was considered at some point.
