### ISSUE TITLE
embyupdate: Allow direct configuration of user ID for private users

### ISSUE THREAD

**Issue by JoshDi** [beetbox/beets#4402]
In the embyupdate.py plugin, if the admin user listed in the beets config is hidden from login screens, the embyupdate plugin will fail and not find the username. 

I am using an API key, which is server wide so the username does not really matter. Therefore the get_user function should just return the user provided in the beets config

We should also allow for the emby user ID (string/hash) to be supplied directly from the beets config to avoid this situation. 

can this change be made please?

**Comment by sampsyo** [comment]
Sounds very reasonable! Any chance you could try putting together a PR to show how this would work?

**Comment by shoriminimoe** [comment]
I happened to encounter this recently. I'm happy to submit a PR for this.
