### ISSUE TITLE
Video tracks mess up release

### ISSUE THREAD

**Issue by dschrempf** [beetbox/beets#4439]
### Problem

When importing releases with video tracks, video tracks are ignored, even when
audio files are available, and the track numbers are messed up.

For example, [this
release](https://musicbrainz.org/release/90ee3dda-176e-4666-807f-db6602531961)
contains 200 tracks, two of which are video tracks (track numbers 114 and 135).
When importing the release (simple `beet import FOLDER`), the audio files of the
two corresponding video files are ignored ("unmatched"), and all tracks between
115 and 134 are mislabeled with numbers 114 to 133, and tracks from 136 to 200
are mislabeled with numbers 134 to 198.

### Setup

* OS: Linux (NixOS)
* Python version: 3.9
* beets version: latest (commit 6eec17c6610c06d21ef283cf84254669ef03c227)
* Turning off plugins made problem go away (yes/no): no

I am not sure if the configuration is of interest because it seems to be a
problem with the scraper. Of course, I can add `beet config` upon request.

**Comment by sampsyo** [comment]
Including your configuration would be great!

You might want to try the `ignore_video_tracks` config option:
https://beets.readthedocs.io/en/stable/reference/config.html#ignore-video-tracks

**Comment by dschrempf** [comment]
Thanks for your quick reply! I didn't know about the `ignore_video_tracks` setting. Indeed, it worked flawlessly!

I think it would be great to warn the user when video tracks are ignored but those tracks are present in the folder to be imported, instead of marking those files "unmatched".

Further, I suggest not shifting the track numbers when video tracks are ignored. (But maybe this has a reason I am not aware of).

Finally, and a little unrelated: On my path towards setting `ignore_video_tracks` to `no`, I accidentally set `import.ignore_video_tracks` to `no` (which is nonsense) and wondered why it didn't work. I think we could warn users when configuration settings are ignored. Of course this would require a separate ticket or PR. What do you think?

Thanks again for your reply!

**Comment by sampsyo** [comment]
It might be helpful to have a conversation about exactly what piece we'd like to carry forward… the warnings about ignored config options, for instance? That might deserve a fresh issue that describes a design for how to accomplish that (it seems nontrivial at first glance).

**Comment by sampsyo** [comment]
Right; we'd need a clever way to determine which fields are used (they are accessed lazily).
