### ISSUE TITLE
lyrics: "Tekst piosenki" inserted at the beginning of every lyrics

### ISSUE THREAD

**Issue by rombat** [beetbox/beets#4451]
### Problem
Every downloaded lyrics start with
```
Tekst piosenki:
```
and end with:
```
Dodaj interpretację do tego tekstu »
Historia edycji tekstu
```
This issue has already been mentioned [here](https://github.com/beetbox/beets/issues/4228), and is supposed to be fixed [here](https://github.com/beetbox/beets/pull/4229), but I've just installed beets today, and the problem is still here

Running this command in verbose (`-vv`) mode:

```sh
 beet -vv lyrics -p Broken wings
user configuration: C:\Users\tinbapakk\AppData\Roaming\beets\config.yaml
data directory: C:\Users\tinbapakk\AppData\Roaming\beets
plugin paths:
lyrics: Disabling google source: no API key configured.
ImageMagick version check failed: [WinError 2] Le fichier spécifié est introuvable
ImageMagick version check failed: Command 'convert --version' returned non-zero exit status 4.
artresizer: method is (1, (0,))
inline: adding item field disc_and_track
inline: adding item field is_flac
inline: adding album field format
Sending event: pluginload
library database: D:\Downloads\beets\musiclibrary.db
library directory: D:\Downloads\beets
Sending event: library_opened
lyrics: lyrics already present: 種ともこ - Broken Wings - Broken Wings
Tekst piosenki:
Baby, I don't understand
Why we can't just hold on
To each other's hands

[...]

Don't you think so too？

Let me hear, Let me hear, Let me hear
Dodaj interpretację do tego tekstu »

Historia edycji tekstu
```

Led to this problem:

```
(paste here)
```

### Setup

* OS:  Windows 11
* Turning off plugins made problem go away (yes/no): the issue is related to a plugin (lyrics)
```
beets version 1.6.0
Python version 3.10.6
plugins: bandcamp, convert, embedart, fetchart, ftintitle, inline, lyrics, zero
```
maybe the fix is not yet in this version ?

My configuration (output of `beet config`) is:
no configuration for lyrics plugin (thus the default settings)

**Comment by jackwilsdon** [comment]
#4229 isn't in 1.6.0 - you'll need to [run the latest source version](https://docs.beets.io/en/latest/faq.html#run-the-latest-source-version-of-beets) to use it.
