### ISSUE TITLE
Docs: "beets releases regularly (about every 6 weeks)". Reality: no new releases for 39 weeks (and counting)

### ISSUE THREAD

**Issue by vinyllionel** [beetbox/beets#4458]
### Problem
the docs for beets state "_Beets sees regular releases (about every six weeks or so)_", but the last release was 9 months ago in late november 2021. 39 weeks have passed since then. can we either start releasing more regularly or update the docs to reflect reality?

i know i can run the latest bleeding edge version, but that further increases the risk of hitting bugs/instability. i've already lost data to beets once, i'm not eager to see that happen again and would prefer to run "stable" releases rather than "bleeding edge" versions.

### Setup

* OS: Ubuntu 21.10
* Python version: Python 3.8
* beets version: 1.6.0
* Turning off plugins made problem go away (yes/no): 

My configuration (output of `beet config`) is: N/A

**Comment by sampsyo** [comment]
Yes, we missed our deadline. I'm working on getting us back on track; we should be able to get there soon.
