### ISSUE TITLE
Add Index_tracks option for MusicBrainz

### ISSUE THREAD

**Issue by Serene-Arc** [beetbox/beets#4486]
The Discogs plugin allows users, through the `index_tracks` option, to prepend the disc name to the name of tracks, which is useful for cases where albums have a large number of tracks split into themed discs or so on. This data also exists on MusicBrainz but there is no option to include this.

### Proposed solution

The solution is to add an `index_tracks` option to the MusicBrainz metadata module and integrate that information in the same way that the Discogs plugin does

#### Non-goals

Spreading this behaviour to any other metadata sources that have this information available but do not currently make use of it.

(I'm happy to attempt this one myself, seems pretty simple and quick)

**Comment by sampsyo** [comment]
Interesting! Just to check we're talking about the right data, we do fetch a field we call `disctitle`, which comes from the "title" of the medium in MusicBrainz:
https://github.com/beetbox/beets/blob/44a7cc74bfe673bcf960c5dc18716b38e33d5ad0/beets/autotag/mb.py#L330

Is there any chance this has the sub-album grouping data you're interested in? If so, maybe the thing is to use a "formatted modify" to put this data into the `title` field.

**Comment by Serene-Arc** [comment]
Ah! Excellent that the metadata includes it; do you think it'd be worth having an option like the Discogs plugin?

**Comment by sampsyo** [comment]
Well, perhaps—but is it as easy to accomplish as `beet modify title='$disctitle: $title'` or similar? If so, maybe we don't need a specialized feature.

**Comment by Serene-Arc** [comment]
Fair enough, I'll close the issue then.
