### ISSUE TITLE
Where is asciify_paths?

### ISSUE THREAD

**Issue by rsc3** [beetbox/beets#4523]
Sorry if I missed something in the documentation. I can't find the asciify_paths plugin.

```
** error loading plugin asciify_paths:
Traceback (most recent call last):
  File "/home/cox/miniconda3/lib/python3.9/site-packages/beets/plugins.py", line 268, in load_plugins
    namespace = __import__(modname, None, None)
ModuleNotFoundError: No module named 'beetsplug.asciify_paths'

```
My only problem is with this plugin, and I can't find it in your source tree. I don't understand why pip installs beets into my miniconda directory, but it seems to work fine.

**Comment by sampsyo** [comment]
It's not a plugin, in fact—it's a built-in configuration option:
https://beets.readthedocs.io/en/stable/reference/config.html#asciify-paths
