### ISSUE TITLE
 Sort and comment "replace"

### ISSUE THREAD

**Issue by RollingStar** [beetbox/beets#4538]
https://github.com/beetbox/beets/pull/4534

We don't currently comment anything in the default config. For more advanced users, occasional comments may be helpful. I think this is most true in the "replace" section, which otherwise requires an eagle eye and a memorization of Python regex escape rules + how regex works.

Comments should be sparing, analogous to code comments vs. code docs in other projects. In our actual docs I may toss a link to https://regexr.com/.

Is there a reason `\/` is separate line than other special chars?

**Comment by sampsyo** [comment]
Adding some comments there seems helpful, yes!

I think the only reason we made `\` and `/` separate is for legibility. (As far as I know.) But comments should help amplify that!
