### ISSUE TITLE
fromfilename: Fails to detect `<track> <title>` filename patterns

### ISSUE THREAD

**Issue by hsandt** [beetbox/beets#4561]
### Problem

Running this command in verbose (`-vv`) mode:

```sh
$ beet import path/to/unknown_music_tracks
path/to/unknown_music_tracks (5 items)
No matching release found for 5 tracks.
For help, see: https://beets.readthedocs.org/en/latest/faq.html#nomatch
[S]kip, Use as-is, as Tracks, Group albums, Enter search, enter Id, aBort?
$ u
```

to Use as-is, will led to this problem:

the track numbers are not recognized. For instance, if I run `beet ls`:

```
$ beet ls
 -  - 01 深き森にて
 -  - 02 緋龍の翼
 -  - 03 風の国ルイヴェスタ
 -  - 04 終りなき狂詩曲
 -  - 05 無慈悲な夜に
```

the track numbers are still part of the files.

If I disable fromfilename plugin, the whole output is empty (no track number nor track name).

Here's a link to the music files that trigger the bug (if relevant):

Use any unknown track, such as a dummy sound file you would create, or rename the folder/files so artist/track cannot be identified (this is however a real use case; I'm simply downloading lesser known tracks from indie bands, etc.)

### Setup

* OS: Ubuntu 20.04
* Python version: 3.8.10
* beets version: 1.6.0
* Turning off plugins made problem go away (yes/no): no

My configuration (output of `beet config`) is:

```yaml
directory: ~/path/to/Music
import:
    copy: no
    write: no
plugins: fromfilename
```

Note: write: yes didn't help. In fact, it didn't even seem to change the track names, but that's another issue. I assume `beet ls` alone should show expected information.

**Comment by sampsyo** [comment]
Can you please include the filenames you're importing? The `fromfilename` plugin relies on very specific patterns in the names to detect various fields.

**Comment by hsandt** [comment]
Folder: 風の国ルイヴェスタ
File names:
01 深き森にて.ogg
02 緋龍の翼.ogg
03 風の国ルイヴェスタ.ogg
04 終りなき狂詩曲.ogg
05 無慈悲な夜に.ogg

(more exactly, I tried both with underscore "01_[name].ogg" which was the original name, and space "01 [name].ogg")

**Comment by wisp3rwind** [comment]
Interestingly, that ordering has been in place for a really long time by now: https://github.com/beetbox/beets/pull/399/files

**Comment by hsandt** [comment]
> If you have a moment, any chance you could give this a try with those two lines swapped?

Yes, it works with "<track>[\s.-_]<title>" before "<title>". I also noticed the underscore is recognized as valid separator in this pattern, so I tried again with the original file names, and it works (I had to use a custom format to display the track numbers):

In the folder containing the tracks:

```sh
$ beet import .

path/to/unknown_music_tracks (5 items)
No matching release found for 5 tracks.
For help, see: https://beets.readthedocs.org/en/latest/faq.html#nomatch
[S]kip, Use as-is, as Tracks, Group albums, Enter search, enter Id, aBort? u
$ beet ls
 -  - 深き森にて
 -  - 緋龍の翼
 -  - 風の国ルイヴェスタ
 -  - 終りなき狂詩曲
 -  - 無慈悲な夜に
$ beet ls -f '$album - $artist - $track : $title'
 -  - 01 : 深き森にて
 -  - 02 : 緋龍の翼
 -  - 03 : 風の国ルイヴェスタ
 -  - 04 : 終りなき狂詩曲
 -  - 05 : 無慈悲な夜に
```

So with this, I just need to learn how to apply beet library metadata back to the actual track files, and I should be able to update my music tags very fast!

I'll let you have a look whether there are other lines to reorder while we're at it though, and if the reordering won't have bad side effects we didn't think of (isn't there a list of unit tests with dummy track names to test on?)

**Comment by sampsyo** [comment]
Indeed; I can't think of any bad side effects—we should probably just do the reordering!

**Comment by JOJ0** [comment]
Another idea I'm using for quite a few months now is additional info logging within the plugin: https://github.com/beetbox/beets/commit/339aed25cc3599773ce2edce2b57bda0f765aa49

It helps to see what fromfilename is actually doing. Right now it is a blackbox that tries to do good but sometimes even worsens and confuses the search terms. At least with better logging, the user would know that with messed up tags/filenaming there is  no chance that beets will find anything anywhere. Let's take an example that occurs to me often. This file has not tags at all and the artistnames starts with digits:

```
   dev  (beets)    ~/git/beets  ➦ 73f8b6f6  beet import ~/Sync/beets_test_music/bad_tag/60\ minute\ man\ -\ together.mp3
fromfilename: Artist replaced with: 60 minute man 
fromfilename: Bad title replaced with:  together
fromfilename: Track replaced with: 60

/home/jojo/Sync/beets_test_music/bad_tag/60 minute man - together.mp3 (1 items)
Finding tags for album "60 minute man  - ".
Candidates:
1. The Black Eagles - Brimstone And Fire / 60 Minutes Man (23.8%) (album, artist, tracks, ...) (Discogs, Vinyl, UK, Ethnic, ETH 38)
2. The Untouchables - 60 Minute Man / Everybody's Laughing (23.0%) (album, artist, tracks, ...) (Discogs, Vinyl, 1960, US, Madison Records, M 139)
3. The Black Eagles - Brimstone & Fire / 60 Minutes Man (22.6%) (album, artist, tracks, ...) (Discogs, Vinyl, 1974, US, Black Eagle, RK-3)
4. The Trammps - 60 Minute Man (21.8%) (album, artist, tracks, ...) (Discogs, Vinyl, 1976, Netherlands, Buddah Records, BDA - 321)
5. Missy Elliott Featuring Ludacris - One Minute Man (20.3%) (album, missing tracks, artist, ...) (Discogs, Vinyl, 2001, Europe, Elektra, 7559-67244-0)
# selection (default 1), Skip, Use as-is, as Tracks, Group albums,
Enter search, enter Id, aBort, eDit, edit Candidates? 
```

**Comment by JOJ0** [comment]
I'm sorry I don't know really where I'm going with this but maybe somewhere around here it could be distinguished that in such a case we shouldn't take the track name as real: https://github.com/beetbox/beets/blob/master/beetsplug/fromfilename.py#L102-L126

Or maybe all the regexes could be more explicitly written to better find out that we have an artist name starting with a digit and it's not the track number.

Not sure, but let's leave my proposal as: What do you think about the logging improvement suggestion?

**Comment by wisp3rwind** [comment]
I doubt there's a real solution to the "60 minute man" example within the simple design that this feature currently has: There's no way to distinguish being part of the artist name or the track number, since the plugin only really looks at tracks in isolation.

About the logging, I personally wouldn't like this as-is due to interrupting the regular importer UI, as you already note. Maybe let's get this in as debug logs, such that at least this information is available if requested (which already improves upon the current state). Displaying warnings/etc during the import flow is a feature where it'd be really nice to come up with a generic solution (maybe delaying messages until a good point, maybe some terminal control trickery to move them above the current prompt, ...?). I'm not fond of the idea to introduce a configuration option; we already have enough of them to control the actual behavior of beets, let alone to fine-tune logging.

**Comment by JOJ0** [comment]
Thanks for taking the time to think about all this!

Looking through these regex patterns again and again I came to a similar thought that it seems not really solveable for artist names starting with digits. I also realised that it's not such of a big deal. Most importantly artist and title are detected correctly, even with the example file from above.
