### ISSUE TITLE
Feat: Use spotify as Album / Song reference

### ISSUE THREAD

**Issue by Emporea** [beetbox/beets#4572]
I am looking for the possibility to use a spotify playlist url as reference to choose the right album release and so on, additionally to Musicbrainz etc .

**Comment by arsaboo** [comment]
You can use Spotify as a tag source. Just configure the Spotify plugin, and it will be automatically used as a tag source. You can also manually specify the album after selecting the `i` option during the tagging process and entering the album URL.

**Comment by Emporea** [comment]
So its only possible manually?
I am searching for away to import a library using beets and by providing a spotify playlist containing all of the songs.
Then it should be possible to automatically tag those songs that match?

**Comment by JOJ0** [comment]
I am not sure if I understand how a **single** Spotify playlist would help to match to **several** albums. Maybe you try to elaborate how a feature like this would work. 

Tagging a rather messy library, which means with missing tags and albums not in sorted in folders already means a lot of manual work. beets can help but fully automatic is not possible in that case.

Have you tried the `fromfilename` plugin (helps finding artist and title if those metadata tags are missing entirely from the files), 

You'll find how to set it up in the plugins section of https://beets.readthedocs.io

Have you tried this option for the `import` command?

```
-g, --group-albums    group tracks in a folder into separate albums


```

HTH

**Comment by Emporea** [comment]
I am not sure how to explain it better.

I have songs on my hard drive ~3000.
Some of them are part of an album, some are singles etc.

I already tried using MusicBrainz Picard and Lidarr.
~2500 have been recognized, but often Picard or Lidarr chose the wrong album, which sometimes results in having several Album Folders and my offline songs are distributed among them.

~500 havent been recognized, sometimes because there simply is no entry on MusicBrainz.


Tagging all of them invidivually is a huuuge work. I thought to myself that there must be a solution.
So what I did, was try to find the correct album on Spotify to every song I have on my drive.

I did, and now I have a big playlist on spotify ~3000 individual songs. 

So in theory it should be possible to give beets the URL of this spotify playlist, and beets will automatically go through everysong I have on my drive + on spotify playlist and tagg my songs on my drive according to the match in the playlist.

Am I thinking too complicated?

**Comment by JOJ0** [comment]
Probably the time u spent for finding on spotify could have been invested better. Sorry to say and no offence! You couldnt know.

Try using spotify as a tagging source as arsaboo suggested!

Have you tried the -g option yet?

But I think your main problem is your badly tagged files. Have you checked some of them with eg mediainfo tool? Whats the situation?

**Comment by JOJ0** [comment]
And no: There is no existing plugin that works by working through a list of spotify tracks and uses them as a helper/reference. Even if there would be one: How should it match spotify track to a badly tagged file with a broken tag. no artist? no title? no match possible :-))

**Comment by JOJ0** [comment]
one possible solution: use only chroma plugin and nothing else!!

**Comment by Emporea** [comment]
Are these tags not sufficent? This is one of the 500 tracks that have no matches.
![image](https://user-images.githubusercontent.com/21969523/205912449-444db326-f610-4910-8946-d590669a700e.png)

**Comment by JOJ0** [comment]
> I already tried using MusicBrainz Picard and Lidarr.

Maybe a backup of prior to any of this would be a good starting point.

> ~2500 have been recognized, but often Picard or Lidarr chose the wrong album, which sometimes results in having several Album Folders and my offline songs are distributed among them.

This manual work can help a lot in that situation: Move files from those several album folders all into one folder! This is the main sign for beets that it's looking at an album. Usually also if files are differentl

**Comment by JOJ0** [comment]
> Are these tags not sufficent? This is one of the 500 tracks that have no matches. ![image](https://user-images.githubusercontent.com/21969523/205912449-444db326-f610-4910-8946-d590669a700e.png)

Those tags look good. Are you really sure that your tagging source has that album? What are u using? Which source plugins? 

On Discogs I found the release: https://www.discogs.com/release/14460272-Johannes-Brahms-Amadeus-Quartett-Christoph-Eschenbach-Klavierquintett-F-moll-Op-34-

Check if it is on MusicBrainz, if this is the only source you are using! And again: From my personal experiene: Ther is no source on the internet that has everything. At least that's the experience I have with my rather diverse music collection!

**Comment by JOJ0** [comment]
Welcome! Try looking up what I describe in this post in the reference docs: https://github.com/beetbox/beets/issues/4572#issuecomment-1338882195

Post your config here and I'll take a look then!

Docs:https://beets.readthedocs.io/en/latest/plugins/index.html#using-metadata-source-plugins

**Comment by arsaboo** [comment]
@Emporea Please note that beets treats each album separately, and there is no way (at least to my knowledge) of providing a bunch of links to match. You will have to tag each album. 

If you are willing to spend some time pre-processing the data, you may be able to use `--search-id` option https://beets.readthedocs.io/en/v1.6.0/reference/cli.html#import

**Comment by JOJ0** [comment]
@Emporea did you try out the suggestions in this thread? Can this issue be closed? Hope something helped! :-)

**Comment by Emporea** [comment]
Well it helped a little bit because it made me realize i have to tag everything manually. Still need to do it tho. 3000 songs doesnt tag themself appereantly ;).
Issue can be closes tho. Thank y'all for the help.

**Comment by JOJ0** [comment]
You can do it! Good luck! I still have thousands in front of me as well. Dont forget to use additional metadata plugins. For my music collection often MusicBrainz doesnt have it in the database. I recommend discogs and spotify plugins and possibly even beatport4 if you have a lot of electronic music.

**Comment by Emporea** [comment]
I have another question. Does beets also consider the filenames everytime?
Is there a way to make beets only consider the exifdata?

**Comment by JOJ0** [comment]
> I have another question. Does beets also consider the filenames everytime?

No. Under 2 conditions: artist and title id3/metadata tags missing AND the fromfilename plugin is enabled.

> Is there a way to make beets only consider the exifdata?

no exifdata in audiofiles. what do you mean?

> 
> For example can I tell beets to cluster files into folder only considering album and artist when deciding in which folder something to put?

You can configure how beets saves the imported files. Read about the path configurations: https://beets.readthedocs.io/en/stable/reference/config.html#path-format-configuration

**Comment by Emporea** [comment]
How can I only use spotify to recognize song?

This is my config.yaml. It still uses musicbrainz even tho i disabled it?

```
plugins: spotify

spotify:
    source_weight: 1

musicbrainz:
    enabled: no
    source_weight: 0
```

Since I have all files in a single folder i use this command to import.
`beet import -s -m .`


Also yes, I made a backup of my unmodified files and I am trying out several options without changing my real data.

**Comment by JOJ0** [comment]
Your beets version supports musicbrainz disabling already? Think it's not in a released version, only in current dev. Not sure need to check.

**Comment by Emporea** [comment]
Well this could explain why its not working :D. I am using 1.6.0.
Merry Christmas btw.

**Comment by JOJ0** [comment]
> But When I use spotify the "similarity" is down to 80% for every song it finds, even tho it is the correct one.

The importer UI tells you why you get penalties for the candidates. Usually in orange color, text in brackets.

Post an example of such an 80% match!

**Comment by JOJ0** [comment]
> Well this could explain why its not disabled :D. I am using 1.6.0.
> 
> Merry Christmas btw.

Run it from git. You wont regret it, dev version is perfectly stable usually.

git clone via http or ssh
cd beets
pip install -e .

**Comment by Emporea** [comment]
I already tried the dev version. Still matches using musicbrainz.

**Comment by Emporea** [comment]
```
/home/empo/SpotifySingle/!llflow - Ich & mein Rucksack.ogg
Tagging track: !llflow - Ich & mein Rucksack
URL:
    https://open.spotify.com/track/5dPTHCbl7A9flc15j61hLz
(Similarity: 80.0%) (source) (Spotify)
[A]pply, More candidates, Skip, Use as-is, Enter search, enter Id, aBort? 

/home/empo/SpotifySingle/!llflow - Länger als jeder Hype.ogg
Tagging track: !llflow, Lakmann - Länger als jeder Hype
URL:
    https://open.spotify.com/track/779m2dPTPVe8WAG7mEde9X
(Similarity: 80.0%) (source) (Spotify)
[A]pply, More candidates, Skip, Use as-is, Enter search, enter Id, aBort? 

/home/empo/SpotifySingle/10cc - Bloody Tourists - 01 - Dreadlock Holiday.ogg
Tagging track: 10cc - Dreadlock Holiday
URL:
    https://musicbrainz.org/recording/f096fef1-0d0f-41e9-98fc-be4a29e97d09
(Similarity: 100.0%)

/home/empo/SpotifySingle/10cc - Bloody Tourists - 04 - Shock on the Tube (Don’t Want Love).ogg
Tagging track: 10cc - Shock on the Tube (Don’t Want Love)
URL:
    https://musicbrainz.org/recording/8e1a0dab-0a82-4b93-b87c-128268d3ef7f
(Similarity: 100.0%)

/home/empo/SpotifySingle/10cc - I'm Not In Love.ogg
Correcting track tags from:
    10cc - I'm Not In Love
To:
    10cc - Not in Love
URL:
    https://musicbrainz.org/recording/f2a15e1f-75dd-490e-8a87-639deb919980
(Similarity: 89.1%) (title)
[A]pply, More candidates, Skip, Use as-is, Enter search, enter Id, aBort? 

/home/empo/SpotifySingle/2080 - Toco Toco.ogg
Correcting track tags from:
    2080 - Toco Toco
To:
    2080 - Toco Toco (extended mix)
URL:
    https://musicbrainz.org/recording/396a517a-5d83-4e2b-a454-54e37bd2826c
(Similarity: 92.6%) (title)
[A]pply, More candidates, Skip, Use as-is, Enter search, enter Id, aBort? 
(Similarity: 100.0%)

/home/empo/SpotifySingle/3 Sud Est - Focul.ogg
Tagging track: 3 Sud Est - Focul
URL:
    https://open.spotify.com/track/7vm8gelkQdI1uDWzWmBXBK
(Similarity: 80.0%) (source) (Spotify)
[A]pply, More candidates, Skip, Use as-is, Enter search, enter Id, aBort? 

/home/empo/SpotifySingle/36 - Black Soma - 01 - Black Soma.ogg
Tagging track: 36 - Black Soma
URL:
    https://musicbrainz.org/recording/f1ac8aa9-825d-487e-93f9-ef078766dc81
(Similarity: 100.0%)

/home/empo/SpotifySingle/36 - Black Soma - 03 - Black Halcyon.ogg
Tagging track: 36 - Black Halcyon
URL:
    https://musicbrainz.org/recording/6135a0d7-fe51-4369-b27e-f5182fbb2c07
(Similarity: 100.0%)

/home/empo/SpotifySingle/47stillstanding - So Fucked Up.ogg
Tagging track: 47stillstanding, R I S K L I F E - So Fucked Up
URL:
    https://open.spotify.com/track/4QlsZUlfUyoQDUXaDnQKsM
(Similarity: 80.0%) (source) (Spotify)
[A]pply, More candidates, Skip, Use as-is, Enter search, enter Id, aBort?
```

This is my output with this command `beet import -s -m SpotifySingle/` using this config:

```
plugins: spotify
spotify:
    source_weight: 1
    mode: list
    tiebreak: popularity
    show_failures: no
    artist_field: albumartist
    album_field: album
    track_field: title
    region_filter:
    regex: []
    client_id: xxx
    client_secret: REDACTED
    tokenfile: spotify_token.json

musicbrainz:
    enabled: no
    source_weight: 0
    detail: yes
```

As you can see, Spotify matches get tagged with 80% everytime.

**Comment by JOJ0** [comment]
Not sure but have you tried without --singleton
I prefer never to use it and it's ather match albums

**Comment by Emporea** [comment]
Well it seems like musicbrainz is only turned off for non-singleton.

**Comment by JOJ0** [comment]
Exactly, use -g

**Comment by Emporea** [comment]
Yes I tried -g already, forgot to mention. It still uses musicbrainz if the similarity is higher, which is the case for a lot of my tracks if spotify keeps dangling around at 80% (even much lower when I only have single files of a whole album when -g and not -s)

Opened a new issue:
https://github.com/beetbox/beets/issues/4605

If I can disable spotify completly I should be able to lower the minimum similarity (rec_strong_thresh) without getting wrong matches from musicbrainz.

**Comment by Emporea** [comment]
found a workaround to only use spotify.
I just ignore any other media:
`ignored_media: ['CD-R', 'CD', '12" Vinyl', 'Data CD', 'DVD', 'DVD-Video', 'Blu-ray', 'HD-DVD', 'VCD', 'SVCD', 'UMD', 'VHS', '7" Vinyl', 'Digital Media']` ( probably more coming)
