### ISSUE TITLE
DSD/DSF file format support

### ISSUE THREAD

**Issue by sampsyo** [beetbox/beets#459]
DSF files apparently use ID3 metadata. Here's a project that adds support for them to Mutagen: https://code.google.com/p/dsf2flac/source/browse/trunk/extras/picard+dsf+file+support/dsf/dsf.py

**Comment by storris** [comment]
I extracted and tagged my SACD ISO library in Windows using Korg Audiogate.  The resulting .dsf files are pop-free, and tagged using MP3Tag.  There is an option to select extract to .dsf or .dff, the difference being that dff (the Philips format) supports 5.1 (possibly others) while .dsf is only stereo.

Audiogate is proprietary software, and needs prop. hardware purchase to activate and use, but an older version (the one I have which IRC is v2.1) has been cracked and is available around the web.

I dual-boot to Linux and have mpd/GMPC which deals with .dsf perfectly, but it currently only reads .dsf filenames, not their tags.

**Comment by docbobo** [comment]
It seems that DSF is still not supported. At least that's what my last test suggested. Any updates on the current plans? Anything I can help with?

**Comment by sampsyo** [comment]
Yeah, some help would be awesome if you're interested! The most helpful thing you can do is take ownership of adding DSF format support to [Mutagen](https://github.com/quodlibet/mutagen). That would involve doing the research to find out how exactly ID3 tags are stored on those files and contributing a module to that project.

**Comment by KingDuckZ** [comment]
Sorry for the necro, just wondering if dff format is also going to work at some point, or what's the outcome of the discussion here? I see dff being discussed but I don't quite get if it should work with beets or not (from a practical test it looks like it doesn't).

**Comment by emiham** [comment]
@KingDuckZ It should be possible, and probably not too hard to add. There is DFF support in Mutagen, so I don't see why it couldn't be added to beets. 

Start by opening a new issue and I can look into it and get some feedback.
