### ISSUE TITLE
Config Keyword Ambiguities: Yes and True

### ISSUE THREAD

**Issue by J4gQBqqR** [beetbox/beets#4590]
### Proposed solution

Use only true/false or yes/no pair for the config file and the documentation.

### Objective

Make the config file syntax clear. The current config file is confusing as some places recommends yes, other places recommends true.

#### Goals

Choose either true/false or yes/no as a standard way of writing the config file.
Rewrite the documentation to reflect this standard.

#### Non-goals

Support both true/false and yes/no in all places across the config file.

#### Anti-goals

Mix usage of yes/true, no/false in the documentation in its current format is very confusing.

**Comment by sampsyo** [comment]
Hello! This is a consequence of [YAML](https://yaml.org) syntax, which treats `true` and `yes` as synonyms. I don't think we want to be in the business of straying from the YAML standard on this point—although sure, fixing the docs to be consistent could be cool!
