### ISSUE TITLE
Test failures, presumably due to mediafile changes for non-existing list fields

### ISSUE THREAD

**Issue by wisp3rwind** [beetbox/beets#4592]
Our CI has started to fail, for example in https://github.com/beetbox/beets/actions/runs/3708150668/jobs/6285601538

I guess this is https://github.com/beetbox/mediafile/pull/64; @sampsyo @jtpavlock any pointers on where a fix on beets's side would need to start?

**Comment by jtpavlock** [comment]
To me it looks like these tests were built around the assumption accessing a list field would return an empty list even if the field did not exist, e.g. `self.assertEqual(len(mediafile.images), 0)`. 

If checking to see if a field does not exist, I would change the checks to use `assertIsNone()` instead.

**Comment by wisp3rwind** [comment]
Yep, so you're saying this most likely just an issue with the tests only, not beets itself? I'll go ahead and adapt the tests, and see where it gets us :)

**Comment by wisp3rwind** [comment]
> If checking to see if a field does not exist, I would change the checks to use assertIsNone() instead.

In fact, some of the tests already used `assertFalse`: That has the advantage to work with all versions of mediafile.
