### ISSUE TITLE
Cannot use the media album value with the inline plugin

### ISSUE THREAD

**Issue by swills1** [beetbox/beets#4609]
https://beets.readthedocs.io/en/latest/reference/pathformat.html

I use the media value in my path format to label the type of media - CD, Digital Media, etc. `$media` works fine in the path, but when you try to use it with inline you get;

```
beetsplug.inline.InlineError: error in inline path field code:
return media

NameError: name 'media' is not defined
```
I tested in the simplest form by doing,

```
album_fields:
    reissue: |
        if (year > original_year):
            re = f'[RE-{year}]'
            return re
    catalog_nospace: |
        return catalognum.replace(" ", "")
    media_cust: |
        return media
```

### Setup

* OS: Fedora 37
* Python version: 3.11
* beets version: 1.6.0
* Turning off plugins made problem go away (yes/no): 

My configuration (output of `beet config`) is:

```
album_fields:
    reissue: |
        if (year > original_year):
            re = f'[RE-{year}]'
            return re
    catalog_nospace: |
        return catalognum.replace(" ", "")
    media_cust: |
        return media
```

**Comment by wisp3rwind** [comment]
From a cursory glance at the code, it appears that `media` is only set an tracks, not albums, so you would need to define `media_cust` within the `item_fields` section.

**Comment by swills1** [comment]
``> item_fields

Thanks, I'm big dumb. This works. 
`item_fields:
    media_cust: |
        if ('Digital' in media):
            return 'Digital'`

Please close and thanks again.
