### ISSUE TITLE
discogs: Fetch a few more metadata fields

### ISSUE THREAD

**Issue by downinthings** [beetbox/beets#465]
Hey Guys,

I've recently begun using the Discogs plugin for beets. I am wondering if the information obtained by the plugin could be extended? I am looking to get the following information for each release I tag:

Discogs URL
Release Date (YYYY-MM-DD)
Genre
Style
Country

I tried playing with the plugin to get this information, but I am not well-versed in python.

Having the ability to specify what tag fields this information is applied to would also be amazing.

Thanks guys!

**Comment by simonbcn** [comment]
Last.fm is useful for obtain genres with popular artist/albums. In other case, it's useless.
For example: https://www.discogs.com/es/S%C3%ADlvia-Comes-L%C3%ADdia-Pujol-Al-Entierro-De-Una-Hoja-Seca-Van-Dos-Caracoles/release/3705782 and http://www.last.fm/es/music/S%C3%ADlvia+Comes+&+L%C3%ADdia+Pujol/Al+Entierro+de+una+Hoja+Seca+Van+Dos+Caracoles
There is the album in Last.fm but without genres.

**Comment by SpaceAgeHero** [comment]
It would be good to fetch Discogs Release ID as well. It could be useful in case an "update tags" feature is planned.

**Comment by dbogdanov** [comment]
+1 on the idea to store Release ID. These identifiers are stable, so they are definitely worth storing, just like MBIDs.

**Comment by thedevilisinthedetails** [comment]
Is this still something that is pending development? Would love to also have the styles from discogs.

**Comment by dbogdanov** [comment]
I guess it is, but someone needs to help and add this functionality. Also, Discogs now provides composition identifiers that would be nice to add too, for example https://www.discogs.com/composition/0ad990be-3414-479f-8c9b-73ed43619781-The-Nine

**Comment by thedevilisinthedetails** [comment]
K, started looking into this and started some development. As I am new to python it may take some time.

**Comment by thedevilisinthedetails** [comment]
Will start working on this  to retrieve and store additional discogs values for the attributes listed above.
