### ISSUE TITLE
python-musicbrainzngs gets no update

### ISSUE THREAD

**Issue by Louson** [beetbox/beets#4651]
### Problem

The musicbrainz python interface https://github.com/alastair/python-musicbrainzngs has received no update for a year, neither it has received answers for pull requests and issues.

**Comment by sampsyo** [comment]
That's definitely true, and its stagnation impeded some features we would like to ship in beets. I would very much welcome the idea of spinning up a new library, which could be a _lot_ simpler by relaying on MB's JSON API (the existing library started when the only output format was XML, which lead to a lot of parsing code that could now be deleted). But beyond this, I don't think there's an issue to track within beets itself. (Please feel free to get the discussion going under Discussions about how to tackle the problem of creating a new, replacement library if you like!)
