### ISSUE TITLE
Removing a flexible field from an album doesn't remove corresponding field from its items

### ISSUE THREAD

**Issue by katedickey** [beetbox/beets#4662]
### Problem

When importing an album with the `--set` flag, beets imports the album with "flex1" set on both the album and each of its tracks:

```sh
$ beet import <path> --set flex1=something
```

Later, when deleting the flex field with `-a`, the value is updated on the album, but is still set on the items:

```sh
$ beet modify -a "Some album" flex1!
```

After modifying, search for matching tracks, and they still return

```sh
$ beet ls flex1::something
```
```
Some artist - Some album - Track name 1
Some artist - Some album - Track name 2
...
```

Search for matching albums, returns nothing

```sh
$ beet ls -a flex1::something
```
```sh
# no results
```

### Setup

* OS: Arch
* Python version: 3.10.9
* beets version: 1.6.1
* Turning off plugins made problem go away (yes/no): no

My configuration (output of `beet config`) is:

```
(tested with default settings)
```

### Extra info

Also of note, this issue naturally doesn't come up if the flex field was added to just the album after import using `beet mod -a flex1=something` which is how I configured a lot of my library, so this issue only happens to albums imported with `import --set`

**Comment by JOJ0** [comment]
Hi @katedickey, this issue bit me quite often in the past. Just want to say "THANKS" :-) :tada: :rocket:
