### ISSUE TITLE
Running import on a folder containing .ZIP files doesn't work

### ISSUE THREAD

**Issue by neilbaldwin** [beetbox/beets#4670]
I can import a single .ZIP file with:

`beet import some_music.zip`

and if a folder contains several .ZIP files I can do:

`beet import *.zip`

and that works also as expected.

However if I run import on the folder that contains the .ZIP files:

`beet  import .`

then nothing is imported.

**Comment by sampsyo** [comment]
Indeed; this is indeed the way it works. You can consider something like `find -iname '*.zip' | xargs beet import` or something roughly along those lines to import the zip files themselves.

**Comment by neilbaldwin** [comment]
Ah, sorry about that Adrian.

Could probably do with a note in the documentation about it. Searching for 'zip' on ReadTheDocs only turns up a one-liner saying '.zip files are supported out of the box' which was what lead me to believe I was either doing something wrong or something wasn't worked as expected.

**Comment by RollingStar** [comment]
I just ran into this. I think we can log and document this better.
