### ISSUE TITLE
AcousticBrainz is shutting down the project

### ISSUE THREAD

**Issue by doronbehar** [beetbox/beets#4688]
This is not a bug really, nor a feature request. Just wanted to let you know that AcousticBrainz is shutting down the project:

https://blog.metabrainz.org/2022/02/16/acousticbrainz-making-a-hard-decision-to-end-the-project/

The API so it seems is supposed to be still somewhat functional, but at least `absubmit` plugin is not functional anymore.

I was wondering whether beets should still maintain the `chroma` and `acousticbrainz` plugins, as they will likely continue to work for a longer time, although their dependencies are hardly maintained.

**Comment by jackwilsdon** [comment]
#4636 was merged recently to deprecate the `absubmit` and `acousticbrainz` plugins. I don't think this affects the chroma plugin at all, as Acoustid isn't shutting down.

**Comment by doronbehar** [comment]
Thanks for the quick reply! Sorry for the noise, I should have looked this up..
