### ISSUE TITLE
website possible typo

### ISSUE THREAD

**Issue by simonmcnair** [beetbox/beets#4695]
https://beets.readthedocs.io/en/stable/plugins/albumtypes.html

should there be a space after the full colon ?

Just trying to help.

Cheers

![image](https://user-images.githubusercontent.com/101189766/223745648-3a5fe84f-2ec1-4c6f-b3d6-5c0299dca571.png)

**Comment by sampsyo** [comment]
Aha; actually, there is a mission colon (not a missing space). It should look like this:

```
albumtype:soundtrack: Various Artists/$album [$year]$atypes/...
```

Any chance you could open a very quick PR to add that?

**Comment by simonmcnair** [comment]
> Aha; actually, there is a mission colon (not a missing space). It should look like this:
> 
> ```
> albumtype:soundtrack: Various Artists/$album [$year]$atypes/...
> ```
> 
> Any chance you could open a very quick PR to add that?

My bad.  It was done ages ago but the site doesn't seem to be up to date ?
https://github.com/beetbox/beets/commit/f5d79676464e7e10e1b5f9e3cacf2e8f0f90a13c

**Comment by jackwilsdon** [comment]
The latest documentation site looks to be up to date: https://beets.readthedocs.io/en/latest/plugins/albumtypes.html

/stable/ refers to the current release, which is from before that change was merged.
