### ISSUE TITLE
discogs: Save album information on singleton imports

### ISSUE THREAD

**Issue by JOJ0** [beetbox/beets#4716]
When the discogs plugin is used for singleton imports consider additionally saving album information to the beets library.

### Proposed solution

On singleton imports the user specifically selects a Discogs release (Discogs release URL) where the track information should be taken from. This could be saved to the library field `album` of the track item (`album` row in the `items` table in the database) and to the corresponding metadata tag of the file.

Let's also compare this feature idea to a singleton import against the MusicBrainz database: Here we have a distinction between an album and a recording. A recording / a track is its own entity and does have a 1:n connection to an album, thus by selecting a recording on a singleton import, we don't know which album we are referring to! A feature like that would not make sense with MusicBrainz. With Discogs on the other hand, we have a 1:1 connection from a track to an album.

#### Goals

Save to the track item's `album` field (`items` table, `album` column). Provide an easy way for subsequent re-tagging of such singletons to albums, by having the required album info already.

#### Non-goals

Adding `album` and `album_id` to the `album` table in the database.

**Comment by JOJ0** [comment]
@ghbrown I'm not sure if this is easily possible. I just had a quick look into the code and see that item_candidates() returns a list of `TrackInfo` objects. The definition of a TrackInfo object here https://github.com/beetbox/beets/blob/master/beets/autotag/hooks.py#L171, does not intend to store the title of an album.

**Comment by JOJ0** [comment]
@arsaboo please help me out: IIRC I came across the fact that the Spotify plugin saves album information when it does singleton imports. Is that correct or did I dream that?

**Comment by JOJ0** [comment]
> @ghbrown I'm not sure if this is easily possible. I just had a quick look into the code and see that item_candidates() returns a list of `TrackInfo` objects. The definition of a TrackInfo object here https://github.com/beetbox/beets/blob/master/beets/autotag/hooks.py#L171, does not intend to store the title of an album.

Whoops, right an hour after I wrote this it came to mind that actually the solution to this problem is provided in the closed PR you based your recent item_candidates PR from: https://github.com/beetbox/beets/pull/3682

**Comment by JOJ0** [comment]
@ghbrown I couldn't wait and resurrected the code I found in #3682, heavily work in progress.

**Comment by JOJ0** [comment]
Also @ghbrown, I guess I'm interfering with issue #4703 now. If you would rather prefer to tackle that issue separately first that's totally fine. If you already started working on it or rather want to do that, I can wait with this new feature PR and later even try to  integrate your optimizations into it.

It's just that I desperately needed this feature and will use it for my endless tagging efforts. It just helps so much to finally be able to have album information available when retagging singletons to albums. That is one the one feature in beets I was missing for such a long time....

**Comment by ghbrown** [comment]
No problem, @JOJ0, please go ahead and finish this effort first. I think that is the more optimal order anyway.

As for `string_dist`, I think that firmly falls into the category of the fix for #4703 (whatever it will be).
