### ISSUE TITLE
Re-imports don't update `data_source` flex attr

### ISSUE THREAD

**Issue by JOJ0** [beetbox/beets#4726]
### Problem

When importing an album or a singleton that was previously imported already, the `data_source` flexible attribute is not updated. It stays as **initially imported**.

### Setup

* OS: ---
* Python version: ---
* beets version: 1.6.1 dev-latest
* Turning off plugins made problem go away (yes/no): no

### Proposed solution 

`data_source` needs to be excluded in `reimport_metadata()`

**Comment by arsaboo** [comment]
Even album re-import does not update `data_source`.

**Comment by JOJ0** [comment]
> 

Thanks for testing and clarifying. I was actually assuming that this is also the case but I wasn't sure yet. So, many thanks, that is very helpful! :-)

I'm pretty sure the problem is located here:

https://github.com/beetbox/beets/blob/4194914e94077f673cf920d595580696b4485305/beets/importer.py#L810-L812

On a reimport this function looks up what `data_source` is in the library already and then simply re-applies it. Similar to the ID fields over at PR #4708, `data_source` would need to be excluded from this "preserving mechanism".


We should investigate older issues and the one that implemented the `reimport_metadata()` method and make sure this is not "intentional" behaviour. If it was, I could think about making it configurable. As I see it now though, it feels like a bug, data_source is an informational field and after a reimport it is just wrong. I _do_ use this field sometimes to save that "I tagged this manuall" with `beet mod data_source=MANUAL query`, but also then _if_ I do find an appropriate album in some metadata source, it makes sense that this field gets overwritten and tells the truth.
