### ISSUE TITLE
Extending REIMPORT_FRESH_FIELDS from plugins

### ISSUE THREAD

**Issue by arsaboo** [beetbox/beets#4788]
@JOJ0 looks like there are still some issues with reimports. 

I am reimporting with [youtube](https://github.com/arsaboo/beets-youtube) and here are the relevant logs:

```
Reimported album 1. Preserving attribute ['added']. Path: /home/arsaboo/shared/music/Tu Jhoothi Main Makkaar (2023)
Reimported album 1. Preserving flexible attributes ['data_source']. Path: /home/arsaboo/shared/music/Tu Jhoothi Main Makkaar (2023)
Reimported item 1. Preserving attribute ['added']. Path: /home/arsaboo/shared/music/Tu Jhoothi Main Makkaar (2023)/Tu Jhoothi Main Makkaar (2023) - Jaadui.mp3
Reimported item 1. Preserving flexible attributes ['data_source', 'yt_album_id', 'yt_artist_id', 'yt_track_id', 'track_alt', 'cover_art_url', 'yt_updated', 'yt_views', 'spotify_album_id', 'spotify_artist_id', 'spotify_track_id', 'jiosaavn_album_id', 'jiosaavn_artist_id', 'jiosaavn_perma_url', 'jiosaavn_track_id', 'jiosaavn_updated', 'danceability', 'beats_count', 'average_loudness', 'danceable', 'gender', 'is_male', 'is_female', 'genre_rosamerica', 'voice_instrumental', 'is_voice', 'is_instrumental', 'mood_acoustic', 'mood_aggressive', 'mood_electronic', 'mood_happy', 'mood_sad', 'mood_party', 'mood_relaxed', 'mood_mirex', 'mood_mirex_cluster_1', 'mood_mirex_cluster_2', 'mood_mirex_cluster_3', 'mood_mirex_cluster_4', 'mood_mirex_cluster_5', 'spotify_track_popularity', 'spotify_danceability', 'spotify_energy', 'spotify_key', 'spotify_loudness', 'spotify_mode', 'spotify_speechiness', 'spotify_acousticness', 'spotify_instrumentalness', 'spotify_liveness', 'spotify_valence', 'spotify_tempo', 'spotify_time_signature', 'spotify_updated']. Path: /home/arsaboo/shared/music/Tu Jhoothi Main Makkaar (2023)/Tu Jhoothi Main Makkaar (2023) - Jaadui.mp3
Sending event: database_change
```

Some of the `yt_*` fields should not be preserved. Specially, `yt_album_id`, `yt_artist_id`, `yt_track_id`, `yt_updated`, `yt_views`, and (maybe even) `cover_art_url`. As a default, `cover_art_url` should be overwritten on reimport (plugins can add a config option to prevent overwriting `cover_art_url`).

**Comment by JOJ0** [comment]
Hmm I'd say this is a feature request. yt we could add to the REIMPORT_FRESH_... module level constants (importer.py). Not sure about cover_art_url. Will think about it but sounds like it would make sense too.

**Comment by JOJ0** [comment]
Sorry for being brief yesterday. Please add to these lists: https://github.com/beetbox/beets/blob/8fc3ddee2702d0612c5340700f876d78c3e06bbc/beets/importer.py#L53

**Comment by arsaboo** [comment]
Is this something a plugin can modify or will it require changes to the beets repo? 

As an approach, shouldn't reimports overwrite plugin-specific information?

**Comment by JOJ0** [comment]
not sure. for now requires edit of beets repo.

**Comment by sampsyo** [comment]
Looks tricky! The obvious solution here would be to introduce a new plugin hook to register these non-preserved fields. That would be a little clunky to use, but it would work. I wonder if there is some more elegant way to approach this, such as somehow using a special prefix on the field name…

**Comment by arsaboo** [comment]
This will definitely have to be resolved. I am seeing this with another (Tidal) plugin:

```bash
Reimported item 144. Preserving attribute ['added']. Path: /home/arsaboo/shared/music/XYZ (2021)/XYZ (2021) - Thode Kam Ajnabi.mp3
Reimported item 144. Preserving flexible attributes ['data_source', 'tidal_album_id', 'tidal_artist_id', 'tidal_alb_popularity', 'tidal_track_popularity', 'explicit', 'cover_art_url', 'tidal_updated', 'tidal_track_id', 'jiosaavn_album_id', 'jiosaavn_artist_id', 'jiosaavn_perma_url', 'jiosaavn_track_id', 'jiosaavn_updated', 'plex_guid', 'plex_ratingkey', 'plex_userrating', 'plex_skipcount', 'plex_viewcount', 'plex_lastviewedat', 'plex_lastratedat', 'plex_updated', 'spotify_updated']. Path: /home/arsaboo/shared/music/XYZ (2021)/XYZ (2021) - Thode Kam Ajnabi.mp3
```
I would even raise this issue to a critical level.

**Comment by arsaboo** [comment]
> Please add to these lists:
> 
> https://github.com/beetbox/beets/blob/8fc3ddee2702d0612c5340700f876d78c3e06bbc/beets/importer.py#L53

@JOJ0 can we make this list configurable?

**Comment by arsaboo** [comment]
Actually, I am trying to now recall why should any field be preserved on reimport. 

Any plugin should be able to rewrite their respective fields. The only restriction should be preventing cross-plugin writes, i.e., the Spotify plugin should not overwrite MusicBrainz fields.

**Comment by JOJ0** [comment]
Actually I think this approach is quite elegant already for my taste. How could we make sure thst knowledge is not buried in this thread? Maybe add a new chapter to the developer's docs? 

Or maybe bring in this feature into one source plugin that comes boxed with beets in a PR?

**Comment by arsaboo** [comment]
Thanks @JOJ0. How about we update the comment here to add that information and maybe even update the spotify code to add an example?
https://github.com/beetbox/beets/blob/8fc3ddee2702d0612c5340700f876d78c3e06bbc/beets/importer.py#L53

**Comment by JOJ0** [comment]
> Thanks @JOJ0. How about we update the comment here to add that information and maybe even update the spotify code to add an example?
> 
> https://github.com/beetbox/beets/blob/8fc3ddee2702d0612c5340700f876d78c3e06bbc/beets/importer.py#L53

Yeah good idea to elaborate on that comment!

Dont forget that spotify_album_id can be updated from MusicBrainz and needs to stay in this list even though someone hasnt activated spotify plug.

**Comment by arsaboo** [comment]
@JOJ0 see #4812
