### ISSUE TITLE
Add option to choose which option we want to use when using quiet

### ISSUE THREAD

**Issue by Sakooooo** [beetbox/beets#4793]
### Proposed solution
Add a config option that is set to none by default that lets us choose which option we want beets to automatically use instead of skipping/importing as is with `--quiet`

### Objective
Make automatic importing work no matter what

#### Goals
Make automatic jobs work better alongside beets (crontab)

#### Non-goals
Autotagger can replace picard in a self-hosted environment
Automatically merge songs from the same album

#### Anti-goals
Wrong metadata

**Comment by sampsyo** [comment]
You may be looking for `quiet_fallback`:
https://beets.readthedocs.io/en/stable/reference/config.html#quiet-fallback

**Comment by Sakooooo** [comment]
yeah something like that but i would like an extra option where it just uses the first option that it finds via musicbrainz and starts applying/merging the tags with my library if possible

**Comment by sampsyo** [comment]
Please give it a try! `quiet_fallback: skip` does something very much like this.

**Comment by Sakooooo** [comment]
> Please give it a try! `quiet_fallback: skip` does something very much like this.

alright will do cause last time i tried it just kept skipping and not importing

**Comment by Sakooooo** [comment]
i left my server on and beets imported the file correctly and now it is showing, thanks!
