### ISSUE TITLE
Fetchart uses incorrect field for spotify_album_id

### ISSUE THREAD

**Issue by arsaboo** [beetbox/beets#4803]
Fetchart currently uses `album.mb_albumid` to get `spotify_album_id`. This assumes `mb_albumid` has the `spotify_album_id`, which may be the case after the initial import with Spotify. However, `mb_albumid` can be overwritten with a valid `mb_albumid`, which will result in an error. 

We should be using `spotify_album_id` instead, which will always have the right value.

**Comment by sampsyo** [comment]
Hi! Let's fold this into #604 and discuss it there. The one thing that makes this tricky is that deduplication is hard-coded to use the MBID field:
https://github.com/beetbox/beets/blob/430a75d1ad0347913497cdb24f1e68ae146c5248/beets/autotag/match.py#L408-L410

Therefore, if there are multiple matches that are _missing_ an ID, they will be considered duplicates of each other. We clearly need a way to identify duplicate matches of the same album (or track) in a source-scoped manner.
