### ISSUE TITLE
auto_keep broken by playlist feature

### ISSUE THREAD

**Issue by night199uk** [beetbox/beets#4824]
the quick n dirty playlist feature in this commit:
https://github.com/beetbox/beets/commit/861bc69df55cb3d4d20da6082878542ff42d85d8
broken auto_keep:

https://github.com/beetbox/beets/blob/79435c3b6f682d30cac169c97f978491dfd8f80d/beetsplug/convert.py#L204
When auto_keep is true, then this line fails because _get_opts_and_config was modified to return 8 values (+ playlist) instead of 7 and this check wasn't updated.

**Comment by wisp3rwind** [comment]
@JOJ0 do you happen to have the bandwidth to fix this?

Maybe, if someone were motivated to do some cleanup, it could make sense to refactor this: Instead of using a gigantic tuple, we might set the parsed options as class attributes (unless there's a reason not to do that), or use a dataclass to replace the tuple.

**Comment by JOJ0** [comment]
Thanks for the report and fixing advice already @night199uk 

@wisp3rwind had a minute for a quickfix and submitted a PR.

As for the refactor idea (which I think is great and easy enough): Should we keep this issue open or create a new one to track it? I won't do it anytime soon, currently on short holiday and then....things to do.... :-) Maybe someone else might pick it up?

**Comment by wisp3rwind** [comment]
> As for the refactor idea (which I think is great and easy enough): Should we keep this issue open or create a new one to track it? I won't do it anytime soon, currently on short holiday and then....things to do.... :-) Maybe someone else might pick it up?

Given that this is just a small refactoring, and neither feature nor bug; maybe we don't need an issue for it?
