### ISSUE TITLE
Add warning to docs about linuxserver.io beets install

### ISSUE THREAD

**Issue by RollingStar** [beetbox/beets#4838]
Linuxserver is great, i use them in many places. But their beets install is unmaintained:

https://github.com/linuxserver/docker-beets/issues/94

This causes some confusion and is not part of the 'core' beets config. I think we should note somewhere in the docs that linuxserver may differ from a plain beets install.

https://discourse.beets.io/t/ux-observations-from-new-users-or-youtubers/2229

**Comment by sampsyo** [comment]
Not a bad idea. We have gotten some confused questions here in the past that seem to stem from using the configuration provided by LinuxServer.

**Comment by snejus** [comment]
Their config now seems to be in sync with what we have
