### ISSUE TITLE
Feature Request .m4a

### ISSUE THREAD

**Issue by DuckoDucky** [beetbox/beets#4894]
Hello, A lot of my music is downloaded through NewPipe which downloads youtube videos as the .m4a format, there is no option for .mp3 and I would like to see support added for this file format please and thank you! :)

**Comment by arsaboo** [comment]
You can use the convert option which will automatically convert these files during import. Let me know if you are not able to figure out (on mobile right now).

**Comment by sampsyo** [comment]
AAC (`.m4a`) audio files should be fully supported! Please let us know if you get an error message or whatever when trying to import them.

**Comment by bal-e** [comment]
This should have been marked as stale.  Can we close this now?

**Comment by wisp3rwind** [comment]
> This should have been marked as stale. Can we close this now?

Sounds good!
