### ISSUE TITLE
mediatype and media tags are not available for albums, only for individual tracks

### ISSUE THREAD

**Issue by afontenot** [beetbox/beets#4904]
I have several albums that are near-duplicates except that one in a CD rip, the other a vinyl rip, etc. I'd like to use `aunique` to disambiguate them using the media tag, e.g. `[CD]`, `[Vinyl]`. Unfortunately this isn't possible because beets does not print the media tag when requested for an album, only for individual tracks.

### Problem

Running this command in verbose (`-vv`) mode:

```sh
$ beet -vv ls -a somealbumname -f '$media'
user configuration: /home/user/.config/beets/config.yaml
data directory: /home/user/.config/beets
plugin paths: /home/user/.local/share/beets/plugins
inline: adding item field multidisc
inline: adding album field authorcredit
fetchart: google: Disabling art source due to missing key
fetchart: lastfm: Disabling art source due to missing key
Sending event: pluginload
library database: /home/user/.config/beets/music.blb
library directory: /home/user/music
Sending event: library_opened
$media
$media
Sending event: cli_exit
```

As you can see, beets has printed the literal text `$media` above rather than the contents of the media tag. I don't see this issue if I remove the album matching `-a` argument.

### Setup

* OS: Ubuntu 22.04.3 LTS
* Python version: 3.10.12
* beets version: git cd0f2b1aa3 (1.6.1)
* Turning off plugins made problem go away (yes/no): no

**Comment by arsaboo** [comment]
Use the `inline` plugin to create an `album_fields`. Something like the following should work:

```yaml
album_fields:
    media: 
        for item in items:
            if item.get('media'):
                return f'{item.media}'
```

**Comment by afontenot** [comment]
Thanks @arsaboo, I ended up doing something quite similar, although I check whether all the items in the album agree on the tag for safety. The downside of this is that using a bunch of dynamically defined fields actually slows beets down quite substantially if they need to be run a lot. I actually just rewrote one that was doubling my `beet mv` time.

I think `media` is probably supposed to be an album field. It's strange (and seemingly inconsistent) that beets stores `genre` for whole albums, for example, but not `media`. [MusicBrainz shows both for releases.](https://musicbrainz.org/release/4f56bab1-05ef-44fe-9acb-bef8a959cb44)

Also, if I haven't misunderstood what I observed (a very obscure error message), you need to give the album field a different name to avoid a circular reference:

```
album_fields:
    albummedia: 
        for item in items:
            if item.get('media'):
                return f'{item.media}'
```

The lookup for `media` on each item appears to try to fall back to the album field if it isn't present.

**Comment by sampsyo** [comment]
The problem, FWIW, is that releases can have heterogeneous media. For example, a single release might include both a DVD and a CD.

**Comment by afontenot** [comment]
Good point.

I guess, likewise, there's no guarantee that the album's genre tags correspond to the tags on the tracks. I think I'm going to close this since there's no straightforward fix and the workaround is good enough. For future searchers, here's what I'm using to disambiguate:

```yaml
aunique:
    keys: albumartist album year
    disambiguators: albummediatype albummedia label catalognum

album_fields:
    albummediatype: |
        m_0 = items[0].get("mediatype")
        if m_0 and all(m_0 == item.get("mediatype") for item in items[1:]):
            return m_0
        return ""
    albummedia: |
        m_0 = items[0].get("media")
        if m_0 and all(m_0 == item.get("media") for item in items[1:]):
            return m_0
        return ""
```

The album part of my `path` looks like `$album ($year)%aunique{}`.
