### ISSUE TITLE
When an album is split into multiple paths, only the first path gets album art

### ISSUE THREAD

**Issue by afontenot** [beetbox/beets#4908]
If you use the [configuration recommended by the documentation](https://beets.readthedocs.io/en/stable/faq.html#create-disc-n-directories-for-multi-disc-albums) for creating individual disc directories for multi-disc albums, along with the fetchart plugin, only the first directory (e.g. "Disc 01") will get album art.

Even more frustrating, if you have your files in multiple disc folders to begin with, each with its own album art, fetchart will only take the art from the first directory, and leave behind the others. This means that even with `move: yes` in your configuration, the leftover files will remain and you then have to clean up the imported directories manually.

I think you could make a case that the correct behavior is to put the art in the album folder instead of duplicating it in the disc folders (although I don't know how media players handle this), but putting it in only *one* of several disc folders seems clearly incorrect. It would be nice to hard link it if possible.

### Problem

Starting from a fresh beets installation with a configuration like that shown below, import an album with multiple discs. [I am testing with this album, already tagged using beets on my real installation.](https://musicbrainz.org/release/2be9c4ac-2246-4073-bc20-acc9272332a2)

```
$ beet import Rework/
```

Observe the result:

```
$ tree music.test/Philip\ Glass/
music.test/Philip Glass/
└── Rework
    ├── Disc 01
    │   ├── 01 - Music in Twelve Parts, Part 1.flac
    │   ├── 02 - Rubric (remix).flac
    │   ├── 03 - Knee 1 (remix).flac
    │   ├── 04 - Alight Spiral Snip.flac
    │   ├── 05 - Warda's Whorehouse (Inside Out version).flac
    │   ├── 06 - Etoile Polaire_ Little Dipper.flac
    │   ├── 07 - Floe ('87 remix).flac
    │   ├── 08 - Opening From Glassworks.flac
    │   └── cover.jpg
    └── Disc 02
        ├── 09 - NYC_ 73-78.flac
        ├── 10 - Protest (remix).flac
        ├── 11 - Mad Rush (organ remix).flac
        └── 12 - Island (remix).flac
```

Observe the original imported file tree:

```
$ tree Rework/
Rework/
└── Disc 02
    └── folder.jpg

1 directory, 1 file
```

As you can see, the existing album art has been left behind.

### Setup

* OS: Ubuntu 22.04.3 LTS
* Python version: Python 3.10.12
* beets version: cd0f2b1aa38f0e488f9528a90729493b98f3563e (git)
* Turning off plugins made problem go away (yes/no): n/a

My configuration (raw config file) is:

```yaml
directory: ~/music.test
library: ~/.config/beets/music.blb

plugins: inline fetchart

import:
    move: true

paths:
    default: $albumartist/$album%aunique{}/%if{$multidisc,Disc $disc/}$track - $title

item_fields:
    multidisc: 1 if disctotal > 1 else 0
```

**Comment by sampsyo** [comment]
Indeed; this is a frustrating situation. Please see #231 for an earlier thread on exactly this issue.

**Comment by afontenot** [comment]
Sorry! I searched the issues but failed to find that one for some reason.
