### ISSUE TITLE
Bug in new UI when multiple mediums are in one release

### ISSUE THREAD

**Issue by JOJ0** [beetbox/beets#4947]
Possible bug in this function when multiple mediums are in one release: https://github.com/beetbox/beets/pull/3721/files#r1328227367

Update: I copied over @RollingStar 's initial report of this issue as it was here: _https://github.com/beetbox/beets/pull/3721#issuecomment-1722714076_

### Orignal report

Possible bug in mixed-medium releases (ex. 1 CD and 1 vinyl record)

https://github.com/beetbox/beets/pull/3721/files#r1328227367

Most logical fix might be "2xMedia" or "2xMixed". Keeping the new UI short horizontally is a goal.

https://musicbrainz.org/release/581db767-5221-424b-b6a0-d5db2ff707a1

![image](https://github.com/beetbox/beets/assets/4810902/35baab09-8848-4753-bc64-4482ebda7bf4)

**Comment by RollingStar** [comment]
https://github.com/beetbox/beets/pull/3721#issuecomment-1722714076

**Comment by InvisibleFunction** [comment]
I think I'm also running into this issue trying to import Hybrid SACDs.

Examples here: https://github.com/beetbox/beets/discussions/4976

**Comment by JOJ0** [comment]
> Possible bug in this function when multiple mediums are in one release: https://github.com/beetbox/beets/pull/3721/files#r1328227367

The lines of code referenced, here in detail:

https://github.com/beetbox/beets/pull/3721/files#diff-e324b20657a7d6b43b8b7aeb5754b96774f5062294b5ba7f1e3062845e9e7044R432-R443

**Comment by JOJ0** [comment]
> > Possible bug in this function when multiple mediums are in one release: https://github.com/beetbox/beets/pull/3721/files#r1328227367
> 
> The lines of code referenced, here in detail and In their current state, as of writing:
> 
> https://github.com/beetbox/beets/blob/f984749cc638632c10ab9fc1bfe683c6f3bebaf6/beets/ui/commands.py#L450-L461

which brings me to the conclusion: This is not the function where the line in the screenshot above is produced.

The think in the screenshot comes from the `disambig_string()` which is this one: 

https://github.com/beetbox/beets/blob/f984749cc638632c10ab9fc1bfe683c6f3bebaf6/beets/ui/commands.py#L198-L210

**Comment by JOJ0** [comment]
> I think I'm also running into this issue trying to import Hybrid SACDs.
> 
> Examples here: #4976

I've not entirely made it through your report over there. Just want to mention that up to now I was assuming that this exact issue here, is only cosmetical and has nothing to do with the matching process per-se.

I could be wrong but please double check my assumption! :-)

**Comment by RollingStar** [comment]
Sorry I had the wrong function listed. I didn't debug the function so it was just a guess based on some searches.

**Comment by JOJ0** [comment]
No worries at all! I learned something new. The function you mentioned is in fact the one that does the headlins like for example

* CD1

:-)

**Comment by InvisibleFunction** [comment]
Is the issue here?

https://github.com/beetbox/beets/blob/3548e353602b47d1dca5e1a0063d27f0b5ad3736/beets/autotag/mb.py#L598

It looks like it just grabs the format of the first medium and uses that for everything.

**Comment by InvisibleFunction** [comment]
I think this is closed now.
