### ISSUE TITLE
Echo Nest genres

### ISSUE THREAD

**Issue by sampsyo** [beetbox/beets#495]
The echonest plugin should (optionally) take advantage of the API's new [genre catalog](http://developer.echonest.com/docs/v4/genre.html) to fetch genres for each album or track. See the [blog post](http://blog.echonest.com/post/73516217273/the-future-of-music-genres-is-here) for background. This could yield more predictable results than lastgenre.

**Comment by pprkut** [comment]
In light of #1920, is this still worth pursuing (albeit with the Spotify API instead of echonest)?

**Comment by sampsyo** [comment]
Probably not. 😒  Too bad about Echo Nest!
