### ISSUE TITLE
Expose import.incremental_skip_later config option as CLI option

### ISSUE THREAD

**Issue by mgoltzsche** [beetbox/beets#4958]
To reduce the time needed for manual prompting during the import of a large number of tracks and to import as much as possible without prompting, I run the import once with the `-i --quiet` options and the `import.incremental_skip_later` config option enabled and then again without the `--quiet` option and `import.incremental_skip_later` disabled within the configuration, letting beets prompt for the previously skipped tracks only.
However, currently that requires me to change the configuration file during the workflow which I'd like to avoid.

### Proposed solution

In addition to the configuration file the  `import.incremental_skip_later` option should be configurable via the CLI as e.g. `--incremental-skip-later` option of the `import` command.

Usage example:
```sh
beet import -siq --incremental-skip-later # no questions asked, tracks skipped in doubt
beet import -si                           # prompting for previously skipped tracks only
```

#### Goals

Improving the import workflow / making the import command more flexible.

#### Non-goals

Changing the import behaviour internally.

#### Anti-goals

Any additional complexity or more prompts. :smile:

**Comment by JOJ0** [comment]
That shouldnt be too hard to implement. If you code Python and submit a PR I can review and assist 😀

**Comment by mgoltzsche** [comment]
@JOJ0 I created PR #5022 to address this issue.

**Comment by mgoltzsche** [comment]
FYI (for others wondering about this as well) I realized that using `--move` instead of incremental imports with the `incremental_skip_later` option is a good alternative in many cases.

**Comment by JOJ0** [comment]
Too late for the game but two things:

I like laying out more options as cli options @mgoltzsche, thanks!

Do we have an easy way with current cli framework to have aliases for options? I do like --record-something since I always found incremental-skip-later super confusing🤣

**Comment by sampsyo** [comment]
Totally happy to support changing the CLI option name in a separate PR if you have a good idea for it! As @Serene-Arc notes, we should probably be circumspect about changing the config option (at least without a backwards-compatibility shim), but a better selection for the CLI option seems easier to support, even if it doesn't perfectly match the config option name.

**Comment by mgoltzsche** [comment]
> Do we have an easy way with current cli framework to have aliases for options?

FWIW you can let two CLI options write the same `dest` key (which is already happening regularly for the `--noX` options).
