### ISSUE TITLE
Can't find library, space in drive is taken up but files are nowhere.

### ISSUE THREAD

**Issue by anischenk0** [beetbox/beets#4979]
### Discussed in https://github.com/beetbox/beets/discussions/4977

<div type='discussions-op-text'>

<sup>Originally posted by **anischenk0** October 26, 2023</sup>
Hello! Sorry about asking stuff here, not sure if it's the right place, but I just ran beets, and now my main partition (which is not where I wanted my stuff!) is about 40 gigs short and the files are nowhere to be found. Could you please help me? My conf file (~/.config/beets) goes:

` directory: /big/Music/sorted` 
` library: /big/Music` 
` import:` 
`  move: yes` 
` replace:` 
` '[\\/]': _` 
` '^\.': _` 
` '[\x00-\x1f]': _` 
` '[<>:"\?\*\|]': _` 
` '\.$': _` 
 ` '\s+$': ''` 
  ` '^\s+': ''` 
 ` '^-': _` 
` asciify_paths: yes ` 

Nothing is to be found in any of the directories specified. I ran "sudo beet import /big/Music/unroot", which is where most stuff is. I only tried '$ beet move' afterwards, which outputs:

`configuration error: /home/w/.config/beets/config.yaml could not be read: mapping values are not allowed here
  in "/home/w/.config/beets/config.yaml", line 7, column 10
`
Thanks! </div>

**Comment by arsaboo** [comment]
Your config file has an error that needs to be fixed. Here's the `replace` section in my config:
```yaml
replace:
    '^\.': _
    '[\x00-\x1f]': _
    '[<>:"\?\*\|]': ''
    '[\xE8-\xEB]': e
    '[\xEC-\xEF]': i
    '[\xE2-\xE6]': a
    '[\xF2-\xF6]': o
    '[\xF8]': o
    '\.$': _
    '\s+$': ''
```
When you use the `sudo beet move`, it uses a different config file and not the one you shared. `sudo beet config --path` will show the path of the config file used. 

I don't think the files are lost. Here are two things you can try:
1. use `find` to locate the file. 
2. move a test file using the verbose flag: `sudo beet -v import /big/Music/unroot`. The logs will indicate where the files are moved.

**Comment by anischenk0** [comment]
Ahhh, thanks. They were being put in /root/, which confused me and also was a protected folder so I couldn't access it from thunar. 

> Your config file has an error that needs to be fixed. Here's the `replace` section in my config:
> 
> ```yaml
> replace:
>     '^\.': _
>     '[\x00-\x1f]': _
>     '[<>:"\?\*\|]': ''
>     '[\xE8-\xEB]': e
>     '[\xEC-\xEF]': i
>     '[\xE2-\xE6]': a
>     '[\xF2-\xF6]': o
>     '[\xF8]': o
>     '\.$': _
>     '\s+$': ''
> ```
> 
> When you use the `sudo beet move`, it uses a different config file and not the one you shared. `sudo beet config --path` will show the path of the config file used.
> 
> I don't think the files are lost. Here are two things you can try:
> 
>     1. use `find` to locate the file.
> 
>     2. move a test file using the verbose flag: `sudo beet -v import /big/Music/unroot`. The logs will indicate where the files are moved.
