### ISSUE TITLE
Support writing ISRC to tracks in Spotify plugin

### ISSUE THREAD

**Issue by JOJ0** [beetbox/beets#4992]
Support ISRC track field in Spotify plugin.

The difficulty is that we currently if I'm not mistaken, only get a "Simplified Track Object" track object from Spotify while fetching album info: https://developer.spotify.com/documentation/web-api/reference/get-an-album -> look for this in the docs:

![Screenshot 2023-11-10 at 09 48 10](https://github.com/beetbox/beets/assets/2733783/e9a8fceb-3c84-41c3-b87d-0c6e1b15da12)

I wanted to instantly open a PR to just add external_ids.isrc to the plugin but it's just not there in the response we currently get from the albums endpoint. We would need an additional request to this endpoint to get it: https://developer.spotify.com/documentation/web-api/reference/get-track

Because we need this data:

![Screenshot 2023-11-10 at 09 51 16](https://github.com/beetbox/beets/assets/2733783/cd1ee3bd-7016-432e-9956-6db31eba12b6)

There might be a better way, maybe asking the albums endpoint to include that field. Not sure if that's possible.

**Comment by JOJ0** [comment]
@arsaboo help me out: Where would you see this additional fetch in the code? I'm unsure if I want to get my hands dirty on that plugin yet :-) Maybe you are quicker ;-)

**Comment by JOJ0** [comment]
FYI MusicBrainz often contains this info as well and beets fetches is as well and writes it to tracks. Also the Deezer plugin fetches it, it's easier I guess there since it is included with the response we get already: https://github.com/beetbox/beets/blob/708a04d4a88eb955f261a21f0b1146c9e2ae0a55/beetsplug/deezer.py#L165C21-L165C21

**Comment by arsaboo** [comment]
@JOJ0 created a PR #4996 to update the ISRC field if available (note that not all albums return the ISRC field).
