### ISSUE TITLE
CD + other disc type shows as 2xCD

### ISSUE THREAD

**Issue by emiham** [beetbox/beets#5011]
### Problem

When importing an album that has discs of different types ([for example this release](https://beta.musicbrainz.org/release/e9fe1ca3-3ac5-486a-b745-ee8c2f3bb4bf)), they are shown as the same type in beets. Very nitpicky, but I was genuinely confused about this for a bit, so I think newer users could have a bigger issue with it. 

Example output:
```
  Match (83.3%):
  ClariS - BIRTHDAY
  ≠ id, unmatched tracks, media, albumdisambig, catalognum
  MusicBrainz, 2xCD, 2012, JP, SME Records, SECL-1115, 期間生産限定盤
  https://musicbrainz.org/release/e9fe1ca3-3ac5-486a-b745-ee8c2f3bb4bf
```

What I would expect:
```
  Match (83.3%):
  ClariS - BIRTHDAY
  ≠ id, unmatched tracks, media, albumdisambig, catalognum
  MusicBrainz, CD+DVD, 2012, JP, SME Records, SECL-1115, 期間生産限定盤
  https://musicbrainz.org/release/e9fe1ca3-3ac5-486a-b745-ee8c2f3bb4bf
```

### Setup

* OS: Arch Linux
* Python/beets versions: 
```
beets version 1.6.1
Python version 3.11.6
plugins: badfiles, chroma, copyartifacts, embedart, fetchart, inline, lyrics, mbsubmit, mbsync, missing, mpdupdate, thumbnails, types, unimported
```
* Turning off plugins made problem go away (yes/no): no

**Comment by JOJ0** [comment]
Duplicate of https://github.com/beetbox/beets/issues/4947

**Comment by emiham** [comment]
I missed that in my search, thank you!
