### ISSUE TITLE
Lyrics plugin adds all the sources even when not configured

### ISSUE THREAD

**Issue by arsaboo** [beetbox/beets#5040]
I was trying to limit the `lyrics` plugin to use only `lrclib`, but this does not work. It looks like the plugin automatically enables all the sources and ignores the sources configured in the config. 

Here's my config:
```yaml
lyrics:
  auto: no
  souces: lrclib 
  force: no
  synced: yes
```

Here are the debug logs (note that Genius is still present here):

```bash
lyrics: Genius failed to find a matching artist for '100RBH'
lyrics: Genius failed to find a matching artist for 'A.R. Rahman, Kavita Krishnamurthy, Shreya Ghoshal, Arman Dehlvi, Gulzar'
```
I think the problem is the following line which adds all the sources:
https://github.com/beetbox/beets/blob/c1a232ec7be13f710fa764d39e13483b093fad9a/beetsplug/lyrics.py#L805

**Comment by DjSlash** [comment]
You spelled 'sources' wrong, missing an **r** there.

**Comment by arsaboo** [comment]
Oh God....this is embarrassing 🙈
