### ISSUE TITLE
Fetch composer name from MusicBrainz

### ISSUE THREAD

**Issue by ryanakca** [beetbox/beets#506]
Please sync the COMPOSER tag from musicbrainz. Since this can be multi-valued, this depends on [issue 505](https://github.com/sampsyo/beets/issues/505), although a good first start would be just to retrieve the first composer listed on MB. For an example of the composer relationship on MB, see for example [this release](http://musicbrainz.org/release/b1d71e3e-cbf1-4ef3-94b3-19cbb1e6de62).

**Comment by sampsyo** [comment]
We now fetch the composer. For future work on including multiple values, let's use #505.
