### ISSUE TITLE
Please cut a new release of Beets

### ISSUE THREAD

**Issue by NHOrus** [beetbox/beets#5161]
Some distributions package only current release of software. Last release of beets in Gentoo, for example, is 1.6.0, with some local patches.

There are a lot of changes and updates to beets since 2021, please tag a new version?

**Comment by arsaboo** [comment]
See discussion [here](https://github.com/beetbox/beets/discussions/4501) and follow the relevant PR [here](https://github.com/beetbox/beets/pull/4952).
