### ISSUE TITLE
Provide command to list all flexible attributes

### ISSUE THREAD

**Issue by dfc** [beetbox/beets#544]
beets should provide a command to list extended attributes. In a perfect world this would isssue would be resolved with two new features:

A command to list ALL extended attributes that beets knows about:

    $ beet xattr 
    ....
    Long list of known extended attributes
    ...
    $ 
    
A command to list extended attributes for a given query (similar to list)

    $ beet listxattr "Your Awesome beets search string"

This could print the names, the values or the names and values. I do not have a real opinion here. I guess the best case is default to names and values and have a switch for just the names.

**Comment by GuilhermeHideki** [comment]
could `beet fields` use some flag to include flexible attributes with some SQL like `select distinct key from item/album_attributes` in the first case?

**Comment by sampsyo** [comment]
Yep, something exactly like that, @GuilhermeHideki.

**Comment by GuilhermeHideki** [comment]
the ``beet xattr`` idea is implemented with ``beet fields`` and the ``beet listxattr query`` with ``beet info query``.
