### ISSUE TITLE
Test fails on OpenBSD at 2.2.0: `fixture 'client' not found`

### ISSUE THREAD

**Issue by catap** [beetbox/beets#5526]
### Problem

```
_______________ ERROR at setup of TestAuraResponse.test_artists ________________
file /build/pobj/beets-2.2.0/beets-2.2.0/test/plugins/test_aura.py, line 139
      def test_artists(
file /build/pobj/beets-2.2.0/beets-2.2.0/test/plugins/test_aura.py, line 57
      @pytest.fixture
      def get_response_data(self, client: Client, item):
E       fixture 'client' not found
>       available fixtures: _other_album_and_item, album, album_document, anyio_backend, anyio_backend_name, anyio_backend_options, app, artist_document, cache, capfd, capfdbinary, caplog, capsys, capsysbinary, cov, doctest_namespace, get_response_data, helper, item, monkeypatch, no_cover, pytestconfig, record_property, record_testsuite_property, record_xml_attribute, recwarn, tmp_path, tmp_path_factory, tmpdir, tmpdir_factory, track_document
>       use 'pytest --fixtures [testpath]' for help on them.

/build/pobj/beets-2.2.0/beets-2.2.0/test/plugins/test_aura.py:57
________________ ERROR at setup of TestAuraResponse.test_albums ________________
file /build/pobj/beets-2.2.0/beets-2.2.0/test/plugins/test_aura.py, line 148
      def test_albums(
file /build/pobj/beets-2.2.0/beets-2.2.0/test/plugins/test_aura.py, line 57
      @pytest.fixture
      def get_response_data(self, client: Client, item):
E       fixture 'client' not found
>       available fixtures: _other_album_and_item, album, album_document, anyio_backend, anyio_backend_name, anyio_backend_options, app, artist_document, cache, capfd, capfdbinary, caplog, capsys, capsysbinary, cov, doctest_namespace, get_response_data, helper, item, monkeypatch, no_cover, pytestconfig, record_property, record_testsuite_property, record_xml_attribute, recwarn, tmp_path, tmp_path_factory, tmpdir, tmpdir_factory, track_document
>       use 'pytest --fixtures [testpath]' for help on them.
```

### Setup

* OS: OpenBSD-current
* Python version: 3.11.10
* beets version: 2.2.0
* Turning off plugins made problem go away (yes/no): no

**Comment by snejus** [comment]
How are you running the tests?

**Comment by snejus** [comment]
I suspect this issue is coming up because `pytest` does not know where's the testing directory at: try

```fish
pytest --rootpath /build/pobj/beets-2.2.0
```

**Comment by catap** [comment]
> I suspect this issue is coming up because `pytest` does not know where's the testing directory at: try providing the `--rootpath` argument with package root
> 
> ```fish
> pytest --rootpath /build/pobj/beets-2.2.0
> ```

It has correct rootpath already, without it, not test discovered.
```
============================= test session starts ==============================
platform openbsd7 -- Python 3.11.10, pytest-8.2.0, pluggy-1.5.0
rootdir: /build/pobj/beets-2.2.0/beets-2.2.0
configfile: pyproject.toml
plugins: anyio-3.7.1, cov-6.0.0
collected 1798 items / 1 skipped
```

Also, it had pick a lot of fixtures...

**Comment by snejus** [comment]
I see what's going on - testing dependencies are missing (in this case it's `pytest-flask`).

How did you use to install testing dependencies before we introduced poetry?

**Comment by catap** [comment]
@snejus like this: https://github.com/openbsd/ports/blob/master/audio/beets/Makefile#L38-L47

Here no `pytest-flask` on OpenBSD ports.

I'll try to add it and re-test but I have no idea when.

**Comment by snejus** [comment]
Just checked the previous package - I can now see that _plugin_ tests had not previously been included in the sdist. Only the tests in the root `test` folder were included.

**Comment by catap** [comment]
@snejus when it explains everything. Thanks!

**Comment by snejus** [comment]
I will exclude the plugin tests - ultimately your concern is to make sure that base `beets` version passes tests, so it does not make sense to force you to test plugins.

**Comment by catap** [comment]
@snejus I think the current way better, special if it means to add one more dependency for tests which can be useful on other ports.

So, no need to exclude anything, I guess.

**Comment by snejus** [comment]
For now, I think, we will mirror the same configuration like we had before. If someone comes across wanting plugin tests to be included, then we can try to hack something there since it's slightly more complicated than just a single dependency. Some of the plugin tests depend on certain system packages being present, for example.

**Comment by catap** [comment]
make sense.

**Comment by eli-schwartz** [comment]
> For now, I think, we will mirror the same configuration like we had before. If someone comes across wanting plugin tests to be included, then we can try to hack something there since it's slightly more complicated than just a single dependency. Some of the plugin tests depend on certain system packages being present, for example.

You can use markers to let people select which tests they want to run, and/or raise skips for missing dependencies.
