### ISSUE TITLE
[Release Process]: Please implement a tag and release workflow and have it fail early if the version is wrong

### ISSUE THREAD

**Issue by Kangie** [beetbox/beets#5539]
The version number did not get an update before being tagged as 2.2.0:

https://github.com/beetbox/beets/blob/01f1fafc888457a440a22a41320f02e9014e07c4/pyproject.toml#L3

Since #5531 means that the PyPi tarball is unsuitable for me as a dowstream I've had to resort to `sed`ing pyproject.toml (etc).

### Proposed solution

Please come up with a solution that produces usable GitHub release artefacts.

**Comment by snejus** [comment]
This is weird, didn't realize I thought I addressed this issue with `2.1.0` release, but it seems like it's occurring again. Will get this fixed asap.

**Comment by snejus** [comment]
Could you confirm that moving the tag to the correct commit would fix your issue?

**Comment by Kangie** [comment]
> Could you confirm that moving the tag to the correct commit would fix your issue?

I've worked around it downstream using `sed` - It's more making sure that a future release can't go ahead if the version and tag aren't in alignment to catch this in future :)

**Comment by snejus** [comment]
This makes sense. If you have time, feel free to have a look at [the PR](https://github.com/beetbox/beets/pull/5536) that fixes this issue.

**Comment by Serene-Arc** [comment]
This is a weird bug that comes from having the tagging action in the wrong part, which @snejus found and fixed! ~~I introduced it when I made the workflow.~~ It's been an issue for the last few releases and we usually fix it manually. Hopefully this means that it won't be an issue in the future.
