### ISSUE TITLE
Python 3.4 standard library modules

### ISSUE THREAD

**Issue by sampsyo** [beetbox/beets#621]
[Python 3.4](https://www.python.org/download/releases/3.4.0/) is out! Even though beets is not on py3k yet, there are a few implications for us. This is a meta-bug to discuss the new standard library modules in 3.4 and how beets could benefit.
- There's a new enum module with a [backport](https://pypi.python.org/pypi/enum34). We should take a dependency on this instead of using my aging hand-rolled implementation.
- There's a new asyncio library that is very similar in purpose to Bluelet but better-maintained. There is a backport called [trollius](https://pypi.python.org/pypi/trollius).
- More ambitiously, [pathlib](http://docs.python.org/3.4/library/pathlib.html) could help us get rid of a _lot_ of hand-rolled code for handling cross-platform paths and filenames. We could more the whole codebase to use path objects in place of bytestrings.

Contributions are welcome in any category!

**Comment by brunal** [comment]
The pathlib backport now works on python 2.6 (since version 1.0.1). See [the changelog](https://pypi.python.org/pypi/pathlib/)

**Comment by arcresu** [comment]
The enum part was handled in #642, pathlib is covered by #1409, and I've now split the bluelet part into #3246. I think that takes care of everything here so I'll close this and let the discussion continue in those focused issues :)
