### ISSUE TITLE
Use underscores instead of spaces

### ISSUE THREAD

**Issue by rafi** [beetbox/beets#623]
I don't like spaces in my directory & file names. Is there a way to use the underscore character instead of spaces?

**Comment by Vrihub** [comment]
+1 For putting this advice in the documentation, maybe in /reference/config.html#replace (or in the FAQ).
It took me a while to find the solution! :)

Even better would be a new configuration option (à la `asciify_paths`) to automatically convert all spaces in underscores in paths.

**Comment by Vrihub** [comment]
Oh, BTW, before finding this solution, I also tried this:

`paths:
    default: $albumartist/$year_$album/$track_$title
`
(i.e. I'd like to have an underscore as separator between year and album, and between track and title)

but  beets would create the path using the `$year` and `$track` strings literally, so putting underscores in the paths definitions seems to cause some trouble, maybe this is bug?

**Comment by sampsyo** [comment]
@Vrihub Good idea! Any chance you could add something to the FAQ?

Our documentation is pretty easy to edit—just switch the "latest" version in the sidebar and then find the "edit on GitHub" link on any page in the docs. Or navigate to `faq.rst` on github.com and hit the edit button.

**Comment by Vrihub** [comment]
> Any chance you could add something to the FAQ?

Er, right now I don't have the time to learn using git(hub) :) but here you are a rst snippet that you can put right after the "...avoid using special characters in my filenames?" FAQ

```
.. _space-underscores:

…use the underscore character instead of space in my directory and file names?
-------------------------------------------------------------------------------

You can use the :ref:`replace` configuration option with the following mapping:

    replace:
        '\s+': _

```

**Comment by sampsyo** [comment]
OK, I'll try to remember to insert this. In the future, though, this is really easy to do on GitHub---just hit the edit button on the appropriate page and it will open a PR for you. It's also really helpful for maintainers because it makes it easier to manage incoming work.
