### ISSUE TITLE
Corrections for apostrophe are wrong

### ISSUE THREAD

**Issue by benlaurie** [beetbox/beets#634]
I'm getting loads of corrections like:
- The Summer Of '91 ->
  The Summer of â91

(on my machine, at least, the replacement is a circumflex, which is 0xe2). Obviously, these are not improvements!

**Comment by catap** [comment]
@benlaurie thanks for your suggestion to start xterm with the right locale. It helps me. Before I discover it, I thought that I drive crazy.

**Comment by catap** [comment]
@sampsyo I've reproduce this issue on the last release with wired behaviour: I can't select anything in import. beets asks me to press button, I do it, but nothing is echoed and when I press Return, it says that I should use one of allowed buttons.
