### ISSUE TITLE
consistent writing & moving options: -wWcCM, import.write, etc.

### ISSUE THREAD

**Issue by tlc** [beetbox/beets#679]
I'd love it if I could configure beets such that nothing but 'write' or 'move' wrote or moved my music files without an explicit command line option.  I can do that for 'import', but I have to remember different command line options for the other commands.

More generally, -WwCcMm could be made consistent across anything that writes or moves files.

* import supports -WwCc, import.write, import.move, import.copy
* modify supports -WwM (and import.write ?), moves by default
* update supports -M, moves by default ('update the db' moves files by default?!)
* mbsync supports -WM and import.write, moves by default
* lyrics supports import.write.  **Does it write one field or everything 'write' would?**
* lastgenre -- no related command line options.  **Will it write the files??  Everything or just the related field?**
* replaygain -- no related command line options.  **Will it write the files??  Everything or just the related fields?**
* ...

**Comment by sampsyo** [comment]
We now do this with a few simple helper functions and standard option sets.
