### ISSUE TITLE
Mark releases with MB type "compilation" as compilations

### ISSUE THREAD

**Issue by flz** [beetbox/beets#725]
I've just imported https://musicbrainz.org/release/2beda690-f988-41f7-a6ed-37e0b34d3db6 and https://musicbrainz.org/release/02c9c809-14d5-430c-b2d3-06f564a849ca and none of those were marked as comp. The artist in MB isn't VA but both are marked as Compilation.

**Comment by Freso** [comment]
The iTunes TCMP/COMPILATION/… tag/flag is unrelated to whether a Release is a compilation though.

A MusicBrainz Release can be an MB:compilation even if only one artist is credited, an iTunes compilation flag can be set on non-MB:compilations if multiple artists appear on the release.

What the iTunes flag is (or was) used for, was to hide artists that only appeared on compilations from the general artist overview (so, say, you only have one Snoop Dogg track in your collection from some compilation, then Snoop Dogg wouldn't appear among the artists in your library).

Thus the technical aspects and criteria for whether something is an MB:compilation or an iTunes compilation are rather different, and one can't be inferred from the other.

**Comment by sampsyo** [comment]
@Freso has a point—let's not do this.
