### ISSUE TITLE
MediaFile: Isolate Mutagen faults when reading fields

### ISSUE THREAD

**Issue by sampsyo** [beetbox/beets#786]
A couple of bug reports have come in over the last few months wherein beets crashes due to an unhandled exception from Mutagen when reading tag fields via MediaFile. [This traceback](https://code.google.com/p/mutagen/issues/detail?id=174), for example, shows a Unicode error being raised inside a `mutagen_file[key]` lookup.

We currently catch and filter Mutagen exceptions in other parts of our interaction with it (e.g., opening and saving files). We should also isolate faults when reading fields to avoid bringing down beets when a bug is exposed. (As an added bonus, this also would let us log the filename of the offending file for better debugging of the underlying failure.)

**Comment by lazka** [comment]
fyi, that particular error is fixed since mutagen 1.25 and I haven't seen similar mutagen bugs reported for a while. Maybe this can be closed.

**Comment by sampsyo** [comment]
Good call; thanks.
