### ISSUE TITLE
echonest: Store Echoprint fingerprints in flexattrs

### ISSUE THREAD

**Issue by LennyBaxter** [beetbox/beets#830]
Echonest fingerprints should be stored in the database like the AcoustID ones are.

**Comment by pprkut** [comment]
With Echonest entering retirement soon (#1920), it's probably best to just close this and consider storing Spotify IDs instead once a plugin for that API takes form.

**Comment by sampsyo** [comment]
Indeed. Thanks for the issue cleanup, @pprkut.
