### ISSUE TITLE
zsh completion

### ISSUE THREAD

**Issue by vapniks** [beetbox/beets#862]
I've written a zsh completion script for beet.
It doesn't handle any plugins yet, but all documented options and arguments are covered.
It's available here: https://github.com/vapniks/zsh-completions/blob/master/src/_beet

**Comment by vapniks** [comment]
I've updated my script as it wasn't working with the smartplaylist plugin. Now it does.
I also added instructions on how to make it run faster.
Its attached to this post.

[beet_zsh-completion.zip](https://github.com/beetbox/beets/files/481571/beet_zsh-completion.zip)

**Comment by sampsyo** [comment]
Cool; thanks! Can you please open a pull request with your changes? Hitting the "edit" button should do it.

**Comment by vapniks** [comment]
OK, done

**Comment by simonbcn** [comment]
To me it doesn't work the method explains in top of `_beet` file to make it faster:
```
# NOTE: it will be very slow the first time you try to complete in a zsh shell (especially if you've enable many plugins)
#       You can make it faster in future by saving the generated completion function: which _beet > _beet2
#       to the top of the file add: #compdef beet
#       to the bottom of the file add: _beet "$@"
#       add this file to your zsh completions directory, and then in your .zshrc file add: compdef _beet2 beet
#       You will need to repeat this proceedure each time you enable new plugins if you want them to complete properly.
```

[`_beet2` file created with that method](http://pastebin.com/kLKiedqh).

I have installed `oh-my-zsh` framework and I have added the line `compdef _beet2 beet` to the final of `.zshrc` file.

But this way the completion for `beets` doesn't work. And without this file, the completion is very slow.

**Comment by vapniks** [comment]
There is a problem with the cacheing method on some systems: https://github.com/beetbox/beets/issues/2266
At some point I will try and fix it but for the moment you will just have to use the normal completion function.

**Comment by vapniks** [comment]
The caching has now been fixed (I hope): https://github.com/beetbox/beets/commit/209d281871e7d86bf60729f2ca25e60b0aaa0e2b

**Comment by JOJ0** [comment]
Not sure if this is related or I should better open a new issue: When using beet commands with global option the completion of e.g paths doesn't work anymore. E.g.:

`beet -v import /path/does/not/complete`

**Comment by JOJ0** [comment]
I opened a separate issue for the path completion problem: https://github.com/beetbox/beets/issues/4285
