### ISSUE TITLE
Exception importing music

### ISSUE THREAD

**Issue by DanielHeath** [beetbox/beets#879]
```
uncaught Mutagen exception in save: 'latin-1' codec can't encode characters in position 0-1: ordinal not in range(256)
error writing /media/sdb5/OrganizedMusic/Files/Non-Album/Sabaton/Nuclear Attack.mp3: Mutagen raised an exception
uncaught Mutagen exception in save: 'latin-1' codec can't encode characters in position 0-1: ordinal not in range(256)
error writing /media/sdb5/OrganizedMusic/Files/Non-Album/Sabaton/Rise of Evil.mp3: Mutagen raised an exception
uncaught Mutagen exception in save: 'latin-1' codec can't encode characters in position 0-1: ordinal not in range(256)
error writing /media/sdb5/OrganizedMusic/Files/Non-Album/Sabaton/We Burn.mp3: Mutagen raised an exception
uncaught Mutagen exception in save: 'latin-1' codec can't encode characters in position 0-1: ordinal not in range(256)
error writing /media/sdb5/OrganizedMusic/Files/Non-Album/Sabaton/Metal Crüe.mp3: Mutagen raised an exception
```

**Comment by jackwilsdon** [comment]
I'm having a similar problem with a couple of songs (except I am converting them, not importing them)

    uncaught Mutagen exception in save: 'latin-1' codec can't encode character u'\u2019' in position 72: ordinal not in range(256)

The character is a [right single quotation mark](http://www.fileformat.info/info/unicode/char/2019/index.htm).

**Comment by sampsyo** [comment]
That's troubling, @jackwilsdon. Could you possibly share a sample file?

**Comment by jackwilsdon** [comment]
I copied the id3 tags from a file to another (royalty free) one for sharing, but did not experience the same issue. After exporting and reimporting the album itself, the issue seems resolved. Even creating a song with a right single quotation mark (`’`) and importing / converting it doesn't seem to cause the issue anymore.

I have no idea what happened to fix this.

**Comment by sampsyo** [comment]
Whoa, weird. Sounds like something lower-level is going on with the tag data format. Do let us know if it comes up again.

**Comment by Joshfindit** [comment]
I just got this:

```
uncaught Mutagen exception in save: 'latin-1' codec can't encode character u'\u2028' in position 6: ordinal not in range(256)
error writing /Volumes/Personal/Shared/Music/beets/Various Artists/Various Artists - 45 — A Tribute To Daniel Hansson_ Free Content [2008]/01 actuel - Sleeping Nagoya.mp3: /Volumes/Personal/Shared/Music/beets/Various Artists/Various Artists - 45 — A Tribute To Daniel Hansson_ Free Content [2008]/01 actuel - Sleeping Nagoya.mp3: 'latin-1' codec can't encode character u'\u2028' in position 6: ordinal not in range(256)
```
I've compressed the file in-place (I have beets configured to copy in to the library, and this is the original), and uploaded it to Dropbox: https://dl.dropboxusercontent.com/u/484200/22%2001%20sleeping%20nagoya.mp3.zip
(This is a CC-licensed track)

For the record, I'd be more than happy to have everything converted to UTF-8 and never see older encodings again.

**Comment by sampsyo** [comment]
Thanks so much, @Joshfindit! This one did it. I found the ID3 COMM frame that was using an older encoding, and tracked down the bug to a place in beets where we weren't updating the encoding to reflect the new data.

Now all strings like this (in comment frames, etc.) should be updated to UTF-8, even if their old encoding was something else.

**Comment by Joshfindit** [comment]
Right on, glad to help track it down, and excited to see UTF-8 across the board :) .
