### ISSUE TITLE
MediaFile: use older text encodings in ID3v2.3 mode

### ISSUE THREAD

**Issue by ruippeixotog** [beetbox/beets#899]
I am trying to create an auto-tagging configuration in which my tags are saved in ID3v2.3 (as 2.4 lacks compatibility with some players I use) and I like the cover art to be embedded in each music file. However, the cover art of the output files is not recognised by OS X 10.9.4 (i.e. in Finder) or iTunes.

Here is a simple configuration with which the problem occurs:

``` yaml
directory: /mnt/data/home/Music

plugins: mbsync fetchart embedart
per_disc_numbering: yes
id3v23: yes

import:
    copy: yes
    write: yes

paths:
    default: $albumartist/$album%aunique{}/$disc-$track $title
```

When I comment the `id3v23: yes` option the covers of the output files are correctly recognised in Mac.

The cover art of the ID3v2.3 output files is recognised in Windows, so it seems a Mac-specific issue. Strangely enough, the input files I used already have ID3v2.3 tags and embedded cover art and are correctly recognised in Mac. Below you have a diff of the ID3v2.3 tags (sorted by name) between an input and an output file taken with `mid3v2`:

``` diff
1c1,2
< APIC= (image/jpeg, 32205 bytes)

---
> APIC= (image/jpeg, 111083 bytes)
> COMM=iTunNORM='eng'= 00001700 00001700 00003981 00003981 00000000 00000000 00008187 00008187 00000000 00000000
3a5,6
> TBPM=0
> TCMP=0
5a9
> TLAN=eng
12a17,19
> TXXX=Album Artist Credit=The Beatles
> TXXX=ALBUMARTISTSORT=Beatles, The
> TXXX=Artist Credit=The Beatles
14a22
> TXXX=MusicBrainz Album Comment=UK mono
17c25
< TXXX=MusicBrainz Album Status=official

---
> TXXX=MusicBrainz Album Status=Official
27a36
> USLT=[unrepresentable data]
```

**Comment by ruippeixotog** [comment]
Hi @sampsyo! Is there any update about this issue? For now I'm applying the hack you mentioned [here](#issuecomment-52378181) every time I update beets, but it would be nice if this had a proper solution.

From what I understood from the discussion a revamp of the architecture would be the most elegant way to do that, but isn't there anything you can do to allow users to manually override the encoding in the configuration for now, even if it seems somewhat strange / specific for this problem?

**Comment by sampsyo** [comment]
Sorry, no update to speak of. Contributions would be very welcome here! (There's no shortcut, alas.)
