### ISSUE TITLE
lastgenre: Remove some bogus 'genres' from whitelist

### ISSUE THREAD

**Issue by gwern** [beetbox/beets#943]
The [lastgenre documentation](http://beets.readthedocs.org/en/v1.3.7/plugins/lastgenre.html) states that

> The plugin chooses genres based on a whitelist, meaning that only certain tags can be considered genres. This way, tags like “my favorite music” or “seen live” won’t be considered genres.

This is a sane approach I agree strongly with. Allowing tags like 'seen live' would be a terrible idea: it tells you little about the musical style or content of the music - pretty much any music can be played live to some degree! Similarly, it would be stupid to allow genre tags like 'CD' or 'DVD' or '8-track tape': those are mediums/sources, not genres.

Unfortunately, in my finished imports, I spotted a few meaningless genre tags, and a read through of my local file `/usr/local/lib/python2.7/dist-packages/beetsplug/lastgenre/genres.txt` leads to a few more:
- "anime music"/"video game music"/"soundtrack": these 3 are chief offenders which exemplify the problem - any kind of music can and does get used in movies/TV-shows/games, from Jpop to symphonic classical music to choral chants to easy listening to techno. All these 3 tell you is something about the medium in which they used, but nothing about the genre, and should be purged with fire.
- ["early music"](https://en.wikipedia.org/wiki/Early_music): I don't know if you could call this a genre at all, when it's defined as negation, any music from before the Baroque (or, almost all of human history and almost all countries throughout the world)
- "essential rock": because we wouldn't want to listen to _in_essential rock, apparently
- "niche": not sure where this comes from, it's not in https://en.wikipedia.org/wiki/List_of_styles_of_music:_N%E2%80%93R but it seems to be a minor synonym for https://en.wikipedia.org/wiki/Bassline_%28music_genre%29 and since it's an adjective which describes most music, better deleted.
- "singer-songwriter": this describes something about the performer, but tells you nothing beyond the fact that it must have vocals in it or else there would be nothing to sing.
- ["background music"](https://en.wikipedia.org/wiki/Background_music): this seems questionable; the WP discussion makes it sound as if music from many genres (Baroque classical is mentioned more than once) count as background music and this is defined by the use not the content, and so is irrelevant to the genre.

(I was irritated to see "beautiful music" and "intelligent dance music" are actual genres. Talk about self-congratulatory.)

So these 8 could be added to the `__init__.py` as a filter on the whitelist to avoid them being stomped during syncs with the Wikipedia pages, or if people might want to add more, be put in a blacklist which overrides the whitelist.

**Comment by ilmc888** [comment]
I just was looking at lastgenre and smartplaylist so I might as well pitch in. My initial use case was to generate playlists for video game music, and identifying other useful lastfm tags I could use.

I kind of agree that "video game music" or "amiga" might not be a genre per se, but it solves my use case atm. Then again, if there is a better solution / source of more information to base my smartplaylists on let me know. Alternatively, as long as the tags of lastfm are available in the beets library (as genre or something else) would be fine for me.
